### ISSUE TITLE
[Feature Request] Actionbars

### ISSUE THREAD

**Issue by Phantasiie** [tukui-org/ElvUI#1003]
**Is your feature request related to a problem? Please describe.**
When swapping between different specs or talent trees, I have to set up like 5 actionbars that I want to always keep the same. and then the rest I change based on what I am playing. 

**Describe the solution you'd like**
I would like to see an option that would allow these actionbars to be set as either persistent across every spec and talent tree or copyable. It could be done with the option to set a 'Default actionbar 5 button layout' and then a 'Copy default actionbar 5 button layout'.  This would allow me to keep things like potions, mounts, toys etc. the same layout across everything and not have to log around classes or talents trees to see what buttons I have where.

**Describe alternatives you've considered**
Taking a screenshot of the default layout that I want to copy is the easiest solution to my problem. It would be convenient to add an option in game if it isn't too difficult to implement and if it makes sense to.

**Additional context**
< Add any other context or screenshots about the feature request here. >

**Comment by Repooc** [comment]
We won't add this.  By default blizzard handles what spells are on what bars based on the talent load out you have loaded, you can change that to shared bars for each load out if you want them all the same.  Azilroka has an addon that you can save spell location for your bars as well as other useful features, it's called ClassTactics
