### ISSUE TITLE
[Retail Bug Report] No Action Bars After 10.1.5 Update

### ISSUE THREAD

**Issue by cemyl95** [tukui-org/ElvUI#1005]
### What is the issue you are having?

Updated ElvUI to the latest version after 10.1.5 released and action bars disappeared.

### What is the expected behavior?

Action bars should be visible

### What actually happened?

I logged in after the patch and all my action bars were missing. I disabled all addons except ElvUI and deleted my WTF folder and the issue persists before and after the setup wizard is complete.

### Suggested Solution/Workaround

None found

### Errors

```shell
None received
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by strinkaj** [comment]
I am having the same issue. Nothing but ELvUI enabled, no action bars

**Comment by ZombieZig** [comment]
Same issue, went through all the basics. Its elvui. Miss my action bars! <3

**Comment by hempton** [comment]
i am also showing a black square box in the upper left corner of the screen. i went through all my addons and it only went away with ElvUI.

**Comment by cemyl95** [comment]
> i am also showing a black square box in the upper left corner of the screen. i went through all my addons and it only went away with ElvUI.

Yeah I saw that as well but forgot to mention it 😂

**Comment by likepies** [comment]
same issue all action bars have vanished, tried reinstall etc. also have black box in top left corner

**Comment by Repooc** [comment]
Update to 13.36
