### ISSUE TITLE
[Feature Request] Use Blizzard's default Micro Bar/Menu

### ISSUE THREAD

**Issue by pesrou** [tukui-org/ElvUI#1007]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
The possibility to use Blizzard's default Micro Bar/Menu instead of Elvui's, like we can enable and disable loads of skins inside Elvui

**Describe alternatives you've considered**
Other addons, but none overlaps Elvui. Disabling it's module remove the whole micro bar instead of Elvui's management of it.

**Additional context**
< Add any other context or screenshots about the feature request here. >

**Comment by 1Botanica1** [comment]
The micro bar is tied to the action bars.  

If you want to use the blizzard micro bar, you have to use their entire action bar settings (disable the ElvUI action bars). 

You can change the look of the ElvUI micro bar.
