### ISSUE TITLE
[Retail Bug Report] In talent tree 'Copy to Clipboard' does not work after copying a string once

### ISSUE THREAD

**Issue by richellevc** [tukui-org/ElvUI#1008]
### What is the issue you are having?

When opening the talent trees and clicking share -> copy to clipboard, it copies the first string correctly every first time after a reload, but any time after that it clears the clipboard (such that the clipboard is suddenly empty) and doesnt copy the string Changing talent trees, reopening the window, etc, doesnt work.

4x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:503: in function `callback'
[string "@SharedXML/LoadSystem/LoadSystemTemplates.lua"]:26: in function <.SharedXML/LoadSystem/LoadSystemTemplates.lua:17>
[string "=(tail call)"]: ?
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2542: in function `SetSelectedValue'
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2494: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

### What is the expected behavior?

It should copy the talent setup string to clipboard, and not play any sound.

### What actually happened?

In general a message "Loadout code copied to clipboard." appears, as expected. However, the code is not actually copied to clipboard. When it does copy the string correctly, no sound is played. When it bugs out, the sound similar to closing and opening a window is played (a sound that sounds like closing the door of a file cabinet). It then gives the error that buggrabber reports the in "Errors" below.

### Errors

```shell
4x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'CopyToClipboard()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CopyToClipboard'
[string "@Blizzard_ClassTalentUI/Blizzard_ClassTalentTalentsTab.lua"]:503: in function `callback'
[string "@SharedXML/LoadSystem/LoadSystemTemplates.lua"]:26: in function <.SharedXML/LoadSystem/LoadSystemTemplates.lua:17>
[string "=(tail call)"]: ?
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2542: in function `SetSelectedValue'
[string "@SharedXML/SharedUIPanelTemplates.lua"]:2494: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game 
`/edebug on` 

And test.  Do you have any issues/errors? 

If so, type in chat in game 
`/estatus`

And upload a full UI screenshot (no cropping)  showing the issue/error and the status panel.

**Comment by Azilroka** [comment]
It always taint.. This isn't a new one.
