### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by maryjane9110024** [tukui-org/ElvUI#1009]
### What is the issue you are having?

Randomly the item level and color will not show in my bags. When I reload, nothing happens. When I switch to another character it might work.

### What is the expected behavior?

To consistently show the item level and quality color

### What actually happened?

It didn't do that

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This usually happens with auction or some bag scanning addons enabled.  

This isn't an issue with ElvUI 

If you disable all addons & test with just ElvUI, the issue doesn't happen.  

If you think you have an issue with ElvUI, please always go through the troubleshooting 

1. Type in chat in game 
`/estatus`
2. Test, do you have the issue/error? 
3. If so, type in chat in game 
`/eatatus` and upload a full ui screenshot (no cropping) showing both the issue and status panel.

**Comment by kodewdle** [comment]
happens when you used an addon that access item data a lot fast (ah scan, item addons, etc) known by us but no fix currently closing this just because we get it every other week in discord
