### ISSUE TITLE
[Wrath Bug Report] ElvUi is Outdate

### ISSUE THREAD

**Issue by Quibbbles** [tukui-org/ElvUI#1010]
### What is the issue you are having?

I done the most recent update through Curseforge and after doing the update now have an error "Your ElvUI is outdated - please update and reload".
![Screenshot 2023-07-16 014623](https://github.com/tukui-org/ElvUI/assets/139640528/a89057ad-8c73-468d-a21d-fa2bfc0613dd)
![Screenshot 2023-07-16 014642](https://github.com/tukui-org/ElvUI/assets/139640528/7ade26f4-01ec-44bc-b8e2-a8eb9cdbbb32)
![Screenshot 2023-07-16 014730](https://github.com/tukui-org/ElvUI/assets/139640528/a884c90e-49b1-43b8-b60c-655ffa82a3b1)

### What is the expected behavior?

I'd like to know how to update or remove as it's causing issues when rolling / loot distributing and cant click through it.

### What actually happened?

I was doing the updates through Curseforge - update was successful with no issue - on login had the error in the middle of the screen.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
ElvUI is not on curseforge. You update other addons and plugins for elvui.  You should use wowup to manage elvui installation as its the easiest for a user to understand.
