### ISSUE TITLE
[Classic Bug Report] raid frames will disappear and reappear

### ISSUE THREAD

**Issue by Zalliano** [tukui-org/ElvUI#1013]
### What is the issue you are having?

My raid frames will disappear and reappear totally on their own in and out of combat. Been an issue for a few months now.

### What is the expected behavior?

Fix the issue

### What actually happened?

Fix the issue

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
I haven't heard of the issue, and not much information is provided to what is causing the issue, so just a "fix the issue" is very obscure. 

Please type in chat in game
`/edebug on`

Do you still have the issue?

If so, type in chat in game
`/estatus` 
and upload a FULL UI screenshot (no cropping) showing both the issue and the status panel. 

Also upload a screenshot of the Blizzard Raid tab - Social, Raid


Add another screenshot of the the relevant ElvUI Raid settings, Ie - raid 1, 2 or 3 (whichever should be showing).  Click and drag the bottom right of the ElvUI menu to expand it to show all the options.
