### ISSUE TITLE
[Retail Bug Report] Reputation Databar Tooltip Broken for Friend-style Factions

### ISSUE THREAD

**Issue by SerendipityJones** [tukui-org/ElvUI#1014]
### What is the issue you are having?

Factions that use the Friend style, such as Soridormi, the Artisan's Consortium, or Nat Pagle, do not have the correct info in the tooltip when you mouseover the reputation databar.  They look like this:
![image](https://github.com/tukui-org/ElvUI/assets/59793669/111c1d9a-57d4-4c47-b405-a39400906a68)

### What is the expected behavior?

When I mouseover that databar, I expect it to look like this:
![image](https://github.com/tukui-org/ElvUI/assets/59793669/e500f441-68f3-409d-a71f-930e098940f6)

### What actually happened?

When moving my mouse over the databar, it gives information that looks like the top image. It's only the actual data that's slightly broken. Otherwise it's correct.

### Suggested Solution/Workaround

The problem appears to be that while DB:ReputationBar_Update() checks for whether it's a Friend type and sorts it out properly, DB:ReputationBar_OnEnter() overwrites with the basic GetWatchedFactionInfo() without checking again for Friend type or not. 

There's likely a more elegant way to solve it, but I seem to have sorted it out by pulling the faction processing out as a separate function and having both of them call it. File is attached (extension changed to txt so it will let me attach it):
[Reputation.txt](https://github.com/tukui-org/ElvUI/files/12138317/Reputation.txt)

(Sorry, I can't give you a full screenshot of when it was broken, because I fixed it before coming here and seeing that you'd want one. I can vouch that I have tested it with only ElvUI enabled and have confirmed I'm up to date, however.)

### Errors

None. It doesn't see itself as wrong.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by SerendipityJones** [comment]
(Unrelatedly, did you know your Changelog & Troubleshooting task list says 'verfied' instead of 'verified' in tasks 2, 3, and 5?)

**Comment by kodewdle** [comment]
fixed in 13.39
