### ISSUE TITLE
[Retail Bug Report] ElvUI Cooldown Text with WeakAuras

### ISSUE THREAD

**Issue by aciabob** [tukui-org/ElvUI#1016]
### What is the issue you are having?

I have a WeakAura that I use ElvUI Cooldown Text for: https://wago.io/WtwVFVDU9, the WeakAura is supposed to show stacks in the middle of the icon at >0 charges, and whenever it reaches 0 stacks it should show the Timer Text from the Display tab.

However, the issue I am having is that only SOMETIMES (I am not able to reproduce it always) the Timer Text does not show up. Clip of this happening: https://youtu.be/8Sa9A7e6jjI. I have checked with the Blizzard cooldown text aswell as with OmniCC and I am not able to reproduce it at all, only happens with the ElvUI Cooldown Text.

### What is the expected behavior?

Had the above copy pasted, sorry!

### What actually happened?

Had the above copy pasted, sorry!

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
probably need something special or something.. don't know but generally we probably don't adjust something to fix somebody WA not working the same as default or OmniCC
