### ISSUE TITLE
Unitframe Health Info Update Has an Unexpected Delay

### ISSUE THREAD

**Issue by FlareStarrr** [tukui-org/ElvUI#1018]
### What is the issue you are having?

ElvUI unitframe info updates unexpected more slowly than another group frame addon called "Cell".

[I don't know why sentences in this paragraph have unintended strikethrough on them.] In specific, I disabled every "smooth bar" related options I could find in ElvUI, but ElvUI unitframe health bar reacts 0~6 frames out of 60fps more slowly than Cell health bar does, ElvUI unitframe health text reacts up to about 15 frames out of 60fps more slowly than Cell health bar does. While ElvUI unitframe power bar (Bear Rage) reacts in line with Cell health bar does more often than the former two do, it may still have 0~5 frames delay out of 60fps than Cell health bar has.

I just checked with Cell addon author, who suggested that there should be no difference theoretically between ElvUI and Cell health update speed. But in reality, ElvUI health bar and text (and power bar and text) usually has a split second of delay in update.

Here is the video footage showing the issue at a Tank dummy: https://streamable.com/bjjhsq.
The issue could be more severe in the real fight. In fact, it is the I reason came here to ask for help. Not only ElvUI health bar updates constantly more slowly than Cell does, but also there was once it completely omitted one tick of deadly Tank Buster in raid because of me being instantly healed to healthy state after that Tank Buster. I would never know that I was almost dead (5% HP left) in fight, without checking my gameplay footage afterwards, during which I noticed the significant delay between health info updates.

### What is the expected behavior?

I just checked with Cell addon author, who suggested that there should be no difference theoretically between ElvUI and Cell health update speed.

### What actually happened?

But in reality, ElvUI health bar and text (and power bar and text) usually has a split second of delay in update.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**I have to enable both and only Cell and ElvUI in order to see the health update difference. I don't think they have conflict between each other, but I could not verify it.**

**Comment by Merathilis** [comment]
Please report back, if this still a thing for you

**Comment by FlareStarrr** [comment]
Hello,

Indeed, the issue persists as observed. The ElvUI Player Unitframe consistently updates the player's health bar 1 to 7 frames slower than CELL, based on a 60 fps frame rate. This observation is derived from my recent gameplay footage of Mythic Nymue and Smolderon encounters this week. Notably, following Tank Buster mechanics such as Nymue's empowered Threaded Blast and Smolderon's Brand, a discernible delay in health bar updates is consistently noticeable on the ElvUI Player Unitframe compared to CELL.

To elaborate further, while the healing absorption bar from Smolderon's Brand aligns swiftly between the ElvUI Player Unitframe and Cell, presumably due to debuff updates, the health drop resulting from taking the Brand consistently lags behind on ElvUI, updating frames later than CELL.

I hope this clarification helps in addressing the issue effectively.
