### ISSUE TITLE
[Retail Bug Report] <bags don`t open>

### ISSUE THREAD

**Issue by CredereNemo** [tukui-org/ElvUI#1022]
### What is the issue you are having?

When i press the hotkey to open the bag it doesnt open. This only happens when elvui is enabled.

Other issues related to this are closed:
#594 
#612 
#620 

I tried uninstalling ElvUI completely and installing it again, but it didn't help, the error remains. ElvUI Version 13.38 [ July 13th 2023 ]
I'm writing a new ticket as I haven't seen any solution to the problem.

### What is the expected behavior?

Pressing a hotkey to open your bag.

### What actually happened?

bags did not open

### Errors

```shell
8x FrameXML/ContainerFrame.lua:899: attempt to index local 'itemButton' (a nil value)
[string "@FrameXML/ContainerFrame.lua"]:899: in function `UpdateItemLayout'
[string "@FrameXML/ContainerFrame.lua"]:1124: in function `ContainerFrame_GenerateFrame'
[string "@FrameXML/ContainerFrame.lua"]:181: in function <FrameXML/ContainerFrame.lua:179>
[string "@FrameXML/ContainerFrame.lua"]:205: in function `OpenBag'
[string "@FrameXML/ContainerFrame.lua"]:270: in function `OpenBackpack'
[string "@FrameXML/ContainerFrame.lua"]:1824: in function <FrameXML/ContainerFrame.lua:1823>
[string "@FrameXML/ContainerFrame.lua"]:1886: in function <FrameXML/ContainerFrame.lua:1857>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals:
self = ContainerFrameCombinedBags {
0 = <userdata>
CheckAuthenticatorSlotsHelpTip = <function> defined @FrameXML/ContainerFrame.lua:1054
UpdateBackground = <function> defined @FrameXML/ContainerFrame.lua:2602
UpdateFilterIcon = <function> defined @FrameXML/ContainerFrame.lua:2606
GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
GetPaddingWidth = <function> defined @FrameXML/ContainerFrame.lua:2570
SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:98
ClearItems = <function> defined @FrameXML/ContainerFrame.lua:2582
CheckUpdateDynamicContents = <function> defined @FrameXML/ContainerFrame.lua:814
UpdateIfShown = <function> defined @FrameXML/ContainerFrame.lua:1040
GetBagID = <function> defined @FrameXML/ContainerFrame.lua:730
TitleContainer = Frame {
}
UpdateItemContextMatching = <function> defined @FrameXML/ContainerFrame.lua:1072
GetContainedBagIDs = <function> defined @FrameXML/ContainerFrame.lua:2550
SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
OnCloseClicked = <function> defined @FrameXML/ContainerFrame.lua:710
UpdateCurrencyFrames = <function> defined @FrameXML/ContainerFrame.lua:2442
GetInitialItemAnchor = <function> defined @FrameXML/ContainerFrame.lua:2614
HideItems = <function> defined @FrameXML/ContainerFrame.lua:2586
CalculateHeight = <function> defined @FrameXML/ContainerFrame.lua:825
IsCombinedBagContainer = <function> defined @FrameXML/ContainerFrame.lua:2512
OnBagSlotLeave = <function> defined @FrameXML/ContainerFrame.lua:2642
SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:88
CancelRefresh = <function> defined @FrameXML/ContainerFrame.lua:955
MatchesBagID = <function> defined @FrameXML/ContainerFrame.lua:2546
UpdateAddSlots = <function> defined @FrameXML/ContainerFrame.lua:2366
UpdateTokenTracker = <function> defined @FrameXML/ContainerFrame.lua:2427
SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
OnBagSlotEnter = <function> defined @FrameXML/ContainerFrame.lua:2636
OnLoad = <function> defined @FrameXML/ContainerFrame.lua:2492
CalculateWidth = <function> defined @FrameXML/ContainerFrame.lua:2562
SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:106
Items = <table> {
}
UpdateCooldowns = <function> defined @FrameXML/ContainerFrame.lua:1046
OnTokenWatchChanged = <function> defined @FrameXML/ContainerFrame.lua:2618
size = 52
GetBackgroundColor = <function> defined @FrameXML/ContainerFrame.lua:798
GetRows = <function> defined @FrameXML/ContainerFrame.lua:774
MoneyFrame = Frame {
}
AddItemsForRefresh = <function> defined @FrameXML/ContainerFrame.lua:962
FilterDropDown = ContainerFrameCombinedBagsFilterDropDown {
}
PortraitButton = ContainerFrameCombinedBagsPortraitButton {
}
SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:102
CloseButton = Button {
}
Bg = Frame {
}
GetExtraRows = <function> defined @FrameXML/ContainerFrame.lua:766
OnShow = <function> defined @FrameXML/ContainerFrame.lua:2500
NineSlice = Frame {
}
EnumerateValidItems = <function> defined @FrameXML/ContainerFrame.lua:584
onCloseCallback = <function> defined @FrameXML/ContainerFrame.lua:2610
SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:84
SetBagID = <function> defined @FrameXML/ContainerFrame.lua:2540
GetBagSize = <function> defined @FrameXML/ContainerFrame.lua:540
CalculateExtraHeight = <function> defined @FrameXML/ContainerFrame.lua:2578
CloseTutorial = <function> defined @FrameXML/ContainerFrame.lua:948
IsBackpack = <function> defined @FrameXML/ContainerFram
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Are you using the ElvUI bags or the Blizzard bags?

If ElvUI - Bag - is unchecked, are you using the ElvUI skin for the Blizzard bags?
ElvUI- Skins - bag

Type in chat in game
`/edebug on`

Test - do you have the issue?  
If so, type in chat in game 
`/estatus` and upload a screenshot showing both the issue/error and the status panel. 

What steps to reproduce the issue?
1. have ElvUI bags enabled/disabled
2. Log into game
3. etc

If you have the issue with only ElvUI & the ElvUI bag disabled, disable all addons & test with the BLizzard UI.

**Comment by CredereNemo** [comment]
I use ElvUI bags.
I entered /edebug and the problem returned. 
Next time I will make a screenshot. 

I don't know what steps can reproduce the error, it may appear once an hour, or it may not appear for several hours. 
It's pretty hard to pinpoint the cause. It can appear when trying to sell things (the bag just does not open when talking to NPC) or during the pumping if you picked up some things and need to see if they are better or not.

**Comment by CredereNemo** [comment]
in anticipation of the bagging bug, a new one has appeared :D
/edebug on
![image](https://github.com/tukui-org/ElvUI/assets/60203650/ba7ccc41-b0c8-4cd3-8bbf-df6253bf919a)

the bags are still working. Last time it took about 20 minutes to break down

**Comment by CredereNemo** [comment]
I had to run with debug for a couple of hours to get it to come out this time)
![image](https://github.com/tukui-org/ElvUI/assets/60203650/ce15a6b2-5227-4676-aa95-96bc00e78cee)

Message: Interface/FrameXML/ContainerFrame.lua:899: attempt to index local 'itemButton' (a nil value)
Time: Thu Aug 10 17:35:07 2023
Count: 3
Stack: Interface/FrameXML/ContainerFrame.lua:899: attempt to index local 'itemButton' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/ContainerFrame.lua"]:899: in function `UpdateItemLayout'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1124: in function `ContainerFrame_GenerateFrame'
[string "@Interface/FrameXML/ContainerFrame.lua"]:181: in function <Interface/FrameXML/ContainerFrame.lua:179>
[string "@Interface/FrameXML/ContainerFrame.lua"]:205: in function `OpenBag'
[string "@Interface/FrameXML/ContainerFrame.lua"]:270: in function `OpenBackpack'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1824: in function <Interface/FrameXML/ContainerFrame.lua:1823>
[string "@Interface/FrameXML/ContainerFrame.lua"]:1886: in function <Interface/FrameXML/ContainerFrame.lua:1857>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

The only difference is the time the error appeared, although the first time it appeared after about 20 minutes. 
As I said, it's not clear what makes it appear. it can be in 10 minutes or even a couple of hours.

**Comment by 1Botanica1** [comment]
That is error 2/2 

Need the first error 1/x

**Comment by CredereNemo** [comment]
what's the difference between 2/2 or 1/x?
It's still a bug. 

It's just that this time another bug that wasn't there before came up first.

**Comment by 1Botanica1** [comment]
> what's the difference between 2/2 or 1/x?
> 
> It's still a bug. 
> 
> 
> 
> It's just that this time another bug that wasn't there before came up first.

The first error is the important one. It gives the relevant information.  

After an error there can be a trickle down effect, so the second, third of 53/70 doesn't show information to help track down where the issue is coming from.

**Comment by CredereNemo** [comment]
Okay, I'll try it later.

**Comment by CredereNemo** [comment]
It's funny. 
I created a new character and when I try to open the bag I get a bug. 
There is a feeling that the bug appears more often on "starting" locations.

![image](https://github.com/tukui-org/ElvUI/assets/60203650/18659915-0b3a-4cd1-9a86-d4fdae165fa1)

Message: Interface/FrameXML/ContainerFrame.lua:899: attempt to index local 'itemButton' (a nil value)
Time: Fri Aug 11 12:40:13 2023
Count: 1
Stack: Interface/FrameXML/ContainerFrame.lua:899: attempt to index local 'itemButton' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/ContainerFrame.lua"]:899: in function `UpdateItemLayout'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1124: in function `ContainerFrame_GenerateFrame'
[string "@Interface/FrameXML/ContainerFrame.lua"]:181: in function <Interface/FrameXML/ContainerFrame.lua:179>
[string "@Interface/FrameXML/ContainerFrame.lua"]:205: in function `OpenBag'
[string "@Interface/FrameXML/ContainerFrame.lua"]:270: in function `OpenBackpack'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1824: in function <Interface/FrameXML/ContainerFrame.lua:1823>
[string "@Interface/FrameXML/ContainerFrame.lua"]:1886: in function <Interface/FrameXML/ContainerFrame.lua:1857>
[string "=[C]"]: in function `ToggleAllBags'
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by Luckyone961** [comment]
Still an issue in Patch 10.1.7 with ElvUI 13.40+ ? If you got steps to reproduce feel free to re-open the ticket.
