### ISSUE TITLE
[Retail Bug Report] ElvUI Mail Frame skin prevents Demodal from making frame moveable

### ISSUE THREAD

**Issue by shinkyoukai** [tukui-org/ElvUI#1023]
### What is the issue you are having?

[Demodal](https://github.com/nezroy/DeModal) is an interface addon that removes the frame limit and allows you to move + save frame positions. While Demodal is enabled _and_ ElvUI's mail frame skin is turned on, the mailframe will always be defaulted to the center of the screen. Attempting to move the mailframe will cause the frame to fail to render properly and become unusable until a UI reload or relog. Frustratingly, this does not appear to generate an error of any kind.

### What is the expected behavior?

The mail frame should be moveable / render correctly on move with the mail frame ElvUI skin enabled.

### What actually happened?

![image](https://github.com/tukui-org/ElvUI/assets/89802157/cec448e9-e99d-491e-a65e-5f75e158c182)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
we don't usually add this sort of thing from another addon! sorry :(
