### ISSUE TITLE
[Feature Request] <Request for AFK screen customization>

### ISSUE THREAD

**Issue by Valyndra** [tukui-org/ElvUI#1026]
**Is your feature request related to a problem? Please describe.**
< Not exactly a problem, but more of a preference! When the afk screen shows up with my character, it also rotates the camera around my character, and the spinning is a little bit too much for me, but I truly enjoy this feature! >

**Describe the solution you'd like**
< A customization page for the afk screen would be ideal. It could also just be an addition of a checkbox with no spinning of the camera, which would work as well. >

**Comment by amgilmor** [comment]
I would also like to be able to turn the spinning off.

**Comment by kodewdle** [comment]
@Repooc to the rescue <3 thank you :) 🌼
