### ISSUE TITLE
[Retail Bug Report] <Filter dropdown menu doesnt appear>

### ISSUE THREAD

**Issue by Lolwhydeat** [tukui-org/ElvUI#1034]
### What is the issue you are having?

In all cases where you should be able to open a dropdown menu to filter things i.e. the petbattle pets, or where you would select the specific raid / group in the dungeonfindner, the drop down menues do not appear.

### What is the expected behavior?

A dropdownmenu with options should appear

### What actually happened?

In all cases where you should be able to open a dropdown menu to filter things i.e. the petbattle pets, or where you would select the specific raid / group in the dungeonfindner, the drop down menues do not appear.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [x] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Lolwhydeat** [comment]
I have made an observation:

since this is true for every drop down or pop up menu, its also relevant while rightklicking in the friendlist:
if I klick on the first person, nothing is visible.
If i klick the last person, in the bottom of the screen the menue appears (not completely, the most of it is still "out of bound)

Is there settable anchors for this?

**Comment by Repooc** [comment]
run this in chat
`/run SetCVar('uiScale', 1); ReloadUI()`

**Comment by Lolwhydeat** [comment]
IT WORKED!
Now I dont hve to feel crippled anymore :)
Thank you so much! 
BR
