### ISSUE TITLE
AddOn 'ElvUI' tried to call the protected function 'Search()'

### ISSUE THREAD

**Issue by Raven427** [tukui-org/ElvUI#1035]
### What is the issue you are having?

i was in a LFG for Raid, Delisted and switched to LFG Dungeon, will not display the groups available.

### What is the expected behavior?

I expected for the LFG listing to change from Raid To Dungeons.

### What actually happened?

would not show the groups available to join in the LFG listing until i did a reload

### Suggested Solution/Workaround

did a /reload and then the list would populate however it would do it again if i made changes to LFG interface

### Errors

```shell
6x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'Search()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:226: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua"]:179: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua"]:72: in function <...s/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:54>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Raven427** [comment]
33x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI/Wrath/Modules/Blizzard/ObjectiveFrame.lua"]:16: in function <...dOns/ElvUI/Wrath/Modules/Blizzard/ObjectiveFrame.lua:13>
[string "=[C]"]: in function `SetPoint'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2699: in function `UIParentManageFramePositions'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1958: in function <Interface_Wrath/FrameXML/UIParent.lua:1945>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2714: in function <Interface_Wrath/FrameXML/UIParent.lua:2712>

**Comment by Typowow** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML/LFGList.lua"]:3543: in function <FrameXML/LFGList.lua:3532>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2603: in function <FrameXML/LFGList.lua:2600>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by kodewdle** [comment]
i believe this is fixed by now, reopen if you still have the issue in The War Within

**Comment by Espboe** [comment]
15x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'CompactPartyFrame:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `Hide'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1522: in function <ElvUI/Core/Modules/UnitFrames/UnitFrames.lua:1520>
[string "=[C]"]: in function `SetShown'
[string "@Blizzard_UnitFrame/Mainline/CompactPartyFrame.lua"]:142: in function `UpdateVisibility'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua"]:714: in function `CompactRaidFrameManager_UpdateContainerVisibility'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua"]:221: in function `CompactRaidFrameManager_UpdateShown'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager.lua"]:186: in function <...mpactRaidFrames/Blizzard_CompactRaidFrameManager.lua:182>
