### ISSUE TITLE
Leave Vehicle Button Issue

### ISSUE THREAD

**Issue by syswis** [tukui-org/ElvUI#1036]
### What is the issue you are having?

Leave Vehicle Button icon is not showing since Ulduar patch. Only a empty (still working) button is shown.

### What is the expected behavior?

Correctly show the leave vehicle button icon

### What actually happened?

Leave Vehicle Button icon is not showing

### Errors

```shell
no errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Do you still have issues with this?


Type in game `/edebug on`

Test - do you have the issue?

If so, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the error and the status panel.
