### ISSUE TITLE
[Wrath Bug Report] Enemy player nameplate dissapear on arena

### ISSUE THREAD

**Issue by Ivankonoiko** [tukui-org/ElvUI#1040]
### What is the issue you are having?

Randomly on Arenas 2x2 enemyplayer nameplate just dissapear from start, it's can happend for both enemy players or just for one of them after Elvui update to 13.40. Sometimes everything is working how it supposed to be.
I'm using Addonskins v4.68, Elvui Eltruism Wrath v3.9.6 Elvui WrathArmory v1.08

### What is the expected behavior?

normal nameplates above enemy models

### What actually happened?

health bar, castbar, icons of debuffs/buffs/ and so on just not existed above enemy player on some arenas.

### Errors

```shell
-
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Ivankonoiko** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/62277076/46dcb75e-53e5-4a11-93ed-1d141a6e479b)
here shamys nameplate bugged but priest nameplate was working welll

**Comment by Ivankonoiko** [comment]
Copy info about lua errors from BugSack:

41x Blizzard_ArenaUI/Blizzard_ArenaUI.lua:93: attempt to index global 'ArenaEnemyFrames' (a nil value)
[string "@Blizzard_ArenaUI/Blizzard_ArenaUI.lua"]:93: in function `ArenaEnemyFrames_UpdateVisible'
[string "@Blizzard_ArenaUI/Blizzard_ArenaUI.lua"]:241: in function <Blizzard_ArenaUI/Blizzard_ArenaUI.lua:212>

Locals:
_ = true
instanceType = "raid"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArenaEnemyFrames' (a nil value)"

**Comment by Ivankonoiko** [comment]
Copy info about lua errors from BugSack:
12x TCT/TCT.lua:1021: attempt to call global 'GetItemCooldown' (a nil value)
[string "@TCT/TCT.lua"]:1021: in function `UpdateIcon'
[string "@TCT/TCT.lua"]:1239: in function `?'
[string "@TCT/TCT.lua"]:272: in function <TCT/TCT.lua:268>

Locals:
self = TCTFrame {
 0 = <userdata>
 ShoworHideFrames = <function> defined @TCT/TCT.lua:408
 PLAYER_ENTERING_WORLD = <function> defined @TCT/TCT.lua:313
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 spellToItem = <table> {
 }
 SetCooldownFor = <function> defined @TCT/TCT.lua:399
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 CreateElements = <function> defined @TCT/TCT.lua:856
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 UpdateIcon = <function> defined @TCT/TCT.lua:1007
 point = <table> {
 }
 PLAYER_LOGIN = <function> defined @TCT/TCT.lua:1234
 cooldownStartTimes = <table> {
 }
 GROUP_ROSTER_UPDATE = <function> defined @TCT/TCT.lua:1189
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 bd = <table> {
 }
 eventFrame = Frame {
 }
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @TCT/TCT.lua:350
 db = <table> {
 }
 UNIT_INVENTORY_CHANGED = <function> defined @TCT/TCT.lua:1177
 wait = <function> defined @TCT/TCT.lua:1438
 Proc = <function> defined @TCT/TCT.lua:1247
 PLAYER_EQUIPMENT_CHANGED = <function> defined @TCT/TCT.lua:1183
 ZONE_CHANGED_NEW_AREA = <function> defined @TCT/TCT.lua:1118
 CreateHolder = <function> defined @TCT/TCT.lua:999
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 cooldownDurations = <table> {
 }
 cooldowns = <table> {
 }
}
unit = "player"
(for index) = 13
(for limit) = 14
(for step) = 1
i = 13
itemID = 47464
icon = 237274
(*temporary) = nil
(*temporary) = 47464
(*temporary) = "attempt to call global 'GetItemCooldown' (a nil value)"
TCTPlayerFrame = TCTPlayerFrame {
 0 = <userdata>
 elements = <table> {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:422
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 lock = <function> defined @TCT/TCT.lua:184
 ApplyBackdrop = <function> defined @SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 unlock = <function> defined @TCT/TCT.lua:131
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 dragframe = Frame {
 }
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @SharedXML/Backdrop.lua:399
 defaultPosition = <table> {
 }
 reset = <function> defined @Interfac

**Comment by Luckyone961** [comment]
Nothing you posted so far is related to the ElvUI AddOn, you also accepted this step:

`I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using /edebug on?`

Which requires testing with only 3 AddOns enabled: 'ElvUI', 'ElvUI_Libraries', and 'ElvUI_Options'
We do not care about AddOnSkins, Eltruism or WrathArmory.

The first error is a Blizzard error and the second error is an AddOn called TCT, whatever that is.
