### ISSUE TITLE
[Classic Bug Report] Sortings with extra bag inside of bag (with quiver in use)

### ISSUE THREAD

**Issue by Stultusaur** [tukui-org/ElvUI#1041]
### What is the issue you are having?

Attempting to Auto Sort my inventory using the "Sort Bags" button.

### What is the expected behavior?

Expected behaviour is the bags will auto sort like normal.

### What actually happened?

Logged into a hunter, with a quiver. When I auto sort, it says "Only arrows can be placed in that"

### Suggested Solution/Workaround

I am unsure, it is likely caused by an item being miss-targeted as an arrow, and trying to be put in the bag.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Stultusaur** [comment]
Update,

I don't know if this was causing my initial issue or not,
But I have verified it is happening when I have a Woolen Bag in my inventory.

**Comment by Crumdidlyumshis** [comment]
Bump @kodewdle what I mentioned before.

**Comment by kodewdle** [comment]
should be fixed by https://github.com/tukui-org/ElvUI/commit/971f60625409096f568ac323ac1f27c4aae872f9
