### ISSUE TITLE
Enemy Nameplates disappear after a short time

### ISSUE THREAD

**Issue by Platewhat** [tukui-org/ElvUI#1046]
### What is the issue you are having?

Elvui nameplates stop working after a few minutes.

When I log in, the enemy nameplates disappear after a few minutes.

When I join a BG e.g. at first everything works fine. After a few minutes nameplates from enemies who appeared later arent showing. The nameplates that first have been shown arent shown anymore, after i respawned.
The same happens in the arena. Nameplates disappear after a few sec or minutes.

### What is the expected behavior?

Nameplates should be shown. 
This bug appeared after the last update of elvui.

### What actually happened?

Please see above.

I updated elvui with deleting the folders "ElvUI", "ElvUI_Libraries" and "ElvUI_Options" first -> same problem.
I tried to update with "over"copy the folders -> same problem.
I deactivated all other addons -> same problem.

When the nameplates disappeared and i hit my hotkey to show nameplates I get a message, that one addons caused an error.

### Suggested Solution/Workaround

n/a

### Errors

```shell
Please see above.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Flamanis** [comment]
You are using Gladdy. Gladdy is hiding ElvUI nameplates for their Totem Plates, and not properly reversing that after.

**Comment by Ivankonoiko** [comment]
> You are using Gladdy. Gladdy is hiding ElvUI nameplates for their Totem Plates, and not properly reversing that after.

any advise how to turn off this setting in ElvUI nameplates ?

**Comment by Flamanis** [comment]
If you are using the addon Gladdy, you can disable Totem Plates in their settings.

**Comment by kodewdle** [comment]
for now if you have this problem please see: https://github.com/XiconQoo/Gladdy-TBC/pull/81 we are waiting to hear back from them to accept this PR :)

**Comment by kodewdle** [comment]
we can close this now, please update Gladdy! :)
