### ISSUE TITLE
[Wrath Bug Report] Enemy Nameplates disappear sometimes on Arena/Battleground

### ISSUE THREAD

**Issue by Ivankonoiko** [tukui-org/ElvUI#1047]
### What is the issue you are having?

Randomly on Arenas 2x2 enemyplayer nameplate just dissapear from start, it's can happend for both enemy players or just for one of them after Elvui update to 13.40. Sometimes everything is working how it supposed to be.

### What is the expected behavior?

normal nameplates above enemy models

### What actually happened?

health bar, castbar, icons of debuffs/buffs/ and so on just not existed above enemy player on some arena

### Suggested Solution/Workaround

compare  v13.40 with 13.39

### Errors

```shell
First:
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI/Wrath/Modules/Blizzard/ObjectiveFrame.lua"]:16: in function <...dOns/ElvUI/Wrath/Modules/Blizzard/ObjectiveFrame.lua:13>
[string "=[C]"]: in function `SetPoint'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2699: in function `UIParentManageFramePositions'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1958: in function <Interface_Wrath/FrameXML/UIParent.lua:1945>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2714: in function <Interface_Wrath/FrameXML/UIParent.lua:2712>
[string "=[C]"]: ?
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface_Wrath/FrameXML/VehicleSeatIndicator.lua"]:62: in function `VehicleSeatIndicator_UnloadTextures'
[string "@Interface_Wrath/FrameXML/VehicleSeatIndicator.lua"]:108: in function <Interface_Wrath/FrameXML/VehicleSeatIndicator.lua:93>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}



Second: 
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'ArenaEnemyFrames:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetPoint'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2679: in function `UIParentManageFramePositions'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:1958: in function <Interface_Wrath/FrameXML/UIParent.lua:1945>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath/FrameXML/UIParent.lua"]:2714: in function <Interface_Wrath/FrameXML/UIParent.lua:2712>
[string "=[C]"]: ?
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface_Wrath/FrameXML/VehicleSeatIndicator.lua"]:62: in function `VehicleSeatIndicator_UnloadTextures'
[string "@Interface_Wrath/FrameXML/VehicleSeatIndicator.lua"]:108: in function <Interface_Wrath/FrameXML/VehicleSeatIndicator.lua:93>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}


Third:
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_Libraries' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/SecureStateDriver.lua"]:18: in function <FrameXML/SecureStateDriver.lua:16>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:164: in function `EmptyPanel'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:671: in function `UpdatePanelAttributes'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:618: in function `LoadDataTexts'
[string "@ElvUI/Core/Modules/DataTexts/Battlegrounds.lua"]:89: in function `onClick'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:440: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:438>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
=
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Ivankonoiko** [comment]
Third:
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_Libraries' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/SecureStateDriver.lua"]:18: in function <FrameXML/SecureStateDriver.lua:16>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:164: in function `EmptyPanel'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:671: in function `UpdatePanelAttributes'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:618: in function `LoadDataTexts'
[string "@ElvUI/Core/Modules/DataTexts/Battlegrounds.lua"]:89: in function `onClick'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:440: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:438>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
=

**Comment by kodewdle** [comment]
dup of: https://github.com/tukui-org/ElvUI/issues/1046
