### ISSUE TITLE
[Retail Bug Report] AddOn 'ElvUI' tried to call the protected function 'ObjectiveTrackerFrame:SetHeight()'.

### ISSUE THREAD

**Issue by NoNick96** [tukui-org/ElvUI#1048]
### What is the issue you are having?

This lua error seemingly randomly pops up when opening different UI windows or going in and out of combat.

### What is the expected behavior?

No lua error.

### What actually happened?

Lua error.

### Errors

```shell
39x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'ObjectiveTrackerFrame:SetHeight()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetHeight'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:810: in function `ObjectiveTracker_UpdateHeight'
[string "@FrameXML/UIParent.lua"]:3193: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2659: in function <FrameXML/UIParent.lua:2646>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3206: in function <FrameXML/UIParent.lua:3204>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML/VehicleSeatIndicator.lua"]:138: in function `UnloadTextures'
[string "@FrameXML/VehicleSeatIndicator.lua"]:42: in function <FrameXML/VehicleSeatIndicator.lua:27>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed already in dev
