### ISSUE TITLE
Totem Bar Disappears

### ISSUE THREAD

**Issue by hirach0** [tukui-org/ElvUI#1050]
### What is the issue you are having?

When playing again on TBC and since then the totem bar bug has not been fix, it disappears when you start the game and I have to recharge it every time I play.

### What is the expected behavior?

I just wanna always see the totem bar active, because disappers always

### What actually happened?

totem bar disappers always any time I can play wow

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/2266754/5e474214-781b-48af-ba79-f34f470fcd57)

**Comment by E-Tsx** [comment]
This is not an issue with ElvUI but with wow itself, they haven't fixed this ever since they introduced the totembar. See here a recording on a character without addons enabled right after the loading screen, and what happens after you type /reload



https://github.com/tukui-org/ElvUI/assets/97974579/8feace32-70e8-415d-ab1f-d99b375ca889

**Comment by kodewdle** [comment]
> ![image](https://user-images.githubusercontent.com/2266754/269781457-5e474214-781b-48af-ba79-f34f470fcd57.png)
