### ISSUE TITLE
Weapon buff timer not updating

### ISSUE THREAD

**Issue by ViolentlightX** [tukui-org/ElvUI#1051]
### What is the issue you are having?

When I use a weapon buff like Rockbiter Weapon or Flametongue Weapon, it shows the buff in the top right properly. Shows 5 minutes. But after the first time of it being applied, if I try to refresh the buff before it has expired, the time remaining will not update.

When the original buffs time expires, the icon for the buff on the weapon remains, but there is no time.

Turned off all other addons except ElvUI and it still happens. Everything works fine on the default interface with all addons turned off.

Other buffs seem to work fine. Seems to be weapon buffs with the issue.

Top is when I refreshed the weapon buff, but let the original buffs timer expire. The second one shows the original buffs timer of 3 minutes, but when hovering over it, shows the weapon currently has 5 minutes left on the buff.
![ElvUI_Weapon_Buff_Bug](https://github.com/tukui-org/ElvUI/assets/35661665/a80eb6ba-4ebb-428d-82fe-4b5d3855c9db)

### What is the expected behavior?

Buff timer should update to the refreshed full timer

### What actually happened?

Original buffs timer is displayed, instead of updating to refreshed buff.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game `/edebug on`
and test - If you still have the issue 

If you still have the issue, type in chat in game `/estatus` and upload a full UI screenshot showing both the issue and the status panel


Include the steps to reproduce the issue.

**Comment by 1Botanica1** [comment]
Just to note - as there is issues 1392 that could be similar

I'm unable to replicate this - the cd timer is working as expected. 

Here is it with 58 minutes

<img width="1258" height="572" alt="Image" src="https://github.com/user-attachments/assets/ec246f04-adaf-4629-84f9-e7f964c7219e" />

Refreshed 

<img width="1260" height="569" alt="Image" src="https://github.com/user-attachments/assets/7771307b-5d20-4a11-8374-0066e1c077e4" />
