### ISSUE TITLE
Tortollan Crab World Quest 

### ISSUE THREAD

**Issue by shaunakt** [tukui-org/ElvUI#1053]
### What is the issue you are having?

The Tortollan quest to move the crab left and right and use shells, with my ELVUI on I do not get any options that would enable me to do the quest. On the flip side the Tortollan quest to shoot down the crabs/gulls that works percfectly.

### What is the expected behavior?

Same 1/2/3 key binds that normal UI provides should appear.

### What actually happened?

The action bar shows up but the keys do not.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/2266754/fc6f3ff2-35df-4e58-97c6-00f5b79dfcec)

**Comment by kodewdle** [comment]
please do the steps we ask so we don't waste each other time.  also, we know of this issue and have it pinned internally.. thanks

**Comment by shaunakt** [comment]
Hi, I appreciate that but what I do not appreciate is how rude you are. I will no longer use your UI and maybe stop making it glitch out so much with the older content, just an fyi :) have a good one buddy

**Comment by Azilroka** [comment]
If I'm not mistaken they broke this awhile back with the default ui rework.

**Comment by Azilroka** [comment]
> Hi, I appreciate that but what I do not appreciate is how rude you are. I will no longer use your UI and maybe stop making it glitch out so much with the older content, just an fyi :) have a good one buddy

You clearly marked every checkbox which means you didn't read the steps. We will start auto closing tickets with improper steps and improper titles soon.

**Comment by Repooc** [comment]
there was nothing rude about anything said besides you and your remarks

**Comment by Flamanis** [comment]
Wait, ElvUI is the cause of the glitches and not Blizzard updating the base UI code and breaking things?
