### ISSUE TITLE
Title here

### ISSUE THREAD

**Issue by maryjane9110024** [tukui-org/ElvUI#1058]
### What is the issue you are having?

When opening bags, the quality color border and ilvl of item disappears and it looks like vendor trash. Sometimes when equipping a piece of equipment, it will show the color and ilvl for all items and sometimes it doesn't. Not sure what is causing this issue. 

### What is the expected behavior?

To see the item's border color (matches the item quality; blue, green, purple, orange) and the ilvl of the item. 

### What actually happened?

When opening bags, the quality color border and ilvl of item disappears and it looks like vendor trash. Sometimes when equipping a piece of equipment, it will show the color and ilvl for all items and sometimes it doesn't. Not sure what is causing this issue. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by maryjane9110024** [comment]
It seems to be intermittent. Sometimes it bugs out sometimes it doesn't but lately it's been more frequent.

**Comment by Azilroka** [comment]
This is due to item caching. You use another addon that scans the auction house which clears the item cache.

**Comment by kodewdle** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/2266754/7ac1a45a-98d2-40e2-b332-0f5fcf42bfdb)
