### ISSUE TITLE
Item quality & level

### ISSUE THREAD

**Issue by maryjane9110024** [tukui-org/ElvUI#1059]
### What is the issue you are having?

![image](https://github.com/tukui-org/ElvUI/assets/4682765/4abbb889-6bdf-40fd-ad0c-6677c6220d11)

This^^^^ 

Item quality border color around items are not showing (see screenshot). I uninstalled and reinstalled, still doesn't work. Sometimes equipping an item from bags will trigger it to add the border color and item level of the item but not always and is very intermittent. 

I have been searching for a solution to this issue for awhile and have not been able to find a solution.

### What is the expected behavior?

border and ilevel to show in bags

### What actually happened?

it doesn't show it just shows the icon of the item 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
if u do `/edebug on` u will most likely not have this issue as this issue is typically caused by other addons like auction house scanning addons, see #260 and #623

**Comment by maryjane9110024** [comment]
Are there any other addons that could be conflicting? I don't have any auction house addons. I got rid of auctioneer awhile ago when it stopped working.

**Comment by Repooc** [comment]
could be but we dont keep track of what api each addon uses, that is why we have the step (that you said u did) for debugging that will disable all addons but elvui to ensure its not an elvui specific issue

**Comment by maryjane9110024** [comment]
i did and it's still happening. it's fine. i'll live with it i guess. eventually it will get fixed. Thanks!

**Comment by maryjane9110024** [comment]
only using elvui ... deleted all other addons, wtf, interface everything and a fresh install on elvui... STILL HAPPENING

guess im sol huh..

**Comment by maryjane9110024** [comment]
Yes JUST elvui like I said I deleted everything and did a fresh install on elvui and it still doesn't work.... but it's fine. It's never going to get fixed for me.... they closed my ticket and dismissed me so..... I've had a few friends have this issue too but they went back to default UI and i can't stand the new default UI for wow

**Comment by Repooc** [comment]
after you log in, do `/edebug on` and then show `/estatus` window & the issue all in the same picture showing that you are still having the issue with only elvui (make sure both are shown in the same picture)
