### ISSUE TITLE
/in Macro function doesn't work anymore.

### ISSUE THREAD

**Issue by afkjustin** [tukui-org/ElvUI#1060]
### What is the issue you are having?

I used to have a macro like the following:

/flood
/in 10 /flood

/flood started an addon, then "/in 10 /flood" would wait 10 seconds and turn off the macro.

### What is the expected behavior?

/in 10 waits 10 seconds then sends the rest of the macro

### What actually happened?

Nothing, the addon turns on from the first /flood but doesn't wait 10 seconds then turn off.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [x] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by afkjustin** [comment]
I did the final check box, I re-tested by doing "/edebug on" then made a macro below, the "Test 2" never went off. My first macro was working yesterday, I updated ElvUI today.

/s Test 1
/in 5 /s Test 2

**Comment by afkjustin** [comment]
> it was removed as it wont work in 10.2

Wasn't in the change log, guess I missed the news somewhere...

**Comment by Repooc** [comment]
we didnt put it in the changelog as it isnt something that is commonly known to be in the addon as it is very old and not documented anywhere
