### ISSUE TITLE
[Feature Request] Buff/Lifebloom Tracker

### ISSUE THREAD

**Issue by Robotnik247** [tukui-org/ElvUI#1061]
**Is your feature request related to a problem? Please describe.**
Since https://www.wowhead.com/spell=274902/photosynthesis has become the norm, would it be possible to add the option to track this hot on yourself akin to how dots currently work i.e sun/moonfire on the actionbar?

**Describe the solution you'd like**
Simply put, add the option to track self-cast hots (or buffs in general) on yourself or just lifebloom if it's such a hassle to implement Or maybe add it to the totem tracker or a way to add other spells/abilities since buff tracking has become such a hassle these days.

Maybe there already is a way to this in the filter section but I don't see such an option there. And obviously it's up to every player to add their own spells.

**Describe alternatives you've considered**
Filtering buffs which only made (insert the thousands upon thousands of Spell IDs here) things worse or a simple WA tracker.

**Additional context**
...

**Comment by Repooc** [comment]
you can track auras with the Aura Indicator option on the frame.  If you are playing as a druid, u can just add it to the Filters -> Aura Indicator (Class) to track it on frames that have Aura Indicator option.  Make sure to use the aura id, not the spell id. The easiest way to get that is to use it on yourself and mouse over the aura by the minimap.

You can tech track this via the Buffs section of a unitframe but I don't suggest this method with raid frames as that can get a bit messy with a bunch of buffs being tracked with so many people but you can if you want via Filters and adding it to a whitelist that is there or one you make yourself and add to the filter priority section at the bottom of the buffs section for the frames you want to track this on.  You can find info on [filters](https://github.com/tukui-org/ElvUI/wiki/filters) on the wiki and in game in the Help tab under the Filters section.
