### ISSUE TITLE
[Feature Request] Itemlevel in Player Tooltips

### ISSUE THREAD

**Issue by Laexxi** [tukui-org/ElvUI#1062]
**Is your feature request related to a problem? Please describe.**
I do not like to have multiple Addons doing the same or similar things. I love ElvUI because it is a compilation of a lot features bundled in one Addon-Suite.
My concerns are about the ElvUI Tooltips. My request is a addition of the targeted/hovered Players Itemlevel. 

**Describe the solution you'd like**
An additional line with the players (equipped) Itemlevel

**Describe alternatives you've considered**
If you add another Addon (TipTacTalents) you do have the itemlevel in the ElvUI Tooltip, but more addons to configure and maintain.

**Additional context**
German, but should be understandable
![Bild_2023-10-14_161029194](https://github.com/tukui-org/ElvUI/assets/59017978/651e9352-c742-403d-9290-4c4819609786)

**Comment by Repooc** [comment]
elvui already has the ability to show item level but you have to hold shift down and mouse over the unit, this is to prevent spammy the blizzard api to get the info as it requires on the event INSPECT_READY from blizzard which they throttle which can cause an issue while in combat as well with other addons trying to use the INSPECT_READY event which multiple addons trying to call that will have issues, so we require u to hold shift to retrieve that info
