### ISSUE TITLE
[Feature Request] Searchbar for ElvUI Config

### ISSUE THREAD

**Issue by Laexxi** [tukui-org/ElvUI#1063]
**Is your feature request related to a problem? Please describe.**
ElvUI is getting more and more features and some are moved and I struggle to know where everything is. 

**Describe the solution you'd like**
I would like to have a searchbar to search (localized) Options of ElvUI Features, including features of ElvUI Compilations like Benik, Merathilis, ... . 
Insipration is the new searchbar of Standard Blizzard WoW-Options.

**Describe alternatives you've considered**
I do not know any alternatives.

**Additional context**
![Bild_2023-10-14_161559325](https://github.com/tukui-org/ElvUI/assets/59017978/6bf2f5bb-1956-4a0f-9ec1-70ce16271b81)

**Comment by Repooc** [comment]
ElvUI already has a search feature, look on the left side of the config

**Comment by Laexxi** [comment]
Im officially dumb :D. Ty
