### ISSUE TITLE
Chat Class Color being removed

### ISSUE THREAD

**Issue by Andromni** [tukui-org/ElvUI#1067]
### What is the issue you are having?

Randomly I am having class colors being removed from my chat screens.

### What is the expected behavior?

Once set, class colors should remain setup and show.

### What actually happened?

Farming during an afternoon and without notice class colors are removed from the chat.

### Suggested Solution/Workaround

I have tried to go into the settings and disabled, enabled chat controls. Disabling chat controls has class colors return. Enabling them causes them to not work again. I ran install again and it resolved the issue temporarily, but the issue happens again after a time.

### Errors

```shell
None Observed.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Sounds like you have an addon that is changing the settings. 

Type in chat in game
`/edebug on`

Then check if the chat colours are working.  If so, test in the troubleshooting mode (only ElvUI) to see if you still have the issue.  

If you have it with only ElvUI (not enabling your other addons), type in chat in game
`/estatus` 
and upload a full ui screenshot (no cropping) showing the issue and the status panel.

**Comment by Andromni** [comment]
Issue Persists with /edebug on. Screenshot attached.
![ElvUI_Bug](https://github.com/tukui-org/ElvUI/assets/93673830/0ec785f1-9a94-4997-894f-fe30f9dbf9c9)

**Comment by Azilroka** [comment]
It will because it's a cvar. Redo the chat install.

**Comment by Andromni** [comment]
I redo it regularly. I run install and set CVAR and reset chat and it works again, but then falls off after a period.

**Comment by 1Botanica1** [comment]
In that screenshot, it looks like you have tested - chat colours have been removed and then done the troubleshooting steps and the status panel and screenshot.  


after doing the cvar 
`/edebug on` 

test with only ElvUI 

Does it happen?  

I haven’t seen the issue with only ElvUI. There are quite a few addons that change the cvars and remove the chat colours.

**Comment by Andromni** [comment]
Correct. Once I redo the install and set CVAR, it does not fix. I have to hit the 3rd step and "setup chat" to fix the issue. CVAR does not solve it. Once I setup/reset chat - the colors return for a time... but then after a period go away again. I have not been able to identify what action is causing them to be removed again. Repeating the chat setup steps again corrects the issue... but it also removed the extra chat windows I create, as well as the font size I set.

**Comment by 1Botanica1** [comment]
ElvUI doesn’t change the chat colours once set. 

There are other addons that remove the class colours

**Comment by Andromni** [comment]
> prat, chatter, leatrix, WA - are only some of the addons people have had the issue with.

I'll review addons and isolate.

**Comment by 1Botanica1** [comment]
ElvUI doesn’t change the class colours once set. 

For the ticket - you need to test with only ElvUI.  If another addon is changing it, that isn’t anything ElvUI can control.
