### ISSUE TITLE
Bag category assignment doesn't work anymore

### ISSUE THREAD

**Issue by Arrothben** [tukui-org/ElvUI#1069]
### What is the issue you are having?

Hello

I don't know when it started but the bag category assignment doesn't work in classic era anymore. It used to work a few days/weeks ago and I can't tell when this changed. Originally the border outlines of the bag slots had a different color for the different categories.

The problem is that the assigned bags are still assigned without the possibility for me to change that.
As you can see in the screenshot, equipment is automatically looted to bag 3 even though there are empty slots in bag 1 and 2. This was my category for bag 3 when it worked.

![Screenshot 2023-10-22 172417](https://github.com/tukui-org/ElvUI/assets/104759428/2ee00e9e-7867-40c0-9e62-d6a32d4db10c)
Additionally the options menu shows but doesn't have any options marked as chosen.

I tried all the usual suspects like deleting WTF, Cache, Interface but nothing changed. The standard interface doesn't have an option to change this. Or at least I couldn't find any.

### What is the expected behavior?

The category assignment should either work or not. A mixture of both isn't good.

### What actually happened?

see description above.

### Suggested Solution/Workaround

I tried to google the problem but no one seems to have had it.

### Errors

```shell
No errors appear.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
it seems the API used for this just no longer works on Classic.  we can't set the flags anymore which means the functionality is useless.  sorry they did that.  i will hide the menu unless they change their minds later.  :)

**Comment by kodewdle** [comment]
for reference, they moved the APIs to the C APIs which i switched to (assuming they still worked on Classic Era, apparently not):  https://github.com/tukui-org/ElvUI/commit/e165737e3a8a39b8df5f710b84537247e1adb00d

**Comment by Arrothben** [comment]
It just sucks that Blizzard still kind of adheres to the once assigned categories.
