### ISSUE TITLE
[Retail Bug Report] Clique compatibility issue

### ISSUE THREAD

**Issue by Horetz** [tukui-org/ElvUI#107]
### What is the issue you are having?

Good day. I ve got a issue that some of keybinds not react. For example i got ability assigned to key R. I press it and nothing happens. Also there is no activation glow on button in command panel. 

### What is the expected behavior?

And strange thing about that it sometimes changes when i switch character location.  Issue continues on all versions from 12.45 . I updated my Elvui to last version today and lost my 12.44 version rar unfortunately. It happens only when Clique addon active. 

### What actually happened?

I ve met people that got same issue on Clique curseforge forums links attached:
https://www.curseforge.com/wow/addons/clique/issues/307
https://www.curseforge.com/wow/addons/clique/issues/305
Also i ve noticed that some fixes already was done to Elvui regarding Clique in changelog of Version 12.39 [ August 5th 2021 ]
Maybe this could help.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by 1Botanica1** [comment]
Does this happen with blizzard UI & clique?

**Comment by Horetz** [comment]
Blizzard Ui works alright no errors so far. When i set Elvui active i met issue again.

**Comment by kodewdle** [comment]
can you retest this sometime with 12.71; I believe some compatibility issues with clique are sorted out now. reopen if it still happens, thank you!
