### ISSUE TITLE
[Feature Request]  I can't find a way to change unit frame color for factions

### ISSUE THREAD

**Issue by cedevitaodnarandze213** [tukui-org/ElvUI#1071]
**Is your feature request related to a problem? Please describe.**
Hey there, I'm palying on a private wotlk 3.5.5.a server the addon version is 6.09 and I can't find a way to change color of the unit frames for horde. (Please see attached files) When I see someone I can't imediatly tell if it is a horde char or a alliance and that is a big Issue for me, I have spent at least 6 hours today seting this addon up but this problem is so annoying and I might need to download something else.

**Describe the solution you'd like**
The soulution is to be told what I need to do to make horde have red health.

**Describe alternatives you've considered**
I tried puting this "horde" and their faction icon but this doesn't look good. 

**Additional context**
Here are clear examples of what I mean hope you understand.
![image (1)](https://github.com/tukui-org/ElvUI/assets/149123638/74bea86f-04e5-4437-9267-f4b8c48a6e40)
![image (2)](https://github.com/tukui-org/ElvUI/assets/149123638/d1269d48-327d-47dc-b78c-2e1eafd0eca0)
![image (3)](https://github.com/tukui-org/ElvUI/assets/149123638/43e3263b-ed2c-46f6-9926-df4b591b155d)

**Comment by cedevitaodnarandze213** [comment]
You can see in the examples. The first picture has the addon enabled, and the second one does not. In the second picture, it is obvious that the paladin is a Horde character because of the red in his name, but in the first one, you can't tell that right away with the shaman.

**Comment by Repooc** [comment]
We have nothing to do with private servers, let alone support them.
