### ISSUE TITLE
We have nothing to do with private servers, let alone support them.

### ISSUE THREAD

**Issue by cedevitaodnarandze213** [tukui-org/ElvUI#1076]
Bravo idiot, this does nothing to have wit hprivate servers... You solved nothing and you are useless. Just say you don't know how to fix it and move on

**Comment by Repooc** [comment]
> Bravo idiot, this does nothing to have wit hprivate servers... You solved nothing and you are useless. Just say you don't know how to fix it and move on

we dont work on any elvui meant for private servers and not support by us
