### ISSUE TITLE
ElvUI Disables Ability to change Action Bar colors and Keybind Text Positioning

### ISSUE THREAD

**Issue by PS1TD** [tukui-org/ElvUI#1077]
### What is the issue you are having?

When ElvUI is used in combination with Masque I can no longer change the colors of my action bar buttons or the positioning of the keybind text.
I have to disable Masque support, change colors and then reenable Masque.

### What is the expected behavior?

Ability to change color and keybind settings on action bars even when masque is enabled

### What actually happened?

Changing color setting does not open color picker.
Changing keybind text  settings does nothing.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
that is because the skin is to handle that and we are not.
