### ISSUE TITLE
Loot Frame Highlighting issue

### ISSUE THREAD

**Issue by NickBlackadar** [tukui-org/ElvUI#1078]
### What is the issue you are having?

I have "Loot Frame" unchecked on the General -> BlizzUI Improvements tab. Whenever I loot any mobs and have to scroll to see all the loot, some of the loot has this dark overlay on them. Every time I loot after this the items still have the overlay. I have to reload for it to go away.

![image](https://github.com/tukui-org/ElvUI/assets/145165432/fd51edd7-b422-4e89-ac6d-d898023d48c7)

### What is the expected behavior?

There should be no dark overlay on the items in the loot frame.

### What actually happened?

After scrolling down in the loot frame, some items get a dark overlay that persists until reloading ui.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please update to 13.48 and test if you still have the issue.

**Comment by NickBlackadar** [comment]
It's working better when there is only a little bit of a scroll bar but once you have to scroll down multiple items the issue returns. 
![image](https://github.com/tukui-org/ElvUI/assets/145165432/55442bf4-e9ce-4f55-ab6f-5594ac8d9674)

**Comment by 1Botanica1** [comment]
Try the dev version, there were some changes. 

 [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)  

Need to delete 
ElvUI 
ElvUI_Options
ElvUI_Libraries 
From your addons folder & place the new folders in.

**Comment by 1Botanica1** [comment]
ElvUI has since been updated. 

Update & test.

**Comment by kodewdle** [comment]
reopen if you still have the issue please :)
