### ISSUE TITLE
Toggle Anchors Bar not to be found

### ISSUE THREAD

**Issue by Qiyamat** [tukui-org/ElvUI#1079]
### What is the issue you are having?

At the very bottom of the Addon is and was always the Toggle Anchors Button. In my version it is not to be found. I simply find blank space where it once was. Would be nice if we this bugged would be fixed so I can move my bars. 

### What is the expected behavior?

Toggle Bars show 

### What actually happened?

Now Icon visiable

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Look at the top of the config for mover and you can always use the chat command to toggle them as well, the movement/rename of the button was in the change log within the past few version.
`/ehelp` for other chat commands as well
