### ISSUE TITLE
World zone text with outline 'Shadow' is not displayed properly after reload.

### ISSUE THREAD

**Issue by ohryk** [tukui-org/ElvUI#1082]
### What is the issue you are having?

The **World Zone Text** with **Outline=Shadow** is not displayed correctly when UI is reloaded.

### What is the expected behavior?

The text should be correctly outlined after UI is reloaded.

### What actually happened?

When you enable **World Zone Text** font override [General/Fonts/World Zone Text] and select **Font Outline = Shadow** it works only to the moment when you reload UI.

I have disabled all my addons except ElvUI and my custom media pack with **FiraSans** font but also I tried with the default **Expressway** font and the issue occurred as well.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
seems to be fixed in dev, closing this 👍
