### ISSUE TITLE
DataTexts/System script ran too long

### ISSUE THREAD

**Issue by LK-Webservices** [tukui-org/ElvUI#1083]
### What is the issue you are having?

I got the following LUA error:

`Message: ...rface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua:140: script ran too long
Time: Sat Nov 11 06:06:23 2023
Count: 1
Stack: ...rface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua:140: script ran too long
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua"]:140: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:94: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:84>

Locals: (*temporary) = <function> defined =[C]:-1
`

### What is the expected behavior?

Error should not happen

### What actually happened?

See the error I got.

### Errors

```shell
`Message: ...rface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua:140: script ran too long
Time: Sat Nov 11 06:06:23 2023
Count: 1
Stack: ...rface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua:140: script ran too long
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/System.lua"]:140: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:94: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:84>

Locals: (*temporary) = <function> defined =[C]:-1
`
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game 
`/edebug on` 

test, do you have the issue/error? 

If so, type in chat in game 
`/estatus`
And upload a full ui screenshot showing the issue/error and status panel.

**Comment by kodewdle** [comment]
no response for some time and can't reproduce, closing.
