### ISSUE TITLE
Can you please tell me what this is and how to remove it? 

### ISSUE THREAD

**Issue by Jaddle95** [tukui-org/ElvUI#1084]
Hello, im having this bar pop up since i last updated ELVUI. Any chance anyone can tell me how to disable it? Thanks 
![Screenshot 2023-11-11 120704](https://github.com/tukui-org/ElvUI/assets/150520135/aa1d4cf7-ced0-4822-85d1-cf5dc1302a02)

**Comment by Repooc** [comment]
looks like  elvui config->Nameplates->player

**Comment by Jaddle95** [comment]
thank you so much <3
