### ISSUE TITLE
Reagent Bank Deposit

### ISSUE THREAD

**Issue by syndenbock** [tukui-org/ElvUI#1085]
### What is the issue you are having?

When opening the reagent bank directly by holding shift when talking to a banker, reagents I deposit are landing in the normal bank, not the reagent bank. After switching to the normal bank and back to the reagent bank, it works properly.

### What is the expected behavior?

I expect reagents to always be deposited into the reagent bank when the reagent bank is open.

### What actually happened?

Reagents went into my normal bank instead.

### Errors

```shell
No errors occured.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type into chat 
`/edebug on` 
And test - do you have the issue? 

If so, type in chat in game 
`/eststus` 
And upload a full us screenshot showing the issue and the status panel. 

Also, please disable all addons & check with the blizzard UI

**Comment by syndenbock** [comment]
Yes, even with /edebugon, I still have the issue.

Here is the screenshot of /estatus:
![image](https://github.com/tukui-org/ElvUI/assets/29254285/871221f4-70a0-429f-aa4d-a31788372994)

I tried testing with the default UI, but the default UI always opens the normal bank tabs and doesn't go to the reagent bank when I hold shift when talking to the banker, so the problem doesn't happen.

**Comment by kodewdle** [comment]
thanks, fixed in dev 🌼
