### ISSUE TITLE
Heal Prediction for Healing-Over-Time Effects Missing

### ISSUE THREAD

**Issue by KevinTyrrell** [tukui-org/ElvUI#1087]
### What is the issue you are having?

Heal prediction overlay on the player's health bar for healing over time effects are missing.
This functionality previously existed but appears to be missing as of Version 13.48.

For example, the following spells have no healing prediction on the player's health frame
Lifebloom
Rejuvenation
Regrowth

This functionality **did** previously exist. I could not locate any such item in the changelog mentioning its removal.

### What is the expected behavior?

Upon casting a healing over time effect on yourself, a green overlay (healing prediction) should appear or grow based on the heal casted, and your current spellpower.

### What actually happened?

No such healing prediction overlay displays. Healing prediction does currently work for spells which have an instant-healing component (e.g. Healing Touch, Regrowth, Nourish).

### Suggested Solution/Workaround

Upon casting a healing over time-related spell, calculate the expected gain over the course of the healing effect's duration, then create a healing overlay accordingly. This functionality previously existed in Elvui for healing over time effects.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type in chat in game 
`/edebug on`

And test.  If you still have the issue type in chat in game 
`/estatus` 
And upload a full ui screenshot (no cropping) showing the issue and the status panel. 

Include a screenshot of the heal prediction settings also.

**Comment by kodewdle** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/2266754/dbefc92b-898a-4dfe-89ff-198859cd72d3)
