### ISSUE TITLE
Can't see quest reward selection.

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1088]
### What is the issue you are having?

Not sure if there is a highlight or not, but I can't see anything when I select a quest reward. All of them have a border and selecting one does nothing to change this.

### What is the expected behavior?

I expect to be able to clearly see which quest reward is currently selected.

### What actually happened?

Nothing.

### Suggested Solution/Workaround

Make it glow.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type into chat 
`/edebug on` 
And test - do you have the issue? 

If so, type in chat in game 
`/eststus` 
And upload a full us screenshot showing the issue and the status panel. 

Also, please disable all addons & check with the blizzard UI

**Comment by kodewdle** [comment]
no response for some time and can't reproduce, closing.
