### ISSUE TITLE
Action bar glow isn't working properly

### ISSUE THREAD

**Issue by ddhvr** [tukui-org/ElvUI#1092]
### What is the issue you are having?

Version: 13.48
I know you stated that the glow function has been fixed from 13.47 to 13.48.
However, it often glows when it should not which affects the gaming experience.

### What is the expected behavior?

It should glow when it's actually triggered.

### What actually happened?

I play as an outlaw rogue and my skill "pistol shot" often glows unexpectedly. It should provide me half the cost and at least 4 combo points with the latest build when it glows. But it just did not work sometimes until I turned off the elvui and found out the issue might be caused by it.

### Suggested Solution/Workaround

Maybe you can take a look at rogue's talent "subterfuge" & "Underhanded Upper Hand" since it's the core of outlaw this patch. I guess it may cause some issues if blizzard doesn't implement this properly.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [x] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Are you on release version or the dev version? 

If on dev, please go to release and test 

Type in chat in game 
`/edebug on` 

test.  Do you have the issue? 

If so, type in chat in game 
`/estatus` 
And upload a full ui screenshot showing both the issue and the status panel (no cropping the screenshot)

**Comment by ddhvr** [comment]
I eventually found out the issue was from Blizzard. There are 2 talents "Opportunity" & "Greenskin's Wickers" trigging the same button glow effect so that made me confused.
