### ISSUE TITLE
Unable to use keybinds after hiding action bars

### ISSUE THREAD

**Issue by dmusto** [tukui-org/ElvUI#1095]
### What is the issue you are having?

I use a macro to toggle my elvui action bars when I want to edit them and then toggle the macro to hide again (copied below). After the most recent update none of my keybinds work after I hide the action bars. I have been using this feature for ~3 years and never had an issue.

/run local bars, E = {1,6,3,4,5}, unpack(ElvUI); for _, n in pairs(bars) do local state = E.db.actionbar["bar"..n].enabled; E.db.actionbar["bar"..n].enabled = (state==false and true or false); E.ActionBars:PositionAndSizeBar("bar"..n) end

### What is the expected behavior?

Use my macro to hide my action bar and use my keybinds normally.

### What actually happened?

Use my macro and none of my keybinds work.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by jmazurek5914** [comment]
Same behavior here with elvui 13.51. I can't use spell (with keybinds) when action bar is disabled.

Workaround : Enable actionbar and set Alpha at 0% (ActionBars => Player Bars => Bar Settings => Alpha)

**Comment by 1Botanica1** [comment]
> Same behavior here with elvui 13.51. I can't use spell (with keybinds) when action bar is disabled.
> 
> Workaround : Enable actionbar and set Alpha at 0% (ActionBars => Player Bars => Bar Settings => Alpha)

That is one way - another way - see below. 

• Actionbars which were disabled but used for keybinds, now need to be enabled and visibility state changed to `hide` to work like before

From the changelog

**Comment by dmusto** [comment]
> > Same behavior here with elvui 13.51. I can't use spell (with keybinds) when action bar is disabled.
> > Workaround : Enable actionbar and set Alpha at 0% (ActionBars => Player Bars => Bar Settings => Alpha)
> 
> That is one way - another way - see below.
> 
> • Actionbars which were disabled but used for keybinds, now need to be enabled and visibility state changed to `hide` to work like before
> 
> From the changelog

Is there any macro option to manually toggle them now or will I need to manually re enable them every time I want to change my keybinds?

**Comment by Repooc** [comment]
> > > Same behavior here with elvui 13.51. I can't use spell (with keybinds) when action bar is disabled.
> > > Workaround : Enable actionbar and set Alpha at 0% (ActionBars => Player Bars => Bar Settings => Alpha)
> > 
> > 
> > That is one way - another way - see below.
> > • Actionbars which were disabled but used for keybinds, now need to be enabled and visibility state changed to `hide` to work like before
> > From the changelog
> 
> Is there any macro option to manually toggle them now or will I need to manually re enable them every time I want to change my keybinds?

As we don't really provide support for custom stuff like this, I will tell you that instead of toggling them enabled/disabled, you would be changing the visibility back and forth between `show` and `hide` instead
