### ISSUE TITLE
No Castbar for Hunter AS and MS

### ISSUE THREAD

**Issue by LiquidDew** [tukui-org/ElvUI#1096]
### What is the issue you are having?

Multishot and Aimed shot cast bars are missing in the most recent update

### What is the expected behavior?

Expect there to be castbars for Multishot and Aimed shot.

### What actually happened?

Disabled all addons except for Elvui, still am missing Multishot and Aimed shot castbars.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verified ElvUI is up to date by checking /estatus.
- [X] I have verified my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have verified my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
ElvUI is at 13.51 - please check at the top of the ElvUI menu in game is 13.51 - if not, update

If ElvUI is up to date & you still have the issue, please type in chat in game
`/edebug on`
and test  - do you still have the issue?

If so, type in chat in game, 
`/estatus`
and upload a full ui screenshot (no cropping) showing the issue and the status panel.

**Comment by UnderGut** [comment]
I confirm the bug

**Comment by Azilroka** [comment]
Classic doesn't have a castbar for AS or MS.

**Comment by kodewdle** [comment]
what he said, default UI is the same way in classic

**Comment by CZonin** [comment]
Same issue here. There was a cast bar for Aimed Shot in previous versions of ElvUI.

**Comment by 1Botanica1** [comment]
Which version of wow  

LibClassicCasterino

for classic hc 
20903 for aimed shot
14290 for multi

These spell ids aren't in the library for aimed or multi shot

**Comment by CZonin** [comment]
It's working again with the latest update. Thanks for the fix!

**Comment by CZonin** [comment]
Looks like this is broken again in 13.54

**Comment by Repooc** [comment]
Well the blizzard api returns incorrect data, we removed the library that faked the information. Your best bet is to find a wa to get what you want as we decided not to use a library just for 2 spells that blizzard is not returning the correct value for.
