### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Hendo72** [tukui-org/ElvUI#1099]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/39675478/08d6e255-f2cc-457e-b3f8-01fe57c59803)

### Describe the expected behavior and what actually happened?

We have 2 issues here.

1. Lua error: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1173: attempt to index local 
2. It's telling me to use the PTR version on Vanilla live.

### Reproducing the issue.

Error is thrown every time I reload the screen.

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1173: attempt to index local 'icon' (a nil value)
Time: Thu Nov 16 01:55:27 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:1173: attempt to index local 'icon' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1173: in function `HandleIcon'
[string "@Interface/AddOns/ElvUI/Classic/Modules/Skins/Character.lua"]:120: in function <...ace/AddOns/ElvUI/Classic/Modules/Skins/Character.lua:80>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:2019: in function <Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:2014>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1814: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1829: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1855: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1965: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:276: in function <Interface/AddOns/ElvUI/Core/init.lua:275>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Thank you for doing the troubleshooting.  I can see what the issue is straight away. 

Your ElvUI is out of date. 13.51 is current. 

If you are updating ElvUI & it is not showing updated in game, I suggest using wowup client to update.

**Comment by Hendo72** [comment]
LOL... i just downloaded 13.48 on Saturday. I didn't realize I was outdated.

**Comment by 1Botanica1** [comment]
Blizzard dropped a surprise patch, there were a few things to fix. :)
