### ISSUE TITLE
Barre de vehicule (commandes supplementaires)

### ISSUE THREAD

**Issue by Gilaax** [tukui-org/ElvUI#11]
Bonjour à tous,
j'ai elvui 12.44 et console port je joue manette sur wow et la barre de véhicule n'apparait pas quand necessaire ! je dois désactiver elvui pour qu'elle apparaisse, merci de me dire que faire pour palier à ce soucis recurrent;

**Comment by 1Botanica1** [comment]
The vehicle bar should appear automatically with ElvUI.  If it isn't appearing, then you have imported someones profile that has changed this or changed the function yourself. 

In action bar 1 - you need to have the visibility settings to have it show when in a vehicle. 
You should be able to reset the settings in Action Bar 1

This isn't an ElvUI bug - it is user settings.

**Comment by Gilaax** [comment]
est ce que console port ne ferait pas conflit ?

**Comment by 1Botanica1** [comment]
Please follow the instructions above.  

If you still have issues, please include screenshots of the visibility settings of Action Bar 1
