### ISSUE TITLE
Party Frames fade in combat 

### ISSUE THREAD

**Issue by WhiteFox99** [tukui-org/ElvUI#1100]
### Troubleshooting Steps

My friend is close to me in range but while in combat they show as far away.

![image](https://github.com/tukui-org/ElvUI/assets/151100401/ea12522e-5f9b-4c56-937a-aab8c2e80126)

### Describe the expected behavior and what actually happened?

When i am in combat the party frames fade away as if the players are far away from me. The "Range" box is ticked and the function works but the moment i am in combat it stops working or something else triggers it. I've checked other profiles as well and even made a new one with everything at default and the problem still occurs so it doesnt seem to be something i have ticked or triggered ( i hope) . 

![image](https://github.com/tukui-org/ElvUI/assets/151100401/f847dcbd-db24-4142-bf0e-c89f2d9b2761)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Thank you for including the information in your bug report. 

It is a known issue - blizzard dropped a surprise patch which broke range for addons in combat!!

there is a fix in dev which is currently being tested to help fix the issue. - https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip
