### ISSUE TITLE
It is no longer possible to modify anchors

### ISSUE THREAD

**Issue by KiwiWOW** [tukui-org/ElvUI#1104]
### Troubleshooting Steps

I ran the test several times and even disabled my other addons.
https://image.noelshack.com/fichiers/2023/46/5/1700225263-elvui.jpg
https://image.noelshack.com/fichiers/2023/46/5/1700225410-elvui2.png

### Describe the expected behavior and what actually happened?

When I open Elvui in-game, I no longer have the ability to move the anchors as I wish on all of my profiles. The command no longer exists, even when searching for it. It started with the 1st update after the release of 10.2, my elvui is up to date and I don't have any more Addons than before. (I use a translator, I apologize for any mistakes)

### Reproducing the issue.

Open Elvui in the WOW menu

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/5704821/961450e8-06e4-430c-a425-494da9764f4f)

Thanks you for including the screenshots 

It has just moved and renamed - as in the changelog. 

The commands `/emove` and `/moveui` still work also.
