### ISSUE TITLE
Totem Bar Shows CD Ready Flash When Set To Mouseover

### ISSUE THREAD

**Issue by macwille** [tukui-org/ElvUI#1106]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/40800682/22562bce-bc47-45ab-a0d4-6fba30f1c366)

### Describe the expected behavior and what actually happened?

I have my totem bar settings set to mouse over but when I come of a global cooldown Elvui shows a cooldown ready flash. This flash does not happen with any other action bars I've set on mouse over.

![image](https://github.com/tukui-org/ElvUI/assets/40800682/3b3cae09-d5c0-46f6-8cee-1eb5ad1df3cb)

### Reproducing the issue.

* 1. Set totem bar to mouse over
* 2. Start casting any spell and totem bar fill flash after a global finishes

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Thanks for including the screenshot with the status lan, but please go through all the troubleshooting steps. 
https://github.com/tukui-org/ElvUI/wiki/troubleshoot

**Comment by 1Botanica1** [comment]
Thanks for that. 

There were other addons enabled in your first post.  Edebug on disables all but ElvUI for troubleshooting.

**Comment by kodewdle** [comment]
fixed + now it also supports Hide Cooldown Bling general setting
