### ISSUE TITLE
Tooltip Lua Error

### ISSUE THREAD

**Issue by Skawt1** [tukui-org/ElvUI#1108]
### Troubleshooting Steps

Hi there,

I get a lua error related to the tooltip whenever I hover over items in my backpack or gear in the character customization.

![image](https://github.com/tukui-org/ElvUI/assets/151476117/404e0751-d8d8-40ab-a35d-a54c271945f4)
`Message: [string "return function() local bonusIds = {"]:64: attempt to concatenate local 'text' (a nil value)
Time: Sun Nov 19 18:00:38 2023
Count: 4
Stack: [string "return function() local bonusIds = {"]:64: attempt to concatenate local 'text' (a nil value)
[string "=[C]"]: ?
[string "return function() local bonusIds = {"]:64: in function <[string "return function() local bonusIds = {"]:52>
[string "return function() local bonusIds = {"]:95: in function <[string "return function() local bonusIds = {"]:74>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ContainerFrame.lua"]:1519: in function `OnUpdate'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1486: in function `OnEnter'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1482: in function <Interface/FrameXML/ContainerFrame.lua:1481>
[string "=[C]"]: ?

Locals: (*temporary) = <function> defined =[C]:-1
`

### Describe the expected behavior and what actually happened?

Expected behavior: Not having any lua error.

What actually happened: invasive lua error 100% repro whenever I hover over items in the backpack.

### Reproducing the issue.

hover over items in the backpack and have the tooltip show.

https://github.com/tukui-org/ElvUI/assets/151476117/fddbd82f-2712-40b6-9717-0619025aa33d

### Lua Errors

```shell
Message: [string "return function() local bonusIds = {"]:64: attempt to concatenate local 'text' (a nil value)
Time: Sun Nov 19 18:00:38 2023
Count: 4
Stack: [string "return function() local bonusIds = {"]:64: attempt to concatenate local 'text' (a nil value)
[string "=[C]"]: ?
[string "return function() local bonusIds = {"]:64: in function <[string "return function() local bonusIds = {"]:52>
[string "return function() local bonusIds = {"]:95: in function <[string "return function() local bonusIds = {"]:74>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:162: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:157>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:182: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:178>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:218: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:208>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:243: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:389: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:339>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:336: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:335>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/ContainerFrame.lua"]:1519: in function `OnUpdate'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1486: in function `OnEnter'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1482: in function <Interface/FrameXML/ContainerFrame.lua:1481>
[string "=[C]"]: ?

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
There are so many addons enabled in that screenshot 

Thanks for including the status panel and error but that first part of the troubleshooting needs to be done. 

Type in chat in game 
`/edebug on` 

test - do you have the issue?  

If so, type in chat in game 
`/estatus`

and upload a full ui screenshot showing both the issue/error and the status panel. 

If you get the error after the troubleshooting, disable all addons & test with the blizzard UI
