### ISSUE TITLE
Lua Error Retail

### ISSUE THREAD

**Issue by Phoenixstyle87** [tukui-org/ElvUI#1109]
### Troubleshooting Steps

Dont know what to do

### Describe the expected behavior and what actually happened?

Wanted to Log-in after a felt decade. After Updating everything i wanted to make my UI and i get this Errors the whole time.

### Reproducing the issue.

![lua error](https://github.com/tukui-org/ElvUI/assets/151553818/be3b27ab-32ec-4742-8dac-1a4942e72da6)

### Lua Errors

```shell
Message: .../Core/Modules/UnitFrames/Elements/HealPrediction.lua:92: attempt to index local 'db' (a boolean value)
Time: Mon Nov 20 16:58:46 2023
Count: 1
Stack: .../Core/Modules/UnitFrames/Elements/HealPrediction.lua:92: attempt to index local 'db' (a boolean value)
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/Elements/HealPrediction.lua"]:92: in function `Configure_HealComm'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/Groups/Raid.lua"]:124: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:905: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:859: in function `ExecuteForChildren'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:925: in function `Update'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:883: in function `Update'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1083: in function `CreateAndUpdateHeaderGroup'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1149: in function `LoadUnits'
[string "@Interface/AddOns/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1823: in function `func'
[string "@Interface/AddOns/ElvUI_Libraries/Core/oUF/factory.lua"]:20: in function <...nterface/AddOns/ElvUI_Libraries/Core/oUF/factory.lua:16>
[string "=(tail call)"]: ?

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Phoenixstyle87** [comment]
![lua mit status](https://github.com/tukui-org/ElvUI/assets/151553818/26bb11ea-f6c2-4fce-96e2-5956d468f02e)

**Comment by Repooc** [comment]
try running `/efixdb`
