### ISSUE TITLE
Option to change "Modifier Key" for "QuickDTMode", it's Hardcoded to LALT and RALT

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#1112]
### Troubleshooting Steps

Hi there,

this is not a bug per se but would be nice to have the ability to change the Modifier Key for your function ``QuickDTMode`` as of it is Hardcoded in ``DataTexts.lua`` line 73 with ``if DT.SelectedDatatext and (key == 'LALT' or key == 'RALT') then``.

I know i can change it **manually** every Update of ElvUI but would be **WAY BETTER** if it will be changeable it in the Config and also will get saved in the Global Profile!

greetings

### Reproducing the issue.

no issue

### Lua Errors

```shell
no
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
This prob won't be implemented as doing so would overlap the modifier and would require recoding some of the datatexts and don't feel its worth the effort.

**Comment by fubaWoW** [comment]
Yeah...
It is overall kinda stupid to **"Hardcode"** anything that is Final State or better say a "non Test State" in a Big Project like ElvUI but... ok 🤦‍♂️
So i will change it for myself 👍

**Comment by Azilroka** [comment]
You would need to recode all modifiers to do it.. like take the volume datatext.. you would need to have it coded to support alt, ctrl, shift and meta. Alt was picked for quick dt because there isn't any of our datatexts that use it currently.
