### ISSUE TITLE
Title here

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1114]
### Troubleshooting Steps

Text tags do not show empty values.

### Describe the expected behavior and what actually happened?

`[power:current:shortvalue]` and `[power:percent]` show nothing when power is zero. This is not helpful. I can see why it works this way for Health, although I would still rather have control.

### Reproducing the issue.

Use the provided tags. Probably others.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
I’m not sure if any of the power tags show at zero. 

There is an addon to code the tags yourself https://www.curseforge.com/wow/addons/elvui-tinkertoolbox
You can use that to create new tags to your liking.

**Comment by kodewdle** [comment]
these tags won't be changed as too many people already use them in the current state and it would mess with too many peoples profiles.
