### ISSUE TITLE
Your github form is borked.

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1115]
### Troubleshooting Steps

<img width="316" alt="lol" src="https://github.com/tukui-org/ElvUI/assets/1219653/d44a8d0f-440a-4e20-9ad6-4a955e7b47f6">

### Describe the expected behavior and what actually happened?

Double placeholder text.

### Reproducing the issue.

Open a github issue.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
I am not seeing the issue 

![image](https://github.com/tukui-org/ElvUI/assets/5704821/9d11332c-c583-4cb3-b155-71c7ed720dae)

**Comment by kodewdle** [comment]
https://github.com/orgs/community/discussions/76619
