### ISSUE TITLE
Spells not working if Action Bars hidden

### ISSUE THREAD

**Issue by A-DVS-NTT** [tukui-org/ElvUI#1116]
### Troubleshooting Steps

![World Of Warcraft Screenshot 2023 11 22 - 14 43 22 71](https://github.com/tukui-org/ElvUI/assets/132249721/122fbb60-c23d-447a-a409-ed077dfb7a7f)
![World Of Warcraft Screenshot 2023 11 22 - 14 49 16 12](https://github.com/tukui-org/ElvUI/assets/132249721/4c5f183d-3699-4182-bc88-147b24239898)

### Describe the expected behavior and what actually happened?

I use a macro to hide my action bars whenever I'm not moving spells around (Full macro present in screenshot, as well as my screen with and without the action bars hidden). While the action bars are hidden, none of the spells that are on them work. If the action bars are showing, then all spells work as normal.

### Reproducing the issue.

I was previously using ElvUI 13.51 with no issues. Upon installing 13.52, this issue began happening. I reverted back to 13.51 and now the issue is present under that build as well. Reverting to 13.47 removed the issue and allowed my action bars to function as normal while hidden.

Any other keybinds that are not on these bars, such as movement and menu binds work as normal, it is just the binds on the hidden bars that are not seeming to work.

### Lua Errors

```shell
No Lua Errors are produced
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
use `hide` in visibility state input box for that bar with it enabled
