### ISSUE TITLE
[Retail Bug Report] <Nameplate overlap>

### ISSUE THREAD

**Issue by Browningmzwo** [tukui-org/ElvUI#112]
### What is the issue you are having?

If i change the setting for nameplate overlapping it resets automaticly after the next login.
![InkedWoWScrnShot_120321_084735](https://user-images.githubusercontent.com/95477871/144594247-742127f3-b684-489b-8b76-c4f0dd714af1.jpg)

I set the overlap to 1.7/1.7

![InkedWoWScrnShot_120321_092259](https://user-images.githubusercontent.com/95477871/144594315-fccd37a8-974a-40c4-9ea4-4838483a81a0.jpg)

When i start wow next time it resets to 0.8/1.1

I already try to solve the problem with:

- 1) Type in chat in game /edebug on
- reset cvars
 
I cant solve it.

### What is the expected behavior?

x

### What actually happened?

x

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Repooc** [comment]
if those settings are resetting then that is a wow issue as they are blizzard settings which we expose for the user to easily change them.  either some or all of your WTF folder may be set to read only or something but def not an elvui issue as all we do is use their api to ask what the setting is set to and display what it returns, and when u change the setting, we use their api to say what the setting you are setting it to
