### ISSUE TITLE
ELvUI load upon demand

### ISSUE THREAD

**Issue by Bradn8pc** [tukui-org/ElvUI#1123]
### Troubleshooting Steps

can not run the / commands 

### Describe the expected behavior and what actually happened?

when loading Addons this is what I get.  ELvUI loaded upon demand

### Reproducing the issue.

I can not run those commands  
![image](https://github.com/tukui-org/ElvUI/assets/65867171/0b658dc9-e2e6-41af-8cca-32d549681d24)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
That is a very old version of ElvUI you have. 

Are you playing on a private server? 

This is where to download ElvUI https://tukui.org/elvui
Not sure where you go that copy from but it isn’t a supported version.

**Comment by Repooc** [comment]
They are playing on a private server and I banned them for insults & to continue to ask when we told them that we do not support it and not to ask about it.
