### ISSUE TITLE
Paused portrait still animates.

### ISSUE THREAD

**Issue by dailytabs** [tukui-org/ElvUI#1124]
### Troubleshooting Steps

13.52

### Describe the expected behavior and what actually happened?

Player portrait, 3d, pause.
Shadow priest, shadowform effects are still moving.

Can't just cache a pic?

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Please go through the troubleshooting steps 
https://github.com/tukui-org/ElvUI/wiki/troubleshoot

**Comment by Repooc** [comment]
To add to this, no the option paused, is for 3d model, so no there is no "pic" to cache. SetPaused is used on the element which is a blizzard api that just stops the model from doing actions (like walking, running, and so on...). ElvUI does not control what is not animated/moving when using their api.
