### ISSUE TITLE
Getting Lua error on Elvui

### ISSUE THREAD

**Issue by Aksyless** [tukui-org/ElvUI#1126]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/152735732/ac4c640d-cbbc-49c3-a1b1-3f5b243593e6)

### Describe the expected behavior and what actually happened?

Getting this error when trying to check Raider Io score only for applying groups. On normal UI this error doesnt exist so its something with elvui.

### Reproducing the issue.

i used this debug and nothing changed

### Lua Errors

```shell
Message: Interface/FrameXML/LFGList.lua:1877: bad argument #1 to 'format' (string expected, got nil)
Time: Sat Dec  2 20:53:26 2023
Count: 3
Stack: Interface/FrameXML/LFGList.lua:1877: bad argument #1 to 'format' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `format'
[string "@Interface/FrameXML/LFGList.lua"]:1877: in function <Interface/FrameXML/LFGList.lua:1851>

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Aksyless** [comment]
Oh i understand, thank you for your reply and sry for taking your time then ^^

**Comment by Repooc** [comment]
no worries, been posted a lot in our discord as well
