### ISSUE TITLE
Lua Error 

### ISSUE THREAD

**Issue by voidposterzsx** [tukui-org/ElvUI#1127]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/152853087/a3e0521d-40f4-4107-b1b6-8bd9b7ed5fe1)

### Describe the expected behavior and what actually happened?

The expected behaviour is that i click on myself and i target myself, this does happen and works but the error popping up is very frustrating to deal with as i need to reload my UI everytime

EDIT: i realised my Elvui was out of date, I have since updated and I am still having the issue.
### Reproducing the issue.

Click on my healthbar as displayed on the left

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:81: bad argument #3 to 'SetFormattedText' (string expected, got nil)
Time: Mon Dec  4 08:27:23 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:81: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface/AddOns/ElvUI/Core/General/Cooldowns.lua"]:81: in function `Cooldown_OnUpdate'
[string "@Interface/AddOns/ElvUI/Core/General/Cooldowns.lua"]:128: in function `Cooldown_TimerUpdate'
[string "@Interface/AddOns/ElvUI/Core/General/Cooldowns.lua"]:254: in function <Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:229>
[string "=[C]"]: in function `SetCooldown'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1769: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1755>
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1525: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1464>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/SecureTemplates.lua"]:523: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:779: in function <Interface/FrameXML/SecureTemplates.lua:764>

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This error is from having Redtuzk UI installed at some point which has caused an error in the CD module (or imported someone’s profile that had it). 

You can try 
ElvUI - Profiles - Module Reset 
Reset the Cooldown module 

Hopefully that should work,  if it doesnt, you will need to create a new profile.

**Comment by voidposterzsx** [comment]
Resetting fixed my issue thank you for the help!
