### ISSUE TITLE
Spells don't work on disabled action bars

### ISSUE THREAD

**Issue by pr4ndy** [tukui-org/ElvUI#1128]
### Troubleshooting Steps

![Screenshot 2023-12-04 162958](https://github.com/tukui-org/ElvUI/assets/152872562/14f8070a-b63d-465c-b61f-42f7dde3ad83)

### Describe the expected behavior and what actually happened?

When action bar is disabled then you can't use spells on it. All spells work well if the bar is enabled (hidden or not it doesn't matter). This issue happens since 13.49 version. 13.48 works well for me.

### Reproducing the issue.

1. Add spell on action bar
2. Toggle checkbox "enable" to disable action bar
3. Now you can't use this spell

### Lua Errors

```shell
There are no lua errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Yes, there has been a change to improve the performance of ElvUI
The bars that are disabled now cannot be used - they are properly disabled.

There is already an option to put hide in the action bar visibility state

• Actionbars which were disabled but used for keybinds, now need to be enabled and visibility state changed to hide to work like before

From the changelog

Duplicate of https://github.com/tukui-org/ElvUI/issues/1095

**Comment by pr4ndy** [comment]
Thank you for your response. Sorry for duplicating the issue.
