### ISSUE TITLE
40man raid frames won't show and when 6-10 people are in raid.

### ISSUE THREAD

**Issue by Icesinn** [tukui-org/ElvUI#1131]
### Troubleshooting Steps

I may be unable to find the setting but I cannot see any of the raid past group 5. I've checked forums posts, YouTube and have found no solution as they were outdated. It's been like this for a quite a few months and I'm finally seeking help. The picture is taken from SoD (classic era) however it is the exact same as the WOTLK Elvui addon to my knowledge.

### Describe the expected behavior and what actually happened?

It's most likely not a bug but rather a setting I've screwed around with too much. Nothing happens just cannot see groups 6-8. This also seems to not show my raid frames when I go between 6-10 people. Updating does hasn't solved my issue.

![UI](https://github.com/tukui-org/ElvUI/assets/153392581/e6f84c76-ccfe-4b96-9d0b-140813616991)
![UI2](https://github.com/tukui-org/ElvUI/assets/153392581/c46ce532-2249-456e-b8f3-f6649af33276)
![UI3](https://github.com/tukui-org/ElvUI/assets/153392581/290fb8d0-a193-46ad-b633-978fa0b0c431)
![UI4](https://github.com/tukui-org/ElvUI/assets/153392581/e4fdd462-5d48-4df2-98b9-8b6bc7f7177d)
![UI5](https://github.com/tukui-org/ElvUI/assets/153392581/9872b15e-91d1-4159-8e63-b0ece168ac16)
![UI6](https://github.com/tukui-org/ElvUI/assets/153392581/c369c78b-0258-4f01-868d-d61dcd62d385)
![UI7](https://github.com/tukui-org/ElvUI/assets/153392581/d05175ef-ab4a-4484-9be1-f6a73afc1c2c)
![UI8](https://github.com/tukui-org/ElvUI/assets/153392581/745fef57-7e46-43e3-8732-93014fb7751d)
![edebug-on](https://github.com/tukui-org/ElvUI/assets/153392581/ee7588f2-c04d-4398-b1c6-61b34fbfe0d5)

### Reproducing the issue.

Just going into a raid. 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [x] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
You didnt show all the settings for raid 3 -> general as you scrolled all the way down and didnt show Number of Groups option which I am assuming is set to 5 instead of 8

**Comment by Icesinn** [comment]
Wait that's in there? I've been blind this entire time?!

**Comment by Repooc** [comment]
Also, we have a discord server for questions like this at https://discord.tukui.org/

**Comment by Repooc** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/1479745/2ae9c826-b88d-48ee-be2c-ec23b2d29827)
scroll up

**Comment by Icesinn** [comment]
Okay so I did that and set the number of groups. Would that also be the fix for seeing the raid when I have 6-10 people? I'm normally able to see the 5 in my party but once a 6th gets added it doesn't show.

**Comment by Repooc** [comment]
by default if you have 6-10 people in your raid group, you should see raid 1 (assuming you have number of groups set properly)
`Party: [@raid6,exists][nogroup] hide;show
Raid 1: [@raid6,noexists][@raid21,exists] hide;show
Raid 2: [@raid21,noexists][@raid31,exists] hide;show
Raid 3: [@raid31,noexists] hide;show`

**Comment by Repooc** [comment]
quick glance, looks like raid 2 and 3 would show for you when u were over 25 people... might want to adjust ur settings

**Comment by Icesinn** [comment]
This would mean raid 2 goes up to group 6, I've changed to these settings you told me to.

> quick glance, looks like raid 2 and 3 would show for you when u were over 25 people... might want to adjust ur settings

**Comment by 1Botanica1** [comment]
You can also drag the bottom right of the ElvUI menu to expand it to see all the options.

**Comment by Icesinn** [comment]
Thank you for the help, just need to get myself some eyeballs and read a bit more.

**Comment by Icesinn** [comment]
Okay now it's not displaying anything at 30 players. but pops up at 31.
![UI9](https://github.com/tukui-org/ElvUI/assets/153392581/d110bda9-22d9-40e5-8b57-e0f8754771b8)

**Comment by 1Botanica1** [comment]
You have the visibility settings wrong for raid 2 

Copy the visibility settings Repooc posted above

**Comment by 1Botanica1** [comment]
This section is for reporting bugs.  For support, please use discord.

**Comment by Icesinn** [comment]
> This section is for reporting bugs. For support, please use discord.

Okay, I'm done here thank you for all the help. I joined the discord. I will go there for future problems.
