### ISSUE TITLE
SOD. Enemy player cast bar

### ISSUE THREAD

**Issue by AleksandrOrlov** [tukui-org/ElvUI#1132]
### Troubleshooting Steps

1. Turn on blizzard interface setting "Show enemy cast  bar"
2. Try duel - enemy player cast bar not showing

### Describe the expected behavior and what actually happened?

Blizzard add option to interface "Show enemy cast bar" on SOD, but ElvUI not show **player** cast bars on nameplates and unit frames. Cast bar correctly working only on mobs

Trying turn off other cast bar option - no result. Turn off elvui unitframe and i see enemy cast bar

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is a known issue - when reporting errors, please give all the requested information as requested. 

No ETA on fix.  YOu can enable blizzard castbars in the Unitframe - General for the moment as a workaround.

**Comment by AleksandrOrlov** [comment]
> This is a known issue - when reporting errors, please give all the requested information as requested.
> 
> No ETA on fix. YOu can enable blizzard castbars in the Unitframe - General for the moment as a workaround.

Thank you. How i can do this? i tried 
![image](https://github.com/tukui-org/ElvUI/assets/21103301/73350b27-0352-4fd6-b66f-ae57af139f8c)

but it still not working

**Comment by 1Botanica1** [comment]
Did you reload as it asked?

https://cdn.discordapp.com/attachments/222356141785612288/1168047622028800000/Wow_BvyTX0OENd.mp4?ex=6587b71e&is=6575421e&hm=ad684bf1f14272d6077a881c094d1e89e0f4e5dfa22aaae2bf124df93a6b3079&

This shows for the player unitframe, but it is the same concept.

**Comment by 1Botanica1** [comment]
Update ElvUI - it has been fixed.
