### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Milky063** [tukui-org/ElvUI#1133]
### Troubleshooting Steps

done

### Describe the expected behavior and what actually happened?

32x ElvUI/Core/General/Math.lua:311: script ran too long
[string "@ElvUI/Core/General/Math.lua"]:311: in function <ElvUI/Core/General/Math.lua:311>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "collect"
(*temporary) = 0
(*temporary) = "script ran too long"
func = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
data = <table> {
 1 = "collect"
}

### Reproducing the issue.

was in a dungeon

### Lua Errors

```shell
32x ElvUI/Core/General/Math.lua:311: script ran too long
[string "@ElvUI/Core/General/Math.lua"]:311: in function <ElvUI/Core/General/Math.lua:311>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "collect"
(*temporary) = 0
(*temporary) = "script ran too long"
func = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
data = <table> {
 1 = "collect"
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
No, you haven't done the troubleshooting steps - see here https://github.com/tukui-org/ElvUI/wiki/troubleshoot

**Comment by Milky063** [comment]
im just posting the error. if you want to fix it go for it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 1Botanica1** [comment]
You need to do the troubleshooting steps (which is why they are specifically mentioned for you to do) - no use just posting some random error
