### ISSUE TITLE
"Smooth Bars" not smooth (for castbars)

### ISSUE THREAD

**Issue by tjanok** [tukui-org/ElvUI#1134]
### Troubleshooting Steps

![Screenshot 2023-12-12 131101](https://github.com/tukui-org/ElvUI/assets/8595236/7775c06d-6caa-490b-b9a7-1ed72d3ccf8e)

### Describe the expected behavior and what actually happened?

Animations on "bars" appear "jerky" or "slow". "Smooth Bars" option enabled/disabled doesn't seem to change anything, along with "smoothing amount" slider.

https://github.com/tukui-org/ElvUI/assets/8595236/65804194-8790-47f4-b929-0fe23712f561

Attached is a video of ElvUI compared to Quartz. 

### Reproducing the issue.

Fresh ElvUI install, show cast bar. Watch as the bar transitions. More noticeable on long duration.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
this don't apply to castbar, only health/power/altpower atm.
