### ISSUE TITLE
[Feature Suggestion] Raid Frames and Indicators

### ISSUE THREAD

**Issue by ZickZak** [tukui-org/ElvUI#1136]
### Troubleshooting Steps

-

### Describe the expected behavior and what actually happened?

I'd love to use ElvUI raid frames, but there's not enough settings. Can you look at Grid2 and borrow some of its features? 
 - Mainly indicators (like colored corners when healing dot is up), colored health bars (for example for boss debuff)... 
 - Grid2 has preset boss debuffs for all dungeons and raids, so you can go through them and enable the ones you want and add them to 5 cathegories, which can display in any of the indicators. For example orange health color for explosion, green health color for stack... there are also indicators like "Reduced healing" or "Prevent healing", "Dungeon role" is awesome and "You", "Low Health" etc.
 - Grid2 also has option to change unitframe height and width based on how many players are in the raid. So going from 25 to 26 can simply make the bars smaller and keeps the overall raid frames size. Depends on how you set it up.
 - Grid2 is the best healing addon out there. Look at its features if you ever need an inspiration on how to improve yours.

![WoWScrnShot_121523_080254](https://github.com/tukui-org/ElvUI/assets/117012525/75ab2ee3-8401-47eb-88c9-802996928587)
![WoWScrnShot_121523_084248](https://github.com/tukui-org/ElvUI/assets/117012525/c565fb23-d923-43a1-9190-5627d3ed5cb9)

### Reproducing the issue.

-

### Lua Errors

```shell
-
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
ElvUI already has coloured squares (or the spell icon) when you have a healing buff, it is called aura indicators. 

You can have a coloured health bar when there is a debeff you can dispel and you can add aura to it if you want to see specific debuffs (or buffs) to highlight the bars - aura highlight 

There are 3 Raid frames.  You can add more and have different raid frames to shows for any number of people in the raid. There isn't an option in ElvUI to dynamically change the raid frame size, but you can manually set it up.

**Comment by kodewdle** [comment]
just use grid 2 🌼
