### ISSUE TITLE
Hunter hostile target unitfrMout of range fading at 30yards

### ISSUE THREAD

**Issue by onekiu** [tukui-org/ElvUI#1137]
### Troubleshooting Steps

Playing hunter, the target unitframe is already fading out at ~30yards.

![WoWScrnShot_121523_151604](https://github.com/tukui-org/ElvUI/assets/42302516/7a3af650-d263-4744-aad5-a87ccded0af9)

### Describe the expected behavior and what actually happened?

Most/all shots of the hunter in classic have an untalented 35 yards range in classic. As you can see on the screenshot, the auto shot ability is toggled while the unit frame is faded out like it would be out of range. It starts fading in at about 30 yards.

### Reproducing the issue.

Happens always, no matter where or which target.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
https://github.com/WeakAuras/LibRangeCheck-3.0/issues

**Comment by 1Botanica1** [comment]
Blizzard doesn't have range check in classic so a library is used by addons, including ElvUI.  

The link above is to the library ElvUI's uses. 

If you want a particular class to be looked at, create a ticket for the authors of the library to investigate

**Comment by kodewdle** [comment]
should be fixed by: https://github.com/tukui-org/ElvUI/commit/e9a8528de19d4a974ebaed6cec616d803a00925f which is a modification of the LibRangeCheck to address https://github.com/WeakAuras/LibRangeCheck-3.0/issues/16

**Comment by kodewdle** [comment]
should be fixed (better) by: https://github.com/tukui-org/ElvUI/commit/170e66ebe2e01b0f7a28cca1aa0c1b01a3826263
