### ISSUE TITLE
Vehicle keybind does not work. Worked in previous version

### ISSUE THREAD

**Issue by soulhon** [tukui-org/ElvUI#1141]
### Troubleshooting Steps

Board any vehicle to load the vehicle UI. Have skills on the vehicle. Have preset keybinds. (1 2 3 works fine too). pressing the preset keys will not work
![image](https://github.com/tukui-org/ElvUI/assets/44266801/aecef1ca-ebb6-4f28-bc94-af4646828e52)

### Describe the expected behavior and what actually happened?

WotLK, ICC raid dungeon, professor boss, drink the potion and enter the "vehicle gundam man"
Previous Elvui version works, after boarding the "gundam" 1 2 3 can absorb water, slow goo, asnd apply damage boss buff.
After Dec 20 version updates, Keys 1 2 3 does not work on the vehicle bar. Mouse clicking the button works.

P.S. I do not have bartender installed as that seems to be a common UI conflict problem. I do not have any other UI addons. Only addons I have other than ElvUI is Weakauras and Deadly Boss mod

### Reproducing the issue.

Just board any vehicle to load the vehicle UI

### Lua Errors

```shell
No LUA errors presented
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Need to go through all the troubleshooting steps, not just some. 

Type in chat in game 
`/edebug on` and test 

If you have the issue, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing the issue and the status panel. 

Type `/fstack` and mouse over action bar - and upload a screenshot.

**Comment by kodewdle** [comment]
no response for some time and can't reproduce, closing.
