### ISSUE TITLE
Enemy Channeling Castbar does not display

### ISSUE THREAD

**Issue by RandleStevens** [tukui-org/ElvUI#1143]
### Troubleshooting Steps

When targeting myself or another player channeled spells do not register in the Target Castbar.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Blizzard doesn't provide castbars for some spells 

Penance is one, multi shot & aimed shot are others. 

You will need a WA for those or an addon that provides the castbar that blizzard doesn't.
