### ISSUE TITLE
SoD - "Energy/Mana Regen Tick" resetting despite using "Fury of Stormrage" rune on druid.

### ISSUE THREAD

**Issue by Altronee** [tukui-org/ElvUI#1146]
### Troubleshooting Steps

1. Type in game: /edebug on (or /ec, on left [Information], on top [Debug])
2. Test. Still have the issue? 
**YES** 
3. Upload a full, uncropped screenshot showing the issue and the status panel.

![image](https://github.com/tukui-org/ElvUI/assets/112508674/71d01b5f-5423-4ffa-995f-d31f4a9d0aea)

![MP5 tic](https://github.com/tukui-org/ElvUI/assets/112508674/0d2bf61c-f9bf-4c1c-a726-f1a3326175b7)

### Describe the expected behavior and what actually happened?

When using the rune "Fury of Stormrage" on druids which makes Wrath cost 0 mana and allow for non-casting mana regen ElvUI still shows the mana tick as if it did cost mana and triggering the MP5 rule. 

### Reproducing the issue.

Equip Fury of Stormrage rune, have "Energy/Mana Regen Tick" enabled in player power options. Attack mob with wrath and see the tick reset after every finished cast, despite not actually resetting the 5s rule. 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
Thanks to @ToddSisson this is fixed in dev 💯
