### ISSUE TITLE
[Feature Suggestion] Synchronize specific actionbars between talent loadouts

### ISSUE THREAD

**Issue by noelrosen** [tukui-org/ElvUI#1147]
### Troubleshooting Steps

-

### Describe the expected behavior and what actually happened?

What i suggest is a feature where you can synchronize selected actionbars between different talent loadouts.

Right now all the spells/macros/etc change when you swap talents. As someone who likes to keep mounts etc on my actionbars but also run multiple talent builds this can get frustrating. Preferably this would add the option for each individual actionbar to be synchronized or not via a checkbox.

* More specifically I want to be able to check a box on every individual actionbar under "Player Bars" and then have the changes made to that actionbar apply and be synced when i later swap talents. 
* If this actionbar houses some spells that are unlearned when swapping talents they would be greyed out like they normally are if they stay on the actionbar.

Thank you for reading and i hope this will be concidered :)

### Reproducing the issue.

-

### Lua Errors

```shell
-
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
We would not implement such feature as this is a bit beyond what we would want to do with ElvUI and rather just let wow handle the spells on the actionbars with talent swaps as they do now with the basic setting they have already. We would recommend this type of thing to be done in an external plugin for elvui or another addon in general to give this feature set you wish to have.
