### ISSUE TITLE
[Feature Suggestion] Color unit frames for selected buffs

### ISSUE THREAD

**Issue by Darkhibaris** [tukui-org/ElvUI#1148]
### Troubleshooting Steps

Hi,

The ElvUI_BuffHighlight mode (https://github.com/Vekkt/ElvUI_BuffHighlight) unfortunately no longer works with the latest versions of Elvui. This feature came in handy to lighten the reading of unit frames and quickly identify players with certain buffs.

Would it be possible to add the functionality of coloring unit frames according to the buffs we've chosen (as you've done for debuffs)? This could be done via filters, for example (see model below for the spell "Atonement"). IIt would be ideal if the buff time countdown could always be parameterized.

![Elvui_uniteframe_color_buff](https://github.com/tukui-org/ElvUI/assets/118050158/ecaae937-c002-445a-beb2-ba3f222dc9b8)

### Describe the expected behavior and what actually happened?

-

### Reproducing the issue.

-

### Lua Errors

```shell
-
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
You can already color the Unitframe based on an aura with the Filter -> Aura Highlight option

**Comment by Darkhibaris** [comment]
Thank you for your quick answer!
Sadly, I can't find where we can do that. Could you show me with a screenshot please?

**Comment by Darkhibaris** [comment]
Found it! Thank you again :)
