### ISSUE TITLE
modifier (alt,ctrl,shift) action paging not working on 13.54, worked in 13.47

### ISSUE THREAD

**Issue by Clonedpirate** [tukui-org/ElvUI#1149]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/2270129/8decd800-5b6a-48f8-92e5-c96044b024b3)

### Describe the expected behavior and what actually happened?

This was working just fine in version 13.47, when I updated to 13.54 the action bars showed up empty when doing action bar switching via modifier keys. 
fx. when i press alt, the actionbar will switch to actionbar2. This shows as empty. 
To proof that its not in fact empty, i have enabled it next to the real bars in the below screenshot.
![elvui_bug1](https://github.com/tukui-org/ElvUI/assets/2270129/8a894f14-3b4d-42d2-88c6-3b5c2c2a57f1)
[elvui-13.54.zip](https://github.com/tukui-org/ElvUI/files/13862998/elvui-13.54.zip)

Here is the action bar paging setup i'm using:
Bar1:
[mod:shift] 5; // Important ability
[mod:alt] 13;   // Defensive ability
[mod:ctrl]10; // Utility ability
[stance:2] 8;
[bonusbar:3] 9;
[bonusbar:5] 11;

Bar7:
[nomod] 7; // Important ability
[mod:shift] 2; // Important ability
[mod:alt] 3; // Defensive ability
[mod:ctrl] 6; // Utility ability

### Reproducing the issue.

Using the below actionbar paging setup, only bar1 with nomod and shift is working. All others shows up as empty and will act as empty also.  (They are not empty if you enable the bars directly)
Bar1:
[mod:shift] 5; // Important ability
[mod:alt] 13;   // Defensive ability
[mod:ctrl]10; // Utility ability
[stance:2] 8;
[bonusbar:3] 9;
[bonusbar:5] 11;

Bar7:
[nomod] 7; // Important ability
[mod:shift] 2; // Important ability
[mod:alt] 3; // Defensive ability
[mod:ctrl] 6; // Utility ability

### Lua Errors

```shell
No errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Clonedpirate** [comment]
It is also worth noting that if I switch back to the elvui version 13.47, it is working fine again. So for now i will try to stick to this version.

**Comment by 1Botanica1** [comment]
Are the action bars you are trying to page to enabled or are they disabled?

**Comment by Clonedpirate** [comment]
Hi, 
thanks for your reply. I have again upgraded to 13.54 to check if it would help to enable all the bars and just set it to mouseover. 
Here is a screenshot showing that i have enabled the bars:
![image](https://github.com/tukui-org/ElvUI/assets/2270129/bb354a26-6b41-4393-9bda-1cb58da97bec)

The action page settings are the following:
Bar1:
[mod:shift] 5; // Important ability
[mod:alt] 13;   // Defensive ability
[mod:ctrl]10; // Utility ability
[stance:2] 8;
[bonusbar:3] 9;
[bonusbar:5] 11;


Bar7:
[nomod] 7; // Important ability
[mod:shift] 2; // Important ability
[mod:alt] 3; // Defensive ability
[mod:ctrl] 6; // Utility ability

With version 13.54 and the bars enabled in mind, for some reason shift is working for bar1. This means that if i press shift, then it will show bar5 on bar1. (I hope this makes sense) 
I have checked all settings on bar5 to see what sets it apart from the others, but its has the exact same settings as fx. bar 13 which is used by bar1 with alt pressed.  
To make sure it's "not" confusing, here is a screenshot of my holding alt down and it being empty while bar13 next to it is full of abilities. 
![image](https://github.com/tukui-org/ElvUI/assets/2270129/e035cc9a-a8b2-4337-baca-125f716872af)


Also, here are the settings bar2 you asked for:
![image](https://github.com/tukui-org/ElvUI/assets/2270129/67eabb39-83c8-4ab1-acc5-4fec9bfb41ee)

Here is my elvui edit export in case this helps somehow:
!E1!L3tw3TTn6(RPVj3H7lP3hgjzPyFRTKgt5MPtpw2us0wCcfPoKqoXZd(3(97daKeGlI0jP5MEM2CSLaXY3(gaOxPUA5kVT(e)1(Pz4Nj7sd8j4NcI9xhfSA9kVhtIjEH)NGvZunzFB(rsuyCWkV53U8QlNnzfzL3MKOe2Ce85dbPHbXBcWV5dddFEAqgjyRqlqB7sItsLwms1HVli8PDeye24AN6VpWJKca8kVlU89xSYlBxYN(hhH5(FUaH1pfULSB1mlCI8)pW8qOZY(KJzbjphKUAK0Ib96PG4Gu)ikYNqc2trHmk6QtNgb03yLhmH7Vk45a6ak(YuOpR8gUzt42GyIF0RpSaWx8lBEbiWHzhI8Fz8o)u)nKG0lJFmHHRRtiKK9l8JdI8ciKW4NYKqAtStzKWnF8LPiUNH4O)JFe)1MJzWyFFuYNOqm5faNaqGeMe)6dJoctm8B6JH5yFyC4E)dL4MMMla)BsIPl4E)qgfi4ZKJPW8Cn0aNjfLSXhN0PL0bkDjBFsczhaYdbQlG(Zu(znGhby)hHgViWFlfKh5V5JBttoGuE)iYIKpfKoYpLbZ(KJz4x8UMcFrHzegqmnjDpih6nBoiDrzbTsErYiFnE0FBavoKjMn1wtX0201uvv1YY12A1JNzQdIIaScmE6pxJ)eMIN9Jowo28Em12vvttXwrXsxb(Gdodg4OMA7OyPP76APzI)tHn3KCGDYNpaGy2N8FbPGjKBsIIKW5LfKAbupgiyNuwIYpEkmgefY8FIRXShLSP8XjrppC09QaooA(YLZV(Qjtxo42lx4Nct1aH2CmThO5yTY7g)WTx7N(rktzy8MDabGp4bWSvzSd0DSgOqxNBNEpow9RPQvElNVOCHWVCMMTYGZuDDw55D19NhSneeJc2(Bb7c3ebsfP8bYN4QlKYavhhuo8tJo(4JzJcabzgL6q5kkJE5nym4mGfnkjlJPf0eWPBI9ceK9Ucyoubvj45gW4snkhRXZa(9avBGk8VsIdgUomkK8YPOzkdmHo7LSj0p66G4JDb)kYu4dbKkJO(AWXBBWIL35ht9zavD0Qgz2vDGLB(QTiGm2pJSUlEZzMkwd00ux5X5MEGpJtpedn1bg5RZs)0NciSF2fXWYrfyuOOWvadDmOBKMejiZjslWVdYCgk2WZssFAhGmJ3LeUjyzYtpHMhBDz0DXb64ks4vBv02WgKEqyIPVz0P6MHMYadDqTCyPfW2MDnz2Vw7qHRoiiBHkXbhosOgPRQxDs5fnQK281)7aWRXZbIIlWcurfOOLZSuaSxdndUa8QfKktIBraqhgKQPgOhSl8rYWrNsH5mvdlWsd4mzi0Sp6kjiThaMPQfqq0TlKNPGNSGztlNHU5advLC2PDFiE2oAdmSb85g0vn4AN0G9J6JL1oAymhihMLbM(7TgUlieTKgKwntOnGAG2TMm1Orf82ik62ObYGhRJFTkPtfPE)1NaFk0S11X(s75Kis6XWS9FyiOHNDCpgGww72F01CgyQbdEK)tzVb6(z6o2OzOkR5jwivNbggGvHZdFcJ2BrAYtOB9Q0(Uwwt9b6gfYLttGy3oHnmDWbdeMbSS3E5K0uiS6kQMdQAYt11u24AFzZurFBqMACKViA1UZvfBurdv(tdFg8OpeC3K1pzdhh9bQUUC6pAC7d(PXqWIu07KobmbCuLtaVCKF8h7eZaluUdunYvQ16e6mm0gysnEuKaIe9OopUOrM(81HBst6dr)mULxrgwpgeLvPj4SUtV0a5gJXJZPei49WyQTTn3kpNM)u)yYQat2svd9aNercp0GEsZkjAwQdWixz8lRoxidWiGMBHty1EB1U0sVB3lIUnyfeNBHaqXOq8H8F7JpjvBh4hOVSrZMSSFKqiWzntaXOr(2LcPMonGHHPKWhHSlFtbaOQIdL5yOsyjTju5cEYlO5DNNbQuz4wWvn7EawGPDKCXdT8Qa)NdeIJVzIGjOBag3rKjqi4I2PW6UaHdKTxwjB1oWEq2zGJAo24Ck9vLb6AAsw8LTjxZmo1QVLcGd)28lhpz8fdx2jEyaybaodzv64TW71bRJWsDbwbM3Y4m0ClnDXKCqpaNMUb0cxRcfvLtXivrIGQGXXkM6pLfehhq2btbcZ9tkQXEmwthizi0QfjyFNQbAUUyCe)JJbhd8Oz03PAknOzLIW(GhtEPBJ(QmZvdJcsFRzPcAEQgGi65bR7JDeDvaanDZRhrNzzJEWOL9lg6hzH)tqaBJWAOrT6ZQILFezhVwp5L0YTAb1QvUecDKaVBQu)kBtQ3nuUfw9JehlTUodJoSZhRsLnw7k)OOLv7hIo7yv)uggd2NGjxDjTCzRHvieldP)(d5LP6NU4D)01V(aw9R1YlD0JpvmSGTHKrjFErswioDaxCYvZ)W9OM(9xoZ7YZNSY7awlWpGvX8ggbZad7H2ArL08Ua6kWSVqS7qpDvWk595RaxtzWxrHTIcF(ByoA0cns5smWScDJ1yTI76fg7JjigsEzjG4PaIbl0HWy6CYSntXpS8B3gVnzZhd2U0FnvEyx42GXjhEHBcFutmmGOhdagviNwgR5tNcwaVzL3h2fMbbJ96d0NrfnW5dysS0nPlbLgmUSSFal2XW21vtv3wX2aJ7UPk(bORxqeK6lwXlwDgzLufrYXIvc8NnvTTmSvmDC00Xci(utnUUHgfxgGMacCvMyialxfvxlfBhJ8j2WfCmxmn5tSMQPLJLMTHPce0dLwCmoKqljEfjwlSo(HXJss3I1fCnRNS67d2tz)gd6m79PjhP6Q86MBQuuk)5GqtkqSx5nD(nJNCpWtQ0TdOjmCWBzwyOuFAfexKeI8yM9iwfNlMUzAGnjGNMM8jqgfE4b)nGhyO9sJeOJZ9HXyLSOkk4Z2GfzUUq7lZHvoahdfYzmqGotHMzaT5SDue0Nq83SdFYYeqbIAAAL3NZhTkZSX9pYvO)dSsSu6WD0p(UmaTi3jSENHX4wxw(Fdqq4JVaQMOvYw2UK8TGyuE14v1zC0yoZSaUC0RayaTR08bJ(skjCwG8nAooCJFKxoHf1wFomlmVsL)XFpfYeWAqWNdZiza(b50cIb396d4MP8l4pWTMjn8)GX5wopaFlvGvxh357SGjTk3BOYzfKlLMbCz7Sf9wNkGbG1Ni7opmnydBCuxB3F7c6JoEyeSM3m)Qj4Ml5V9Ln7c28r0yRWUCqNheKVmMwaAMUhNOR0MufPqsxfRYaZrMeF5StXxOGjvdbJPw07NP8wDLGPzYkCh439YZpNIljrb5yr5CMNrHOmRrbAQlq7q0AR)EWHCkBvqWFrkwaE6uTuq8JW4bGAZP0J5U8RPiBjq)8YP3CU2)mNmisIBBdYoKgcKcu2CbyWkj2pcufoUhMOmQUFP5ccD30qONL2mD)TgvHsYa2Xj7x7tQipikKX2glFSC5SyuaFNJW9bDMfslq7fbB5(w1SzM8aJaGYdneb0Rke)BryfuR9ByX4txrW(4hf2tsnDNITcKb8u9F6UzomEBXMksTOZ(gZOwHWJclYJLjxKeTL6uGjew4tzn1q2t0FMwSlRvmkYSNfLe)0DTBySC3FRBwKpwjD7tUdDcgf5YenBvSu7Yuwb(pabGDhU7NQdV8khvApvgCzJRjq9TBZUa6ku7ycq014TtjPd7)5NKDPKdDlw(6dGoy2RpmZNk6)wHrtzyKX32d2aoUVBUEnYyvNH5tuVPR9KTJMUe47Lk7xNhgBU(UOovy8JjSiBfS0YeCAXYDPjaZgTXsAWt8zQsdSpM)fvCB1YkN0uy1KXElTiokcCLI7o8GCBJdItIlTtcgTkJtsP0wPtNoGQkqI9LZLPF(DWuTb0MVtsUIYwyHpwXNrd(c6HT)QUlkj4yPllJiWTcPJ3DUGmAk4MHxpPzFjIHBwnw0(yv)BI3frh)9rUSv5lrX0VeB7sMz)oAEVuW7nzBx0U7FEw3Rfr(BXUPSfSVN2oRc291UPHY3gtC)PyGrkDMcZlYIpY5t2AWIcXJvMCp1G0srIxtfHQwOA1I9QhXUvQF2JfvmBiQHjrUvr4KCgeoNaldZ26ZITOws(WdCaEeVYzfNoory9W8c1QyvxYOBtPbGfCnNMBki7jhGEPfVQsrYMaLm1(BtUz5LJhEvnjrbDhshzL2S5BomsRlFoiwjNYn4oI2GTBX8ZYksDTPm1kz1cvPOeD1QKN2PtITqtRg9tq1RlfUnhtXI4YQMb9iVDxvIzBwoYGraPIVY78jEJBjOR8ZROpwS6K9JHLkiLX95fZuuHwksLAgJufD(3LrvaoFjVcnnuMbUOToUa)PX((Q0zAqe9)p1ya7P0sdYSO2Oc9xJg0p0c6NsYwwh4hsbDwO5ngGUipOGkl2yhrnyAwc(ne3OaSreCcr9dFGUtHvGhrV21lTKqyjsrW3GYvzg0wQmKRJa6lWEwzEqEilAZr1R8dYklHfmAJYirYrsN213oZi38ZnClp14f1QpzLmPAVqLLLCLiRU1t8QhrW4FKKCbYugjTjEfLThJEnmkI1sWw2qks6Pm9SZNSC44lMCUWqLIvSmVTpSlKeWop05lODnWhpyle8KpMvKeMKadUprdjx7)zgUmQ6of0ugyAk6vQgt3baZUWeEStFV0UiLNtwh1hsSKnFhQqu1KWy558tV(WUdV(qPw6xC9HQLtgnPIV0SY(SqosY7usFsWri4)Uc)9TLDqTa1RLAqJrU)1Lmql6QYxhMwsaPa1bQf9K(XAyK0wb8gZSiV3aQZ7DEUgr(eAHbOg3APqjKwYY70(eQuLmbvxrjo9gDsivOm6(6i4uPKrCIckjyyQhf2QQrCRvfbIQwXr4BpEX(UjiFVcIS0SsVdN8lkYX(U3yAIb3)YFIzC1)ID8FVHKEGfjAJHokrOfz1cgVld)K0sfp5R)Y36MWudbedB7R0tBd(Um6LVlmm7s92uWyEAwWumgRrIMn1zHNrV(aYQGTE(nW(dYG(YDVwn8SffkQtWOH3N7GJT)4fsye8onMvD3KlxRs6RBRMXAEB)LJBSHW3Ao(jjEQDfbRgtisiMZAsQCSgvLAWyB9cQk6wYQtHVtSfs6Anwj0YI1YeTiR4xWqebzhC7xFyueEOFAicJYRSltPIruxlCHnxtpcrJRETifpgvut1qy4jht3eqNSfdVA45xod)i9OlPKFEO0Wd2Kd)uo5w2KTLPqGyq8cjuxH4KntTCAWd(KIUl7GqPNdh8XntRSJfhtkS3Av7OEEh5aIIqNvnTLRiA9ZoH)AWK7AMBBwWEeASfO(2JOemnht0alBZN4KTFwRXt1vXz)sv3UmYwWzum9eJXg9uhDDOxMQoQAwkok87Ak9(PAyQROAz4OBORyu8K1RMAzyP76QOPy464AyuE)uz8AUwGiZMQbCFrlTXVPdNNIN4W5ZlkoqNjPNHsqCXRxO((yzpJnuzfNcudGdRPRQyyBAxCPDZHIPoAwMiY6a)0q3IFLCj1MU73cE3Bdlq4FKFkEc7l4qU4)zB7AyP5GHnWetrHnfllvt4hMC2MbYY00mCSSD0uLSEmD(4B9WpqhTQm)LnAnH2yzUF9WzdladDHteybyyxrBznxBzYSj38(FVySoveYy54WGzM0fY3f0NN6y7AceuBfdvDu4Qu0QLNSUTNq4zFKFJ0jLg1xYLaYPlmbuBhvhxvhBDfBxnxkFUSogmJY79dJZNbXmv2l56uC6ZV13wQQAQaZ0wvLnXiYAcMgmubJhw62gGAd)jaWyyzPzAQyyPccFgaxjhyeCrKdA9upbi0ZsUeJcl94bsblYU0gMg(onGjNylEqq5CmQ4rrR4CcP6fJztcoEgYuaPhawUU83yfPciwHAofeLTrtj25MnR266MALFaZAk(i27pGCCGjT4b5mTLzWaYLo5tulU4WZKKa6y)OlZCwxPYQV8Ilh)RIV1kWG)9G4zJ3MTIFE4W3hgK84lfYch3MamiCA753EWZHottpM6RYJMJbnOzAAL0OsOU(PXtqluiT8zIoXH0JjrbygqaUtf7)TGyAqALZ4j7EXvqfbMI8eOW6YcjgGWmsoINCuGMbpFXo56WVza5RaBa4DMaNapT8paz7X9FJ9qioZgais59lTBGpLglK35l8Krek(JahB4EZXGw25JfLCCuc9GO2nYn6y41HB3gfC(sjeSKHEYHpDHxVwgeBfa1X0Kc3ecrorAo3zFAKh8awHFPZm3jxBb0Kb9a2Fr(XFYcnEUjnP5t0)UeYhdEPE5K)yqWbCkVbJRLLkrJLDUC8vbGs9UILxEO8UvC4KR8YzPybRd00je11wunlt(KIcCA8(HkW48vmOFxiDSsWVP3KnqNt9zViv43AHLTsXiuEItt8eNwPEfqRDn2MZjPaHX7Wl6f40BTF0uFEr5BHxwNm0n)gT(fKbjqKcwaNhpo3k8O2mIdiV73wbY6pRMqjt)ARK4s1mBGMfR3RIqwakSiloH0z2IG0BWq5TAsE9lteTn2uJQn5STM0ZAsIgMZ4eYT0KPLVHjAIjFXZfQwJRBOrMKTAlm3dvoz4vy2U9GzltMGzQlAKixPMmbyc5c6OlQS9jnDrjWR7YifJPyMpOXLXWofstWgOu6qWIyaJgcrhBAaPO5Qz5aXyQ4AvM41xPCtPDLd(pHcJlXYL((BNG(CUE47HF)h7t2(Um8nSXDV(G5V86d)T)2RpC5EC)q9JjV(a)fdZR)V0ocr5bDtvh6h()yFpp4XG4SWNdQ23nK0O7uv4t5Te2Ze6ugScBcENgmJo)c891jX0Yq8oDOfxPwmXvvfAAL3IBUCI3Y)Ib4R8(WWBUA(4FflItcSiyZDbZ5iNwxDKHC9h3E9bRwrUYIX8xnk81ZN9R)LdOp)MBV88)Ib1OqYKFB(VIx3Y)sb4R88Uy41d)lNOnr0b4)uO61LT(7LBEUslHWkEH(6kGwy1TBWpoDlq70pEpCw)njKTEhqMSd8t4uTzN4TfrqF5gn5pw62v(m7fxXXW74xOsqi4qaHLki0gEYu(f2JGNSHU945DfFg04FNvnKbV(a)oAk)4CP4QTXubQ2kvgUOrXGhk0FYDIz3LUZxGtSU1VA3bwHBGFCbW6rc0By8TyPQpa5PStvyfsDqCsgHwGpyigswOAZkMyueVzS87gNGhb8pQai6Nnp(GFKHXIyb(rfifsA4hwqKKN(SPKF3E5X7KvAsvVSq4FbEt7Dc2SvBb7GB0YA0rSdnw7KgRGvFDu7NFgEnRbXyl57(X6gRRLCH8rsPYxfPSayCAbRQxrIkvrGUhyQQAgwwgk6oQUMAL7(MPPQIMJLJQQoUhB2cBILLQLMPUJPPITMMzz9f6vHaBTax5hmp6Bu73NgYRx9tf40qbeEp)vDxfkOuLCL5bJAS(2E8GLM85qszTw5hclRU0fm(gRCz(TTsMNUuR)xzP1XDJHxzDF2BMgGSR9DLS3Tc)Pvr(Et))Qi5njnXK1T6frxcz)tVQ9DQZkue8VEcBdCR3aPUB)NSsdms2i56wCwiHpNor18mFR7nSWgoJfBC6A3x(s97lwvRhC9MyENuVtKH0t9UVfcdcbp0H)Yt6MT2(YqyhlWd4zINEWbkEvCTC4nVFYs8t0JvQ3g)OaKDIVqV5h00H4VW7pbRhcx5gWT8N4x6e6F5hO88PqCXZo)QF)(zlgJZB(5r8KNwckioz2KRlg2Pp4MASGdp1zrKUjQqCWb1UzokIhYrQOhrgmlfso9r8OCwgpz2siFfOVLhBfkZtc4eoeNOBOIBqrpxeH3SIIiknSRS9(P0JJtPu10RG88UF0TtN6D)8z3F(e6hlj0lUA4VdWCB06t(Y)y8y(l0XA8esijItiZpHPh2qB8UMjpYeLEjT4v5Ka3iJONOe((iM(kULEovhCo(Q(lkchXG1yGcZsYVVgdyVOrPDEWYJPakX(m(kvD0l3cQuO(N8lcfz5X(ZLeLo4462WhFmCZXiYl8d(oTl39h0dUl9mHf(yi7Vsk31fbSxcvKMJww(itvE8DrRbYB7BJhw2F22s8OXUIFWaLpTSN(qel)Efe51(S)K18VpgZUefT7EVYFTCKqSdrSBRjmDAuZU(pzW)To)3QSCiEoiEBs67t9FHUUH4bS7z)i6bMt(qccJH79vYbrTJx(fZV5Y)18zlhEfokjOS0CKuZ1DTGO)5fNCcCzW7nj)VjcieG)b2HsWY2K6FOgLsm6mXZ(wLZN2xZzHtt70Nfoc7uXw9S73qaeTWFZcoeqp3iaOtVPIRB5VYn4TLRWjP9jDzt4xipPm392XUOa5pS9HvbazbsyizJQb8dZaUWuclhfQ2fi0Tfp0)fCUcKqvTowvto785Fy29C19pbcbdFeVHoyPlAlGiavPafT6gPL2d5avJe3EqmB8y8Ktu5jF70eT)5QVAjvOdDr17hvJKFMvTvV7DhstEmmk4DVBCusCW27V9Y71()(

**Comment by Anaxagoras85** [comment]
I am experiencing the same thing on 13.54 on WoW SoD game client.  Set my bars 1 and 2 to page to bars 7 and 8 for Metamorphosis.  It does not seem to use the real version of bars 7 and 8, and it wipes the bars when I relog or reloadui

**Comment by Qiyamat** [comment]
I can see no UI whatsoever and there is no Eluvi buttons

**Comment by 1Botanica1** [comment]
> I can see no UI whatsoever and there are no Eluvi buttons

Please don't hijack other tickets. 

Join the discord for questions.

**Comment by Clonedpirate** [comment]
I suspected that the issue could be attributed to corrupted settings within the "WTF" folder. 
I tried the following testing steps to see if this was the case.

1: Exported the profile to a string and saved the action bar paging settings.
2: Deleted both ElvUI and the "WTF" folder to start fresh.
3: Downloaded a new copy of ElvUI and launched World of Warcraft.
4: Imported the "export" code and the previously saved action bar paging settings (refer to earlier posts).

Encountered the same error. :(
So the issue does not seem to be any corrupted data from the "WTF" folder.

I have no idea what the root cause of the issue could be.

**Comment by Clonedpirate** [comment]
Update:
With the release of 10.2.5, the ElvUI version 13.47 is completely broken. Which means I'm unfortunately forced to update ElvUI to 13.55. 

As a last resort, I have installed Bartender as it seems the action paging works here. 
This is a sad day for me as I love ElvUI and its action bar configuration.  
If there's anything more I can do to help you developers figure out the issue, I'll gladly be of assistance.

**Comment by Clonedpirate** [comment]
**HOLY Velen of the action bar, I've found the issue!!!!!!**
It seems that at some point between 13.47 and 13.55, a change was made that made the comments I did in the actionbar section invalid. 
My action paging looked like this:
[mod:shift] 5; **// Important ability**
[mod:alt] 13;   **// Defensive ability**
[mod:ctrl]10; **// Utility ability**
[stance:2] 8;
[bonusbar:3] 9;
[bonusbar:5] 11;

A small hint was that "shift" was working. 
After the first // (highlighted in bold) it will still page when hitting alt/ctrl/shift but to something empty or wrong? (but not sure what it's actually doing)
It was bartender who gave me the solution as it was working and I could generate the paging conditionals.
I tried to input these bartender-generated conditionals into ElvUI and it started working.
For anyone interested, here is the "new" layout:
Bar1:
[mod:ctrl]10;
[mod:alt]13; 
[mod:shift]5; 
[stance:2] 8;
[bonusbar:3] 9;
[bonusbar:5] 11;

Bar7:
[nomod] 7;
[mod:shift] 2;
[mod:alt] 3; 
[mod:ctrl] 6;

**Comment by Thenebra** [comment]
> I suspected that the issue could be attributed to corrupted settings within the "WTF" folder. [...] Deleted both ElvUI and the "WTF" folder to start fresh [...] Encountered the same error.  [...] issue does not seem to be any corrupted data from the "WTF" folder.

Delete the WTF folder and reinstall game after does not erease all the files, corrupted or not... 
this explains it better than me: (it's a bit long to read ^^')

> _Resetting the WoW User Interface by deleting the game client or WTF folder does not completely reset your CVars. This setting has normal (client-wide) scope._
> <details>
> <summary> ...READ MORE </summary>
> <p><b> synchronizeConfig </b></p>
> <p><i>Instructs the client whether to save character- and account-scoped CVars to the server for synchronization after each session, for recall on another machine or if config-cache.wtf is deleted.</i>[...]</p>
> 
> - <p> Deleting the WTF folder while the game client is not running <b><u>does not reset</u></b> all CVars back to their coded default value, but restore all character- and account-scoped CVars to their last synchronized value on the server instead as <b>synchronizeConfig</b> will default back to value 1.</p>
> See also:
> 
> - **synchronizeBindings** – Toggles the saving of key bindings to the server
> - **synchronizeMacros** – Toggles the saving of macros to the server
> - **synchronizeSettings** – Toggles the saving of UI settings to the server
> 
> source: [synchronizeConfig](https://warcraft.wiki.gg/wiki/CVar_synchronizeConfig) ,  [cvar_default](https://warcraft.wiki.gg/wiki/CVar_cvar_default)
> </p>
> </details> 

maybe worth check if you got any weird value cvar acting buggy 
➤ get the addon  **_AdvancedInterfaceOptions_** it has a cvar browser where you can track all cvar, their current value and what default one should be. when not default, the value is red: makes it very easy to check by scrolling all – ...and maybe find there what is causing the conflict
