### ISSUE TITLE
[Feature Request] A solid solution for arena targeting in Elvui

### ISSUE THREAD

**Issue by Sherlockell** [tukui-org/ElvUI#115]
**Is your feature request related to a problem? Please describe.**
< A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] >
I have a deep affection for Elvui, I've used it for years and quite honestly couldn't play WoW without it. However I've had one issue that throughout my time using it, I've been unable to resolve. **The issue relates to targetting in arena, specifically the inability to correctly order players in a logical way in relation to binds.** No matter what setting I've tried, Elvui seems to populate party frames in arena based on the time people join the arena? I'm still not entirely sure. Irrespective of whether I set it to sort by index/group I cant seem to get it how I want it. 

**Describe the solution you'd like**
< A clear and concise description of what you want to happen. >
**I would like the ability to set/anchor yourself to a position on your party frames, and party 1 & 2 to be able to be sorted either ascending or descending in relation to your position.** For example for me personally, I would love to be able to anchor myself to the middle frame and have party 1 above me, and party 2 beneath me. [Party 1 > Me > Party 2]. Since i use mouse-wheel up to target party 1, down for 2 and mouse wheel click-in to target self. This makes the most sense to me logically and is what many pro arena players use, but of course this feature could accomodate many different ways people have binds set up. I've had conversations with friends who have said they've been reluctant to use Elvui in the past specifically because of issues they had relating to targetting.

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >
As a side thought, not as important but I was thinking It would also be cool if we could have the ability to auto-load an arena profile when entering the arena. It would allow some specific changes players might want only while in there. From my perspective, with this feature I would switch my frame growth to left to right. So that it allowed my eyes to be closer between my party and arena frames.
https://i.imgur.com/LYQoKWn.jpeg

**Additional context**
< Add any other context or screenshots about the feature request here. >
Only to say that thanks again for all the hard work you put into Elvui and I hope we can make something work with this feature request. Im more than happy to beta test and help troubleshoot issues if you need me. Cheers!

**Comment by Sherlockell** [comment]
Additionally to add, the addon **SortGroup** basically achieves what I want to do. However, it is outdated and also doesn't seem to work with Elvui - if at all anymore.

**Comment by Azilroka** [comment]
You should be able to do this via SortBy Index

**Comment by Sherlockell** [comment]
Hi Azilroka,

Thanks for the reply. But SortBy Index doesn't seem to allow pinning your character frame to a specific point. So I would have to give leader to someone so that it hopefully sorts me to the middle, but this doesn't always work. Is this something that could be considered as a new feature?

**Comment by Azilroka** [comment]
No, The best course for me to tell you is to use Class Sort and change the sort order.. hopefully you are not on a repeating class in 3's. We use a header to control the output of the frames.

Default UI does not and 'player' is a fake frame added to that.
