### ISSUE TITLE
Interface/AddOns/ElvUI/Core/General/Core.lua:198: attempt to call method 'SetColorRGB' (a nil value)

### ISSUE THREAD

**Issue by Stripeman** [tukui-org/ElvUI#1151]
### Troubleshooting Steps

I have removed all my addons. and even deleted my settings for all my chars. I just updated to the latest patch as of today (17 JAN) and i get this error message.

### Describe the expected behavior and what actually happened?

well i expect my UI to open with out any errors. Please tell me what u need here specifically more than this.

### Reproducing the issue.

update Elvui and open game.

![image](https://github.com/tukui-org/ElvUI/assets/30218228/2bab6ee6-994f-44bf-a722-2b264118127c)

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/Core.lua:198: attempt to call method 'SetColorRGB' (a nil value)
Time: Wed Jan 17 00:29:50 2024
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Core.lua:198: attempt to call method 'SetColorRGB' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:198: in function `GrabColorPickerValues'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:212: in function `CheckClassColor'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:226: in function `UpdateClassColor'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:299: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:329: in function <Interface/AddOns/ElvUI/Core/init.lua:287>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:619: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:354
 mylevel = 70
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:411
 Config_OpenWindow = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:991
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1436
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:453
 ScheduleTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:624
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:138
 Cooldown_UnbuggedTime = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:19
 Config_CreateFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:789
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 ScanTooltip_InventoryInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:873
 ScanTooltip_UnitInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:861
 Layout = <table> {
 }
 myRaceID = 5
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1255
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 UIFrameFade = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:361
 TimeIndicatorColors = <table> {
 }
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:489
 StaticPopup_CreateSecureButton = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1095
 Truncate = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:142
 SetupReset = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:537
 ToggleMoveMode = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:71
 RemoveTableDuplicates = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:646
 WorldMap = <table> {
 }
 Disable = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 TimeColors = <table> {
 }
 SlideOut = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:296
 Unhook = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 XPIsTrialMax = <function> defined
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is a blizzard issue with the macOS client.

**Comment by Synnovva** [comment]
im having the same issue, and im on a PC.

**Comment by Stripeman** [comment]
Sorry yes.. im running windows 11 64bit

**Comment by 1Botanica1** [comment]
EU or US? 

EU is on ElvUI 13.54

US - 13.55

How do you update? Client or manually? 

If manually, delete 
ElvUI
ElvUI_Libraries
ElvUI_Options
Download & copy the new folders into the addons folder.

**Comment by Stripeman** [comment]
US
How did i update.  Manually copied the 3 extracted folders on top of my own.. However, i did try a fresh set of folders as well.. same result

**Comment by Stripeman** [comment]
ok... i downloaded the EU one. trying to find the US one

**Comment by Stripeman** [comment]
Is there a link for the US file ?

**Comment by 1Botanica1** [comment]
If you are in the US - you need 13.55

**Comment by 1Botanica1** [comment]
Just update your ElvUI as normal 

If you are in the EU - use ElvUI 13.54 - https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.54.zip

US - ElvUI - 13.55 - https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.55.zip

**Comment by Stripeman** [comment]
> If you are in the US - you need 13.55

Thank you so much for the links! Ill test now

**Comment by Stripeman** [comment]
Yep looks like that fixed it.. Thank you so much.  I live in the EU but have a US account. However, previously i have used the same method in getting the Elvui files. So i am not sure what the diff was. but regarless. im good now. Thank you very much, Sir.

**Comment by spencersmith** [comment]
> This is a blizzard issue with the macOS client.

Is this still a known bug? 

I'm getting the following now: 

```Message: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
Time: Tue Jan 16 21:19:18 2024
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: (*temporary) = <function> defined =[C]:-1
```

**Comment by 1Botanica1** [comment]
> > This is a blizzard issue with the macOS client.
> 
> 
> 
> Is this still a known bug? 
> 
> 
> 
> I'm getting the following now: 
> 
> 
> 
> ```Message: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
> 
> Time: Tue Jan 16 21:19:18 2024
> 
> Count: 1
> 
> Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
> 
> [string "=(tail call)"]: ?
> 
> [string "=(tail call)"]: ?
> 
> [string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
> 
> [string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
> 
> [string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
> 
> [string "=[C]"]: ?
> 
> [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
> 
> [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
> 
> [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
> 
> [string "=[C]"]: ?
> 
> [string "=[C]"]: in function `LoadAddOn'
> 
> [string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
> 
> [string "@Interface/FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
> 
> [string "=[C]"]: in function `CreateFrame'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
> 
> [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
> 
> 
> 
> Locals: (*temporary) = <function> defined =[C]:-1
> 
> ```

Please don't hijack other tickets. 

Go through the troubleshooting steps

**Comment by spencersmith** [comment]
> > > This is a blizzard issue with the macOS client.
> > 
> > 
> > Is this still a known bug?
> > I'm getting the following now:
> > ```
> > 
> > Time: Tue Jan 16 21:19:18 2024
> > 
> > Count: 1
> > 
> > Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
> > 
> > [string "=(tail call)"]: ?
> > 
> > [string "=(tail call)"]: ?
> > 
> > [string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
> > 
> > [string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
> > 
> > [string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
> > 
> > [string "=[C]"]: ?
> > 
> > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
> > 
> > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
> > 
> > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
> > 
> > [string "=[C]"]: ?
> > 
> > [string "=[C]"]: in function `LoadAddOn'
> > 
> > [string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
> > 
> > [string "@Interface/FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
> > 
> > [string "=[C]"]: in function `CreateFrame'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
> > 
> > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
> > 
> > 
> > 
> > Locals: (*temporary) = <function> defined =[C]:-1
> > ```
> 
> Please don't hijack other tickets.
> 
> Go through the troubleshooting steps

Wasn't trying to... I was asking if it was a known bug since you'd already mentioned it. The person that created the issue wasn't on Mac, so their issue ended up being different. Was trying to save opening a duplicate ticket by replying to your post.

**Comment by 1Botanica1** [comment]
> > > > This is a blizzard issue with the macOS client.
> 
> > > 
> 
> > > 
> 
> > > Is this still a known bug?
> 
> > > I'm getting the following now:
> 
> > > ```
> 
> > > 
> 
> > > Time: Tue Jan 16 21:19:18 2024
> 
> > > 
> 
> > > Count: 1
> 
> > > 
> 
> > > Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
> 
> > > 
> 
> > > [string "=(tail call)"]: ?
> 
> > > 
> 
> > > [string "=(tail call)"]: ?
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
> 
> > > 
> 
> > > [string "=[C]"]: ?
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
> 
> > > 
> 
> > > [string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
> 
> > > 
> 
> > > [string "=[C]"]: ?
> 
> > > 
> 
> > > [string "=[C]"]: in function `LoadAddOn'
> 
> > > 
> 
> > > [string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
> 
> > > 
> 
> > > [string "@Interface/FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
> 
> > > 
> 
> > > [string "=[C]"]: in function `CreateFrame'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
> 
> > > 
> 
> > > [string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
> 
> > > 
> 
> > > 
> 
> > > 
> 
> > > Locals: (*temporary) = <function> defined =[C]:-1
> 
> > > ```
> 
> > 
> 
> > Please don't hijack other tickets.
> 
> > 
> 
> > Go through the troubleshooting steps
> 
> 
> 
> Wasn't trying to... I was asking if it was a known bug since you'd already mentioned it. The person that created the issue wasn't on Mac, so their issue ended up being different. Was trying to save opening a duplicate ticket by replying to your post.


The issue originally reported could be a few things
The macOS client is currently broken - addons are causing errors.  Blizzard need to hotfix 
Or 
Could be that people don't have the correct ElvUI version for the region they are on (wow version)
