### ISSUE TITLE
Action bars breaking (elvui 13.55, wow retail 10.2.5)

### ISSUE THREAD

**Issue by Serfenia** [tukui-org/ElvUI#1152]
### Troubleshooting Steps

Description: 
When logging in after updating WoW to 10.2.5 and ElvUI to 13.55, the action bars seem broken and not all UI elements of ElvUI seem to be working. For example the minimap is also not a square, the colors of the in-game WoW menu are different.

Also the action bars menu in the ElvUI menu seem broken.
Operating system: macOS.

Screenshots:
![Screenshot 2024-01-17 at 14 29 44](https://github.com/tukui-org/ElvUI/assets/2427370/29189b17-d93f-42ba-a76b-8307993b83a1)

![Screenshot 2024-01-17 at 14 30 12](https://github.com/tukui-org/ElvUI/assets/2427370/299299f9-9ce7-49a7-a546-1bddb5e0f363)

### Describe the expected behavior and what actually happened?

A regular load of my user interface without LUA errors.

### Reproducing the issue.

Disable all addons but ElvUI, log into a character witih only ElvUI 13.55 enabled as an the AddOns , using build 10.2.5.52902 of WoW retail. 

### Lua Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
Time: Wed Jan 17 14:41:10 2024
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:354
 mylevel = 12
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:411
 Config_OpenWindow = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:991
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1447
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:453
 ScheduleTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:635
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:138
 Cooldown_UnbuggedTime = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:19
 Config_CreateFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:789
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 ScanTooltip_InventoryInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:884
 ScanTooltip_UnitInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:872
 Layout = <table> {
 }
 myRaceID = 36
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1266
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 PositionGameMenuButton = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:746
 UIFrameFade = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:361
 TimeIndicatorColors = <table> {
 }
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:489
 StaticPopup_CreateSecureButton = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1095
 Truncate = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:142
 SetupReset = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:537
 ToggleMoveMode = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:71
 Dump = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:445
 WorldMap = <table> {
 }
 Disable = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:310
 TimeColors = <table> {
 }
 SlideOut = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:296
 Unhook = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:417
 XPIsTrialMax = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:699
 StaticPopup_GetAllSecureButtons = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1119
 EscapeString = <function> defined @Interface/AddOns/ElvUI/Core/init.lua:214
 RGBToHex =
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by joergluehmann** [comment]
I have exactly the same.problem. Also on Mac OS Sonoma

**Comment by coders-kitchen** [comment]
Not the same but similiar issue here:

Action bars not visible at all, chat input somehwere located, minimap is squared, but the default circle texture is shown.
And the ELV ui config window does not open

LUA Error:

    22x ElvUI/Core/General/Toolkit.lua:132: bad argument #1 to 'unpack' (table expected, got nil)
    [string "=[C]"]: ?
    [string "@ElvUI/Core/General/Toolkit.lua"]:132: in function <ElvUI/Core/General/Toolkit.lua:124>
    [string "@ElvUI/Core/General/Toolkit.lua"]:199: in function `SetTemplate'
    [string "@ElvUI/Core/General/PluginInstaller.lua"]:255: in function `CreateFrame'
    [string "@ElvUI/Core/General/PluginInstaller.lua"]:548: in function <ElvUI/Core/General/PluginInstaller.lua:545>
    [string "=[C]"]: ?
    [string "@ElvUI/Core/General/Core.lua"]:1822: in function `CallLoadFunc'
    [string "@ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadedModule'
    [string "@ElvUI/Core/General/Core.lua"]:1863: in function `InitializeModules'
    [string "@ElvUI/Core/General/Core.lua"]:1973: in function `Initialize'
    [string "@ElvUI/Core/init.lua"]:284: in function <ElvUI/Core/init.lua:283>
    [string "=[C]"]: ?
    ...
    [string "@FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
    [string "@FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
    [string "=[C]"]: in function `CreateFrame'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
    [string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
    
    Locals:
    (*temporary) = nil
    (*temporary) = "table expected, got nil"

The white text "Sagen: " is the chat input frame, the expected action bars should be located at the center section on the bottom

![image](https://github.com/tukui-org/ElvUI/assets/1186163/23e8953f-780b-4e38-8197-fcb0da4304e4)

**Comment by coders-kitchen** [comment]
Re-download directly the files, deleting the old interface files from the addons folder and putting the newly downloaded files solved the issue

**Comment by Serfenia** [comment]
> Re-download directly the files, deleting the old interface files from the addons folder and putting the newly downloaded files solved the issue

Are profiles kept or are they removed? If they are kept I'm going to try that.

**Comment by joergluehmann** [comment]
I also tried to delete elvui and all addons for it. And just installed the ELVUI from the Website. Still does not work

**Comment by Stripeman** [comment]
> I also tried to delete elvui and all addons for it. And just installed the ELVUI from the Website. Still does not work

If i could... ensure you DL'd the update from the correct regioun
EU - ElvUI  v13.54 - https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.54.zip
US - ElvUI  v13.55 - https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.55.zip

**Comment by Serfenia** [comment]
Since when are they different? I always download from https://tukui.org/elvui, doesn't specify a difference there.

**Comment by Stripeman** [comment]
I had opened up a tix last night and thats what was told to me and it worked. and yes, i understand what you are saying. same for me. Please note tho.. the version may be updated. I hope im not speaking out of place here.

**Comment by Stripeman** [comment]
You can test by backup up your addon folder and apply this update and see if it changes anything. No change. restore.

**Comment by Serfenia** [comment]
No worries, will try it out! Appreciate any help.

**Comment by Stripeman** [comment]
> No worries, will try it out! Appreciate any help.

ok let me know  :) would be nice to know i helped hahaha

**Comment by chuckcharlie** [comment]
I deleted everything in Interface and WTF, installed fresh from https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.55.zip. Same issue.
```
Message: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
Time: Wed Jan 17 08:55:47 2024
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/API.lua:968: attempt to concatenate local 'localized' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/General/API.lua"]:968: in function `LoadAPI'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1982: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:284: in function <Interface/AddOns/ElvUI/Core/init.lua:283>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:781: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: self = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:354
 mylevel = 70
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:411
 Config_OpenWindow = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:991
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1447
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:453
 ScheduleTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:635
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:138
 Cooldown_UnbuggedTime = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:19
 Config_CreateFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:789
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 ScanTooltip_InventoryInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:884
 ScanTooltip_UnitInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:872
 Layout = <table> {
 }
 myRaceID = 6
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1266
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
```

**Comment by Serfenia** [comment]
@Stripeman doesn't work at all. Even more broken. I think there is no region difference ;)

**Comment by joergluehmann** [comment]
I tried the versions from GitHub. No Change. 
Do you have a Windows machine or a Mac?

**Comment by Stripeman** [comment]
> @Stripeman doesn't work at all. Even more broken. I think there is no region difference ;)

ok id put everything back.  also ill step back.. i dont want to make things worse.

**Comment by Serfenia** [comment]
As stated in the ticket: MacOS

**Comment by bluesockets** [comment]
Looks like this line (Interface/AddOns/ElvUI/Core/General/API.lua:968)

`local localized = (x == 3 and female) or male`

returns nil. tracing it up the chain makes it look like Interface/AddOns/ElvUI/Core/General/API.lua:930 isn't initializing the class names correctly.

`local MALE = _G.LOCALIZED_CLASS_NAMES_MALE`

I don't know enough about this code to know where _G is set but I'm digging.

**Comment by bluesockets** [comment]
This looks related: 

https://us.forums.blizzard.com/en/wow/t/localizedclasslist-on-mac-doesnt-return-complete-table/1767178

```
Now that 10.2.5 is live in the US, when I login on a character on my 16" M1 Max MacBook Pro (which is at 10.2.5.52902) I get a ton of errors. They’re all related to LOCALIZED_CLASS_NAMES_MALE and LOCALIZED_CLASS_NAMES_FEMALE. When I dump those tables, they only show Warrior. I saw that it was changed in 10.2.5, those are filled in via the LocalizedClassList(false) for MALE and LocalizedClassList(true) for FEMALE. And again when I do a /dump on those, I get back a table as follows.

Dump: value=LocalizedClassList(false);
[1]={
[true]=“Warrior”
}

On a PC this is filled in properly. This is only affecting my Mac (and I tested this with no addons
```

**Comment by bluesockets** [comment]
So, to wrap up,  this is not a bug with Elvui. It's a bug Blizz released that broke any addon that relies on `_G.LOCALIZED_CLASS_NAMES` male/female. From what I can tell, this variable is a constant that only Blizzard can set, so the fix for this is to wait until Blizz releases a patch containing the fix. Guessing it'll be released in the next few days.

**Comment by bluesockets** [comment]
If you want a quick fix until they release you can take the following steps:

1. Open retail/Addons/ElvUI/Core/General/API.lua
2. go to line 968 and change it to: `local localized = "true" -- (x == 3 and female) or male`
3. reload UI
4. profit

**Comment by 1Botanica1** [comment]
There aren't different version for different regions. 

There is - when blizzard drops a patch and the patch comes out in the US first and then the EU many hours later, like it did for this patch. 

US (who was on the new wow patch) had to update ElvUI first 
EU (who didn't have the new wow patch at that time) had to stay on the previous wow version

**Comment by 1Botanica1** [comment]
> So, to wrap up,  this is not a bug with Elvui. It's a bug Blizz released that broke any addon that relies on `_G.LOCALIZED_CLASS_NAMES` male/female. From what I can tell, this variable is a constant that only Blizzard can set, so the fix for this is to wait until Blizz releases a patch containing the fix. Guessing it'll be released in the next few days. 

^
This

**Comment by bobojobaxter** [comment]
> So, to wrap up, this is not a bug with Elvui. It's a bug Blizz released that broke any addon that relies on `_G.LOCALIZED_CLASS_NAMES` male/female. From what I can tell, this variable is a constant that only Blizzard can set, so the fix for this is to wait until Blizz releases a patch containing the fix. Guessing it'll be released in the next few days.

Someone mentioned that setting a line to TRUE was a workaround...is this the line that we can set to True?

**Comment by Flamanis** [comment]
None of them. Modifying Elvui is not supported and leads to a ton of extra support issues with people that never removed their "fix".

**Comment by 1Botanica1** [comment]
Blizzard has updated and fixed the mac client

**Comment by bluesockets** [comment]
> None of them. Modifying Elvui is not supported and leads to a ton of extra support issues with people that never removed their "fix".

^ this - let's not cause more problems and stray from the path!

**Comment by Thenebra** [comment]
> Blizzard has updated and fixed the mac client

Thankyou for sharing this update info. Time to log bnet!

**Comment by Serfenia** [comment]
I can confirm the issue has been fixed and there are no more LUA errors using the downloaded files from the website.
Thanks everyone and happy playing.
