### ISSUE TITLE
Right chat window non-existent (addon version 13.55, game version 10.2.5)

### ISSUE THREAD

**Issue by abehnan** [tukui-org/ElvUI#1153]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/12018696/850a7b4f-41f6-4709-8b3e-54806ce9ef27)

### Describe the expected behavior and what actually happened?

Ever since updating to 13.55, the right chat window is non-existent. This still occurs even after doing the "install" procedure.

### Reproducing the issue.

- Clear WTF folder.
- Clear Interface folder.
- Install ElvUI 13.55
- Log into game
- Run installation, ensuring that "setup chat" was completed.
- Look at right chat window.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by abehnan** [comment]
Note that the left chat is correctly being setup when "setup chat" is executed. i.e. trade chat, skill ups, and loot are removed.

**Comment by cabalcoffers** [comment]
Same is happening to me. Unfortunately, I discovered this on my main when I had made changes to chat and decided to go back to defaults via Elv’s install process. Now I cannot return it to prior functionality.

**Comment by 1Botanica1** [comment]
From discord 

`Install` button works again in [dev.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)  however, if you try to create another chat it will automatically be a Text To Speech forced (same happens in Blizzard's UI currently).

**Comment by kodewdle** [comment]
fixed in 13.56+
