### ISSUE TITLE
Chat input field is not located properly for private messages

### ISSUE THREAD

**Issue by Lunat1q** [tukui-org/ElvUI#1154]
### Troubleshooting Steps

move chat bot to the bottom of the screen (no space under)
set input to bottom (inside)

### Describe the expected behavior and what actually happened?

Expected: Input is bottom (inside for every tab)

Actual:
it works fine for party chat and general, but not for b.net friends or whisper.

### Party tab:
![image](https://github.com/tukui-org/ElvUI/assets/16973172/559e7404-9173-43cc-aea6-76a167167b80)

### Whisper (b.net) tab (input is outside of the screen)
![image](https://github.com/tukui-org/ElvUI/assets/16973172/966b983b-64e5-42f4-85da-aa77e73d9591)

### Lua Errors

```shell
no errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Lunat1q** [comment]
This is most likely because CH:UpdateEditboxAnchors() is not called on the new tab creation.

**Comment by kodewdle** [comment]
step 3

**Comment by Lunat1q** [comment]
It's still a problem tho...
