### ISSUE TITLE
v13.55 Tooltip

### ISSUE THREAD

**Issue by doadin** [tukui-org/ElvUI#1155]
### Troubleshooting Steps

With player titles on in tooltip, player name does NOT show. 
<img width="174" alt="image" src="https://github.com/tukui-org/ElvUI/assets/2148359/5f561678-1b34-485e-bed9-cc7c44f2b291">

### Reproducing the issue.

turn player titles on, names disapear, titles off names come back.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
fixed in dev :)
