### ISSUE TITLE
Everytime I am on my warlock my ui disappers in Wintergrasp with Elv UI Blizz ui no issues 

### ISSUE THREAD

**Issue by williamtheturtle** [tukui-org/ElvUI#1157]
### Troubleshooting Steps

Everytime I am on my warlock my ui disappers in Wintergrasp with Elv UI Blizz ui no issues 

### Describe the expected behavior and what actually happened?

Everytime I am on my warlock my ui disappers in Wintergrasp with Elv UI Blizz ui no issues 

### Reproducing the issue.

no issues being reported 

### Lua Errors

```shell
no issues being reported
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Please go through the troubleshooting steps requested when you opened the ticket.  

Here is a link https://github.com/tukui-org/ElvUI/wiki/troubleshoot

**Comment by kodewdle** [comment]
step 3
