### ISSUE TITLE
Pet Battle XP Bar Overlap

### ISSUE THREAD

**Issue by gizzmo** [tukui-org/ElvUI#1159]
### Troubleshooting Steps

![WoWScrnShot_012824_171602](https://github.com/tukui-org/ElvUI/assets/5255/a9581c19-c01e-4137-9acd-ff4022e80114)

### Describe the expected behavior and what actually happened?

During a pet battle, when the pet's XP bar is shown, the XP bar is displayed over the Pass button. Which makes the mouseover border of the Pass button not visible on the top edge.

### Reproducing the issue.

- Add battle pet to team, which is not level 25 and has some amount of experience. 
- Mouseover the Pass button. 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
thank you! fixed :)  on thin border mode, i also separated them a little bit
