### ISSUE TITLE
[Retail Bug Report] <Interrupt annouce on French client doesn't work properly>

### ISSUE THREAD

**Issue by Drey242** [tukui-org/ElvUI#116]
### What is the issue you are having?

As a follow up to https://github.com/tukui-org/ElvUI/issues/59
Interrupt annouce on French client doesn't work properly

### What is the expected behavior?

Interrupt annouce showing up on chat with spell name instead spell ID

### What actually happened?

No error but it shows spell ID instead spell name (with link)

### Suggested Solution/Workaround

Line 175 on Interface\AddOns\ElvUI\Core\Locales\frFR file :

L["Interrupted %s's |cff71d5ff|Hspell:%d:0|h[%s]|h|r!"] = "|cff71d5ff|Hspell:%d:0|h[%s]|h|r Interrompu %s !"

That works : L["Interrupted %s's |cff71d5ff|Hspell:%d:0|h[%s]|h|r!"] = "Interrompu %s |cff71d5ff|Hspell:%d:0|h[%s]|h|r !"

### Errors

```shell
No error
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Repooc** [comment]
u can try dev or wait til release, but should be ok now

**Comment by Drey242** [comment]
Awsome thanks
