### ISSUE TITLE
[Feature Request] Hide chat windows or particular chat windows when in combat.

### ISSUE THREAD

**Issue by kallso** [tukui-org/ElvUI#1160]
### Troubleshooting Steps

Would it be feasible to hide chat windows when in combat and to choose which one to hide ? In a more general way can Elvui react on "in combat" state changes ? 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
step 2
