### ISSUE TITLE
Left chat window missing

### ISSUE THREAD

**Issue by Hyndruin** [tukui-org/ElvUI#1161]
### Troubleshooting Steps

![WoWScrnShot_012124_190009](https://github.com/tukui-org/ElvUI/assets/158534199/ecd27b36-8914-4ad5-935f-be4b3955a72b)
![WoWScrnShot_020124_200255](https://github.com/tukui-org/ElvUI/assets/158534199/f54fe0c6-83fe-4380-9430-c62a2d0b7f10)
![WoWScrnShot_020124_200450](https://github.com/tukui-org/ElvUI/assets/158534199/c0c39e33-845e-4dab-a076-045a2b3dee44)

### Describe the expected behavior and what actually happened?

Elvui ate my left chat window. It is present with Elvui installed and enabled, but I tried to remove Elvui and no longer have the window. I disabled all addons except Elvui, and no chat window unless enabled on Elvui. I the did the /edebug with no change. I uninstalled the game entirely, then reinstalled it and still have no chat frame. I would like to not use elvui, but how do I get the chat frame back?

### Reproducing the issue.

1.Disabled all addons except Elvu
2. Tried the chat window both enabled and disabled in Elvui. Chat only shows up when enabled on Elvui.
3. Uninstalled the game completely.
4. Reinstalled the game but still have no chat windows. How do I restore the left chat window?
5. I checked my alts and they have the normal chat window. I did not install Elvui on any other toons.
6. Thus my assumption that Elvui ate my left chat window. Please help.

### Lua Errors

```shell
I had no Lua errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
> Type in /resetchat in the chat window —this will restore your chat setting to default.

[https://us.battle.net/support/en/article/10678](https://us.battle.net/support/en/article/10678)
