### ISSUE TITLE
Chat input anchor is wrong for new tabs

### ISSUE THREAD

**Issue by Lunat1q** [tukui-org/ElvUI#1162]
### Troubleshooting Steps

move chat bot to the bottom of the screen (no space under)
set input to bottom (inside)

### Describe the expected behavior and what actually happened?

Expected: Input is bottom (inside for every tab)

Actual:
it works fine for party chat and general, but not for b.net friends or whisper.

### Regular tab (Party):
![image](https://github.com/tukui-org/ElvUI/assets/16973172/416e528d-72c4-4161-86f7-a60bc9e50573)

### New tab (whisper)
![image](https://github.com/tukui-org/ElvUI/assets/16973172/abd3d5d7-6c93-416a-bcdb-623d9c7ff018)

### Lua Errors

```shell
no errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
need to go through all the troubleshooting steps, not just some.

Type in chat in game `/edebug on` and test

If you have the issue, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing the issue and the status panel.

**Comment by Lunat1q** [comment]
> need to go through all the troubleshooting steps, not just some.
> 
> Type in chat in game `/edebug on` and test
> 
> If you have the issue, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing the issue and the status panel.

Thanks, I still did it and get what /edebug is doing tho. 

Regarding Troubleshooting Steps checkbox -> It's mentioned here, but there is no explanation what is it (or it's hidden way too well).

**Comment by 1Botanica1** [comment]
> > need to go through all the troubleshooting steps, not just some.
> > Type in chat in game `/edebug on` and test
> > If you have the issue, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing the issue and the status panel.
> 
> Thanks, I did it, but I still didn't get what `/edebug` is doing tho.
> 
> Regarding Troubleshooting Steps checkbox -> It's mentioned here, but there is no explanation what is it (or it's hidden way too well).

When you create a new ticket - the steps are there for you to follow 
![image](https://github.com/tukui-org/ElvUI/assets/5704821/e815ee0e-145d-4180-8bde-63a13b215c40)

**Comment by Lunat1q** [comment]
> > > need to go through all the troubleshooting steps, not just some.
> > > Type in chat in game `/edebug on` and test
> > > If you have the issue, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing the issue and the status panel.
> > 
> > 
> > Thanks, I did it, but I still didn't get what `/edebug` is doing tho.
> > Regarding Troubleshooting Steps checkbox -> It's mentioned here, but there is no explanation what is it (or it's hidden way too well).
> 
> When you create a new ticket - the steps are there for you to follow ![image](https://private-user-images.githubusercontent.com/5704821/302151163-e815ee0e-145d-4180-8bde-63a13b215c40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDAzMDEsIm5iZiI6MTcwNzEwMDAwMSwicGF0aCI6Ii81NzA0ODIxLzMwMjE1MTE2My1lODE1ZWUwZS0xNDVkLTQxODAtOGJkZS02M2ExM2IyMTVjNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMDIyNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRlZjYyMDBhZTE2NGU0NTc1NDQ4Yjc4YmJiZGRkN2I3MTdiOTE0NjYxOTlhYjY2YTcyOGFiNzM5MTZkYmM4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OazLE5p30TCAyMGFgh4ZJjWSNa4Pi7Uii6qCWnP4NFw)

Sure, thanks.

Regarding the issue, I have some ideas why that happens, there is a method that applies input anchors adjustments, that method is not called when new tab is created.

**Comment by kodewdle** [comment]
can't reproduce on my end, try redoing the `Setup CVars` and `Setup Chat` part of the installer, also before you reply please update to the latest version (currently of writing this would be 13.59)

**Comment by Lunat1q** [comment]
Me and my friend can repro that on 2 different PCs. 
I can record the video if needed.

**Comment by kodewdle** [comment]
sure, record a video of doing `Setup CVars` and `Setup Chat` after doing `/edebug on` and show the issue please :)
