### ISSUE TITLE
Blizzard (De)Buffs shown while Disabled blizzard is enabled.

### ISSUE THREAD

**Issue by TrusterX** [tukui-org/ElvUI#1165]
### Troubleshooting Steps

![WoWScrnShot_020624_221742](https://github.com/tukui-org/ElvUI/assets/6065454/bdc59e4d-f6f9-448e-a608-1157649c9950)

### Describe the expected behavior and what actually happened?

Well, after upgrade to 13.56 today, the blizzard De/Buff icon in the upper right corner are shown, regardless the selected option in ElvuI
![WoWScrnShot_020624_222842](https://github.com/tukui-org/ElvUI/assets/6065454/8829ee8e-5440-4dc2-aa9d-ed3ff260219c)

### Reproducing the issue.

Not sure about that. Issue arises after upgrade.

### Lua Errors

```shell
N/A
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by TrusterX** [comment]
is there a way to switch back to the previous version? i have a backup from it's WTF-Data. I couldn't find a download link. Next time i'll backup for myself...

**Comment by 1Botanica1** [comment]
Nothing to do with previous version of ElvUI (which aren't supported anyway)

This buffs and debuffs is a blizzard issue - waiting on a fix from blizzard.
From discord - The player buffs and debuffs (near the minimap) - currently this will be always off until Blizzard addresses an issue with the Secure Headers for Auras

**Comment by kodewdle** [comment]
fixed in 13.57
