### ISSUE TITLE
SoD: Renew is not shown in unit frames anymore after applying "Empowered Renew" rune

### ISSUE THREAD

**Issue by ychromosome** [tukui-org/ElvUI#1167]
### Troubleshooting Steps

![grafik](https://github.com/tukui-org/ElvUI/assets/5198981/1e7ca45a-d30a-431a-984d-e757d9aa76b2)

### Describe the expected behavior and what actually happened?

Renew should be shown in Group / Raid unitframes, but it is not shown when an item with  "Empowered Renew" rune is worn.

### Reproducing the issue.

1.  Apply "Empowered Renew" rune
2. Cast Renew
3. Notice no "Renew" displayed on character in unit frames.

4. remove the item
5. Cast Renew
6. Notice that "Renew" is displayed again as it should be.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Copied from discord - https://discord.com/channels/209244641537556480/1205677295550079027

Aura Indicators (SoD) not showing new spells

You can add them yourself, or wait for them to be added to ElvUI (no eta) 

Adding an aura to the aura indicators
Get the aura on yourself, mouse over the aura near the minimap and get the id from the tooltip.  Dont get it from your spellbook/action bars or wowhead.  It has to be the correct aura id, not spell id

Add the aura id to 
Filters - Aura Indicators (class) - Add spell

To change the coloured squares into the spell icon
X unitframe - aura indicator 
Change “Style” to Textured Icon

**Comment by 1Botanica1** [comment]
Update ElvUI

**Comment by kodewdle** [comment]
reopen if needed after updating (redo the screenshot on reopen please). also, read the few things we ask next time :(

![image](https://github.com/tukui-org/ElvUI/assets/2266754/4adecceb-e9b6-4d23-9121-b1c297717a8a)
