### ISSUE TITLE
Minimap difficulty mouseover tooltip in wrong place

### ISSUE THREAD

**Issue by Arrothben** [tukui-org/ElvUI#1169]
### Troubleshooting Steps

My minimap has the difficulty flag in the topleft. The mouse over tooltip appears when I am hovering above the top right.
Mouse cursor is on the right.
![grafik](https://github.com/tukui-org/ElvUI/assets/104759428/07e71bbc-45e4-49d1-83e2-c4355a84a2bb)

### Describe the expected behavior and what actually happened?

The tooltip should be connected to the graphic element.

### Reproducing the issue.

Everytime

### Lua Errors

```shell
None
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You didn't do the troubleshooting and provide the screenshot as requested. 

Type in chat in game `/edebug on`
and test 
If you still have the issue, type in chat in game `/estatus` and upload a full UI screenshot showing both the issue and the status panel

Upload a screenshot of the relevant tooltip setting as well.

**Comment by Arrothben** [comment]
Sorry I misunderstood the line. Not native. Hope this is sufficient. Only ElvUI enabled and the cursor is in the top right corner again (not on the dungeon difficulty artwork on the left).
![grafik](https://github.com/tukui-org/ElvUI/assets/104759428/587a7641-0c1e-40d9-b5c9-edee2886e633)

**Comment by Arrothben** [comment]
And I don't know what you mean by "Upload a screenshot of the relevant tooltip setting as well."

**Comment by Arrothben** [comment]
When I am in a guild group the tooltip appears when hovering the artwork on the left

**Comment by kodewdle** [comment]
thank you, it's fixed in dev.  i also updated the view of it somewhat to hopefully made it look a bit less, terrible. lol
