### ISSUE TITLE
[Feature Request] Loot Roll Icons Further Apart

### ISSUE THREAD

**Issue by Jiveturkey35** [tukui-org/ElvUI#117]
Hello. First of all I love ElvUI. I have been using it for a long time and I recommend it to everyone. The only thing, and I mean literally the ONLY thing I have not liked over the years is the loot roll icons being so close to each other. The "Need, Greed, Pass" buttons. I have, on many occasions, hit the wrong button because they are so close to each other. I have friends that have done the same. This is a very easy improvement. Can this PLEASE happen? Thank you so much and continue being awesome, all of you!

**Comment by Repooc** [comment]
use the dev build or wait til release as azil had already put some extra space

**Comment by Repooc** [comment]
correction, he thought he made them further apart on the dev build but he went the wrong way and made them even closer.... so he should have that done soon

i mean, we can do a "boomer" version for you like so
![unknown](https://user-images.githubusercontent.com/1479745/144942358-1551c280-0731-4970-8a5e-e9433a962315.png)
lol  just playing, he will adjust it a bit though

**Comment by Jiveturkey35** [comment]
Haha thanks man. Ya I never needed the icons bigger, just more space between them is all. Appreciate the response. :)
