### ISSUE TITLE
Right click menu showing up super tiny

### ISSUE THREAD

**Issue by MrWicked1989** [tukui-org/ElvUI#1170]
### Troubleshooting Steps

![Screenshot 2024-02-15 210802](https://github.com/tukui-org/ElvUI/assets/160200033/ff8e4732-8158-4595-bd47-9d0d26415a62)

### Describe the expected behavior and what actually happened?

just setup elvui on several toons everything works as intended, except just when i right click on quests or right click on character health bar to reset raids and whatnot it shows up super tiny. but when i open up my guild & communitys chat tab it shows full size like it should. 

### Reproducing the issue.

ive disabled all addons except elvui and still proceeds to be happening, i dont think this is a bug persay, i think im just missing where to change the size and location on this toolbox 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by MrWicked1989** [comment]
apon unrelising my elvui was needing update which i failed to check, updated to current version but still box shows up offset
![Screenshot 2024-02-15 212025](https://github.com/tukui-org/ElvUI/assets/160200033/16128813-1ee4-4163-bbe6-9663488a286d)

**Comment by 1Botanica1** [comment]
One of your addons has changed the blizzard scale (ElvUI doesn't change this). 

And it will happen if you disable all your addons as well, just have the blizzard UI. 

Type in chat in game 
/run SetCVar('uiScale', 1); ReloadUI()

**Comment by MrWicked1989** [comment]
that worked perfectly, thank you ;D
