### ISSUE TITLE
[keybind are randomly blocked] 

### ISSUE THREAD

**Issue by omri1212000** [tukui-org/ElvUI#1171]
### Troubleshooting Steps

The bug keep happening even after /edebug on.

### Describe the expected behavior and what actually happened?

My key binds are randomly being blocked. When I change a spec (fire to arcane mage) it happen 100% of time. I have no addon up (/edebug on). It sometimes happen after alt/tab or using dragonriding mount, keybinds fail to use vigor.
If I click them, they still work. I also get a weird noise as the action gets block, similar to hitting ESC button.
If I do /reload it gets fixed. 
I should say that I disabled the entire 'ActionBars' option in Elvvui and moved to Blizzard's. I've also disabled Chat, Cooldown tests, Nameplates and few Skins (BG MAP, Talents).

### Reproducing the issue.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR5BUTTON6"]:2: in function <[string "MULTIACTIONBAR5BUTTON6"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by omri1212000** [comment]
[![image](https://github.com/tukui-org/ElvUI/assets/160275670/0e92f7b2-f2f5-4717-b174-358ac6193672)
](https://i.imgur.com/HpSsN65.png)

**Comment by omri1212000** [comment]
Hallo?

**Comment by 1Botanica1** [comment]
You didn't do the troubleshooting and provide the screenshot as requested. 

Type in chat in game `/edebug on`
and test 
If you still have the issue, type in chat in game `/estatus` and upload a full UI screenshot showing both the issue and the status panel

Also, mouse over the action bar where the keybinds aren't working and type `/fstack` and upload that screenshot as well.

**Comment by omri1212000** [comment]
Whoa I've learn new things, thanks for the reply. here is the missing information:

> You didn't do the troubleshooting and provide the screenshot as requested.
> 
> Type in chat in game `/edebug on` and test If you still have the issue, type in chat in game `/estatus` and upload a full UI screenshot showing both the issue and the status panel
> 
> Also, mouse over the action bar where the keybinds aren't working and type `/fstack` and upload that screenshot as well.

Whoa I've learn new things, thanks for the reply. here is the missing information:
![MidFight](https://github.com/tukui-org/ElvUI/assets/160275670/d895bca5-ab4c-4cc4-a6b3-35358e3595b9)


Here u can see in my chat I am getting spammed. Tt happened mid fight, As soon as I had to use my DragonFlying abilities during intermission. I had to click the binds in order for them to work [1-3]. I was prevented all other abilities as well (fire mage abilities). Only a reload mid fight fixed it.

![ProofElvuiOnly](https://github.com/tukui-org/ElvUI/assets/160275670/a13ddadb-ee7d-42dc-ba53-5bb02a7ec793)
Here a proof I did /edebug on

![ProofElvuiOnly2](https://github.com/tukui-org/ElvUI/assets/160275670/8a72cc53-2337-4018-a68f-99524b0c1521)

Followed by /estatus



Finally, here some /fstack on different abilities and macros if it matters:
![No macro keybind](https://github.com/tukui-org/ElvUI/assets/160275670/2bbc9b5c-7fd3-419d-af8e-27113a90b54b)
![DB macro](https://github.com/tukui-org/ElvUI/assets/160275670/f0292587-2df0-4737-a58f-fd21f4b0e44b)
![Fireball macro](https://github.com/tukui-org/ElvUI/assets/160275670/66cb6770-a370-47ac-9e3d-f82838b72709)

**Comment by 1Botanica1** [comment]
You haven't done the troubleshooting correctly. 

You need to type in chat in game 
`/edebug on` 
Before the fight.  Not after the fight when you are having issues either every addon enabled. 
Not get the issue, then type edebug on 

/edebug on
Test during the fight with only ElvUI - do you have the issue? 

If so, continue with the troubleshooting

**Comment by omri1212000** [comment]
> You haven't done the troubleshooting correctly.
> 
> You need to type in chat in game `/edebug on` Before the fight.
> 
> Not after the fight when you are having issues either every addon enabled. Not get the issue, then type edebug on
> 
> /edebug on Test during the fight with only ElvUI - do you have the issue?
> 
> If so, continue with the troubleshooting

I am not sure why it needs to be mid-boss fight? I told u it also happens when I change spec or mount up, specifically with DragonRiding mounts. Doesn't have to be during combat at all.
Any time the action bar is switched (either by different specs or by changing to DragonRiding abilities) the bug occurs. 
Here is a video showing you everything you want:

https://www.youtube.com/watch?v=Re3Us1N4rqg

And here a quick follow-up video (less than 1min), enabling only BugGrabber addon to show what happen when I try to use a keybind after a spec change:
https://www.youtube.com/watch?v=J_AIDoodAB4

**Comment by 1Botanica1** [comment]
You are the one that posted a screenshot midfight saying about getting spammed errors.  

My reply was in response to that. 

This is for troubleshooting with ElvUI only.  

The taint you posted above (snippet down below) mentions Weak Auras.   That has nothing to do with ElvUI.  


`Here is the bug report trying to click a keybind after changing a spec:

1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Frame:SetPropagateKeyboardInput()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPropagateKeyboardInput'`

Please keep any info provided relevant to the issue and to ElvUI.

**Comment by omri1212000** [comment]
> You are the one that posted a screenshot midfight saying about getting spammed errors.
> 
> My reply was in response to that.
> 
> This is for troubleshooting with ElvUI only.
> 
> The taint you posted above (snippet down below) mentions Weak Auras. That has nothing to do with ElvUI.
> 
> Please keep any info provided relevant to the issue and to ElvUI. There is a lot of unnecessary stuff in this ticket.
> 
> ```
> 
> 1x [ADDON_ACTION_BLOCKED] AddOn 'WeakAuras' tried to call the protected function 'Frame:SetPropagateKeyboardInput()'.
> [string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
> [string "=[C]"]: in function `SetPropagateKeyboardInput' ```
> ```

Ok, can you please ignore the WA report? It was from last night mid fight, which now we know is irrelevant. I made two vids which I linked showing all the troubleshooting steps u requested. We can ignore combat relevance, as it seems it happens when action bar switching is required.

**Comment by omri1212000** [comment]
> Duplicate of #643
> 
> See reply here [#643 (comment)](https://github.com/tukui-org/ElvUI/issues/643#issuecomment-1332455240)

So am I to understand, there is no fix for it as it stands?
Thank you for your help.
