### ISSUE TITLE
Garrison Invasion Alternative Power Bar.

### ISSUE THREAD

**Issue by RAtwood90** [tukui-org/ElvUI#1174]
### Troubleshooting Steps

![WoWScrnShot_022224_163049](https://github.com/tukui-org/ElvUI/assets/73589071/901e0ac6-895e-444a-8acf-21e9fd5240cf)
![WoWScrnShot_022224_163146](https://github.com/tukui-org/ElvUI/assets/73589071/093cc459-58d6-4f7a-b398-def40207afed)
![WoWScrnShot_022224_163153](https://github.com/tukui-org/ElvUI/assets/73589071/f742024c-ac5b-4d3b-98e1-1743a3258195)

### Describe the expected behavior and what actually happened?

The alternative power bar disappears when you mount up to the dragon riding mount. It also no longer becomes visible when you get off the mount.

### Reproducing the issue.

Go to your Garrison.
Do Garrison Invasion.
Mount up on your Dragon Riding Mount.

### Lua Errors

```shell
None.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by E-Tsx** [comment]
not a elvui issue, happens on default ui also
https://github.com/tukui-org/ElvUI/assets/97974579/bd27f3bf-78e6-4e35-a699-1a1b945eb2e0

**Comment by kodewdle** [comment]
seems to be a Blizzard error which means no reason for us to have a ticket open over it :)  closing this, ty for the report however and thanks Tsxy for checking with no addons

**Comment by kodewdle** [comment]
feel free to open a ticket here: https://github.com/Stanzilla/WoWUIBugs/issues
