### ISSUE TITLE
Cannot cancel buffs

### ISSUE THREAD

**Issue by Soromeister** [tukui-org/ElvUI#1175]
### Troubleshooting Steps

![WoWScrnShot_022824_182316](https://github.com/tukui-org/ElvUI/assets/45243695/f7d916f8-9145-4db9-a20c-a04257251ce2)

### Describe the expected behavior and what actually happened?

We should be able to cancel the buffs located on the Buff bar on the Player UnitFrame.

### Reproducing the issue.

1. Have buffs enabled on UnitFrame => Individual Units => Player => Buffs
2. Get any buff on your character (like Mark of the Wild)
3. Attempt to cancel the buff by right clicking it on the buff frame attached to the UnitFrame. This works when right clicking the buff icon near the minimap.

### Lua Errors

```shell
N/A
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
No, it isn't possible to right click to cancel buffs on the unitframe.  

You need to right click the buffs that are, by default, at the Minimap.

**Comment by Soromeister** [comment]
@1Botanica1 Ok, then how can I apply filters to the buff bar near the Minimap? There seems no options are available for that bar, which I can then move it near the UnitFrame to be able to clear buffs there.

**Comment by 1Botanica1** [comment]
There is no option to filter the buffs near the minimap. 

If there was the option to do that (and even if you didn't use that option) the ability to right click to cancel the buff wouldn't be possible.  

No filters - can right click to cancel the buff 

Filters - can't right click to cancel.

**Comment by Soromeister** [comment]
This explains the behavior.

I assume this happens because `/cancelaura` doesn't take a SpellID, but knowing the SpellID you can also get the name, so this in theory should be possible, right?
