### ISSUE TITLE
No action bar display

### ISSUE THREAD

**Issue by Thrashceltic** [tukui-org/ElvUI#1176]
### Troubleshooting Steps

Message: ...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2477: attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)
Time: Fri Mar  1 21:32:06 2024
Count: 1
Stack: ...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2477: attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2477: in function `GetPassiveCooldownSpellID'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2071: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2066>
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1769: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1756>
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1752: in function `UpdateAction'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:667: in function `UpdateState'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:649: in function `SetState'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:345: in function `CreateBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1717: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1657>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1813: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1828: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1854: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1964: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:276: in function <Interface/AddOns/ElvUI/Core/init.lua:275>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = ElvUI_Bar1Button1 {
 0 = <userdata>
 HotKey = ElvUI_Bar1Button1HotKey {
 }
 action = 0
 NewActionTexture = Texture {
 }
 Border = ElvUI_Bar1Button1Border {
 }
 Flash = ElvUI_Bar1Button1Flash {
 }
 FlyoutBorderShadow = ElvUI_Bar1Button1FlyoutBorderShadow {
 }
 Count = ElvUI_Bar1Button1Count {
 }
 NormalTexture = ElvUI_Bar1Button1NormalTexture {
 }
 _state_action = 1
 icon = ElvUI_Bar1Button1Icon {
 }
 AutoCastShine = ElvUI_Bar1Button1Shine {
 }
 AutoCastable = Texture {
 }
 SpellHighlightAnim = AnimationGroup {
 }
 state_actions = <table> {
 }
 state_types = <table> {
 }
 id = 1
 header = ElvUI_Bar1 {
 }
 SpellHighlightTexture = Texture {
 }
 __LAB_Version = 44
 outOfRange = false
 config = <table> {
 }
 FlyoutBorder = ElvUI_Bar1Button1FlyoutBorder {
 }
 _state_type = "action"
 AuraCooldown = Cooldown {
 }
 FlyoutArrow = ElvUI_Bar1Button1FlyoutArrow {
 }
 cooldown = ElvUI_Bar1Button1Cooldown {
 }
 Name = ElvUI_Bar1Button1Name {
 }
}
_actionType = "spell"
actionID = 6603
onEquipPassiveSpellID = nil
(*temporary) = nil
(*temporary) = 1
(*temporary) = "attempt to call field 'GetItemActionOnEquipSpellID' (a nil value)"
C_ActionBar = <table> {
 HasPetActionPetBarIndices = <function> defined =[C]:-1
 FindSpellActionButtons = <function> defined =[C]:-1
 HasSpellActionButtons = <function> defined =[C]:-1
 ShouldOverrideBarShowManaBar = <function> defined =[C]:-1
 IsAutoCastPetAction = <function> defined =[C]:-1
 ToggleAutoCastPetAction = <function> defined =[C]:-1
 ShouldOverrideBarShowHealthBar = <function> defined =[C]:-1
 IsOnBarOrSpecialBar = <function> defined =[C]:-1
 Fin

### Describe the expected behavior and what actually happened?

No more access to the action bar on classic.
Version > ok
action bar > activated
Size change test > no change.
Creation of a new profile > no change.
Test of retrieving a profile via Wago > no change.

### Reproducing the issue.

No change

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Thrashceltic** [comment]
![2024-03-01 21_18_24-World of Warcraft](https://github.com/tukui-org/ElvUI/assets/161887628/496df92d-0d48-4c61-8778-070ccd07519a)
![2024-03-01 21_18_47-Window](https://github.com/tukui-org/ElvUI/assets/161887628/600d1c43-f492-4b54-ac0d-25783cd3e3d3)
![2024-03-01 21_34_46-World of Warcraft](https://github.com/tukui-org/ElvUI/assets/161887628/06f131e6-5e55-4c8f-bd37-0de9dee2d53f)

**Comment by Repooc** [comment]
You need to update ElvUI as you are out of date.

**Comment by Thrashceltic** [comment]
I have a 13.59 version available for download on your site
