### ISSUE TITLE
4x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.

### ISSUE THREAD

**Issue by rifuller** [tukui-org/ElvUI#1178]
### Troubleshooting Steps

![WoWScrnShot_030924_152954](https://github.com/tukui-org/ElvUI/assets/15852038/646ca5bb-b482-450c-a869-5093dfac92c2)

### Describe the expected behavior and what actually happened?

Expected: BugSack is not triggered.
Actual: BugSack catches an error.

### Reproducing the issue.

1. Disable all addons other than ElvUI, BugSack, and BugGrabber
2. Try to open the encounter journal through the shortcut, boss icon on the map. This does not happen every time it's opened but it does eventually happen reliably within a session.

### Lua Errors

```shell
4x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:586: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:575>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2968: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2868: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2676: in function <FrameXML/UIParent.lua:2672>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3278: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3239: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1177: in function `ToggleEncounterJournal'
[string "TOGGLEENCOUNTERJOURNAL"]:1: in function <[string "TOGGLEENCOUNTERJOURNAL"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by rifuller** [comment]
Side note: I am trying to track down a separate issue with the selected talent loadout being incorrect and this may or may not be related.

**Comment by 1Botanica1** [comment]
You have so many addons enabled in that screenshot. 

you need to go through the troubleshooting steps and test if you have the issue with ONLY ElvUI enabled.

**Comment by rifuller** [comment]
Got it. Will give it a shot.  Sorry about the screenshots - I was in a rush.  I did repro it with debug mode enabled but forgot to take a screenshot at the time.
