### ISSUE TITLE
[TBC Bug Report] loot roll window

### ISSUE THREAD

**Issue by Havoc256** [tukui-org/ElvUI#118]
### What is the issue you are having?

The loot roll window has been recently updated. the BoE message over laps with the name of the item.  Love the fact you can resize the window been look for that for a long long time.  Also prefer the rolls on the right not the far left.

![image](https://user-images.githubusercontent.com/10010114/145023901-62a96eb5-e572-4fdd-8425-68d62e9b6076.png)

### What is the expected behavior?

not having the text overlap

### What actually happened?

text is over lapping

### Suggested Solution/Workaround

you can work around it by making the  loot window SUPER long, but then you have to mouse for ever to press the roll buttons.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Luckyone961** [comment]
Increase the Width. Its one of our new options.
