### ISSUE TITLE
Both chats have all the channels

### ISSUE THREAD

**Issue by Polbels** [tukui-org/ElvUI#1181]
### Troubleshooting Steps

Tried to install again and download the new 13.60 release.
Tried de-selecting the channnels and reloading, also tried relogging, they reappear with each login.

### Describe the expected behavior and what actually happened?

The right chat should be for loot, experience gains and such

### Reproducing the issue.

Logging into WoW retail with ELVui installed
![image](https://github.com/tukui-org/ElvUI/assets/164220004/da3505f1-1729-45f5-9f81-9af422465988)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Siora** [comment]
i have the same problem :(

**Comment by tobibachert** [comment]
Same problem

**Comment by grehy** [comment]
same

**Comment by Repooc** [comment]
This happens even in the default ui, not just with elvui
