### ISSUE TITLE
Ticket window above character head, ticket frame nowhere near that area.

### ISSUE THREAD

**Issue by jeffv2011** [tukui-org/ElvUI#1184]
### Troubleshooting Steps

When I hover my mouse above my character, it's empty but says click to be taken to support. Then, if I click the empty space. Blizzard ticket window opens. I have turned off all addons, then re-enables only Elvui and the problem is not there with all addons disable, it is there with only Elvui enabled. 
![elvui info](https://github.com/tukui-org/ElvUI/assets/23734962/d7c933b9-ef8b-4796-9198-caaf99cb761f)
![TICKET FRAME](https://github.com/tukui-org/ElvUI/assets/23734962/2125c958-9880-4127-b6bb-7c4cf01916df)
![TICKET ABOVE HEAD](https://github.com/tukui-org/ElvUI/assets/23734962/51689d93-1b2d-4a0a-a508-566219c606a8)

### Describe the expected behavior and what actually happened?

When mouse is above characters head, it says 'click to open ticket' for blizzard support and when clicked, does open the blizzard ticket system. With all addons disabled = this does not occur. With only Elvui enabled: this does occur. Also, included my Move UI screen to show ticket frame is nowhere near my character.

### Reproducing the issue.

Nothing, just hovering my mouse above my character does it.

### Lua Errors

```shell
None.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [x] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Camski42** [comment]
I am running into the exact same thing. Turn ELVui add-on off. It's fine. Turn it on, the ticket status button is dead center. Can not move or interact with it in any way though Elvui.

**Comment by jeffv2011** [comment]
> I am running into the exact same thing. Turn ELVui add-on off. It's fine. Turn it on, the ticket status button is dead center. Can not move or interact with it in any way though Elvui.

With me, I can click where the box is above my head and it actually does open up my ticket. Perhaps that's because I have an open ticket and you might not?

**Comment by Camski42** [comment]
Oh sorry. I meant I can't interact with it through elvui. I can click on it normally. I also do have an active ticket.

**Comment by Cronuh** [comment]
OH my god and I thought I'm the only one with that issue. It drives me nuts :D

**Comment by 1Botanica1** [comment]
Fixed in dev version.  Can download that or wait until next release. (No eta)

**Comment by Merathilis** [comment]
Fixed in 13.61
