### ISSUE TITLE
The Healing UnitFrame in Group is not updated anymore

### ISSUE THREAD

**Issue by highaktiv** [tukui-org/ElvUI#1185]
### Troubleshooting Steps

![ElvUi-status](https://github.com/tukui-org/ElvUI/assets/164974201/19229eec-bcd9-455c-8de9-767cb450cce0)

### Describe the expected behavior and what actually happened?

The Healing is not Updated i have this Problem und Group UnitFrames and My Frame

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Not sure what you mean by the healing is not updated?
Do you mean the heal prediction?  

You haven’t followed all the steps above.  You have other addons enabled. 

The first step is important

1. Type in game `/edebug on`

2. Test - do you have the issue?

3. If so, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the error and the status panel.

**Comment by highaktiv** [comment]
Yes, I will try it, but it will be difficult to test it under the circumstances maybe in follower dungeons


I marked it, the coloring has changed even though it should be full

**Comment by highaktiv** [comment]
![elvUI-debugMode on](https://github.com/tukui-org/ElvUI/assets/164974201/67b2ca33-f7c0-41c1-baef-262881306462)


Hello, I tried it again to find the error.
I strictly followed your information.

To do this, I went into a follower dungeon and disabled all addons only ElvUI alone and use Command /edebug on
and lo and behold, I still have the error 

for upload a Full UI i type /estatus and make a screenshot.


So it can only be ElvUI or some WoW options?

Please need Help i cant heal so anymore

**Comment by Merathilis** [comment]
Closed. Same in stock Blizzard UI
