### ISSUE TITLE
Cant move Bag Position after Opening.

### ISSUE THREAD

**Issue by DanielSpindler** [tukui-org/ElvUI#1186]
### Troubleshooting Steps

worked back in the days, but no there is no more option to do so.

### Describe the expected behavior and what actually happened?

ofc the bag should be openend where i want it and not in the middle of the screen. i shouldnt have to use other addons to do that for ElvUI. leads to accidently selling stuff from the inventory-

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
ElvUI bags can be moved via the `/moveui` command. If you want to move them temporary while they are open (this position is not saved as it is meant to move them out of your way for that moment) mouse over the ? while the are open for that info
