### ISSUE TITLE
Chat: Input Box - no Background since Client Update today.

### ISSUE THREAD

**Issue by TrusterX** [tukui-org/ElvUI#1188]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/6065454/394a418f-cf99-4819-acad-998206b0f6ad)
the issue is shown on the bottom left chat window

### Describe the expected behavior and what actually happened?

before this happend, the input box has a transparency, overlays the status information window on the left side.

### Reproducing the issue.

i dont know how. This happens after the latest client patch today.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by TrusterX** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/6065454/0176c3e0-a9cc-4318-92f9-cc5173745c2b)
with enabled addons to better visualize the issue in the bottom left corner.

**Comment by 1Botanica1** [comment]
This should be fixed in the dev version https://api.tukui.org/v1/download/dev/elvui/main

You can download that or wait until next release, no ETA

**Comment by TrusterX** [comment]
as i play currently SSF - i didn't need it that much and will wait for the next release.  Thanks in advance!

**Comment by 1Botanica1** [comment]
Fixed in 13.62. Update
