### ISSUE TITLE
Raid Frames Range Fader set to 30y for Disc and Holy Priest

### ISSUE THREAD

**Issue by Ianni** [tukui-org/ElvUI#1189]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/471066/d113a587-834f-4c32-8cd4-5278e4a069f0)

### Describe the expected behavior and what actually happened?

Since the last update the raid frame range fader for priest is set to 30y. 
In the screenshot you can see that the friendly target is healed and according to the unit frames it is out of range. and not just by a little bit. although the 30y are just an estimate. The correct value would be 40y.
This happens only for my holy/disc priest. Druids and Paladins are fine.

### Reproducing the issue.

se above. should be the same for every priest in wotlk

### Lua Errors

```shell
no errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by BRollo1988** [comment]
I also noticed this issue yesterday, very frustrating

**Comment by 1Botanica1** [comment]
Open the spellbook and click on Show All Spells. 
Then reload /rl

**Comment by Lxf3gK** [comment]
Playing SoD and noticed a similar range-related fader issue on resto druid where the target frame for enemies faded when outside of melee range after a recent update. Enabling the "Show all spell ranks" in the Spellbook and reloading as suggested above worked for me.

**Comment by kodewdle** [comment]
this is also fixed in the dev version https://api.tukui.org/v1/download/dev/elvui/main

**Comment by 1Botanica1** [comment]
Fixed in 13.62. Update
