### ISSUE TITLE
Beast Training blocks "Train" buttom

### ISSUE THREAD

**Issue by bevail** [tukui-org/ElvUI#1192]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/166833359/628c63b0-b327-47d3-852f-f527a11d2632)

### Describe the expected behavior and what actually happened?

It should scroll but
Great Stamina (rank 6) all the way to Growl (rank 2) never moves

### Reproducing the issue.

always happens

### Lua Errors

```shell
no lua error
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by bevail** [comment]
ok, it seems like a bug connected to Eltruism and not standalone ElvUI. Sorry

**Comment by bevail** [comment]
seems connected to ElvUI eltruism and not ElvUI.

**Comment by Repooc** [comment]
closed as you have found the issue with eltruism
