### ISSUE TITLE
Change combat text font greyed out

### ISSUE THREAD

**Issue by klute94** [tukui-org/ElvUI#1195]
### Troubleshooting Steps

I have completed all troubleshooting steps, problem still persists.

### Describe the expected behavior and what actually happened?

The option to change the combat text font is greyed out / unclickable. Screenshot attached.
![Screenshot (2)](https://github.com/tukui-org/ElvUI/assets/167113767/53dc780c-a3b2-411c-911f-5e893cdc1733)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You have ultra wide checked.  
uncheck it
