### ISSUE TITLE
Dragonflight fragments does not show awakened crests

### ISSUE THREAD

**Issue by berickus** [tukui-org/ElvUI#1200]
### Troubleshooting Steps

In the datatexts the dragonflight fragments does not show the new awakened crests. It does work on the bags.
![Screenshot 2024-04-29 094218](https://github.com/tukui-org/ElvUI/assets/3184026/8cba680b-2599-4a78-adbb-e6305def10dd)
![Screenshot 2024-04-29 100056](https://github.com/tukui-org/ElvUI/assets/3184026/1b195b6e-7311-40c4-9b42-63c44f6f2582)

### Describe the expected behavior and what actually happened?

Crests are shown in the datatexts

### Reproducing the issue.

Use dragonflight fragments on the datatexts

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
this has already been addressed in the dev build
