### ISSUE TITLE
map shows up on main character but doesnt work on alt

### ISSUE THREAD

**Issue by jaredb12** [tukui-org/ElvUI#1201]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/168802350/828f7abe-95d8-425d-aeae-013411d55961)

### Describe the expected behavior and what actually happened?

just logged in too no minimap on new alt ... the minimap works fine on my main

### Reproducing the issue.

logging in?

### Lua Errors

```shell
Interface/FrameXML/Minimap.lua:461: attempt to call method 'Layout' (a nil value)
Time: Fri May  3 01:01:02 2024
Count: 1
Stack: Interface/FrameXML/Minimap.lua:461: attempt to call method 'Layout' (a nil value)
[string "=[C]"]: in function `Layout'
[string "@Interface/FrameXML/Minimap.lua"]:461: in function <Interface/FrameXML/Minimap.lua:453>

Locals: (*temporary) = <function> defined =[C]:-1
2nd lua error 
Message: Interface/FrameXML/Minimap.lua:389: attempt to call method 'Layout' (a nil value)
Time: Fri May  3 01:01:02 2024
Count: 1
Stack: Interface/FrameXML/Minimap.lua:389: attempt to call method 'Layout' (a nil value)
[string "=[C]"]: in function `Layout'
[string "@Interface/FrameXML/Minimap.lua"]:389: in function <Interface/FrameXML/Minimap.lua:377>

Locals: (*temporary) = <function> defined =[C]:-1
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by jaredb12** [comment]
making a new profile and going back to the old profile fixed the issue

**Comment by 1Botanica1** [comment]
Addons don’t work very well in the starting areas.  

They will be ok once out of the area.
