### ISSUE TITLE
DataText "Durability" don't open Character Pane when in combat

### ISSUE THREAD

**Issue by k0pfnuss** [tukui-org/ElvUI#1203]
### Troubleshooting Steps

1. Done.
2. Yes still have the issue.
3. I click on the DataText "Durability" and get the Character Pane when iam out of fight. If i click it infight i get a "You can't do that in combat". But i can Open it with a Hotkey.
![WoWScrnShot_050624_004817](https://github.com/tukui-org/ElvUI/assets/169001972/db1ff259-49c9-43f0-bf7d-844e40c0140b)

### Describe the expected behavior and what actually happened?

expected behavior:
I click on the DataText "Durability" and get the Character Pane when iam infight. "Block Combat Click" is deactivated and i can open my charakter pane with Blizzard UI when iam in combat.
what actually happened?
I click on the DataText "Durability" and  get a "You can't do that in combat". But i can Open it with a Hotkey.

### Reproducing the issue.

1. Get in combat.
2. Click on the DataText "Durabilitiy" in the chatpanel

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
opening via hotkey vs the datatext is not the same thing and is protected in combat to avoid taints and errors from us doing that in combat, you will/should just use the hotkey to do it in combat
