### ISSUE TITLE
The Chat messages panel and the main chat panel aren't "stuck" to each other

### ISSUE THREAD

**Issue by mixels** [tukui-org/ElvUI#1204]
### Troubleshooting Steps

Resizing the chat using the arrow in the bottom right corner or moving the chat panel by using the Movers feature of ElvUI causes a sort of asynch problem where the chat messages start overflowing the panel. If you move the panel far enough via Movers, the chat messages panel stays where it is, leading to the chat messages being completely outside the panel.

Seems something's not docked correctly.

ElvUI is up to date. I don't believe this issue can apply with default Blizzard UI since both of these panels are ElvUI components.

See attached screenshot.

![2024-05-06 22_45_24-World of Warcraft](https://github.com/tukui-org/ElvUI/assets/7928577/237ec905-087e-4000-88db-952268fbf97e)

### Describe the expected behavior and what actually happened?

When I resize the chat message panel or move the parent chat panel, the whole thing should resize and move together.

### Reproducing the issue.

1) Unlock your chat panel.
2) Resize the left chat panel using the arrow in the bottom right corner. Make it bigger or smaller. Note the ElvUI chat panel does not resize with it.
3) Activate ElvUI Movers and move the left chat panel. Note the chat messages panel does not move with it.

If I use the Movers feature to move the chat messages panel back onto the left chat panel, it snaps in place and stays there. However I'm still not able to resize it because the chat panel won't resize no matter how I manipulate the chat messages panel.

### Lua Errors

```shell
No LUA errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by mixels** [comment]
I figured out how to resize the chat window. It's in ElvUI settings, Chat -> Panels -> Chat Panels section. There you'll see sliders for Panel Height and Panel Width. There is also a checkbox that controls whether panel sizes affect both panels or, if set for separate panels, you get separate sliders.

However the function of the resize arrow isn't clear. Maybe that should be removed if that's possible to minimize confusion.

**Comment by 1Botanica1** [comment]
Blizzard controls the chat, which can be moved in Blizzard edit mode, and ElvUI controls the chat panel. 

It was much easier when ElvUI moved both, but with blizz bringing out edit mode & take over some of the elements - it has ended up with this. 

So they have to be moved separately and sized separately.
