### ISSUE TITLE
No Profile Import anymore?

### ISSUE THREAD

**Issue by carsonwrobel** [tukui-org/ElvUI#1206]
### Troubleshooting Steps

Theres no option to import profiles anymore.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
You obviously skipped the troubleshooting steps when making this ticket and didnt even read the steps and checked everything...
![image](https://github.com/tukui-org/ElvUI/assets/1479745/aac31bae-2ab0-4b1b-95de-00607bf93f99)
![image](https://github.com/tukui-org/ElvUI/assets/1479745/3ea0d672-2479-40e6-91e5-59628cf87893)
you have an addon breaking it from showing most likely which would be found after doing the Troubleshooting Steps
