### ISSUE TITLE
Heal Prediction is Wrong

### ISSUE THREAD

**Issue by pdk-media** [tukui-org/ElvUI#1207]
### Troubleshooting Steps

No bug is showing in the debug process, but it's not working properly.

### Describe the expected behavior and what actually happened?

Ever since the Cataclysm pre-launch, the heal prediction for Healing Wave, Heal, Holy Light, etc, all of the "new" efficient heals, are reading as the heal prediction for Greater Healing Wave, Greater Heal, Divine Light, etc, the big heals.  So you go to cast a regular heal, and it shows you're going to fill up the whole bar, but you only get a small amount of bar filled.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Blizzard provides the heal prediction information, ElvUI uses that. 

Check with no addons, blizzard UI.

**Comment by kodewdle** [comment]
we don't add custom checks for this, it's managed by the APIs.
