### ISSUE TITLE
Sorting bag appears to delete Buzzing/Hissing Runes

### ISSUE THREAD

**Issue by fayths** [tukui-org/ElvUI#1211]
### Troubleshooting Steps

Have the runes in your inventory then hit sort. I use the search function and it's gone - I get inventory space back etc. Easy to reproduce. Checked for updates and relog issue reproduces.
![elvuistatus](https://github.com/tukui-org/ElvUI/assets/43795041/5a560348-c530-4db1-b14e-c524213f32c7)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You haven’t followed the troubleshooting steps asked when you opened your tucket. 

 please go through the troubleshooting steps when making the ticket (linked here https://github.com/tukui-org/ElvUI/wiki/troubleshoot ) and include screenshots - before & after or even better a video of what is happening (with only ElvUI & the status panel showing)

**Comment by fayths** [comment]
https://youtu.be/EByaNkW5MN0
Still bugged to me unless missing something?

**Comment by 1Botanica1** [comment]
![screenshot](https://github.com/tukui-org/ElvUI/assets/5704821/2fa92d19-b484-4a9a-92dc-88aca0831c81)
![screenshot](https://github.com/tukui-org/ElvUI/assets/5704821/2fa92d19-b484-4a9a-92dc-88aca0831c81)

**Comment by 1Botanica1** [comment]
There was no difference in the actual inventory space.   
It is just the runes (gone?) and everything moved left a space until the in the second screenshot there is something in there that isn't in the first screenshot.

**Comment by fayths** [comment]
This time it "added" Darkmoon Faire Game token. When I go to delete it Blizzard thinks it is it as well.

https://i.imgur.com/9H7xXXY.jpeg

**Comment by fayths** [comment]
Disabled Elvui and they show up now.
https://i.imgur.com/QmSGCfW.jpeg

**Comment by E-Tsx** [comment]
top right in elvui bags, click the 2nd icon to open bag bag, and enable whatever bag you have disabled (they should all have checkmarks)

**Comment by fayths** [comment]
> top right in elvui bags, click the 2nd icon to open bag bag, and enable whatever bag you have disabled (they should all have checkmarks)

Holy god I'm an idiot and how did that get disabled.
My bad thanks for the time/help.

**Comment by E-Tsx** [comment]
it happens :p
