### ISSUE TITLE
Nicknames are not colored in class color in chat

### ISSUE THREAD

**Issue by ErsteNacht** [tukui-org/ElvUI#1213]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/104284424/1a3f3a0b-eebe-4a7f-a3c2-81c12846d862)

### Describe the expected behavior and what actually happened?

The text of nicknames is not colored in the class color. I don’t know what’s wrong, I didn’t find a solution to the problem on Google, so I’m writing here. As soon as I disable the "chat" module in ElvUI, I see colored nicknames again. I also tried completely uninstalling the game, then installing ONLY the ElvUI addon and launching the game. The problem remains relevant. I also tried resetting chat settings and "in-game settings" through the Battle.net launcher. Using "/edebug on" does not make any difference.

However, I noticed that the mentioned nickname is displayed correctly, but the sender of the message has no color.
![image](https://github.com/tukui-org/ElvUI/assets/104284424/4ff8b3a5-f72d-4c0e-9476-567df8fb7921)

For example, when using the “Prat 3.0” chat addon, and with the chat module in ElvUI disabled, I see colored nicknames.
Sorry for the spelling, I'm using translator.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
That is a blizzard cvar - not controlled by ElvUI 

Type in chat in game 
`/edebug on` 

### 


Chat issues? Editbox bugged? Colors bugged? Do the following:
- Open the ElvUI options and click on "Install" at the bottom.
- Skip all steps except (2) CVars and (3) Chat.
- Skip to the end and click "Finished"
- Disable these AddOns: Prat, Chatter, Glass, Leatrix Combat Log Hide(Option)


Test.  Do you have class coloured in chat after that?

**Comment by ErsteNacht** [comment]
Yes, it helped me to reset the settings in step 2, to “ElvUI install”. Thanks a lot!!!!
