### ISSUE TITLE
Guild Group Icon Position does not scale with Minimap

### ISSUE THREAD

**Issue by Ianni** [tukui-org/ElvUI#1214]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/471066/0b7d5742-7f96-48b9-84e8-5f88f6a6ba1a)
(yes cropped) but i guess this is sufficient for the issue.
We had the same issue with the "difficulty banner" some months ago.

### Reproducing the issue.

Join any guild raid and have the minimap not at the standard size/scale

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Yes it is cropped, but the rest of the troubleshooting hasn't been done either. 

please go through the troubleshooting steps when making the ticket (linked here https://github.com/tukui-org/ElvUI/wiki/troubleshoot ) and include the requested information.

**Comment by kodewdle** [comment]
reopen if you have the issue after the steps above :)

**Comment by kodewdle** [comment]
should be fixed by https://github.com/tukui-org/ElvUI/commit/1ef511f20d2a2190bdd94100a8ed3a89f2ea74b4
