### ISSUE TITLE
Druid dispellable debuffs in raidframes not highlighting Magic and Poison

### ISSUE THREAD

**Issue by Ianni** [tukui-org/ElvUI#1215]
### Troubleshooting Steps

ElvUI Version 13.64

Yes, I know (again) not the full procedure as you would like it, sorry for that. But I am not sure how to show things not being there in this case.
I will try to make a screenshot the next time it happens in dungeons (I am using the raid layout for 5man).

### Describe the expected behavior and what actually happened?

As a resto druid lvl 85 specced into Nature's Cure (the talent that my dispell also removes magic) I can't see magic or poison debuffs in the raidframes. only curses are visible/hightlighted.
(Poison is also not shown as Moonkin)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
This has been addressed in the dev build already and should be live in the next update of ElvUI which should be out pretty soon.

**Comment by Ianni** [comment]
Thanks, good to know. In the meantime, if anyone has the same problem just replace line 1077 in libDispel.lua with `local cure = true`, although this will make it visible for all druid specs (and game versions)
