### ISSUE TITLE
issue with spell icons on top of raid frames

### ISSUE THREAD

**Issue by AlexAguila79** [tukui-org/ElvUI#1216]
### Troubleshooting Steps

i dont know how to use debug information, besides it wont show any errors

### Describe the expected behavior and what actually happened?

i have an issue when raiding using elvui/toxiui, as soon as the raid is formed, lots of spells and abilities appear on top of every player frame, like a weakauras rotation.
this happens only when i played with a paladin, so far all other classes work just fine.

this is a post on wowhead with screenshots
https://www.wowhead.com/forums/topic/elvui-toxiui-huge-icons-on-raid-grid-issue-341739#p4695503

i have tried removing all addons except for elvui/toxiui and still happens.

any idea of what can be causing this?

thanks in advance.
![WoWScrnShot_052424_135012](https://github.com/tukui-org/ElvUI/assets/170766150/37bce342-09e7-4e99-81be-c2f6b5b13984)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
If you had of done the troubleshooting steps you would see it wasn’t from ElvUI.  That is one of the reasons to do the troubleshooting.  The other is to provide the information requested. 

Type in chat in game 
`/edebug on` 
Test 
Are they still there?  (No - because the aren’t from ElvUI) 
If you still have issues after edebug on, type in chat in game 
`/estatus` and upload a FULL UI screenshot showing the issue and the status panel. 


Disable them from the addon providing them.

**Comment by 1Botanica1** [comment]
Also, this is for reporting errors, it isn’t for support.  If you need help with ElvUI (the issue above is still not from ElvUI) please use discord.

**Comment by AlexAguila79** [comment]
youre absolutely right guys, using debug mode on, those auras wont appear, maybe is toxiui i will keep trying and looking for a reason, im sorry if this wasnt the right communication channel. thanks

**Comment by 1Botanica1** [comment]
It isn’t from ToxiUI - it is another of your addons
