### ISSUE TITLE
Cataclysm Classic. Buffs priority issue.

### ISSUE THREAD

**Issue by Revolution5041** [tukui-org/ElvUI#1218]
### Troubleshooting Steps

Strange behavior of the priority of buff filters associated with mounts. Even if you put the "Mounts" filter in the first position, some effects still turn out to be higher in priority. If you get an effect without a duration before the mount, then the mount follows the effect, violating the priority. For example, if you received Trueshot Aura or Aspect of the Hawk before mount, the aura or aspect will come first.
I use the standard ElvUI v13.65 buff filters priorities with the addition of “Mounts” and set it to first place.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
The filter priority doesn’t set the order in which the auras show on the frames.  It is the filter priority 


If you want to sort the auras differently on the frames, use the X unitframe - buffs - sort by

**Comment by 1Botanica1** [comment]
If you need further support, please use discord.  

If you are reporting issues here, please always add the troubleshooting steps & the screenshots requested when creating a ticket.

**Comment by Revolution5041** [comment]
> The filter priority doesn’t set the order in which the auras show on the frames. It is the filter priority
> 
> If you want to sort the auras differently on the frames, use the X unitframe - buffs - sort by

Sure. Already did it but the result is the same. You can see this in the screenshot.
![WoWScrnShot_052524_105146](https://github.com/tukui-org/ElvUI/assets/170770039/75cf2912-a670-4e2b-8390-3663972e1bc9)

**Comment by 1Botanica1** [comment]
No

that is the opposite of what I have said. 

**The filter priority has no effect on the order that auras are shown**

You need to change the order in 
Player Unitframe - buffs - Sort By (not filter priority)

**Comment by Revolution5041** [comment]
Sorry, my bad. Thank you.

**Comment by Revolution5041** [comment]
So I can't display mounts at the top of the buff list? Because with all the “Sorted by” and “Sort Direction” positions, some effects are still ahead of mounts. Sometimes mounts even is in the middle of the list.
