### ISSUE TITLE
[Retail Bug Report] Some features of ElvUI missing

### ISSUE THREAD

**Issue by SketchStriker** [tukui-org/ElvUI#122]
### What is the issue you are having?

![WoWScrnShot_121321_232655](https://user-images.githubusercontent.com/96106596/145952483-e4299e2b-3302-4eec-8d05-5a1413f3cd2e.jpg)
![WoWScrnShot_121321_232702](https://user-images.githubusercontent.com/96106596/145952493-be16a3ff-e441-43d1-b24a-6cc375b44b07.jpg)
![WoWScrnShot_121321_232956](https://user-images.githubusercontent.com/96106596/145952620-db51efca-50c8-4f94-afb1-57257674c0a1.jpg)
Some of the features are not showing up as ELVUI. Even though I've updated the curseforge shadow and light and the ElvUI.

### What is the expected behavior?

I am hoping someone can help fix this because I am unsure of what happened

### What actually happened?

As you can see above in the screenshots, I was playing the game normally only to come across these issues and I am confused as to how they occurred

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by 1Botanica1** [comment]
Please follow the troubleshooting steps 
TROUBLESHOOTING STEPS
1)Type in chat in game `/edebug on`
2) Test - Do you still have the issue?
3) If you still have the issue/error, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the issue/error and the estatus panel.
