### ISSUE TITLE
My message with linked item is not showing

### ISSUE THREAD

**Issue by rodier** [tukui-org/ElvUI#1222]
### Troubleshooting Steps

![elvui](https://github.com/tukui-org/ElvUI/assets/2135013/0fd3a26a-8782-4ce9-afc3-63af6de4579e)

### Describe the expected behavior and what actually happened?

When I link any mount from Collections to Chat - my message does not appear in chat box.  But others see it. 

### Reproducing the issue.

When I link any mount from Collections to Chat - my message does not appear in chat box. 

### Lua Errors

```shell
no errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
tested with 0 addons and found to be something on blizzards end, not elvui... not sure if we can do anything about it tbh
