### ISSUE TITLE
Class Color Override Less Authority Than Health Breakpoint

### ISSUE THREAD

**Issue by aus10code** [tukui-org/ElvUI#1224]
### Troubleshooting Steps

Health Breakpoint has higher priority than Class Color Override setting `Force On` when the frame is less than 100% health.

### Describe the expected behavior and what actually happened?

If an individual frame has Class Color Override set to `Force On`, that should take priority over the general setting of Health Breakpoint.

The current functionality has the class color show only at 100%. I believe the functionality for `Force On` should leave the class color on permanently when selected for an individual frame. There could be another setting added in the Class Color Override that uses the existing functionality. 

the image below is a monk character and it displays how the Health Breakpoint setting overrides the Class Color Override
![image](https://github.com/tukui-org/ElvUI/assets/62197117/68fb6842-9aef-44ac-b860-db8c84fb6436)

### Reproducing the issue.

enable Class Color Override and Health Breakpoint at same time.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
added a new option "Always" which will keep it 🌼
