### ISSUE TITLE
protected function call 'GetPlaystyleString()'  error

### ISSUE THREAD

**Issue by YoungWoo93** [tukui-org/ElvUI#1225]
### Troubleshooting Steps

![WoWScrnShot_060724_005747](https://github.com/tukui-org/ElvUI/assets/44487641/c403e5e4-1c85-472a-9f88-83828490b4bc)

### Describe the expected behavior and what actually happened?

simply applying for a party and getting rejected is repeatedly causing bugs to accumulate in BugSack.

I couldn't find any mention of this bug in the change log of the latest version of Elv. Since this bug has been observed starting from version 13.64, I am submitting this bug report.

### Reproducing the issue.

1. /edebug on
2. load BugSack / BugGrabber
3. applying party through the party finder
4. rejected from the party

### Lua Errors

```shell
3x [ADDON_ACTION_BLOCKED] 애드온 'ElvUI'|1이;가; 보호된 함수 'GetPlaystyleString()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:4048: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2881: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2878>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
That is a taint

You can read about it here https://github.com/tukui-org/ElvUI/wiki/errors

**Comment by kodewdle** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/595

**Comment by kodewdle** [comment]
people started overriding it to "fix" it since it was protected back then: <https://github.com/0xbs/premade-groups-filter/blob/master/Fixes/FixGetPlaystyleString.lua>
