### ISSUE TITLE
Conquest points not showing right

### ISSUE THREAD

**Issue by kklattrup** [tukui-org/ElvUI#1227]
### Troubleshooting Steps

![conquestdisplay](https://github.com/tukui-org/ElvUI/assets/49807655/f0eec6a2-eb82-4132-a2b4-02334dd5261c)

### Describe the expected behavior and what actually happened?

Expected the season total to show the amount of points I have earned this season (should be about 7700 right now as I capped this week, but missed a few houndred last week), I was also halfway expecting some way of being able to see on a weekly basis, how far I am from capping in case I don't just run it all in one sitting and wait until the amount earned pr match is lower than expected because the cap has been reached.

### Reproducing the issue.

Install ElvUI, play some arena's and spend some points.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kklattrup** [comment]
Honor points seems to have the same problem.

**Comment by Repooc** [comment]
> ### Troubleshooting Steps
> ![conquestdisplay](https://private-user-images.githubusercontent.com/49807655/337636893-f0eec6a2-eb82-4132-a2b4-02334dd5261c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3ODYwMjYsIm5iZiI6MTcxNzc4NTcyNiwicGF0aCI6Ii80OTgwNzY1NS8zMzc2MzY4OTMtZjBlZWM2YTItZWI4Mi00MTMyLWEyYjQtMDIzMzRkZDUyNjFjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE4NDIwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZWY2YWQxM2Y5YmZiM2E0YjFhMDBiMmMwNTU3N2I4ODM3ZDM3ZDlhODYzM2VlNjI2ZDgwZGFjYmY2YmM5NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O1XwiQCuMYu3en7X_sdUm7FdVR4Hr5IFqcm6uaEL3FY)
> 
> ### Describe the expected behavior and what actually happened?
> Expected the season total to show the amount of points I have earned this season (should be about 7700 right now as I capped this week, but missed a few houndred last week), I was also halfway expecting some way of being able to see on a weekly basis, how far I am from capping in case I don't just run it all in one sitting and wait until the amount earned pr match is lower than expected because the cap has been reached.
> 
> ### Reproducing the issue.
> Install ElvUI, play some arena's and spend some points.
> 
> ### Lua Errors
> _No response_
> 
> ### Verification Steps
> * [x]  I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
> * [x]  I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
> * [ ]  I have not read any of these steps, please close my issue when you see it.
> * [x]  I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

This is not following the steps as you missed step 1 which was `/edebug on` . Regardless this, is not an elvui thing as all that data is display by blizzard, we just skins the frame. You can verify this by disabling ALL addons and look.
