### ISSUE TITLE
Cast bars for channeled spells not showing

### ISSUE THREAD

**Issue by noonien** [tukui-org/ElvUI#1228]
### Troubleshooting Steps

Channeled spells do not show up for other units' cast bars in Classic Era.

This is probably because they don't show up in the default UI either, however, other cast bar addons have a workaround that fixes this.

The response I got in Discord was to just use other addons for cast bars, however, as an ElvUI lover, this is not a good solution for me.

There is also another related issue which was closed, https://github.com/tukui-org/ElvUI/issues/1096#issuecomment-1864549853 however, there are not just 2 channeled spells, there are at least 40, 5 classes are affected directly, and all players indirectly.

An example of a workaround is in ClassicCastbar which involves [a list of channeled spells with their cast time](https://github.com/wardz/ClassicCastbars/blob/a477186629d4be4160deb1fd55f88e02c8930e8f/ClassicCastbars/core/ClassicSpellData.lua#L229) and [uses it for classic clients](https://github.com/wardz/ClassicCastbars/blob/a477186629d4be4160deb1fd55f88e02c8930e8f/ClassicCastbars/ClassicCastbars.lua#L141).

Image with a channeling spell:
![image](https://github.com/tukui-org/ElvUI/assets/126649/8d35bcda-81d1-47fb-9baf-45347458ce5e)

Image with a normal spell:
![image](https://github.com/tukui-org/ElvUI/assets/126649/4eaac3af-07a0-4d77-b51b-361242e86b43)

### Describe the expected behavior and what actually happened?

Castbars should be visible for channeled spells.

### Reproducing the issue.

Target self, cast First Aid.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This was the response on discord 

**Castbar - multi shot, aimed shot, penance, channeled spells missing**

Blizzard didn’t show cast bars in classic so a library was used to provide these.  

Blizzard is now showing castbars which broke things ElvUI - so the library was removed.  Blizzard doesn’t show castbars for some casts - channeled spells. 

You will need either a WA or a dedicated cast bar addon

**Comment by noonien** [comment]
I see this issue has been closed but no relevant info in the changelog.

I'm guessing the decision was made to not support channeling cast bars, correct?
