### ISSUE TITLE
Nameplate bug?

### ISSUE THREAD

**Issue by fia111212** [tukui-org/ElvUI#1229]
### Troubleshooting Steps

![weew](https://github.com/tukui-org/ElvUI/assets/172188776/6d8efc0a-9252-468c-9165-9a219675f1fb)

why do the nameplates look like this?? i know it has nothing to do with my settings which is why i think its a bug... when i try to switch to a different profile (default or just one i havent done anything on) the nameplates stay like this!!!  all the neameplates except mine look like this, and not only does it look ugly but its very annoying because i cant see their guild name neither. i just want it to be like it used to be.

no matter how many times i change the font in the nameplate settings this stays the same. usually the nameplates change to this after ive played on the character for a month.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Yours is a Name - not a nameplate 


The others are nameplates. 

**Nameplates & names**

You want to toggle between nameplates & names

Not an ElvUI/ Tukui setting.  It is a blizzard toggle. 
V for enemy 
Shift V for friendly 
Ctrl v for all 

These are the default blizzard keybinds, check the blizzard keybind section if you have changed the binds.
