### ISSUE TITLE
This 13.66 version of ELVUI .....Can not use for 3.4.3 WOW version(Chinese)

### ISSUE THREAD

**Issue by BullFrogLT** [tukui-org/ElvUI#1233]
### Troubleshooting Steps

I'm chinese WOWer, the client version is 3.4.3 of WOW.
Can not see this 13.66 version ElvUI in the game ,  but i can use 13.64 or 13.6x yesterday.....

### Describe the expected behavior and what actually happened?

111

### Reproducing the issue.

11

### Lua Errors

```shell
111
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Yes - ElvUI 13.66 is for wow 4.4.0, not earlier wow versions.  

I know there was talk about ElvUI for the Chinese wow client, but I don't know what is happening at this stage.

**Comment by Luckyone961** [comment]
We will not be adding back support for Wrath of the Lich King for multiple reasons, including the fact that we don't have access to this game build for testing and troubleshooting. The last working ElvUI version for you should be 13.61 if I remember correctly. You can get that from the tag history on GitHub.

**Comment by hubbleppt** [comment]
The version 13.60 works fine for the WoLK. But the "out of date" waning message really bothering me. How can I disable this dialogue box? If any one knows, thanks a lot!
