### ISSUE TITLE
Remove unnecessary decimals

### ISSUE THREAD

**Issue by MathieuLAllier** [tukui-org/ElvUI#1236]
### Troubleshooting Steps

I would like to see the shortValue for health to remove the decimals in certain cases where it isn't needed. For example, when health is full I would prefer seeing 100% vs 100.0% (now).

Or when the target has 23 millions, I would prefer seeing 23 vs 23.2 until a get <1 1M

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
![image](https://github.com/user-attachments/assets/738dc4ab-3122-4c51-b9e0-9dfba63b899b)
