### ISSUE TITLE
WLK3.4.3 use ElvUI 13.60 Is it possible to provide a shutdown method?

### ISSUE THREAD

**Issue by carpediem-777** [tukui-org/ElvUI#1237]
### Troubleshooting Steps

null

### Describe the expected behavior and what actually happened?

![image](https://github.com/tukui-org/ElvUI/assets/24445264/6fdfa59f-7832-4e21-a341-e2215c6b29d7)

### Reproducing the issue.

null

### Lua Errors

```shell
null
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
Not from elvui, its one of your addons... Major sure to read the check boxes and troubleshooting steps that are given when creating a ticket as you wouldn't have had the issue if you did.
