### ISSUE TITLE
Dispellable Debuffs not adhering to Blacklist

### ISSUE THREAD

**Issue by LootFever** [tukui-org/ElvUI#1239]
### Troubleshooting Steps

![image](https://github.com/tukui-org/ElvUI/assets/32418486/3850dacc-2215-49e7-ac4e-4c2dec3484a6)

As I personally don't have the trinket to reproduce the bug/problem it took a while to find a LFR group where someone has it:
![image](https://github.com/tukui-org/ElvUI/assets/32418486/19e827cc-0e88-439b-be0f-17507732a982)

I noticed the problem just in Season 4.
The trinket [Waters Beating Heart](https://www.wowhead.com/item=212682/waters-beating-heart) creates a dispellable magic debuff [Primal Wellspring Water](https://www.wowhead.com/spell=433726/primal-wellspring-water) on the player wearing it.
This Debuff is considered a RaidDebuff and the icon display for it is controlled by the "Show Dispellable Debuffs" setting and the position is the same as RaidDebuffs, yet it is not listed in any filter.
Adding it to the Blacklist or creating a new Blacklist and adding the debuff it is still shown on the Raidframes.

### Describe the expected behavior and what actually happened?

Expected behavior:
Adding the Spell to the Blacklist should prevent it from being shown.

Current behavior:
Adding the spell to the blacklist does nothing. The spell still shows and sometimes overlaps actual RaidDebuffs.
Unchecking the "Show Dispellable Debuffs" option only removes the icon but still changes the ccolor of the UnitFrame.

### Reproducing the issue.

Having someone in your group with the [Waters Beating Heart](https://www.wowhead.com/item=212682/waters-beating-heart) trinket, should be enough to reproduce the "problem".

### Lua Errors

```shell
None
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by LootFever** [comment]
Farmed the trinket for testing. Tried a complete ElvUI reset.
But I still can't find a solution for this problem.

**Comment by Repooc** [comment]
If you mean the Raid Debuff Indicator section? Show Dispellable Debuffs will show regardless of what you add to the blacklist filter. The Raid Debuff Indicator shows what is in the filters that are set in UnitFrames -> General -> Raid Debuff Indicator where you can set 2 filters, the default is RaidDebuffs and CCDebuffs, and you enabled Show Dispellable Debuffs, which will show the icon. If you don't want to see the icon, you will have to disable the option to Show Dispellable Debuffs (as you will not be able to specify to not show a particular debuff that u can dispell) and ensure the spell isnt listed in the 2 filters you have set to ensure its not seen.

**Comment by LootFever** [comment]
So it's working as intended.
Thanks for clarifying.
