### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Treylewous** [tukui-org/ElvUI#124]
### What is the issue you are having?

Upgrading gear error, 
Message: ADDON_ACTION_FORBIDDEN: Details tried to call the protected function 'UpgradeItem()'.
Time: Thu Dec 16 08:52:16 2021
Count: 8
Stack: ADDON_ACTION_FORBIDDEN: Details tried to call the protected function 'UpgradeItem()'.
[string "@Interface\AddOns\Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...UI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `UpgradeItem'
[string "@Interface\AddOns\Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@Interface\FrameXML\StaticPopup.lua"]:325: in function `OnAccept'
[string "@Interface\FrameXML\StaticPopup.lua"]:5137: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>

### What is the expected behavior?

update the ilvl on my gar

### What actually happened?

error code pops up, and gear wont update 

### Errors

```shell
Message: ADDON_ACTION_FORBIDDEN: Details tried to call the protected function 'UpgradeItem()'.
Time: Thu Dec 16 08:52:16 2021
Count: 8
Stack: ADDON_ACTION_FORBIDDEN: Details tried to call the protected function 'UpgradeItem()'.
[string "@Interface\AddOns\Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ils\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Details\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...UI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `UpgradeItem'
[string "@Interface\AddOns\Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@Interface\FrameXML\StaticPopup.lua"]:325: in function `OnAccept'
[string "@Interface\FrameXML\StaticPopup.lua"]:5137: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
A) That is a taint. B) That specifically says Details.. Which means you didn't do the Troubleshooting steps that you checked off as doing.
![image](https://user-images.githubusercontent.com/1934853/146468893-ab85302a-2fa7-43d1-8ec2-94370908f8c2.png)
