### ISSUE TITLE
Beta: LUA Error when pressing "shift" key and cursor is over a building sign in a capitol city

### ISSUE THREAD

**Issue by danieljespersen** [tukui-org/ElvUI#1242]
### Troubleshooting Steps

**If the mouse cursor is hovering over a building sign and the "shift" key is pressed i get the lua error.**

![image](https://github.com/user-attachments/assets/7e852cd7-ca9f-498d-bc93-57d87be84537)

Message: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:980: bad argument #1 to 'FindSpellBookSlotForSpell' (Usage: local spellBookItemSlotIndex, spellBookItemSpellBank = C_SpellBook.FindSpellBookSlotForSpell(spellIdentifier [, includeHidden, includeFlyouts, includeFutureSpells, includeOffSpec]))
Time: Tue Jul 16 09:46:44 2024
Count: 1
Stack: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:980: bad argument #1 to 'FindSpellBookSlotForSpell' (Usage: local spellBookItemSlotIndex, spellBookItemSpellBank = C_SpellBook.FindSpellBookSlotForSpell(spellIdentifier [, includeHidden, includeFlyouts, includeFutureSpells, includeOffSpec]))
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:980: in function `SpellButtonOnEnter'
[string "@Interface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:823: in function `?'
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = UIParent {
 variablesLoaded = true
 Tabs = <table> {
 }
 firstTimeLoaded = 1
}
_ = nil
tt = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 numMoneyFrames = 2
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 updateTooltipTimer = 0.143000
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
E = <table> {
 mylevel = 80
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 wowtoc = 110002
 InfoColor2 = ""
 myname = "Blasphemus"
 ActionBars = <table> {
 }
 myfaction = "Alliance"
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 1920
 versionString = "13.70-153-gf969590"
 LSM = <table> {
 }
 InfoColor = ""
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Alliance"
 myrace = "Human"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Human"
 myclass = "WARLOCK"
 wowdate = "Jul  8 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "These Go To Eleven"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.850000
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }

### Reproducing the issue.

put mouse cursor over a building sign. Press shift key.

### Lua Errors

```shell
Message: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:980: bad argument #1 to 'FindSpellBookSlotForSpell' (Usage: local spellBookItemSlotIndex, spellBookItemSpellBank = C_SpellBook.FindSpellBookSlotForSpell(spellIdentifier [, includeHidden, includeFlyouts, includeFutureSpells, includeOffSpec]))
Time: Tue Jul 16 09:46:44 2024
Count: 1
Stack: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:980: bad argument #1 to 'FindSpellBookSlotForSpell' (Usage: local spellBookItemSlotIndex, spellBookItemSpellBank = C_SpellBook.FindSpellBookSlotForSpell(spellIdentifier [, includeHidden, includeFlyouts, includeFutureSpells, includeOffSpec]))
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:980: in function `SpellButtonOnEnter'
[string "@Interface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:823: in function `?'
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = UIParent {
 variablesLoaded = true
 Tabs = <table> {
 }
 firstTimeLoaded = 1
}
_ = nil
tt = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 numMoneyFrames = 2
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 updateTooltipTimer = 0.143000
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
E = <table> {
 mylevel = 80
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "DAMAGER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = false
 myrole = "DAMAGER"
 UFParent = ElvUFParent {
 }
 wowtoc = 110002
 InfoColor2 = ""
 myname = "Blasphemus"
 ActionBars = <table> {
 }
 myfaction = "Alliance"
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 9
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 220
 callbacks = <table> {
 }
 snapBars = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 1920
 versionString = "13.70-153-gf969590"
 LSM = <table> {
 }
 InfoColor = ""
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Alliance"
 myrace = "Human"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Human"
 myclass = "WARLOCK"
 wowdate = "Jul  8 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "These Go To Eleven"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.850000
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
See https://github.com/tukui-org/ElvUI/issues/1232#issuecomment-2169383205
