### ISSUE TITLE
Gem slots and enchants not showing on character stats/gear screen

### ISSUE THREAD

**Issue by Jenesiswow** [tukui-org/ElvUI#1243]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/e77ab033-e699-4063-a0d0-711a89a40c2d)

### Describe the expected behavior and what actually happened?

used to show gems and enchants

### Reproducing the issue.

log in. issue exists.

### Lua Errors

```shell
none.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
u skipped the first main step, `/edebug on` then do the testing and show `/estatus`

**Comment by Darryl-a-e-l** [comment]
I had the same problem and It has somthing to do with it not likeing deja which we both use dissabling deja works

**Comment by Repooc** [comment]
deja needs to update for our changes, they have code specifically that errors from our changes
