### ISSUE TITLE
Flickering with Portrait and RayTracing

### ISSUE THREAD

**Issue by Teax20** [tukui-org/ElvUI#1244]
### Troubleshooting Steps

![grafik](https://github.com/user-attachments/assets/ae8a8350-c023-44b0-84f8-61ac16dd83bd)

![Animation](https://github.com/user-attachments/assets/e50ed385-fb2e-4a71-9c7d-16c7a667eb0e)

### Describe the expected behavior and what actually happened?

While turning RayTracing and 3D Portrait on, shadows on coastlines are bugged and flicker blue/black. 
Underwater ist unplayable with those flickering. Disabled RayTracing or the Portrait, fixes the issue.

### Reproducing the issue.

- Go to a coastline
- activate portrait + raytracing
- flickering starts

### Lua Errors

no errors

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
elvui doesnt control how the wow engine handles ray tracing, your best bet is to mess with some visual settings or disable ray tracing
