### ISSUE TITLE
"Math.lua:311: script ran too long", pops randomly but 100% when Teleport to Garrison

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#1245]
### Troubleshooting Steps

Is there any "fix" for the bug ``Math.lua:311: script ran too long``?
It's not really a Game Breaking bug but it is annoying!

### Reproducing the issue.

The errors pops also very rare randomly but 100% when Teleport to Garrison.
So the best way to trigger this error is Teleport to Garrison, for me at last.

### Lua Errors

```shell
1x ElvUI/Core/General/Math.lua:311: script ran too long
[string "@ElvUI/Core/General/Math.lua"]:311: in function <ElvUI/Core/General/Math.lua:311>

Locals:
(*temporary) = <function> defined =[C]:-1
(*temporary) = "collect"
(*temporary) = 0
(*temporary) = "script ran too long"
func = <function> defined =[C]:-1
unpack = <function> defined =[C]:-1
data = <table> {
 1 = "collect"
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

Type in chat in game
`/edebug on`
Test
Do you still have the issue?
If you still have issues after edebug on, type in chat in game
`/estatus` and upload a FULL UI screenshot showing the issue and the status panel.

From reports, that happens when you have raider.io enabled as well, doesn’t happen with just ElvUI

**Comment by fubaWoW** [comment]
Nah...
I've many addons besides ElvUI (everyone does!) and i will not disable them.
And no, it's not happening with "just" ElvUI enabled (but who does?!)

Im aware of that more addons and especially "bigger" addons do more load... obviously!
But that is not the point here!
The question is, can you "fix" it?

As of it seems you do unpack sometimes **big** data or even whole UI-Elements with your ``E:Delay`` function so the question is:
Is this needed "all the time" over and over again?

Especially as of this "function" seems VERY performance intensive and not really optimized how to "unpack" way to many UI-Elements at the worst case!

I figured out that ``..\ElvUI\Mainline\Modules\Skins\ExpansionLandingPage.lua`` line 33 ``hooksecurefunc(factionList, 'Create', DelayedMajorFactionList)`` or better say line 25 ``E:Delay(0.1, HandleScrollBar, frame)`` is causing the "overload" in my case!

Disable the **Expansion Landig Page** in the ElvUI Skins Page, also "prevent" this error:
![image](https://github.com/user-attachments/assets/1670cd09-0b63-4c19-ae1a-7e0b22169ca4)

BUT this is just a "workaround" for THIS specific situation only!

It is not a REAL fix, as of the "E:Delay" function is the "bad guy" here!
Maybe it needs some restrictions or filters so this never can happen?

**Comment by 1Botanica1** [comment]
No one is asking you to play with only ElvUI - it is only asked for the first part of the troubleshooting. 

Thanks for looking into the issue further.

**Comment by kodewdle** [comment]
see if this helps (it will go into 13.71) https://github.com/tukui-org/ElvUI/commit/b5cfb631279856079187bc1597d5b04d0631ecd6

**Comment by kodewdle** [comment]
reopen if needed
