### ISSUE TITLE
Keybind text renders over cooldown text in action bars

### ISSUE THREAD

**Issue by c9d5e1** [tukui-org/ElvUI#1253]
### Troubleshooting Steps

![WoWScrnShot_072424_155443](https://github.com/user-attachments/assets/5e6083d3-7642-4156-8083-ad3651e7f935)

### Describe the expected behavior and what actually happened?

The expected behaviour is for the cooldown text to be rendered above the keybind text, but instead, the keybind text renders over the cooldown text.

### Reproducing the issue.

Should work without having to reproduce anything. Perhaps scale the size of your keybind text if it is too small to interfere with the cooldown text.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
• Hotkey text was over Cooldowns (this was something Blizzard changed so this fix only applies to our Actionbars).
 https://github.com/tukui-org/ElvUI/commit/b37b20c4a3f5167b5c80ef0d0ac3226686b40f76
