### ISSUE TITLE
Mouse Hover for Uniframe is not working

### ISSUE THREAD

**Issue by Syanez133** [tukui-org/ElvUI#1254]
### Troubleshooting Steps

Unitframe fader stopped working as intended with the prepatch. No longer am I able to mouse over my unitframe to display the frame. 
![Wow_IOYXWWs17z](https://github.com/user-attachments/assets/e9bcf1d8-9961-4198-bf03-d61f138f12b0)
![Wow_OMLgzkbOCC](https://github.com/user-attachments/assets/6935a8d8-6832-422e-87cf-f2b25f67cbd1)

### Describe the expected behavior and what actually happened?

The expected should be that I mouse over the hidden frame and it appears. but the actual is when I mouse over the unit frame it does not appear.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Stevespim** [comment]
I have this exact same issue too. I'm glad someone has reported it so I don't make a duplicate post.

**Comment by kodewdle** [comment]
fixed in dev
