### ISSUE TITLE
Map is big, Echap Menu is big

### ISSUE THREAD

**Issue by fttf7** [tukui-org/ElvUI#1255]
### Troubleshooting Steps

It seems there is a problem with the map size and the Esc menu. Changing the size of the map in the Elvui options changes nothing and changing the interface scale in the Blizzard options also changes nothing.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is the size blizzard has set. It can’t be changed.

**Comment by fttf7** [comment]
We could change it before, right?

**Comment by kodewdle** [comment]
![image](https://github.com/user-attachments/assets/06a92e8c-a8dd-4b59-87ad-104184e0e4dd)

**Comment by fttf7** [comment]
I find the bug ! Its Windtools :) 
My post can be delete
