### ISSUE TITLE
TWW prepatch issues

### ISSUE THREAD

**Issue by angryatoms92** [tukui-org/ElvUI#1256]
### Troubleshooting Steps

I got on the game today and realized that the elvui addons were not working. I've installed them correctly and they have been working fine since before the prepatch. Now none of my addons work at all. I uninstalled them, then reinstalled them. I have no idea what's wrong

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Sounds like you haven’t installed ElvUI correctly. 

**ElvUI version number**
Type in chat in game /dump C_AddOns.GetAddOnMetadata('ElvUI', 'Version') & upload a screenshot

If it doesn’t say 13.71 - you haven’t updated correctly. 

**It is recommended to download/update via a client**. 
Either the
[Tukui client](<https://tukui.org/client>) - downloads/updates ElvUI (and backups your WTF folder)  

Or 
[WowUp client](<https://wowup.io/>) - downloads/updates ElvUI and all your other addons.
Or
[Wago client](<https://addons.wago.io/app>) - downloads/updates ElvUI and your wago hosted addons.

If you need further help, please post in discord - that is for troubleshooting

**Comment by 1Botanica1** [comment]
https://discord.gg/tukui-community-209244641537556480
