### ISSUE TITLE
"world zone text" not functioning

### ISSUE THREAD

**Issue by Woodencross** [tukui-org/ElvUI#1257]
### Troubleshooting Steps

<img width="1193" alt="image" src="https://github.com/user-attachments/assets/0ab86e16-1e44-452a-b353-1982f4d8281a">

### Describe the expected behavior and what actually happened?

the "world zone text" setting is not functioning, the zone text on the map is too small.
<img width="592" alt="image" src="https://github.com/user-attachments/assets/9ec8b032-6386-454f-a9bf-9da0861b0adb">

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
![image](https://github.com/user-attachments/assets/6de86283-fb7c-4879-98dc-3050d7972a91)


World zone text refers to this text.

**Comment by Woodencross** [comment]
> ![image](https://private-user-images.githubusercontent.com/5704821/352352749-6de86283-fb7c-4879-98dc-3050d7972a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NjM4NTMsIm5iZiI6MTcyMTk2MzU1MywicGF0aCI6Ii81NzA0ODIxLzM1MjM1Mjc0OS02ZGU4NjI4My1mYjdjLTQ4NzktOThkYy0zMDUwZDc5NzJhOTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMDMxMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQzNzQ4NjQwNDhjOTMwMzdmZjczYTg0MDFlODc0NGUzMzNmNjRmOTRhMTRiNjE3NGRjZWM5OTA4YWQ2YjI4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OUyNmDcjX5dOx2SMBeRy1ZUXfRBhQqwuVqQ9KM51tbs)
> 
> World zone text refers to this text.

Thanks, then which setting refers to the small text in my image, if I may ask? The larger text in my image is controled by "world sub zone" as I tested so I think the smaller one is the "world zone text". This keeps confusing me.

**Comment by Woodencross** [comment]
solved, just uncheck "general-fonts-no font scale" and it's good.
