### ISSUE TITLE
[Feature Request] Skins for communities Add dialog window & Options for loot windows

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#126]
Communities Add dialog window is not skinned now. So will be good if it skinned!
https://imgur.com/a/x4rZQQQ

And hope it will be good there's options for loot window like icon size  or font sizes(count / dropped item name / loot frame title)

**Comment by Repooc** [comment]
if i recall, it hasnt been skinned bc its a secure frame and will cause taints.  Azil or Simpy can confirm when they get a chance to read the ticket

**Comment by Azilroka** [comment]
It's secure.

**Comment by hobulian** [comment]
> if i recall, it hasnt been skinned bc its a secure frame and will cause taints. Azil or Simpy can confirm when they get a chance to read the ticket

Options for loot windows also causes taints??

**Comment by Repooc** [comment]
Idk what that has to do with this ticket as the loot window is skinned...
