### ISSUE TITLE
[Feature Request] Custom Quest Log DataText

### ISSUE THREAD

**Issue by drsleo** [tukui-org/ElvUI#1268]
No Label and Custom Color.

I know, I know, this isn't the best time for this :D, but if anyone finds it interesting, maybe check it out in the future, thanks

The intention would be to put the datext next to the game's objective tracker, since the first line of the objective tracker is static right now.

I know there are addons that do this like benik and mediatag, but they override the shadow and light settings.

**Comment by Repooc** [comment]
Create your own datatext panel and move it where you want with `/moveui`
We have 0 plans to integrate any more datatext panels as the elements that it makes sense on already has it.  In Datatext -> Panels you can make your own panel

**Comment by drsleo** [comment]
![elvui](https://github.com/user-attachments/assets/58a2f12d-8ad2-4e9b-8886-ff28e3be3d51)

I think you didn't understand correctly, as my game is not in English I don't know exactly the names of each tab and functions in English. As in the photo, I'm talking about the tab where you can configure several elvui datatexts, that's what I'm talking about, the possibility of being able to do this in this Datatext.

**Comment by Repooc** [comment]
Able to do what in the datatext? You have not made it clear what you want. It sounded like you want to move a datatext panel next to the objective tracker which you can do already.
