### ISSUE TITLE
[Feature Request]  Adding options for Loot windows

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#127]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Adding options for Loot windows. Like changing icon size / Loot window title text size / Looted item text sizes. It now has it's own fixed value so users cannot change it without changing it's lua file.
I red-squared that regions in SC below.
https://imgur.com/a/H8tuh0R

**Additional context**
I knew you guys added loot roll window options. But i think it will be good there also be loot windows option for it's icon size or text sizes.

**Comment by Repooc** [comment]
ahh that loot, i was thinking u meant loot roll... of course we added something like that for our loot roll frame but doing something specific for the loot frame like that isnt going to happen... the font is set from General -> Media which includes the font size.... the frame size/icon size are based on UI Scale like pretty much all blizzard frames we skin

**Comment by hobulian** [comment]
Hmm. I think icon size is now not only based on Ui scale but it has it's own value when i opened lua file of loot frame.
But I agree that text font sizes are fixed to settings in General -> Media. But you guys cannot make separate options for that?
Sometimes loot frame's text size is too small for me in my korean client.

**Comment by Repooc** [comment]
After talking to another dev, as I didn't dbl check our code... It is our module not a skinned version so maybe we will do something to help with it

**Comment by Repooc** [comment]
options been added in dev

**Comment by hobulian** [comment]
At least i think there be scaling options for this
