### ISSUE TITLE
Display character Info

### ISSUE THREAD

**Issue by footfred999** [tukui-org/ElvUI#1272]
### Troubleshooting Steps

![display](https://github.com/user-attachments/assets/405bb871-edea-409c-b4e5-5362e7050619)

display character info cant be activating

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You haven’t gone through the troubleshooting steps as asked for when you opened the ticket. 

Type in chat in game 
`edebug on` 
Test - do you have the issue?  If so, type in chat in game 
`/estatus` 
And upload a FULL UI uncropped screenshot showing both the issue and the status panel.

**Comment by 1Botanica1** [comment]
![image](https://github.com/user-attachments/assets/2213156c-91ec-48ce-b984-e0e668db6bf6)

**Comment by footfred999** [comment]
Yeah i tried to delet my post but i cant find how :/

Le dim. 28 juill. 2024, 11 h 03 p.m., Botanica ***@***.***> a
écrit :
