### ISSUE TITLE
Reagent bank not sorting

### ISSUE THREAD

**Issue by jonmudrick** [tukui-org/ElvUI#1275]
### Troubleshooting Steps

![WoWScrnShot_072924_233342](https://github.com/user-attachments/assets/aaa68413-a593-42ef-8618-c0602705fe4e)

### Describe the expected behavior and what actually happened?

Expectation: Reagent bank sorts like regular bags, grouping items together and clustering them at the bottom
Actual: "Sort Bags" button does default blizz behavior of cleaning up extra stacks but no further sorting is done, leaving items where they were in the bag.

### Reproducing the issue.

1. Open Bank
2. Open Reagents tab
3. Click "Sort Bags" button in upper right of bank window

### Lua Errors

```shell
no apparent lua errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
this is a blizzard bug, try it with no addons

**Comment by kodewdle** [comment]
should be fixed in live by blizzard
