### ISSUE TITLE
Wintools and BenikUi modules lost on one of my characters.

### ISSUE THREAD

**Issue by Rypley001** [tukui-org/ElvUI#1278]
### Troubleshooting Steps

![capture_elvui_issue](https://github.com/user-attachments/assets/ad685fdf-71a9-420f-acc5-580e7b45ad1d)

### Describe the expected behavior and what actually happened?

Hello, I use the latest version of Elvui (13.72). But also the Benikui and WindTools modules.
It has always worked well but since patch 11.0 of WOW Retail one of my characters no longer displays the two modules, they are no longer present in the Elvui configuration window either.
On all my other characters I do not have this problem. It is only on one (unfortunately my main).
I tried to reset the mod on this character, I tried to delete all the mods, the WTF, Interface and Cache folders. It did not solve the problem.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is for ElvUI only. 

BenikUI & Windtools are by other authors and you need to report any issues directly to them.  

Before reporting to BenikUI, type in chat in game 
`/edebug on` 
Then enable only BenikUI 
Does it work? 
if so, find the addon that is stopping it from working & report to that author.  Most likely you have an outdated addon stopping it from working.
