### ISSUE TITLE
[Feature Request] Worldmap questmap frame not overlapping quest reward frame

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#128]
**Is your feature request related to a problem? Please describe.**
yes. questmap frame at worldmap frame is now overlapping quest reward frame like in SC
https://imgur.com/a/7SfBaS1

**Describe the solution you'd like**
I think it should be like this
https://imgur.com/a/0cL3a0l
1. quest reward frame's backdrop height should be shorter. or it has separate option to disable quest reward frame skinning, or backdrop using gradation texture like original one. And it’s border should be hidden
2. questmapframe's backdrop anchoring should be like
QuestMapFrame.DetailsFrame.backdrop:Point('TOPLEFT', -3, 0)
QuestMapFrame.DetailsFrame.backdrop:Point('BOTTOMRIGHT', QuestMapFrame.DetailsFrame.RewardsFrame, 'BOTTOMRIGHT', 1, -1)
So it's border should not be shown behind quest texts.

**Comment by kodewdle** [comment]
you were close with 2, goodjob :)
i set some new points to make it slightly cleaner look! 

![image](https://user-images.githubusercontent.com/2266754/168453191-dc90893d-bc82-457b-aa32-4e890cb45a45.png)
