### ISSUE TITLE
Elvui Lua Error

### ISSUE THREAD

**Issue by raven1000** [tukui-org/ElvUI#1285]
### Troubleshooting Steps

Check your addons yourself!

### Describe the expected behavior and what actually happened?

Check your addons yourself!

### Reproducing the issue.

Don't you check your addons in all WOW clients before releasing them?
How bad are you?

### Lua Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/Blizzard/QuestWatch.lua:32: attempt to index local 'QuestTimerFrame' (a nil value)
Time: Sun Aug  4 06:26:54 2024
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/Blizzard/QuestWatch.lua:32: attempt to index local 'QuestTimerFrame' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1822: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1863: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1975: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:302: in function <Interface/AddOns/ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:354
 mylevel = 42
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:411
 Config_OpenWindow = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:1029
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1436
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:453
 ScheduleTimer = <function> defined @Interface/AddOns/Decursive/Libs/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RemoveEmptySubTables = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:624
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:138
 Cooldown_UnbuggedTime = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:19
 Config_CreateFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:827
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 ScanTooltip_InventoryInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:955
 ScanTooltip_UnitInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:943
 Layout = <table> {
 }
 UnregisterEventForObject = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1752
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1255
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 PositionGameMenuButton = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:795
 UIFrameFade = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:361
 TimeIndicatorColors = <table> {
 }
 StaticPopup_IsLastDisplayedFrame = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:486
 StaticPopup_CreateSecureButton = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1103
 Truncate = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:142
 SetupReset = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:544
 ToggleMoveMode = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:70
 Dump = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:474
 WorldMap = <table> {
 }
 Disable = <function> defined @Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:310
 TimeColors = <table> {
 }
 SlideOut = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:296
 Unhook = <function> defined @Interface/AddOns/Decursive/Libs/AceHook-3.0/AceHook-3.0.lua:417
 XPIsTrialMax = <function> defined @Interface/AddOns/ElvUI/Core/G
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Wow, what a rude way to write a ticket!    

Do you not understand blizzard makes unannounced changes which addons must then update to the changes.  

Was going to help, but considering your tone!

**Comment by raven1000** [comment]
Hi, I don't get anything for this report! Just the fact that I report an error here should be respected.

I'm a programmer and I know exactly what needs to be done in your LUA mess.

But if I'm called rude here because of just one ticket report, find your own mistakes.

I will no longer use your addon.

**Comment by raven1000** [comment]
Hi, I don't get anything for this report! Just the fact that I report an error here should be respected.

I'm a programmer and I know exactly what needs to be done in your LUA mess.

But if I'm called rude here because of just one ticket report, find your own mistakes.

I will no longer use your addon.

**Comment by raven1000** [comment]
Hi, I don't get anything for this report! Just the fact that I report an error here should be respected.

I'm a programmer and I know exactly what needs to be done in your LUA mess.

But if I'm called rude here because of just one ticket report, find your own mistakes.

I will no longer use your addon.

**Comment by 1Botanica1** [comment]
Hi, its a free addon, the devs don't ask for anything for you to use it, so by your understanding, they should be respected.  

Yes, you got called rude, whether it be one or more tickets, because of how you worded this ticket. 

Feel free to use another addon :) especially if you think that is appropriate way to act.

**Comment by Crumdidlyumshis** [comment]
So if you're a programmer and know what the issue is and how to fix it, then why don't you provide a PR fix without slandering the developers of this add-on? Maybe not using it would be wise.

**Comment by 1Botanica1** [comment]
If you are a programmer, you would know the importance of the troubleshooting steps. 

You chose to open a ticket and you chose to word it like that.  You can choose to word it differently. 

But anyways, I hope you have a better day, it must be going bad for you to think it is ok to act like that.
