### ISSUE TITLE
Archaeology Bar Placement Being Overwritten

### ISSUE THREAD

**Issue by sparkystrike** [tukui-org/ElvUI#1287]
### Troubleshooting Steps

![2024-08-04](https://github.com/user-attachments/assets/ed5640b7-a91c-4e67-9396-915ef68de498)
YouTube Video uploaded to show the issue: https://youtu.be/C5QUGVMrz0U

### Describe the expected behavior and what actually happened?

Expected Behavior: Movement of the archaeology bar using Blizzard's Edit UI should be honored across sessions.

Actual Behavior: The archaeology bar placement is being overwritten by ElvUI upon entry into a new session.

### Reproducing the issue.

1. Access Blizzard's Edit UI
2. Enable the Archaeology Bar (if not already active)
3. Move the bar anywhere on the screen (I would like it at the top)
4. Begin using archaeology during the same game session (requires archaeology site) [Note: The placement of the archaeology bar is honored.]
5. Reload the UI (/reload)
6. Begin using archaeology during the same game session (requires archaeology site) [Note: The placement of the archaeology bar is changed to the middle of the screen.]

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by sparkystrike** [comment]
I'm pretty sure it was staying put with just the Blizzard UI, but I'll double-check one more time tonight.

**Comment by sparkystrike** [comment]
I have disabled all addons (including ElvUI), and the problem does not occur in the Blizzard UI. I have disabled all addons except ElvUI, and the problem persists.

**Comment by kodewdle** [comment]
fixed by https://github.com/tukui-org/ElvUI/commit/407853c93b96a941c03b548d409060169b4ef0e6
