### ISSUE TITLE
Quest Log, Expand/Collapse, hovering not working properly

### ISSUE THREAD

**Issue by Mera42** [tukui-org/ElvUI#1288]
### Troubleshooting Steps

![Elvui-Questlog-Collapse](https://github.com/user-attachments/assets/79346e4b-9e5c-4f06-a719-8e95a0d06ac2)

### Describe the expected behavior and what actually happened?

**Expected behavior :** hovering and clicking on the line of text next to'+' or '-' icons to collapse/expand quest zone instead of clicking on the very tiny icon which is frustrating when playing on low scale (pixel perfect)

### Reproducing the issue.

Open **QuestLog** and try to Expand/Collapse

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This is fixed in dev and will be in next release.
