### ISSUE TITLE
[Retail Bug Report] Nameplates: list of names under triggers displays always the same name

### ISSUE THREAD

**Issue by RaulRG** [tukui-org/ElvUI#129]
### What is the issue you are having?

I created a style filter for my nameplates and added different entries by name under "Triggers". The panel displays always the same name instead of the original ones. It does not matter if you use the NPC ID or the name, it just repeats one of them for all the checkboxes.
If you go to the combobox "Remove Name or NPC ID" you can see the different names, so I think it is a problem with the panel displaying the wrong names for the checkboxes.

I am using version 12.58.
![elvui](https://user-images.githubusercontent.com/6229748/147576791-a705d344-77c7-4f27-9e1d-c18e19e158b4.png)

### What is the expected behavior?

The panel for "Name" under "Triggers" should display the original names for the comboboxes instead of repeating one of them.

### What actually happened?

The panel displays the wrong names or IDs

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Repooc** [comment]
already been fixed in dev build, just hasnt been released

**Comment by RaulRG** [comment]
Thank you!! You are great! My bad, I just looked at the open issues

**Comment by Repooc** [comment]
no worries, i dont think anyone reported it and we had fixed it before anyone had reported it just havent done a release just yet since the fix.
