### ISSUE TITLE
[Retail Bug Report] Vehicular UI buttons empty during "Made to Order" quest in Ember Court Scenario

### ISSUE THREAD

**Issue by solkarnar** [tukui-org/ElvUI#130]
### What is the issue you are having?

In the weekly Ember Court scenario, there will be a quest "Made to Order" where we have to go into a dredger and turn on vehicular ui. Somehow the vehicular ui buttons are empty when I hop into the dredger. When i turned off ElvUI and used the default UI, the buttons became showed the correct quest buttons.

More explanation of the problem here : https://www.reddit.com/r/wow/comments/nbpgjl/ember_court_made_to_order_functionality/

### What is the expected behavior?

Vehicular UI must show quest buttons

### What actually happened?

Vehicular UI quest buttons are empty

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
I have done this several times and the buttons always show for me.
I only use a handful of addons anyway so there isn't a conflict.
That's what the troubleshoting steps are for.
