### ISSUE TITLE
Quest sidepanel reskinning broke for 11.0.2.56110

### ISSUE THREAD

**Issue by jeremy-hill** [tukui-org/ElvUI#1301]
### Troubleshooting Steps

Seems some change Blizzard made today broke skinning the quest panel:

![image](https://github.com/user-attachments/assets/1c919835-ed7a-4ce3-9bac-fa22a258fd36)

### Describe the expected behavior and what actually happened?

Side panel should be skinned.

### Reproducing the issue.

Ensure 'Quest Frames' is enabled under Skins.

### Lua Errors

```shell
4x ElvUI/Core/Modules/Skins/Skins.lua:1103: attempt to index local 'frame' (a nil value)
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1103: in function `HandleBlizzardRegions'
[string "@ElvUI/Mainline/Modules/Skins/Quest.lua"]:429: in function <ElvUI/Mainline/Modules/Skins/Quest.lua:323>
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:2187: in function <ElvUI/Core/Modules/Skins/Skins.lua:2182>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadFunc'
[string "@ElvUI/Core/General/Core.lua"]:1852: in function `CallLoadedModule'
[string "@ElvUI/Core/General/Core.lua"]:1878: in function `InitializeModules'
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>
```
```


### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by RAtwood90** [comment]
> ### Troubleshooting Steps
> Seems some change Blizzard made today broke skinning the quest panel:
> 
> ![image](https://private-user-images.githubusercontent.com/66854273/357611633-1c919835-ed7a-4ce3-9bac-fa22a258fd36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzIzNzYsIm5iZiI6MTcyMzczMjA3NiwicGF0aCI6Ii82Njg1NDI3My8zNTc2MTE2MzMtMWM5MTk4MzUtZWQ3YS00Y2UzLTliYWMtZmEyMmEyNThmZDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE0Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NjgzOTQ4NDE4OGU2ZTBlMWY1MGUyYzIwNjViNjQ0ZjdjNzE3ZGQxM2EyNDVlODgwMzRjNDA1NjZhZjk5NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5IdLVMuzPVmUmE1_Q3OhNmOHh9sOwd88gn10uh0PYto)
> 
> ### Describe the expected behavior and what actually happened?
> Side panel should be skinned.
> 
> ### Reproducing the issue.
> Ensure 'Quest Frames' is enabled under Skins.
> 
> ### Lua Errors
> ```shell
> 4x ElvUI/Core/Modules/Skins/Skins.lua:1103: attempt to index local 'frame' (a nil value)
> [string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1103: in function `HandleBlizzardRegions'
> [string "@ElvUI/Mainline/Modules/Skins/Quest.lua"]:429: in function <ElvUI/Mainline/Modules/Skins/Quest.lua:323>
> [string "=[C]"]: ?
> [string "@ElvUI/Core/Modules/Skins/Skins.lua"]:2187: in function <ElvUI/Core/Modules/Skins/Skins.lua:2182>
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "@ElvUI/Core/General/Core.lua"]:1837: in function `CallLoadFunc'
> [string "@ElvUI/Core/General/Core.lua"]:1852: in function `CallLoadedModule'
> [string "@ElvUI/Core/General/Core.lua"]:1878: in function `InitializeModules'
> ...
> [string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
> [string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
> [string "=[C]"]: in function `CreateFrame'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
> [string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>
> ```
> 
> ```
> 
> 
> ### Verification Steps
> 
> - [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
> - [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
> - [ ] I have not read any of these steps, please close my issue when you see it.
> - [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.
> ```

Do these steps in order:
Type in game: /edebug on  (or /ec, on left [Information], on top [Debug])
Test. Still have the issue?
NO Issue is probably another addon or plugin. Skip to the last step.
YES Type in game: /estatus  (or /ec, on top [Status])
Upload a full, uncropped screenshot showing the issue and the status panel.
Finished with debugging? Type in game: /edebug off.

**Comment by jeremy-hill** [comment]
![image](https://github.com/user-attachments/assets/28c6ebb6-2cbd-4a9e-b3c1-fcc755fe7a7f)

**Comment by jeremy-hill** [comment]
![image](https://github.com/user-attachments/assets/d59983bb-2a1b-4024-8933-b4c0de528fa7)

**Comment by jeremy-hill** [comment]
I have everything checked for 'Skins': 
![image](https://github.com/user-attachments/assets/b2076c26-dbe9-48bc-aaf9-9e4673c905c4)
