### ISSUE TITLE
Disable bags module option is not remembered

### ISSUE THREAD

**Issue by brett1337** [tukui-org/ElvUI#1302]
### Troubleshooting Steps

When I uncheck Enable bags module it is not saved across any character regardless of if they share the same elvui profile.

### Describe the expected behavior and what actually happened?

I expect the enable elvui bags option to at least be saved for the same profile, but given that people often do this because they use a different bag addon (for me it is BetterBags), I think the expected behavior would be to change the option for your whole account regardless of profile. In reality I have to uncheck on each character and also refresh each time. Also BetterBags does overwrite the B button press regardless of this option but not opening bags via inventory, but I suspect that is a fault with that addon not elvui.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
It is stored in the private (per character) settings not the profile.  

Your options 
Disable the bag module on each toon 
Use the same private profile across each toon 
Create your own installer to have the settings you want
