### ISSUE TITLE
Gold Window Offscreen

### ISSUE THREAD

**Issue by KatyPurry** [tukui-org/ElvUI#1303]
### Troubleshooting Steps

Have a lot of characters then hover gold datatext. If you have too many character not all window is displayed.

### Describe the expected behavior and what actually happened?

Suggestion : Limit the display to X characters with the most gold?
![Sans titre-1](https://github.com/user-attachments/assets/f84f13e3-bac3-42b1-b649-a745a19ab47d)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by RAtwood90** [comment]
> ### Troubleshooting Steps
> Have a lot of characters then hover gold datatext. If you have too many character not all window is displayed.
> 
> ### Describe the expected behavior and what actually happened?
> Suggestion : Limit the display to X characters with the most gold? ![Sans titre-1](https://private-user-images.githubusercontent.com/89610869/358203130-f84f13e3-bac3-42b1-b649-a745a19ab47d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MzIyMTgsIm5iZiI6MTcyMzczMTkxOCwicGF0aCI6Ii84OTYxMDg2OS8zNTgyMDMxMzAtZjg0ZjEzZTMtYmFjMy00MmIxLWI2NDktYTc0NWExOWFiNDdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDE0MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOWM5OWNhZGFmYTc2ZDBiNTYyMThkNDJmZjM1YzA5NGNjZTg2NjVmMzY1YWI4NjMyYTQzN2JkNjYwNDZmYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jcm97BfuMgQ8ABRItOqTaP4yh_YLF0XSmGVkEV-0PGA)
> 
> ### Reproducing the issue.
> _No response_
> 
> ### Lua Errors
> _No response_
> 
> ### Verification Steps
> * [x]  I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
> * [x]  I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
> * [ ]  I have not read any of these steps, please close my issue when you see it.
> * [x]  I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

Hello! I can see serveral Addons loaded in the Background please do:

Do these steps in order:
Type in game: /edebug on  (or /ec, on left [Information], on top [Debug])
Test. Still have the issue?
NO Issue is probably another addon or plugin. Skip to the last step.
YES Type in game: /estatus  (or /ec, on top [Status])
Upload a full, uncropped screenshot showing the issue and the status panel.
Finished with debugging? Type in game: /edebug off.

**Comment by KatyPurry** [comment]
Hello, 

Please find an uncropped screenshot on debug mode with status : 

![Sans titre-3](https://github.com/user-attachments/assets/cc81560f-f9a6-4992-8d41-8031c3f19177)

**Comment by kodewdle** [comment]
thanks for the suggestion, will be in the next version 🌼
