### ISSUE TITLE
Problems Selling Junk Items

### ISSUE THREAD

**Issue by marcelhdl** [tukui-org/ElvUI#1304]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/e1b762cc-29dd-46fb-8211-db23026455d6)

You can see the red Error on top, i just opened the vendor on the left.
The same error appears if you click the sell gray items button in the bags.

### Describe the expected behavior and what actually happened?

If i open any vendor i expect to sell my gray items

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
do the grey items all have a value when this happens?

**Comment by marcelhdl** [comment]
I think so, yes.

**Comment by kodewdle** [comment]
so far, i can't reproduce this;  do you know if you had any special items, perhaps a Quest item or something like that?  maybe a newer item like Warband, etc?

**Comment by kodewdle** [comment]
actually, this isn't a bug in ElvUI at all.  this is how blizzard's Sell Junk works.  if you want to use ours, disable the Use Blizzard Sell Junk in our options and click the button from our bags.
