### ISSUE TITLE
Power parent not saving

### ISSUE THREAD

**Issue by Deranged-Hermit** [tukui-org/ElvUI#1305]
### Troubleshooting Steps

![bug report](https://github.com/user-attachments/assets/f08ea115-17ed-44cd-8750-2aa7ff5ce3a3)

### Describe the expected behavior and what actually happened?

Prior to TWW prepatch the power bar was always behind the health bar. I can go in and manually change it by selecting UIparent than going back and selecting Frame and it still works but any reload, logout or joining group resets the power bar back to being UIParent.

How it should look
![image](https://github.com/user-attachments/assets/bf81d930-a597-4256-a7eb-525660822a06)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
last month we added options for frame strata and level if u look in ur screenshots, u will see the tab, that is prob what changed that you were not aware of 79f2eeb265d7c960841eca0f7a60f127400c1501

**Comment by Deranged-Hermit** [comment]
Changed it to custom on Frame level and it now works. Thanks for the quick fix.
