### ISSUE TITLE
Failed to load elvui plugin

### ISSUE THREAD

**Issue by Guy-Z** [tukui-org/ElvUI#1307]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/dd5a8d84-a359-461d-b35a-41fe4c34aa2a)
Execution of commands `/edebug on`, `/estatus`, and `/ec` all failed
![image](https://github.com/user-attachments/assets/49850c55-69f2-4b1f-a3e4-a16d5d17613b)

### Describe the expected behavior and what actually happened?

![image](https://github.com/user-attachments/assets/ba96d96d-5426-4c50-8900-50f8f842f842)

### Lua Errors

```shell
Message: ...ries/Core/Ace3-ElvUI/AceGUIWidget-DropDown-ElvUI.lua:2: attempt to call global 'LibStub' (a nil value)
Time: Fri Aug 16 23:27:34 2024
Count: 1
Stack: ...ries/Core/Ace3-ElvUI/AceGUIWidget-DropDown-ElvUI.lua:2: attempt to call global 'LibStub' (a nil value)

Locals:
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
By the looks of the error you are cloning/downloading directly from github which is not supported unless u know what you are doing. Info about this was posted in our Announcement channel in discord when we altered the repo.

**Comment by Guy-Z** [comment]
Thanks for your answer, I must have made a mistake.
