### ISSUE TITLE
LUA Error on open EncounterJournal when Skin "Blizzard_EncounterJournal" is enabled

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#1309]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/3744f9b3-7713-4c8d-a357-8eda5fa6d861)

### Describe the expected behavior and what actually happened?

LUA Error when open the EncounterJournal 
``ElvUI/Mainline/Modules/Skins/EncounterJournal.lua:256: attempt to index field 'reset' (a nil value)``

``EncounterJournal.encounter.info`` does not always? contain a "reset" value, missing -> "value exists check"?!

### Reproducing the issue.

Open Encounter Journal

### Lua Errors

```shell
Message: ...ns/ElvUI/Mainline/Modules/Skins/EncounterJournal.lua:256: attempt to index field 'reset' (a nil value)
Time: Tue Aug 20 18:00:11 2024
Count: 1
Stack: ...ns/ElvUI/Mainline/Modules/Skins/EncounterJournal.lua:256: attempt to index field 'reset' (a nil value)
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:998: in function `ToggleEncounterJournal'
[string "TOGGLEENCOUNTERJOURNAL"]:1: in function <[string "TOGGLEENCOUNTERJOURNAL"]:1>

Locals:
```

possible fix, remove ``EncounterInfo.reset:StripTextures()`` at line 256 and replace
```LUA
EncounterInfo.reset:ClearAllPoints()
EncounterInfo.reset:Point('TOPRIGHT', EncounterInfo.difficulty, 'TOPLEFT', -10, 0)
_G.EncounterJournalEncounterFrameInfoResetButtonTexture:SetTexture([[Interface\EncounterJournal\UI-EncounterJournalTextures]])
_G.EncounterJournalEncounterFrameInfoResetButtonTexture:SetTexCoord(0.90625000, 0.94726563, 0.00097656, 0.02050781)
```
with
```LUA
if EncounterInfo.reset then
  EncounterInfo.reset:StripTextures()
  EncounterInfo.reset:ClearAllPoints()
  EncounterInfo.reset:Point('TOPRIGHT', EncounterInfo.difficulty, 'TOPLEFT', -10, 0)
  _G.EncounterJournalEncounterFrameInfoResetButtonTexture:SetTexture([[Interface\EncounterJournal\UI-EncounterJournalTextures]])
  _G.EncounterJournalEncounterFrameInfoResetButtonTexture:SetTexCoord(0.90625000, 0.94726563, 0.00097656, 0.02050781)
end
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Thanks for the report. 

This has already been fixed in the dev version and will be in next release.
