### ISSUE TITLE
[Feature Request] Make Smart Raid Filter smarter

### ISSUE THREAD

**Issue by sergeysh93** [tukui-org/ElvUI#131]
**Is your feature request related to a problem? Please describe.**
Best way to use ELVUI raidframes now is "raid" for mythic raids or raids less than 21 ppl, and "raid40" for the rest
In mythic raid frames switchs to raid40, with smart filter availiable if there are more than 20 ppl in raid (including benched ppl) 

**Describe the solution you'd like**
Make smart raid filter priority check for player's current dungeon difficulty, and if it's mythic raid, force it to "raid"

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >

**Additional context**
< Add any other context or screenshots about the feature request here. >

**Comment by kodewdle** [comment]
this is a little, messed up.  we know and we have a plan to create something even better however the work is not finished for that yet.  forcing raid instead of raid40 wouldn't fix the problem when people are doing bigger raids for example.  we have a plan it's just not done yet.
