### ISSUE TITLE
No options for the AddonCompartmentFrame in Minimap options

### ISSUE THREAD

**Issue by strongbow25** [tukui-org/ElvUI#1310]
### Troubleshooting Steps

![elvui](https://github.com/user-attachments/assets/9dbb5edd-43c5-4dc2-9211-603ba096c34e)

### Describe the expected behavior and what actually happened?

I would like to see options to hide, reposition, and/or scale the missing icons. (Obviously no option to hide the queue status icon - that's req'd). I can use other addons to do this but would prefer if it were added to ElvUI.

![minimap](https://github.com/user-attachments/assets/ec7d68c1-a62f-4955-9518-8ed3804cf23b)

### Reproducing the issue.

Open ElvUI Options, go to Map, select Minimap tab, and see that the two frames are not listed.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by strongbow25** [comment]
Actually ... just the AddonCompartmentFrame. Just noticed the QueueStuts mover. Sorry about that.

**Comment by strongbow25** [comment]
And a friend just pointed me to the BlizzUI improvements which allows for hiding and rescaling of the AddOn Compartment. While it would still be nice to reposition it, you I'm just going to close this issue. Sorry for wasting your time. :I

**Comment by 1Botanica1** [comment]
> improvements

`/emove` and move the anchor for it.
