### ISSUE TITLE
Your discord link in both github & website not working

### ISSUE THREAD

**Issue by spiitf1re** [tukui-org/ElvUI#1314]
### Troubleshooting Steps

Your discord link in both github & website not working

### Describe the expected behavior and what actually happened?

Your discord link in both github & website not working

### Reproducing the issue.

Your discord link in both github & website not working

### Lua Errors

```shell
Your discord link in both github & website not working
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
sure it does, it just redirected me without an issue, more info is needed

**Comment by Repooc** [comment]
You may also be banned... again, without any useful info, cant really give you any other info
