### ISSUE TITLE
Target UnitFrames cannot worked

### ISSUE THREAD

**Issue by feverearl** [tukui-org/ElvUI#1315]
### Troubleshooting Steps

When I switch specializations, the target frame is not highlighted，the range is ok，is it a bug or setting error？
![WoWScrnShot_082224_191103](https://github.com/user-attachments/assets/e3d71644-26fc-4637-80c2-a1322d6155e4)
![WoWScrnShot_082224_191050](https://github.com/user-attachments/assets/e74bb208-507d-4df4-b312-ba2ab9e75a97)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
That is fixed in dev and will be in next release. 

Please when reporting an issue, follow the troubleshooting steps to provide the information requested.

**Comment by feverearl** [comment]
thanks your report

发自移动版 Gmail


Botanica ***@***.***>于2024年8月23日 周五03:34写道：

**Comment by kodewdle** [comment]
fixed in 13.76
