### ISSUE TITLE
Action bar 1 switches when stance is changed

### ISSUE THREAD

**Issue by tyggerdev** [tukui-org/ElvUI#1318]
### Troubleshooting Steps

.

### Describe the expected behavior and what actually happened?

Upon updating to version 13.75, action bar 1 started changing to action bar 7 when I changed my stance to shadowform.  This has never happened in many years I've used Elvui.  I wiped out elvui including files in WTF and ran Wow without it, and action bar 1 does not change to action bar 7 on shadowform.

I downgraded to version 13.74, and things are back to normal.

The issue exists within 13.75.

### Reproducing the issue.

.

### Lua Errors

```shell
.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Remove the paging from action bar 1 if you don’t want it to change when you go into shadow form.

**Comment by tyggerdev** [comment]
Thank you! That did fix it. I've never noticed that text field before, probably because it was never relevant until now.

Looks like some changes were made to that field over the update which caused this:
Action Paging:

13.74
[bonusbar:1] 7;
>
13.75
[form:1] 7;

I just deleted cleared the text box. Fixed.

**Comment by 1Botanica1** [comment]
Yes, ElvUI updated it due to a blizzard change.
