### ISSUE TITLE
Nameplate filter lua bug

### ISSUE THREAD

**Issue by OldKing6666** [tukui-org/ElvUI#1319]
### Troubleshooting Steps

1.In the Nameplate filter,when setting conditions related to skill cooldown, a lua error occurs and the filter fails.
![1](https://github.com/user-attachments/assets/ed70af31-7283-4935-9a78-f48c8c50a8dc)
![2](https://github.com/user-attachments/assets/02db33da-7cfd-4ae6-9cd0-a795803740ca)
![3](https://github.com/user-attachments/assets/d0583628-8870-4a2c-ae0a-85196820263b)

2.step 1
![5](https://github.com/user-attachments/assets/b65a3a63-c490-48df-9c65-777a2aa9b33a)

3.step2
![6](https://github.com/user-attachments/assets/d20ec42a-31fc-4d02-bc21-16a544865904)

4.BugSack
![4](https://github.com/user-attachments/assets/6f3da68f-1b22-4aa5-9370-9127acfcea0a)

### Describe the expected behavior and what actually happened?

In the Nameplate filter,when setting conditions related to skill cooldown, a lua error occurs and the filter fails.This never happened in previous versions.

### Reproducing the issue.

Set the nameplate to change color when the spell cooldown is out and the target casts interruptible spells.A lua error is displayed and the filter is invalid.

### Lua Errors

```shell
Message: ...izzard_TimeManager/Mainline/Blizzard_TimeManager.lua:94: attempt to perform arithmetic on local 'alarmTime' (a nil value)
Time: Sat Aug 24 12:27:06 2024
Count: 1
Stack: ...izzard_TimeManager/Mainline/Blizzard_TimeManager.lua:94: attempt to perform arithmetic on local 'alarmTime' (a nil value)
[string "@Interface/AddOns/Blizzard_TimeManager/Mainline/Blizzard_TimeManager.lua"]:94: in function <...izzard_TimeManager/Mainline/Blizzard_TimeManager.lua:90>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:565: in function `TimeManager_LoadUI'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:1410: in function <...rface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua:1290>

Locals: self = TimeManagerFrame {
 layoutType = "PortraitFrameTemplate"
 AlarmTimeFrame = TimeManagerAlarmTimeFrame {
 }
 Inset = TimeManagerFrameInset {
 }
 PortraitContainer = Frame {
 }
 TopTileStreaks = Texture {
 }
 Bg = TimeManagerFrameBg {
 }
 TitleContainer = Frame {
 }
 CloseButton = TimeManagerFrameCloseButton {
 }
 NineSlice = Frame {
 }
}
alarmTime = nil
(*temporary) = <table> {
 alarmEnabled = false
 alarmHour = 12
 alarmMessage = ""
 alarmAM = true
 alarmMinute = 0
 localTime = true
 militaryTime = true
}
(*temporary) = ""
(*temporary) = ""
(*temporary) = "timeMgrAlarmTime"
(*temporary) = "attempt to perform arithmetic on local 'alarmTime' (a nil value)"
Settings = <table> {
 alarmEnabled = false
 alarmHour = 12
 alarmMessage = ""
 alarmAM = true
 alarmMinute = 0
 localTime = true
 militaryTime = true
}
CVAR_USE_MILITARY_TIME = "timeMgrUseMilitaryTime"
CVAR_USE_LOCAL_TIME = "timeMgrUseLocalTime"
CVAR_ALARM_TIME = "timeMgrAlarmTime"
CVAR_ALARM_MESSAGE = "timeMgrAlarmMessage"
CVAR_ALARM_ENABLED = "timeMgrAlarmEnabled"
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
this won't be in 13.76 because i just seen this.  you can try dev here: [elvui-main.zip](<https://api.tukui.org/v1/download/dev/elvui/main>)

**Comment by OldKing6666** [comment]
> this won't be in 13.76 because i just seen this. you can try dev here: [elvui-main.zip](https://api.tukui.org/v1/download/dev/elvui/main)这不会出现在 13.76 中，因为我刚刚看到了这个。您可以在此处尝试 Dev：[elvui-main.zip](https://api.tukui.org/v1/download/dev/elvui/main)

After updating 13.76,there are still problems with the nameplate filter.
