### ISSUE TITLE
Shortvalue text display isn't correct

### ISSUE THREAD

**Issue by MathisVkg** [tukui-org/ElvUI#1320]
### Troubleshooting Steps

Hello everyone, 

Since some version of Elvui, I have a bug with the "shortvalue" tag in my custom text for health display.
The shortvalue doesn't display the correct amount of healt after the million. You can see on the first screenshot my full health currently without the shortvalue tag (1 226 590) and on the second screenshot the health shortered with the shortvalue tag.

Nomally it should display 1.2M but here instead I have just 1M. The text is rounded to the lowest value, and when health comes close to 2M in this case it rounding to the highest value.
Another thing to note, is if my health go below 1M, the display become good and the shortvalue work correctly.

I try already to reinstall completely Elvui and disable all addon but the display is always incorrect. Also changing profile or going on default profile is the same.

Here is custom text but the bug also happens in the default health section in UnitFrames category

![ElvuiBug1](https://github.com/user-attachments/assets/0159663a-4b6d-4eae-ada9-ce93ddde305a)
![ElvuiBug2](https://github.com/user-attachments/assets/02c28483-7fbd-4a4e-8459-c440bd3c58d2)

### Describe the expected behavior and what actually happened?

Shortvalue tag from Elvui doesn't display the correct amount of health after pass the million

### Reproducing the issue.

Create custom text with tag '"shortvalue" for display health

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
**Health not showing decimals** or to show more/less decimals 

Set the decimal length 
ElvUI - Search (top right) - decimal

**Comment by MathisVkg** [comment]
@1Botanica1 I didn't know there was a decimal setting in Elvui. I don't know how this setting got changed by himself with the update/or maybe mistake from my side but anyway now I can fix this thing :)

Thank you very much
