### ISSUE TITLE
Can't Adjust font placement on action bars with Masque enabled

### ISSUE THREAD

**Issue by jardragon901** [tukui-org/ElvUI#1325]
### Troubleshooting Steps

![Screenshot 2024-08-25 160337](https://github.com/user-attachments/assets/ea047bbd-f398-4734-a2a9-0594de7fe9a6)

notice how the fonts on the actionbar are all squished together on the right side.

### Describe the expected behavior and what actually happened?

When Masque is turned on font placement is completely broken, you change the x or y and it skips for a second like its trying to change it but nothing happens. Works perfectly with Masque off. Buffs and debuffs work fine, just seems to be the actionbar buttons.

### Reproducing the issue.

Deactivate Masque, move key binding and/or stack font placement on the actionbars, will move just fine. Reactivate Masque and the fonts will be moved to their default positions and changing the x or y will not work in the elvui actionbar settings. 

### Lua Errors

```shell
no lua errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
If you have masque enabled, the position is handled by masque, not ElvUI
