### ISSUE TITLE
[Feature Request] Skin for infobox frames

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#133]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
https://imgur.com/a/e3NBCuD
Like SC above, Some info boxes skinned somehow not clean. 

**Describe alternatives you've considered**
Think it will be much clean if info boxes skinned just like way tooltips skinned.

**Comment by hobulian** [comment]
Garrison Building Frame's info box is still needed to be skinned i think.

**Comment by Azilroka** [comment]
Nope. They are all changed over.
