### ISSUE TITLE
In version 13.76, the backpack cannot be summoned

### ISSUE THREAD

**Issue by xinoer** [tukui-org/ElvUI#1331]
### Troubleshooting Steps

In version 13.76, after replacing the material pack with the new 38-slot material pack released in version 11.0, the backpack cannot be summoned.
![微信截图_20240827172103](https://github.com/user-attachments/assets/dbf299f6-b392-43b8-8c35-62692e604bd4)
![微信截图_20240827172120](https://github.com/user-attachments/assets/9f893a7d-b448-469c-a624-22b945a718e0)

### Describe the expected behavior and what actually happened?

120x ElvUI/Core/Modules/Bags/Bags.lua:1256: attempt to index local 'slot' (a nil value)
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:1256: in function `Layout'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:1382: in function `SetBagAssignments'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:1408: in function `UpdateDelayedContainer'
[string "@ElvUI/Core/Modules/Bags/Bags.lua"]:1472: in function <ElvUI/Core/Modules/Bags/Bags.lua:1434>

Locals:
self = <table> {
 IsEquipmentSlot = <table> {
 }
 BagFrame = ElvUI_ContainerFrame {
 }
 BAG_FILTER_ICONS = <table> {
 }
 QuestSlots = <table> {
 }
 BagIndice = <table> {
 }
 name = "ElvUI_Bags"
 QuestKeys = <table> {
 }
 QuestColors = <table> {
 }
 ItemLevelSlots = <table> {
 }
 defaultModuleState = true
 REAGENTBANK_SIZE = 98
 SortUpdateTimer = Frame {
 }
 SellFrame = ElvUIVendorGraysFrame {
 }
 AutoToggleClose = <table> {
 }
 BankTab = 1
 BankFrame = ElvUI_BankContainerFrame {
 }
 WARBANDBANK_SIZE = 98
 ProfessionColors = <table> {
 }
 Initialized = true
 BagFrames = <table> {
 }
 AssignmentColors = <table> {
 }
 baseName = "ElvUI"
 db = <table> {
 }
 numTrackedTokens = 0
 modules = <table> {
 }
 enabledState = true
 hooks = <table> {
 }
 GearFilters = <table> {
 }
 WarbandBanks = <table> {
 }
 BindText = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 WarbandIndexs = <table> {
 }
 Dropdown = <table> {
 }
 orderedModules = <table> {
 }
 moduleName = "Bags"
 ExcludeVendors = <table> {
 }
 AutoToggleEvents = <table> {
 }
 ExcludeGrays = <table> {
 }
}
isBank = nil
f = ElvUI_ContainerFrame {
 Bags = <table> {
 }
 pickupGold = Button {
 }
 spinnerIcon = ElvUI_ContainerFrameSpinnerIcon {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 bottomOffset = 8
 totalSlots = 185
 template = "Transparent"
 __windShadow = 1
 ContainerHolderByBagID = <table> {
 }
 closeButton = ElvUI_ContainerFrameCloseButton {
 }
 WTMoveFramesHandled = true
 BagIDs = <table> {
 }
 vendorGraysButton = Button {
 }
 currencyButton = Frame {
 }
 shadow = Frame {
 }
 backdropInfo = <table> {
 }
 bagsButton = ElvUI_ContainerFrameBagsButton {
 }
 PixelSnapDisabled = true
 BottomEdge = Texture {
 }
 DelayedContainers = <table> {
 }
 stackButton = ElvUI_ContainerFrameStackButton {
 }
 holderFrame = Frame {
 }
 ContainerHolder = ElvUI_ContainerFrameContainerHolder {
 }
 TopRightCorner = Texture {
 }
 helpButton = ElvUI_ContainerFrameHelpButton {
 }
 goldText = FontString {
 }
 Center = Texture {
 }
 staleBags = <table> {
 }
 BottomRightCorner = Texture {
 }
 sortButton = ElvUI_ContainerFrameSortButton {
 }
 TopEdge = Texture {
 }
 mover = ElvUIBagMover {
 }
 NewItemGlow = <table> {
 }
 editBox = ElvUI_ContainerFrameEditBox {
 }
 events = <table> {
 }
 BottomLeftCorner = Texture {
 }
 LeftEdge = Texture {
 }
 topOffset = 50
}
lastButton = ElvUI_ContainerFrameBag5Slot36 {
 BottomLeftCorner = Texture {
 }
 IconOverlay = Texture {
 }
 centerText = FontString {
 }
 AugmentBorderAnim = AnimationGroup {
 }
 showMatchHighlight = true
 flashAnim = AnimationGroup {
 }
 RightEdge = Texture {
 }
 equipIcon = Texture {
 }
 NewItemTexture = Texture {
 }
 glossTex = true
 TopEdge = Texture {
 }
 bagFrame = ElvUI_ContainerFrame {
 }
 emptyBackgroundAtlas = "bags-item-slot64"
 Count = ElvUI_ContainerFrameBag5Slot36Count {
 }
 searchOverlay = ElvUI_ContainerFrameBag5Slot36SearchOverlay {
 }
 LeftEdge = Texture {
 }
 NormalTexture = ElvUI_ContainerFrameBag5Slot36NormalTexture {
 }
 pushed = Texture {
 }
 name = "ElvUI_ContainerFrameBag5Slot36"
 Cooldown = ElvUI_ContainerFrameBag5Slot36Cooldown {
 }
 BagIndicator = Texture {
 }
 Stock = ElvUI_ContainerFrameBag5Slot36Stock {
 }
 bindType = FontString {
 }
 IconBorder = Texture {
 }
 icon = ElvUI_ContainerFrameBag5Slot36IconTexture {
 }
 ScrapIcon = Texture {
 }
 questIcon = ElvUI_ContainerFrameBag5Slot36IconQuestTexture {
 }
 newItemGlow = Texture {
 }
 HighlightTexture = Texture {
 }
 PixelSnapDisabled = true
 flash = Texture {
 }
 hover = Texture {
 }
 PushedTexture = Texture {
 }
 BottomRightCorner = Texture {
 }
 BattlepayItemTexture = Texture {
 }
 newitemglowAnim = AnimationGroup {
 }
 itemContextMatchResult = 3
 itemLocation = <table> {
 }
 template = "Default"
 itemLevel = FontString {
 }
 SlotID = 36
 timeSinceUpgradeCheck = 0
 UpgradeIcon = Texture {
 }
 BagID = 5
 Center = Texture {
 }
 BottomEdge = Texture {
 }
 ItemContextOverlay = Texture {
 }
 TopRightCorner = Texture {
 }
 IconQuestTexture = ElvUI_ContainerFrameBag5Slot36IconQuestTexture {
 }
 TopLeftCorner = Texture {
 }
 backdropInfo = <table> {
 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
![image](https://github.com/user-attachments/assets/66a08d19-700f-4d78-b58b-23c84803b347)
closing bc of duplicate and did not read instructions
#1329 #1328 #1327
