### ISSUE TITLE
Extra Action Button (Boss Button) changing size

### ISSUE THREAD

**Issue by lowpita** [tukui-org/ElvUI#1339]
### Troubleshooting Steps

Whenever Im in combat and a special spell pops up the extra action button changes size, like +25% bigger than normal compared to getting it out of combat.
![1](https://github.com/user-attachments/assets/42616edd-d71b-4e6c-9491-1c6bfa2e015f)
![2](https://github.com/user-attachments/assets/a1e7d588-a4c9-4ff8-9e2a-957a94867bf9)

### Lua Errors

```shell
No lua errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by lowpita** [comment]
Updated to 13.73 and still same

**Comment by 1Botanica1** [comment]
13.76 is current. 

Please also test with no addons, blizzard UI

**Comment by lowpita** [comment]
Yeah misstyped, meant to say 13.76. I did test it with no addons as you can see on the screenshots.

**Comment by Azilroka** [comment]
We think Blizzard may change the scale depending on encounter and we only scale it one time..

**Comment by lowpita** [comment]
> You did test with addons - ElvUI
> 
> Test with no addons, blizzard UI

Oh I see. That'd be really hard to test for me as my whole UI depends on elv, but will try to do. Maybe forcing it to rescale when in combat might fix it.

**Comment by lowpita** [comment]
> We think Blizzard may change the scale depending on encounter and we only scale it one time..

Dont think it depends on encounter because it actually happened on every single content when the spell triggers during combat. So if I get the extra action button before encounter starts and get in combat it would stay the same scale as before. It only changes scale when the button spawns during combat.

**Comment by lowpita** [comment]
I've finally tested this without any addons and it doesnt change size within combat nor when leaving it with the blizzard UI. So it's an elvui issue.

**Comment by kodewdle** [comment]
have this pinned, will look into it soon

**Comment by kodewdle** [comment]
fixed by https://github.com/tukui-org/ElvUI/commit/92a275e9674f23bfa6e7254929e5d6f77be55321

**Comment by lowpita** [comment]
Thanks :)
