### ISSUE TITLE
Bar 1 is copying bar 7

### ISSUE THREAD

**Issue by inarmswestorm** [tukui-org/ElvUI#1342]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/b3f131f0-1a0c-481f-9065-b6582a253873)

### Describe the expected behavior and what actually happened?

Bar 1 is being replaced with abilities on bar 7. Keybinds remain tied to bar 1. Moving abilities off either bar changes both bars. This happened after updating from 13.71 to 13.76

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
**Action bar 1 changing for Priests in Shadowform / shadow form**
With the Blizzard changes, bar 1 now pages when in shadow form
* If you don't bar 1 to change in shadowform - Actionbar 1  - Action Paging - remove the `[form:1, spec:3] 7;` and hit `accept`
* If you want shadowform to page another bar - Action bar 1 - Action Paging - `[form:1, spec:3] 7;` - change the 7 to another bar.
