### ISSUE TITLE
Dragonflight Fragments Datatext Panel update for TWW

### ISSUE THREAD

**Issue by mitchguthmann** [tukui-org/ElvUI#1344]
### Troubleshooting Steps

![Screenshot 2024-08-31 185544](https://github.com/user-attachments/assets/4c5b15a6-2d59-4ec0-acf0-4c76e12f129f)

### Describe the expected behavior and what actually happened?

"Dragonflight Fragments" should be linked to the new crests in TWW, probably rename also to make relevant

Datatext in Panel option still linked to DF crests and flightstones

### Reproducing the issue.

ElvUI > DataTexts > Panels > Datatext Panel > choose Dragonflight Fragments.

### Lua Errors

```shell
NA
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by mitchguthmann** [comment]
Of cause after I post this i find that its being addressed in pull #1332 

if someone could confirm that would be great.

**Comment by 1Botanica1** [comment]
It is in dev version, you can manually install here https://api.tukui.org/v1/download/dev/elvui/main or wait until next release, no ETA

**Updating ElvUI manually** 
Delete the folders
ElvUI
ElvUI_Options
ElvUI_Libraries

Then cut and paste the new 
ElvUI
ElvUI_Options
ElvUI_Libraries

Always need to delete the old folders first, not copy over

**Comment by mitchguthmann** [comment]
Thanks for the update, not urgent so happy to wait for next release.
