### ISSUE TITLE
Missing Scenario StepsText

### ISSUE THREAD

**Issue by ChrPtt** [tukui-org/ElvUI#1345]
### Troubleshooting Steps

In the standard user interface, you will see a scenario text at the top of the screen. This is missing in the ElvUI.
Example from City of Threats Event for 2nd Boss.
![image](https://github.com/user-attachments/assets/b303bbba-82eb-4ce4-9dd0-d09c823a121b)

### Describe the expected behavior and what actually happened?

This Text should be shown somewhere in ElvUI as well.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
In  ElvUI - General - BlizzUI Improvements
Do you have Hide Error Text enabled?

If so, this is blizzards Error and Quest Progression Text (it is already renamed for the next ElvUI release)

If it is enabled, uncheck it and test. 

If it isn't enabled, or you still have issues, please go through the troubleshooting. 

Type in chat in game
`/edebug on`

Test

If you still have the issue, type in chat in game `/estatus` and upload a full ui screenshot showing the issue and the status panel,
