### ISSUE TITLE
Shadowform Action Bar

### ISSUE THREAD

**Issue by cheyndn** [tukui-org/ElvUI#1346]
### Troubleshooting Steps

![Screenshot 2024-08-31 111112](https://github.com/user-attachments/assets/ab8b17e4-de44-42e4-bc80-ba0e1a009e31)

### Describe the expected behavior and what actually happened?

When I swap to shadowform, it is not changing my action bar to a shadowform bar. 

### Reproducing the issue.

![Screenshot 2024-08-31 111613](https://github.com/user-attachments/assets/2c6643a6-b13d-48bd-b122-2486f6b4b79e)
I click on shadowform. An my action paging has [form:1,spec:3]7;

### Lua Errors

```shell
None
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
This has been fixed in dev & will be in next release.  

You can remove the  `, spec:3` part of the action bar paging for it to work. (A change needed as blizzard changed how retail worked but not classic)

**Comment by cheyndn** [comment]
Thank you!! It works perfectly!!!
