### ISSUE TITLE
ADDON_ACTION_BLOCKED on event = "QUESTLINE_UPDATE"

### ISSUE THREAD

**Issue by takeandrei5** [tukui-org/ElvUI#1351]
### Troubleshooting Steps

Whenever I am in combat, from time to time I am getting this issue without any explanation. I tried opening map and closing it, but nothing seems to make it consistent. But, if I disable the world map module inside the Map tab, I don't get this anymore.
![image](https://github.com/user-attachments/assets/8cac109c-aeba-4398-a1ea-869ac8affa7f)

### Lua Errors

```shell
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'Frame:SetPropagateMouseClicks()'.
Time: Wed Sep  4 20:59:35 2024
Count: 1
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'Frame:SetPropagateMouseClicks()'.
[string "@Interface/AddOns/Blizzard_WorldMap/Blizzard_WorldMap.lua"]:148: in function <...rface/AddOns/Blizzard_WorldMap/Blizzard_WorldMap.lua:147>

Locals: self = WorldMapFrame {
 NavBar = Frame {
 }
 pinNudgingDirty = false
 TitleCanvasSpacerFrame = Frame {
 }
 minimizedHeight = 534
 lockReasons = <table> {
 }
 callbackTables = <table> {
 }
 overlayFrames = <table> {
 }
 pinPools = <table> {
 }
 dataProviderEventsCount = <table> {
 }
 expandedMapInsetsByMapID = <table> {
 }
 mapArtID = 1818
 mouseClickHandlers = <table> {
 }
 areDetailLayersDirty = false
 dataProviders = <table> {
 }
 wasShowingQuestLog = false
 isMaximized = true
 QuestLog = QuestMapFrame {
 }
 SidePanelToggle = Button {
 }
 questLogWidth = 333
 minimizedWidth = 702
 debugAreaTriggers = false
 pinsToNudge = <table> {
 }
 globalPinMouseActionHandlers = <table> {
 }
 pinFrameLevelsManager = <table> {
 }
 cursorHandlers = <table> {
 }
 pinTemplateTypes = <table> {
 }
 detailLayerPool = <table> {
 }
 isUndefinedEventAllowed = true
 BorderFrame = Frame {
 }
 BlackoutFrame = Frame {
 }
 ScrollContainer = ScrollFrame {
 }
 MouseAction = <table> {
 }
 activeAreaTriggers = <table> {
 }
 fadeInfo = <table> {
 }
 debugInspectionSystem = "MapCanvas"
 mapID = 2215
 navBar = Frame {
 }
}
event = "QUESTLINE_UPDATE"
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You said you get this issue from time to time. 

For troubleshooting, did you do 
`/edebug on` 

and then test?  Does it happen in edebug mode? 

Your screenshot is both cropped and doesn’t show the error in the screenshot.

**Comment by takeandrei5** [comment]
Yes, I did `/edebug on` and it still happens. In the screenshot I have only attached the Elvui Addon information. For the actual error text, it's below the screenshot, which is taken from the error window.

**Comment by 1Botanica1** [comment]
I see the error text is below.  It is good to have both. 

The troubleshooting steps asks for a FULL UI screenshot, no cropping that shows both the status panel and the issue/error (in the same screenshot) 

Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

Type in chat in game
/edebug on
Test
Do you still have the issue?
If you still have issues after edebug on, type in chat in game
/estatus and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by takeandrei5** [comment]
Hello! I have just done a bunch of world quest activities yesterday after the latest update of the patch. I noticed that I am no longer getting this issue so I guess it can be marked as fixed for now? I am unsure what fixed though. In case I get back the issue, I shall put in the correct information (Full picture with the error per your request).

Thank you for the help!
