### ISSUE TITLE
Initial gaining of a boss button ability during combat becomes larger than normal until combat has ended.

### ISSUE THREAD

**Issue by Novakowski95** [tukui-org/ElvUI#1355]
### Troubleshooting Steps

![BcvBa6y](https://github.com/user-attachments/assets/79efc498-e43d-4192-8faf-38a97485dd32)

### Describe the expected behavior and what actually happened?

Expected Behavior: Boss button remains the same size whenever it appears if the boss button ability is gained during combat
Actual Behavior: When I gain a boss button ability DURING combat, the size becomes much larger than it normally is. As soon as combat ends, it returns to normal size

### Reproducing the issue.

There are several ways I've been able to recreate this. It usually happens in a dungeon when you gain a boss button ability in combat but I've been able to recreate this bug with several world quests that have it so you can gain a boss ability in combat. The specific world quest I'm using right now is the quest "Special Assignment: Lynx Rescue".

1.) Enter combat with a mob
2.) Click a lynx to gain the boss button ability
3.) The boss button icon becomes larger than it should for the duration of combat
4.) Exit combat for the boss button to return to normal size.

There have been several world quests and times in dungeons since the expansion launch that I've had this issue and tonight specifically I have had it happen several times. It solely requires gaining any boss button ability during combat. 

**PLEASE NOTE**
It appears that the bug only happens on the initial gaining of the boss button during combat. If I go through the above step, leave combat with the boss ability, the next time I enter combat with the same boss button ability, the size bug DOES NOT occur. It only seems to occur on the initial gaining of a boss button ability. 

### Lua Errors

```shell
No LUA errors pop up when reproducing this bug.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Novakowski95** [comment]
I did notice someone else in the issue tracker with a similar issue but as the post was bare bones and without much info so I didn't know if they were having it as a boss or zone button issue.  Apologies if I should have tagged on to their post instead.

**Comment by lowpita** [comment]
Duplicated of https://github.com/tukui-org/ElvUI/issues/1339

**Comment by kodewdle** [comment]
closing, it's a duplicate
