### ISSUE TITLE
ActionBars problem in Live PTR

### ISSUE THREAD

**Issue by alperhankendi** [tukui-org/ElvUI#1356]
### Troubleshooting Steps

ActionBars.lua:1223: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)

### Describe the expected behavior and what actually happened?

ActionBar is not working.

### Reproducing the issue.

Version of code : https://api.tukui.org/v1/download/dev/elvui/ptr

_No response_

### Lua Errors

```shell
Message: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1223: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
Time: Sat Sep  7 21:28:52 2024
Count: 1
Stack: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1223: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...ce/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
There is no support for the ptr.  

Please do not report errors.
