### ISSUE TITLE
Quest log quality is low 

### ISSUE THREAD

**Issue by Shibandk** [tukui-org/ElvUI#1359]
### Troubleshooting Steps

![elvui4](https://github.com/user-attachments/assets/42c54331-dff4-4e4d-b47e-b09ececc0121)
![elvui3](https://github.com/user-attachments/assets/32ea050a-f5f1-41e8-887b-a5b330cec9f6)
![elvui1](https://github.com/user-attachments/assets/c8336106-4d0f-4488-8dd4-8d3c27bf99cb)

### Describe the expected behavior and what actually happened?

When I launched the game today, my quest log's quality (both text and image) is low. I have tried the debugging steps, but still persists as an issue. Screenshots are attached for reference. It could be a blizzard bug, but I couldn't find anything on their bugtracker.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
To test if it is blizzard, disable all addons & test with the blizzard UI 

**Font blurry, scale has changed**
That is from blizzard, not ElvUI
Blizzard settings - set resolution to default (even if it already shows your right resolution) - Click apply  
https://cdn.discordapp.com/attachments/478095559685570570/1277726316875219064/image.png?ex=66d1829c&is=66d0311c&hm=b2b16791fac1b3771b9d126ac41007b63399bf516965ccf55ab0daa234e36a4e&
