### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by RapidDonut** [tukui-org/ElvUI#136]
### What is the issue you are having?

Cannot click on ElvUI in in-game menu or use /elvui in chat option

### What is the expected behavior?

Would normally open ElvUI options menu

### What actually happened?

Nothing happens

### Errors

```shell
Message: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function
Time: Sat Jan  8 13:40:46 2022
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Config.lua"]:1091: in function `ToggleOptionsUI'
[string "@Interface\AddOns\ElvUI\init.lua"]:213: in function <Interface\AddOns\ElvUI\init.lua:212>

Locals:
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
Message: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function

This path no longer exists. You didn't do the troubleshooting steps as step 1 is make sure all addons are updated.

**Comment by RapidDonut** [comment]
> Message: Interface\AddOns\ElvUI\Core\Config.lua:1091: hooksecurefunc(): Open is not a function
> 
> This path no longer exists. You didn't do the troubleshooting steps as step 1 is make sure all addons are updated.

I updated all addons before this. Problem still persists. I disabled all addons except elvui, problem still persists. I deleted Elvui and reinstalled, problem still persists.
