### ISSUE TITLE
ElvUI breaks shift-clicking from SpellBook into WeakAuras

### ISSUE THREAD

**Issue by emptyrivers** [tukui-org/ElvUI#1360]
### Troubleshooting Steps

troubleshooting steps in issue form are counterproductive, given that this is specifically an interaction between addons...

/estatus yields this: 
![estatus printout](https://github.com/user-attachments/assets/b177e799-6739-4911-a0f6-163ec68e6b85)

WeakAuras version is the main branch checkout @ commit [7e1046f](https://github.com/WeakAuras/WeakAuras2/commit/7e1046f6f631675941fc0aea31ce32764bd1dc81) (i.e. latest alpha).

I have no idea how long this has been a problem, sorry - I didn't even realize it was a feature until yesterday 😅

Here's the bisector report I obtained when doing my own troubleshooting:

```
Bisect results:

report version: 2
addon version: **working copy**
mode at print: done
bisect origin: cli
last test result: bad
Bisect took 11 out of (6-114) steps
Hints taken: 1
Addons ruled out: 55
Addons proved: 1

Narrowest set of addons that reproduces the issue:
|-- H:WeakAuras @ @project-version@
|  |-- D:WeakAuras Archive @ @project-version@
|  |-- D:WeakAuras Companion @ 5.2.4
|  |-- d:WeakAuras Model Paths @ @project-version@
|  |-- d:WeakAuras Options @ @project-version@
|  |  |--WeakAuras Model Paths...(see above)
|  |  |-- d:WeakAuras Templates @ @project-version@
|  |--WeakAuras Templates...(see above)
|-- P:ElvUI Libraries @ v13.76-30-gd74a1a8
|  |-- D:ElvUI @ v13.76-30-gd74a1a8
|  |  |-- D:OPie: ElvUI @ 1.2.6
|  |  |-- d:ElvUI Options @ v13.76-30-gd74a1a8
|  |  |-- d:ElvUI Shadow & Light @ 4.81
|-- A:BetterAddonList @ 1.2.3
|-- A:Bisector @ 1.1.2
|-- A:BugGrabber @ v10.2.6
|-- A:BugSack @ v11.0.0
|-- A:DevTool @ 1.1.6

Libraries:
LibFishing-1.0 @ 101109
LibDualSpec-1.0 @ 24
AceAddon-3.0 @ 13
AceSerializer-3.0 @ 5
SpellRange-1.0 @ 24
LibElv-UIButtons-1.0 @ 3
LibAPIAutoComplete-1.0 @ 3
LibQTip-1.0 @ 49
AceConfig-3.0 @ 3
AceComm-3.0 @ 14
AceConfigDialog-3.0 @ 87
LibSerialize @ 1
AceTimer-3.0 @ 17
AceConfigRegistry-3.0-ElvUI @ 24
LibRangeCheck-3.0 @ 26
AceBucket-3.0 @ 4
LibDBIcon-1.0 @ 55
LibBabble-3.0 @ 2
LibElvUIPlugin-1.0 @ 45
AceConfigCmd-3.0-ElvUI @ 14
AceLocale-3.0-ElvUI @ 8
AceDB-3.0 @ 30
CallbackHandler-1.0 @ 8
LibCompress @ 90083
LibActionButton-1.0-ElvUI @ 57
AceConfig-3.0-ElvUI @ 3
AceHook-3.0 @ 9
LibDispel-1.0 @ 10
AceDBOptions-3.0 @ 15
LibGetFrame-1.0 @ 62
LibSharedMedia-3.0 @ 8020003
HereBeDragons-2.0 @ 22
AceGUI-3.0 @ 41
LibUIDropDownMenu-4.0 @ 90135
AceConfigRegistry-3.0 @ 21
AceTab-3.0 @ 9
LibBabble-SubZone-3.0 @ 90238
AceGUI-3.0-DropDown-ItemBase @ 2000
LibDeflate @ 3
LibProcessable @ 62
LibDialog-1.0n @ 9
AceGUISharedMediaWidgets-1.0 @ 9004
LibRangeCheck-3.0-ElvUI @ 21
LibAceConfigHelper @ 11
LibCustomGlow-1.0 @ 20
LibTranslit-1.0 @ 4
AceEvent-3.0 @ 4
AceConfigDialog-3.0-ElvUI @ 90
LibSpecialization @ 10
LibSimpleSticky-1.0 @ 4
AceConfigCmd-3.0 @ 14
AceConsole-3.0 @ 7
AceLocale-3.0 @ 6
LibDataBroker-1.1 @ 4
LibTourist-3.0 @ 903
```

### Describe the expected behavior and what actually happened?

In various places in WeakAuras Options, a user can input a link in lieu of a spell name or spell id. The intended way to use this is as a convenience, i.e. you can shift-click a spell in your spellbook to drop it into a WeakAuras editbox just like you can into the chat editbox, instead of having to manually type in the spell name or id.

Unfortunately it seems that with ElvUI enabled, this feature doesn't work anymore.

### Reproducing the issue.

1. Ensure WeakAuras and ElvUI are enabled
2. Open the spellbook
3. open WeakAurasOptions, and create any non-group aura
4. Focus an editbox that is expecting a spell input (I was using the "spell known" option in the Load tab to reproduce)
5. shift-click any spell in the spellbook, or any node in the talents UI

Expected:

A link to the spell appears in the focused editbox, similar to what happens when you have a chat editbox focused.

Actual:

Nothing happens.

### Lua Errors

```shell
n/a
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
thanks @emptyrivers 💛 should be fixed in dev 🌼
