### ISSUE TITLE
Odd chat behaviour

### ISSUE THREAD

**Issue by yager005** [tukui-org/ElvUI#1361]
### Troubleshooting Steps

![WoWScrnShot_091124_225952](https://github.com/user-attachments/assets/e1132311-5b06-4ef4-8a39-1cd5f541bb1b)

### Describe the expected behavior and what actually happened?

When I switch chat tabs I don't expect a chat prompt to pop up like I pressed "ENTER" but somehow it does. It is pretty annoying.
IDK what does it.

### Reproducing the issue.

Reproducing? I just switch chat tabs.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Please always go through the troubleshooting when you are reporting an issue. 

This behaviour is because you have enabled IM mode in blizzard options for chat style, change to classic if you dont want that.

Going through the ElvUI install sets the chat to classic.  If you use the same profile on different characters, always go through the ElvUI install before copying profiles over.

**Comment by yager005** [comment]
![image](https://github.com/user-attachments/assets/2741ec58-8283-4ccf-b2d7-ee4e128a1eca)
This is all I see at the chat part of the installation and it keeps happening despite chat being reset. I also use S&L and ProjectAzilroka.

**Comment by Repooc** [comment]
you will still have to manually select the chat style like botanica suggested or you can skip to the Setup CVars section and click Setup CVars as that should change the chat style and whisperMode to what ElvUI expects

**Comment by yager005** [comment]
> you will still have to manually select the chat style like botanica suggested or you can skip to the Setup CVars section and click Setup CVars as that should change the chat style and whisperMode to what ElvUI expects

That solved it. I LOVE YOU FAM!
