### ISSUE TITLE
Reversed heal prediction for heal doesn't work

### ISSUE THREAD

**Issue by Pouffay** [tukui-org/ElvUI#1368]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/f55fda85-625f-41df-b6a8-c7804468c2bd)

### Describe the expected behavior and what actually happened?

I want the absorb to show over the health bar. It use to work and I think around a week ago it stopped working out of nowhere.
I tried every heal prediction options and nothing worked.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Fox-Paws** [comment]
I experienced the same issue and downgraded to version 13.76 and the issue did not manifest there, so it's definitely something with the 13.77 version causing this.

**Comment by 1Botanica1** [comment]
This should be fixed in the dev version which you can download and install manually https://api.tukui.org/v1/download/dev/elvui/main
Or wait until next release, no eta

**Comment by Pouffay** [comment]
I'll just downgrade version until next release. Thank you for the response!
