### ISSUE TITLE
Raid Frames Faded in SOD

### ISSUE THREAD

**Issue by HGonda** [tukui-org/ElvUI#1369]
### Troubleshooting Steps

![ElvUI Raid Frames](https://github.com/user-attachments/assets/feb404eb-f881-4419-bd23-f19268abde87)
The other day, my raid frames were suddenly faded out as if everyone is out of range of me. Same with party frames. I have tried updating ElvUI several times but this has not helped. I am not sure what I did? I am hoping it's an easy fix. It's fine if I feel like an idiot afterward!

### Describe the expected behavior and what actually happened?

All party frames and raid frames are dark as if everyone is out of range of me.
![Fader](https://github.com/user-attachments/assets/0db9425b-370e-4afc-be20-20cf90f3271b)

### Reproducing the issue.

It's constant for the last week, so I don't need to reproduce it. 

### Lua Errors

```shell
No errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
From discord https://discord.com/channels/209244641537556480/1278105963349409832

### Classic Era
- you will have to check `Show all spell ranks` in Spellbook.  This is no longer optional as the APIs require it.


Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

Type in chat in game
/edebug on
Test
Do you still have the issue?
If you still have issues after edebug on, type in chat in game
/estatus and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by HGonda** [comment]
Oh my gosh thank you! That did it!
