### ISSUE TITLE
Reverse Absorb for heal prediction is not working anymore

### ISSUE THREAD

**Issue by Syanez133** [tukui-org/ElvUI#1371]
### Troubleshooting Steps

![Photos_IssXi5OTup](https://github.com/user-attachments/assets/30f1185a-00aa-41a4-9663-a2f459030bca)
![Photos_J0GLp2zADM](https://github.com/user-attachments/assets/6ac6ee3f-e29d-486b-bfcb-a09f5154781b)

In the picture above I have I have a shield on but reverse absorb is not showing in the unit frame. I'm not entirely sure when this bug occurred but It was working in Dragonflight.

### Describe the expected behavior and what actually happened?

Actual: When a shield is active no reverse absorb can be seen in the unit frame.
Expected: When a shield is active the reverse absorb should display in the unit frame

### Reproducing the issue.

No replication steps: trying to set up any reverse absorb doesn't seem to work. I did notice that when I set it to normal I see a little bit of the absorb behind the health bar. So perhaps it's just being covered behind the unit health bar.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Syanez133** [comment]
I would assume that this bug happened more recently because this was pretty obvious to me.

**Comment by Fox-Paws** [comment]
This should be fixed in the dev release as commented in this closed ticket:  https://github.com/tukui-org/ElvUI/issues/1368

**Comment by kodewdle** [comment]
yes, it's fixed in dev and will be released tomorrow but here is dev version: [elvui-main.zip](<https://api.tukui.org/v1/download/dev/elvui/main>)
