### ISSUE TITLE
Title here

### ISSUE THREAD

**Issue by Aramlss** [tukui-org/ElvUI#1372]
### Troubleshooting Steps

![B87EE377C886F316D3AE512C9C7E757B](https://github.com/user-attachments/assets/dd66f80f-a34e-4d59-a76c-23c6d55f2439)

### Describe the expected behavior and what actually happened?

ElvUI/Core/General/Animation.lua:330: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@ElvUI/Core/General/Animation.lua"]:330: in function <ElvUI/Core/General/Animation.lua:311>

Locals:
(*temporary) = WTExtraItemsBar1 {
 register = true
 id = 1
 backdrop = Frame {
 }
 buttons = <table> {
 }
 fadeInfo = <table> {
 }
 alphaMin = 1
 alphaMax = 1
 FadeObject = <table> {
 }
}
(*temporary) = Infinite

### Lua Errors

```shell
ElvUI/Core/General/Animation.lua:330: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@ElvUI/Core/General/Animation.lua"]:330: in function <ElvUI/Core/General/Animation.lua:311>
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
You don't show page 1 of current session, you didn't do the troubleshooting steps which is displayed when making a ticket, and I assume didn't read anything we put in regards of tickets as you checked all the boxes.

![image](https://github.com/user-attachments/assets/99a4f551-bfa5-4adc-88b3-e3d1084e3b25)


![image](https://github.com/user-attachments/assets/03c11bf8-e35d-4f4f-b57b-725f8b0f1ba7)
