### ISSUE TITLE
In the battleground, I encounter an error when entering combat.

### ISSUE THREAD

**Issue by dnxxymcj** [tukui-org/ElvUI#1373]
### Troubleshooting Steps

In the battleground, I encounter an error when entering combat.
![WoWScrnShot_092324_234342](https://github.com/user-attachments/assets/d99ee521-17da-4599-aa04-32ac6ca76330)
![WoWScrnShot_092324_234406](https://github.com/user-attachments/assets/38bd0133-ad6d-41f9-adfe-a7b7dab38200)

### Lua Errors

```shell
Message: ...face/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua:725: CreateFrame(): Couldn't find inherited node "ElvUIAuraTemplate65"
Time: Mon Sep 23 23:44:43 2024
Count: 64
Stack: ...face/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua:725: CreateFrame(): Couldn't find inherited node "ElvUIAuraTemplate65"
[string "@Interface/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua"]:725: in function <...face/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua:724>
[string "@Interface/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua"]:762: in function <...face/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua:735>
[string "@Interface/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua"]:1087: in function `SecureAuraHeader_Update'
[string "@Interface/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua"]:693: in function <...face/AddOns/Blizzard_FrameXML/SecureGroupHeaders.lua:689>

Locals: kind = "Button"
name = "ElvUIPlayerDebuffsAuraButton1"
parent = ElvUIPlayerDebuffs {
 enchantButtons = <table> {
 }
 auraType = "debuffs"
 spells = <table> {
 }
 elapsedSpells = 0.025000
 elapsedEnchants = 0.350000
 mover = DebuffsMover {
 }
 enchants = <table> {
 }
 filter = "HARMFUL"
 visibility = Frame {
 }
 name = "ElvUIPlayerDebuffs"
}
template = "ElvUIAuraTemplate65"
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
it sounds like you may have imported a profile that uses a value not supported for the auras or used a plugin that had that as an option. You can try to go into the config and edit the value there and make sure it gets set properly and reload the ui. Make sure to do that in the Debuffs tab as well.
![image](https://github.com/user-attachments/assets/4bf5d3b9-7c25-4434-9abe-2574e0df68ee)

**Comment by dnxxymcj** [comment]
thanks!
