### ISSUE TITLE
Lua Error with Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#1377]
### Troubleshooting Steps

On load I get a Lua error. Using 13.78.

### Describe the expected behavior and what actually happened?

On load.

### Lua Errors

```shell
49x ElvUI/Core/Modules/Skins/Skins.lua:1135: doesn't exist!
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:1135: in function `HandleDropDownBox'
[string "@ElvUI/Classic/Modules/Skins/AddonManager.lua"]:25: in function <ElvUI/Classic/Modules/Skins/AddonManager.lua:13>
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/Skins/Skins.lua"]:2186: in function <ElvUI/Core/Modules/Skins/Skins.lua:2182>
[string "=[C]"]: ?
[string "@ElvUI/Core/General/Core.lua"]:1833: in function `CallLoadFunc'
[string "@ElvUI/Core/General/Core.lua"]:1848: in function `CallLoadedModule'
[string "@ElvUI/Core/General/Core.lua"]:1882: in function `InitializeModules'
[string "@ElvUI/Core/General/Core.lua"]:1980: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:302: in function <ElvUI/Core/init.lua:301>
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventoryClient.lua"]:949: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13483: in function `LoadAddOn'
[string "@ArkInventory/Core/ArkInventory.lua"]:13501: in function `BlizzardAPIHook'
[string "@ArkInventory/Core/ArkInventory.lua"]:3189: in function <ArkInventory/Core/ArkInventory.lua:3145>
[string "=[C]"]: ?
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

Locals:
(*temporary) = nil
(*temporary) = "doesn't exist!"
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
You didn't do any of the troubleshooting steps, you didn't give the information requested and you have other addons enabled.  

Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

Type in chat in game
/edebug on
Test
Do you still have the issue?
If you still have issues after edebug on, type in chat in game
/estatus and upload a FULL UI screenshot showing the issue/error and the status panel.
