### ISSUE TITLE
Title here

### ISSUE THREAD

**Issue by kaynov** [tukui-org/ElvUI#1379]
### Troubleshooting Steps

![scr1](https://github.com/user-attachments/assets/ce4e24f8-4f29-4b11-94ca-13305c11665b)

### Describe the expected behavior and what actually happened?

range issue on mage, fade for party of friendly targets any rang, since elvui-13.76
other classes was fixed

### Reproducing the issue.

just enter the game )
[15:55] Welcome to ElvUI version 13.78, type /ec to access the in-game configuration menu. If you are in need of technical support you can visit us at [https://tukui.org] or join our Discord: [https://discord.tukui.org]  
[15:55] Please use /ehelp for a list of available ElvUI commands. 

### Lua Errors

```shell
dont have
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Do you have 
Show all spell ranks enabled in your spellbook? 

If not, check that option.  Upload a screenshot of the spellbook and the issue.

**Comment by kaynov** [comment]
wow, if i enable all ranks to show, party/raid frames works correctly 
Is that how it's supposed to work now?

**Comment by 1Botanica1** [comment]
Yes.

**Comment by 1Botanica1** [comment]
With the blizzard change, a couple of classes, the range fader isn’t the correct range. This is being looked into.  (Hunter & warrior)
