### ISSUE TITLE
Can't see party mana bars until in-range in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#1380]
### Troubleshooting Steps

See screenshot.

### Describe the expected behavior and what actually happened?

<img width="235" alt="image" src="https://github.com/user-attachments/assets/39cc0a06-7cec-420d-8d47-200be53b0493">

### Reproducing the issue.

See screenshot.

### Lua Errors

```shell
See screenshot.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Luckyone961** [comment]
Probably the most useless ticket I've seen in a while.
"See screenshot" copy pasted 3 times and a picture of 5 party frames with 0 information.
