### ISSUE TITLE
Missing action bars

### ISSUE THREAD

**Issue by rchupp** [tukui-org/ElvUI#1382]
### Troubleshooting Steps

All the action bars are missing.

### Describe the expected behavior and what actually happened?

![Screenshot_1](https://github.com/user-attachments/assets/2bc0005b-5cb3-4a05-9ae8-febdcbe7379a)

### Reproducing the issue.

Log in to the game.

### Lua Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/DataBars/Reputation.lua:59: attempt to call upvalue 'C_Reputation_IsFactionParagon' (a nil value)
Time: Sat Sep 28 05:46:50 2024
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/DataBars/Reputation.lua:59: attempt to call upvalue 'C_Reputation_IsFactionParagon' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 13
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = true
 UFParent = ElvUFParent {
 }
 wowtoc = 11504
 InfoColor2 = ""
 myname = "Blondbeard"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 5
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 216
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 1920
 versionString = "13.70"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Alliance"
 myrace = "Dwarf"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Dwarf"
 myclass = "PRIEST"
 wowdate = "Sep 27 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Skull Rock"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.700000
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 toc = 11503
 ClassicHC = true
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard = <table> {
 }
 MountDragons = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1080
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1.015873
 myLocalizedClass = "Priest"
 PixelMode = true
 serverID = 5099
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-5099-027F6B54"
 loadedtime = 859.800000
 texts = <table> {
 }
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 resolution = "1920x1080"
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ModuleCopy = <table> {
 }
 InversePoints = <table> {
 }
 SpecByClass = <table> {
 }
 ScanTooltip = ElvUI_ScanTooltip {
 }
 UserList = <table> {
 }
 TutorialList = <table> {
 }
 QualityColors = <table> {
 }
 locale = "enUS"
 CreditsList = <table> {
 }
 PluginInstaller = <table> {
 }
 myRaceID = 3
 Minimap = <table
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by rchupp** [comment]
Message: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1185: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
Time: Sat Sep 28 05:46:50 2024
Count: 1
Stack: .../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1185: attempt to index field 'InterfaceOptionsActionBarsPanelStackRightBars' (a nil value)
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: self = <table> {
 initializequeue = <table> {
 }
 statuses = <table> {
 }
 embeds = <table> {
 }
 frame = AceAddon30Frame {
 }
 addons = <table> {
 }
 enablequeue = <table> {
 }
}
addon = <table> {
 mylevel = 13
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.1f"
 oUF = <table> {
 }
 Classic = true
 UFParent = ElvUFParent {
 }
 wowtoc = 11504
 InfoColor2 = ""
 myname = "Blondbeard"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 5
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 216
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 1920
 versionString = "13.70"
 LSM = <table> {
 }
 InfoColor = ""
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "Alliance"
 myrace = "Dwarf"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "Dwarf"
 myclass = "PRIEST"
 wowdate = "Sep 27 2024"
 PopupDialogs = <table> {
 }
 Chat = <table> {
 }
 myrealm = "Skull Rock"
 LayoutMoverPositions = <table> {
 }
 global = <table> {
 }
 orderedModules = <table> {
 }
 Misc = <table> {
 }
 UnitFrames = <table> {
 }
 uiscale = 0.700000
 TBC = false
 AnimElastic = <table> {
 }
 media = <table> {
 }
 data = <table> {
 }
 Options = <table> {
 }
 toc = 11503
 ClassicHC = true
 HiddenFrame = Frame {
 }
 Media = <table> {
 }
 name = "ElvUI"
 TimeFormats = <table> {
 }
 ShortPrefixStyles = <table> {
 }
 versionDev = false
 Blizzard = <table> {
 }
 MountDragons = <table> {
 }
 TotemTracker = <table> {
 }
 RegisteredCooldowns = <table> {
 }
 SpecInfoBySpecID = <table> {
 }
 ObjectEventTable = <table> {
 }
 defaultModuleState = true
 EditorMode = <table> {
 }
 MapInfo = <table> {
 }
 frames = <table> {
 }
 physicalHeight = 1080
 NewSignNoWhatsNew = ""
 ClassicSOD = false
 Retail = false
 MountIDs = <table> {
 }
 AnimShake = <table> {
 }
 DisabledMovers = <table> {
 }
 mult = 1.015873
 myLocalizedClass = "Priest"
 PixelMode = true
 serverID = 5099
 PrivateAuras = <table> {
 }
 GetFormattedTextStyles = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 ConfigTooltip = ElvUI_ConfigTooltip {
 }
 SpecInfoBySpecClass = <table> {
 }
 statusBars = <table> {
 }
 charSettings = <table> {
 }
 myguid = "Player-5099-027F6B54"
 loadedtime = 859.800000
 texts = <table> {
 }
 Spacing = 0
 Border = 1
 EasyMenu = ElvUI_EasyMenu {
 }
 resolution = "1920x1080"
 SpellBookTooltip = ElvUI_SpellBookTooltip {
 }
 baseName = "ElvUI"
 Filters = <table> {
 }
 TagInfo = <table> {
 }
 InverseAnchors = <table> {
 }
 ModuleCopy = <table> {
 }
 InversePoints = <table> {
 }
 SpecByClass = <table> {
 }
 ScanTooltip = ElvUI_ScanTooltip {
 }
 UserList = <table> {
 }
 TutorialList = <table> {
 }
 QualityColors = <table> {
 }
 locale = "enUS"
 CreditsList = <table> {
 }
 PluginInstaller = <table> {

**Comment by 1Botanica1** [comment]
Update ElvUI 

ElvUI is on 13.78, you are on 13.70 

**It is recommended to download/update via a client**. 
Either the
[Tukui client](<https://tukui.org/client>) - downloads/updates ElvUI (and backups your WTF folder)  

Or 
[WowUp client](<https://wowup.io/>) - downloads/updates ElvUI and all your other addons.
Or
[Wago client](<https://addons.wago.io/app>) - downloads/updates ElvUI and your wago hosted addons.

**Comment by rchupp** [comment]
Ok
