### ISSUE TITLE
No Action Bars / Version Mismatch?

### ISSUE THREAD

**Issue by Kavrrin** [tukui-org/ElvUI#1383]
### Troubleshooting Steps

Typing /edebug on throws a lua error and turns off the addon until the game is reloaded.
![image](https://github.com/user-attachments/assets/6ed08685-26c1-4941-8ae5-e5c6db7ac2fb)

### Describe the expected behavior and what actually happened?

Loaded the game to find my action bars gone. Checked the game movers to check if they actually weren't there (settings make them invisible if there's no abilities slotted) but even the movers don't show them.
![image](https://github.com/user-attachments/assets/07733813-ec26-45b9-b802-9b15fc85f538)
![image](https://github.com/user-attachments/assets/c9a12c45-cd0d-40bc-8bcc-9dd8a9137680)

Proceeded to scour the Issue Tracker and found a lot of other people being told to update. So I updated the addon manually (twice just to make sure) and while the zip file says 13.78, the /estatus menu shows a different version.
![image](https://github.com/user-attachments/assets/88b9597f-549f-4e6c-aa72-7346fb00c882)

For those suspicious that this is some kind of prank or Noob mistake, here's the exact file as well as the download date. I've redownloaded it a couple of times just to make sure I'm not imagining things. 
![image](https://github.com/user-attachments/assets/111256bd-03f6-4f87-b033-261f0b706450)

### Reproducing the issue.

Simply updating with the currently hosted 13.78 zip file with no other addons installed. (This includes deleting any residual Elvui folders from a previous install version from the Addons folder)
Type /edebug on and receive a lua error.
Restart game to reactivate any elvui menus/ui replacements as the lua error forces them off.

### Lua Errors

```shell
Message: Interface/AddOns/Blizzard_SharedXMLBase/Mixin.lua:9: bad argument #1 to 'pairs' (table expected, got nil)
Time: Tue Oct  1 15:33:01 2024
Count: 1
Stack: Interface/AddOns/Blizzard_SharedXMLBase/Mixin.lua:9: bad argument #1 to 'pairs' (table expected, got nil)
[string "@Interface/AddOns/Blizzard_SharedXMLBase/Mixin.lua"]:9: in function <Interface/AddOns/Blizzard_SharedXMLBase/Mixin.lua:6>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibCustomGlow-1.0/LibCustomGlow-1.0.lua"]:38: in main chunk

Locals: object = <table> {
}
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
mixin = nil
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Kavrrin** [comment]
Got a new lua error from another game reload. Similar to the other "action bars gone" issues here.
https://pastebin.com/ZSetR6NU

**Comment by Azilroka** [comment]
Update ElvUI. You are out of date. 13.78 is the current version.

**Comment by 1Botanica1** [comment]
You are updating incorrectly, either to the wrong game install (quite a few have multiple wow installs) the wrong game flavour, or wrong folder, or even not delete the old folders first & copying over. 

**It is recommended to download/update via a client**. 
Either the
[Tukui client](<https://tukui.org/client>) - downloads/updates ElvUI (and backups your WTF folder)  

Or 
[WowUp client](<https://wowup.io/>) - downloads/updates ElvUI and all your other addons.
Or
[Wago client](<https://addons.wago.io/app>) - downloads/updates ElvUI and your wago hosted addons.
