### ISSUE TITLE
/whisper putting the message in say chat. 

### ISSUE THREAD

**Issue by iAmCallumJ** [tukui-org/ElvUI#1385]
### Troubleshooting Steps

/w or /whisper doesnt work and just puts the message in say chat. 
https://www.youtube.com/watch?v=wdcit5t6yAs
![WoWScrnShot_100524_131052](https://github.com/user-attachments/assets/8d4e64ce-d184-43fc-a4f2-03cdba72ffa7)

### Describe the expected behavior and what actually happened?

Whenever i use /w or /whisper with Elvui addon enabled, it will put my message to the person in say chat instead of whispering it to them. And if I disable Elvui /w will work and message the person. 

### Reproducing the issue.

If you want my elvui profile to test on your end. 

!E1!fV16xQnow()A6pTqF87hz)eqrLQotXJfC6SzMtiLmia3XyZylQKQ)q93(EVsY2Ygd4k7mN5050awYs3N)UpKQv6RcwTCdHrcjz543z7ZOeg(nAcjmMUkCfd((ppsZIOjRP4i7J2qhWMq(5t0xOXWmw(JOnS9RMAOPHZEFAsAgoX6poJE8eJWIstuw(HnNf5VGDIrBqbWa7Oj0msmNitz0dCYDxw6py7VlkJUMVWlFy2Ih)7ZMgm4PvlZpswhLSB1up47r)fD1uB(w8pprprxcKYj(ASnnbE4dPhO5hpLi(9s(01n4u02VJ84HOKOdKJ4BKVMeJd)7A2fRms9lJwNMWxYnrB3gT(um7v8xhtZJeu3WzbbZMS4Xp(qaUY4YKSHKvBnHL8NZ2UnNYwnTVoNGpqIe8n9NStz0vlNapqhhHLrw)DKhduEltdUedgomLXspmNKiutHWK3KLEClzdDDASqjrwDVTLMLPUVRJRTVHVJ2QT9Tnbf2Q7D91nm0CGX1DSCmDXrCbX(Q79SCDnHb0SSCm011LJecVJPLRMLNNMPNJRUJCeGAEHeFQAFHv3Zr3ZX203XY2XX2WtUVWQB5BzRB4Byz5clUTHCey1DSD89TDnS8Cn818KVdS65SO1F)17ZiGEez20W)enkEHYF0GtS0ha72ht(B0xZzPjCtV2Nd(2KnBstgLE4ijJDGMW9ieAADhC3egndYIiXV98usgyhII7Kt5ZkwZ5LQ9bFkygORiXOQ6bkzdF7wk04AOgVoH8anA3EqrAHgvKy280FqZgsAXNk)qAkBpSQdoKEcOiy1CT5MmPVqfE0JJF5t3)T7txFkFejNbo6tWXkmg79PhNtYaoSN83A9mHLq91ciz7OSAVf3eU5RkEyFtxVEwooflXcs0gt5lhmB(tJVx5flEGwpGtf7tbZwB)4tcxV67i)X2U29SS0HPMMNp8eyXNCrMZW3SNjyoT8jqUXL1vuwT1h)THLDV(wMwRw(3b7LbHrXrGdDXsFo10Z0YrS6ltxdggtOjN6SuZrJldeYmHKyWPms3Lc2A9SnafxH8BeyHsIamZ6Q7wiBTEgL78CkRnRKRTZGbdId(h09rRJPlHWhTW0N)Us(2W0QNVNy7FCij57nmvAOu4pZcmYS8qLyEoYMzPXx3Mw3ZVNjGVSminB3EG)gTpnAnniD3oWfKR8RP51613dejtIa)6SGOd0m9RyNOdthravm417ObFDeHoW683BGigzLtcm65I5YhcKNHHPk5z0zLRj4faYTfLXUBztBFhrpYbnqrV9B23qhC6aZPz1qe7eF2x3WewaFRAAoJRO56BIoEG)6(OTSbd7IarxZtVNPUnc(djOG6oAwNuC9T8l9YIjV2nhtmMkmYGHFZTlOiUM90Dr9fgaz0(3PRONce0G88OCwhymluNPxqLOGPdKPrpltF0D84iyq6zGvTPSajOj60WZqTR2(9rZjld76s(wde2QcWuhK7pr3EUW86qIaH(Xjxl2ccAGQuYU83LoY1fcXaV4Dr7wcyaZZs3LrH4EDNBgReI59I1BBGPhywl9G3d5B6y0Z0d08dIBpq)fOBlmWww0legfXV(mjlbaoVfiRba73VY00StMMo9SCTQlLAjbOBkKmHeGgft6QMbs7grTwNL2uDCDjQIh783bjcBOhA9nDCqhWKT0n4gRc5OxNeJ6Gjo(kLvo25ah2vAmRoTvU9SRI((E1vyYJ2AL7OwN2rG588QdPOKSwR(7qsXqaaBembkA(th5jRssUoKhIDbu0)tvbR3we23qZGNwvbp53vwYU8v0VUXQULtXmn6Mzk44dbMq1jno9hteLsFHmuBUF6wMOr(Fm7XrJh9WGGlekhccbo7aZk0hVd0fd0xD4jO65BozigPUy(G3w3sya9TlTO7ceKMqsjEb7BOj08kZ8(jk5f6nQ)rxhcFGrdvsqsP4SEQ5nvTlALPNVRfOP2v4E290DQqTr3J8RRNbniK9cpjDg9qa2zJBzAycf94jOUPZRNvvGAo9Jgpny8ceDrVYx366IwxnSPqjPzDg4Y0OyPDUHwZZb5Y0yw0XolqRLDwq3kuIhaenHaWMMzQEz8dtWrYrQg6IheK3TDpdG5VduYIQKvtAVl4dqaZYggadZE9gMkqv28cHIPz3Sm((iUaywDhnSt(4q1ScxCjm1TfzOIbBNxAcmt2CYoAo2DPqi3oSdmWNFw01gleI9ppL897O5aAEg4yGtm)iiZKZCzrtl15)0sUq6YpnKFAk)0g(KjErE3PWWfHGXrXgIij4VLJckjiPXd8yqJoLZspmc7h34YMXMVoJC8rGtKRVSRtLTs1(69CL31X17LDq(qkoHh5DfnC1sgaRarXoC8(0SdWuw(Bp8HFBYBpJDugiLSxxkBsRg2SSW7R6dl8GJytmdiHaUqcqnGcy9RinYFErdZ4DHL)eo)Vq8utJINou2auGMF8UXG((bS5Q)8jiiuoUXGvYMsnZFGTiOK4ZPWMcpfPO8gB8IIDheVVGVfVJRdIpUNSAk2x4ecwkl4xWrwxn1hjOOe(oiqS57b2xwGfZNMwsOHfn2K3c60t5u0A8pk3KskrQWTf9f8useBl6xu0G7YgAZhs0QFWSOwB257pxDdYKcQ)39kALCUO12cVi5SqpEUrWutu0JDiDgqFzyxu5QTxRALTOVPTVfy31RTJlpIXVVA3ZtKSx1ekCiXrL9jv31fL)Btfsl80lK2k6UIwWZlasPZQ4BWuMg6q9lXXcgEpLedlBlmcIqlKTBXYOAiCvp(LZ50ARqzpHXyBxuhQYQ5hPXXlO81nSIxXYRvwloTX45t3G4wJnBUY)0t5jQNKc)HFPqEOPmRzNyXGthGXoB6SrpSy2KXbp84O)2Spf80JthRifX2PwtSxSm)VfZWq1PfzhOIdSD8cyJSO0mrBBJbFQyaOP3CAwEAcjUxsAsX3BQjXWzBK75CvdmuMKIv0ipkRLCLWscg6tiCjmgz9(GuiIZ4GbJEy8DGwbFJnXVIPbf86rGXFyWIj3)PNqAhNoDJ0b2abRkn(8u5GkATPab(9q8a8KNyvR2ayt9pYZqsQsbKdalDhvE4wQtu1)tYo0FYqwINwTC05z0nrIyayKdgqqKbjBeNkiI7GaqIFnLtxnzvbw1AECiCd42wIWspWDB(TZjaXakN2LM4CX(2wzqL)HWJJFotFv(JpaMeRbv2xvDpp)K)(tyRJ2(keuqKWOyg30wTcavEwG2cxhCVvKriReMNMfUK9k215PZwmHhYC5MOCCfMuaV)rOgj1tgftyxX7vkWGqjChUa1dtTcRhTJAWGmekmNFkyfaIHQY)2xUZoBub5FjPHs0goaOurHRpx0uACBxH2yAk1IJkoDq8Ce1D1SmDD100nSCCnQoDqxBBpFpihqCkAwEkNxzRVdtfeTU5ep5XgXqQdBxF(vsowDo5syJ6AxaCu5qEvdtInxRmBlnfWmhvOG3fCf3vOCUlVF2IrJ)2SPLrEQG4Vwcahplkajz9(uOq7iKXkJ9wz9CbKOItTuGCvb8OgjZv7srTTuCye96H7TewZdbpiEH4xEw4sKVReJ9scPoyj0W6PsZ61aAsvp79Vlq29L5cRAJzvG(EFw6bHr)WwbKRirXLF46X1kd8G7wBrYQWgRmEbXbcZcw4V9Cyg9h9YPq68Wq9yPNwV)TNt3(2ZFNaYSE4fPaafF75dKDrR7TbkEGM82Z7HbRhLSrergEKv5mEHmnu0LMKvOCQw7(TKl6VweQQ1))WXNudv(VPiuOHJQ)35rzknlnp76cvEBhG1a7yUCrUT9QUVFD79TrXXc4t6gCPZirBIo3gqoc)YpLPGhifo6QMTv3QMA(g8CKsoD4JzPNoMZD1pRUyoE43(0C8QpLFkdFEHbzLVuJIAYsJPftsvVv9ck4o5k3sPwYjvkMTTBGLQcqxev8N186VCrekklwrXbTwIW1doe2bJkDmzbX9rtAp(XNM952iU7Dm1S1m9TC9m19C8TLjeu6iFHj0WcPsglKFkYefdIxR0kLwsMIqu3OsVk4EvnqHwY6cv0w8YLfPzD940yRrinugNvL6L1X1q)QxjGQN2fcy9)Vs11QdgCvY)Ys7I1fjDSvInKf1ZwxjfkTlsP1m8bJsSlFrRjXlvYtdm2J(l8anQEAFJ6WlvrJD5zXCgGXDZ(80VjS9afqoaGc2MeMiJ4Y3gpePCL7owvedt5QE64qim70btgxhqjVSWGk27mBZw1STGhQvZGOMgrDovuNX7lqyt1QILIbMu9LSFxNEiKC5QBTli16X9u9ilvyQns4mJLQS0lVULI8A5xL2HYmkfyHqMjqAs4rmH)8F138rHj2dGUiMRpcWBhqofmG4BoI(z5ydGF(A6wov1lHvszOz76G1qPz6655JJyXPW2VtOmSpkui46TwyBxFdGdHbDm9mfxCuBoByBHSnYB2Ao6UoITKHPvLDlkgOllxhpBDxBnBCbCvKpE2axO5B445AbF6usXtWChVnfF5lbBDHKKxyOZruUm0X7FLfTkhTreM(HVYVFSICL4ogyUqOHeeE8okztzpHhkY1IF7cefmpuX)D80Xl(4xkSZ4YepOOylFF8Mrvqu8JxO5971ItAossd3IQlRl(ccKUqzc24eMM(iE9DYoDKjNM2VBiSSS8a9UNbg1vxAHB329d2SqCY6y6S58dchtsuEcnyt94(bqPrSIK05nfN)TIBVZDWWf5aHCZDZxYdTdHubu(iSnaHvTDx6st4ieYmsHp4r6dLTSNJPj(HSAtRYbNtZwWXoGWfr5rfxE0)bugnapXIPFfkJbWs(VF75894Lhg))Feqxe5gbBLtfU0g(PXi2i1ZhszRXaM)kBus6ceMurtFVlyqaQinWAx3ZYWsQ62DXrcpBKQeSwNMgVj9hCVeu9wEL7LThXQfnFPQojL9jEoI1ippWGYXWuxZY1211wIzH3jDDmdpBxpWjZ13ucTWXg0nS0T018bhyDa7Oe05G8k30qwtucO0qUBwxUBWxgWMuCfxuxhP8LhcvLbCm8Cb6WuZ0eiiF3kg4cJGG)M2EAgMG8fHz8mkzaG2nA3q5F9wK6vg)kN2ytZsXCTvM7fmzn9A1vQIqn(1OuaciJmG74kVoebkAuSxQXusIiw)FH3S7UnvGPMtz1vWNrYAYzAXXGev)OueGkcZfKfQslf(6xw4u28ZJXa6yJ)iFGqlI7tPW(Kl(2xMiriVVzIZ8K72kpfJYZAS6rpuDCzmLZyecgn5lFB68r4pAnj8ZpEJEHXPR)(0MNnJOjN1Q(Q2rAb8kpp3WANDhAoacOYuGB0QUQE0OCqL6kzWI30PYDhvTx785Q1sxfmot1L3NlJlZvUGwL9kSo6OSKU)5jLEzvw0FDuu(Bx16xz52QDswP8d5MvEeAYx)lT2sArVoIlA4yvdrQrbAneHCcpyWIpooaFRDqT9YQ4ZXpSWcvHKRvkHcM)9lEC807E6lFB(td(Y4fDWOP6u9KwnfDbS6u(Wl)sVrJKx)JE49hv(9gMqQQuSQEr7LRveM6uyrGZwnjcVSKAIerh8UpkJ82Zljj5V98O0Kn0KC6M3EEcuaYPd1A5htyihWx6WklRYAMWhiRyc)6hiHHz0x(qCAYUV20M79T591VGbERsBOad8mKXP0tCVR4xGUEbNYasN)9woU8wT8TRS8R2ZM)r4bavk57gwxtuAB2szQ9nvlrg)f8chF5yulQ1HcP)qYgrDJnQsUW1ZtUe8e0J2IldmP2xqUBGafSYM(c2CNlAkQzUMjGSs51yhfty9bH8xptE1Q5z)AaO9nn7oGMvDlBNUzCDvjDfzH)fyutUNRKz17qoJwcP)q0(DmQgSMXBeD9U1sguQqVwXoIyVzNLpPBr1rlZPX0IwhaRFGi5TwsrZ(IjVjR4PrruQPjABy46QbVi8phpp9Q0eTDGIFDDm0m8Hc8CnQst0wZZXs3ZX0XekcwVS4ACNIJw)DqSKEAh3gRiYD1b19ip452OyM8pDqHtoxchG)TMgTBNCK623v)TeC95nLEcYmlUYoVLPk7pF(M8RVw8lU33GSeck7(8fxnH)G4(wIdIgBt4)9swwSTm19luaArbjf2m3QRYydF4KHs0RwAqOxlTs0T083HdG(5mcE(cMx78fuDJBFBuobAvx2IGa50Ju82ZmdQtJh8)S9cba5hLrEAgdE(QL)xIl0xTBbuBCtXKoV6oL8QW)B1h(WXSuW8J(HpetpqEf(3)3

I don't know any other steps to reproduce other than using /w with my profile to see if its my profile or a bug with something else. 

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
At the top of the ElvUI menu - click on the Install button and go through the cvars part of the install only.  Don't do any other part of the install, just the cvars

Test - do you still have the issue?

**Comment by kodewdle** [comment]
reopen if you still have the issue after going through the cvars part of the install
