### ISSUE TITLE
'ElvUI_Libraries' tried to call the protected function 'CheckInteractDistance()' in Classic Era

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#1386]
### Troubleshooting Steps

'ElvUI_Libraries' tried to call the protected function 'CheckInteractDistance()' in Classic Era

### Describe the expected behavior and what actually happened?

No lua error.

### Reproducing the issue.

Happens all the time. Make a group with someone far away, or click on a mob that's off in the distance.

### Lua Errors

```shell
18x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_Libraries' tried to call the protected function 'CheckInteractDistance()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:634: in function `interactCheck'
[string "@ElvUI_Libraries/Core/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:663: in function `checker'
[string "@ElvUI_Libraries/Core/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:837: in function <...braries/Core/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:832>
[string "=(tail call)"]: ?
[string "@ElvUI_Libraries/Core/LibRangeCheck-3.0-26/LibRangeCheck-3.0.lua"]:912: in function <...braries/Core/LibRangeCheck-3.0/LibRangeCheck-3.0.lua:893>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/UnitFrames/Elements/Range.lua"]:14: in function <...Ons/ElvUI/Core/Modules/UnitFrames/Elements/Range.lua:13>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/UnitFrames/Elements/Range.lua"]:47: in function `UpdateRange'
[string "@ElvUI_Libraries/Core/oUF_Plugins/oUF_Fader.lua"]:99: in function <...ddOns/ElvUI_Libraries/Core/oUF_Plugins/oUF_Fader.lua:70>
[string "=(tail call)"]: ?
[string "@ElvUI_Libraries/Core/oUF_Plugins/oUF_Fader.lua"]:150: in function <...ddOns/ElvUI_Libraries/Core/oUF_Plugins/oUF_Fader.lua:144>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Gogo1951** [comment]
Likely related to this. https://github.com/tukui-org/ElvUI/issues/1380

But also you still can't see a player's resource bar until you're right up next to them and they cast a spell to refresh it.

**Comment by kodewdle** [comment]
already fixed in dev
