### ISSUE TITLE
quest log

### ISSUE THREAD

**Issue by tjtje** [tukui-org/ElvUI#1391]
### Troubleshooting Steps

0

### Describe the expected behavior and what actually happened?

when i go do a raid ore instance i have to reload because the quest log is gone

### Reproducing the issue.

do a instance when done questlog is gone un till you reload

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

1. Type in chat in game
`/edebug on`
2. Test
Do you still have the issue?
3. If you still have issues after edebug on, type in chat in game `/estatus`and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by kodewdle** [comment]
you can try dev: [elvui-main.zip](<https://api.tukui.org/v1/download/dev/elvui/main>)
