### ISSUE TITLE
terrible FPS using ELvui,  it's the libraries folder spiking!

### ISSUE THREAD

**Issue by Carolinaelf** [tukui-org/ElvUI#1393]
### Troubleshooting Steps

during 25-30 man raids, the library folder ping up and down, causing terrible FPS drops. It only occurs with I have ELVUI installed and using 
![WoWScrnShot_101024_214354](https://github.com/user-attachments/assets/10623584-2a76-4d76-9b49-549b35aca19e)

### Describe the expected behavior and what actually happened?

![WoWScrnShot_101024_195957](https://github.com/user-attachments/assets/c273f26b-9930-4614-8b89-f0e1e4c3b710)

FPS in raid sizes 25-30 goes from 80/90 down to 35 or 40 terrible spikes.

### Lua Errors

```shell
no lua errors
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Carolinaelf** [comment]
![WoWScrnShot_101024_200009](https://github.com/user-attachments/assets/8fe43ef7-5330-49e9-b766-1247bd3c466a)

**Comment by 1Botanica1** [comment]
The purpose of the troubleshooting steps is to test when you are having issues.  

Not post a screenshot with all addons disabled except ElvUI then test with all the addons enabled.  That doesn’t show anything. 

Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

1. Type in chat in game
`/edebug on`
2. Test
Do you still have the issue?
3. If you still have issues after edebug on, type in chat in game `/estatus`and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by 1Botanica1** [comment]
## Low FPS in raids - ElvUI_Libraries high

The Libraries are used by many, many, many addons, and whichever addon loads the library first, (usually ElvUI) all the addons use that library.  This is why you can see ElvUI_Libraries high on the list. The libraries are being ustilised by other addons.  

### For testing for Low FPS

* creating a fresh profile of ElvUI  - ElvUI - Profiles - New (and leave as is for testing)
* Type in chat in game  `/edebug on`  (disables all addons except ElvUI for testing)
* Disable Portraits on ElvUI - Player/Target Unitframe (if enabled)
* Disable Party, Raid1, Raid2, Raid3 - Debuffs.  You can enable Raid Debuff Indicator for those frames to show debuffs.  Set the filter ElvUI - Unitframe - General "Raid Debuff Indicator"
* Disable Smooth bars - ElvUI - search (top right) - smooth
* Try a LFR & test.  

* If you still have issues, type `/estatus` and a full UI screenshot showing the status panel & issue (ie - in the raid).   Please don't crop the image.  

Read more here thanks to Luckyone <https://x.com/Luckyone961/status/1843256715917050331>

**Full guide for optimising ElvUI here** <https://github.com/tukui-org/ElvUI/wiki/performance-optimization-retail#step-4-optimize-your-elvui> & the game in general
