### ISSUE TITLE
Chat Edit Box not always loading

### ISSUE THREAD

**Issue by coding-bunny** [tukui-org/ElvUI#1396]
### Troubleshooting Steps

The Chat Edit Box is not always loading.
I can chat and type text, but the box is...invisible?

![image](https://github.com/user-attachments/assets/72c59590-6695-41bf-b4e1-e184b666ab53)
This is when it's working normally.
However when it's not working, you will still see the `Guild: ` and whatever text you type, but it will just be pure green text over the display panel:

![Screenshot 2024-10-15 190812](https://github.com/user-attachments/assets/99c1e30f-14aa-45ec-90b4-2eeff11b66e7)

## Status
![WoWScrnShot_101524_190913](https://github.com/user-attachments/assets/a45120a1-db35-41ee-9e1c-2ca9fbe29fca)

### Describe the expected behavior and what actually happened?

I expect the box to always load so it's clear and readable what I am typing.

### Reproducing the issue.

Usually happens on initial load.
/reloadui often fixes the problem

### Lua Errors

```shell
None
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
In the ElvUI menu - click on Install up the top. 

Go through the cvars and chat (will reset chat back to default ElvUI) part of the install only.  Don’t do the other parts of the install. 

After doing that, test again.

**Comment by coding-bunny** [comment]
Will do on next possibility and report back!

**Comment by kodewdle** [comment]
reopen if you still have the issue after going through the cvars part of the install

**Comment by coding-bunny** [comment]
Will do, so far it seems to hold fine.

**Comment by 1Botanica1** [comment]
This can happen if you don't go through the ElvUI install on each toon before importing a profile.   Need to always go through the ElvUI profile on each toon, then import profile.  

Or if you/ or another addon, sets the blizzard chat style
