### ISSUE TITLE
Object Frame doesn't "un-hide" after raid/dungeon boss fights are over

### ISSUE THREAD

**Issue by theothershiloh** [tukui-org/ElvUI#1399]
### Troubleshooting Steps

**ElvUi Settings for Auto hide (General>Blizzard UI Improvements>Object Frame)** 
![WoWScrnShot_101624_183751](https://github.com/user-attachments/assets/e634c966-d44e-49b4-8761-8adebd0615b8)

**ElvUi Status**
![WoWScrnShot_101624_183457](https://github.com/user-attachments/assets/9227c0f5-d16d-4145-96ca-7196a6da3dd5)

### Describe the expected behavior and what actually happened?

The Object Frame hides when a raid or dungeon boss is engaged, but it does not un-hide when the encounter is finished.  You have to /reload ui for it to appear again.

### Reproducing the issue.

1. Ensure Auto hide (General>Blizzard UI Improvements>Object Frame) is checked and fight a boss in a raid or dungeon.
2. The Object Frame hides when the boss is engaged
3. When the encounter ends, the Object Frame does not appear

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
might already be fixed in dev

**Comment by 1Botanica1** [comment]
Duplicate of #1391

**Comment by theothershiloh** [comment]
Whoops.  When I searched, I was looking for "Object Frame" and not "quest Log".  Sorry about that!  Closing this issue.
