### ISSUE TITLE
[Feature Request] Change the default Custom Glow back to Action Button Glow

### ISSUE THREAD

**Issue by Daenarys** [tukui-org/ElvUI#140]
I decided to download the latest Dev build to do some testing and I immediately noticed that the new "Pixel Glow" is now set as the default action bar glow. It's such a downgrade coming from the "old" default Action Button Glow. Its barely noticeable to see if you have a free proc now.. I think it would be much better and user friendly to set the default Glow back to Action Button Glow. I know I can change it myself in the Settings, but since its quite a big downgrade, I request that you change the default.
Thanks.

**Comment by Azilroka** [comment]
I turned the custom color off.. We have no plan on making the *old* default the new one as we changed libs to get pixel one for the UI.
