### ISSUE TITLE
The queue status is not appearing correctly.

### ISSUE THREAD

**Issue by CrisReus** [tukui-org/ElvUI#1404]
### Troubleshooting Steps

![Uploading QQ图片20241026214351.png…]()
![Uploading QQ图片20241026214342.png…]()

### Describe the expected behavior and what actually happened?

This issue has persisted across multiple versions. 
When I enter the queue, I often fail to notice the eyeball moving. 
I can count the frequency of the eyeball's appearance with just one hand. 
I only use of the wind toolbox.
Will LFG Call to Arms cause compatibility issues?

### Reproducing the issue.

enter the queue

### Lua Errors

```shell
no
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by CrisReus** [comment]
ps: I disable the  LFG Call to Arms, and fail to notice the eyeball moving.

**Comment by 1Botanica1** [comment]
Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

1. Type in chat in game
`/edebug on`
2. Test
Do you still have the issue?
3. If you still have issues after edebug on, type in chat in game `/estatus`and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by CrisReus** [comment]
![test](https://github.com/user-attachments/assets/56e6b458-3e4c-48d3-a0d2-6efa13712fc5)
![test again](https://github.com/user-attachments/assets/46c8ec44-52ef-45a4-9ff7-2731feae1d2b)
When I initiated the test, I immediately noticed the green eyeball moving.

**Comment by 1Botanica1** [comment]
If it works after doing `/edebug on` then the issue is not ElvUI as it disables all other addons. 

ElvUI is only 
ElvUI 
ElvUI_Options
ElvUI_Libraries 

All other addons, even starting with ElvUI, are from different authors and you will need to report any errors to the addon causing the issue.

**Comment by CrisReus** [comment]
thx for your help
