### ISSUE TITLE
Equipment Set Data Text - Tooltip Error and Lua Bug

### ISSUE THREAD

**Issue by naeshy** [tukui-org/ElvUI#1407]
### Troubleshooting Steps

![image](https://github.com/user-attachments/assets/a29ddc16-dd12-48d3-8972-676efe0142e1)
![image](https://github.com/user-attachments/assets/0ecdd1e0-9dee-40d9-8aab-ef7b54ca05d2)

### Describe the expected behavior and what actually happened?

Expect: 

1. Able to right click on data text, see all 3 equipment sets and select one to equip.
2. Able to hover over data text and see all available sets (with currently equipped one green?)

Actual:

1. Left/Right click generates a Lua error and only shows 2 of 3 equipment sets (the one equipped is not actually the missing one either)
2. Hovering shows a non-equipped set as green (assume that is what is indicated by green) 

### Reproducing the issue.

1. Create equipment sets
2. Configure ElvUI panel to show the Equipment Set Data Text
3. Hover/click data text

### Lua Errors

```shell
1x Blizzard_Menu/Menu.lua:930: bad argument #2 to 'min' (number expected, got nil)
[string "=[C]"]: in function `min'
[string "@Blizzard_Menu/Menu.lua"]:930: in function <Blizzard_Menu/Menu.lua:926>
[string "@Blizzard_Menu/Menu.lua"]:977: in function <Blizzard_Menu/Menu.lua:946>
[string "@Blizzard_Menu/Menu.lua"]:1056: in function <Blizzard_Menu/Menu.lua:1047>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:1155: in function `SetMenuDescription'
[string "@Blizzard_Menu/Menu.lua"]:1168: in function <Blizzard_Menu/Menu.lua:1162>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:2262: in function <Blizzard_Menu/Menu.lua:2216>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Blizzard_Menu/Menu.lua"]:2432: in function <Blizzard_Menu/Menu.lua:2429>
[string "=[C]"]: in function `OpenContextMenu'
[string "@Blizzard_Menu/MenuUtil.lua"]:159: in function `CreateContextMenu'
[string "@ElvUI/Core/General/API.lua"]:1062: in function `ComplicatedMenu'
[string "@ElvUI/Core/Modules/DataTexts/EquipmentSets.lua"]:32: in function `onClick'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:448: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:446>

Locals:
(*temporary) = 754.677551
(*temporary) = nil
(*temporary) = "number expected, got nil"
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
thanks 🌼 fixed by https://github.com/tukui-org/ElvUI/commit/5b5d591381eadd0f4e25a290cfa556f5b79b5d18
