### ISSUE TITLE
Accessibility issue: Map scaling

### ISSUE THREAD

**Issue by HarryWraith** [tukui-org/ElvUI#1410]
### Troubleshooting Steps

1. Press M to bring up mini map. Observe tininess. 

### Describe the expected behavior and what actually happened?

As a visually impaired gamer I need good control of UI elements. It is not (I am unable to find) to scale the map independently of the global UI scale. For example, if setting UI scale to 0.6, pressing M to bring up the map, results in a small map anchored to the left side of the screen. I would like to be able to do two things:
1. Scale the map independently with a full screen option.
2. Anchor the Map to the centre of the screen so it is right in front of my field of vision.

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
M is used to open the World Map, not the Minimap as a clarification. Assuming retail wow since I dont see any signs of what wow version you are on. We dont/wont give the World Map a mover in any wow flavor to begin with. If you go into our config -> Maps, enable the Smaller World Map option. When enabled, it will be in the center of the screen and there is a slider to alter the scale of it (reload of the ui is required to take effect)

**Comment by HarryWraith** [comment]
Hi. Thanks for taking the time. I went to config > Maps > world map, and enabled Smaller World Map and tried to use the slider but it didn't alter the size at all no matter when the slider was far left or far right. 

Disabling Smaller World Maps makes no difference either. 

Actually, even with that whole 'maps' element disabled my map is still small. Its like the entire section doesn't do anything for me. I'm happy to provide screenshots or even a video using obs if it helps.

**Comment by Repooc** [comment]
You still didn't say what wow flavor you are running, you should also test after doing `/edebug on` to ensure no other addons are enabled and show `/estatus` window to show what elvui version you are on and wow flavor u are on

**Comment by Repooc** [comment]
Don't forget a reload is needed and u have to hit the ^ at the top

**Comment by Repooc** [comment]
https://github.com/user-attachments/assets/9101971c-8285-4e59-9e36-411e2e512ba2

**Comment by HarryWraith** [comment]
Apologies. Yes, I did reload the UI. However, the cursor co-ordinates on the world map were obscuring the ^. My visual error. That works now. Thank you.

The ^ x and cursor co-ordinates are on top of each other. 

Retail
v13.80 downloaded today

![image](https://github.com/user-attachments/assets/3c01a4f9-2009-474a-b7f9-949099e51ee6)

**Comment by Repooc** [comment]
u can move those btw

**Comment by Repooc** [comment]
that doesnt appear to be elvui's actually

https://github.com/user-attachments/assets/d9a94b81-5817-47f4-9504-0dbc15afc360
