### ISSUE TITLE
[Cataclysm Classic] Elvui ver. 13.80 - Abilities in spellbook dont show their tootlip

### ISSUE THREAD

**Issue by ventarius5** [tukui-org/ElvUI#1415]
Pretty much the title. There is no errors. The icons highlight when hovering over them, spell are usable as usual. Debugging doesnt have any effect. Disabling elvui fixes the issue.

Elvui Disabled:
![image](https://github.com/user-attachments/assets/5cf60de1-b2fd-4e55-b741-2b10da1d4d43)

Elvui Enabled:
![image](https://github.com/user-attachments/assets/bb556d1e-19cb-48ce-b5c4-aff1e1180ac4)

**Comment by Repooc** [comment]
reported to tukui which is wrong, moved to elvui

this has already been addressed in the development build and will be fixed in the next release
