### ISSUE TITLE
[Request] Character Enchant Abbreviation Improvement

### ISSUE THREAD

**Issue by FlareStarrr** [tukui-org/ElvUI#1416]
### Request
Some of the character enchant information has wrong or unintuitive/uninformative abbreviations. In general, automated abbreviations aren't informative, and I'd appreciate it if popular enchants are abbreviated manually.

1. Wrong abbreviation. 
  a. Chant of Armored Speed = "100 Spe". It should be "1000 Speed" or "+1000 Spd"
2. Unintuitive abbreviation. Many automated enchant abbreviations are unintuitive. It would be better if their actual effects are shown.
  a. Chant of Burrowing Rapidity = "Cha of Bur Rap". How about "+250 Spd & -25% Hearth" or simply "+250 Spd"?
  b. Crystalline Radiance = "Cry Rad". How about "+745 Prim. Stat" or "+745 Str" on a strength spec?
  c. Defender's March = "Def's Mar". How about "+895 Stam"?
  d. Cursed Critical Strike = "Cur Cri Str". How about "+390 Crit & -115 Haste"?

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by FlareStarrr** [comment]
![Character Enchant Information Improvement](https://github.com/user-attachments/assets/80d9b941-f347-4fdd-8987-9cdeb8441b8a)

**Comment by kodewdle** [comment]
Sadly there is not an API for this from Blizzard and it's even worse on Cataclysm.
ElvUI does not have a list of enchants with their data, stats, localization, etc which makes this not likely to happen.
The module that displays this is very basic and is most likely going to stay that way.

Perhaps you can find another add-on that does this better than ElvUI does?

**Comment by FlareStarrr** [comment]
Thanks for the explanation.

I find the addon BetterCharacterPanel basically meet my needs.
