### ISSUE TITLE
Chat channel alerts for non-standard global channels

### ISSUE THREAD

**Issue by rbounds** [tukui-org/ElvUI#142]
I find myself often missing messages to non-standard global channels (ie /join fooBar). While ElvUI does seem to support this functionality for some channels (party, raid, guild, etc) it's not possible or unclear on how to configure these for non-standard global channels. 

Ideally I'd like ElvUI config to get a list of all channels I'm currently in to populate the chat 'channel alerts' configuration screen. This interface being context aware would let me treat additional global channels just like the party, raid, etc that are already found on this page.

There might be other addons that add sounds to chat channels but it feels like elvui already does this so I'd like to keep all chat alerts in one place to reduce complexity and possibilities for conflicts

**Comment by asa-git** [comment]
+1 !

**Comment by 1Botanica1** [comment]
This addon may have feature you requested. 


https://www.curseforge.com/wow/addons/mychatalert

**Comment by kodewdle** [comment]
implemented 👍

**Comment by kodewdle** [comment]
![image](https://github.com/tukui-org/ElvUI/assets/2266754/e54f3dac-4877-48ae-88ba-fe07517bc0a5)
