### ISSUE TITLE
Displaying the number of teams in the team instance

### ISSUE THREAD

**Issue by HhhhhhhuiEr** [tukui-org/ElvUI#1420]
### Troubleshooting Steps

Why are teams 7 and 8 not displayed in the team instance? Can it be displayed outside the replica?
![微信图片_20241122220418](https://github.com/user-attachments/assets/46b1b338-a88f-4da3-b547-bfad04efb84d)
![微信图片_20241122220443](https://github.com/user-attachments/assets/3caca871-5d58-4e19-86d0-1cac0668233e)
![微信图片_20241122225746](https://github.com/user-attachments/assets/77bcd50c-9a17-4b2a-85b0-702c9f89ed23)

### Describe the expected behavior and what actually happened?

Display 8 teams in the instance

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [X] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by 1Botanica1** [comment]
Unitframe - general - max allowed groups (uncheck)
