### ISSUE TITLE
Featue Request - Implement Combat Status Icon for Raid Frames.

### ISSUE THREAD

**Issue by neferens** [tukui-org/ElvUI#1423]
### Troubleshooting Steps

Hello!

I would like to request that the existing feature "Combat Status Icon" is implemented for Raid Frames! I use it for most Individual Units, and for Group Units - Party.

Having this feature on the Raid Frames would be very valuable to prevent getting stuck in combat when buffing allies in combat!

One such occation is when playing a healer, and wanting to drink between trash packs!

Another such occation is when using 3/8 T2 to buff Improved Battle Shout as a Warrior. You need to keep track of the combat status of your group to prevent being locked in a very gimped item set!

Best Regards, Auuro

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by kodewdle** [comment]
sure! thank you 🌼 https://github.com/tukui-org/ElvUI/commit/f57f7db4a1ca3e00bf5c381a53512428066b4a03

**Comment by neferens** [comment]
Amazing! I tried fixing it myself, but I missed:
P.unitframe.units.raid1.CombatIcon.enable = false

Much appreciated, I'm eager to try it out when I get home!
