### ISSUE TITLE
Classic Anniversary - if Minimap module is disabled, QueueStatus module still loads

### ISSUE THREAD

**Issue by foobarna** [tukui-org/ElvUI#1424]
### Troubleshooting Steps

Have LFG enable in Classic Anniversary realm, then disable Minimap module from ElvUI

### Describe the expected behavior and what actually happened?

The LFG eye icon is scaled up and in wrong position.
Expectation would be that it should stay untouched given that Minimap module was disabled.

![image](https://github.com/user-attachments/assets/8bb65b28-2d26-41bb-b256-7c3a61094f76)

### Reproducing the issue.

Have LFG enabled in Classic Anniversary realm, then disable Minimap module from ElvUI.

### Lua Errors

```shell
No Lua errors.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by foobarna** [comment]
I've also tried to edit the saved profile from `/Applications/World of Warcraft/_classic_era_/WTF/Account/<account_name>/SavedVariables/ElvUI.lua`, under `general` in `queueStatus` to insert `["enable"] = false` between lines 1254 and 1255 in the hopes that when entering the game that value would be read and behaving as expected. But, the value is ignored and after login/reload/logout it would just revert back.

<img width="529" alt="image" src="https://github.com/user-attachments/assets/52aaca80-a7e1-478e-b3fe-27136026f7ae">

**Comment by 1Botanica1** [comment]
Please follow all the troubleshooting steps and provide the requested information when opening a ticket.

1. Type in chat in game
`/edebug on`
2. Test
Do you still have the issue?
3. If you still have issues after edebug on, type in chat in game `/estatus`and upload a FULL UI screenshot showing the issue/error and the status panel.

**Comment by foobarna** [comment]
Like I've said, no Lua errors, just wrong behaviour.

![image](https://github.com/user-attachments/assets/77e09e20-08e5-4301-8c04-226b255a8921)
