### ISSUE TITLE
[Working as intended/unimplemented/bug?] NPC Party Name misaligned

### ISSUE THREAD

**Issue by Robotnik247** [tukui-org/ElvUI#1425]
### Troubleshooting Steps

Whenever you're with a party of NPCs or as with TWW with Delves, the name (Attach Text To) tag doesn't respond to the chosen position whatsoever. This has been an issue since Legion at the earliest but since it happens so rarely I didn't really think of it that much. 

![Untitled](https://github.com/user-attachments/assets/58b0d30c-6ee4-4a73-8c66-d45fde58d309)

I have attached a picture which shows how it's intended to look.

![Untitled](https://github.com/user-attachments/assets/2440a014-0bae-487b-b448-7b2e3aeb7e1b)

### Describe the expected behavior and what actually happened?

It should work as shown in the picture.

### Lua Errors

```shell
None
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
not sure if i understand what you are trying to say fully but sounds like you have the option, "Text Toggle On NPC" enabled and do not want it enabled so it will follow the location you set instead

**Comment by Robotnik247** [comment]
> not sure if i understand what you are trying to say fully but sounds like you have the option, "Text Toggle On NPC" enabled and do not want it enabled so it will follow the location you set instead

Actually I just wanted to move the text so it behaved like player names, but untoggling the NPC text solved my issue.

**Comment by Repooc** [comment]
> st wanted to move the text so i

yeah toggling that option if the "fix" as how it is setup now was intended by elv when he made that option (for what reason, who knows as its been there for YEARS lol)
