### ISSUE TITLE
Can't purchase a Guild Bank slot

### ISSUE THREAD

**Issue by unclekoen** [tukui-org/ElvUI#143]
### What is the issue you are having?

I am missing the 'plus' next to my Guild Bank to purchase new slots.

### What is the expected behavior?

There is nothinh to click on, so nothing happens.

### What actually happened?

Nothing

### Suggested Solution/Workaround

Create a 'Plus' button.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
https://i.imgur.com/s91dc1k.png

**Comment by Luckyone961** [comment]
![Image 1](https://i.imgur.com/s91dc1k.png "Image 1")
![Image 2](https://i.imgur.com/g0CDVRy.png "Image 2")

**Comment by Azilroka** [comment]
Must be out of date.
