### ISSUE TITLE
Target Unitframe Buff/debuffs No masque support

### ISSUE THREAD

**Issue by itsreps** [tukui-org/ElvUI#1434]
### Troubleshooting Steps

when i apply masque to elvui it skins my buffs/debuffs by minimap but doesnt to any unitframes. target/pet ect. would like this added if possible or is there something i am missing. thanks

this with masque(buffs/debuffs by minimap. works as intended.)
![with masque](https://github.com/user-attachments/assets/7d75c036-6531-499b-abf9-b06147880a00)

this is unitframe, target and no masque
![no masque](https://github.com/user-attachments/assets/9a35a1d2-1f14-4c1c-9373-a0bec763d1cc)

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Repooc** [comment]
you didnt do anything "wrong", just no support for it
