### ISSUE TITLE
Weird Raid Frame Issue

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#1436]
### Troubleshooting Steps

Hey feel free to tell me this is user-error and not a bug. 

I'm having an issue where when I enter an instance, the number of raid groups seems to be capped at 6. But when I'm out side of an instance they work regularly. I just noticed this starting to happen today, and to my knowledge I haven't changed any of the frames. Been about 2 weeks since I was in a 40-man raid.

I did a reset on the "Raid 3" options, but it still has this going on. Any suggestions for other settings to try? Thanks!

Outside of instance

<img width="455" alt="image" src="https://github.com/user-attachments/assets/c3f213fa-dc79-4798-a083-8f2ed662bb9f" />

In the instance

<img width="479" alt="image" src="https://github.com/user-attachments/assets/5fe0d844-063b-4fc2-be46-a8ff2af5e7cc" />

Raid

(They added someone mid-screenshots, hence the discrepancy in one of the groups. But the point was just that there are 7 groups but it's only showing 6.)

<img width="328" alt="image" src="https://github.com/user-attachments/assets/acbd3b15-4910-4e4c-b923-b7c9efb08865" />

### Describe the expected behavior and what actually happened?

See above.

### Reproducing the issue.

See above.

### Lua Errors

```shell
None.
```

### Verification Steps

- [X] I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/main/CHANGELOG.md) and verified [ElvUI](https://tukui.org/elvui) is up to date by checking **/estatus**
- [X] I have verified my issue doesn't exist in the Default UI or the [Issue Tracker](https://github.com/tukui-org/ElvUI/issues).
- [ ] I have not read any of these steps, please close my issue when you see it.
- [X] I have done the Troubleshooting Steps and included the requested screenshots, which show the issue and status panel.

**Comment by Gogo1951** [comment]
<img width="836" alt="image" src="https://github.com/user-attachments/assets/86b3877a-3584-4b0d-b5dc-9a177f38d552" />

Settings for Raid 3.

**Comment by Repooc** [comment]
Uncheck Max Allowed Groups

**Comment by Gogo1951** [comment]
Thank you! Easy fix, appreciate that! (=
