### ISSUE TITLE
[Retail Bug Report] Micro Bar no longer displays when "As Letters" is checked on. Elvui 12.58

### ISSUE THREAD

**Issue by Wiskurs** [tukui-org/ElvUI#144]
### What is the issue you are having?

After installing Elcui 12.58 ans re starting wow, i noticed the Micro Bar i had set to "As Letters" had changed back to images. I went to the Elvui Mico Bar menu and noticed the "As Letters" button was still checked to on. So i set it to off, then checked that the Micro Bar still displayed images. Then checked "As Letters" back on and the Micro Bar no longer appeared at all. 

Happend 100% of the time.

### What is the expected behavior?

Micro Bar should be visible and display letters instead of images.

### What actually happened?

Micro Bar only ever displays images and no longer appears at all when "As Letters" is checked on. In the Elvui Micro Bar tab.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Sounds like a plugin for ElvUI which is not part of ElvUI itself.  You need to the issue up with the plugin developer that adds that as an option.
