### ISSUE TITLE
[Feature Request] Combat font option

### ISSUE THREAD

**Issue by icedterminal** [tukui-org/ElvUI#146]
**Is your feature request related to a problem? Please describe.**
Do not know.

**Describe the solution you'd like**
Combat font change to be an option.

**Describe alternatives you've considered**
Each release, manually editing [`Fonts.lua`](https://github.com/tukui-org/ElvUI/blob/7c9c8e5537362068bfa832108355af738cdb0fd4/ElvUI/Core/General/Fonts.lua#L173) and adding the snippet of code that was removed back in at the bottom of the list.

```lua
SetFont(_G.CombatTextFont,						COMBAT, 200, 'OUTLINE')						-- Self combat font
```
Otherwise, the combat font will always be the default font of the entire ElvUI interface.

**Additional context**
Because https://git.tukui.org/ no longer exists, I am unable to look up any specifics regarding this UI element being removed. I think this was removed in a 2019 release. IIRC someone said it was a rendering issue for some? Which is one I do not have. Even so, this should still be an option for users. There is even a short thread about this on your support forums from 2021. https://www.tukui.org/forum/viewtopic.php?f=5&t=16773 - Users here grabbed another addon. IMO, defeats the purpose of ElvUI having an addon for each aspect of the UI when it is considered a complete UI replacement. 

Currently, "Combat text font" does nothing without the snippet of code. Which is also confusing in itself since the option actually does nothing.

**Comment by icedterminal** [comment]
Closing.
None of the maintainers have contributed to any activity in over 30 days.

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/156470722-5050f38a-7c53-4ebd-a9ce-705514651d24.mp4

**Comment by Azilroka** [comment]
```
local chatFontHeights = {6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}
function E:UpdateBlizzardFonts()
	local db			= E.private.general
	local NORMAL		= E.media.normFont
	local NUMBER		= E.media.normFont
	local NAMEFONT		= LSM:Fetch('font', db.namefont)

	-- set an invisible font for xp, honor kill, etc
	local COMBAT		= (E.eyefinity or E.ultrawide) and E.Media.Fonts.Invisible or LSM:Fetch('font', db.dmgfont)

	_G.CHAT_FONT_HEIGHTS = chatFontHeights

	if db.replaceNameFont then _G.UNIT_NAME_FONT = NAMEFONT end
	**if db.replaceCombatFont then _G.DAMAGE_TEXT_FONT = COMBAT end**
...
end
```

**Comment by Azilroka** [comment]
![Wow_UAyx25k08T](https://user-images.githubusercontent.com/1934853/156470950-dae12e03-eece-4833-a5ef-81055244d22e.jpg)

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/156471013-b970c6ea-1f38-4ae1-9918-e3f4e7fd39c4.mp4

**Comment by icedterminal** [comment]
This clip was to large to upload. Please see here: https://streamable.com/skok59

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/commit/660eda1046c53914b347af34da141225cf957f63

**Comment by icedterminal** [comment]
Greatly appreciated. 🙂
