### ISSUE TITLE
[Retail Bug Report] Quest item no longer glow in loot table

### ISSUE THREAD

**Issue by matyx666** [tukui-org/ElvUI#147]
### What is the issue you are having?

After update to 12.60/61 quest items no longer glow

![glow3](https://user-images.githubusercontent.com/98023024/150118351-d6aa0d29-2a4a-465b-93bd-a69b69c693fb.png)

### What is the expected behavior?

Quest items used to glow like execute spells (Action button glow)
![glow](https://user-images.githubusercontent.com/98023024/150116995-624cde5c-0a5d-461e-affd-3cd386e7c53b.png)

### What actually happened?

After update to 12.60/61 quest items no longer glow

![glow3](https://user-images.githubusercontent.com/98023024/150118351-d6aa0d29-2a4a-465b-93bd-a69b69c693fb.png)

Quest items used to glow like execute spells (Action button glow)
![glow](https://user-images.githubusercontent.com/98023024/150116995-624cde5c-0a5d-461e-affd-3cd386e7c53b.png)

### Suggested Solution/Workaround

Might be related to change in 12.60:
ActionBars: Swapped to Custom Glow (General -> Cosmetic)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [x] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Should be fixed in Dev
