### ISSUE TITLE
Untargetable boss frames not appearing

### ISSUE THREAD

**Issue by Thdlock** [tukui-org/ElvUI#148]
### What is the issue you are having?

On Guardian of the First ones (SoD) and Vigilant Guardian (Sepulcher) there are boss frames which show the energy / hp of the boss that do not appear when using elvui. 

### What is the expected behavior?

This image shows how it looks on the default UI 
![image](https://user-images.githubusercontent.com/97811478/150183002-70332783-cbf5-4f34-9dd6-68b3551990c8.png)

### What actually happened?

How it appears on elvui
![image](https://user-images.githubusercontent.com/97811478/150183086-cb443d95-3f66-4e6f-96a7-522e1f7debc2.png)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
It's been confirmed to be a bug in their secure driver code for the unitframes on Blizzard's side. So it might eventually get fixed.
