### ISSUE TITLE
[TBC Bug Report] Quest Icon doesn't appear in bags

### ISSUE THREAD

**Issue by Dhorm** [tukui-org/ElvUI#149]
### What is the issue you are having?

Quest Icon doesn't appear in bags.

### What is the expected behavior?

Quest Icon should appear

### What actually happened?

Ever since I updated from v2.14, Quest Icon doesn't appear in bags.
Currently, I'm using v2.33 and I tried to enable/disable Quest Icon in bag option but it never displays the Quest Icon.
Although quest items do show assigned color, which is red.

If I rollback the version from v2.33 to v2.14 Quest Icon appears correctly.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
The quest icon is only for starter items. It was incorrectly showing for all items.
