### ISSUE TITLE
[Feature Request] Elvui Nameplate - Threat color

### ISSUE THREAD

**Issue by Jejeow** [tukui-org/ElvUI#151]
Hello, i have a problem

When i'm on my war tank, the color of my target is green and my co-tank had it's aggro had a purple colored nameplate. But when i'm on my druid tank, the color of my target is red and my co-tank had it's aggro had a green colored nameplate.
I tested with the same profile as my warrior on my druid and it didn't change anything.
Can you help me, so that I have the same nameplate color settings as on my war, i.e. as a tank.
Thank you

**Comment by Azilroka** [comment]
This ticket system is not support.
