### ISSUE TITLE
[Feature Request] <Font for Torghast Powers module>

### ISSUE THREAD

**Issue by Hollicsh** [tukui-org/ElvUI#152]
**Is your feature request related to a problem? Please describe.**
< The problem is that I can't find where I can change the font for the "Torghast Powers" module. I have PT Sans Narrow by default installed everywhere, but when I activate the S&L "Torghast Powers" module, I cannot change the font anywhere. >

**Describe the solution you'd like**
< Хотелось бы, чтоб появилась возможность менять шрифт модуля "Torghast Powers". >

**Additional context**
< I talked in discord with Mr. Repooc, he told me to create an ElvUI ticket, perhaps in the future this function will be implemented. >

![Screenshot_4](https://user-images.githubusercontent.com/54585769/150690991-0e718076-2890-44a4-a0ab-54ea0290e11e.png)

**Comment by kodewdle** [comment]
we don't add font options for skins, generally they take whatever "font" is applied from the "Replace blizzard fonts" option
