### ISSUE TITLE
[Retail Bug Report] Exporting and importing a profile does not keep the "Enable" state of different panels 

### ISSUE THREAD

**Issue by RaulRG** [tukui-org/ElvUI#156]
### What is the issue you are having?

I export a profile from a computer with ElvUI 12.62 and import it in another computer with the same version.

Under the configuration for "Bags" i had the flag "Enable" deactivated as I use another addon for bags.
I assign the profile to a character in the new machine and the "Enable" flag is active and thus I need to deactivate it again.

Of course, it is not a big deal, but if you need to do it for 20 toons is just annoying

### What is the expected behavior?

The export / import of profiles should keep the state of the "enable" flag for different options (my example was the bags, but I think it is in more places)

### What actually happened?

The flag was not exported or it was ignored.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Enables for Modules are stored in Private Profile not the normal profile. This is not an issue.

**Comment by Azilroka** [comment]
Both of the issues you created could have been explained in Discord.
