### ISSUE TITLE
[Feature Request] Class color to selected choices

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#157]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Now selected frame is emphasized by green color like in SC below
https://imgur.com/a/YkSV2Fh
https://imgur.com/a/rNvfAfo

Now elv supports classcolored border for  mouseovered buttons like SC below
https://imgur.com/a/7TE8t3q

I think when selected buttons is also class colored, It feels more integrated for users.

**Describe alternatives you've considered**
Maybe you guys can added class-colored options for this stuff. So users can have choice.

**Additional context**

Found out that skinning addon like aurora support this function.
https://media.forgecdn.net/attachments/217/792/wowscrnshot_092517_095616.jpg
https://media.forgecdn.net/attachments/217/790/wowscrnshot_092517_095637.jpg

**Comment by Azilroka** [comment]
We are not going to do options for skins.
