### ISSUE TITLE
[Feature Request] Lightning elemental crit chance doesn't show

### ISSUE THREAD

**Issue by Voc1f3ra** [tukui-org/ElvUI#158]
The spell critical chance does not properly show the element of Lightning for elemental shamans, which is our main spell crit stat. 

![image](https://user-images.githubusercontent.com/91396771/152069233-df8ca456-88ab-483f-b640-fad2fb147402.png)

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/152071311-3085caea-ea87-440d-b474-2f11d5ef8897.png)

I don't know what addon is providing that info but the default ui does not provide it.

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/152071619-8f381fbd-0b78-4896-9e0e-94b5e560033a.png)

It's not part of the damage schools for me to query
