### ISSUE TITLE
[TBC Bug Report] Embedded LibHealComm4 error

### ISSUE THREAD

**Issue by Road-block** [tukui-org/ElvUI#160]
### What is the issue you are having?

Lua errors on HoT/Cleave heals

### What is the expected behavior?

Heal prediction without errors

### What actually happened?

Heal prediction intermittently failing

### Suggested Solution/Workaround

The error is caused by `spellID` being `nil` at the line shown in the callstack.

At a guess it happens because querying [GetSpellInfo](https://github.com/tukui-org/ElvUI/blob/f66fad62561fe967b45268c665812a33b85cc2d4/ElvUI/Libraries/TBC/LibHealComm-4.0/LibHealComm-4.0.lua#L2183) with a name at line:2183 is not guaranteed to return information unless the spell is in the player's spellbook.

### Errors

```shell
18x LibHealComm-4.0\LibHealComm-4.0-101.lua:2198: table index is nil
[string "@LibHealComm-4.0\LibHealComm-4.0-101.lua"]:2198: in function `?'
[string "@LibHealComm-4.0\LibHealComm-4.0-101.lua"]:2835: in function <LibHealComm-4.0\LibHealComm-4.0.lua:2833>
```
```


### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
was this fixed by https://github.com/tukui-org/ElvUI/commit/1e385d1236d42280b6a48f79f7d66ba041842667? reopen if not :)
