### ISSUE TITLE
Moonkin Form active icon bug

### ISSUE THREAD

**Issue by Squimbert** [tukui-org/ElvUI#163]
### What is the issue you are having?

When switching to moonkin form the activated icon is tinted instead of looking like the arcane explosion icon.
![image](https://user-images.githubusercontent.com/99698377/153970995-28a60f8d-9af3-46a5-8ad3-f536eb6cef8b.png)
![image](https://user-images.githubusercontent.com/99698377/153971037-7d751128-bd6e-43e1-800d-4df66fc194af.png)
The first image is what it looks like when form is activated and bugged.  The second image is what it's supposed to look like when activated, and is what all my other forms look when activated. i am balance specialization.

### What is the expected behavior?

the moonkin form icon should look like the second picture attached above when active.

### What actually happened?

the moonkin form icon looks like the first picture above, unlike every other form.

### Suggested Solution/Workaround

i haven't been able to pinpoint what exactly causes it or what conditions cause it, but the bug tint looks like "darken inactive" style for stance bar (although this issue is for the player bar) where it's supposed to look like "classic" style. i did a full private and global profile reset and elvui installation and it didn't fix.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
should be fixed if you try dev, thanks for reporting
