### ISSUE TITLE
[Feature Request] Druid Bear: Classbar Mana Show Condition

### ISSUE THREAD

**Issue by pquerner** [tukui-org/ElvUI#164]
**Is your feature request related to a problem? Please describe.**
With the latest release of 2.35 it was added that druids in bear form could see there current mana as a classbar.
This fixes the "problem" of not seeing the manabar as a bear, but doesnt as a cat first off, but second of, this was previously fixed by "most of us"  with Weakauras.

Adding a toggling option if this Classbar should show Mana is needed to go back to a neutral behaviour imho.

**Describe the solution you'd like**
Add a toggling option to display mana/or not in druid forms.

**Describe alternatives you've considered**
Returning to 2.34.

**Comment by Repooc** [comment]
We wont be adding it for kitty bc the classbar is the combo points which is taking the place of where the mana bar would be.  You can enable the Auto Hide option and it will hide the mana bar in bear if mana is full to help you work around it from showing or not.  We have sort of touched based on if we will add such option to not show but can't say we will really.

**Comment by pquerner** [comment]
Hello!

Thanks for getting back to me.

I understand the combo bar is more important for cat druids, of course.
However, this also limits information (as in the default UI) for example of "how many powershifts can I do before not returning to my wanted form again".

Wheres as manabar in bear form is usually, most of the time, not needed to know.

Hiding the mana when at full mana only solves it partially (for bears); hiding it fully (optionally) brings back a neutral behaviour - or rather a completely "set as you need" experience.

Please consider it. :)

Thanks!

**Comment by Xmind2006** [comment]
Just wanted to throw my support behind Pquerner's last comment.   I was excited to see the mana bar recently while in bear form and was about to delete my "Druid Bar Classic" add on, but then not seeing it in cat form is the whole reason I have that add on.

I'd be okay even if the top bar was split like 50/50 where half is combo points and half is the mana bar.  I mean most cats don't care about knowing exactly 3 or 4 combo points or 45% or 55% mana, relative numbers is all we really need.

I'm also okay if it was it's own bar as I have now with the "Druid Bar Classic" plate that is present whenever I'm in feral.

Thanks for entertaining the idea.
