### ISSUE TITLE
[Retail Bug Report] Keybinds Move/Remove Randomly on log-in

### ISSUE THREAD

**Issue by Punk611** [tukui-org/ElvUI#165]
### What is the issue you are having?

Several times when logging in my keybinds will change or be completely removed. No clue what causes this, please fix.

### What is the expected behavior?

Once set, keybinds should remain the same ever log in.

### What actually happened?

Keybinds changing or being removed when logging in.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Either you have another addon causing issues or maybe you are having file permission issues that wow isn't able to write ur keybind to the local disk. ElvUI doesn't handle the saving of keybind not any way of changing them.  When u go into keybind mode or use wows keybind menu, all that is handled by blizzard. There are addons that can save and alter ur keybind a based on various things like spec and such but that has nothing to do with elvui.  You should start with the basics and do `/edebug on` and see if u still have the issue then also test with 0 addons.

**Comment by Punk611** [comment]
This is not caused by blizzard or another addon. This is Elvui. At this point I'm Uninstalling this addon and using something else. Sent from my  U.S.Cellular© Smartphone
-------- Original message --------From: Repooc ***@***.***> Date: 2/18/22  5:12 PM  (GMT-06:00) To: tukui-org/ElvUI ***@***.***> Cc: Punk611 ***@***.***>, Author ***@***.***> Subject: Re: [tukui-org/ElvUI] [Retail Bug Report] Keybinds Move/Remove
  Randomly on log-in (Issue #165) 
Either you have another addon causing issues or maybe you are having file permission issues that wow isn't able to write ur keybind to the local disk. ElvUI doesn't handle the saving of keybind not any way of changing them.  When u go into keybind mode or use wows keybind menu, all that is handled by blizzard. There are addons that can save and alter ur keybind a based on various things like spec and such but that has nothing to do with elvui.  You should start with the basics and do /edebug on and see if u still have the issue then also test with 0 addons.

**Comment by Azilroka** [comment]
Good luck and have fun. Keybinds are stored server side.
ElvUI and ElvUI_OptionsUI is the only 2 official addons. All others with ElvUI in it's name is a 3rd party plugin.
