### ISSUE TITLE
[TBC Bug Report] Friends list, including Battle.net friends is filled with "Unknown" characters after updating Elvui to version 2.36 

### ISSUE THREAD

**Issue by meebsmagee** [tukui-org/ElvUI#173]
### What is the issue you are having?

My entire friends list including Battle.net friends is filled with "unknown" characters, when I am messaged by a battle.net friend their name is blank so I am unable to see who is sending the message.

### What is the expected behavior?

My friends list works as normal.

### What actually happened?

My friends list in-game only shows "Unknown" characters, and I cannot message them, or tell who is messaging me.

### Suggested Solution/Workaround

Reverting back to version 2.35 fixed the issue.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
that is client/server issue and not related to elvui... just happened to show for you when you reinstalled the other version as its perfectly fine as we speak and we dont change anything like that on the frame, we just skin the frame.
