### ISSUE TITLE
[Feature Request] SpellHaste DataTexts TBC

### ISSUE THREAD

**Issue by d3xavier** [tukui-org/ElvUI#176]
**Is your feature request related to a problem? Please describe.**
This is not related to any problem.

**Describe the solution you'd like**
Add the SpellHaste Data Texts so it easy to see current SpellHaste on the Datatext Panels

**Describe alternatives you've considered**
I currently have the SpellHaste DataText created locally which I copy back over after every update to ElvUI.  In other words, I've already implemented it myself, but having it part of the official ElvUI codebase would remove that hassle, as I have to also edit the Load_DataTexts.xml as well.  

**Additional context**
Find the compressed SpellHaste.lua file below for addition to the ElvUI/Core/Modules/DataTexts
Also included is the modified Load_DataTexts.xml 

[SpellHaste.zip](https://github.com/tukui-org/ElvUI/files/8147136/SpellHaste.zip)

**Comment by Repooc** [comment]
I cant say if we will add this or not, but i would suggest to get https://www.curseforge.com/wow/addons/elvui-tinkertoolbox where you can just add a custom datatext there where you don't need to edit any elvui files

**Comment by kodewdle** [comment]
the file you had was a little messed up, missing a function for classic and it has the wrong event.  anyways, implemented it myself
