### ISSUE TITLE
[Retail Bug Report] Compatibility issue with KgPanels

### ISSUE THREAD

**Issue by mont3crysto** [tukui-org/ElvUI#177]
### What is the issue you are having?

When using the last version of ElvUI (12.66) KgPanels breaks and its panels will not attach to ElvUI anymore. Toggling ElvUI's profiles will fix the issue until the next UI reload.

I'm sure it worked up until ElvUI 12.2, last version I used when I was playing, but unfortunately I cannot test other versions as I'm not able to download them from Tukui.org

Attached are two screenshot, one with ElvUI 12.66 and the other with the 12.2 version, imported from a backup of mine.

![WoWScrnShot_022722_175050](https://user-images.githubusercontent.com/61067006/155892789-9134f8c6-b921-4685-9c2b-5f826978575c.jpg)

![WoWScrnShot_022722_175431](https://user-images.githubusercontent.com/61067006/155892795-496f9989-1141-44f8-aaf5-8b2ddee9e14c.jpg)

### What is the expected behavior?

KgPanels should be able to attach to ElvUI frames

### What actually happened?

KgPanels glitches with newer versions of ElvUI

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
We don't provide direct support for other addons including kgPanels.  We don't have any code that directly interacts with ElvUI so you will need to contact them if you are having issues working with kgPanels + ElvUI.  If they find something we changed that can't be worked around, they can contact us to specify what was changed that broke them working together.

**Comment by mont3crysto** [comment]
Is there a way for me to download other versions of ElvUI in order to better pinpoint the version with the breaking changes?

**Comment by Azilroka** [comment]
You have to wait until the unitframes are loaded to attach the kgPanel onto it.. It doesn't happen until after entering world event

**Comment by mont3crysto** [comment]
> You have to wait until the unitframes are loaded to attach the kgPanel onto it.. It doesn't happen until after entering world event

Would love to if there was a way, but even toying with a bit of scripts I couldn't do much.

If the problem is, as you're suggesting, that my panels are trying to attach to the unitframes before they're rendered, I can only guess that something has changed about the way that's handled by ElvUI.

Seems strange to me though that the panels are behaving this way, as they never had problems with unitframes toggling between visible and invisible states all the time, even without adding any custom script.

--

Anyway, I've been able to retrieve the lua error that, for whatever reason, I wasn't getting before.

> Message: Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua:177: attempt to index local 'unit' (a nil value)
> Time: Sun Feb 27 23:32:12 2022
> Count: 1
> Stack: Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua:177: attempt to index local 'unit' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua"]:177: in function `HandleUnit'
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua"]:347: in function <Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua:298>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua"]:776: in function `Spawn'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1109: in function `CreateAndUpdateUF'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1134: in function `LoadUnits'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1547: in function `func'
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\factory.lua"]:20: in function <...nterface\AddOns\ElvUI\Libraries\Core\oUF\factory.lua:16>
> [string "=(tail call)"]: ?
> 
> Locals: 

and

> Message: Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua:177: attempt to index local 'unit' (a nil value)
> Time: Sun Feb 27 23:32:13 2022
> Count: 1
> Stack: Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua:177: attempt to index local 'unit' (a nil value)
> [string "=[C]"]: ?
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\units.lua"]:177: in function `HandleUnit'
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua"]:347: in function <Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua:298>
> [string "=(tail call)"]: ?
> [string "@Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua"]:867: in function <Interface\AddOns\ElvUI\Libraries\Core\oUF\ouf.lua:829>
> 
> Locals: 

Maybe it rings some bells to you.

**Comment by Azilroka** [comment]
We have no lua errors on the current release in Exile's Isle that I can tell. I logged in with ElvUI and BugGrabber.

Also, Yes, We did change how the UnitFrames are loaded. It's not a problem of ours if it breaks compatibility for an addon.
