### ISSUE TITLE
No Access to this setting UNIT FRAME MOUSEOVER CASTING under Interface Options > Combat.

### ISSUE THREAD

**Issue by Zerofuxx** [tukui-org/ElvUI#179]
### What is the issue you are having?

NEW SETTING: UNIT FRAME MOUSEOVER CASTING
This setting allows you to mouse over a unit frame and cast a spell on that character without targeting them.
Access this setting under Interface Options > Combat.

NOT SHOWN. Need to Disable ElvUI
![ElvUI](https://user-images.githubusercontent.com/100688565/156159298-c8e686b0-850d-4667-8e30-601f7e1c70a8.png)
![RETAIL UI](https://user-images.githubusercontent.com/100688565/156159301-aa88d4f4-85e1-4d2d-8b32-14a746efb9f7.jpg)

### What is the expected behavior?

Shown

### What actually happened?

Not usable exept u tune ElvUI off to change settings and then back on.

### ElvUI Changelog/Troubleshooting

- [x] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [x] I have verfied ElvUI is up to date by checking /estatus.
- [x] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [x] I have verfied my issue doesn't exist in the default UI.
- [ ] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Guess you found that we located it in our settings.

**Comment by Zerofuxx** [comment]
> Guess you found that we located it in our settings.

Yes not happy with that solution but helps thx

**Comment by Repooc** [comment]
No reason to no be happy considering u are using elvui bars, our option doesn't require a reload to use the feature as during testing it would only work after reload and it's nothing new to what we do to handle options we tie into
