### ISSUE TITLE
[Retail Bug Report] Boon of the Ascended raid frames fading on cast

### ISSUE THREAD

**Issue by foobartles** [tukui-org/ElvUI#182]
### What is the issue you are having?

https://user-images.githubusercontent.com/6947753/156477444-8ad61369-360d-448d-9368-991bb829e633.mp4

when casting boon of the ascended, all raid frames go out of range for a GCD

### What is the expected behavior?

frames should not fade out

### What actually happened?

frames faded out of range after casting boon of the ascended

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by foobartles** [comment]
vesrion 12.66 on patch 9.2

**Comment by kodewdle** [comment]
![image](https://user-images.githubusercontent.com/2266754/159989653-58d861fa-f1b7-4722-940e-8b24c326a0b6.png)

but that caused a problem, it was refixed by https://github.com/tukui-org/ElvUI/commit/a9388443d9528095a3d954b164e4abbda734c14a in this build: [dev](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)

**Comment by foobartles** [comment]
cheers, thanks
