### ISSUE TITLE
[Retail Bug Report] Bag Auto Toggle option doesn't appear to work

### ISSUE THREAD

**Issue by akbyrd** [tukui-org/ElvUI#185]
### What is the issue you are having?

I have all of the check boxes for Bag Auto Toggle disabled, but my bags are still opening when I talk to a vendor, open the bank, or open the AH.

### What is the expected behavior?

When I disable Auto Toggle my bags do not automatically open.

### What actually happened?

My bags automatically opened.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
![image](https://user-images.githubusercontent.com/1479745/156876609-ee2ccc52-67fb-4cb5-8ad1-5aa9f96af21a.png)
Make sure to do this step of `/edebug on` and test as i just tested on retail and cant reproduce on 12.66.

**Comment by akbyrd** [comment]
It does indeed seem to be an interaction specifically with ArkInventory. I disabled addons manually and didn't disable that one because it's the one I need the options to work with.

**Comment by Repooc** [comment]
well our options does not apply to other addons, so that is something that ark inventory will need to handle

**Comment by Azilroka** [comment]
People just blindly click the boxes instead of reading. I mean what's the point of typing the things out if they are just ignore it anyway.
