### ISSUE TITLE
Focus target not working on middle mouse click on target frame - have to uncheck/check to work

### ISSUE THREAD

**Issue by XBlueBobX** [tukui-org/ElvUI#187]
### What is the issue you are having?

Until latest update focus could be set by middle mouse clicking on target frame. Checkbox is still checked. Unchecking then checking makes it work

### What is the expected behavior?

Middle mouse click sets focus 

### What actually happened?

Nothing

### Suggested Solution/Workaround

Restore to previous action

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
fixed in 40eff045384ee160dc43343f3e69a24510fb76a1
