### ISSUE TITLE
[Retail Bug Report] Chat doesn't line up with Chat Frame when Panel Snapping is enabled.

### ISSUE THREAD

**Issue by Zithyxx** [tukui-org/ElvUI#191]
### What is the issue you are having?

When Panel Snapping is enabled, it causes the chat to not align with the Chat Frame properly. The chat will exceed the chat frame which will cause text to be cut off.

### What is the expected behavior?

The expected behavior is that the chat should align perfectly with the chat frame, as it seems counterintuitive to have a feature that snaps the chat to a chat frame, but not snap it properly.

### What actually happened?

When I go through the ElvUI installation process and set up the Chat, while it looks fine, it's actually protruding from the Chat Frame, which I can see when I "Unlock Window" on the Chat. Since the chat is snapped to the chat  frame it causes any text that goes past the chat frame into the protruding area to not be visible. This happens on both the left and right chat frames. I have tried everything from clearing my cache and WTF files to disabling all addons except ElvUI, and it seems to just be problem with chat snapping to the chat frame.

### Suggested Solution/Workaround

The only workaround is to disable chat frame snapping and manually adjust the chat. However, this causes problems when you try to hide the chat panel as the chat still stays as it is no longer attached to the chat frame.

### Errors

No errors, as this doesn't seem to be an internal problem with elvui, just a problem with how chat panel snapping is configured.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
You should show examples of what you mean.
