### ISSUE TITLE
[Feature Request] pvp itemlevel on PaperDoll

### ISSUE THREAD

**Issue by VeranusXia** [tukui-org/ElvUI#197]
\core\General\ItemLevel.lua
line 44:
	local itemLevel = lineText and (strmatch(lineText, MATCH_ITEM_LEVEL_ALT) or strmatch(lineText, MATCH_ITEM_LEVEL))
=>
	local itemLevel = lineText and (strmatch(lineText, MATCH_ITEM_LEVEL)  or  strmatch(lineText, MATCH_ITEM_LEVEL_ALT))

**Comment by kodewdle** [comment]
it's like this by design so we can see the real players item level in other situations of scaling; obviously it's not ideal for PVP situations but that's how it is
