### ISSUE TITLE
[Retail Bug Report] F2P XP Bar Does Not Hide At 20

### ISSUE THREAD

**Issue by cheeseman1** [tukui-org/ElvUI#20]
### What is the issue you are having?

For free-to-play accounts, the XP bar does not hide when the character reaches max level (20).

### What is the expected behavior?

The XP bar should automatically hide when the character reaches 20 and is XP capped.

### What actually happened?

The XP bar remains visible despite "hide a max level" being checked

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).

**Comment by Azilroka** [comment]
We never added that check because it was never an issue.
