### ISSUE TITLE
[Retail Bug Report] Nameplates Stylefilter color overrides the threat color

### ISSUE THREAD

**Issue by mBlinkii** [tukui-org/ElvUI#200]
### What is the issue you are having?

The Custom Life Bar Color in the Style Filter settings overrides the bad Threat color. 

### What is the expected behavior?

the custom color should not override the bad threat color or the transition color. It should be so that the color of stylfilter is taken only when the threat is good and for everything else the threat colors are used.

### What actually happened?

Currently, the color is always taken from the style filter.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
This is actually working as intended.  Style Filters are advanced and meant to override any "built-in" setting.  Only thing that would override a style filter is another style filter with a higher prioirty.  You will have to account for threat in your Style Filter under the Threat section so the health color only applies for the selected Threat triggers.

**Comment by mBlinkii** [comment]
> This is actually working as intended. Style Filters are advanced and meant to override any "built-in" setting. Only thing that would override a style filter is another style filter with a higher prioirty. You will have to account for threat in your Style Filter under the Threat section so the health color only applies for the selected Threat triggers.

Hi, thanks for the quick answer, then I will have to think of something for it. greetings blinkii

**Comment by Repooc** [comment]
Just go to the threat section for the filter and check which conditions you want it to change color of the nameplates and not check the threat conditions you don't want them to change color
