### ISSUE TITLE
Buffs/Debuffs

### ISSUE THREAD

**Issue by jaftica** [tukui-org/ElvUI#204]
### What is the issue you are having?

Version 2.38 does not show any aura icons next to the mini map.

### What is the expected behavior?

Aura icons should show

### What actually happened?

Nothing

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Dichotomia** [comment]
Same error here.

**Comment by Lilbanter** [comment]
Yeah same here, I think it's a problem related to the latest ZA patch (TBC classic).

**Comment by CuNe89** [comment]
Just read the latest changelog:

"_Version 2.38 March 23, 2022
Auras: Turned off ElvUI top auras until Blizzard fixes the bug (Untick "Disable Blizzard" if you want to see default auras)_"

**Comment by Repooc** [comment]
should be fine on wow build > 2.5.4.42873

**Comment by insunaa** [comment]
Funny that it's a Blizzard bug when it works completely fine with older versions of ElvUI

**Comment by Azilroka** [comment]
> Funny that it's a Blizzard bug when it works completely fine with older versions of ElvUI

Which version because it was literally patched and confirmed on https://github.com/Stanzilla/WoWUIBugs/issues/225

**Comment by insunaa** [comment]
Worked with 2.35

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/160018711-e57fe1d6-afa4-4457-a8de-3fdf5aa2542a.png)

**Comment by Azilroka** [comment]
![sublime_text_VsiGQoO3Wm](https://user-images.githubusercontent.com/1934853/160018807-c6bdd457-31bf-42e7-a8d4-c6dd126692f5.jpg)

**Comment by Azilroka** [comment]
https://github.com/Gethe/wow-ui-source/blob/0f7ac16511a41a3786ca18d879bbeca3f62dd64d/Interface/FrameXML/AuraUtil.lua This was at the beginning of the ZulAman Patch

**Comment by Azilroka** [comment]
ZulAman: https://github.com/Gethe/wow-ui-source/blob/bc779043df19164bbe2478ab47305231e60c8899/Interface/FrameXML/SecureGroupHeaders.lua#L1026
HotFixed https://github.com/Gethe/wow-ui-source/blob/classic/Interface/FrameXML/SecureGroupHeaders.lua#L1026

**Comment by Azilroka** [comment]
Maybe next time you get the facts straight.

**Comment by insunaa** [comment]
Worked on my client, I can only tell you what I observed

**Comment by Azilroka** [comment]
Worked on your private client? Unless you are using retail World of Warcraft - private servers are not supported here. It was the secure header that was broken. I linked all relevant information.
