### ISSUE TITLE
[Retail Bug Report] Boss Frames no longer grey out when out of range

### ISSUE THREAD

**Issue by Pagallac-eng** [tukui-org/ElvUI#207]
### What is the issue you are having?

Boss frames (including "friendly targets") for instance on Anduin or Prototype Pantheon do not grey out when out of range. Unitframes (target frames) still grey out correctly. This seems to have coincided with the change to show more targets on the boss frames in version 12.72 (UnitFrames: Added support to display all Seeds of the Pantheon fight in Boss Frames)

### What is the expected behavior?

Mobs on boss frames (both boss and friendly targets) should grey out when out of range.

### What actually happened?

All frames have the "in-range" visuals. The settings under Unitframes->group units->boss do not seem to affect the boss frames. 

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
was fixed by: https://github.com/tukui-org/ElvUI/commit/a9388443d9528095a3d954b164e4abbda734c14a
