### ISSUE TITLE
[TBC Bug Report] <Chat frame moving>

### ISSUE THREAD

**Issue by Purplecatchap** [tukui-org/ElvUI#209]
### What is the issue you are having?

Second chat window moving between relogs. 

### What is the expected behavior?

For the window to sit in place when locked. Wasnt an issue before the latest phase 4 patch/updates to the addon. 

### What actually happened?

Second chat window (see screenshot) moved between relogs. Doesnt matter if it is locked or not.  Starting to happen after the phase 4 update/addon update for this phase. 
1.Only seems to affect people using elvui. 
2.Addon is up to date.
3.Turned all other add-ons off and still happens. 
4.Does not happen on the default/blizz UI.

Tends to move maybe 1cm down and to the right when I relog. Ive tried moving it to other places on the screen and it sometimes moved my even larger amounts. 3-4 cm etc. 

![image](https://user-images.githubusercontent.com/102548076/160499739-a55577db-4fb0-4c2c-a6a9-c3b7c0f688c3.png)

Apologies if this has been reported already.  Ive looked and could not see it.
Thank you.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Purplecatchap** [comment]
Where it moves to after a relog.
![image](https://user-images.githubusercontent.com/102548076/160504086-d770bcf3-5255-4498-ba73-d71924373781.png)

Moving to center of screen to show it happens even when moving it some where else:
![image](https://user-images.githubusercontent.com/102548076/160504190-0fd4db7b-7736-4947-b79a-2fe0eefe418f.png)

Where it moved to after a relog:
![image](https://user-images.githubusercontent.com/102548076/160504239-8db7abc8-ccdb-44b2-81a5-e3e6d2688d44.png)

**Comment by BigMeanGiraffe** [comment]
Having the same issue

**Comment by Purplecatchap** [comment]
Thank you, that worked.
