### ISSUE TITLE
[Feature Request] Nameplates overlapping friendly, stacking enemy

### ISSUE THREAD

**Issue by aurorawalberg** [tukui-org/ElvUI#213]
**Is your feature request related to a problem? Please describe.**
I use the console command /run SetCVar('nameplateShowOnlyNames', 1) like many other raiders. This allows me to turn on friendly nameplates and see everyone's names clearly. However, I do not want the friendly nameplates to stack, because then they will take up too make space. I do however want the enemy nameplates to stack because then I can see them all. Plater has implemented something to solve this - an option that makes only the enemy nameplates stack and keeps the friendly ones overlapping. It would be incredible if neatplates could do the same! I think they implemented /run C_NamePlate.SetNamePlateFriendlySize(1, 1) settings to avoid overwriting it.

**Describe the solution you'd like**
An option to allow enemy nameplates to stack, while friendly ones overlap.

**Describe alternatives you've considered**
- Installing plater
- Using overlapping plates in raid and not seeing all enemy frames (works because I'm a healer but still not optimal)

**Comment by Repooc** [comment]
![image](https://user-images.githubusercontent.com/1479745/167327000-289a6a24-614f-4b5c-a2bc-c0335066df4c.png)
I dont see such option in Plater to not have friendly np and enemy np not stack as the stacking nameplate option is a blizzard cvar which handles both.
"It would be incredible if neatplates could do the same!"
We arent Neatplates addon development team, you will need to talk to them. [Neatplates Github Issues](https://github.com/Luxocracy/NeatPlates/issues)
If another addon is doing what you said with C_NamePlate.SetNamePlateFriendlySize, we give you the option to adjust that in ElvUI's Nameplates section -> General -> Clickable Size  Our min size can typically be overwritten if you do any coding and want to overwrite what the min is or do it another way.

**Comment by Repooc** [comment]
After a small discussion, it seems that what you were saying with the SetNamePlateFriendlySize is a way some have been "working around" it but yes, we wont add any options to force the size of them 1, 1 with options besides what we have in the config but a typical user cant with our options since we have a min set and would need a plugin to overwrite the min in the options or do like some others do, make a wa that sets them that size when in an instance and revert to normal when not
