### ISSUE TITLE
[TBC Bug Report] [curpp] for rage shows values above 100 after a target dodges

### ISSUE THREAD

**Issue by JimtheMaggot** [tukui-org/ElvUI#215]
### What is the issue you are having?

the [curpp] tag shows rage values above 100 after a target dodges an attack. For example it will show that I have 150 rage when I really have 50 rage

### What is the expected behavior?

For [curpp] to show rage values between 0 to 100

### What actually happened?

I've noticed the rage values on my power bar show more rage than I actually have, but I couldn't pinpoint why it was causing it, but I realized that it happened after a mob dodged my attack, so I went to Stratholme to test it out as mobs they are higher dodge chances.
1. It happened instantly after my target dodged the attack
2. It doesn't seem to happen with parries or miss, not sure about blocks
3. after a few seconds the value corrects itself to the correct value (example: from 150 to 50)

Here it is happening with the rest of my addons enabled
![WoWScrnShot_040322_154342](https://user-images.githubusercontent.com/102925010/161451017-be67e6e6-5583-47e5-b2f8-d62ab03b0296.jpg)

Here it is happening with my addons disabled, I removed my [level] [class] tags for better viewing

![DodgeRageBug](https://user-images.githubusercontent.com/102925010/161451083-5381c7fc-51a9-41a4-b76d-22fd706b23cd.jpg)

### Suggested Solution/Workaround

It has something to do with dodges, so maybe start looking there? Otherwise I have no clue.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
the code here isn't specific to the addon, if this happens it would fall back to blizzard as an API bug where the api gives us the wrong data (which we can't really "fix" - short of writing some custom stuff to verify the power isn't greater than max power, but blizzard should be doing this on their end)
