### ISSUE TITLE
[Retail Bug Report] <double group finder queue>

### ISSUE THREAD

**Issue by NiltonAnyosa** [tukui-org/ElvUI#217]
### What is the issue you are having?

everytime i queue in raid / group finder the waiting option appears twice for each choose, at start was waiting for a solution on next upgrade but still ahving the same problem

here its a picture of how the bug looks like on my UI, i would like a solution if posible

![1](https://user-images.githubusercontent.com/103144130/162051920-b8af7cdb-d0ce-470a-ac75-e4fefb3d3766.png)
![2](https://user-images.githubusercontent.com/103144130/162051925-0a7c7587-6813-4db7-bed3-fcd09caa4a2c.png)

### What is the expected behavior?

just 1 queue everytime i looks for group

### What actually happened?

keeps appearing twice

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Not elvui related, it's on blizzards side
