### ISSUE TITLE
[Feature Request] Make a configurable option to flash or not flash time current time if something changed in the calendar

### ISSUE THREAD

**Issue by Rottenbeer** [tukui-org/ElvUI#224]
Hi!
My guild uses the ingame calendar to organize raids and wants to stick to this (for whatever reason).
Everytime someone updates his availability my time in the elvui bar starts flashing until I click on it and I'm kinda annoyed by this.
I see  that other people like this feature and I would like to suggest to make this configurable to have a flash effect or not.
Maybe you could also add an alternate color to pick if there's an update, I just don't want to have a flash effect.

Thanks :)

**Comment by Rottenbeer** [comment]
Thanks!

**Comment by Repooc** [comment]
np
