### ISSUE TITLE
[TBC Bug Report] Rezz Indicator missing since recent update

### ISSUE THREAD

**Issue by Blumberg1337** [tukui-org/ElvUI#23]
### What is the issue you are having?

Apparently with the union of ElvUI's different versions, the rezz indicator seems to be missing in the Classic TBC version of ElvUI. As there is no mass rezz in Classic BC yet, please add this option again. 

### What is the expected behavior?

Having party and raid Frames that show rezz indicators for ElvUI's Classic and Classic BC version.

### What actually happened?

No option to show rezz indicators.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).

**Comment by Luckyone961** [comment]
Fixed next release
