### ISSUE TITLE
[Feature Request] Echo Raid Tools Support

### ISSUE THREAD

**Issue by DaleHuntGB** [tukui-org/ElvUI#231]
**Is your feature request related to a problem? Please describe.**
Echo Raid Tools has been released and they attach their icon to the right hand side of the Adventure Guide, however, ElvUI has moved these to the bottom and are using names instead. 

![Echo Logo Issue](https://user-images.githubusercontent.com/95256492/166137961-9f63c004-0024-4224-9a6d-c96cbedac485.png)

**Describe the solution you'd like**
Just to add the Echo tab in a similar fashion to the current ones. 

**Describe alternatives you've considered**
Disabling Skinning for Blizzard frames but that is something I would rather not do, if possible.

I appreciate that this might be something that I need to go to the AddOn developer for Echo Raid Tools instead, so if that is the case, please let me know.

**Comment by Repooc** [comment]
This would type of thing we would suggest to have the addon do this as they can check if the skin is enabled or not and change where their button is located.
They can check if `ElvUI[1].private.skins.blizzard.enable` is true and `ElvUI[1].private.skins.blizzard.encounterjournal` is true to see if the ElvUI skin is enabled
