### ISSUE TITLE
[Classic Bug Report] Cancel Button does not work on Windows Client on the "Browse For Folder" Window

### ISSUE THREAD

**Issue by Eric-Dawson-Ray** [tukui-org/ElvUI#232]
### What is the issue you are having?

When I first launch the Tukui Client for windows (installed using tukui-windows-3350.zip) the "Browse For Folder" windows is spawned and when I click the cancel button the window flashes briefly and does not de-spawn. I have to kill the the Tukui Client process in Task Manager to make it go away.

### What is the expected behavior?

When you click the cancel button the "Browse For Folder" window goes away.

### What actually happened?

"The Browse For Folder" windows does not go away.

### Suggested Solution/Workaround

 kill the the Tukui Client process in Task Manager.

You might want to add Bug Reporting Support for the Clients rather than it getting "misfiled"  in addons category

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This isnt a tracker for client issues.

**Comment by Eric-Dawson-Ray** [comment]
I am aware of this as I stated in the report I made.  I was unable to find
any place to report client bugs so was hoping this would get pointed in to
correct direction by an admin or whatnot.

Cheers
