### ISSUE TITLE
[Retail Bug Report] Spells Not Showing after Update for FCT

### ISSUE THREAD

**Issue by Aavery89** [tukui-org/ElvUI#237]
### What is the issue you are having?

I recently updated FCT (Floating Combat Text) the Elvui addon and now its not showing the Holy Priest Spells Holy Word: Serenity, Heal, or Flash Heal.

### What is the expected behavior?

I would like these spells to show on the unit frame when I use them again

### What actually happened?

I just updated the addon and now they dont work

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
This is not the place to report plugin issues.  You will need to go to ElvUI_FCT GitHub page which you can find on the ftc addon page on tukui.org.
