### ISSUE TITLE
[TBC Bug Report] Raid Frame Fader

### ISSUE THREAD

**Issue by NotWarlock** [tukui-org/ElvUI#24]
### What is the issue you are having?

Raid frame/target range fader option does not work in new version 2.19

https://i.imgur.com/9MoNXvD.png

This occurs only on one character using the same profile as all others:

https://i.imgur.com/luzOi6l.png
https://i.imgur.com/A8KFwXE.jpeg

### What is the expected behavior?

Raid frames are expected to fade when out of range and be full alpha when in range

### What actually happened?

Raid frames are always faded regardless of being in range or not

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://changelogurlhere.com) and done the [Troubelshooting Steps](https://urlfortroubleshootingstepshere.com).

**Comment by Luckyone961** [comment]
Fixed in the next release
ref https://github.com/tukui-org/ElvUI/commit/546c54e9d18e886f481be68fe5e9df1faafeb6b1
