### ISSUE TITLE
[TBC Bug Report] Cast bar mana ticks not lining up correctly when wearing mage tier 6 set bonus

### ISSUE THREAD

**Issue by dewwork** [tukui-org/ElvUI#240]
### What is the issue you are having?

Castbar ticks are not adjusting properly for mage tier 6 set bonus. (2 seconds longer channel) 

### What is the expected behavior?

Ticks in the castbar should line up with the timing of mana regen from evocate.

### What actually happened?

Timing does not line up correctly when wearing mage tier 6 2 piece set bonus.

### Suggested Solution/Workaround

Increase cast time from 8s to 10s when 2p tier 6 is equiped

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
No plans in supporting gear specific stuff in classic or tbc
