### ISSUE TITLE
[TBC Bug Report] ActionBar Backdrop Multiplier Miscalculation

### ISSUE THREAD

**Issue by akaFluence** [tukui-org/ElvUI#245]
### What is the issue you are having?

When trying to setup a grid of buttons using 3 ActionBars, each in a 3 x 4 configuration, it became evident there is an issue with the Multiplier calculation as the Backdrop is longer or taller than it should be (for Width or Height, respectively).

_**Note:** this is not a new issue, it's just one I haven't been able to find a workaround for on my own, so figured it was time I reported it. I've had this issue in both the Retail version (where I use the Backgrounds option in Shadow & Light as a workaround) and now the TBC version (which isn't getting S&L as far as I can tell)._

**TBC Version:** 2.47
**Retail Version:** 12.80

![H1](https://user-images.githubusercontent.com/106152627/171971705-916262dc-6766-40ce-b477-16b9b9b8dae2.jpg)
![H2](https://user-images.githubusercontent.com/106152627/171971714-26912875-17db-4b82-b775-eb8074b1f4a9.jpg)
![H3](https://user-images.githubusercontent.com/106152627/171971716-e4ace39f-6431-499a-bfa0-7ea7894fd96e.jpg)
![H4](https://user-images.githubusercontent.com/106152627/171971721-43606b97-eb38-4d6c-bc91-a6b8e02b4fd8.jpg)
![W1](https://user-images.githubusercontent.com/106152627/171971724-3a75e1a8-cd98-45a0-a843-089795bed47c.jpg) ![W2](https://user-images.githubusercontent.com/106152627/171971726-28624c73-9586-4bab-9d22-30e091d404b3.jpg) ![W3](https://user-images.githubusercontent.com/106152627/171971728-9f7cd783-c0fd-4124-9cf6-5e3318171603.jpg) ![W4](https://user-images.githubusercontent.com/106152627/171971731-8d417280-dec5-4291-adb2-9f361b1411d8.jpg)
![WH1](https://user-images.githubusercontent.com/106152627/171971734-c3b9401a-081a-40fa-856b-ef1385d30956.jpg) ![WH2](https://user-images.githubusercontent.com/106152627/171971735-6e2059ea-e693-4671-8cf5-c1ac63b6de0a.jpg) ![WH3](https://user-images.githubusercontent.com/106152627/171971736-c707f193-3124-4f7a-ab68-b20d452bd784.jpg)

### What is the expected behavior?

The Backdrop should be as consistently spaced around the ActionBars when the Multiplier value is 3 or more, as it is for a 1 or 2 Multiplier.

### What actually happened?

Additional space is added to the Backdrop. With a little testing, the problem exists for both the Width and Height Multiplier (and when Width & Height are used together), but only when the value is 3 or more - setting the Multiplier to 1 or 2 works as intended.

### Suggested Solution/Workaround

I **_think_** the calculation (in pseudocode) should be something like:

```
ActionBarWidth = ButtonSize * ButtonsPerRow + (ButtonSpacing * (ButtonsPerRow - 1))
BackdropWidth = ActionBarWidth * BackdropWidthMultiplier + BackdropSpacing * 2

ButtonsPerColumn = ceiling(Buttons / ButtonsPerRow)
ActionBarHeight = ButtonSize * ButtonsPerColumn + (ButtonSpacing * (ButtonsPerColumn - 1))
BackdropHeight = ActionBarHeight * BackdropHeightMultiplier + BackdropSpacing * 2
```

I just have no idea how to translate that to LUA, or integrate with the current ElvUI code. If I had to guess, it would require an update to the `HandleBackdropMultiplier` function.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
that pseudocode is not really covering everything, we dont even do it that way now actually as we check to see if the multi is higher than 1 and if so we grab the current size of the backdrop frame and try to adjust the size that way.... going your route is a pain in the butt as you havent accounted for border size depending if they have thin borders enabled or disabled or if they have the "secret" 2 pixel option that is only available if they modify a value in the code, also not accounting for number of buttons shown... even then u will have an issue that we have doing it the way we are bc of pixel perfect issues as u may be off by a pixel or 2 depending on where you have your bars on the screen...

**Comment by kodewdle** [comment]
this seems like a pixel perfect issue not math issue so can't really fix closing

**Comment by kodewdle** [comment]
as work around make a DT with no DTs (just for the panel and use that as backdrop maybe?) or do it with wa or something?

**Comment by akaFluence** [comment]
I guess I'll find a workaround - WA's sound like the easiest option.

I really don't see how this is a "pixel perfect" issue, though? The discrepancy isn't present when the Multiplier is 1 (calculation is skipped) or 2 (calculation seems to be based around this), it appears on 3, is increased on 4 and increased again on 5. Is that not a calculation issue, specifically around the multiplication?

I feel like if it was a pixel perfect issue, the extra space would be inconsistent and minor (1-2 pixels maybe, as outlined by repooc). Instead, it's around 4 pixels per multiplier (as seen in the screenshots): adding " - 4", " - 8", " - 12" to the below line for the 3, 4 & 5 multiplier respectively results in the correct sizing (on a limited test case):

`local offset = ((oldWidth + buttonSpacing) * (widthMult - 1)) - backdropSpacing`
`local offset = ((oldWidth + buttonSpacing) * (widthMult - 1)) - backdropSpacing - 4`

Anyway, you made your decision. Maybe it's time I learn some LUA...

**Comment by kodewdle** [comment]
> I feel like if it was a pixel perfect issue
trust me lol

**Comment by kodewdle** [comment]
for sake of my curiosity, however try:

`local offset = (oldHeight * (heightMult - 1)) - ((E.Border * 2) * heightMult)` for **useHeightMult** section
and
`local offset = (oldWidth * (widthMult - 1)) - ((E.Border * 2) * widthMult)` for **useWidthMult** section

but anything using Point will fail to the pixel perfect problem, which is why i know this might fix it for you but will break it for others - didn't test really tho

**Comment by kodewdle** [comment]
to be more clear the problem of size relation is broken directly by `local oldWidth, oldHeight = bar.backdrop:GetSize()` itself as this data is not pixel perfect

**Comment by kodewdle** [comment]
wait - i seen something! it is still a pixel issue but there was two problems LOL

**Comment by kodewdle** [comment]
test dev, this should fix it but the pixel problem can still happen 100% in my tests it would
