### ISSUE TITLE
[Feature Request] Open Map in Foreground per default

### ISSUE THREAD

**Issue by Blumberg1337** [tukui-org/ElvUI#246]
**Is your feature request related to a problem? Please describe.**
WeakAuras overlay the map, when opened first time after loading screen.

**Describe the solution you'd like**
Map opens in foreground.

**Describe alternatives you've considered**
Putting any WeakAuras to "LOW" or "BACKGROUND" frame strata. -> Annoying... :P

**Comment by Repooc** [comment]
We don't change the FrameStrata for the world map.  Your reasoning for wanting us to alter it when we haven't all this time isn't sufficient reason to be honest.

**Comment by Blumberg1337** [comment]
@Repooc Whew, dismissing small feature requests like this...

Seems like a minor effort with a nice quality of "life" improvement (not to open the map twice every time) to me. Here is a screenshot to show the "style issue":

![image](https://user-images.githubusercontent.com/54710425/172215624-5f7dad92-e359-4f35-862d-523dbffd7e6a.png)
