### ISSUE TITLE
[Feature Request] Add Group Numbers above affiliated Group Option

### ISSUE THREAD

**Issue by Blumberg1337** [tukui-org/ElvUI#247]
**Describe the solution you'd like**
Being able to choose displaying Group Numbers above affiliated groups... "Group 1" text above group 1, etc.

**Comment by Repooc** [comment]
As it stands, that is unlikely to be added considering how the Unitframes can be sorted raid wide which will mix the groups up. You can use a tag to display the group number of the unit, which is what we direct people to do it if you are any good with weakauras, you can do something similar to what you are wanting.
