### ISSUE TITLE
[Retail Bug Report] Threads of Fate join button

### ISSUE THREAD

**Issue by Toetag1974** [tukui-org/ElvUI#249]
### What is the issue you are having?

When choosing a covenant after selecting Threads of Fate, the join button is not attached to the frame. When trying to select the button, the frame collapses.

### What is the expected behavior?

Button should be attached to frame.

### What actually happened?

Button not attached to frame, resulting in frame collapsing.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Toetag1974 this Bug was already posted into ur Discord Server. An got fixed meanwhile ago. Can u Post an Screenshot of it with /edebug on and /estatus here pls.

Thanks!

**Comment by Toetag1974** [comment]
![WoWScrnShot_062622_213716](https://user-images.githubusercontent.com/74637048/175850614-881f0b08-a478-420d-9bf0-39a1277aa2b8.jpg)
![WoWScrnShot_062622_213720](https://user-images.githubusercontent.com/74637048/175850626-bc7b72a0-881d-4626-a5b0-c9d1c025ac8d.jpg)
![WoWScrnShot_062622_213814](https://user-images.githubusercontent.com/74637048/175850643-5004611d-bfa8-43e7-bb45-165dd92de637.jpg)
![WoWScrnShot_062622_213818](https://user-images.githubusercontent.com/74637048/175850649-c557189c-36ed-490f-84a4-2fe6e1ff14a7.jpg)
In the first screenshot, you can see the cursor on the Kyrian box. When moving the cursor down to the join button, the button disappears(screenshot 2). In the 3rd and 4th pictures, Elvui has been disabled, allowing selection.
