### ISSUE TITLE
[Retail Bug Report] autocompletion no longer includes realm name

### ISSUE THREAD

**Issue by Exupery** [tukui-org/ElvUI#250]
### What is the issue you are having?

Presumably related to the new `AUTO_COMPLETE_RECENT_PLAYER` flag introduced in `9.2.5` autocompletion (e.g. when typing `/ignore`) no longer includes the realm name and will now only suggest the relevant player name(s). This was observed in ElvUI version `12.80`.

Confirmed this is an ElvUI issue and not a WoW regression by disabling ElvUI and confirmed autocompletion was again including realm names. (i.e. as ElvUI did prior to `9.2.5`).

See also https://wowpedia.fandom.com/wiki/Patch_9.2.5/API_changes

### What is the expected behavior?

When typing `/ignore` it should suggest/autocomplete the names, including realms for characters on a different realm, of party members and/or nearby characters.

### What actually happened?

Names are still suggested as autocomplete options (via tab to cycle through multiple matches if applicable) but realms are no longer included for those characters not on the player's own realm.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Merathilis** [comment]
https://i.imgur.com/LqpTNqN.gif

^ I dont see anything wrong here. Tested with only ElvUI dev. version.

**Comment by Exupery** [comment]
Interesting, when I switched to a character on a different realm I'm unable to reproduce this (even when trying with all my other addons enabled), it's only an issue on the characters on my main realm. So must be a (mis)configuration of some sort on my end. Closing this since it's apparently not a bug.
