### ISSUE TITLE
Nameplate clickable size

### ISSUE THREAD

**Issue by JJay1** [tukui-org/ElvUI#251]
### What is the issue you are having?

Occasionally, the clickable boxes of nameplates grow abnormally upward regardless of the clickable size in the Elv UI settings.

### What is the expected behavior?

The clickable box should be the same size above and below the nameplate.

### What actually happened?

Don't know what triggers this, but sometimes logging into a character I can see the problem. What I've found is that going into interface settings in the game menu and exiting makes it back to normal.

### Suggested Solution/Workaround

Links to related videos are attached. Blizz mouse cursor is not visible because it is a recorded video. [https://youtu.be/xVQ3yro76IY](https://youtu.be/xVQ3yro76IY)

### Errors

```shell
No errors.
```

### ElvUI Changelog/Troubleshooting

- [x] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Merathilis** [comment]
If this is still an issue for you, please report back and feel free to reopen the issue
