### ISSUE TITLE
Major stuttering with WeakAuras

### ISSUE THREAD

**Issue by Luthaniel** [tukui-org/ElvUI#252]
### What is the issue you are having?

I am using WeakAuras with ElvUi. The issue is that the game stutters / causes my entire system to stutter.

The issue appears when three things a true:

    1. WeakAuras is on
    2. ElvUi is on
    3. I have two instances of WoW running, and logged in game (as opposed to character select).

Upon these things being true, the stutter persists until I exit out of WoW on one of the characters (sometimes I need to exit out on both). The stutter persists even if I disable both WeakAuras and ElvUi in game after loading in on both characters.

When either ElvUi is disabled, or WeakAuras is disabled upon log in I do not experience the stutter.

The stutter caused is a system wide stutter i.e. if I alt tab to browser, the browser will stutter.

The stutter occurs at a consistent interval (for every 1 second of stutter, I will have 1 second of smooth operation).

The stutter occurs regardless of whether the particular character has any WeakAuras loaded.

### What is the expected behavior?

No stuttering. 

### What actually happened?

Stuttering - see above. 

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Luthaniel i got also two Accounts didn't got this Problem. I think it's ur System or corrupted ElvUI Profile or a Weakaura.
