### ISSUE TITLE
[Retail Bug Report] Inherhit Global Fade Mouseover

### ISSUE THREAD

**Issue by RAtwood90** [tukui-org/ElvUI#254]
### What is the issue you are having?

Explanation on Imgur.

https://imgur.com/a/ioKB7JG

### What is the expected behavior?

Mouseover shouldn't be working there cause Box is unchecked.

### What actually happened?

Mouseover is working with Inherhit Global Fade without a checked Mouseover Box.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
I am not sure what you are saying you are having issues with. If you inherit global fade enabled on a bar and have the inherit global fade transparency set to be 100 invisible or any % so the bar is hidden or barely seen, the bar will show upon mouse over. The separate mouse over option I should prob disable it if u have inherit global fade enabled on the bar bc the inherit global fade option is priority and shouldn't be doing anything.
Inherit global fade option makes it so the bar will show upon mouse over, selecting a target, and getting into combat (off top of my head, don't think any other triggers are part of that option besides those)

**Comment by RAtwood90** [comment]
> I am not sure what you are saying you are having issues with. If you inherit global fade enabled on a bar and have the inherit global fade transparency set to be 100 invisible or any % so the bar is hidden or barely seen, the bar will show upon mouse over. The separate mouse over option I should prob disable it if u have inherit global fade enabled on the bar bc the inherit global fade option is priority and shouldn't be doing anything. Inherit global fade option makes it so the bar will show upon mouse over, selecting a target, and getting into combat (off top of my head, don't think any other triggers are part of that option besides those)

Yeah, u understood it right. The Checkbox for Mouseover shouldn't be there then like u said a little bit confusing. Cause also in the Tooltip of Inherhit Global Fade there is no Word of Mouseover here.

What's why Tsyx and Me thought it's bugged i guess.

Then i have to change my Visibility Settings to get that i want to have. 

Instead of using ur Plugin with Inherhit Globale Fade.

Cause i want no Mouseover for my 1st Actionbar like i have now.

And with the stayed Checkbox i thought it's a Bug would get be fixed and the Mouseover is gone.

But sadly like i read it's not :/ cause there is no Option to seperat disable the Mouseover think with Inherhit Globale Fade but may a Checkbox for your Plugin?

**Comment by Repooc** [comment]
my plugin only makes it so that if u have inherit global fade, u can remove some of the triggers that inherit global fade does.  What i am going to try to do is make it an option so you can disable the mouseover trigger for inherit global fade.  not sure if that is what you are looking for but i can ping u in discord to take a look when i add it and see if it is what you want.
