### ISSUE TITLE
[Retail Bug Report] Tooltip and objectives anchors are misbehaving.

### ISSUE THREAD

**Issue by Warlockly** [tukui-org/ElvUI#257]
### What is the issue you are having?

I logged on today, and my tooltip moved itself to it's original location, and I cannot move it, or do anything to move it. I tried just moving it's location within the Toggle Anchors menu, and it jumps back to it's original location. I also tried toggling on the attach to cursor, and that doesn't move it either. I turned the setting for ElvUI Tooltip off, still had the issue when I turned it back on. I've done everything, bar uninstalling the entire mod and reinstalling it. 
Also, at the same time, the anchor for my objectives window has completely vanished. I have no way to interact with that window at all, to move it or change it's size. 

### What is the expected behavior?

I should be able to move it with no issue. I should also be able to see my objectives anchor so I can move that and change it's size. 

### What actually happened?

Explained above. Anchor for objectives is gone, and I cannot move my tooltip anchor anywhere as it moves itself back to the original location instantly. 

### Suggested Solution/Workaround

I've tried everything and have no more ideas. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Warlockly 

Troubleshooting Steps (ElvUI)
Do these steps in order.
1) Type in chat in game /edebug on
2) Test - Do you still have the issue?
3) If you still have the issue/error - type in chat in game /estatus
4) Upload a full, uncropped screenshot showing the issue and the estatus.
5) If you are finished with debugging, you can enable your AddOns back with: /edebug off
