### ISSUE TITLE
Yellow quest progress text disappears with "Hide Error Text" setting

### ISSUE THREAD

**Issue by JVemmer** [tukui-org/ElvUI#259]
### What is the issue you are having?

Enabling the "Hide Error Text" setting under General -> BlizzUI Improvements, also hides the yellow quest progress text, such as "Killed <mob> 1/10", while in combat. The description for the setting is "Hides the red error text at the top of the screen while in combat", but this seemingly applies to the yellow quest progress text as well. It seems ElvUI hides the entire `UIErrorsFrame`, instead of filtering out the "red text" messages.

### What is the expected behavior?

I expect that the setting hides the red error text, but leaves the yellow quest progress text alone, since that is what the tooltip states.

### What actually happened?

All text was hidden, not just the red error text.

### Suggested Solution/Workaround

Looking at the code itself (ElvUI/Core/Modules/Misc/Misc.lua)
```lua
function M:ErrorFrameToggle(event)
	if not E.db.general.hideErrorFrame then return end
	if event == 'PLAYER_REGEN_DISABLED' then
		_G.UIErrorsFrame:UnregisterEvent('UI_ERROR_MESSAGE')
	else
		_G.UIErrorsFrame:RegisterEvent('UI_ERROR_MESSAGE')
	end
end
```

It should hide only the errors, so the problem is likely on Blizzard's end (them sending quest progress text via the UI_ERROR_MESSAGE channel). One workaround could be a list of all actual error messages, by their type, and then filter any message coming in, through that list. That is the approach that the [xanErrorDevourer](https://github.com/Xruptor/xanErrorDevourer) addon uses for instance.

### Errors

```shell
No errors are shown.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Toxicreaction** [comment]
This also exists in Classic TBC as well. I know the label shows it as retail. Could we also add classic to it?

**Comment by kodewdle** [comment]
this isn't something we can really adjust and keeping a list of the errors or quests just isn't sane for the base elvui.  for that reason we decide to just clarify this also includes the Quest Progression text.
