### ISSUE TITLE
[TBC Bug Report] ClassBar not showing

### ISSUE THREAD

**Issue by Andromni** [tukui-org/ElvUI#26]
### What is the issue you are having?

On recent update to 2.19 the ClassBar stopped showing as part of the player Unitframe. I attempted to detach it, and it still is not showing.

### What is the expected behavior?

ClassBar should show and give combo point details.

### What actually happened?

Upgraded to newest ELVUI and lost ability to see combo points tracking

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Repooc** [comment]
fixed in dev
