### ISSUE TITLE
[Retail Bug Report] Item Quality Colour in Bags

### ISSUE THREAD

**Issue by TotalControl123** [tukui-org/ElvUI#260]
### What is the issue you are having?

The coloured border of item quality from the option "show quality colour" does not always appear to function on loading or reloading, however moving or placing items in the bag can cause a refresh.

### What is the expected behavior?

A coloured border showing item quality

### What actually happened?

No border appears, as if option in settings is turned off

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This is due to Auction House Scanning. It forces some item cache out.
