### ISSUE TITLE
[Retail Bug Report] Error when trying to start groups

### ISSUE THREAD

**Issue by pimcha17** [tukui-org/ElvUI#261]
### What is the issue you are having?

Whenever I try to start a group for a group quest I get [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'CreateListing()'.
[ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.

### What is the expected behavior?

It should create a group for the quest that I'm trying to do

### What actually happened?

Group didnt form and I had to manually type in the quest name

### Errors

```shell
[ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'CreateListing()'.
[ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
Troubleshooting Steps (ElvUI)
Do these steps in order.
1) Type in chat in game /edebug on
2) Test - Do you still have the issue?
3) If you still have the issue/error - type in chat in game /estatus
4) Upload a full, uncropped screenshot showing the issue and the estatus.
5) If you are finished with debugging, you can enable your AddOns back with: /edebug off

**Comment by pimcha17** [comment]
![WoWScrnShot_071522_184917](https://user-images.githubusercontent.com/109215883/179327788-981d45e3-bf64-49b5-9f12-bb430f53411a.jpg)

Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'CreateListing()'.
Time: Fri Jul 15 18:47:46 2022
Count: 1
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'CreateListing()'.
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...vUI\Libraries\Core\Ace\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `CreateListing'
[string "@Interface\FrameXML\LFGList.lua"]:1055: in function `LFGListEntryCreation_ListGroupInternal'
[string "@Interface\FrameXML\LFGList.lua"]:1117: in function `LFGListEntryCreation_CheckAutoCreate'
[string "@Interface\FrameXML\LFGList.lua"]:658: in function `LFGListEntryCreation_Show'
[string "@Interface\FrameXML\LFGList.lua"]:2107: in function <Interface\FrameXML\LFGList.lua:2104>

Locals: <none>

**Comment by RAtwood90** [comment]
Thank u! Viable Bug then Devs will take a look into it i guess!

**Comment by devil81** [comment]
i get this so many times aswell , special when in group its crossfaction party group

**Comment by kodewdle** [comment]
thanks, i will try to look into these soon if i can reproduce them.. generally these happen under specific cases (but it's often when you do the same things).  can you do a `/reload` and figure out what triggers this like for example:

1. reload
2. open quest log
3. mouse over item
4. create group
5. error shows up

i need the steps to make it happen, the smaller (and specific) this is. will save me time trying to figure out what causes the issue.
i know there is also one with doing world quests... i forgot but it's something like shift+click a world quest taint errors something (not during but later, like when you do a group thing)

**Comment by pimcha17** [comment]
so I just click on the world quest on the map
click the eye in the objective frame for the world quest I selected
click start my own group
most of the time that error appears

also Idk if this helps, but usually it happens when there are no other groups listed. and sometimes doing a /reload fixes it temporarily but not always

**Comment by Azilroka** [comment]
Pretty sure this is still tainting in the default ui as well

**Comment by RAtwood90** [comment]
> Pretty sure this is still tainting in the default ui as well

Azilroka i tested it both Ways and the Bug still exist. Not for the Default UI only for the ElvUI.

Look at this:


https://user-images.githubusercontent.com/73589071/204277430-6374b308-3c75-4b6d-b30c-52c4e1182453.mp4


https://user-images.githubusercontent.com/73589071/204277476-1a1c9066-bd13-4b35-89b8-04277e2d3804.mp4

**Comment by RAtwood90** [comment]
It's an known Issue Simpy said no Fix for it at the Moment.
