### ISSUE TITLE
[Wrath Beta Bug Report] Initial Findings (including solution to crash)

### ISSUE THREAD

**Issue by Pixolsc2** [tukui-org/ElvUI#262]
### What is the issue you are having?

Just posting some initial findings on how to get ElvUI running on Wrath Beta...

### ElvUI not showing under Addon List
Easiest solution is to remove "_TBC" from the .toc file names.

Rename these:
`Interface\AddOns\ElvUI\ElvUI_TBC.toc`
`Interface\AddOns\ElvUI_OptionsUI\ElvUI_OptionsUI_TBC.toc`

to:
`Interface\AddOns\ElvUI\ElvUI.toc`
`Interface\AddOns\ElvUI_OptionsUI\ElvUI_OptionsUI.toc`

### Crashing during Loading Screen
This is the line that crashes your Wrath Beta during the loading screen:
RegisterCVar('fstack_showhighlight', '1') `ElvUI\Core\init.lua`

This was verified by crashing the game with:
`/run RegisterCVar('fstack_showhighlight', '1')`

Just comment the line out in the file and you should be good to go.

Here are some variable outputs on Wrath Beta currently:
```
Dump: WOW_PROJECT_MAINLINE
WOW_PROJECT_MAINLINE=1

Dump: WOW_PROJECT_CLASSIC
WOW_PROJECT_CLASSIC=2

Dump: WOW_PROJECT_BURNING_CRUSADE_CLASSIC
WOW_PROJECT_BURNING_CRUSADE_CLASSIC=5

Dump: WOW_PROJECT_ID
WOW_PROJECT_ID=5

Dump: value=GetBuildInfo()
[1]="3.4.0",
[2]="44644",
[3]="Jul 12 2022",
[4]=30400
```
Currently there is no WOW_PROJECT_WRATH_CLASSIC (or whatever it's going to be named) variable that I could find with ViragDevTool `find WOW_PROJECT`.

### LUA Errors (Variables no longer exist/renamed)

- MiniMapLFGFrame exists but MiniMapLFGBorder does not exist `ElvUI\Core\Modules\Maps\Minimap.lua`

- QuestWatchFrame does not exist (best guess: WatchFrame) `ElvUI\Core\Modules\Blizzard\QuestWatch.lua`

- QuestTimerFrame does not exist `ElvUI\Core\Modules\Blizzard\QuestWatch.lua`

- QuestWatch_Update does not exist (best guess: WatchFrame_OnUpdate) `ElvUI\Core\Modules\Blizzard\Blizzard.lua`

- BattlefieldListScrollFrame does not exist (BG UI changed) `ElvUI\TBC\Modules\Skins\Battlefield.lua`

- BattlefieldListScrollFrameScrollBar does not exist (BG UI changed) `ElvUI\TBC\Modules\Skins\Battlefield.lua`

- BattlefieldFrameZoneDescription does not exist (BG UI changed) `ElvUI\TBC\Modules\Skins\Battlefield.lua`

- GearManagerToggleButton exists but GearManagerToggleButtonIconTexture does not exist (it is one of PaperDollItemsFrame's children) `ElvUI\TBC\Modules\Skins\Character.lua`

- _G['ReputationBar'..i].SetStatusBarTexture does not exist (best guess: _G['ReputationBar'..i..'ReputationBar'].SetStatusBarTexture) `ElvUI\TBC\Modules\Skins\Character.lua`

- _G['ReputationHeader'..i] does not exist (Rep UI changed) `ElvUI\TBC\Modules\Skins\Character.lua`

- _G['ReputationBar'..i..'AtWarCheck'] does not exist (Rep UI changed) `ElvUI\TBC\Modules\Skins\Character.lua`

- QuestFrameExitButton does not exist `ElvUI\TBC\Modules\Skins\Quest.lua`

- QuestLogTimerText does not exist `ElvUI\TBC\Modules\Skins\Quest.lua`

- QuestLogCollapseAllButton does not exist `ElvUI\TBC\Modules\Skins\Quest.lua`

- Lots of LFG things don't exist (LFG UI Changed) `ElvUI\TBC\Modules\Skins\LFG.lua`

I just commented out references to these variables (or made the replacement variable names) to get ElvUI running without LUA errors. It's not a fix, but lets me play the beta with a functioning ElvUI.

### What is the expected behavior?

N/A

### What actually happened?

N/A

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
We still dont have beta access and no we dont rename any files or toc's.
Project ID stuff was patched ~2 days ago and RegisterCVar is only for Classic+TBC.
More temporary skin stuff related to your report https://github.com/tukui-org/ElvUI/commit/f35149d4dd92040ada5bdcd264457a8a497ec1a7
