### ISSUE TITLE
Guild Interface Bug

### ISSUE THREAD

**Issue by mltco78dhs** [tukui-org/ElvUI#263]
### What is the issue you are having?

From the Guild Roster tab in the guild interface, active the drop down menu for an individual player and this error showed up.

256x SharedXML\UIDropDownMenu.lua:1345: attempt to index field '?' (a nil value)
[string "@SharedXML\UIDropDownMenu.lua"]:1345: in function `UIDropDownMenu_EnableButton'
[string "@FrameXML\UnitPopupShared.lua"]:257: in function `OnUpdate'
[string "@FrameXML\UnitPopupShared.lua"]:283: in function `UnitPopup_OnUpdate'
[string "*:OnUpdate"]:3: in function <[string "*:OnUpdate"]:1>

Locals:
level = 1
id = 15
(*temporary) = nil
(*temporary) = nil
(*temporary) = "1"
(*temporary) = "Button"
(*temporary) = "15"
(*temporary) = "attempt to index field '?' (a nil value)"

### What is the expected behavior?

Not to get the error.

### What actually happened?

Exactly as in "What is the issue you are having?"

### Suggested Solution/Workaround

I have no clue as to the specific code that's in error as ElvUI is a massively complex addon.

### Errors

```shell
256x SharedXML\UIDropDownMenu.lua:1345: attempt to index field '?' (a nil value)
[string "@SharedXML\UIDropDownMenu.lua"]:1345: in function `UIDropDownMenu_EnableButton'
[string "@FrameXML\UnitPopupShared.lua"]:257: in function `OnUpdate'
[string "@FrameXML\UnitPopupShared.lua"]:283: in function `UnitPopup_OnUpdate'
[string "*:OnUpdate"]:3: in function <[string "*:OnUpdate"]:1>

Locals:
level = 1
id = 15
(*temporary) = nil
(*temporary) = nil
(*temporary) = "1"
(*temporary) = "Button"
(*temporary) = "15"
(*temporary) = "attempt to index field '?' (a nil value)"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by mltco78dhs** [comment]
Regarding disablilng everything, I left BugSack and BugGrabber turned on to capture the error in the run where I provided the error report, but an error still occurred with them turned off.

**Comment by Azilroka** [comment]
You can also get this bug without ElvUI.
