### ISSUE TITLE
[Retail Bug Report] XP databar does not hide automatically on trial accounts at level 20

### ISSUE THREAD

**Issue by cheeseman1** [tukui-org/ElvUI#264]
### What is the issue you are having?

For trial accounts (free to play), the maximum level is 20. However, the XP data bar does not hide when reached. It does appear to correctly hide if experience gain is disabled though:
/run print("Experience gain is "..(IsXPUserDisabled()and"disabled."or"enabled."))

Related to #20 which added a check for XPGainDisabled.

### What is the expected behavior?

When a veteran trial account hits level 20 and the "hide when max level" box is checked, the XP databar should automatically hide. In principle this could also be the "correct" behavior for all restricted accounts but non-veteran trial characters do still bank experience and will level up on first log in after the account in converted to pay-to-play [IsRestrictedAccount() vs IsVeteranTrialAccount() vs IsTrialAccount()].

### What actually happened?

No change. The XP data bar remains visible despite being unable to gain additional experience as the character has reached the maximum trial account level.

### Suggested Solution/Workaround

Add additional check with GetRestrictedAccountData() or IsVeteranTrialAccount() to determine the level cap for a given character. Then hide the XP databar if:
Hide At Max Level Box is true
AND
(Character is at the max level, for veteran trial accounts or normal accounts OR XPGainDisabled is true)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
thanks, seems we missed that api :)
