### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by jph290** [tukui-org/ElvUI#267]
### What is the issue you are having?

While in battle Swatter caught this error.  I was not in a party at the time as well.

### What is the expected behavior?

Not calling the Hide() function while in combat.  Looks like one of the things that blizz added a few years ago to inaccessible items while in combat.

### What actually happened?

I was not in a party at the time as well.

### Errors

```shell
Date: 2022-07-19 21:30:07
ID: 2
Error occured in: AddOn: ElvUI
Count: 1
Message: Note: AddOn ElvUI attempted to call a protected function (PartyMemberFrame1:Hide()) during combat lockdown.
Debug:
   [string "=[C]"]: Hide()
   [string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1272:
      ...\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua:1262
   [string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1348: DisableBlizzard()
   [string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1185: UpdateAllHeaders()
   [string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:966: HandleSmartVisibility()
   [string "@ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:971: ?()
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [string "=[C]"]: ?
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119
Locals:
None
AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  WowheadLooter, v90205
  ACP, v3.5.7 
  AddonFactory, v9.2.001
  Altoholic, v9.2.004
  AngryKeystones, v
  ArkInventory, v30967
  ArkInventoryRules, v30967
  ArkInventoryRulesExample, v3.09.67
  ArkInventorySearch, v30967
  AskMrRobot, v112
  Auctioneer, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.3 (OneMawTime)
  AutoLog, vv9.1.0.0
  BattlePetBreedID, vv1.20.2
  BlizzMove, vv3.4.2
  ClassicQuestLog, v2.1.0
  DataStore, v2022.06.05
  DataStoreAchievements, v9.2.004
  DataStoreAgenda, v9.2.004
  DataStoreAuctions, v9.2.004
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v9.2.004
  DataStoreCrafts, v9.2.004
  DataStoreCurrencies, v9.2.004
  DataStoreGarrisons, v9.2.004
  DataStoreInventory, v9.2.004
  DataStoreMails, v2022.06.05
  DataStorePets, v9.2.004
  DataStoreQuests, v9.2.004
  DataStoreReputations, v9.2.004
  DataStoreSpells, v2022.06.05
  DataStoreStats, v9.2.004
  DataStoreTalents, v9.2.004
  DBMCore, vd99d605
  DBMStatusBarTimers, vd99d605
  DBMVPVEM, v8131fe3
  Details, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v12.81
  ElvUIActionBarPanels, v3.3
  ElvUIEnhanced, v4.0.16
  ElvUIExtraDataTexts, v2.1.6
  ElvUILocPlus, v2.64
  ElvUISystemDatatext, v3.0.10-retail
  ElvUITB, v1.16
  GatherMate2, v1.47.2
  GatherMateSharing, vv1.14
  GTFO, v4.67
  GuildMemberStatus, v1.34
  HandyNotes, vv1.6.6
  HandyNotesBattleForAzerothTreasures, vv25
  HandyNotesOribos, vv17
  HandyNotesShadowlands, v47
  HandyNotesShadowlandsTreasures, vv68
  HandyNotesStygia, vv90200.0
  HigherHotKey, v1.0.8
  InFlightLoad, v9.2.0
  Mapster, v1.9.7
  ModelPique, v9.2.0.0 Release
  MoveAnything, v18.0.8
  OPie, vXe 6
  Paste, v1.4.10
  PetTracker, v9.2.0
  PetTrackerJournal, v
  Postal, vv3.8.1
  Rematch, v4.11.24
  RematchElvUISkin, v1.2.7
  Simulationcraft, v9.2.5
  SlideBar, v9.1.BETA.5.3 (OneMawTime)
  Stubby, v9.1.BETA.5.3 (OneMawTime)
  TomCats, v2.4.12
  TomTom, vv3.0.7
  TradeSkillMaster, vv4.11.32
  TradeSkillMasterAppHelper, vv4.0.21
  WeakAuras, v4.0.2
  WeakAurasCompanion, v1.1.0
  WorldQuestTab, v9.0.08.2
  BlizRuntimeLib_enUS v9.2.5.90205 <none>
  (ck=933)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@jph290 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

In my Eyes Invalid Ticket no Title seems like u didn't even have done with Steps before.

Also:

AddOns:
  Swatter, v9.1.BETA.5.3 (OneMawTime)
  WowheadLooter, v90205
  ACP, v3.5.7 
  AddonFactory, v9.2.001
  Altoholic, v9.2.004
  AngryKeystones, v
  ArkInventory, v30967
  ArkInventoryRules, v30967
  ArkInventoryRulesExample, v3.09.67
  ArkInventorySearch, v30967
  AskMrRobot, v112
  Auctioneer, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.3 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.3 (OneMawTime)
  AutoLog, vv9.1.0.0
  BattlePetBreedID, vv1.20.2
  BlizzMove, vv3.4.2
  ClassicQuestLog, v2.1.0
  DataStore, v2022.06.05
  DataStoreAchievements, v9.2.004
  DataStoreAgenda, v9.2.004
  DataStoreAuctions, v9.2.004
  DataStoreCharacters, v2022.06.05
  DataStoreContainers, v9.2.004
  DataStoreCrafts, v9.2.004
  DataStoreCurrencies, v9.2.004
  DataStoreGarrisons, v9.2.004
  DataStoreInventory, v9.2.004
  DataStoreMails, v2022.06.05
  DataStorePets, v9.2.004
  DataStoreQuests, v9.2.004
  DataStoreReputations, v9.2.004
  DataStoreSpells, v2022.06.05
  DataStoreStats, v9.2.004
  DataStoreTalents, v9.2.004
  DBMCore, vd99d605
  DBMStatusBarTimers, vd99d605
  DBMVPVEM, v8131fe3
  Details, v
  DetailsDeathGraphs, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  ElvUI, v12.81
  ElvUIActionBarPanels, v3.3
  ElvUIEnhanced, v4.0.16
  ElvUIExtraDataTexts, v2.1.6
  ElvUILocPlus, v2.64
  ElvUISystemDatatext, v3.0.10-retail
  ElvUITB, v1.16
  GatherMate2, v1.47.2
  GatherMateSharing, vv1.14
  GTFO, v4.67
  GuildMemberStatus, v1.34
  HandyNotes, vv1.6.6
  HandyNotesBattleForAzerothTreasures, vv25
  HandyNotesOribos, vv17
  HandyNotesShadowlands, v47
  HandyNotesShadowlandsTreasures, vv68
  HandyNotesStygia, vv90200.0
  HigherHotKey, v1.0.8
  InFlightLoad, v9.2.0
  Mapster, v1.9.7
  ModelPique, v9.2.0.0 Release
  MoveAnything, v18.0.8
  OPie, vXe 6
  Paste, v1.4.10
  PetTracker, v9.2.0
  PetTrackerJournal, v
  Postal, vv3.8.1
  Rematch, v4.11.24
  RematchElvUISkin, v1.2.7
  Simulationcraft, v9.2.5
  SlideBar, v9.1.BETA.5.3 (OneMawTime)
  Stubby, v9.1.BETA.5.3 (OneMawTime)
  TomCats, v2.4.12
  TomTom, vv3.0.7
  TradeSkillMaster, vv4.11.32
  TradeSkillMasterAppHelper, vv4.0.21
  WeakAuras, v4.0.2
  WeakAurasCompanion, v1.1.0
  WorldQuestTab, v9.0.08.2
  BlizRuntimeLib_enUS v9.2.5.90205 <none>
  (ck=933)

???

**Comment by jph290** [comment]
@RAtwood90 the reports I have been receiving require swatter.  I have done the estatus stuff.  I am a programmer and the likelyhood that this particular issues being due to an addon seems unlikely.  Did you even look at it or just close it because the debugging environment was not to your liking?

**Comment by Repooc** [comment]
> ```shell
> HandyNotes, vv1.6.6
>   HandyNotesBa
> ```

RAtwood doesnt have the ability to close/open tickets.  Simpy aka kodewdle did and yes you need to do the troubleshooting steps as an addon can cause that issue and to rule out other addons, we have the troubleshooting steps there for that reason.
