### ISSUE TITLE
Can't add custom font to ElvUI with 12.46 update

### ISSUE THREAD

**Issue by cygnius0** [tukui-org/ElvUI#27]
### What is the issue you are having?

I updated ElvUI from 12.44 to 12.46 today and found that I can no longer use the Pepsi font that I've been using for Combat text or any other text in the game:
![elvui bug](https://user-images.githubusercontent.com/53566835/140191984-0ff05c5c-f98e-4f2e-aeaf-bbef9e3dbd87.png)

I first checked that `SharedMedia.lua` was correctly updated to include the addition of `Pepsi.ttf` which it was:
![image](https://user-images.githubusercontent.com/53566835/140192084-1d2eaa3e-1b43-4fa3-8793-fccd043ff36e.png)

I then tried restarting the game multiple times, deleting `AddMedia('font','Pepsi.ttf',				'Pepsi')` and starting the game without it, then adding it back to no avail. I still can't add the font to the game

### What is the expected behavior?

The expected behaviour is that I can select Pepsi from the menu and then the game uses that font for combat text

### What actually happened?

I can't select Pepsi from the menu as ElvUI doesn't pick it up for some reason

### Suggested Solution/Workaround

I don't really have an idea, but since it worked in 12.44 something must've broken it in 12.46.

### Errors

```shell
N/A
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Repooc** [comment]
We don't support modifying elvui files, even when doing this and point people to use SharedMedia addon to add ur custom fonts and such... you can even use this as an example https://www.tukui.org/forum/viewtopic.php?f=20&t=1

**Comment by cygnius0** [comment]
This guide is outdated

**Comment by cygnius0** [comment]
I thought you were linking another article I found which was outdated. I'll check this out. Thanks
