### ISSUE TITLE
[TBC Bug Report] AuraIndicator(Class) Warlock Unending Breath has wrong SpellID

### ISSUE THREAD

**Issue by StonnyGH** [tukui-org/ElvUI#280]
### What is the issue you are having?

The Aura Indicator(Class) for Warlocks has the wrong SpellID for the Buff Unending Breath. **5597** instead of **5697**.

### What is the expected behavior?

The Aura Indicator(Class) for Warlocks should show the Buff Unending Breath (SpellID: **5697**).

### What actually happened?

The Aura Indicator(Class) for Warlocks shows the Buff Serious Wound (SpellID: **5597*) which can't be cast by Warlocks.

### Suggested Solution/Workaround

It looks like its just a Typo. Change SpellID from **5597** to **5697**.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
The spell ID is `5697` already and this line of code is unchanged since October 16th, 2021
