### ISSUE TITLE
[TBC Bug Report] Quest Icon button does nothing (under bags options)

### ISSUE THREAD

**Issue by blzrkr** [tukui-org/ElvUI#286]
### What is the issue you are having?

When I check or uncheck the quest icon button under settings > bags, nothing happens. Tested with /edebug on still nothing.

### What is the expected behavior?

When you tick the quest icon button under settings > bags, your quest items in the bag should have a yellow quest exclamation mark or some outline or something to indicate this item belongs to a quest.

### What actually happened?

Nothing happens when you check or un check the quest icon button

![image](https://user-images.githubusercontent.com/89321505/183393997-55301acc-fb41-4a47-94cf-bb4e96705344.png)

![image](https://user-images.githubusercontent.com/89321505/183394165-3286aec0-c960-48e5-b4e3-f32e72eccdde.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@blzrkr 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

Also do a /rl everytime u change a Setting sometimes that Helps.

**Comment by Azilroka** [comment]
The Quest Icon option is just for Quest Starters. I'll correct the text.
