### ISSUE TITLE
[TBC Bug Report] No interrupt announce since the last update

### ISSUE THREAD

**Issue by Moonzen** [tukui-org/ElvUI#29]
### What is the issue you are having?

No interrupt announce since the last update (2.19).
Previously, interrupt were announced in /say.
Since the update, nothing (at least in /say, didn't test the others).
In the settings, the announces are selected to be done on "Say".

### What is the expected behavior?

Interrupts should be announced via the selected channel in the settings (/say in my case).

### What actually happened?

No announce at all when i interrupt something in raid / group, even if i change the channel (tried yell and party/raid).

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Moonzen** [comment]
Re-opening this since it is still broken (using 2.21).

**Comment by Repooc** [comment]
fixed in dev
