### ISSUE TITLE
[TBC Bug Report] Chat font size increases when opening CopyChatFrame

### ISSUE THREAD

**Issue by ColeSchaefer** [tukui-org/ElvUI#291]
### What is the issue you are having?

When opening the CopyChatFrame, if your font size is below 12pt, it will be increased up to 12pt. If you have a font size set above 12pt, nothing changes.

### What is the expected behavior?

Chat font size should remain at the user-specified font size when opening the CopyChatFrame.

### What actually happened?

Chat font size is increased to 12pt. when opening the CopyChatFrame, if the current tab's font is set to below 12pt.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Think it's fixed unless simpy has a reason for it
