### ISSUE TITLE
[Wrath Bug Report] totem rightclick doesn't work

### ISSUE THREAD

**Issue by hypongithub** [tukui-org/ElvUI#292]
### What is the issue you are having?

hi, when right clicking on a totem to dismiss it, the totem is placed again instead. impossible to recall a single totem

### What is the expected behavior?

right clicking a totem should destroy it

### What actually happened?

when right clicking on a totem to dismiss it, the totem is placed again instead. impossible to recall a single totem

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
As far as I know we aren't doing tickets about Wrath.

However, I did look into it. Blizzard doesn't have that ability on this totem bar that they introduced for Wrath Classic. So technically it isn't a bug.

**Comment by hypongithub** [comment]
got it, thanks. however the right click works when elvui is disabled.

**Comment by Azilroka** [comment]
right click on which bar?

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/185806897-b0d65611-c23b-4d67-816e-cc2b56ab3e80.png)

The one at the unitframe or the bar at the bottom?
