### ISSUE TITLE
[Feature Request] add timers to totems

### ISSUE THREAD

**Issue by hypongithub** [tukui-org/ElvUI#293]
**Describe the solution you'd like**
It would be good to have totems show the remaining time. that feature works in tbc classic

![image](https://user-images.githubusercontent.com/111681793/185785060-1d4790bf-3258-4d76-a65b-b8fee26ac58d.png)

**Comment by Repooc** [comment]
wrath totem timers are shown via the classbar (either on the player unitframe or the target nameplate) as the totem bar shows the timer that blizzard shows which is the cd timer before u are able to cast that particular totem again.
