### ISSUE TITLE
[Feature Request] make classbar right-clickable

### ISSUE THREAD

**Issue by hypongithub** [tukui-org/ElvUI#294]
**Is your feature request related to a problem? Please describe.**
Sorry, I expressed it wrongly in the previous post. On the standard interface, under the portrait there is an icon for each totem that can be right clicked to dismiss only one totem, without having to use totemic recall. the classbar implemented in elvui cannot be right clicked and as a result, single totems cannot be dismissed. 

**Describe the solution you'd like**
please make the shamans class bar be right clickable. since the new blizzard ui totem bar frame can't be right clicked, it would be good to have something to right click to dismiss one single totem.

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >

**Additional context**
thanks

![image](https://user-images.githubusercontent.com/111681793/185805292-35bf253e-8707-4b95-99a5-da0033dd407b.png)

**Comment by Azilroka** [comment]
yea that one is right clickable.. however the other one isnt.. I just made changes to the other bar that will work the same as that.

**Comment by hypongithub** [comment]
Azilroka... you rock. thanks!
that is beautiful.
