### ISSUE TITLE
[TBC Bug Report] <Title here>

### ISSUE THREAD

**Issue by syswis** [tukui-org/ElvUI#296]
### What is the issue you are having?

Profiles got messed up/deleted

### What is the expected behavior?

Tell me

### What actually happened?

Rebooted, for some reason Wow Couldn't find anymore my i stalled game. I pointed it where should be.
Everything is okay, EXCEPT elvUI decided for some reason to delete all the profiles and start over.

My DEFAULT profile, where all my customization have been made, it is now just DEFAULT like it has never been installed.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
ElvUI doesn't just delete profiles.  It is a known issue that the wow client derps up like in your situation and clears some if not all addons. If you did not back up the wtf folder or export your settings then it sounds like you no longer have your settings.
