### ISSUE TITLE
[TBC Bug Report] <Title here>

### ISSUE THREAD

**Issue by Ludoswow** [tukui-org/ElvUI#297]
### What is the issue you are having?

As a guild master, there is an issue with the guild's interface. When I try to, for example, upgrade the grade of a member, I can't do it and it's "blocked". When I try to change the permission of a role, sometimes it works, sometimes all the permissions are removed and I can't change anything. I don't understand why it happens, but all is working fine when i disable Elvui. 
I

### What is the expected behavior?

The guild's interface should have no issue with Elvui, making it possible to change the grade of a member, the permissions of a role, etc ... But it's not possible right now.

### What actually happened?

Sometimes I want to upgrade a member or change the permissions of a role. But when it's bugged, I can't do that. For the upgrade of a member, if I click on the arrow to upgrade the member, nothing happens and it's like I never click on the arrow.

Change the permissions of a role is the same : when it's bugged, the interface shows every permission disabled (even for me, the GM), and I can't change anything. In fact, I have the same rights as before (i mean, the "bugged" interface doesn't change the permissions already given), but I can't modify anything. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Ludoswow 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

after that we can Continue.
