### ISSUE TITLE
[Feature Request] Action Bar - Empty Slots should be clickthrough

### ISSUE THREAD

**Issue by Reudig** [tukui-org/ElvUI#298]
**Is your feature request related to a problem? Please describe.**
At the moment, every actionbar just blocks everything beneath it from being clicked. you either click on the icon on the action bar or you click the empty action bar slot, but you cannot click e.g. a quest items, lying on the group behind it. You also cannot click there to turn the camera.

**Describe the solution you'd like**
If possible I'd suggest to have empty action bar slots be clickthrough by default.

**Describe alternatives you've considered**
at the moment action bars are either solid and non-clickthrough or entirely clickthrough, which means you cannot click the icons.

**Comment by Repooc** [comment]
I recall your message in discord.  Even though I said it's most likely possible, I should have clarified that we would leave this to be something for a plugin to do.  We rather keep the bar itself to be clickthrough or not clickthrough.
