### ISSUE TITLE
[TBC Bug Report] Nameplate style filter doesn't update isTargetingMe on body-pull or with adds consistently

### ISSUE THREAD

**Issue by bthomp2420** [tukui-org/ElvUI#299]
### What is the issue you are having?

Setting up some nameplate styles, I ran into an issue where 2 separate styles that should alternate based on whether a unit is targeting me wasn't working consistently when body pulling or getting an add through social aggro.

Ultimately, after doing some /etrace investigation it turns out the UNIT_TARGET doesn't consistently fire in all cases that a mob enters combat and starts targeting a player despite the threat update events happening.

### What is the expected behavior?

When a unit enters combat and starts targeting a player, isTargetingMe should update appropriately when the units target changes.

### What actually happened?

isTargetingMe filter doesn't update and filter styles don't change to the correct style consistently.

### Suggested Solution/Workaround

update isTargetingMe state for nameplate filter styles on both threat update events and unit target events
[patch.txt](https://github.com/tukui-org/ElvUI/files/9441553/patch.txt)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [TBC Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@bthomp2420 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

and/or join our Discord Server for Help with Filters.

**Comment by kodewdle** [comment]
wish this would just get fixed on the real event, implemented it but we'll see how it goes
