### ISSUE TITLE
[Feature Request] <Target Debuff>

### ISSUE THREAD

**Issue by kkofodh** [tukui-org/ElvUI#300]
On the target frame. i would like the option to have the Debuff transition from icon to bar when the debuff gets under a set amount of time.

example: a dot is applied with 28seconds duration. it shows as an icon. then when it got less than 6 seconds left it transition into a bar. thereby making the player aware that its about to run out.

currently you can filter both bars and icons individually with a minimum and maximum time. so in the end im just asking for a transition option between the 2.

**Comment by Azilroka** [comment]
This is unlikely to happen. WeakAuras handles this pretty well.
