### ISSUE TITLE
[Wrath Bug Report] <Calendar Fails to Open>

### ISSUE THREAD

**Issue by DumpsterFire6** [tukui-org/ElvUI#301]
### What is the issue you are having?

I have gone into the setting and enabled the calendar. When you click on the calendar icon the calendar does not open.

### What is the expected behavior?

I would expect that you can click on the calendar icon and it will open the calendar

### What actually happened?

I clicked on the calendar icon and it fails to open properly.

### Suggested Solution/Workaround

I am not skilled with programming but either allowing the option to set a key bind to open the map or code the button to work properly would be my suggestion. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
fixed
