### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by Frinata** [tukui-org/ElvUI#304]
### What is the issue you are having?

Parts of the UI are 'sticking' the gold piece on the left side, and the /fstack of it on the right
![image](https://user-images.githubusercontent.com/112581974/187761572-da2e24c8-ac20-41f7-bf04-877e44012d04.png)

### What is the expected behavior?

For it to go away when the quest window closes?

### What actually happened?

It sticks around over the UI at the top most layer

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [ ] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by eltreum0** [comment]
I've had this happen too, and while the screenshot has other addons it also seems to happen randomly without them, i am not sure whats causing it maybe a setparent is wrong or there is something that happens when the window closes that the gold icon stays
