### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#305]
### What is the issue you are having?

I keep getting this message during combat. 

### What is the expected behavior?

Not to get this error

### What actually happened?

Don't know just getting error spam.

### Errors

```shell
Message: [string "UIEr"]:1: '=' expected near '<eof>'
Time: Wed Aug 31 17:56:39 2022
Count: 20
Stack: [string "UIEr"]:1: '=' expected near '<eof>'
[string "=[C]"]: ?
[string "=[C]"]: in function `RunScript'
[string "@Interface\FrameXML\ChatFrame.lua"]:2196: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:4933: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4596: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:2977: in function <Interface\FrameXML\ChatFrame.lua:2970>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseAction'
[string "@Interface\FrameXML\SecureTemplates.lua"]:343: in function `handler'
[string "@Interface\FrameXML\SecureTemplates.lua"]:625: in function <Interface\FrameXML\SecureTemplates.lua:569>
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:266: in function <Interface\FrameXML\SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface\FrameXML\SecureHandlers.lua"]:296: in function <Interface\FrameXML\SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/187800901-e467c313-acbe-4dac-b50b-dd932896b295.png)

Not sure if it's really Elv, but it's been happening since I logged in today. All up-to-date as far as I can tell.

**Comment by Azilroka** [comment]
WeakAuras

**Comment by Azilroka** [comment]
You have one called.. UIEr

**Comment by Gogo1951** [comment]
Not that I know of... and even with Weak Aura turned off I get the error.

**Comment by Azilroka** [comment]
How about `/edebug on` which is the last step that ensures 0 other addons are enabled.

**Comment by Gogo1951** [comment]
I stepped out for dinner but I'll try it as soon as I'm home.

Thanks for the help trouble shooting this!

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/187814453-fa410e53-4c19-4404-a553-1db4d6918843.png)
 
Someday. Thanks guys!

**Comment by Gogo1951** [comment]
Happens with /edebug on

![image](https://user-images.githubusercontent.com/55365231/187823017-8504ef7d-5121-4edf-b9f2-1b78590e5bdd.png)

**Comment by Gogo1951** [comment]
/script UIErrorsFrame:Clear()

Found it. Had a macro that was malformed. Sorry to waste your time! Thanks for the help!
