### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by mentyrr** [tukui-org/ElvUI#307]
### What is the issue you are having?

Hello guys,

with wrath prepatch and new elvui update i got fps drops as soon as the fight begins, i disabled all addons besides elvui and the issues remained, with everything disabled there are no problems, i tried to enable everything except elvui and evereything is fine too.

i had the same problem years ago and opened a ticket back in the day, you guys fixed the behavior, but i dont know the problem anymore.

### What is the expected behavior?

no changes to pre wrath :)

### What actually happened?

fps drops are from 160 (capped by me) to 130/120/110, after this immidiatly going up to 150/160 again, and rinse and repeat

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
First world problems.

The out of combat fps is always going to be higher than in combat. You aren't doing any api calls or events to make the ui do anything outside of combat.

**Comment by Azilroka** [comment]
First world problems.

The out of combat fps is always going to be higher than in combat. You aren't doing any api calls or events to make the ui do anything outside of combat.

**Comment by mentyrr** [comment]
hey,

no that kind of world first probs,
these drops result in micro lags. friends of mine got the same problem too.
all issues since prepatch and since i got this problem fixed in the past, i thought i open a ticket.

greetings

**Comment by laksateef** [comment]
> 
Same here
