### ISSUE TITLE
Change order of totems in totem bar and class bar

### ISSUE THREAD

**Issue by iymeko** [tukui-org/ElvUI#308]
**Is your feature request related to a problem? Please describe.**
I've always had my totems showing in order of: air, earth, water, fire (whether it be on my action bars or via a totem addon like TotemTimers). Now that we have Call of Ancestors, etc. I need to use the totem bar, but not having the totems in the order I'm used to is kinda frustrating. The 4 buttons I use for the 4 totem elements are all in a row on my keyboard, so having the display order not match up to the keybind order hurts my brain. I guess I could re-teach myself different keybinds to match with the different order, but well... re-learning keybinds sucks. Also, the fact that the totem order on the totem bar and class bar doesn't currently match up is kinda aesthetically bad imo.

**Describe the solution you'd like**
I'd like the option to change the order of totems in the totem bar. This isn't as big a deal to me for the class bar but it'd be nice to be able to change it there too.

**Describe alternatives you've considered**
Normally I use TotemTimers, which does let you change the totem order, but I don't know when the dev(s) behind it will get it working right for WotLK, and I don't know how well it will work with Call of Ancestors, etc. Maybe I'm being a little impatient? =/

**Additional context**
Thanks a bunch, I love ElvUI =)

**Comment by Azilroka** [comment]
I've actually said something to Blizzard Devs about this. Their bar is wrong. Ours on the unitframe is right.

**Comment by kodewdle** [comment]
fixed in 12.89
