### ISSUE TITLE
[Wrath Bug Report] Profiles don't change UI 

### ISSUE THREAD

**Issue by Rakaaria** [tukui-org/ElvUI#309]
### What is the issue you are having?

After updating ElvUI to woltlk, custom profiles show up but do not change the UI any longer.

### What is the expected behavior?

If i change the Profile, the UI should've changed to my previous settings.

### What actually happened?

I could choose my old custom profiles but it did not change the UI the slightest.

### Suggested Solution/Workaround

tried /edebug, did nothing.
Edit:
Also tried the Dev version, same outcome.
Tried replacing the new WTF folder and the ElvUI.lua with my backuped ones didn't work, neither did overwriting the elvui folder nor WTF. (Yes I installed it correctly before).

![elvui profiles not working](https://user-images.githubusercontent.com/112638648/187938482-319da68c-53b0-40c7-9ae0-ce3408bbe07e.jpg)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
https://user-images.githubusercontent.com/1479745/187990695-5c469c36-d70d-46f1-8cce-c937c45e85cc.mp4

working as it should, be warned, not reading the check box contents will get ur ticket auto closed next time
