### ISSUE TITLE
[TBC Bug Report] Group unit frames not showing in V2.19

### ISSUE THREAD

**Issue by DrSterni** [tukui-org/ElvUI#31]
### What is the issue you are having?

The group unit frames are simply not showing.

### What is the expected behavior?

The group unit frames should be shown.

### What actually happened?

As explained: They don't show up. Apart from that the player- or target-unit-frames are showing.

### Suggested Solution/Workaround

No solution/workaround found.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by dlecina** [comment]
To add some context from my experience: in older versions, when I'm in a 25 raid, groups >5 will only show while outside the instance or even inside the instance sometimes when people are being moved around. When this happens, I usually reload and it only shows groups 1-5.

In this new version, I was seeing groups > 5, and I tried reloading as usual, but this time all the groups disappeared entirely and I could not find any way to get them back even after multiple reloads and even exiting and coming back to the game.

In the end, the only solution was to go to my PTR folder to recover the old version.

Hopefully this is in some way helpful.

_BTW A couple tangentially related requests that you don't need to tackle in this issue: it would be nice to have an archive of old version releases so we can downgrade in cases like these. Maybe there is, but I could not find one. Also, it would be nice to be able to force the UI to load the config window, if at all possible with the current API (maybe not). I was trying to troubleshoot it while in combat and I couldn't do anything._

**Comment by shotouw** [comment]
For me the raid frames dont show at all. Groups up to 5 people do show up though, it's only raids that don't work.
Luaerror on shows the following error messages:

> Message: attempt to concatenate a nil value
> Time: Thu Nov  4 01:33:42 2021
> Count: 1
> Stack: attempt to concatenate a nil value
> [string "=[C]"]: ?
> [string "=[C]"]: ?
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:116: in function `?'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:768: in function `Configure_Groups'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1054: in function `CreateAndUpdateHeaderGroup'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1136: in function `LoadUnits'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1539: in function `func'
> [string "@Interface\AddOns\ElvUI\Core\Libraries\oUF\factory.lua"]:20: in function <...nterface\AddOns\ElvUI\Core\Libraries\oUF\factory.lua:16>
> [string "=(tail call)"]: ?
> 
> Locals: 


As well as

> Message: attempt to concatenate a nil value
> Time: Thu Nov  4 01:33:43 2021
> Count: 1
> Stack: attempt to concatenate a nil value
> [string "=(tail call)"]: ?
> [string "=[C]"]: ?
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:116: in function `?'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:768: in function `Configure_Groups'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1054: in function `CreateAndUpdateHeaderGroup'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:1168: in function `UpdateAllHeaders'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:624: in function `Update_AllFrames'
> [string "@Interface\AddOns\ElvUI\Core\Modules\UnitFrames\UnitFrames.lua"]:960: in function `?'
> [string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
> [string "=[C]"]: ?
> [string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
> [string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
> [string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...UI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
> 
> Locals: <none>
I hope this helps!

**Comment by Azilroka** [comment]
This should be resolved in 2.20
