### ISSUE TITLE
[Wrath Bug Report] Player castbar takes on interruptible color

### ISSUE THREAD

**Issue by Redtuzk** [tukui-org/ElvUI#310]
### What is the issue you are having?

The player castbar takes on the uninterruptable color when casting harmful spells on enemy targets.
Video example: https://streamable.com/9g5x3e

### What is the expected behavior?

With the castbar set to "class color", it should always be class colored.

### What actually happened?

 Castbar takes on the uninterruptable color, only when casting on enemies.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
it is working as intended (just like retail). if you download the dev build, i added the option for uninterruptible color and such so it is now like retail wow.  it will color the castbar the uninterruptible color if the spell is not able to be interrupted, as the class color option doesnt override that.

**Comment by Redtuzk** [comment]
> t

Even for the _player_ bar? I'd understand the enemy bar, but I swear I never had this issue on retail.

**Comment by Repooc** [comment]
yes on the player bar, it indicates that what u are casting can be interrupted (by others vs not)

**Comment by Redtuzk** [comment]
> yes on the player bar, it indicates that what u are casting can be interrupted (by others vs not)

gotcha, deleted my comment shortly after as I remembered that is is indeed how that works, thanks repooc

**Comment by Repooc** [comment]
np
