### ISSUE TITLE
[Classic Bug Report] <Title here>

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#316]
### What is the issue you are having?

Joining LFG Tool

### What is the expected behavior?

Shouldn't give errors.

### What actually happened?

Gave an error.

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:69: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
already fixed in dev

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/188274514-8f2ddec9-c353-4adb-9585-fd5a970c7b7f.png)

boom

**Comment by Gogo1951** [comment]
> ![image](https://user-images.githubusercontent.com/1934853/188274514-8f2ddec9-c353-4adb-9585-fd5a970c7b7f.png)
> 
> boom

Come on mate, it's hard enough getting people to test and report issues. This was a valid issue, glad it was fixed. Adding all the steps to enter a bug is excessive.
