### ISSUE TITLE
[TBC Bug Report] "ELVUI"-Button in Chat-Bar gone in V2.19

### ISSUE THREAD

**Issue by DrSterni** [tukui-org/ElvUI#32]
### What is the issue you are having?

Since the last update the chat-bar seems to miss the "ELVUI"-Button in the chat-bar below (or above) the left chat-window.

### What is the expected behavior?

There should be a button for the quick launch of the ELVUI-menu.

### What actually happened?

Well, nothing?

### Suggested Solution/Workaround

none.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Luckyone961** [comment]
discussed / fixed on discord

**Comment by DrSterni** [comment]
Thanks! Was a bit hard to find as discord is not structured well enough for ticket-processing, but I could find it.
