### ISSUE TITLE
[Classic Bug Report] Interruptible Castbar Color missing from WoTLK 

### ISSUE THREAD

**Issue by Vimento05** [tukui-org/ElvUI#320]
### What is the issue you are having?

The option to change what color a castbar have when something is either 'interruptible or not' is missing in the WoTLK version compared to it's Retail counterpart.

This is something I came by as I imported a retail profile into the WoTLK version for an easy setup but since the option cannot be accessed I'm having some funky color missmatch between my desired wishes.

![RetailInterruptable](https://user-images.githubusercontent.com/112804910/188308993-ce8d313e-704e-4db2-84e1-bb272a2b3f16.JPG)
![WoTLKInterruptableMissing](https://user-images.githubusercontent.com/112804910/188308996-f3e3c98f-733c-4b49-be67-4a12218a8e15.JPG)

### What is the expected behavior?

I would assume the expected behaviour is that the WoTLK version will also be able to change a castbars color depending on the user input.

### What actually happened?

Whenever casting something the likes of Hearthstone, Bandages or such the color is correctly displayed as Class Color in my case, but using Steady Shot / Volley changed the color into a reddish hue (The same color as the Retail screenshot Non-interruptible) as you can see on the two screenshots
![VolleyColor](https://user-images.githubusercontent.com/112804910/188309094-fe63570b-e35e-4d70-ba59-cdfa0d1fc678.JPG)
![EaglesEye](https://user-images.githubusercontent.com/112804910/188309095-48045531-fc2a-47b9-a707-a1938a27f1de.JPG)

### Suggested Solution/Workaround

For now there is no workaround it seems since the option is not available to be changed in the ElvUI settings.

### Errors

```shell
No errors besides the one presented and edebug on/off did not fix the issue either.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Confirmed fixed in dev.
