### ISSUE TITLE
[Feature Request] <table of units>

### ISSUE THREAD

**Issue by jesseroiz** [tukui-org/ElvUI#321]
**Is your feature request related to a problem? Please describe.**
Good morning, it's about the unit board, we don't have an option to put the unit boards to appear only in combat, just disable it,

**Describe the solution you'd like**
if you put this option it would be of great help for a clean Ui interface , an option to put the UI code to hide and show only in battle.

**Comment by Repooc** [comment]
your request isnt very clear but from what i gathered. you are wanting Unitframes (not sure if that is what you are talking about when you say "unit boards") to hide when out of combat.  Unitframes Fader section has an option for combat already, for group units that have a visibility text box, you dont have use the Fader section to do this and just use wow macro condtional `[combat]` or `[nocombat]` as a condition on when to hide/show the frames you have this set on.
