### ISSUE TITLE
[Classic Bug Report] Lua Error in Combat, Unknown Cause

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#322]
### What is the issue you are having?

Got an error while in combat, not sure what triggered it.

### What is the expected behavior?

Shouldn't get this error.

### What actually happened?

I was questing in combat, and BugSack caught something.

Not happening consistently.

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'OverrideActionBarButton3:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:357: in function `ActionButton_Update'
[string "@FrameXML\ActionButton.lua"]:694: in function `ActionButton_OnEvent'
[string "@FrameXML\ActionButton.lua"]:207: in function <FrameXML\ActionButton.lua:204>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
Issues around ActionButton_Update continue to pop up but just randomly. In combat or when I'm drinking after. Seems to happen more in a raid than not. Not really sure.

**Comment by Raulfin** [comment]
I seem to get this error almost everytime 1 change druid stance more than once during a fight. Not sure how much that will help, just something i've noticed.

**Comment by tomten2k4** [comment]
I'm getting almost identical error using version 13.26:

ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'OverrideActionBarButton1:Show()'.
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/ActionButton.lua"]:357: in function <Interface/FrameXML/ActionButton.lua:331>
[string "=[C]"]: in function `ActionButton_Update'
[string "@Interface/FrameXML/ActionButton.law
