### ISSUE TITLE
[Retail Bug Report] <Chat Channels not showing even though they are checked>

### ISSUE THREAD

**Issue by Nate46burton** [tukui-org/ElvUI#326]
### What is the issue you are having?

I no longer can see the trade or general chat. I've tried resetting the user interface, uninstalling WoW, resetting my cache, leaving and re-joining channels but chat is still missing. 

### What is the expected behavior?

I would like to know how to get chat back

### What actually happened?

Chat is not visible no matter [what[](url)]([url](url))

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Retail Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
They are the blizzard chat channels, Have you tried the 
/join Trade
https://us.battle.net/support/en/article/9738

Please disable all addons & test with just the Blizzard UI

Upload a screenshot - 

If it is working with no addons, blizzard UI

Enable only ElvUI & ElvUI_OptionsUI & test. 
If it is different from the blizzard you, type in chat in game
/estatus

and upload a screenshot showing the status panel and the issue.

**Comment by Nate46burton** [comment]
I’ve tried disabling all addons it still didn’t show up. I notice that the chats went away when I tried altering my Elvui chat windows by clicking “reset chat positions” and I’ve not been able to get it back since then.

I will upload a screenshot to y’all tomorrow

**Comment by 1Botanica1** [comment]
If it is happening without addons, then it is something with the blizzard UI 

Try the blizzard reset chat mentioned in the blizzard troubleshooting chat I linked above.

**Comment by 1Botnet** [comment]
/resetchat may work for you as well
