### ISSUE TITLE
[Wrath Bug Report] Group Browser breaks when Listing Self in Group Finder (Version 3.00)

### ISSUE THREAD

**Issue by VarvatosVex** [tukui-org/ElvUI#327]
### What is the issue you are having?

When you list yourself in the Group Finder, you get an error message in the chat saying "Interface action failed because of an AddOn", and then the Group Browser tab completely breaks until you manually reload the UI.

### What is the expected behavior?

When you click on "List Self", it should switch to the Group Browser tab and show other players/groups currently looking for group so that you can whisper, group invite or request to join other players.

### What actually happened?

When you click on "List Self", it switches to the Group Browser tab and gets stuck on "Searching...". No matter what buttons you click or what options you select, it's completely broken and will not work. Even if you unlist and relist yourself, it's still broken. The only way to fix this is to reload the UI.

What is shown until reload:
![image](https://user-images.githubusercontent.com/20911914/188649768-4e833d1a-7b85-4526-b054-8e6519e1e5b6.png)

What should be shown:
![image](https://user-images.githubusercontent.com/20911914/188650002-6701b81d-6301-4a31-bfe5-6b7bcbb8bbd1.png)

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'Search()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Search'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:225: in function `LFGBrowse_DoSearch'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua"]:178: in function `SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua"]:92: in function `LFGParentFrame_SearchActiveEntry'
[string "@Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua"]:69: in function <...s\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:49>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Fixed in dev version which you can download, or disable the LFG skin in - ElvUI - skins & wait for next release.
