### ISSUE TITLE
[Wrath Bug Report] Quest accepting / turn in errors

### ISSUE THREAD

**Issue by crypticasden** [tukui-org/ElvUI#328]
### What is the issue you are having?

When accepting or turning in a quest I get an error code. 

### What is the expected behavior?

No error code when accepting and allowed to turn in quests

### What actually happened?

When accepting or turning in a quest I get an error code. 

### Suggested Solution/Workaround

Clicking through the error message

### Errors

```shell
Message: Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:391: attempt to index field '?' (a nil value)
Time: Tue Sep  6 10:53:16 2022
Count: 8
Stack: Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:391: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua"]:391: in function <Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:375>
[string "=[C]"]: in function `QuestInfo_Display'
[string "@Interface_Wrath\FrameXML\QuestFrame.lua"]:697: in function <Interface_Wrath\FrameXML\QuestFrame.lua:689>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2215: in function `SetUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2122: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:1928: in function <Interface_Wrath\FrameXML\UIParent.lua:1924>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_Wrath\FrameXML\UIParent.lua"]:2717: in function `ShowUIPanel'
[string "@Interface_Wrath\FrameXML\QuestFrame.lua"]:92: in function <Interface_Wrath\FrameXML\QuestFrame.lua:24>

Locals: 


Message: Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:391: attempt to index field '?' (a nil value)
Time: Tue Sep  6 10:53:16 2022
Count: 8
Stack: Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:391: attempt to index field '?' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua"]:391: in function <Interface\AddOns\ElvUI\Wrath\Modules\Skins\Quest.lua:375>
[string "=[C]"]: in function `QuestInfo_Display'
[string "@Interface_Wrath\FrameXML\QuestFrame.lua"]:697: in function <Interface_Wrath\FrameXML\QuestFrame.lua:689>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\QuestLogFrame.lua"]:120: in function <Interface_Wrath\FrameXML\QuestLogFrame.lua:86>

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This is fixed in dev version which you can update to, or wait until next release.

**Comment by Gogo1951** [comment]
Had this error too! Thanks for fixing it.
