### ISSUE TITLE
[Retail Bug Report] Leader Icon shows behind buffs/debuffs

### ISSUE THREAD

**Issue by Kommeh** [tukui-org/ElvUI#33]
The leader icon on both player and target unitframes for as long as I can remember shows up behind other frames such as buffs and debuffs. It would be nice if it could take priority and be forced to be in front of other frames. I have looked for strata options and such but nothing I have tried has been an effective solution. I have attached an example that shows what happens with both player and target unitframes. No change between them so the picture will show an example. The leader icon in this example is the shadow in the top left corner.
![Leader Icon Target](https://user-images.githubusercontent.com/71908003/140234714-20312d90-c7fb-43fe-8b44-d9aaaec38f2d.JPG)

**Comment by Luckyone961** [comment]
Fixed in 12.47
