### ISSUE TITLE
[Wrath Bug Report] Lib Heal comm LUA error when standing still in raid group

### ISSUE THREAD

**Issue by Jovzin** [tukui-org/ElvUI#330]
### What is the issue you are having?

I was invited to our raid group.  After about 20 seconds while I was waiting for port to Sunwell I was getting this error : 
Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
Time: Wed Sep  7 19:31:48 2022
Count: 33
Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2398: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2384>
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2571: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>

Locals: 

### What is the expected behavior?

No errors should pop up I think.

### What actually happened?

Raid starting at around 19:30 CET. Logged to the game around 19:20 CET.  Asked for invite. Got invite to the raid group and was waiting in Shatrrah  for summon. Suddenly got an LUA error message : 
Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
Time: Wed Sep  7 19:31:48 2022
Count: 33
Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2398: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2384>
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2571: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>

Locals: 

### Suggested Solution/Workaround

Update the Lib Heal Comm library ore maybe we need to remove it ?

### Errors

```shell
Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
Time: Wed Sep  7 19:31:48 2022
Count: 33
Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2398: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2384>
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2571: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
![image](https://user-images.githubusercontent.com/1479745/188944161-8ff082b4-4b2a-406c-b3b7-85b2db91f079.png)
been reported and answered

**Comment by Jovzin** [comment]
I have an update.  
I just updated the RClootcouncil classic addon and enabled it to check.  

And got this error. 

Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
Time: Wed Sep  7 19:54:14 2022
Count: 10
Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2398: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2384>
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2571: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355


I think I might be getting that error before due to I had not enabled the RCLoot council classic addon. And each time the Guild COuncil guy was posting some item I was getting that first error ?
