### ISSUE TITLE
[Wrath Bug Report] Issues with TBC/WOTLK LibHealComm 

### ISSUE THREAD

**Issue by Iahz** [tukui-org/ElvUI#333]
### What is the issue you are having?

I keep receiving these two errors, espacially on a raid environment:

Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3154: bad argument #1 to 'strsub' (string expected, got nil)
Message: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)

These two errors didn't exist before prepatch.

### What is the expected behavior?

I don't understand what is triggering these errors so it's difficult for me to have a correct expected behavior other that "not having these errors".

### What actually happened?

I guess I have these errors when a new healing/buff spell (from prepatch) is used by any of the raid members.
For example "Wild growth" from healing druids seems to trigger these errors.

### Errors

```shell
Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3154: bad argument #1 to 'strsub' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3154: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>

Stack: ...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2398: attempt to perform arithmetic on local 'tickInterval' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2398: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:2384>
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:2571: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua"]:3349: in function <...UI\Libraries\TBC\LibHealComm-4.0\LibHealComm-4.0.lua:3345>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
![Screenshot_20220909-122628.png](https://user-images.githubusercontent.com/1479745/189397312-c1b51632-8204-4ae1-8620-32ba12e96ca0.png)asked and answered in a few closed issues

**Comment by Repooc** [comment]
Try the dev build for now or wait till next release which is soon: tm:

**Comment by trixxtaa** [comment]
did you figure this out? happening to me
