### ISSUE TITLE
[TBC Bug Report] Heal prediction for HOTs

### ISSUE THREAD

**Issue by alexriedl** [tukui-org/ElvUI#34]
### What is the issue you are having?

starting with version 2.19 heal prediction for HOTs no longer show up on any unit frame (player, target, party, raid)

### What is the expected behavior?

Heal predictions show up for direct heals and HOTs

### What actually happened?

Heal prediction only shows up for direct heals, but not for HOTs

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by lmtierney** [comment]
Looks like it might be affecting absorbs too

**Comment by Luckyone961** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/163
