### ISSUE TITLE
[Wrath Bug Report] Equipment Manager / Macro Bugs

### ISSUE THREAD

**Issue by bferg317** [tukui-org/ElvUI#340]
### What is the issue you are having?

Multiple bugs with saving sets and setting slots to ignore/include with ElvUI 3.0. Macro UI does not show icons. These errors are not mentioned in the changelog for 3.01.

![image](https://user-images.githubusercontent.com/46008360/189540938-7659788a-c584-4e33-b0a0-bd94037898b6.png)

### What is the expected behavior?

NA

### What actually happened?

1. When saving macros, the icons do not load. Minor issue.
2. When saving sets in Equipment Manager, the icons do not load. Minor issue.
3. When attempting to save sets in Equipment Manager, the following error appears: (See 'Errors' section)
4. When attempting to save a slot as 'ignored' in a set, the set saves as if that slot were included as 'equip no item'. This behavior is difficult to reproduce due to the above stopping error.

![image](https://user-images.githubusercontent.com/46008360/189541063-62c8e116-8890-4556-a0d1-ed88d8fdb5d4.png)

![image](https://user-images.githubusercontent.com/46008360/189541089-bf1478e8-b973-477a-99be-f91984cb3ce0.png)

### Suggested Solution/Workaround

Only disabling ElvUI allows function of equipment manager.

### Errors

```shell
Message: Interface_Wrath\FrameXML\PaperDollFrame.lua:2379: attempt to perform arithmetic on upvalue '_numItems' (a nil value)
Time: Sun Sep 11 13:22:59 2022
Count: 1
Stack: Interface_Wrath\FrameXML\PaperDollFrame.lua:2379: attempt to perform arithmetic on upvalue '_numItems' (a nil value)
[string "=[C]"]: ?
[string "@Interface_Wrath\FrameXML\PaperDollFrame.lua"]:2379: in function `RecalculateGearManagerDialogPopup'
[string "@Interface_Wrath\FrameXML\PaperDollFrame.lua"]:2356: in function <Interface_Wrath\FrameXML\PaperDollFrame.lua:2353>
[string "=[C]"]: in function `Show'
[string "@Interface_Wrath\FrameXML\PaperDollFrame.lua"]:2272: in function <Interface_Wrath\FrameXML\PaperDollFrame.lua:2269>

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Wrath Changelog]().
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step five and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
That error is a blizzard one.

**Comment by SteveEbey73742** [comment]
Where is the download for the latest Elvui-Wrath, I have searched the entire website, for a way to update my Evlui and not finding anything.

**Comment by Azilroka** [comment]
> Where is the download for the latest Elvui-Wrath, I have searched the entire website, for a way to update my Evlui and not finding anything.

Did you look at ElvUI on the main addon section at the top of the site? It's there. Download ElvUI.

**Comment by SteveEbey73742** [comment]
yes, i figured out what was going on, the add on installer was not working properly.  12.xx has all the retails and classic modules in it. Thanks for the response.

**Comment by Repooc** [comment]
> Where is the download for the latest Elvui-Wrath, I have searched the entire website, for a way to update my Evlui and not finding anything.

Don't "hijack" someone else's issue that has nothing to do with ur own issue. Always check the website for downloads or use discord and ask.

**Comment by bferg317** [comment]
Update: The icons aspect of this report is no longer applicable in 12.87, but the equipment manager "ignore slot" function still does not work with ElvUI enabled. It does work with ElvUI disabled.

**Comment by fallgaming** [comment]
The icons (and therefore not being able to save) report in equipment manager still exists in version 12.91. Confirmed by disabling all other addons before disabling ELVUI to check for the problem. Only by disabling ELVUI am I able to overwrite saves in equipment manager.
