### ISSUE TITLE
[Retail Bug Report] <Update changed my Raid profiles / action bar settings>

### ISSUE THREAD

**Issue by Hounze** [tukui-org/ElvUI#342]
### What is the issue you are having?

Hey - so I installed the most recent update and now my raid profiles seem to have reset to default, they were exactly how I wanted them before. I tried to re-import my profile that I had shared with someone previously, but it had the same issue. I really have no idea how to get around this, they look so different, and I spent a lot of time getting them set up how I liked them.

### What is the expected behavior?

To be like it was before this last update.

### What actually happened?

The profile was bugged by your update.

### Suggested Solution/Workaround

Revert my ElvUi to the last version.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
There was a needed updates to the raid frames (Smart Raid Filter being removed) and therefore, the visibility settings were changed and another raid frame (Raid 2) being added
You can read the changes here https://www.tukui.org/download.php?ui=elvui&changelog

Raid 1 or 3 should have the settings you already had.  
If you need help, join the ElvUI discord. 

Action Bar settings haven't been changed apart from a CD added, which you can read in the changelog.
