### ISSUE TITLE
[Feature Request] Disable taskbar icon flash on whispers received in background

### ISSUE THREAD

**Issue by sharkMaster12345** [tukui-org/ElvUI#343]
I find it annoying that my client icon (on the taskbar) flashes when I receive a whisper on an inactive client as I often have two clients open at once on separate monitors. This allows me to be aware of incoming whispers on the non-active client window but I still have to manually select the secondary client to stop the icon from flashing.

I would like to be able select in the settings whether my taskbar icon should flash on incoming whispers on inactive clients or not. Currently I just delete the [line of code](https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/Chat/Chat.lua#L2190) responsible for it from the ElvUI source code but that turns it off for all characters and is not persistent through ElvUI updates. I have reached out to the Discord community if they could think of a more beautiful solution short of submitting a feature request but they even denied that it was an ElvUI feature.

**Comment by Azilroka** [comment]
I don't know who you talked to.. I dont see any messages about it tho.

**Comment by Azilroka** [comment]
Implemented
