### ISSUE TITLE
[Wrath Bug Report] Buffs/Debuff anchoring with "Fluid debuffs on buffs" on target frame.

### ISSUE THREAD

**Issue by Zhizhica** [tukui-org/ElvUI#344]
### What is the issue you are having?

I am trying to set up the display of buffs and debuffs on my target unitframe. I want them both to the right of the frame, growing down, and debuffs attached to the bottom row of buffs. 
![image](https://user-images.githubusercontent.com/83887992/190283271-41bb14d0-c675-43a0-9d9a-2b7681e6cb40.png)
I configure General/Buffs/Debuffs settings of my target frame in the folowing way:
On "General" tab "**Fluid debuffs on buffs**" is selected.
![image](https://user-images.githubusercontent.com/83887992/190283431-740d424c-76c9-4cd5-81fd-e683d685bd9c.png)
**Buffs** are anchored with the "**TOPRIGHT**" option related to the **frame** and they grow to the **Right on X** and **Down on Y** directions.
![image](https://user-images.githubusercontent.com/83887992/190283462-c0cb79fd-60bf-4959-bf1d-da470fa9a417.png)
**Debuffs** are anchored with the "**BOTTOMLEFT**" option related to the **buffs** and they grow to the **Right on X** and **Down on Y** directions.
![image](https://user-images.githubusercontent.com/83887992/190283478-79eb9e21-e51e-4201-8313-53f5a0fb51f6.png)

With these settings i expect debuffs to grow down from the buffs, but instead i am getting following picture with "Show Auras" on:
![image](https://user-images.githubusercontent.com/83887992/190284403-38ad750c-0ded-4518-8743-02a03042cd90.png)

### What is the expected behavior?

I expect to achieve following positioning of buffs and debuffs on my target frame:
![image](https://user-images.githubusercontent.com/83887992/190283271-41bb14d0-c675-43a0-9d9a-2b7681e6cb40.png)
And i was able to acheve similar positioning during TBC with my old curently lost profile:
![image](https://user-images.githubusercontent.com/83887992/190284648-1a2a67d3-797c-4f2a-86aa-b3e51a8f7ad9.png)

### What actually happened?

Together with Eltreum from Tukui Community discord we made a few experiments to try to figure out how to achieve desired buffs/debuffs positions.
Our conversation with screenshots of various combinations of settings can be seen between following messages from the above mentioned discord:
https://discord.com/channels/209244641537556480/831324000717242439/1019726076936732733
https://discord.com/channels/209244641537556480/831324000717242439/1019754966186991646

During these experiments we noticed that there were moments when anchoring behaved as expexted:
Buffs were anchored with the "RIGHT" option related to the frame
Debuffs were anchored with the "BOTTOM" option related to the buffs

However if ether or or both buffs/debuffs were anchored with corner anchors (TOPRIGHT, BOTTOMLEFT, etc...) anchoring looked broken in one or the other way.

After all these experiments I strongly feel that there may be some problem with anchoring when fluid buffs/debuffs are enabled.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Zhizhica** [comment]
Problem with anchors stays on with **/edebug on**
![image](https://user-images.githubusercontent.com/83887992/190294601-d3cd2f05-fb15-43c3-b29b-51a6172589ec.png)

**Comment by Zhizhica** [comment]
I was able to fix this issue locally by making the following changes to the file [ElvUI/Core/Modules/UnitFrames/Elements/Auras.lua](https://github.com/tukui-org/ElvUI/blob/76dbe5b956f252fcb080f003b4a6fcc80915188f/ElvUI/Core/Modules/UnitFrames/Elements/Auras.lua)
(git diff format)
```diff
@@ -17,6 +17,14 @@ local UnitCanAttack = UnitCanAttack
 local UnitIsFriend = UnitIsFriend
 local UnitIsUnit = UnitIsUnit

+local SimpleAnchors = {
+       BOTTOM = 'TOP',
+       CENTER = 'CENTER',
+       LEFT = 'RIGHT',
+       RIGHT = 'LEFT',
+       TOP = 'BOTTOM',
+}
+
 UF.MatchGrowthY = { TOP = 'TOP', BOTTOM = 'BOTTOM' }
 UF.MatchGrowthX = { LEFT = 'LEFT', RIGHT = 'RIGHT' }
 UF.ExcludeStacks = {
@@ -109,10 +117,8 @@ function UF:GetAuraRow(element, row, col, growthY, width, height, spacing, ancho
                if last and holder ~= last then
                        if middle then
                                holder:SetPoint(middle..anchor, last, E.InversePoints[middle]..anchor)
-                       elseif growthY == 1 then
-                               holder:SetPoint(anchor, last, inversed)
                        else
-                               holder:SetPoint(inversed, last, anchor)
+                               holder:SetPoint(anchor, last, inversed)
                        end
                elseif middle then
                        holder:SetPoint(middle..anchor, element)
@@ -363,7 +367,13 @@ function UF:Configure_Auras(frame, which)
        auras.filterList = UF:ConvertFilters(auras, settings.priority)
        auras.numAuras = settings.perrow
        auras.numRows = settings.numrows
-
+
+       if not SimpleAnchors[settings.anchorPoint] then
+               local xname = settings.growthX == "RIGHT" and "LEFT" or "RIGHT"
+               local yname = settings.growthY == "UP" and "BOTTOM" or "TOP"
+               auras.initialAnchor = yname..xname
+       end
+
        local x, y
        if settings.attachTo == 'HEALTH' or settings.attachTo == 'POWER' then
```

Hope it helps!

**Comment by kodewdle** [comment]
added it but we still have to test it, going to close this for now -- long as no issues come up should be fine ty <3
