### ISSUE TITLE
[Feature Request] Add support for phrases in Chat Keyword Alerts + System messages

### ISSUE THREAD

**Issue by Taizunz** [tukui-org/ElvUI#349]
**Is your feature request related to a problem? Please describe.**
Being limited to purely "chat" messages and 1-word keyword alerts unfortunately means that some things can be tough or outright impossible to set up for alerts.

**Describe the solution you'd like**
For system messages to be supported, i.e. to set up alerts for certain rare spawn triggers that send out zone wide system messages.

For full or part of a phrase to be supported for keyword alerts, i.e. "Hirukon cautiously emerges" to reliably know when someone has summoned Hirukon, as just having "Hirukon" as the keyword alert would fire off if anyone mentioned the rare as well, which wouldn't be ideal in this case.

**Describe alternatives you've considered**
Researching and testing other addons to see if they support this functionality.

**Additional context**
My current keyword setup where only the 1-word keywords fire off an alert:
![Wow_2022-09-17_21-27-24](https://user-images.githubusercontent.com/15648000/190915723-d20dc247-6ba1-4f2f-b0df-a0b92d03ee65.png)

**Comment by Azilroka** [comment]
It only executes on chat messages. It doesn't fire on emote / system.

**Comment by Taizunz** [comment]
I've gone ahead and updated the feature request to include the addition of support for system messages.
