### ISSUE TITLE
Actionbar 1 get mirrored randomly to another used bar. Version 12.88

### ISSUE THREAD

**Issue by Ryzom88** [tukui-org/ElvUI#350]
### What is the issue you are having?

Actionbar 1 get randomly mirrored to another used bar which means that i cant use my skills in moonkin form or when i play my shaman use my dmg skills.
only a relog resolve the problem.  

for example on my druid. 

bear is linked to bar 10 
cat is linked to bar 9
moonkin is linked to bar 7 

and when the bug happen Bar 1 show me in any stance the same as in Bar 2. When i move an icon in Bar 1, the same icon in Bar 2 move 

### What is the expected behavior?

that the bars switch as i assign it to? and not randomly?

### What actually happened?

as explaind in the first box?

### Suggested Solution/Workaround

no ideas

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Did you test with Default UI which is step 5? Because it sounds like you paged bar 1 to bar 2 using the keybind.. Shift + BarNumber is the default for WoW example.. Shift + 3 is Bar 3
