### ISSUE TITLE
[Wrath Bug Report] attempt to index local "WintergraspTimer" (a nil value)

### ISSUE THREAD

**Issue by Nnoggie** [tukui-org/ElvUI#356]
### What is the issue you are having?

Lua error when starting up the AddOn
![image](https://user-images.githubusercontent.com/27819512/192011848-116edc7a-77b9-48ec-bca8-199c706d4e9d.png)

With /edebug on:
![image](https://user-images.githubusercontent.com/27819512/192012102-4a12f4dc-5492-45a6-9d34-b4e2bcc9b095.png)

### What is the expected behavior?

Check if the frame WintergraspTimer exists before modifieing it.

### What actually happened?

Lua error popped

### Errors

```shell
3x ...aceElvUI\Wrath\Modules\Skins\Battlefield.lua:30: attempt to index local 'WintergraspTimer' (a nil value)
[string "@ElvUI\Wrath\Modules\Skins\Battlefield.lua"]:30: in function <...aceElvUI\Wrath\Modules\Skins\Battlefield.lua:9>
[string "=[C]"]: ?
[string "@ElvUI\Core\Modules\Skins\Skins.lua"]:1672: in function <ElvUI\Core\Modules\Skins\Skins.lua:1667>
[string "=[C]"]: ?
[string "@ElvUI\Core\General\Core.lua"]:1786: in function `CallLoadFunc'
[string "@ElvUI\Core\General\Core.lua"]:1801: in function `CallLoadedModule'
[string "@ElvUI\Core\General\Core.lua"]:1827: in function `InitializeModules'
[string "@ElvUI\Core\General\Core.lua"]:1936: in function `Initialize'
[string "@ElvUI\Core\init.lua"]:220: in function <ElvUI\Core\init.lua:219>
[string "=[C]"]: ?
[string "@AccountWideRaidProfiles\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...tWideRaidProfiles\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@AccountWideRaidProfiles\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@AccountWideRaidProfiles\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...tWideRaidProfiles\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
ElvUI\Wrath\Modules\Skins\Battlefied - error 
This is fixed in the dev version and will be in next release of ElvUI 
Until then you can go to ElvUI menu - Skins & disable Battlefield skin to stop the error.
