### ISSUE TITLE
[Wrath Bug Report] Lua error on every UI load

### ISSUE THREAD

**Issue by Daeke** [tukui-org/ElvUI#357]
### What is the issue you are having?

Anytime the UI loads (on initial login, on /reloadui), an immediate Lua error occurs related to Battlefield.lua (and the Wintergrasp timer specifically).

### What is the expected behavior?

No error appears.

### What actually happened?

See attached error.

### Suggested Solution/Workaround

Curious if this will no longer be an issue come Monday? Not sure how the Wintergrasp timer UI works, but maybe it's just not working until Wrath officially launches.

### Errors

```shell
Message: ...ace\AddOns\ElvUI\Wrath\Modules\Skins\Battlefield.lua:30: attempt to index local 'WintergraspTimer' (a nil value)
Time: Sat Sep 24 10:41:46 2022
Count: 1
Stack: ...ace\AddOns\ElvUI\Wrath\Modules\Skins\Battlefield.lua:30: attempt to index local 'WintergraspTimer' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI\Wrath\Modules\Skins\Battlefield.lua"]:30: in function <...ace\AddOns\ElvUI\Wrath\Modules\Skins\Battlefield.lua:9>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Modules\Skins\Skins.lua"]:1672: in function <Interface\AddOns\ElvUI\Core\Modules\Skins\Skins.lua:1667>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1786: in function `CallLoadFunc'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1801: in function `CallLoadedModule'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1827: in function `InitializeModules'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1936: in function `Initialize'
[string "@Interface\AddOns\ElvUI\Core\init.lua"]:220: in function <Interface\AddOns\ElvUI\Core\init.lua:219>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...vUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...vUI\Libraries\Core\Ace\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
asked and answered #356 maybe sure to do the stuff u checked off on the ticket as it was the latest closed issue if not mistaken
![image](https://user-images.githubusercontent.com/1479745/192114644-fb1d5f4b-3acb-4195-a333-85ec43935908.png)
