### ISSUE TITLE
[Wrath Bug Report] <Unable to change Renew Class Aura Indicator>

### ISSUE THREAD

**Issue by jurasekdominik** [tukui-org/ElvUI#359]
### What is the issue you are having?

Unable to change settings for Renew Aura Indicator.

### What is the expected behavior?

To be able to change it. (Position, size, offset, ...)

### What actually happened?

When i try to change anything under Renew there is a small game freeze and setting is not applied.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
/estatus

and show your settings for the frames in question and the filters

**Comment by jurasekdominik** [comment]
![image](https://user-images.githubusercontent.com/111370450/192152700-c3e6f901-66e0-46e8-873d-43b148d3cfbe.png)
![image](https://user-images.githubusercontent.com/111370450/192152771-4270c9fd-e5f3-4713-8123-f18d70551869.png)
https://drive.google.com/file/d/16jwQnVAUO5w_cIlNoKT7mvc47QoBG9sq/view?usp=sharing

Google drive has short video showcasing issue while /estatus open

**Comment by Azilroka** [comment]
no video showcasing it on said frames?

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/192159050-ed155017-aa85-4fe2-92da-0744f1838f4e.mp4

**Comment by 1Botanica1** [comment]
Your ElvUI is out of date.  Please update and test again with only ElvUI if you are still having issues.  
/edebug on 
Disables all other addons.

**Comment by jurasekdominik** [comment]
@1Botanica1 I sure will try that, but there are no mentions in any updates associated with Aura Indicators.

**Comment by jurasekdominik** [comment]
> no video showcasing it on said frames?

I can attach that too but it is visible on frames with settings showcased on video.  TOPRIGHT textured icon of renew and it does not move.

**Comment by jurasekdominik** [comment]
Solved this issue by removing Global Aura Indicator for Renew rank 1 (139 ID). After removal I was able to change the settings.
