### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by HolyCross944** [tukui-org/ElvUI#36]
### What is the issue you are having?

The addon is saying that my elvui is out of date and it isnt and wont install the "update" when i push update on it 

### What is the expected behavior?

it should say up to date

### What actually happened?

what i put in the first box

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by kodewdle** [comment]
This is a client issue and we are aware.  The issues here is for the addon's code now the client.  Closing this but just letting you know that the client issue is known. 🧡
