### ISSUE TITLE
[Feature Request] Combat Indicator

### ISSUE THREAD

**Issue by wotlk-addon** [tukui-org/ElvUI#360]
**Is your feature request related to a problem? Please describe.**
Combat Indicator

**Describe the solution you'd like**
To see if i'm in combat or not

**Describe alternatives you've considered**
Combat Time, does not work as I like it

**Additional context**
There use to be, from some backported version or something like this
Here is code, don't know who did it, I just updated last line to be more in check with new ElvUI style and added a row in Load_DataTexts.xml

```LUA
local E, L, V, P, G = unpack(ElvUI)
local DT = E:GetModule('DataTexts')

local function OnEvent(self, event, ...)
	if event == "PLAYER_REGEN_ENABLED" then
		self.text:SetText(L["Out of Combat"])
		self.text:SetTextColor(1, 1, 1)
		return
	elseif event == "PLAYER_REGEN_DISABLED" then
		self.text:SetText(L["In Combat"])
		self.text:SetTextColor(1, 0, 0)
		return
	end
	self.text:SetText(L["Out of Combat"])
	self.text:SetTextColor(1, 1, 1)
end

DT:RegisterDatatext('Combat Indicator', nil, {'PLAYER_ENTERING_WORLD', 'PLAYER_REGEN_ENABLED', 'PLAYER_REGEN_DISABLED'}, OnEvent, nil, nil, nil, nil, L["Combat Indicator"], nil, ValueColorUpdate)```

**Comment by Caedis** [comment]
> don't know who did it

Hi

Almost all of the datatexts still work from ExtraDataTexts, but I am probably going to work on porting them into here.
