### ISSUE TITLE
[Wrath Bug Report] quest items do not always have the yellow exclamation indicator

### ISSUE THREAD

**Issue by telias82** [tukui-org/ElvUI#361]
### What is the issue you are having?

items that start quests do not always have the giant exclamation mark on their icon.

### What is the expected behavior?

that all items that start quests should have this indicator on them

### What actually happened?

most items were missing it. I checked with elvui bags off and there were a lot more icons with the yellow ! on them

### Suggested Solution/Workaround

![image](https://user-images.githubusercontent.com/55420496/192285657-914e83f4-79aa-4ade-8051-0c0160d354a4.png)
![image](https://user-images.githubusercontent.com/55420496/192285934-0488673b-babe-432e-a86a-026e3cb3f603.png)

### Errors

```shell
no errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Its not a bug. The Bags skin doesn't have the correct code for quest starters.
