### ISSUE TITLE
[Classic Bug Report] Bag closes with auto-toggle off

### ISSUE THREAD

**Issue by syswis** [tukui-org/ElvUI#364]
### What is the issue you are having?

I have the auto-toggle turned off for everything, but seems to have effects only for opening the bags.

They do not open if auto-toggle is off, and that's correct, but they do close, even when opening vendor window, and that's annoying.
I don't have other addons that interact with the bags.

### What is the expected behavior?

If auto-toggle is off, it should not change the state of the bag.

### What actually happened?

Bag window auto closes both when opening or closing vendor, mail, banker, AH window.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
reopen if needed :)
