### ISSUE TITLE
[Wrath Bug Report] Heal Prediction not working with new Paladin spell ranks

### ISSUE THREAD

**Issue by Toygeron** [tukui-org/ElvUI#365]
### What is the issue you are having?

Heal Prediction with new ranks of Flash of Light (Rank 8) and Holy Light (Rank 12) do not work. Previous ranks work as intended.

### What is the expected behavior?

Heal Prediction should show up as a UI element for any qualifying target of a heal.

### What actually happened?

Heal prediction is not working for the Paladin spells Flash of Light Rank 8 or Holy Light Rank 12.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Blizzard handles the direct heal heal prediction and seems they haven’t added them for all healing spells, highest ranks.
