### ISSUE TITLE
[Wrath Bug ReportA] Ace3 windows no longer have visible close button in title bar

### ISSUE THREAD

**Issue by crimsoncoyote** [tukui-org/ElvUI#366]
### What is the issue you are having?

In previous ElvUI versions, there was a visible 'X' button in the title bar of Ace3 windows to close the windows. In ElvUI v12.89+ the 'X' button is no longer visible, though you can click where it should be and the close functions as expected.

### What is the expected behavior?

Title bar 'X' button for closing a window should be visible. 

### What actually happened?

The 'X' button is not visible. You can still click where it is supposed to be to close the window.

This appears to be a skinning issue caused by the early load changes in [this commit](https://github.com/tukui-org/ElvUI/commit/7cbdc0935d46754a1135114b654630fa0635d5c3), specifically the changes in Ace3.lua

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Show the steps you said you did.

/estatus and the config window.

**Comment by crimsoncoyote** [comment]
All addons Enabled (should be an X in the top-right corner)
![image](https://user-images.githubusercontent.com/1790997/196761395-17aa4026-1390-43b3-9d3a-de0d8e61801c.png)

Addons Enabled, ElvUI disabled
![image](https://user-images.githubusercontent.com/1790997/196760858-73fe8179-0049-4ce0-bdfe-4030ae2a85c0.png)

`/edebug on`, with only Classic Loot Manager Enabled
![image](https://user-images.githubusercontent.com/1790997/196761144-1fe55317-697e-484b-afb0-f9447462a332.png)

I have since found the issue presents with any one of these individual addons enabled alongside ElvUI. There may be others, this is just what I have installed:
Extended Character Stats v3.0.4
GatherMate2
Nova World Buffs
Questie v7.4.1
RatingBuster
ThreatPlates
ThreatClassic2
TomTom

Prior to the ElvUI 12.89 release, the X was correctly skinned with these addons enabled. Is there a common thread with these addons?

**Comment by Caedis** [comment]
Do these steps in order.
1) Type in chat in game /edebug on
2) Test - Do you still have the issue?
3) If you still have the issue/error - type in chat in game /estatus
4) Upload a full, uncropped screenshot showing the issue and the estatus.
5) If you are finished with debugging, you can enable your AddOns back with: /edebug off

**Comment by Caedis** [comment]
Issue is cause another addon updated Ace3. We also updated it in the dev version if you want to try that.

**Comment by crimsoncoyote** [comment]
I'll give the dev version a try

**Comment by crimsoncoyote** [comment]
Unfortunately, the dev version does not seem to resolve the issue. Is there anything else I can try or info I can provide?
