### ISSUE TITLE
[Wrath Bug Report] Health prediction not showing for me, showing other's incoming heals though

### ISSUE THREAD

**Issue by Joeydeezul** [tukui-org/ElvUI#367]
### What is the issue you are having?

Health Prediction is not showing my incoming heal predictions for both my own individual unit frame or party group frames. It was working perfectly fine yesterday, but has stopped working for me when I logged in today. The party frames still show incoming health predictions when someone else in the group uses a heal, but it does not show health predictions for my healing. 

I am using 12.91 version of ElvUI, I have disabled all other addons other than ElvUi and the problem does not resolve itself by disabling all other addons. 

![WoWScrnShot_093022_143610](https://user-images.githubusercontent.com/114771786/193337292-26b3c886-8a51-4d0f-9b5d-1c9d1fd16d55.jpg)
![WoWScrnShot_093022_143620](https://user-images.githubusercontent.com/114771786/193337294-c766497d-a60c-412c-8657-f75a105ed85d.jpg)
![WoWScrnShot_093022_143649](https://user-images.githubusercontent.com/114771786/193337296-8cd46297-ce53-4c39-8acf-4802374a85cd.jpg)
![WoWScrnShot_093022_143656](https://user-images.githubusercontent.com/114771786/193337298-004c6c67-cb60-498e-9d92-003e298d56ae.jpg)

### What is the expected behavior?

When I heal members of my group, there should be a lightly colored indicator showing the predicted amount of health that will be healed. 

### What actually happened?

When I heal myself or members of my group, the predicted amount of health is not showing. This is not showing up on party members in the party frame, or on my own individual bar when using it on myself when not grouped. 
![WoWScrnShot_093022_145244](https://user-images.githubusercontent.com/114771786/193337687-0a76a89d-1e9c-4466-bc01-364fda0010d2.jpg)

### Errors

```shell
I am not experiencing any errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Phillyjawn** [comment]
Did this get resolved? I am also having this issue
