### ISSUE TITLE
[Wrath Bug Report] WoW crash at last boss in Ahn'kahet

### ISSUE THREAD

**Issue by Chalapacho** [tukui-org/ElvUI#369]
### What is the issue you are having?

The last Boss of Ahn'kahet spawns adds, that are clones of the players in the group. When i target these adds, my WoW crashes. 
Mouseover and Nameplates seems to work fine, but when they start casting at you, you automatically target them, and WoW crashes.

My ElvUI version is 12.91

### What is the expected behavior?

No crash

### What actually happened?

Here is the LUA Stack of the crash:

```
[C]: in function 'SetOwner'
Interface\AddOns\ElvUI\Core\General\Tags.lua:1107: in function <Interface\AddOns\ElvUI\Core\General\Tags.lua:1104>
(tail call): ?
...ce\AddOns\ElvUI\Libraries\Core\oUF\elements\tags.lua:698: in function 'UpdateTag'
...ce\AddOns\ElvUI\Libraries\Core\oUF\elements\tags.lua:589: in function <...ce\AddOns\ElvUI\Libraries\Core\oUF\elements\tags.lua:584>
```

I got many custom texts in use for my unit frames, maybe this triggers this exception. 

Here is the WoW Error file: https://pastebin.com/mEXyt2QW
And here is my ElvUI profile: https://pastebin.com/zygcBF1z

### Suggested Solution/Workaround

My workaround was to comment out the lines 1107 - 1109 of the Tags.lua file. I don't know what these lines do, but i didn't notice any differences. At least i got no more crashes.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
That npctitle tag is part of the scantooltip... that's the crash that everyone is experiencing even without ElvUI. This is a Blizzard bug with the tooltip code.

**Comment by Azilroka** [comment]
Try the development version. I altered the Tags to bypass the limitation until Blizzard fixes it

**Comment by Chalapacho** [comment]
It works, thanks :)
