### ISSUE TITLE
[Wrath Bug Report] <random frame drop on macbook pro m1 pro>

### ISSUE THREAD

**Issue by tabask0** [tukui-org/ElvUI#372]
### What is the issue you are having?

It started to get worse but i get random frame drops from 75 (with vertical sync) to 11-12 and my interface moves when i click on something untill the frame goes back to 75. It makes everything unclickable and the UI scale also its betting bigger for few seconds and then back to normal, all of these things are happening only when the frame drops randomly. 

I am playing on a Macbook Pro. I did try to reset my all ui, i delete game configs, WTF, cahe etc. I updated several times and the result is still the same.

### What is the expected behavior?

It should not drop frames or resize the UI

### What actually happened?

i get random frame drops from 75 (with vertical sync) to 11-12 and my interface moves when i click on something untill the frame goes back to 75. It makes everything unclickable and the UI scale also its betting bigger for few seconds and then back to normal, all of these things are happening only when the frame drops randomly. 

### Errors

```shell
No errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
So you tried with just ElvUI? Because that's what the last checkbox is. Are you alt tabbing and playing in window mode?

**Comment by Caedis** [comment]
Did you also try with the default blizzard ui (aka 0 addons enabled)?

**Comment by tabask0** [comment]
yes i did and its not happening, its an elvui issue

**Comment by Caedis** [comment]
Does it happen in retail?
