### ISSUE TITLE
[Wrath Bug Report] Mouse over quest reward prompts a lua error

### ISSUE THREAD

**Issue by Feppeltanten** [tukui-org/ElvUI#378]
### What is the issue you are having?

When I click a quest in the "Objectives" interface to the right (as shown in first picture) and then put the mouse over the rewards to look at them I get this luaerror (picture 2). 

Message: Interface_Wrath\FrameXML\QuestInfo.lua:1017: Invalid quest item in SetQuestLogItem("type", index [, questID])
Time: Sun Oct  9 02:16:32 2022
Count: 22
Stack: Interface_Wrath\FrameXML\QuestInfo.lua:1017: Invalid quest item in SetQuestLogItem("type", index [, questID])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetQuestLogItem'
[string "@Interface_Wrath\FrameXML\QuestInfo.lua"]:1017: in function <Interface_Wrath\FrameXML\QuestInfo.lua:1013>

Locals:

This doesn't happen with every quest, but with most of them. I have no idea why it happens.

1 ![WoWScrnShot_100922_021625](https://user-images.githubusercontent.com/86558175/194732038-e0a93195-6ea5-47f8-ad52-a9e77dd2328d.jpg) 

2  ![WoWScrnShot_100922_021628](https://user-images.githubusercontent.com/86558175/194732068-761199b4-e393-4d42-8ef7-9d510a8d5e66.jpg) 

### What is the expected behavior?

Wanted outcome is for there not to be an error and to see the item stats

### What actually happened?

There was a luaerror and you can't see the stats of the items

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Message: Interface_Wrath\FrameXML\QuestInfo.lua:1017: Invalid quest item in SetQuestLogItem("type", index [, questID])

**Comment by Azilroka** [comment]
That is Blizzard's Interface.. Which means it will happen with the Default UI

**Comment by Feppeltanten** [comment]
> That is Blizzard's Interface.. Which means it will happen with the Default UI

Hmm, that's weird. It doesn't happen when I turn ElvUi off
