### ISSUE TITLE
[Retail Bug Report] <Backpack Only not work without Bags(Enabled)>

### ISSUE THREAD

**Issue by awedy01** [tukui-org/ElvUI#38]
### What is the issue you are having?

As the title says, Backpack Only option within "Bag Bar" tab wont work if you have Bags disabled

### What is the expected behavior?

It should hide all my other bags from the Bag Bar

### What actually happened?

It will only hide my other bags IF "Bags" is enabled

A bit of more details:
![image](https://user-images.githubusercontent.com/57992981/140315077-98eb8198-decf-4a74-b4f7-cfd89f1cf034.png)
I use Bags > Bag Bar without "Bags" actually being enabled.
As Bag Bar option is usable without ElvUI bags, and "Backpack Only" option is within "Bag Bar", i assume it should also work without ElvUI Bags
- Tried with "edebug on"
- Tried without other bag addon
- Tried with latest DEV edition of ElvUI as well as the 12.48 version of elvui

Talked it out with Merathilis(check in #elvui-retail-support for more logs)
1:31 PM] Merathilis: ah, know i get it
[1:31 PM] NightLite: awesome
[1:31 PM] Merathilis: sorry, never used the bag bar
[1:31 PM] NightLite: I assume it(backpack only option) should work because its also within the "Bag Bar" tab which works without "Bags" enabled 
[1:31 PM] NightLite: So i think it can be called a bug
[1:36 PM] Merathilis: I would agree, yes

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by kodewdle** [comment]
Thanks for this!  I have fixed the problem here: d12234767778c49b02777f1f49d39e0c7230cc69

Have a great day. 🌼
