### ISSUE TITLE
[Classic Bug Report] <Title hereMalygos drake health not shown>

### ISSUE THREAD

**Issue by meuhh5** [tukui-org/ElvUI#386]
### What is the issue you are having?

When entering in last phase on Malygos (25man or 10man), the health of the drakes are not shown on the UI.
I have to manually take Malygo's target to be able to heal.

Is there an option in the ElvUI settings to change player's health with drake's health ?

### What is the expected behavior?

See the drake's health instead of player's health in the raid frame

### What actually happened?

I still see player's health on last phase

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Blizzard Issue
