### ISSUE TITLE
[Wotlk Classic Bug Report] Quartermasters Recipes sticky after interaction

### ISSUE THREAD

**Issue by Laggsteryo** [tukui-org/ElvUI#388]
### What is the issue you are having?

I just talked to a Quartermaster and as soon as the trader window opens, it shows me a recipe that keeps on sticking, even if I close the window an dwithout hovering over it. it happens on all quartermasters. it disappears when I go to the next page of the vendor. seems to be compability issue with DataStore by Thaoky. Happens with elvui itself and with the addition of benikUi, tried every combination.

https://user-images.githubusercontent.com/115883666/195991795-857fc265-07c7-4131-bf9d-3a4a16fef26f.mp4

### What is the expected behavior?

the recipe shouldnt show at all unless I hover over it with my mouse and it should disappear when I close the window

### What actually happened?

above

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using /edebug on? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.
