### ISSUE TITLE
[Wrath Bug Report] Taint using the LFG tool

### ISSUE THREAD

**Issue by coolmodi** [tukui-org/ElvUI#389]
### What is the issue you are having?

Taint when using the LFG tool, log below. Version is 12.91 from dev branch, currently at https://github.com/tukui-org/ElvUI/commit/60ba0b51dcd37e5a341d10b19ebd2ced655bc152

```
10/16 02:31:40.536  Global variable UIDROPDOWNMENU_MENU_LEVEL tainted by ElvUI - Interface\FrameXML\UIDropDownMenu.lua:40
10/16 02:31:40.536      securecall()
10/16 02:31:40.536      Interface\FrameXML\UIDropDownMenu.lua:74 UIDropDownMenu_Initialize()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:168 LFGBrowseFrame:SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:67
10/16 02:31:40.536  Execution tainted by ElvUI while reading UIDROPDOWNMENU_MENU_LEVEL - Interface\FrameXML\UIDropDownMenu.lua:890 UIDropDownMenu_GetSelectedID()
10/16 02:31:40.536      Interface\FrameXML\UIDropDownMenu.lua:764 UIDropDownMenu_Refresh()
10/16 02:31:40.536      Interface\FrameXML\UIDropDownMenu.lua:869 UIDropDownMenu_SetSelectedValue()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:169 LFGBrowseFrame:SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:67
10/16 02:31:40.536  An action was blocked because of taint from ElvUI - Search()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:225 LFGBrowse_DoSearch()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGBrowse.lua:178 LFGBrowseFrame:SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
10/16 02:31:40.536      Interface\AddOns\Blizzard_LookingForGroupUI\Blizzard_LFGListing.lua:67
```

### What is the expected behavior?

No taint.

### What actually happened?

Taint.

### Suggested Solution/Workaround

Line 459 and 461 in https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/General/Toolkit.lua cause the taint to occur. Commenting out those 2 lines fixes the taint, i.e. doing this:
```
if not object._SetNormalTexture then -- bullshit WoW10
		--CheckTextureAPI(mk, SetNormalTexture, 'SetNormalTexture')
		CheckTextureAPI(mk, SetPushedTexture, 'SetPushedTexture')
		--CheckTextureAPI(mk, SetCheckedTexture, 'SetCheckedTexture')
		CheckTextureAPI(mk, SetDisabledTexture, 'SetDisabledTexture')
		CheckTextureAPI(mk, SetHighlightTexture, 'SetHighlightTexture')
	end
```
The errors now popping up can be fixed by changing all instances of `:SetNormalTexture()` and `:SetCheckedTexture()` to `:SetNormalTexture("")` and `:SetCheckedTexture("")`. Not sure about side effects, especially for retail or DF, but seems to work in wrath so far.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Meivyn** [comment]
> Line 459 and 461 in https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/General/Toolkit.lua cause the taint to occur. Commenting out those 2 lines fixes the taint, i.e. doing this:
> 
> ```
> if not object._SetNormalTexture then -- bullshit WoW10
> 		--CheckTextureAPI(mk, SetNormalTexture, 'SetNormalTexture')
> 		CheckTextureAPI(mk, SetPushedTexture, 'SetPushedTexture')
> 		--CheckTextureAPI(mk, SetCheckedTexture, 'SetCheckedTexture')
> 		CheckTextureAPI(mk, SetDisabledTexture, 'SetDisabledTexture')
> 		CheckTextureAPI(mk, SetHighlightTexture, 'SetHighlightTexture')
> 	end
> ```
> 

This also seems to taint the spell book, which prevents the player to click spells from it. 

![image](https://user-images.githubusercontent.com/793322/197685159-c70e11bc-de82-403e-a7a4-b8a0b1719db5.png)

**Comment by Repooc** [comment]
Have you tried the beta branch as i believe that was removed now https://github.com/tukui-org/ElvUI/blob/beta/ElvUI/Core/General/Toolkit.lua

**Comment by Meivyn** [comment]
This indeed seems to be fixed on the beta branch.
