### ISSUE TITLE
When changing Specc, bars won't swap spells

### ISSUE THREAD

**Issue by Thel82** [tukui-org/ElvUI#393]
### What is the issue you are having?

When I'm changing from Disc -> Shadow I continiously need to re-enter my spells manually from the spellbook onto my actionbars.
![lua 1](https://user-images.githubusercontent.com/116022178/196236566-c6880523-b224-4aaa-8c08-051f7eb37b02.jpg)
![lua 2](https://user-images.githubusercontent.com/116022178/196236570-9b92d750-dd2d-4527-8e49-9a5aefa2c49a.jpg)

### What is the expected behavior?

It should be automatically swap the spells like it does for my paladin.
![Lua Elvui switching specc](https://user-images.githubusercontent.com/116022178/196236616-0bde8d9f-7727-494d-83d4-ef923340bef9.jpg)
![estatus](https://user-images.githubusercontent.com/116022178/196236661-915f789f-5178-4baf-a6d1-a6a168cbe9f7.jpg)

### What actually happened?

When I'm changing from Disc -> Shadow I continiously need to re-enter my spells manually from the spellbook onto my actionbars.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
the spells on the bars is not handled by elvui.
for the errors, try 12.99 and see if u still get those errors, if u still do have errors, do `/edebug on` and show `/estatus` window in the same pic as the errors (1st page is enough typically)
