### ISSUE TITLE
[Wrath Bug Report] Blizzard added the Vehicle Seat UI

### ISSUE THREAD

**Issue by hepkat** [tukui-org/ElvUI#395]
### What is the issue you are having?

Blizzard added the Vehicle Seat UI. Can't move it with ElvUI yet.

### What is the expected behavior?

/moveui should allow me to move the vehicle seat UI frame.

### What actually happened?

/moveui does not allow you to move the vehicle seat UI that has now been added.

Screenshot:

https://i.imgur.com/77d4Tbq.jpg

### Suggested Solution/Workaround

Enabled the movement of that frame again (like in retail).

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
It is enabled in the development version.
