### ISSUE TITLE
[Feature Request] DataText Average Item Level

### ISSUE THREAD

**Issue by Belden1** [tukui-org/ElvUI#397]
**Is your feature request related to a problem? Please describe.**
Lately in WotLK, item level has become a thing now, some old macros work but not always, same with WA, but untrusted/non-working...

**Describe the solution you'd like**
Maybe there could be one DataText where it would show characters average item level, not sure how it could be done with targets item level, but maybe an small HUD shows targets ilvl...

**Describe alternatives you've considered**
TacoTip but I don't like GS or how they work with ElvUI is not so good what I remember...

**Additional context**
-

**Comment by Repooc** [comment]
https://www.curseforge.com/wow/addons/wratharmory-elvui-plugin
https://www.curseforge.com/wow/addons/wratharmory-elvui-plugin
is a good alternative...
