### ISSUE TITLE
[Feature Request] Ability to Track All Kinds of Currency

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#403]
**Is your feature request related to a problem? Please describe.**
< A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] >

Not a bug.

**Describe the solution you'd like**
< A clear and concise description of what you want to happen. >

As a user with a lot of alts, I would like to be able to track a variety of currencies across all of the alts using ElvUI, so I know where my money / tokens are at. Gold... Badges.... Cooking Awards... I want to be able to turn on what I want to see in the currency summary widget.

Character Name | Gold {GOLD ICON} Silver {Silver Icon} Copper (Copper Icon) | Badges (Badge Icon)... you already have a design that would work! (=

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >

**Additional context**
< Add any other context or screenshots about the feature request here. >

![image](https://user-images.githubusercontent.com/55365231/197272587-a0f19c5b-b7ca-43d8-af41-172e03723254.png)

**Comment by Caedis** [comment]
Blizzard limitation. Can only track 3 before DragonFlight.

**Comment by Gogo1951** [comment]
Hey @Caedis ,

You record the values coming out of the UI and just store them as a saved variable anyway, yeah? In the saved variables there's a list of gold for each toon you have. Seems like it'd be easy enough to just record all of the currencies and then display the values you have stored. What am I missing? (=

**Comment by Caedis** [comment]
While it would be possible, we are going to leave it to any plugin that wants to do it.
Saving every single currency a character has into the SavedVariables will affect loading time the more characters you have.

I have also talked it over with the devs, and they agree.

**Comment by Gogo1951** [comment]
I don't quite buy that it would impact load time... but I understand it's a feature you'd rather punt to a plug-in. Fair enough.

**Comment by Azilroka** [comment]
You don't buy that? Load up around 500 WA into your saved variables and see if that affects your load time.

Each currency would have to store all the data on every toon.. there is almost 2000 currencies in the game that can be iterated.

**Comment by Gogo1951** [comment]
I don't buy it. Not for Classic. There's just what... badges and honor and cooking tokens? And just reading them in and storing them as a saved variable is trivial.

I already started on a plug-in. I feel like you should be honest with people, and it's perfectly honest to say this is a better fit as a plugin. It's less honest to say... "load times" and "we can only pull 3"... those were just blow-off answers.

I'm able to save all of the currency tokens in Classic in a trivial amount of time -- refreshes on load and boss kill events for now, then loading the saved variables is also trivial.

**Comment by Azilroka** [comment]
MAX_WATCHED_TOKENS has a limitation of 3 in Wrath unless you set it higher and risk taints. That is and was the correct answer.

As for your statement of only badges and honor and cooking tokens.. If you iterate all the tokens there is more than 5 that you are talking about. There is hidden ones. Now if you do a preset list.. of course it will be easier. If you cache the current currency ui you can also bypass it also.

So as you say if you are storing it in just a basic savedvariable and not store it in the global table like we would.. yea it wouldn't transfer with your profile between clients.

You are clearly only talking about Wrath and we are not. We are talking about ElvUI on 3 current WoW Flavors.

**Comment by Azilroka** [comment]
`/run local n = 0; for i = 1, 2000 do local name = GetCurrencyInfo(i) if name ~= '' then n = n + 1 end end print(n)`

Shows 24 for Wrath

`/run local n = 0; for i = 1, 2000 do local info = C_CurrencyInfo.GetCurrencyInfo(i) if info and info.name ~= '' then n = n + 1 end end print(n)`

Shows 306 on DragonFlight
