### ISSUE TITLE
[Feature Request] Heal Prediction Style

### ISSUE THREAD

**Issue by Klaa2** [tukui-org/ElvUI#41]
**Is your feature request related to a problem? Please describe.**
< No >

**Describe the solution you'd like**
< I would like for the Unit Frame Health Prediction Absorbs Style to have a new option, making it so that we can have absorbs that only cover the health bar to the left rather than extending past the current health to the right. PLZ & TY.  >

**Describe alternatives you've considered**
< Using another Unit Frame addon >

**Additional context**
< The first photo is using ELVUI Player frame and shows the Absorb bar extending both left and right past the actual/current health. The Second photo is using Z-Perl Unit Player Frame and shows the Absorb Bar extending only to the left, like most and nearly all Unit Frame addons do. The way that ELVUI handles absorbs in this manor makes it difficult for one to guess how much absorb one has left. >
![WoWScrnShot_110521_085826](https://user-images.githubusercontent.com/93785664/140545196-f2547256-5a68-4ed3-88ba-8fdde618e6df.jpg)
![WoWScrnShot_110521_090442](https://user-images.githubusercontent.com/93785664/140545791-3c82bf28-ed40-401e-943f-329768bf79a9.jpg)

**Comment by Azilroka** [comment]
Did you try the other Styles? You currently have Wrapped enabled.

**Comment by Klaa2** [comment]
Tried them ann im afraid.
