### ISSUE TITLE
[Retail Bug Report] <Right click to remove buff>

### ISSUE THREAD

**Issue by Alleister19** [tukui-org/ElvUI#415]
### What is the issue you are having?

Cannot right click a buff near the minimap to remove the buff

### What is the expected behavior?

Right click the buff should remove the buff (if it can be removed)

### What actually happened?

I tried to right click the mount buff or stealth but it does not remove it

### Suggested Solution/Workaround

I have disabled ElvUI and it works properly, the bugs seems to be within ElvUI

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by aarhusbhoy** [comment]
Same problem here, have used edebug on.  The dfault bugg bar when enabled works, but the elvui one does not

**Comment by Caedis** [comment]
Fixed on dev

**Comment by staynasty** [comment]
@Caedis still broken even with the dev download.

**Comment by sellentis** [comment]
same in 12.93

**Comment by Mr-nUUb** [comment]
Seems fixed in 12.95
