### ISSUE TITLE
[Retail Bug Report] Can't open the bank

### ISSUE THREAD

**Issue by Mordhakan** [tukui-org/ElvUI#417]
### What is the issue you are having?

I can't open the bank when I click on the npc
I have all my addons desactivate except elvui and elvui options. I can open the reagent bank with the shift click

### What is the expected behavior?

Windows should open like usually

### What actually happened?

Nothing. The windows doesnt open at all.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by bunjiboys** [comment]
Getting the following LUA error

```
Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua:902: bad argument #1 to 'GetBagSlotFlag' (outside of expected range 0 to 4294967295 - Usage: local isSet = C_Container.GetBagSlotFlag(bagIndex, flag)) 
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:902: in function `GetFilterFlagInfo'
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:917: in function `GetBagAssignedInfo'
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:1149: in function `SetBagAssignments'
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:1131: in function `UpdateLayout'
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:2186: in function `ShowBankTab'
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:2237: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119> 
```

**Comment by Repooc** [comment]
fixed in the dev branch already just not released yet
