### ISSUE TITLE
[TBC Bug Report] Heal Prediction doesn't shows HoT and shows direct heal only

### ISSUE THREAD

**Issue by Dhorm** [tukui-org/ElvUI#42]
### What is the issue you are having?

After I updated TBC ElvUI to v2.21, I don't see any heal prediction for HoT spells.
I enabled all Heal prediction in player/party/raid unit frame but it always shows heal prediction for direct heal only.
It used to show HoT spells as well.
Please check and fix this issue.

### What is the expected behavior?

After I updated TBC ElvUI to v2.21, I don't see any heal prediction for HoT spells.
I enabled all Heal prediction in player/party/raid unit frame but it always shows heal prediction for direct heal only.

### What actually happened?

After I updated TBC ElvUI to v2.21, I don't see any heal prediction for HoT spells.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by SirDaddy66** [comment]
can confirm, is not working

**Comment by SirDaddy66** [comment]
devestating on Resto druid

**Comment by Azilroka** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/163
