### ISSUE TITLE
[Retail Bug Report] Quest frame coloring makes the text hard to read.

### ISSUE THREAD

**Issue by prvlaar** [tukui-org/ElvUI#420]
### What is the issue you are having?

Update 26-10-2022 release 

![image](https://user-images.githubusercontent.com/1567234/198014906-9a649f2a-10a5-4aea-afe5-bec4ac2cffc7.png)

### What is the expected behavior?

Light background/blizzard

### What actually happened?

Background seems to have dropped away.

### Suggested Solution/Workaround

![image](https://user-images.githubusercontent.com/1567234/198015126-901586f0-cc60-4c9d-962e-f29f6bcf1f96.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by GhostReapersWorld** [comment]
I'd like to add that it seems to me that parchment background is not shown. I have the same issue with NPC Dialog frames. If you use the Parchment Remover in the "Skins" section, you can temporarily force ElvUI to display the text in white with black background which makes it readable.

**Comment by prvlaar** [comment]
Latest version has resolved this.
