### ISSUE TITLE
[Retail Bug Report] Error "Usage: self:SetHighlightTexture(asset [, blendMode])"

### ISSUE THREAD

**Issue by dakhran** [tukui-org/ElvUI#421]
### What is the issue you are having?

On changing zones, the following error is reported in BugSack.
```
1x Usage: self:SetHighlightTexture(asset [, blendMode])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:456: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:454>
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
[string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>

Locals:
(*temporary) = "Usage: self:SetHighlightTexture(asset [, blendMode])"
```

### What is the expected behavior?

No error should occur.

### What actually happened?

Error occurs.

### Errors

```shell
1x Usage: self:SetHighlightTexture(asset [, blendMode])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:456: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:454>
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
[string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>

Locals:
(*temporary) = "Usage: self:SetHighlightTexture(asset [, blendMode])"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by endoze** [comment]
While this likely doesn't actually fix the underlying issue, you can get the error to stop by changing the code in ElvUI/Core/Modules/ActionBars/ActionBars.lua.

```lua
hooksecurefunc(Button, 'SetHighlightTexture', function(btn, tex)
  if tex ~= btn.hover and btn.hover then -- it seems btn.hover is nil which is the actual cause of the error
    Button:SetHighlightTexture(btn.hover)
  end
end)
```

When we hook this function, the btn passed in doesn't have a value for hover currently.

**Comment by Thaonnor** [comment]
> > **Same Error** After I updated to the latest game version and ElvUI 12.95, some of my actionbar key combinations are break down now, but also with the error message below. Specifically, when I press a key combination that including one of mouse keys, there are no feedback from the game, like CTRL+MOUSEKEY3/4/5 or ALT+MOUSEKEY3/4/5.
> > Here's a case I don't know if it can be helpful:
> > > 1 Activate the key-binding mode of ElvUI；
> > > 2 Move cursor to the actionbar cell and press CTRL+M3；
> > > RESULT: Now CTRL+M3 will be work as usual (with the same error), but once game reload it's break again.
> > 
> > 
> > And I found if I search "CTRL" in the original game option menu, the key combination like CTRL+MOUSEKEY3/4/5 will be displayed in the search result, but they are actually can not be find in the shortcuts > actionbars' menu (I use simplified Chinese as the language of my game interface so I don't know what is the exactly menu name so I just try guessing).
> > So...is this possible to fix?
> > **Error:**
> > ```
> > Message: Usage: self:SetHighlightTexture(asset [, blendMode])
> > Time: Sat Oct 29 16:52:36 2022
> > Count: 3
> > Stack: Usage: self:SetHighlightTexture(asset [, blendMode])
> > [string "=[C]"]: ?
> > [string "=[C]"]: ?
> > [string "=[C]"]: in function `SetHighlightTexture'
> > [string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:456: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:454>
> > [string "=[C]"]: in function `SetHighlightTexture'
> > [string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
> > [string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>
> > 
> > Locals: 
> > ```
> 
> After update to the ElvUI 12.98, this seems has been solved, thanks for the dev team, thank you @endoze!

I am still seeing this on version 12.98.

**Comment by chompers1** [comment]
I'm having the same error, using 12.99. It seems to be always active, as in I don't need to use a certain ability of keybinding for the error to show.

> Message: Usage: self:SetHighlightTexture(asset [, blendMode])
Time: Wed Nov  2 11:07:43 2022
Count: 5
Stack: Usage: self:SetHighlightTexture(asset [, blendMode])
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:457: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:455>
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
[string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>

Locals:

**Comment by Azilroka** [comment]
This is fixed in 12,99

> I'm having the same error, using 12.99. It seems to be always active, as in I don't need to use a certain ability of keybinding for the error to show.
> 
> > Message: Usage: self:SetHighlightTexture(asset [, blendMode])
> > Time: Wed Nov  2 11:07:43 2022
> > Count: 5
> > Stack: Usage: self:SetHighlightTexture(asset [, blendMode])
> > [string "=[C]"]: ?
> > [string "=[C]"]: ?
> > [string "=[C]"]: in function `SetHighlightTexture' [string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:457: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:455> [string "=[C]"]: in function `SetHighlightTexture'
> > [string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
> > [string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>
> 
> Locals:

This isn't 12.99

Line 457 is a SetPoint.
https://github.com/tukui-org/ElvUI/blob/v12.99/ElvUI/Core/Modules/ActionBars/ActionBars.lua#L457
