### ISSUE TITLE
[Retail Bug Report] Moving action bar icon activates ability

### ISSUE THREAD

**Issue by dakhran** [tukui-org/ElvUI#422]
### What is the issue you are having?

While editing action bars and moving abilities around, any click on the bar will activate the ability on mouse down, even if the bar locked and the pick up action key is held. Confirmed that this does not occur in the new default UI when ElvUI is disabled and the default UI's "Lock ActionBars" is checked and the pick up key is used. The state of the ElvUI ActionBar general option "Key Down" has no impact on the issue whether checked or unchecked.

Also, the default UI's Lock ActionBars settings seems to have no impact on ElvUI, but ElvUI does override the default, sometimes even without updating the interface.

### What is the expected behavior?

When action bar editing is locked, I should be able to hold the pick-up key and move an icon without activating the ability.

### What actually happened?

Specific test: on warlock, moving an icon for Drain Life on Bar 1. Action bar editing is locked, ALT is set for the pick up key. Holding ALT and clicking with either mouse button causes a "You have no target" alert and sound, as if the ability is activated. I am still able to drag the ability to a new bar position as expected.

Tested with multiple abilities and classes, cooldown or not, targeted power or not, in all cases the icon's ability/item/macro is activated on mouse down prior to the drag event even when pick key is held.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
Fixed on dev

**Comment by dakhran** [comment]
Confirmed to work with 12.95.
