### ISSUE TITLE
[Retail Bug Report] Talking Head Frame missing from Anchors and appear randomly at the bottom and top of screen

### ISSUE THREAD

**Issue by PiotrLech94** [tukui-org/ElvUI#427]
### What is the issue you are having?

Talking Head Frame dissapeared while anchors are toggled, additionally it appear randomly at the top and the bottom of the screen.

### What is the expected behavior?

Talking Head Frame previously was visible while anchors were toggled and it was being displayed in the correct place.

### What actually happened?

Talking Head Frame dissapeared while anchors are toggled, additionally it appear randomly at the top and the bottom of the screen.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Marving1023** [comment]
go to here : https://github.com/tukui-org/ElvUI/issues/441#issuecomment-1293744579

**Comment by brutt87** [comment]
I have the issue too, moving the talking head frame with Edit Mode from the game options won't solve it, it will reappear on the old position.
I have found that the position of the talking head frame follows the "Loot/Alert Frames" mover from ElvUI.

**Comment by judgdredd** [comment]
This is 100% happening. Blizzards Talking Head is tied to Elvui's Loot / Alert Frames, which is very annoying and it can't be disabled at all, so you have to move your Loot / Alert Frame off to the side. Elvui option The Talking Head Scale in Skins is not working also, setting it to 50% does nothing.

**Comment by brutt87** [comment]
Weird, scaling it from ElvUI options works fine here.
