### ISSUE TITLE
[Classic Bug Report] <Client not updating>

### ISSUE THREAD

**Issue by Chianah** [tukui-org/ElvUI#43]
### What is the issue you are having?

Have done a clean re-install of Tukui Client. Client still reporting that ElvUI Reatil and ElvUI TBC are out of date and will not update them. Update seems to stop a little past half-way through. Suggestions
![1](https://user-images.githubusercontent.com/26779256/140595308-59a041bb-6795-4428-8ea6-53687b83f346.JPG)
![2](https://user-images.githubusercontent.com/26779256/140595309-a71aaeda-0eb2-495c-8c89-d724b2b6f466.JPG)

?

### What is the expected behavior?

Because it usually does...?

### What actually happened?

Neither ElvUI for TBC or Retail WoW will update.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Repooc** [comment]
ElvUI will show as out of date on the client as ElvUI has combined the three versions (easy explanation) and the client only sees the first toc which is the Classic one.

It will show as Classic Version on the client and out of date. 

Log into the game and it will be correct , in game (not client).

The client should be updated soon ™️
