### ISSUE TITLE
[Retail Bug Report] Can't Shift-Click to Move Buttons on Action Bars Without Activation

### ISSUE THREAD

**Issue by Calesta** [tukui-org/ElvUI#430]
### What is the issue you are having?

Holding Shift and clicking a button to move it to another location now uses the item/spell before allowing me to drag it.

I have the following selections.

![Shift Click to Move](https://user-images.githubusercontent.com/13042214/198092245-79919d3d-7f6a-454c-85fe-563d9f416251.PNG)

### What is the expected behavior?

Holding Shift and clicking a button to move it to another location used to allow me to drag it without being used with the settings I had selected.

### What actually happened?

Holding Shift and clicking a button to move it to another location now uses the item/spell before allowing me to drag it with the settings I had selected.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Calesta** [comment]
10.27 Update.  Installed 12.95 and this issue seems to have been resolved.

**Comment by tlonsbury** [comment]
I had no idea actual QA style bug reports existed for ElvUI but this was tremendously helpful. Thank you.

**Comment by nihilistzsche** [comment]
Since this was marked by the author as resolved and we see no indication that this has changed in the versions released since going to go ahead and close this.
