### ISSUE TITLE
[Retail Bug Report] Can't Cancel Buff by Right-Clicking

### ISSUE THREAD

**Issue by Calesta** [tukui-org/ElvUI#434]
### What is the issue you are having?

I'm unable to right-click a buff to cancel it as before.

![image](https://user-images.githubusercontent.com/13042214/198149388-dc7dcb30-766d-4965-9a62-fff6d5cb4795.png)

### What is the expected behavior?

As before, we should be able to cancel an aura/spell by right-clicking it in the buffs section.

### What actually happened?

Right-clicking a buff does nothing.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by srmorgan22** [comment]
Same here waiting for a solution...

**Comment by Calesta** [comment]
10.27 Update. Installed 12.95 and this issue seems to have been resolved.

**Comment by leon3399** [comment]
> 10.27 Update. Installed 12.95 and this issue seems to have been resolved.

SetCVar('ActionButtonUseKeyDown', 0),This command can solve the problem.But you must release the key to cast skills, not press the key to cast skills

**Comment by Nexue-R** [comment]
Still can't cancel buffs :(

**Comment by jlemerle** [comment]
> 

Same with what I have found.

It seems to be with any _modifier macro's_ that don't work with `/console ActionButtonUseKeyDown 1` Normal macro's without [mod:shift] / [nomod] in it, will stop working. Changing `/console ActionButtonUseKeyDown 0` will enable modifier macro's to work again, however gameplay feels janky as abilities only work when the key is coming up.
