### ISSUE TITLE
[Retail Bug Report] Custom Time options in Boss Frame's cast bars are nonfunctional

### ISSUE THREAD

**Issue by fspy** [tukui-org/ElvUI#44]
### What is the issue you are having?

I'm trying to change the X and Y offsets of the boss frame's cast bar texts, but the **Time** offsets aren't applied.
They are instead *linked* to the **Text** offsets.

### What is the expected behavior?

The **Time** offsets should apply to the "time" text, not the "text" text.

### What actually happened?

The options are linked together and the Time text settings are ignored.

![image](https://user-images.githubusercontent.com/45343878/140595517-a15233aa-615a-40cb-85c2-3b21605e4fdd.png)
there are my current settings

![image](https://user-images.githubusercontent.com/45343878/140595533-eb7c0a11-279e-4c61-aec8-ef345029daec.png)
note the time text is not changed

![image](https://user-images.githubusercontent.com/45343878/140595556-0eb96ec5-332b-4006-80a7-5a35f0229669.png)
only one of the Y-offsets were changed, but applied to both

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by kodewdle** [comment]
Thanks 🌼
