### ISSUE TITLE
[Retail Bug Report] Unable to use blizzard bags with ElvUI

### ISSUE THREAD

**Issue by Kspud91** [tukui-org/ElvUI#442]
### What is the issue you are having?

I want to keep the 5 individual blizzard bags but with the ElvUI skin.
Im not able to. The skin doesnt work at all and for some reason im not able to use items in my bags unless I enable ElvUI bags. I can change gear but thats it. I cant use my Eternal Augment Run/any potions/any food etc. 
works if i disable ElvUI completely

### What is the expected behavior?

I should be able to have the black ElvUI skin on blizzard bags and be able to use items within these bags. 

### What actually happened?

cannot use items in bag.

### Errors

```shell
No errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by baka44** [comment]
same thing

**Comment by Mcdrowd** [comment]
I have the same problem

**Comment by Demokdawa** [comment]
If i disable the WHOLE elvui actionbars module, the bags works (click AND icons appear) and the vanilla UI re-appear. 
So if i disable the whole module, elvui effectively fallback to blizzard UI like intended.

**Comment by kodewdle** [comment]
fixed by https://github.com/tukui-org/ElvUI/commit/8d37562b0c745c546fee837ec7352e8568fa4554

**Comment by dezzuzu** [comment]
note you have to enable the bags module and disable it again for this to "refresh" the bagids
