### ISSUE TITLE
[Retail Bug Report] Retail unit frames stuck when ElvUI Unitframes are disabled

### ISSUE THREAD

**Issue by Ekojie** [tukui-org/ElvUI#448]
### What is the issue you are having?

Having the Elvui-unitframes disabled, but still using Elvui makes the retail unitframes unable to be moved in the new HUD Edit Mode. I've tried disable every other addon, except for ElvUI to test if there is a disruptor. 

![UI Wierd](https://user-images.githubusercontent.com/116836261/198363704-2baf549f-5891-46d1-b1c0-3a534d3b3e8b.jpg)

### What is the expected behavior?

Disabeling the ElvUI unitframes should've opend up the possibility to adjust the retail blizzard UFs as expceted.

### What actually happened?

The self-unit frame and the target frame is stuck in the middle. Not even being movable when the HUD Edit Mode is active. 

### Errors

```shell
No errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by CleverChrononaut** [comment]
I didn't test whether this works for all Blizzard Frames, however, if you uncheck the Cast Bar under UnitFrames -> Disabled Blizzard Frames -> Individual Units this restores the functionality to move the default Blizzard Cast Bar. You may have to enable and disable the UnitFrames Elvui module and/or reload the UI for this to work.
