### ISSUE TITLE
[Retail Bug Report] <impossible to use an object from the bag>

### ISSUE THREAD

**Issue by Electronium89** [tukui-org/ElvUI#449]
### What is the issue you are having?

hello, following the 10.0 update of the game and the last update of the addon, I can no longer use objects from my bag (hearthstone or potion of any type) in the bag mode while one disabled. However, it works with the active all-in-one bag, however I do not want to use this option.
after using the /edebug command I got a lua error involving AceEvent30 (AceAddon 3.0), bartender4 and rarity appeared after reactivating my addons and reloading the UI. Please find the complete error in the error encountered section

(sorry for the approximate English I am French and not very good in English)

### What is the expected behavior?

using an object from the bag (with right click) should work

### What actually happened?

does not work and emits the same sound as when you want to destroy an object

### Suggested Solution/Workaround

activating the all-in-one bag allows the use of objects (with right click) from the bag (not desirable for me)

### Errors

```shell
Message: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
Time: Thu Oct 27 20:28:48 2022
Count: 1
Stack: AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=(tail call)"]: ?
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/Bartender4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/Rarity/Core/EventHandlers.lua"]:68: in function `Register'
[string "@Interface/AddOns/Rarity/Core.lua"]:189: in function `DoEnable'
[string "@Interface/AddOns/Rarity/Core.lua"]:151: in function <Interface/AddOns/Rarity/Core.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Please open this ticket for Rarirty as it has nothing to do with ElvUI.
