### ISSUE TITLE
[TBC Bug Report] Flask buffs bar cooldown text starts at 1 hour

### ISSUE THREAD

**Issue by MMoisa** [tukui-org/ElvUI#45]
### What is the issue you are having?

The cooldown text for flasks in the buff bar next to the minimap start at 1 hour instead of 2 hours. The moment the timer hits 0 it goes back to 1 hour until it reaches 0 again and the flask actually expires. It might be an issue with all buffs that last more than 1 hour.

### What is the expected behavior?

The cooldown text should start from 2 hours or 120 minutes.

### What actually happened?

The cooldown text should starts from 1 hour or 60 minutes.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by kodewdle** [comment]
2 hour aura start at 2 hours, it's 2 hours for one second.
after that it is really 1 hour, 59 minutes, and 59 seconds.
displaying as hours, without rounding up:  that's 1 hour and **X**.   _(the **X** isn't shown unless you use HH:MM or MM:SS)_

**Comment by Repooc** [comment]
think @kodewdle sees whats going on (by discord chat) reopening for now until he does some checks

**Comment by MMoisa** [comment]
> 2 hour aura start at 2 hours, it's 2 hours for one second. after that it is really 1 hour, 59 minutes, and 59 seconds. displaying as hours, without rounding up: that's 1 hour and **X**. _(the **X** isn't shown unless you use HH:MM or MM:SS)_
> 
> anyways, in next version the hour cooldowns will update each minute, rather than each 30 minutes. which might be where the confusion came from. <3

I have the addon configured to display the time in minutes for all the buffs and flasks start at 60 minutes and started thicking down. When the timer reaches 0 it goes back to 60 minutes.

**Comment by Repooc** [comment]
fixed with 7bda62cba59dd56a63cabe7ed68287af151df983
