### ISSUE TITLE
[Retail Bug Report] Key Down option is gone in 12.95 version

### ISSUE THREAD

**Issue by lierox90** [tukui-org/ElvUI#450]
### What is the issue you are having?

Looks like option to have action ok key pressed rather than released was removed

![image](https://user-images.githubusercontent.com/4543689/198374573-f03fbf04-0ef5-4cb2-bd51-8927991b277f.png)
vs
![image](https://user-images.githubusercontent.com/4543689/198374627-253bdeb3-260f-416f-b462-b053176597e5.png)

### What is the expected behavior?

To have na ability to select if ability is activated on press or release

### What actually happened?

i updated elvui from .93 to .95, option to switch switch between press and release is gone, not mentioned in change log

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by lierox90** [comment]
That's a bit sad to hear, game feels sluggish AF with this, Ty for workaround anyway

**Comment by thisisjar** [comment]
Especially annoying because ElvUI keeps setting that CVAR ActionButtonUseKeyDown to 0 every reload. Effectively blocking other addons from allowing a workaround...

**Comment by notfelx** [comment]
> Especially annoying because ElvUI keeps setting that CVAR ActionButtonUseKeyDown to 0 every reload. Effectively blocking other addons from allowing a workaround...

Confirming this behavior. Elvui ignores all addons and sets it to 0. 
How can we disable this behavior ?
