### ISSUE TITLE
action bar  error

### ISSUE THREAD

**Issue by yolonutz** [tukui-org/ElvUI#451]
### What is the issue you are having?

![WoWScrnShot_102822_011552](https://user-images.githubusercontent.com/116852626/198421229-ef903fa2-f6d3-426e-a61a-a2677d6205c1.jpg)

### What is the expected behavior?

press the action bar button and for it to work

### What actually happened?

pressed the action bar button and nothing but an error message dialogue box

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Fri Oct 28 01:23:19 2022
Count: 9
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by brutt87** [comment]
I have the same issue, for my warlock it happens exclusively with the summon demon skill (it's supposed to spawn additional temporary buttons). I have tried to disable ElvUI and doing that fixes the issue.

**Comment by yolonutz** [comment]
Hi It does it on the hunter summon/utility button aswell On 28 Oct 2022 10:24, brutt87 ***@***.***> wrote:
I have the same issue, for my warlock it happens exclusively with the summon demon skill (it's supposed to spawn additional temporary buttons). I have tried to disable ElvUI and doing that fixes the issue.

**Comment by Vilogity** [comment]
Yep I have the same error, WL and Hunter Spell to summon dosnt work, only can use it from Spell Book

**Comment by Araldwenn** [comment]
Flightout buttons don't work at all, wether it's button for summoning demons, summoning pets, poisons, etc...

**Comment by dblanch369** [comment]
Yeah none of the Flyouts work with ElvUI loaded.  Unload ElvUI and they work again.  I see the same error as the OP.

**Comment by RealArbitrary** [comment]
Same problem. Since Dragonflight my summon demon ability does not pop out with the list of options.

**Comment by Azilroka** [comment]
All addons have this issue with flyouts. They messed it up for addons.

**Comment by yolonutz** [comment]
Tukui is working ok though
but more importantly can it be fixed?

**Comment by gz2k2** [comment]
same here, if i click on a "flyout" Spell :
Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)

**Comment by infamousjoeg** [comment]
Same issue for Teleport and Portal flyouts on Mage class:

```text
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Oct 30 16:54:33 2022
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

**Comment by gweber68** [comment]
Why has this issue been closed?
It still persists with ElvUI loaded.  Any flyout has this problem.

**Comment by nihilistzsche** [comment]
Its closed because its a known issue, so having more open issues about it is not conducive to actually fixing the problem.

**Comment by yolonutz** [comment]
It wasn't listed as a known issue when I checked as previous versions worked fine as does tukuiOn 31 Oct 2022 07:05, Nihilistzsche ***@***.***> wrote:
Its closed because its a known issue, so having more open issues about it is not conducive to actually fixing the problem.
