### ISSUE TITLE
[Classic Bug Report] Hunter Expandable Icons stopped working with latest Pre Dragonflight patch

### ISSUE THREAD

**Issue by jgsandri** [tukui-org/ElvUI#454]
### What is the issue you are having?

"Call Pet", "Pet Utility", and "Hero's Path: Shadowlands" stopped working.   When I use the WoW interface, those 3 expand when I click on them as expected.  Before the latest patch, they expanded as expected with Elvui as well.  So when I click on them they don't expand showing and icons within them.

### What is the expected behavior?

When I clock on the icon (they have an Up Arrow on the Icon), they are supposed to then show the icons within the group.  So "Call Pet" is to show the pets that I can summon.

### What actually happened?

When I click on the icon, nothing happens.   The icons within the group do not show up.

### Suggested Solution/Workaround

Obviously return the behavior to working condition.

### Errors

```shell
After following step 6 below /edebug on, I go a Lua Error.

Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Thu Oct 27 19:41:56 2022
Count: 6
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Mcdrowd** [comment]
Same for Mage Portals

**Comment by syuukon** [comment]
Warlock pet selection has the same issue too.

**Comment by Caedis** [comment]
Issue is on blizz's side, nothing we can do.

**Comment by jgsandri** [comment]
Thanks for the reply.  I don't understand the interaction between Elvui and Blizzard, but this works fine in the Blizzard UI.  So with that information you still feel it's a Blizzard issue?

**Comment by Caedis** [comment]
Yes, cause blizzard's UI is special. It runs "secure", while every addon is "unsecure".

Here is some reading material: https://wowpedia.fandom.com/wiki/Secure_Execution_and_Tainting
