### ISSUE TITLE
[Retail Bug Report] <bag interact issue>

### ISSUE THREAD

**Issue by yeboyr** [tukui-org/ElvUI#456]
### What is the issue you are having?

my items in my bag cant be interacted with

### What is the expected behavior?

use the item

### What actually happened?

nothing happended

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by dezzuzu** [comment]
i realize this only happens when you disable bags from the elvui menu. if you activate bags, then the user can interact with the items in the bag. this solution forces the user to use elvui bags. i prefer not to use the elvui bag ui, and others seems to prefer the default blizzard bag ui. 

toggling the bag skin in the skins menu does nothing.

**Comment by yeboyr** [comment]
> i realize this only happens when you disable bags from the elvui menu. if you activate bags, then the user can interact with the items in the bag. this solution forces the user to use elvui bags. i prefer not to use the elvui bag ui, and others also seems to prefer the default blizzard bag ui.
> 
> toggling the bag skin in the skins menu does nothing.

yes, thank you fora adding up these info, we having the same issue here

**Comment by Azilroka** [comment]
This has been fixed in dev. It was being tainted and we had to find out where. The solution was to use either all in one bag.. Our or Blizzards. It was a temporary solution.

**Comment by MatuMikey** [comment]
I'm glad I found this issue, I'd like to add that for some reason my bags don't get re-skinned by ElvUI either on version 12.95 in addition to not being able to right click interact with usable items in my bags however I can EQUIP items by right clicking.

**Comment by Azilroka** [comment]
Because they are new bags and we didn't touch them yet. I'm pretty sure Simpy skinned the individual bags and is working on the all in one.

**Comment by dezzuzu** [comment]
makes sense. you said earlier that it's fixed, i guess we should wait for the next version for the fix to deploy?
