### ISSUE TITLE
[Retail Bug Report] Erratic EXP Bar

### ISSUE THREAD

**Issue by Anseilon** [tukui-org/ElvUI#458]
### What is the issue you are having?

Experience databar turns fully transparent upon getting EXP (that is, both the fill and remaining/rested EXP).  Upon quest becoming "turn-in," the entire fill bar will change to the color specified for "completed quest EXP."  Actually turning the quest in will revert the fill bar to defined color for regular EXP, but still maintain full transparency.

### What is the expected behavior?

The expected behavior is to have, even when on transparent, for the EXP fill bar to remain solid, with the remainder transparent; the fill bar to not change to the completed quest color value when a quest is ready to turn in.

### What actually happened?

Logged in on leveling toon, nothing was wrong with the bar.  Killed an enemy, the fill bar went transparent.  Fulfilled a quest's requirements, and the bar became the color of the "completed quest" EXP bar.  In my case, gold.

First image shows the blue part having shifted to transparent.  Toggling transparency briefly corrects this, but soon goes full transparent:

![image](https://user-images.githubusercontent.com/24575895/198581367-3db9b162-3de2-404b-87cc-235d8e312fba.png)

Second image shows the blue bar changing completely to "completed quest" state:

![image](https://user-images.githubusercontent.com/24575895/198582007-98450a7c-152f-4559-a9c3-c4e3e146cc7c.png)

Toggling the following options corrects the issue until you either again kill a mob or flag a quest for turn-in:

![image](https://user-images.githubusercontent.com/24575895/198582364-2903eb76-66f5-4d2f-a07e-173fddb43220.png)

### Errors

```shell
No lua errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
sounds like the draw layer issue we have fixed in the development build already, you can try it out and double check or assuming you can deal with it for now, wait for the next release, of course reopen if its not the exact issue after trying the dev build (or next release)
