### ISSUE TITLE
[Retail Bug Report] Flayout Buttons Lua Error

### ISSUE THREAD

**Issue by Gennoken** [tukui-org/ElvUI#461]
### What is the issue you are having?

Lua error when using a flaout button, ie: Summon Demon

### What is the expected behavior?

No errors :)

### What actually happened?

Lua Error upon key stroke

### Errors

```shell
1x Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by jdwoodall** [comment]
Just FWIW, I encountered the same issue with my hunter with the flyout to summon pet.

**Comment by Caedis** [comment]
Issue is on blizzard's end.

**Comment by Gennoken** [comment]
@Caedis 
I dont get the error when i disable ElvUI.
i mean no error with base WoW UI

**Comment by Caedis** [comment]
The issue is still on blizzard's end.
Blizzard's UI can do things addons can't because it is their own UI.
Everything they do is considered "secure". Everything addons do is "insecure".
And the way they recoded the flyouts, it errors when something insecure accesses it.
