### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by leon3399** [tukui-org/ElvUI#462]
### What is the issue you are having?

Now you must release the key to cast skills. After using this command, SetCVar ('ActionButtonUseKeyDown ', 1) solves the problem, but you can't right click to cancel the aura.

### What is the expected behavior?

Press the key to cast and right-click to cancel the aura.I used the Blizzard native UI without this problem

### What actually happened?

Now you must release the key to cast skills. After using this command, SetCVar ('ActionButtonUseKeyDown ', 1) solves the problem, but you can't right click to cancel the aura.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
Issue is on blizz's end.
Issues with it set to 0, issues with it set to 0.
