### ISSUE TITLE
[Retail Bug Report] <Player portrait not disappearing>

### ISSUE THREAD

**Issue by Poukynette** [tukui-org/ElvUI#466]
### What is the issue you are having?

I have set up my player frame to disappear when I am not selected or in combat. The frame still dissapears but the player portrait remains.
![WoWScrnShot_102922_163011](https://user-images.githubusercontent.com/116963090/198837807-fd790d94-f215-493d-8a70-2498f9690f73.jpg)
![WoWScrnShot_102922_163007](https://user-images.githubusercontent.com/116963090/198837809-18624791-cf4c-4722-9ba3-8ac72934e38c.jpg)

### What is the expected behavior?

The portrait should disappear with the whole player frame when not selected or in combat.

### What actually happened?

The player portrait remains floating on the interface, without the frame around it.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
This is a known issue affecting all addons reported on the WoWUIBugs github, not one we need to track here.
