### ISSUE TITLE
[Retail Bug Report] Actionbars after change not working on KeyPress

### ISSUE THREAD

**Issue by Rajine85** [tukui-org/ElvUI#468]
### What is the issue you are having?

When using ElvUI without the actionbars (default Blizz UI) after a change of actionbar 1 (for example: shapeshift druid) the abilities/spells are no longer usable. You can click on them and the casting works. However, all action bars are then no longer usable via hotkeys.

### What is the expected behavior?

For example, when I press 1, 2 or 3 etc on the keyboard, the cast should be activated. This no longer happens after a shape change (druid). The problem usually does not occur immediately, but at the latest after the 3rd or 4th change of action bars.

### What actually happened?

As soon as the error occurs, only the actionbar 1 are no longer usable with the keyboard. They can only be clicked with the mouse. 

### Suggested Solution/Workaround

Only a reload of the UI can help.

### Errors

```shell
Message: ADDON_ACTION_FORBIDDEN: ElvUI tries to call the protected function 'UseAction()'.
Time: Sat Oct 29 18:49:22 2022
Count: 1
Stack: ADDON_ACTION_FORBIDDEN: ElvUI tries to call the protected function 'UseAction()'.
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ils/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Details/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/ActionButton.lua"]:157: in function `ActionButtonUp'
[string "ACTIONBUTTON1"]:4: in function <[string "ACTIONBUTTON1"]:1>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Yin-wow** [comment]
Hello, 
I have the exact same issue, with rogue going in and out of stealth.
Thanks !

**Comment by Dexterosa** [comment]
Same issue for me as well, i have disabled elv ui action bars and using default blizzard. tried to enable only elv ui and nothing else, problem remains,
1x [ADDON_ACTION_FORBIDDEN] Модификация 'ElvUI' пыталась вызвать защищенную функцию 'UseAction()'.

**Comment by Ljensen91** [comment]
I also have this exact issue
