### ISSUE TITLE
[Retail Bug Report] Covenant symbol disappears when switching to covenant without soulbind

### ISSUE THREAD

**Issue by Wasilewskiii** [tukui-org/ElvUI#47]
### What is the issue you are having?

After using the new Covenant switch ability of the game, i switched to a Covenant my character never has had before, therefore there are no soulbinds available and the minimap icon disappeared forever.

### What is the expected behavior?

The minimap Soulbind Covenant icon should switch to the new Covenant symbol.

### What actually happened?

After using the new Covenant switch ability of the game, i switched to a Covenant my character never has had before, therefore there are no soulbinds available and the minimap icon disappeared (forever). I then purchased the new item and unlocked all 3 soulbinds, but the icon remained hidden. I checked the settings (see screenshot) which seem to be ok. Even after switching back to the old Covenant, the Icon never came back.

I also tested this on another character which already had soulbinds in the Covenant I switched to, there it worked as expected. The icon switched to the new Covenant.

![WoWScrnShot_110721_020913](https://user-images.githubusercontent.com/24535655/140628669-722200a1-2f40-4b23-8668-7911f5f042a5.jpg)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by 1Botanica1** [comment]
Please test with only ElvUI - to quickly disable all other addons, type in chat in game 
/edebug on

Test - If you still have the issues, type in chat in game
/estatus

and upload a screenshot showing both the issue and status panel

**Comment by Wasilewskiii** [comment]
@1Botanica1 Thank you for the reply. Indeed the issue was caused by ProjectAzilroka which seemed to automatically hide the Garrison button (maybe because no soulbinds?) and not showing it again.

The issue is therefore resolved.
