### ISSUE TITLE
[Retail Bug Report] Chat/Chat Panel Shifts

### ISSUE THREAD

**Issue by Calesta** [tukui-org/ElvUI#472]
### What is the issue you are having?

The left side of the chat panel appears to shift to the right.

![Chat Not Fully in ElvUI Chat Panel](https://user-images.githubusercontent.com/13042214/198858022-803c7c40-f456-4b0f-b538-442dfd249e3b.PNG)

As soon as I display or hide the chat panel backdrop, it shifts back to fully filling the panel and stays that way until there's a reload (e.g., taking a portal, using a hearthstone) and then it shifts back to the right.

![Chat Panel Displayed Then Fills](https://user-images.githubusercontent.com/13042214/198858028-ab3e8ed9-1a05-4ce5-aada-506ba69fcc96.PNG)

### What is the expected behavior?

I would expect that the chat would completely fill the chat panel.

### What actually happened?

As above, the chat keeps shifting to the right at times during gameplay and has to be 'reset' by display/hiding the chat panel backdrop.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by CristianoBesi** [comment]
I had the same problem. Somehow I solved it disabling the Details addon. If you enable it again, the problem won't show up anymore. I know, it is weird but it worked on all my chars, so far

**Comment by Nazgul084** [comment]
Not sure if its a relevant clue or not to the issue, but I've seen an issue where my Blizzard UI got reset from a custom profile back to Modern after finishing the Headless Horseman event, and when that occurred, chat was moved to its reset position. Upon restoring my pre-ElvUI custom Blizzard UI, ElvUI properly repositioned and resized everything, including chat. In other words, could be an issue with Blizzard's UI reestablishing control over a screen element.

**Comment by Calesta** [comment]
I installed the latest version (12.99) and this behavior seems to have been addressed.  Thanks!
