### ISSUE TITLE
[Retail Bug Report] Paging Action Bars constantly resetting.

### ISSUE THREAD

**Issue by Fizgig1973** [tukui-org/ElvUI#474]
### What is the issue you are having?

After setting up Paging for Player Action Bars. They are not saved between sessions, even when copied to different profiles as backup.

### What is the expected behavior?

Paging to be saved to the profile.

### What actually happened?

Paging seems to reset after logging out for an extended period.

### Suggested Solution/Workaround

I've had to swap to Bartender 4 for the meantime as it is working there. Would rather just continue with ElvUI as a whole.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [x] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
do you mean the Paging section of the bar? if the settings arent saved in that text box then that sounds like a write permission error on the file inside the wtf folder for wow to save the setting... or is it just not working as you expect?  prob best to show a picture of the setting u are using

**Comment by Fizgig1973** [comment]
Seems to be fixed after I installed the latest update of Elv. 

It wasn't a permissions issue, as I had reinstalled WoW and checked the settings prior to filing. Things just weren't saving after I logged out and back in. 

But regardless, it is working correctly now, so I thank you and your team.

**Comment by Repooc** [comment]
awesome thats working now for ya
