### ISSUE TITLE
[Retail Bug Report] ElvUi sets ActionButtonUseKeyDown = 0 every load/reload.

### ISSUE THREAD

**Issue by notfelx** [tukui-org/ElvUI#477]
### What is the issue you are having?

ElvUI sets ActionButtonUseKeyDown = 0 every load/reload, ignoring any other add-ons & configs.

Related: #450 #430 #434
The option was forced to avoid the right click bug & shift drag bug (#430) & (#434).
```lua
if E.Retail then -- set for now to get Auras right click to work
    SetCVar('ActionButtonUseKeyDown', 0)
end
```

Forcing the CVar is more shifting the bug than a solution, so I would like to have this ticket open for the new bug.

### What is the expected behavior?

User can change CVar and decide.

### What actually happened?

ElvUi overrides CVar every time.

### Suggested Solution/Workaround

Workaround is to comment out line 544 in Auras.lua (Under Core/Modules/Auras) to avoid ElvUI forcing its hand.
```lua
-- SetCVar('ActionButtonUseKeyDown', 1)
```

User should be able to set the CVAR or not to decide which bug they prefer
-- Keep the  [no drag + no aura cancel]
or 
-- Keep ActionButtonUseKeyDown = 1), 

ElvUi should not force this choice.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
We will remove it as soon as Blizzard fixes it. It has to be 0 to right click auras.
