### ISSUE TITLE
[Retail Bug Report] Mini Map Resetting

### ISSUE THREAD

**Issue by Bengesko** [tukui-org/ElvUI#478]
### What is the issue you are having?

The Minimap keeps resetting size and scale. The settings don't save between sessions, even when copied to different profiles. I set the size and scale, and any time there's a loading screen, the map resets- to a very small corner of the screen. 

Elvui is up to date- just updated it with a fresh reinstall this morning. Also cleared my WTF folders of all Elvui lua/bak files to reset all possible settings. 

### What is the expected behavior?

Map size/scale to save and not reset.

### What actually happened?

Minimap settings simply reset, or possibly there is an issue with the anchors?

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by w-raken** [comment]
I have exactly this error now, is there any way to fix it? I see that the issue is one month old and there is no answer

**Comment by Bengesko** [comment]
> I have exactly this error now, is there any way to fix it? I see that the issue is one month old and there is no answer

No fix aside from disabling the minimap and using another addon. I replaced it with SexyMap.

**Comment by w-raken** [comment]
Quite disappointing that they ignored this problem... Thanks for your answer

**Comment by kodewdle** [comment]
can't reproduce, sorry
