### ISSUE TITLE
[Retail Bug Report] Warlock "Summon Demon" spell not working from castbar

### ISSUE THREAD

**Issue by tensware** [tukui-org/ElvUI#480]
### What is the issue you are having?

Current version installed: **Elvui 12.98**
Running on latest WoW Dragonflight Pre Patch (Retail) version 10.0.0.46366.

The spell "_Summon Demon_" has been dragged from the common spellbook to one of the buttons on the castbar. Clicking on the button on that castbar should drop a rolling menu wherein one can choose the demon to be summoned. Instead, a LUA error is given (see error description for full LUA error message).

* It does not matter on which castbar the spell is put: all castbars have the same behaviour, thus the same error output.

* Opening the Spellbook and casting it from there does work well (current workaround). The LUA error is only given when the spell is put on a castbar.

* To make sure no other add-on was interfering, causing the bug, all other addons were disabled. And the game has been reloaded several times in between. Disabling all addons had no effect, however.

* In the original Blizzard GUI the spell on the castbar does work fine.

* The option /edebug (after switching off all other addons) does show no (extra) information.

### What is the expected behavior?

Expected functionality is a dropdown (or -up) menu with an overview of all demons able to summon. By picking one of those demon pets, I would summon it to fight beside me.

Now, not even a menu (overview of demon pets) is shown. 

### What actually happened?

Before the pre-patch it worked just fine. But with the introduction of the Dragonflight pre-patch, this issue has come to live.

### Suggested Solution/Workaround

I'm not familiair with the Elvui code, but as there is a nil value in the LUA error, I assume a null object is encountered due to the probably new GUI/castbars in WoW, but that's just a guess.

A workaround in the game is the spellbook: from there the dropdown menu appears and I can select a demon. However, mid-fight this is far from ideal.

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Oct 30 17:15:54 2022
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ith77** [comment]
same issue, all addon disabled cant summon demons.

**Comment by Luckyone961** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/302
