### ISSUE TITLE
[Retail Bug Report] Call Pet (or any pull-out icon) Not Working

### ISSUE THREAD

**Issue by Merancapeman** [tukui-org/ElvUI#481]
### What is the issue you are having?

Click the pet options or call pet options icon, will not extend; comes up with an error instead.

### What is the expected behavior?

Menu options extend from icon.

### What actually happened?

Nothing but an error.

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Oct 30 12:44:59 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by UnaffiliatedGamer** [comment]
Same or similar issue here, definitely isolated to ElvUI. It seems to override the Blizzard mover and hooks the TalkingHeadFrame to the expanding Loot/Alert Frames for me, with no options (that I can find) to unlink them.

**Comment by infamousjoeg** [comment]
Mage here: Teleport & Portal flyouts affected:

```
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Oct 30 16:54:33 2022
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

**Comment by Araldwenn** [comment]
Don't forget rogue poisons as well.

**Comment by Jorgitas** [comment]
Confirmed not working

**Comment by Luckyone961** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/302
