### ISSUE TITLE
[Retail Bug Report] ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()

### ISSUE THREAD

**Issue by DDekker84** [tukui-org/ElvUI#483]
### What is the issue you are having?

The following error is being thrown when I exit combat. ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()

I did the following to make it happen.

1. Mounted up.
2. Check my bags, and close them.
3. Dismount to kill a creature.
5. Creature death triggers the error.

Although I suspect it had nothing to do with mounting or checking bags, since the last part of the stacktrace shows :[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:878: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:876>

When attacking multiple creatures each creature death triggers the following message in chat "ElvUI: Lua error received. You can view the error message when you exit combat.".

It happens on all characters that have quest updates.

I tried ElvUI version 11.93: 11.95, 11.97, 11.98.
The only active addons are ElvUI

### What is the expected behavior?

The error not to appear when I exit combat.

### What actually happened?

The error showed up.

### Errors

```shell
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
Time: Sun Oct 30 19:35:47 2022
Count: 1
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function <Interface/FrameXML/UIParent.lua:3102>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:1470: in function `ObjectiveTracker_Update'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:878: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:876>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.
- [X] I have not read step six and I am just clicking all boxes.

**Comment by Jorgitas** [comment]
Confirmed, also to me.

**Comment by CristianoBesi** [comment]
It has been a while since I got this error. Recently this issue started to be even worse. Together with the Lua error, the window of possible loot opens itself

**Comment by Aegllor** [comment]
This error has happened to me as well. unsure if it was a level up or a looting of a corpse for a quest objective because they happened about the same time.

**Comment by brett1337** [comment]
Just adding that this still happens on 12.99

**Comment by bfoxeh** [comment]
I also have this issue or similar. Often when I change zones as soon as I try to use any action bar 1 button except for button 1 for some odd reason. If I do /reload everything is usually fine for the duration of that zone. In my case it looks like its also an interaction with Allthethings or sometimes DBM. Could be coincidental as those prob also have Ace.

Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
Time: Fri Nov  4 23:02:55 2022
Count: 3
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ElvUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...vUI/Libraries/Core/Ace/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function <Interface/FrameXML/UIParent.lua:3102>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:641: in function `UpdateBottomActionBarPositions'
[string "@Interface/FrameXML/EditModeManager.lua"]:555: in function `UpdateActionBarLayout'
[string "@Interface/FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@Interface/FrameXML/StanceBar.lua"]:73: in function `UpdateState'
[string "@Interface/FrameXML/StanceBar.lua"]:12: in function <Interface/FrameXML/StanceBar.lua:10>
[string "=[C]"]: ?

Locals: <none>

**Comment by brett1337** [comment]
seems fixed
