### ISSUE TITLE
BlendMode error when using portal or hearthstone.

### ISSUE THREAD

**Issue by Xugos** [tukui-org/ElvUI#485]
### What is the issue you are having?

Each time a portal is taken or using hearthstone a error will occur. This error doesn't seem to effect the ui.

### What is the expected behavior?

Portal taken or hearth performed. No errors.

### What actually happened?

Each time a portal is taken or using hearthstone a error will occur.

### Suggested Solution/Workaround

N/A

### Errors

```shell
Usage: self:SetHighlightTexture(asset [, blendMode])
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:457: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:455>
[string "=[C]"]: in function `SetHighlightTexture'
[string "@Interface/FrameXML/MainMenuBar.lua"]:116: in function `Update'
[string "@Interface/FrameXML/MainMenuBar.lua"]:96: in function <Interface/FrameXML/MainMenuBar.lua:95>

Locals:
(*temporary) = "Usage: self:SetHighlightTexture(asset [, blendMode])"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
![image](https://user-images.githubusercontent.com/18713839/199052337-fe64958d-2144-4444-9e96-32075ece855e.png)

also, the issue is in the masque skin you are using.
Disable Masque, or disable Masque Support in /ec -> Action Bars and the issue goes away.
