### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Soromeister** [tukui-org/ElvUI#486]
### What is the issue you are having?

Mailbox window looks weird after clicking anywhere inside it

### What is the expected behavior?

Mailbox window should work as expected

### What actually happened?

Icons and text disappear from window and will remain like this until reload, when it happens again.

![image](https://user-images.githubusercontent.com/45243695/198989281-4bb30c4b-4dde-40b1-8485-adf3bb835fe6.png)

### Suggested Solution/Workaround

Probably some hook needs to be updated

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
`/edebug on` then show `/estatus` and reopen ticket if you still have the issue

**Comment by Soromeister** [comment]
This was fixed with the new release of ElvUI (12.99)
