### ISSUE TITLE
[Retail Bug Report] Call Pet click causes error, wont open

### ISSUE THREAD

**Issue by JPearson4110** [tukui-org/ElvUI#487]
### What is the issue you are having?

Call pet from action bar doesnt open

### What is the expected behavior?

Available pet buttons should show

### What actually happened?

Error and wont open

### Errors

```shell
21x Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by SteveEbey73742** [comment]
I have run retail, with only ElvUi and get the same Fly out error, with my mage, when she attempts to open portals, or teleport. Version 12.98 Retail.  I do not know if the error is also present on classic WotLk, as my DK Warrior, and Warlock do not use fly out function for any spells.

**Comment by SteveEbey73742** [comment]
re-open. 12.99 has same error. nothing changed.

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/480

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/461

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/454

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/431

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/418

**Comment by Azilroka** [comment]
And that isn't even all of them. It's a Blizzard side bug.
