### ISSUE TITLE
[Retail Bug Report] <Power bar disappears after switching specs, then switching back>

### ISSUE THREAD

**Issue by imsoemokthx** [tukui-org/ElvUI#488]
### What is the issue you are having?

I play a Shadow Priest, and when I switch my spec to a different loadout, then back, my insanity bar disappears until I relog. The insanity bar on ElvUI is classed as the "power bar" and not the "class bar".

### What is the expected behavior?

My bar shouldn't disappear.

### What actually happened?

The bar disappears until I relog.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Blizzard decides the power/class bar. 
For Shadow Priests, their main power is insanity & therefore the power bar. 

Please type in chat in game
`/edebug on`

Does the issue still occur?  If so, type in chat in game 
`/estatus` and upload a FULL UI screenshot (no cropping) showing both the issue and the status panel 
Include another screenshot of the power bar settings.

**Comment by kodewdle** [comment]
closing, no response.  reopen if needed. :)
