### ISSUE TITLE
[Feature Request] Detached Power Bars position could (should ?) be linked to the health frame

### ISSUE THREAD

**Issue by Tabidou** [tukui-org/ElvUI#49]
**Is your feature request related to a problem? Please describe.**
I'm having quite a hard time to pixel-perfect position the detached power bar as the anchor becomes free floating. Also, whenever I move my health bar, I need to redo the positioning of the power bar.
Additionally, this would also give the possibility to have the "detach" option available for group units where it is missing at the moment.

**Describe the solution you'd like**
Once "Detached from frame" is checked, there could be new options appearing to give the origin point of the health frame (TOP, BOTTOMRIGHT, etc.) and X/Y offsets for the same point (or a different one, but that would require an additional option and I'm not sure that is necessary) of the power frame.
The actual behaviour could stay but it could be an additional choice: Free floating (existing) / Position (new)

**Describe alternatives you've considered**
Haven't found any other alternatives yet, but fairly new to ElvUI, might have missed them.

**Additional context**
Here is an example of what I'm trying to achieve.
![image_2021-11-07_180620](https://user-images.githubusercontent.com/93877344/140654568-da60933a-7601-478d-9d1f-907db6c66c75.png)

**Comment by Azilroka** [comment]
power offset

**Comment by Tabidou** [comment]
I'm sorry, maybe there is something I don't see, but there is no power offset.
In the "power" section, the only offset available is for the text.

![image_2021-11-11_072108](https://user-images.githubusercontent.com/93877344/141248132-51cabf93-77a2-492f-85b8-273f08b3fa80.png)

**Comment by Repooc** [comment]
Style -> Change it to offset
