### ISSUE TITLE
[Retail Bug Report] Action Bar scrolling issues

### ISSUE THREAD

**Issue by Wightwind** [tukui-org/ElvUI#490]
### What is the issue you are having?

Scrolling through actionbars scrolls through every single bar, whether enabled or disabled. Before prepatch it only scrolled between bar 1 and 2 (as only those 2 were enabled). So I use Elvui with all the available Elv bars active, and I scroll through 2 bars on the mainbar slot, similar to ESO where you swap between a front bar and back bar. 

### What is the expected behavior?

Pressing the next action bar button only cycles through the action bars that are enabled, not all of them. So when clicking the "next action bar" button multiple times it just changes between Bar 1 and Bar 2. Scrolling order should be 1>2>1>2>1>2 etc.

When tested with default UI, if I have every single actionbar enabled, then it does what I expected which is only swapping between bar 1 and bar 2 on keypress, and it only cycles between them. Enabling or disabling all bars with elvui active does not replicate this behavior however, and for some reason my blizz actionbar settings keep toggling random options on and off. 

### What actually happened?

Clicking the "Next Action Bar" button scrolls through every single action bar, even if they are disabled.  Scrolling is currently 1>2>3>4>5>6>7>8>1

### Suggested Solution/Workaround

I honestly dont know, It might be a blizz problem, since before prepatch the action bar options in the main menu were "Remove Extra Action Bar X(2-8)", now that setting no longer exists as far as I can see.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
should be fine in the next build, u can test the development branch or wait for the next release.
