### ISSUE TITLE
[Wrath Bug Report] Quest log issue

### ISSUE THREAD

**Issue by tlecas** [tukui-org/ElvUI#492]
### What is the issue you are having?

When opening the quest log or after abandoning a quest, pressing the "Abandon" button won't necessarely attempt to abandon the currently selected quest.

### What is the expected behavior?

Pressing the abandon button should always lead to abandoning the currently selected quest.

### What actually happened?

![S7vHo3q](https://user-images.githubusercontent.com/36078510/199263402-af8268b1-8178-4b3f-a4f3-0f1f0f538c0a.jpg)
As you can see on the above screenshot, pressing the "Abandon" button triggered a confirmation to abandon the quest "A Call to Arms: The Plaguelands!" while the quest currently selected in the quest log is "The New Frontier".

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
We don't alter that code other than skinning the window.
