### ISSUE TITLE
[Retail Bug Report] Press&Hold Casting

### ISSUE THREAD

**Issue by TYtheAlkemist** [tukui-org/ElvUI#493]
### What is the issue you are having?

Press and Hold Casting does not activate at all, no amount of holding down the button will cast repeatedly. This is in open world, raid, and training dummy

### What is the expected behavior?

Automatic Casting

### What actually happened?

My character stood around and watched an enemy beat it's face in, when i released the button, the cast started. Pressing and holding after that cast starts does nothing; your character stands around

### Suggested Solution/Workaround

No idea, just wanted you guys to know :)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/317

We know.

**Comment by TYtheAlkemist** [comment]
> [Stanzilla/WoWUIBugs#317](https://github.com/Stanzilla/WoWUIBugs/issues/317) [Stanzilla/WoWUIBugs#307](https://github.com/Stanzilla/WoWUIBugs/issues/307)
> 
> We know.

Sorry they listed the bug by LUA and not the name of the actual feature that's broken, not my fault that search won't pick that up. Congratulations you're snark is just to be a dickwad

**Comment by nihilistzsche** [comment]
Leave a comment
Calling people dickwads isnt likely to endear them to continuing to acknowledge you.
