### ISSUE TITLE
Minimap Difficulty Indicator looks bad

### ISSUE THREAD

**Issue by Shadowinplay** [tukui-org/ElvUI#496]
### What is the issue you are having?

After update 10.0 which introduced a new HUD to Retail, they changed all minimap buttons, however ElvUI is not getting some of the new textures replaced properly along other things.

### What is the expected behavior?

To icons/textures to show properly and align correctly.

### What actually happened?

This is the Raid Difficulty Indicator sharing the same settings, misplaced:
![WoWScrnShot_110222_132351](https://user-images.githubusercontent.com/111493171/199547049-509e5dcd-edc0-47d7-8f92-3ff26a41c0a7.jpg)

This is the Dungeon Difficulty Indicator sharing the same settings, misplaced:
![WoWScrnShot_110222_132724](https://user-images.githubusercontent.com/111493171/199546250-9eeacece-4da5-4f25-a0d7-107c43bb5c25.jpg)

In both screenshots, the Mail Indicator is stretched/distorted and not replaced by the new one, not even as an option.

### Suggested Solution/Workaround

Correct any hardcoded settings of these buttons, so they can show correctly.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
If this still an issue?

If so, please type in chat in game
`/edebug on`
Do you still have the issue?

If so, type in chat in game
`/estatus` and upload a full UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by kodewdle** [comment]
I have this one pinned but haven't had time it's low prio but thanks for the report regardless, i'll link this ticket to the pin.
