### ISSUE TITLE
[Retail Bug Report] flyout menus is missing for buttons in the action bar

### ISSUE THREAD

**Issue by dezzuzu** [tukui-org/ElvUI#497]
### What is the issue you are having?

when an action with a fly out menu like "poisons" or "summon pet" is placed in an action bar, pressing the action button does not create the submenus to select a poison or pet.

### What is the expected behavior?

the submenu should show, allowing the user to select the subitem

### What actually happened?

nothing, the button acts as if it is not interactable or the ability is passive

### Suggested Solution/Workaround

open the spellbook, press the button, and the menu appears for the user to select

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by dezzuzu** [comment]
one of my guildmates has the same problem, except it produces an error. please see below

Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Wed Nov  2 14:38:25 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>

**Comment by nihilistzsche** [comment]
This is a known issue that Blizzard has to fix.  No addons are able to use spell flyouts, nor hold & cast at this time.  Our apologies, but theres nothing that can be done here on our end, weve tried everything.
