### ISSUE TITLE
[Classic Bug Report] <Not (all) Silence Stun Duration Shown on Self Abilities>

### ISSUE THREAD

**Issue by maxiking913** [tukui-org/ElvUI#498]
### What is the issue you are having?

When Silenced or Stunned the Duration sometimes not shown on abilities like in retail.

### What is the expected behavior?

See Silence and Stun effect.

### What actually happened?

Nothing

### Errors

```shell
no errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Not a bug. Classic doesn't have all the quality of life changes.
