### ISSUE TITLE
Blizz default action bar visible[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Holznacken** [tukui-org/ElvUI#499]
### What is the issue you are having?

Whenever I port somewhere else or enter an instance, the Blizz standard actionbar 6 is also visible as an overlay. The same applies to the standard Blizz group unit when I form a group. If I then relog again, the action bar is correct again. The Blizz group unit sometimes only changes size when I relog and is then gone.

### What is the expected behavior?

No Overlay from standart Blizz Units

### What actually happened?

See above

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Frutzi** [comment]
I recognized the same behaviour on different twinks.
A workaround that works for me:
- disable ElvUI addon and /reload
- go to >Options >Action bars in standard Blizzard Options and disable the action bar that pops up (mine where always activated)
- activate ElvUI again
