### ISSUE TITLE
[Feature Request] More Threat Bar Options (X-Offset, Disable Text, Increse Offset)

### ISSUE THREAD

**Issue by Spegeli** [tukui-org/ElvUI#5]
**Is your feature request related to a problem? Please describe.**
If you use the ElvUI Threat Bar Vertical, you need a X-Offset for the Text to get better Positions.
If you use ElvUI together with BenkUI and use the BenkUI Threat Text you need a Option to Disable the Thread Text from ElvUI.

**Describe the solution you'd like**
1) Add X-Offset to Threat Bar Options (for Text)
2) Add Disable Text to Threat Bar Options
3) Increase the Y-Offset from 30 to 50 or 100

Here is a Screen to show the X-Offset issue when using a Vertical Bar.
On my UI its on the right side of the Target Frame and the Threat Text is hidden by the Target Frame.
With an X-Offset it would be possible to let the text on the right side of the thread bar.
![Screen1](https://user-images.githubusercontent.com/19636318/133653579-efac296a-600b-4e08-b92b-a68a764c60b6.png)

**Comment by Spegeli** [comment]
@Repooc 

thx for the fast implementation. works perfect now ;-)

The Blue "Text yOffset" can be now removed, its the old one which is no longer needed.
![Screen](https://user-images.githubusercontent.com/19636318/133755520-911c7ed8-64d9-4dc0-a5b5-ba311b5adb0b.png)

**Comment by Repooc** [comment]
Np, that is not from ElvUI
