### ISSUE TITLE
[Retail Bug Report] <AceDB>

### ISSUE THREAD

**Issue by devil81** [tukui-org/ElvUI#50]
### What is the issue you are having?

I get this error when i reload or login , 1 time . Same with release version or even with last dev version .

### What is the expected behavior?

x

### What actually happened?

x

### Errors

```shell
1x ...ns\ElvUI\Core\Libraries\Ace3\AceDB-3.0\AceDB-3.0-27.lua:373: bad argument #1 to 'next' (table expected, got boolean)
[string "=[C]"]: ?
[string "@ElvUI\Core\Libraries\Ace3\AceDB-3.0\AceDB-3.0-27.lua"]:373: in function <...ns\ElvUI\Core\Libraries\Ace3\AceDB-3.0\AceDB-3.0.lua:359>

Locals:
(*temporary) = true
(*temporary) = "table expected, got boolean
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Azilroka** [comment]
but did you try with just ElvUI tho?

**Comment by devil81** [comment]
yes , only with elvui i get no errors. i will start add 1 by 1 to see what plugin its adding this error

**Comment by devil81** [comment]
the error its from addon world quest list  .
