### ISSUE TITLE
[Retail Bug Report] Voice overlay positioning

### ISSUE THREAD

**Issue by crbntyp** [tukui-org/ElvUI#500]
### What is the issue you are having?

The voice overlay is not respecting the position given on the interface grid, instead, it centres over the action bars.

### What is the expected behavior?

To a position were placed.

### What actually happened?

It positions itself bottom centre 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Is this still an issue?  If so, 

Type in chat in game
`/edebug on`
Do you still have the issue?

If so, type in chat in game
`/estatus` and upload a full UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by kodewdle** [comment]
closing, no response. reopen if needed. :)
