### ISSUE TITLE
[Retail Bug Report] <Add on not working at all>

### ISSUE THREAD

**Issue by Deimees** [tukui-org/ElvUI#501]
### What is the issue you are having?

i have installed the latest addon, every update that comes,, but when i go to enable the addon, it takes away my player bar and my target is also gone  and everything else just stays the same as the default blizz ui.

### What is the expected behavior?

addon expected to look before patch 10 of wow

### What actually happened?

whatever i do, can not solve issue, even just deleting the elvui in the addons folder and starting new.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by h21anlus** [comment]
Experiencing the same issue.

**Comment by Repooc** [comment]
sounds like you update manually and didnt DELETE the old ElvUI and ElvUI_OptionsUI folders before dropping in the new one (yes this matters even if it "worked" before but u are leaving files in there that will break this time around which is why you have to delete the old folders first before updating always)
