### ISSUE TITLE
[Retail Bug Report] <Summon Demon Skill Bug>

### ISSUE THREAD

**Issue by Angyolo** [tukui-org/ElvUI#504]
### What is the issue you are having?

Trying to use the "Summon Demon" Skill on my warlock using elvui, but the list of demons don't appear after using the skill on a keybind.  If I open my spellbook, the list of demons show, but if I'm using it on a keybind or clicking on it on my action bars, the list doesn't show.

### What is the expected behavior?

The list of demons should show after I use the "Summon Demon" skill on an action bar.

### What actually happened?

List of demons don't show when using the "Summon Demon" skill on my warlock when the skill is clicked or binded on an action bar.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
This is a known issue that Blizzard has to fix.
