### ISSUE TITLE
[Retail Bug Report] <Mage Teleport/Portal Tab won't open>

### ISSUE THREAD

**Issue by xILightning** [tukui-org/ElvUI#506]
### What is the issue you are having?

If i click the Teleport/Portal icon to open the Teleport Tab, nothing happen just a voice that says "fatality" and the arrow shows it always open upside.
![Issue](https://user-images.githubusercontent.com/109232751/199952885-3c99ff33-329c-4b22-a958-02b5a73712ef.png)
Version: 12.99

### What is the expected behavior?

The Teleport/Portal Bar open up and let me teleport

### What actually happened?

nothing, just a voice sayin' "fatality"

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Fri Nov  4 11:47:35 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
Kwown issue about flyouts that has been reported 50 times already that Blizzard hsa to fix.
