### ISSUE TITLE
[Retail Bug Report] <BlizzUI party frame randomly appear when entering a new instance>

### ISSUE THREAD

**Issue by Vinko90** [tukui-org/ElvUI#508]
### What is the issue you are having?

Sometimes when entering a dungeon/raid, the BlizzUI party frame appear on top of the ElvUI party frame. 

The way to get rid of it is to click ESC -> Edit Mode -> Then close Edit mode and the BlizzUI party frame disappear.

See image below:
![](https://i.imgur.com/qElwUXZ.png)

### What is the expected behavior?

I am expecting to don't see Party or Raid frames from BlizzUI if I am using ElvUI.

### What actually happened?

When entering dungeons, sometimes the BlizzUI party frame show up.

### Errors

```shell
Tried enabling the debug mode but unfortunately I don't see any errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Fortex365** [comment]
I had same issues but opening and closing new edit mode from blizzard.
