### ISSUE TITLE
[Retail Bug Report] Hunter 'Call Pet' action generates Lua error

### ISSUE THREAD

**Issue by 78Weaver** [tukui-org/ElvUI#509]
### What is the issue you are having?

When I use the Hunter 'Call Pet' action from an ElvUI action bar, it generates the following Lua error (see error below).
It works fine from the Blizzard Hunter Spellbook.

### What is the expected behavior?

When using the 'Call Pet' button, you should see a list of available pets to summon.

### What actually happened?

Upon clicking the 'Call Pet' button from an ElvUI action bar, it generates the error below.
I have to use the Blizzard Hunter Spellbook to call my pet.

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Fri Nov  4 16:25:02 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
Known blizzard issue that they even confirmed.
![image](https://user-images.githubusercontent.com/18713839/200101742-b7a56309-0d37-4d0c-b2fd-af0ad67ccbd0.png)
