### ISSUE TITLE
[Feature Request] Add visibility state to classbar

### ISSUE THREAD

**Issue by Belplao** [tukui-org/ElvUI#51]
**Is your feature request related to a problem? Please describe.**
Using player classbar on center of screen and noticed warlock cannot be rly affected by "auto-hide" feature. It hides classbar when full or empty, but warlock is kinda never having it, which means it will always be shown on my screen.
An option to hide out of combat or adding visibility state so anyone can customize as they want, would solve this problem

**Describe the solution you'd like**
As described above, if you could add visibility state just as Action Bars have, anyone could customize when they want to see classbar. IF its too much of pain, then it would be awesome to have at least "hide out of combat" option.

**Describe alternatives you've considered**
Alternative is noted above, but it would be an option to hide out of combat

**Additional context**
I know i can just move classbar to somewhere it doesnt disturb, but it causes even more annoyance under my player frame, sadly, meanwhile i must have a track on it as it contains important info.

Thanks in advance

**Comment by Azilroka** [comment]
visibility - no, hide out of combat - most likely.
