### ISSUE TITLE
[Retail Bug Report] Reputation bar not working past exalted

### ISSUE THREAD

**Issue by OlivierCodol** [tukui-org/ElvUI#512]
### What is the issue you are having?

The reputation bar is empty when tracking an exalted reputation which is now at the "reward" level.

### What is the expected behavior?

The reputation bar should track reputation progress at the "reward" level.

### What actually happened?

The reputation bar does not track reputation progress at the "reward" level, and instead shows as an empty bar.

### Suggested Solution/Workaround

None.

### Errors

```shell
No errors.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Eldranil** [comment]
This pull request looks promising ( #511 ), didn't think to look there.
