### ISSUE TITLE
[Retail Bug Report] <Can't use items from bag if All-In-One 'Bags' Module is disabled>

### ISSUE THREAD

**Issue by Alysrazor** [tukui-org/ElvUI#513]
### What is the issue you are having?

I can't use any item from the bags if I disable the All-In-One 'Bags' Module.

### What is the expected behavior?

I should be able to use any item from the bags even if the All-In-One 'Bags' Module is disabled.

### What actually happened?

https://user-images.githubusercontent.com/22854149/200108178-730b6954-f3aa-4849-a48d-265b2a2d8e2e.mp4

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by dezzuzu** [comment]
it's a hit or miss with me. sometimes interacting with the bag works, and on some characters it never works. hopefully there's a fix soon

**Comment by MatuMikey** [comment]
This issue is not related to just the all-in-one bag. See #520
