### ISSUE TITLE
[Retail Bug Report] Drop down menu for abilities on bar wont open, causing a lua error

### ISSUE THREAD

**Issue by irinoulaa** [tukui-org/ElvUI#516]
### What is the issue you are having?

Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What is the expected behavior?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What actually happened?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

Suggested Solution/Workaround
No idea.

### What is the expected behavior?

Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What is the expected behavior?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What actually happened?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

Suggested Solution/Workaround
No idea.

### What actually happened?

Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What is the expected behavior?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

What actually happened?
Everytime I click on elvui on my char, for a drop down menu, for example: hunter pets, the ability that opens the menu in my bars, to click on a certain pet, it doesnt open, and pop up a lua error.

Suggested Solution/Workaround
No idea.

### Suggested Solution/Workaround

No idea.

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sat Nov  5 12:43:30 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
This is a known issue that Blzizard has to fix.
