### ISSUE TITLE
[Retail Bug Report] <Expand buttons not working EG mage portals/hunter pets>

### ISSUE THREAD

**Issue by cjtowns12** [tukui-org/ElvUI#518]
### What is the issue you are having?

buttons that you click to expand your options are not working
Mage - teleports/portals
warlock - summon demon
hunter - summon pets

### What is the expected behavior?

the button should expand to allow you to click on further options. 

### What actually happened?

nothing happens when you click the initial button

### Errors

```shell
no errors showing
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by AphelionZero** [comment]
I'm getting this also and have taken the same steps to diagnose it. The error bugsack grabs is as follows:

`23x Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?`

**Comment by cjtowns12** [comment]
Hi,
I'm sorry you will have to dumb this down for me.
Is that just the error code or something that I need to input?

Thanks


Sent from Samsung Mobile on O2



-------- Original message --------
From: AphelionZero ***@***.***>
Date: 05/11/2022 15:48 (GMT+00:00)
To: tukui-org/ElvUI ***@***.***>
Cc: cjtowns12 ***@***.***>, Author ***@***.***>
Subject: Re: [tukui-org/ElvUI] [Retail Bug Report] (Issue #518)


I'm getting this also and have taken the same steps to diagnose it. The error bugsack grabs is as follows:

23x Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value) [string "=[C]"]: ? [string "=[C]"]: ? [string ***@***.***/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39> [string ***@***.***/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263> [string "=[C]"]: ? [string ***@***.***/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279> [string "=(tail call)"]: ?

**Comment by Repooc** [comment]
flyout button issues are a known blizzard issue
