### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#519]
### What is the issue you are having?

Pet Bar moves top left of the screen with weird spacing "sometimes" in combat and throw an LUA Taint Error.

### What is the expected behavior?

Pet Bar do NOT move top left of the screen ^^

### What actually happened?

Pet Bar do move top left of the screen

### Suggested Solution/Workaround

Reload UI and wait until it happens again -> reload UI -> Repeat...

### Errors

```shell
LUA Error:

1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function <Interface/FrameXML/UIParent.lua:3102>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:1470: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:1365>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua"]:878: in function <...zzard_ObjectiveTracker/Blizzard_ObjectiveTracker.lua:876>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Calesta** [comment]
The same thing happens after a pet battle.

Before a pet battle, everything is fine with the pet bar just above the action bars as I positioned it.

https://imgur.com/QoQ2yra

Afterwards, the pet bar shifts to a random location.

Example 1, Shifts Left & Intertwined in the Action Bars (with spaces): https://imgur.com/enjhvEo

Example 2, Shifts to the Upper Left Hand Corner (with spaces): https://imgur.com/f7K74T8

A simple /reload fixes the positioning.

**Comment by jeremy-hill** [comment]
Same: Pet abilities are way off (upper left) when they are anchored elsewhere (bottom right). https://i.imgur.com/Fd7UL4j.png
