### ISSUE TITLE
[Retail Bug Report] <"Drop down" buttons on action bars do not work>

### ISSUE THREAD

**Issue by Egiukaz** [tukui-org/ElvUI#521]
### What is the issue you are having?

"Drop down" buttons such as rogue's Poisons, hunter's "Pet utility", "Call Pet", mage's Portals and Teleport do not expand when clicked. This behavior is noticed after 10.00 release.
Using ElvUI 12.99

### What is the expected behavior?

When pressed mentioned buttons should expand with additional buttons as intended.

### What actually happened?

As described above, mentioned button simply do not react when clicked.

### Errors

```shell
No Errors are being noticed.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by brett1337** [comment]
this has been posted 20 times plz delete

**Comment by Egiukaz** [comment]
Couldn't find nothing similar, could you link at least couple out of these 20?

**Comment by Egiukaz** [comment]
Thanks, was searching only in open tickets, forgot to look in closed ones.
