### ISSUE TITLE
[Classic Bug Report] May be an issue with pet bar

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#522]
### What is the issue you are having?

When I got to move abilities on the pet bar, they disappear. And when I got to add them back to the bar from the spell book they can't be dropped on to the bar.

### What is the expected behavior?

It should work.

### What actually happened?

It doesn't work.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Classic Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
Reproduce by re-arranging active pet abilities.

**Comment by Gogo1951** [comment]
May be related. 

14x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'OverrideActionBarButton3:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:480: in function <!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `Show'
[string "@FrameXML\ActionButton.lua"]:357: in function `ActionButton_Update'
[string "@FrameXML\ActionButton.lua"]:694: in function `ActionButton_OnEvent'
[string "@FrameXML\ActionButton.lua"]:207: in function <FrameXML\ActionButton.lua:204>

**Comment by donagrejja** [comment]
I have the same issue in WotLK/Classic.

When I try to move a pet spell I can't put it back. The slot becomes unusable.
So then I have to perform reloadui for every pet spell/action that I want to move or replace on the pet action bar.
