### ISSUE TITLE
[Retail Bug Report] <ElvUI  not loading in wow retail 

### ISSUE THREAD

**Issue by dhyde2022** [tukui-org/ElvUI#524]
### What is the issue you are having?

I have updated ELvUI to the latest update but it is not loading into my world of warcraft 

![2022-11-06_15h51_58](https://user-images.githubusercontent.com/117586940/200180747-294ce2e7-46e8-4eb8-92d0-167b85e5c796.png)

### What is the expected behavior?

the release of 10.0 

### What actually happened?

![2022-11-06_15h54_48](https://user-images.githubusercontent.com/117586940/200180892-57373620-528d-4901-bebb-d6bf3bfabb68.png)

### Errors

```shell
Message: [string "Interface/AddOns/ElvUI/TaintLess.xml:<Scrip..."]:56: attempt to index global 'InterfaceOptionsFrame' (a nil value)
Time: Sun Nov  6 15:48:24 2022
Count: 1
Stack: [string "Interface/AddOns/ElvUI/TaintLess.xml:<Scrip..."]:56: attempt to index global 'InterfaceOptionsFrame' (a nil value)
[string "Interface/AddOns/ElvUI/TaintLess.xml:<Scripts>"]:56: in main chunk

Locals: purgeKey = <function> defined Interface/AddOns/ElvUI/TaintLess.xml:<Scripts>:11
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = "attempt to index global 'InterfaceOptionsFrame' (a nil value)"


that is 1 out of 184 errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Looks like u update manually and didn't delete the 2 old folders ElvUI and ElvUI_OptionsUI before dropping the new ones in
