### ISSUE TITLE
[Retail Bug Report]  Actionbar Keybind Bugs

### ISSUE THREAD

**Issue by MeetTh3Greed** [tukui-org/ElvUI#526]
### What is the issue you are having?

I use a mix of the new interface from patch 10.0 and elv ui 12.99, after a teleport for example joining a group dungeon, pvp or just a portal to ogrimmar i get lua errors after i try rolling (as monk). I use normal keybinds and the ability is in action bar 2 , binded on "F". The Lua error says "elvui is trying to use a protected funtion "UseAction ()". Sometimes the whole actionbars cant be used after this. I can click the actions bars but if i hit the binded keys i only get the sound and glow up on the action bar but no abilty get activated.

### What is the expected behavior?

Normal activation of binded abilities in actionsbar by using keybinds

### What actually happened?

![grafik](https://user-images.githubusercontent.com/117592530/200185989-efbe6bae-e4c7-4071-b69d-981720cd8139.png)

### Suggested Solution/Workaround

Dont have any idea

### Errors

```shell
See the screenshot
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by MeetTh3Greed** [comment]
18:57 [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' hat versucht die geschützte Funktion 'TargetUnit()' aufzurufen. 
18:57 [string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1518: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1462: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:171: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:193: in function <Interface/FrameXML/EditModeManager.lua:191>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2844: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2648: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2552: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

**Comment by MeetTh3Greed** [comment]
This is the LUA Error if the Action Bars doesnt work anymore.

20:37 [Error 000002140222DDE0] gefangen, klicke auf den Link für mehr Informationen. 
20:37 [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' hat versucht die geschützte Funktion 'UseAction()' aufzurufen. 
20:37 [string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:22: in function `MultiActionButtonUp'
[string "MULTIACTIONBAR1BUTTON7"]:4: in function <[string "MULTIACTIONBAR1BUTTON7"]:1>

**Comment by MeetTh3Greed** [comment]
Same Issue on Blizzard Forum from another user:

https://us.forums.blizzard.com/en/wow/t/help-with-elvuicliquedf-update-keybinds-not-working/1394376

**Comment by cityslicka** [comment]
I am having the same issue.

![image](https://user-images.githubusercontent.com/32719932/200201757-e1df06a7-c214-4959-b500-84ea34e72258.png)

I've isolated it to ElvUI.

Here's a screenshot of my full UI:
![image](https://user-images.githubusercontent.com/32719932/200201787-2bdd63b7-f121-4520-a64f-63d64c438820.png)

**I disabled taints, and used buggrabber + bugsack:**
2x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:22: in function `MultiActionButtonUp'
[string "MULTIACTIONBAR3BUTTON7"]:4: in function <[string "MULTIACTIONBAR3BUTTON7"]:1>

Not sure how helpful that is to debug.

Please let me know if there's anything I can provide to help the investigation.

Thanks!

**Comment by Astraphobiaa** [comment]
Do you using default Action Bar instead of Elvui Action Bar?
If yes, you can use Elvui action bar to fix the problem. Atleast for a while..
@MeetTh3Greed @cityslicka

**Comment by MeetTh3Greed** [comment]
yes i use default action bars, yes i already tried it with the elv ui action bars but i like the default skin so thats why ... and you already mentioned it just fix the problem for a while so i hope we get a solution for this ;)

**Comment by smbody-mipt** [comment]
Same here, also with only ElvUI enabled but default action bars. Hotkeys don't work, clicking on the bars works.

**Comment by gz2k2** [comment]
you can use this addon, to fix this bug:
https://www.curseforge.com/wow/addons/notaint2

**Comment by Astraphobiaa** [comment]
> you can use this addon, to fix this bug: https://www.curseforge.com/wow/addons/notaint2

It's just spamming "/reload" toast for me when im switching between zones. So didn't work.

**Comment by cityslicka** [comment]
Hoping we get an actual fix for this for Dragonflight, because I've been using ELVUI mostly for party frames, but have since switched to Vuhdo because it doesn't throw the same issue with default action bars.

**Comment by CrimsonChaord** [comment]
This is absolutely just when Elv actionbars are disabled. Bump for giga priority

**Comment by MeetTh3Greed** [comment]
yes i hope they will supply a fix with the new version 13.01 is still there

**Comment by CrimsonChaord** [comment]
bump

**Comment by MeetTh3Greed** [comment]
still not fixed if u dismount from dragons....

**Comment by MeetTh3Greed** [comment]
bump

**Comment by MeetTh3Greed** [comment]
2024 and the Problem still exist, its really strange its seems that it depends on the class.. only with monk this problem seems to appear
