### ISSUE TITLE
[Retail Bug Report] Abilities like Teleport don't show on actionbars

### ISSUE THREAD

**Issue by metaladrian95** [tukui-org/ElvUI#527]
### What is the issue you are having?

This issue started shortly after the prepatch went live but as of this moment any ability like a mage teleport that normally shows me all the portals then i can click and choose which one won't appear in my action bars once I click the icon. The spell is in my action bar, but the scroll feature won't appear. This is also an issue with other classes that have similar abilities like warlock summon demon, and hunter pet utilities. The only way to get the ability to work properly is to open the spell book and manually click it from there.

### What is the expected behavior?

Normally when I click on my action bar teleport spell it shows me all the teleport spells i can use but as of right now it doesn't do this.

### What actually happened?

Ability to work properly have to open spell book each time.

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Nov  6 09:40:33 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by jph290** [comment]
I am also having the same issue.  The Summons on Warlock as well as Polymorph Variants, Portals, and Teleports on Mage do not show the flyout that shows each of the spells.

**Comment by Repooc** [comment]
flyout button issues is a known blizzard issue
