### ISSUE TITLE
[Retail Bug Report] 3D portrait not fading 

### ISSUE THREAD

**Issue by oddball250** [tukui-org/ElvUI#529]
### What is the issue you are having?

Elvui's 3rd model for the player unitframe is not fading with everything unselected 

### What is the expected behavior?

normally the 3d model would just fade and then show back up when in combat or if selected

### What actually happened?

3d model is not fading for the player frame and stays stuck on the screen

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
Known issue affecting every addon in existence right now, so not something we need specifically here.
