### ISSUE TITLE
[TBC Bug Report] Friendly Unitframes fade at every range

### ISSUE THREAD

**Issue by Moonzen** [tukui-org/ElvUI#53]
### What is the issue you are having?

Unitframes for friendly units (target, targettarget, party, raid etc) fade at all range on my rogue, even if i'm next to them, even if i target myself.

On the Target Fader for example, i have Enabled checked and only "Range" checked, all the rest blank. Same with all the other Individual or Group Units.

Elvui updated to last version (2.21). Not sure if it was broken with 2.21/2.20/2.19 though.
Worked fine before 2.19, long time user of ElvUI.

I have several characters and this issue is not happening on others, using the exact same settings.
ONLY HAPPENS ON MY ROGUE. Maybe a talent issue, some info specific to the rogue that ElvUI is not catching?

### What is the expected behavior?

Friendly Unitframes should not be faded if close to them, and Target Unitframe should not be faded if i target myself.

### What actually happened?

Friendly Unitframes fade at every range, including if i'm next to the player or if i target myself.
The issue is only with Friendly units however, the Range Fader works well with enemy players / units.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Repooc** [comment]
already been addressed in the dev build
