### ISSUE TITLE
[Retail Bug Report] Summoning pet button doesn't work

### ISSUE THREAD

**Issue by Drey242** [tukui-org/ElvUI#531]
### What is the issue you are having?

When I click/press key on the summoning pet button (warlock/hunter, rogue poisons...) icons don't show up. I've tested some bar position.

It works when I do it from the grimoire.

I talk about this : https://imgur.com/5Lfliv3

I've tried to unable all other addons, remove cache folder... but nothing changed. I've checked WoW/Elvui options but I find nothing.

Game client : French
Elvui version : 12.99 (problem was the same with the 2 or 3 previous versions)

### What is the expected behavior?

Buttons should show up

### What actually happened?

Buttons don't show up

### Suggested Solution/Workaround

-

### Errors

```shell
No error
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by jeremy-hill** [comment]
Just so you know this is a Blizzard UI problem (try using stock UI and any of the buttons you're using with ElvUI).

https://github.com/Stanzilla/WoWUIBugs/issues/302

See other related ElvUI tickets attached to the above Wow UI bug post.
