### ISSUE TITLE
[Wrath Bug Report] Weird actionbar GCD animation on hover

### ISSUE THREAD

**Issue by ragnarla** [tukui-org/ElvUI#532]
### What is the issue you are having?

Ever since upgrading from 12.91 to 12.99, whenever I hover over any unit or unitframe, the actionbar cooldown animation for the spell Shadowform, on the bar, is triggered. 

This only occurs whilst in Shadowform.
Only affects regular action bar, stance bar seems unaffected.
Does not occur in druid forms using same profile.
Does not occur if ElvUI is disabled.

It does not seem to actually do anything, no spell is cast and no other spell button is affected, just visually very distracting.
Standing in a busy hub and moving the mouse over a bunch of players, the spell CD looks like it's constantly resetting.

Steps to reproduce:
- [optional] Create a new empty profile. All other addons disabled ( /edebug on )
- Place Shadowform on any actionbar
- Enter Shadowform
- Hover over any player or unit frame

### What is the expected behavior?

Nothing, no visual effect

### What actually happened?

Spell looks like it's going on cooldown
![image](https://user-images.githubusercontent.com/2362588/200377762-c4bb0201-9483-4799-8bb3-784d5061f4f0.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ikorodi** [comment]
hi, i'm actually experiencing the same for prowl, while prowled (cooldown looks like starting to count down every time when moving the mouse over any unit) .

**Comment by 1Botanica1** [comment]
Is this still an issue? If so 

Type in chat in game
/edebug on
Do you still have the issue?

If so, type in chat in game
/estatus and upload a full UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by ragnarla** [comment]
Thank you for showing an interest in this issue.
Yes, still happens in latest version.
It's a little hard to display animation on a screenshot, but one can at least see that the stance bar is not showing anything, while the shadowform icon on the toolbar shows a cooldown animation.
![image](https://user-images.githubusercontent.com/2362588/234645997-4aea4016-3878-44c1-8129-816f6771116d.png)
![image](https://user-images.githubusercontent.com/2362588/234644923-728561e6-6d61-42c4-8065-15a62f1e3cb1.png)

**Comment by tjmitchell1** [comment]
I am also having this occur, are you using `/use !Shadowform` to prevent accidentally leaving shadowform as well?

**Comment by ragnarla** [comment]
> I am also having this occur, are you using `/use !Shadowform` to prevent accidentally leaving shadowform as well?
> 
> No LUA errors pop up or anything else when edebug on is set

No, no macro

**Comment by Luckyone961** [comment]
Can't reproduce

**Comment by tjmitchell1** [comment]
@Luckyone961 Did you test this with the live version of elvui or the development version? Still getting this behavior on live.
