### ISSUE TITLE
[Retail Bug Report] <group finder Error > LFG errors

### ISSUE THREAD

**Issue by uaeuaeuae** [tukui-org/ElvUI#533]
### What is the issue you are having?

when I opened group finder and just mouse over any opened group, I got this error 

6x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface/FrameXML/LFGList.lua"]:3520: in function <Interface/FrameXML/LFGList.lua:3509>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2595: in function <Interface/FrameXML/LFGList.lua:2592>
[string "=[C]"]: ?

### What is the expected behavior?

nothing

### What actually happened?

6x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface/FrameXML/LFGList.lua"]:3520: in function <Interface/FrameXML/LFGList.lua:3509>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2595: in function <Interface/FrameXML/LFGList.lua:2592>
[string "=[C]"]: ?

### Suggested Solution/Workaround

Need Fix 

### Errors

```shell
6x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface/FrameXML/LFGList.lua"]:3520: in function <Interface/FrameXML/LFGList.lua:3509>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2595: in function <Interface/FrameXML/LFGList.lua:2592>
[string "=[C]"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ysosrslawl** [comment]
I am still receiving this error and I have updated elvui as of today.

**Comment by ysosrslawl** [comment]
I am still receiving this error. Please see the following.

`Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'GetPlaystyleString()'.
Time: Sat Dec  3 19:21:40 2022
Count: 12
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BugSack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@Interface/FrameXML/LFGList.lua"]:3522: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2597: in function <Interface/FrameXML/LFGList.lua:2594>

Locals: <none>`

**Comment by heikki-nieminen** [comment]
2x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML/LFGList.lua"]:3522: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2597: in function <FrameXML/LFGList.lua:2594>
