### ISSUE TITLE
[Retail Bug Report] Call-outs not working

### ISSUE THREAD

**Issue by dburnt** [tukui-org/ElvUI#534]
### What is the issue you are having?

Any action bar item that features a "call-out" (i.e. a pull up menu) such as (but not limited to) Teleport, Portal, Summon Demon, Pet Utilities, etc. does not work (Clicking on it throws a LUA error, and the menu doesn't pull up).

### What is the expected behavior?

To be able to click on the action bar and see the list of applicable spells.

### What actually happened?

No response, and a LUA error generated

### Suggested Solution/Workaround

No workaround discovered

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by nihilistzsche** [comment]
Known Blizzard issue that Blizzard must fix.
