### ISSUE TITLE
[Retail Bug Report] <Bank bag disappaer>

### ISSUE THREAD

**Issue by Hilldres** [tukui-org/ElvUI#535]
### What is the issue you are having?

After addon updated to 12.92, one of the bank bag disappear from the all-in-one bank interface. That bag shows a red cross on the bank bag bar, and everything in the bag does not shown up (items still in bank).
![WoWScrnShot_110822_120857](https://user-images.githubusercontent.com/117704154/200473086-486e888d-53cd-4032-ac4e-84cc85cb340b.jpg)
![WoWScrnShot_110822_120905](https://user-images.githubusercontent.com/117704154/200473091-daba877c-e321-4877-bc07-043d8e30ee83.jpg)

### What is the expected behavior?

The bag should shown up with all it contained in the bank interface.

### What actually happened?

It does not shown up with what it contained.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Read the tooltip the bottom 2 lines. Red X means its toggled off.
