### ISSUE TITLE
[Retail Bug Report] Volume datatext LUA error when changing output device

### ISSUE THREAD

**Issue by NoNick96** [tukui-org/ElvUI#538]
### What is the issue you are having?

When I shift click on the Volume datatext and select any audio output device the device is changed correctly, but I get a LUA error.

### What is the expected behavior?

No LUA errors when switching audio output device via Volume datatext

### What actually happened?

LUA error when switching audio output device via Volume datatext

### Errors

```shell
17x ...rface/AddOns/ElvUI/Core/Modules/DataTexts/Volume.lua:53: attempt to perform arithmetic on a nil value
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Volume.lua"]:53: in function <...rface/AddOns/ElvUI/Core/Modules/DataTexts/Volume.lua:49>
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Volume.lua"]:140: in function <...rface/AddOns/ElvUI/Core/Modules/DataTexts/Volume.lua:129>

Locals:
stream = <table> {
 Enabled = "Sound_EnableAllSound"
 Name = "Master"
 Volume = "Sound_MasterVolume"
}
tooltip = nil
color = "00FF00"
(*temporary) = nil
(*temporary) = "Sound_MasterVolume"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "Sound_MasterVolume"
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a nil value"
AudioStreams = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
}
GetCVarBool = <function> defined @Interface/SharedXML/CvarUtil.lua:29
GetCVar = <function> defined @Interface/SharedXML/CvarUtil.lua:17
format = <function> defined =[C]:-1
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
Fix in dev
