### ISSUE TITLE
[Retail Bug Report] GetPlaystyleString Lua error

### ISSUE THREAD

**Issue by komxela** [tukui-org/ElvUI#539]
### What is the issue you are having?

Using ElvUI v12.99. 
Lua occurrs when I mouseover the list of groups in premade groups section. 

### What is the expected behavior?

There should be no lua error.

### What actually happened?

Lua occurrs when I mouseover the list of groups in premade groups section. 

### Suggested Solution/Workaround

N/A

### Errors

```shell
7x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function GetPlaystyleString' [string "@Interface/FrameXML/LFGList.lua"]:3520: in function <Interface/FrameXML/LFGList.lua:3509> [string "=[C]"]: in function LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2595: in function <Interface/FrameXML/LFGList.lua:2592>
[string "=[C]"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This is a taint - see here https://github.com/tukui-org/ElvUI/wiki/errors

Are you still getting the taint?

Type in chat in game
`/edebug on`
Do you still have the issue?

If so, type in chat in game
`/estatus` and upload a full UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by kodewdle** [comment]
closing, no response. reopen if needed. :)
