### ISSUE TITLE
[Retail Bug Report] cooldowns issue with skills charges

### ISSUE THREAD

**Issue by drsleo** [tukui-org/ElvUI#541]
### What is the issue you are having?

#
![WoWScrnShot_111022_010450](https://user-images.githubusercontent.com/63939756/201000154-7346f395-5b70-4d1f-b272-35a7878fcbca.jpg)
using blizzard cooldowns texts, the numbers are below as shown in the photo, only in skills with charges

### What is the expected behavior?

.

### What actually happened?

.

### ElvUI Changelog & Troubleshooting

- [x] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [x] I have verfied ElvUI is up to date by checking /estatus.
- [x] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [x] I have verfied my issue doesn't exist in the default UI.
- [x] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
Can't reproduce
