### ISSUE TITLE
[Feature Request] Tooltip grow direction options

### ISSUE THREAD

**Issue by bchevreau** [tukui-org/ElvUI#543]
**Is your feature request related to a problem? Please describe.**
The current tooltip can only grow from bottom-right anchor position. And it solely grows from Right to left, and thus overlaps other UI elements or messes up alignment, especially when the anchor is placed to display the tooltip on the right side of the screen.

**Describe the solution you'd like**
Allow for selection of TOPRIGHT / TOPLEFT / BOTTOMRIGHT / BOTTOMLEFT / CENTER options like any other bar or frame. Allow growth direction Left / Right / Center like you do for bars or text positioning.

**Describe alternatives you've considered**
Another addon, such as TipTac. Showing tooltip on left side has more chances to fail with raid frames and such

**Additional context**
Here are 2 tooltips that would look fantastic if the anchor was bottom-left and growing from left to right, but dont because only bottom right Right=>Left grow is available and no option to change it. you can clearly see misalignement with chat/details panel below it.
![image](https://user-images.githubusercontent.com/12772470/201073997-d466ce91-d7b9-4343-adad-9f0e99a2594a.png)
![image](https://user-images.githubusercontent.com/12772470/201074058-06a3821c-198e-4ac1-b07d-704dd7d18dbd.png)

Thank you again for all your fantastic work. I simply hope to find more

**Comment by mohcow** [comment]
Another thing would be the option to disable the spacing between the anchor and the actual tooltip.
