### ISSUE TITLE
HyperDT is to be removed NOW

### ISSUE THREAD

**Issue by nihilistzsche** [tukui-org/ElvUI#545]
HyperDT was added to ElvUI with my permission, however, due to recent circumstances and a primadonna who thinks they are god, I am rescinding that permission in its entirety, and I will give you until Sunday to remove all mentions of HyperDT and HyperDT functionality from ElvUI you no longer have my permission to use it.

**Comment by Azilroka** [comment]
I removed the original hyperdt and also removed the last comment that i forgot the first time because I made sure where credit was due it was done.

**Comment by nihilistzsche** [comment]
No, you have no right to the idea at all anymore.  Remove it now.
