### ISSUE TITLE
[Feature Request] Player always at top or bottom of UnitFrames in Raid group

### ISSUE THREAD

**Issue by ki-88** [tukui-org/ElvUI#546]
My issue : my unitframe placement within a raid group is random which confuses me a lot in arenas and ruin the placement of my team ability tracker. Examples:

First arena fight:
Party1
Me
Party2
Second arena fight:
Me
Party1
Party2

Solution: 
Add a feature that makes me always in bottom or always in top every time I am in a raid group. Example:
Me
Party1
Party2 

or 
Party1
Party2
Me 

at all times.

I have tried using other solutions such as rearrange group based on class or role. but that makes it even more confusing since Sometimes the first person in the raid is not actually party1, it could be party2 or party3 while party1 is last or vesa versa.

**Comment by Azilroka** [comment]
No way to do this without writing a custom player setup for strings which would have to be done each time you form up
