### ISSUE TITLE
GPL Violations

### ISSUE THREAD

**Issue by nihilistzsche** [tukui-org/ElvUI#547]
As you have admitted to using GPL licensed libraries in ElvUI, you have two choices:

You either relicense ElvUI to the GPL, or you remove all of the GPL licensed libraries, you have no other choices.  If this is not done by Sunday I will report the repository to Github and let them deal with it.

**Comment by Luckyone961** [comment]
Could you please clarify which part of the GPL is being violated. The ElvUI license does not cover 3rd party (which includes Libraries)

The contents of this addon, excluding third-party resources, are copyrighted to their authors with all rights reserved.

"excluding third-party resources" in this case

**Comment by nihilistzsche** [comment]
The GNU Public License require all parts of a program to be using a license that is compatible with the GNU Public License.  ElvUIs license is not, therefore you are in violation using any Library that is licensed under the GPL.

**Comment by nihilistzsche** [comment]
https://www.gnu.org/licenses/license-compatibility.en.html

**Comment by nihilistzsche** [comment]
The LGPL would allow your excluding third-party resources line to work, the GPL explicitly does not.

**Comment by Luckyone961** [comment]
Thanks, appreciate the quick reply

**Comment by Luckyone961** [comment]
As of right now, ElvUI removed all libraries licensed under the GPL.

The repository license for tukui-org/ElvUI has been [Updated](https://github.com/tukui-org/ElvUI/blob/development/LICENSE.md)

and a Third Party Notice has been added for all other files [here](https://github.com/tukui-org/ElvUI/blob/development/ThirdPartyNotices.md)
