### ISSUE TITLE
HyperDT to be remove NOW.

### ISSUE THREAD

**Issue by nihilistzsche** [tukui-org/ElvUI#548]
HyperDT was added to ElvUI with my permission, however, due to recent circumstances and a primadonna who thinks they are god, I am rescinding that permission in its entirety, and I will give you until Sunday to remove all mentions of HyperDT and HyperDT functionality from ElvUI you no longer have my permission to use it.

Closign the issue does not absolve you, you no longer have permissio nto use my idea, to use code derived from my idea, or to mention it any way shape or form.

**Comment by nihilistzsche** [comment]
I do not care if you thumbs down me, QuickDT/HyperDT was from my idea, and I rescind any permission I ever gave for it.

**Comment by linaori** [comment]
Can you prove that it was your idea?

Besides of that, my thumbs down is because of how petty this is. Willing to screw over hundreds of thousands of ElvUI users and forcing devs to use up free time to fix this for you, while there's literally no issue.

**Comment by nihilistzsche** [comment]
I wrote it about 12 years ago in NihilistzscheUI, and Azilroka said he would like to use it, and I gave him permission for it, he will admit it was my idea.  And there is an issue, the issue is Simpy.

**Comment by BarryDonovan** [comment]
I think Azilroka made it clear in the first post you made about this, you cant withdraw an idea you have given permission for, he already stated it has been re-written, he closed your first issue properly and should resort to just closing this one to be fair.

**Comment by linaori** [comment]
So now you want to punish everyone else? It's really petty and childish.

**Comment by nihilistzsche** [comment]
I do not care.

**Comment by BarryDonovan** [comment]
> I can withdraw permission for my idea, the rewritten code was derived from mine and since that permission has been withdrawn that code can no longer exist. I'm not sorry, Simpy could have simply said he was sorry and let it go but instead he chose to punish me for something he did, so my patience and willingness to cooperate is at an end.

I don't see how you are possibly gonna win in this but good luck in your delusion of the idea of withdrawing an idea. I think your are delusional and childish, and Azilroka already dealt with you properly in the first place. You are grasping for air at this point.

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/201342748-868d3610-9076-4f87-a78e-1e10363ad410.png)

**Comment by Azilroka** [comment]
https://www.copyright.gov/help/faq/faq-protect.html
