### ISSUE TITLE
Skill  summon deamon does not work

### ISSUE THREAD

**Issue by GregorFey** [tukui-org/ElvUI#550]
### What is the issue you are having?

The warlock skill summon deamon does not work when put on an action bar. 

### What is the expected behavior?

With a left click of the mouse a submenu with all available deamons should be shown.

### What actually happened?

The spell icon is highlighted in response to the mouse click, but the submenu to select a the deamom to summon is not shown. The standard ui shows the submenu.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Caedis** [comment]
[Issue with spell flyouts is on Blizz's side](https://us.forums.blizzard.com/en/wow/en/wow/t/lua-error-stopping-me-from-using-summon-demon/1383629/13)
