### ISSUE TITLE
Hunter Call Pet & Pet Utility & Warlock Summon Deamon

### ISSUE THREAD

**Issue by Newkhaos** [tukui-org/ElvUI#551]
### What is the issue you are having?

the hunter Call Pet, Hunter Pet Utility and Warlock summon Deamon, when i put the ability in the action bar, does not open de box, therfore a can't select anything if the ability is in the action bar.
It woerk ok in Wow deafult interface (both action bar and spellbook and it works OK with ELVUi speelbook, but does nothing in the action bar. 

### What is the expected behavior?

The ability should open in the arrow, thus i can select it.

### What actually happened?

the ability does not expand in the action bar.

### Suggested Solution/Workaround

None

### Errors

```shell
No errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the two called 'ElvUI' and 'ElvUI OptionsUI' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://cdn.discordapp.com/attachments/222356141785612288/1040613855501492405/image.png

**Comment by jimmyjimjamfam** [comment]
I also have this same issue. It is the same with rogue poisons and teleports etc.

**Comment by Mkorny** [comment]
Can confirm this bug as well, any "expanding" ability does not expand and this is extremely impactful for hunters/warlocks..
