### ISSUE TITLE
Retail Bug objectives frames and talking head frames dissapeared

### ISSUE THREAD

**Issue by Zarkki** [tukui-org/ElvUI#552]
### What is the issue you are having?

The objetive tracker frame and the talking head frame dissapeared from the Elvui movable options two days ago.
Try to fix turning off the addons but not is the problem.

### What is the expected behavior?

Before the last update both options work fine

### What actually happened?

Cant move frames of objetives/quest or talking head when i work in my new UI

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by NomadTheOne** [comment]
Since 13.10 update i have exactly the same issue. I have tested with or without any other addons. Also tried to delete ElvUI and ElvUI_Options and update again with no difference after all. The only way i have found to move Quest Tracker, was through the Blizzard's edit mode, but it only works for resetting the default position.

**Comment by Repooc** [comment]
we removed them and the only way to move them is with blizzards edit mode, i found i had to disable elvui and move the quest frame and save that layout for it to move then reenable elvui.  But yeah, elvui doesnt move either frame now
