### ISSUE TITLE
[Retail Bug Report] Lua Error

### ISSUE THREAD

**Issue by MalikiOne** [tukui-org/ElvUI#554]
### What is the issue you are having?

Getting a lua error

### What is the expected behavior?

Not getting a lua error

### What actually happened?

 [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'UIParentRightManagedFrameContainer:SetPoint()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function <Interface/FrameXML/UIParent.lua:3102>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetPowerBarFrame.lua"]:8: in function `layoutFunc'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:530: in function `UpdateWidgetLayout'
[string "@Interface/AddOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua"]:60: in function <...dOns/Blizzard_UIWidgets/Blizzard_UIWidgetManager.lua:57>

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [ ] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Vilogity** [comment]
Same

1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' hat versucht die geschützte Funktion 'UIParentRightManagedFrameContainer:SetPoint()' aufzurufen.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@Interface/SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@Interface/FrameXML/UIParent.lua"]:3086: in function `UIParentManageFramePositions'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3104: in function <Interface/FrameXML/UIParent.lua:3102>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@Interface/FrameXML/TargetFrame.lua"]:191: in function `OnEvent'
[string "@Interface/FrameXML/UnitFrame.lua"]:1044: in function <Interface/FrameXML/UnitFrame.lua:1042>

Locals:
Skipped (In Encounter)
