### ISSUE TITLE
[Classic Bug Report] Error Quest Tracker

### ISSUE THREAD

**Issue by salome161** [tukui-org/ElvUI#555]
### What is the issue you are having?

Bugsack is catching an error concerning the quest tracker. I disabled all addons except basic elv, no plug ins, and bugsack. Still had the same error. Dowloaded KalielsTracker because when tracing the the error it said line 95 was the error. Line 95 in the current version of 13.01 is support for KalielsTracker addon. Installed and reloaded the error went away. 

My husband who is not running the current version published as of 11/11/22 has this line of code on line 91 in an older version which corresponds with line 95: 
if (E.Retail or E.Wrath) and not E:IsAddOnEnabled('DugisGuideViewerZ') and not E:IsAddOnEnabled('!KalielsTracker') then
		B:MoveObjectiveFrame()
	end

### What is the expected behavior?

Umm no error rather or not I am or am not running a quest tracker addon.

### What actually happened?

Basically if Im not running KalielsTracker then I am going to get an error every time I log in. I run questie but with or without questie on there is still an error. The only way to not have an error is to run KalielTracker.

### Suggested Solution/Workaround

When I added 

if (E.Retail or E.Wrath) and 

to:

if not (E:IsAddOnEnabled('DugisGuideViewerZ') or E:IsAddOnEnabled('!KalielsTracker')) then
		B:MoveObjectiveFrame()
	end

To this: 

if (E.Retail or E.Wrath) and not (E:IsAddOnEnabled('DugisGuideViewerZ') or E:IsAddOnEnabled('!KalielsTracker')) then
		B:MoveObjectiveFrame()
	end

The error went away. With or with out quest worked, with or without KalielsTracker worked.

### Errors

```shell
Bugsack is catching this......
...faceElvUI\Core\Modules\Blizzard\Blizzard.lua:95: attempt to call method 'MoveObjectiveFrame' (a nil value)
[string "@ElvUI\Core\Modules\Blizzard\Blizzard.lua"]:95: in function <...faceElvUI\Core\Modules\Blizzard\Blizzard.lua:61>
[string "=[C]"]: ?
[string "@ElvUI\Core\General\Core.lua"]:1788: in function `CallLoadFunc'
[string "@ElvUI\Core\General\Core.lua"]:1803: in function `CallLoadedModule'
[string "@ElvUI\Core\General\Core.lua"]:1829: in function `InitializeModules'
[string "@ElvUI\Core\General\Core.lua"]:1938: in function `Initialize'
[string "@ElvUI\Core\init.lua"]:226: in function <ElvUI\Core\init.lua:225>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:66: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:626: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:611>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
thanks for the report and suggestion.  fixed in dev. 🌼
