### ISSUE TITLE
[Retail Bug Report] Bag search stopped working for terms bo{a,e,p}

### ISSUE THREAD

**Issue by Mr-nUUb** [tukui-org/ElvUI#556]
### What is the issue you are having?

Previously, ElvUI allowed searching bags with the terms "boe", "boa" and "bop". It highlighted all items that were bound on equip, account, pickup respectively. Today, after applying version 13.01, nothing is highlighted using these terms.

Is this connected to the change _"Bag search will now be simplified to using the same API Blizzard provides for their bags"_?

To the default UI part: using these terms never worked and was a feature of ElvUI.

### What is the expected behavior?

Search input "boe" should highlight items bound on equip.
Search input "boa" should highlight items bound to Battle.net Account.
Search input "bop" should highlight items bound on pickup.

### What actually happened?

None of the aforementioned search terms highlights anything.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
![Image](https://i.imgur.com/YeoDyZB.png)

**Comment by Luckyone961** [comment]
boe, boa, bop are all part of a Custom Search library which can no longer be used due to license issues.
