### ISSUE TITLE
[Feature Request] Add loadout string to the player inspect > talents button

### ISSUE THREAD

**Issue by rctunisi** [tukui-org/ElvUI#557]
It would be really helpful if you could add the current loadout string of the player inspect > talents button

Example of the inspect > talents view with the loadout string and copy button (could be replaced by a interactable string field on the loadout string)
![image](https://user-images.githubusercontent.com/24812426/201477096-2c3cc435-1adb-4639-9abe-2505ea34b2db.png)

Sorry about the simplicity, but the idea is pretty straightforward and its my first feature request for ElvUI :)

**Comment by Azilroka** [comment]
I'm almost confident that we will not be touching that as it could taint the TalentUI

**Comment by rctunisi** [comment]
> I'm almost confident that we will not be touching that as it could taint the TalentUI

add an extra window to it? or even a button to copy the loadout string on the inspect tab, similar to the current 'talents' button?

**Comment by kodewdle** [comment]
i suggested making a smaller addon to do this and not requiring ElvUI to use it as it might be useful for other people than just ElvUI users.
