### ISSUE TITLE
[Retail Bug Report] <Tukui client is not seeing any folders>

### ISSUE THREAD

**Issue by Naxterra** [tukui-org/ElvUI#558]
### What is the issue you are having?

I reinstalled Tukui client due to I reformatted my OS, and now it only sees Desktop. It is not showing my disk drives, also I cannot close the selection screen. I have to force kill the app.

Version 3410

### What is the expected behavior?

Show all folders in the computer

### What actually happened?

![grafik](https://user-images.githubusercontent.com/41871948/201485969-b0f3cedf-5788-4af1-8c4e-58eeac837c06.png)

### Suggested Solution/Workaround

No workaround

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
we do not have a github repo for windows client reports, but if not mistaken it has something to do with onedrive service or something being enabled... that info is mentioned in our window client channel in our discord server.
