### ISSUE TITLE
[Retail Bug Report] LUA error when trying to use dropdown spells like summon pet v2

### ISSUE THREAD

**Issue by MaximilianKresse** [tukui-org/ElvUI#563]
### What is the issue you are having?

Spells with dropdown throwing LUA error and not opening and there is an error in LUA debug window.
Spells like "Summon pet", for example (warlock, hunter).
Tried to move the button to another panel and change dropdown directions - same issue.

### What is the expected behavior?

When I click on the "summon pet" dropdown menu with pets shown and I can click on any pet to summon.

### What actually happened?
```
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Nov 13 11:42:40 2022
Count: 3
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Sun Nov 13 11:42:40 2022
Count: 3
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by MaximilianKresse** [comment]
As the original issue #560 is locked - I created a new issue - sorry for that. 

But the issue does also occur for me since the prepatch for all my characters. When disabling elvui the issue doesn't occur. 

My version:
![image](https://user-images.githubusercontent.com/545671/201517801-30a5d319-6161-444e-9938-895888b28bce.png)

**Comment by VladTimo** [comment]
Regarding #560 and the answer I get there: 
**Original WoW UI, no error:**
![original_ui_no_error](https://user-images.githubusercontent.com/21192856/201534908-f0d5f8a1-acff-47ff-b4d4-061ff383ca2e.jpg)
**ElvUi with error:**
![elvui_lua_error](https://user-images.githubusercontent.com/21192856/201534917-8a28d21f-560a-4fb1-9e8e-57378bd1359a.jpg)

**Comment by CristianoBesi** [comment]
same error happens when, as a mage, I try to select a portal or, as a warlock, try to select a pet from their list:


Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

**Comment by Gonkers** [comment]
I'm not trying to pile on here, but I too have had the same issue for the past couple weeks. I have blown away all local settings/configs and the problem persists.

**Comment by jardragon901** [comment]
I'm also getting this error on my hunter and lock and so are several of my friends.

**Comment by Caedis** [comment]
Issue is on blizzard's end. They even admitted it.
![image](https://user-images.githubusercontent.com/18713839/201739276-ce67c3a2-72b2-44f5-b82e-d4f786dd23b8.png)

If you see a ticket has been closed/locked, that does not mean to open another one btw.
