### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Karl4291** [tukui-org/ElvUI#571]
### What is the issue you are having?

Any action bar item that features a "call-out" (i.e. a pull up menu) such as (but not limited to) Teleport, Portal, Summon Demon, Pet Utilities, etc. does not work (Clicking on it throws a LUA error, and the menu doesn't pull up).

### What is the expected behavior?

being able to select command from the drop down menu

### What actually happened?

No response, and a LUA error generated

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Tue Nov 15 16:07:25 2022
Count: 1
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/568
https://github.com/tukui-org/ElvUI/issues/550
https://github.com/tukui-org/ElvUI/issues/527
https://github.com/tukui-org/ElvUI/issues/506
https://github.com/tukui-org/ElvUI/issues/497
https://github.com/tukui-org/ElvUI/issues/495
https://github.com/tukui-org/ElvUI/issues/494
https://github.com/tukui-org/ElvUI/issues/481
https://github.com/tukui-org/ElvUI/issues/461
https://github.com/tukui-org/ElvUI/issues/451
https://github.com/tukui-org/ElvUI/issues/418
https://github.com/tukui-org/ElvUI/issues/431
