### ISSUE TITLE
[Retail Bug Report] <Evoker's Fire Breath not activating>

### ISSUE THREAD

**Issue by Draerukw** [tukui-org/ElvUI#574]
### What is the issue you are having?

When you have the ability keybinds to elvui action bar you will not be able to use fire breath

### What is the expected behavior?

for it to cast when you press the keybind butto

### What actually happened?

NOTHING

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Grolock** [comment]
I'm noticing the same issue, related to the Key Down option for ActionBars. With KeyDown disabled, empowered abilities do not work at all. With KeyDown enabled, they work but function as Blizzards Press and Tap option. I have not had any success getting Hold and Release to work for empowered spells with ElvUI enabled.

**Comment by Repooc** [comment]
> as Blizzards Press and Tap option

well u wont get any success with any addon with hold and release bc that is something up to blizzard to let addons do or not and atm it is not allowed

**Comment by GabrielGM** [comment]
You can create a macro that acts as a Press and Tap option:
```
#showtooltip
/cast Fire Breath
```

**Comment by Frutzi** [comment]
It seems, Blizzard has fixed it server-side right now.
Was creating new macros when i noticed, that i can also cast as intended from actionbar.
