### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Alcarva** [tukui-org/ElvUI#577]
### What is the issue you are having?

While having it keybind and pressing Fire breath for evoker class nothing happens

### What is the expected behavior?

Cast ability

### What actually happened?

Nothing

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Enable the Key Down option in elvui config (use search in the config and look for `Key Down`)
Try running the 2 commands:
`/console ActionButtonUseKeyDown 1`
`/console empowerTapControls 1`
Also note, no addons can use the Hold and Release option blizzard has and can only use the Tap and Press
