### ISSUE TITLE
[Feature Request]  Separate reagent bag slots from all-in-one bag

### ISSUE THREAD

**Issue by NANTOIANER** [tukui-org/ElvUI#578]
**Is your feature request related to a problem? Please describe.**

With the addition of reagent bags we will all carry one during DF. When currently equipping a reagent bag its slots get added to the all-in-one bag as normal slots, with no visual separation or visual differentiation between a **normal bag slot** and a **reagent bag slot**. 

The problem here being that not all items go in a reagent bag slot. 

Sure, after a while you get used to where your reagent bag slots are, but that's not necessarily a solution.

**Describe the solution you'd like**
In my opinion it would be a good addition to either 

- separate the reagent bag from the all-in-one bag entirely, by giving it its own adhered "box", anchored somewhere on the all-in-one-bag,

- add a visual barrier, indicating where the reagent bag slots begin, or

- offer an option to set a different backdrop color for reagent bag slots, to highlight reagent bag slots.

**Additional context**

https://user-images.githubusercontent.com/73881929/202210408-7b1257bb-9856-4889-8996-ac83574a454d.mp4

![Wow_d7eS6jeLHx](https://user-images.githubusercontent.com/73881929/202210438-cf344b8e-d8d1-41ac-9ac4-9d10b9a82ddb.png)

**Comment by jshier** [comment]
At the least, bag sorting needs to be updated to account for the reagent bag and sort only valid agents into it.

**Comment by drsleo** [comment]
I was thinking about it. it would be very good, even with the combined bags in the blizzard UI, the reagent is separated next to the combined bags. 
![bag test](https://user-images.githubusercontent.com/63939756/202341498-2d5082b4-3387-4ebd-a03f-65ebbfa42d33.jpg)

**Comment by Azilroka** [comment]
you can separate it a bit.. separate bag 5

**Comment by KevinPeplinski** [comment]
[drsleo](https://github.com/drsleo) has ElvUI bags disabled, but applied the ElvUI skin to the default ui - thats a ok solution for right now, but none of the ElvUI bag options apply here so thats more of a temporary solution

**Comment by Urhas** [comment]
Would it be possible to even add Bag 5 to the split bag options we already have available?
![Split Bag](https://user-images.githubusercontent.com/8009682/202528002-c75fc20f-1527-4394-9ee4-40e262e8011c.PNG)
