### ISSUE TITLE
[Feature Request] Color Party/Raid Frames based on buff

### ISSUE THREAD

**Issue by carlschoeneich** [tukui-org/ElvUI#58]
**Is your feature request related to a problem? Please describe.**
Mainly whenever I play Disc Priest I think about how much I'd like the option to color the raid frames of players with atonement in a specific color instead of heaving the buff indicator. 

**Describe the solution you'd like**
I'd love to have the option to color the party and raid frames in a specific color if the unit is affected by a specific buff. Maybe this could just be an option within the aura indicators.

**Describe alternatives you've considered**
I've considered this addon which basically does this: https://github.com/Vekkt/ElvUI_BuffHighlight
But it has a few flaws (f.e. you can't use it if you use class colored unit frames). And I think in general that this could be a feature a lot of people would like to have without installing an additional addon or switching to GRID2 or other raid frame addons.

**Additional context**
![image](https://user-images.githubusercontent.com/16469528/141037944-d1387b1a-5a50-4e30-8d72-71774ebdba43.png)

**Comment by Repooc** [comment]
if you go to Filters->Aura Highlight that is what this does already.  Note: Aura indicators were written to track something like this as by default, we color the frames when there is a debuff u can dispel (but u can setup the filter i have directed you to do what you are asking anyways)
