### ISSUE TITLE
[Retail Bug Report] 40 yard Alpha Fader On Evoker

### ISSUE THREAD

**Issue by Verdell263** [tukui-org/ElvUI#582]
### What is the issue you are having?

With Evokers having a 30 yard healing range, group frames are not fading at 30, but 40 yards. This leaves a 10 yard gap where frames show in range for the class but nothing will interact with mouseovers. 

### What is the expected behavior?

Frames should fade at 30 yards for Evokers.

### What actually happened?

I targeted a party member and got 31 yards away. The spell on the bars went red, but their party frame did not fade and I could not mouseover with the selected ability. Once I moved to 41 yards, the frame faded. 

### Suggested Solution/Workaround

Either make Evokers default 30 yard fader or add an option in the fader settings to set the fader range. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
use plater alpha version

**Comment by Najto** [comment]
hey, for me this error still exists with elvui 13.21 for my evoker frames fade at 40 yard. it there a way to change it maually ?

**Comment by matvi87** [comment]
13.23 still a problem, can we just have a slider to set it manualy. :)

**Comment by Azilroka** [comment]
A slider to adjust visibility would only allow certain ranges.. you guys think it's a slider to adjust anywhere between 0-60 yards at 1 yard increments and it's not.

**Comment by matvi87** [comment]
But now half the raid is out of range and still shows as in range. Anything I can do on my end to set it up properly than?

**Comment by Najto** [comment]
suprisingly i got it fixed by loading anothe profile and switching back to my own one, while on my evoker.  dont know why ^^

**Comment by matvi87** [comment]
tried the same and it kinda works supgrinsingly. but now my raid frame positions are different in & out of instance. :o in the instance they are fine and outside they line up 3 cm's more to the right :/
