### ISSUE TITLE
[Wrath Bug Report] Item comparison tooltip is sticky

### ISSUE THREAD

**Issue by hnfmr** [tukui-org/ElvUI#584]
### What is the issue you are having?

This has been plaguing me since Classic 60s and it still happens in WOTLK ElvUI. I've found a consistent way to reproduce 100%. Here is a video link to better illustrate it.
https://www.youtube.com/watch?v=DHgRsg6jCsI&ab_channel=hamster

Basically it looks like ElvUI remembers the last item my mouse cursor hovered (item that I don't have e.g. an item in AH listing), and when I move my mouse cursor to an empty bag slot, the bug will be triggered where the tooltip (comparison) will be sticky, which looks like a phantom comparison. Now if I keep moving my mouse cursor over NPCs/players, the comparison will be sticky.

This is a weird bug that's been plaguing me for a long time, hopefully someone here is able to find a fix, happy to provide more info if requested. (In the video, I used BenikUI edit, but this issue happens with nothing but just ElvUI enabled as well).

Thanks

### What is the expected behavior?

ElvUI should not pop up a comparison tooltip when mouse cursor is pointing an empty bag slot (after leaving the hovering of an item) and subsequently should not make the comparison tooltip be sticky around.

### What actually happened?

Comparison tooltip pops up over empty bag slot (be it default ElvUI bag or Bagnon), the item slot being compared is tied to the item that the mouse cursor last hovered. e.g. If I hovered over a wrist, and move my mouse to an empty bag slot, comparison tooltip against my currently equipped wrist will pop up. The comparison is a phantom one as it just shows my currently equipped slot, with nothing to compare against.

In addition, the comparison tooltip will stick around if I hover over NPC / player and etc... unless it's another item, this behaviour seems to reset.

### Errors

```shell
No LUA errors in this process.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
did not appear you read/did these steps...
1) `/edebug on`
2) see if the issue is still there
3) If you still have the issue/error, type in chat in game `/estatus` and show the window from estatus command and including the issue again as i have not seen or able to reproduce with just elvui itself

**Comment by hnfmr** [comment]
Sorry about this.

I still can 100% reproduce with /edebug on. The trick is that when you mouse over an item e.g. in AH (wrist), then mouse to your bag (without mouse over anything in between).

And here is a screenshot for /estatus 
![elvui](https://user-images.githubusercontent.com/1443015/202335340-e2d4fca7-3d27-447b-860b-97599d6ab8f3.jpg)
Thanks

**Comment by LuniaDev** [comment]
> did not appear you read/did these steps...
> 
>     1. `/edebug on`
> 
>     2. see if the issue is still there
> 
>     3. If you still have the issue/error, type in chat in game `/estatus` and show the window from estatus command and including the issue again as i have not seen or able to reproduce with just elvui itself

Eh? I literally show myself having all other AddOns disabled in my video and then pulled up /estatus on the screen.

Here's another where I explicitly type /edebug on instead: [https://www.youtube.com/watch?v=EhBxofDW8gY](url)
