### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Milky063** [tukui-org/ElvUI#585]
### What is the issue you are having?

Clicking on items in bags or action bars.

### What is the expected behavior?

Should be able to click on it and move it. 

### What actually happened?

Lua error

### Errors

```shell
8x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function <Interface/FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by imbillly** [comment]
I having the same problem when using elvui action bars seems to be fine but when using elv with default bars when i do edit mode/talent changing it will bug them out where i cant use keyboard to push them anymore but i can click them.

**Comment by imbillly** [comment]
17x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'TargetUnit()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `TargetUnit'
[string "@Interface/FrameXML/EditModeManager.lua"]:1512: in function `RefreshTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1456: in function `OnEditModeEnter'
[string "@Interface/FrameXML/EditModeManager.lua"]:170: in function `EnterEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:192: in function <Interface/FrameXML/EditModeManager.lua:190>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2853: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2657: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2561: in function <Interface/FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3159: in function <Interface/FrameXML/UIParent.lua:3138>
[string "=[C]"]: in function `ShowUIPanel'
[string "*GameMenuFrame.xml:94_OnClick"]:2: in function <[string "*GameMenuFrame.xml:94_OnClick"]:1>

**Comment by lfmnovaes** [comment]
I have the same issue as described by @Milky063 , tried to use `/edebug on` and had no success.
```
9x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
```

**Comment by Azilroka** [comment]
> I have the same issue as described by @Milky063 , tried to use `/edebug on` and had no success.
> 
> ```
> 9x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
> [string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `UseContainerItem'
> [string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
> [string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
> ```
> 
> Edit: Seems like using the Bag from ElvUI makes it work again because I wasn't using it before.

That specific error is from before 13.00

**Comment by NoNick96** [comment]
Same issue here. LUA error:
```
5x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
```
