### ISSUE TITLE
[Retail Bug Report] Opening Guild and Communities pane results in Skins.lua:470: doesnt exist!

### ISSUE THREAD

**Issue by zmoose** [tukui-org/ElvUI#587]
### What is the issue you are having?

When I open the Guild & Communities window I get this error.

### What is the expected behavior?

No LUA errors.

### What actually happened?

Get LUA errors but the guild chat window works.

### Errors

```shell
Message: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
Time: Wed Nov 16 23:49:20 2022
Count: 1
Stack: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua"]:541: in function <.../AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua:144>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1844: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1785: in function `?'
[string "@Interface/AddOns/Decursive/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...ive/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Decursive/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...ive/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Decursive/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:823: in function `Communities_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1124: in function `ToggleCommunitiesFrame'
[string "@Interface/FrameXML/UIParent.lua"]:979: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by LanceB71** [comment]
Can confirm this occurred for me tonight by clicking the guild icon on the mini map:

Message: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
Time: Wed Nov 16 22:21:34 2022
Count: 1
Stack: Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:470: in function <Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:469>
[string "=[C]"]: in function `HandleButton'
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua"]:541: in function <.../AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua:144>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1844: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1785: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:117: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:117>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:27: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:23>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:62: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:823: in function `Communities_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1124: in function `ToggleCommunitiesFrame'
[string "@Interface/FrameXML/UIParent.lua"]:979: in function <Interface/FrameXML/UIParent.lua:958>
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/Guild.lua"]:221: in function `onClick'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:359: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:357>

Locals: <none>

**Comment by Imna1975** [comment]
I can also confirm this 

8x Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:470: in function <Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:469>
[string "=[C]"]: in function `HandleButton'
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua"]:541: in function <.../AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua:144>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1844: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1785: in function `?'
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/!KalielsTracker/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
...
[string "=[C]"]: in function `Click'
[string "@Interface/FrameXML/ChatFrame.lua"]:1617: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5204: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:3132: in function <Interface/FrameXML/ChatFrame.lua:3125>
[string "=[C]"]: in function `RunMacroText'
[string "@Interface/FrameXML/SecureTemplates.lua"]:468: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function <Interface/FrameXML/SecureTemplates.lua:730>

**Comment by Zetaprime82** [comment]
Same issue:
`2x Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:470: doesnt exist!
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:470: in function `HandleButton'
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua"]:541: in function <.../AddOns/ElvUI/Mainline/Modules/Skins/Communities.lua:144>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1844: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1785: in function `?'
[string "@Interface/AddOns/BlizzMove/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...ove/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/BlizzMove/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ove/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/BlizzMove/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/BlizzMove/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AddOns/BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:823: in function `Communities_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:1124: in function `ToggleCommunitiesFrame'
[string "@Interface/FrameXML/UIParent.lua"]:979: in function `ToggleGuildFrame'
[string "@Interface/AddOns/TitanClan/TitanClan.lua"]:169: in function `TitanPanelClanButton_OnClick'
[string "*TitanClan.xml:18_OnClick"]:1: in function <[string "*TitanClan.xml:18_OnClick"]:1>`

**Comment by nikkisaurus** [comment]
The issue is that `CommunitiesFrame.NotificationSettingsDialog.OkayButton` and `CommunitiesFrame.NotificationSettingsDialog.CancelButton` have been renamed.

In \Mainline\Modules\Skins\Communities.lua, lines 541 and 541 should be changed to:
541: `	S:HandleButton(CommunitiesFrame.NotificationSettingsDialog.Selector.OkayButton)`
542: `	S:HandleButton(CommunitiesFrame.NotificationSettingsDialog.Selector.CancelButton)`

Although this solves the error, there are still issues with the notification dialog. `CommunitiesFrame.NotificationSettingsDialog.Selector` needs to be stripped and skinned. Additionally, the dropdown box in the top right of the dialog has text overflowing out of the dropdown.

Here is an image demonstrating the extra issues (this is after I changed the button names):
https://github.com/nikkisaurus/images/blob/master/WoWScrnShot_111722_183659.jpg

**Comment by zmoose** [comment]
I updated to ElvUI 13.03 and this error seems to have been fixed.
