### ISSUE TITLE
[Retail Bug Report] evoker empower spell cant use

### ISSUE THREAD

**Issue by totti444** [tukui-org/ElvUI#588]
### What is the issue you are having?

Cant start empowered spell casting with elvui

### What is the expected behavior?

.

### What actually happened?

Try to update and is not working

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Reddaxi** [comment]
I'm also experiencing this.

Updated my ElvUI to 13.02 through WowUp, logged on to wow and created an Evoker.

**Comment by kelsier99** [comment]
Try this
/ console ActionButtonUseKeyDown 1 then
/console empowerTapControls 1
Reload ui after running those

**Comment by vamperor1** [comment]
Confirming.
ElvUI 13.02.
Works from the spellbook, but does not work from the panel.

**Comment by Ingolanto** [comment]
Solved this for my character by checking first box "On Button's Press" (not sure how it exactly sounds in English) at skill's panels settings. 
So empower spells doesn't work if skills happening when button unholds.

**Comment by Zefya** [comment]
updated my elvui, still not working. the box "On Button's Press" does not allow to hold the key to charge the spell as we do on Blizzard UI

**Comment by xapotah** [comment]
Temp solution based on previous comment (v 13.02, US English Version):
/elvui
ActionBars: General
In "General" subsection, check/enable "Key Down". 
Empowered Evoker spells (Fire Breath, Eternity Surge, etc.) will then require two button pushes: once to start cast, once again to end when desired Empower Level is reached. 

Assumption here: preference would be for press-and-hold functionality for empowerment, mirroring default Blizzard action.
(thanks!)
