### ISSUE TITLE
Hunter call pet LUA error

### ISSUE THREAD

**Issue by CustomGraphix1** [tukui-org/ElvUI#589]
### What is the issue you are having?

When pressing the call pet button on an action bar i end up with a LUA error, verified by removing all other addons entirely, only happens with elvui

### What is the expected behavior?

happends every time

### What actually happened?

clicked the button received lua error

### Suggested Solution/Workaround

only workaround so far is to make a bar with all my pets to summon them

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Thu Nov 17 12:54:09 2022
Count: 2
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Toasticon** [comment]
This is a blizz bug and effects all action bar replacement addons (or none at all).
https://cdn.discordapp.com/attachments/222356141785612288/1040613855501492405/image.png

**Comment by Yuma-rust** [comment]
Same bug for summoning warlock pets and for choosing portals and teleport on mage. basically every spell using a drop-down wont work.

**Comment by Arcanemagus** [comment]
Here's the actual forum post from the screenshot posted above: https://us.forums.blizzard.com/en/wow/en/wow/t/lua-error-stopping-me-from-using-summon-demon/1383629/13
