### ISSUE TITLE
[Retail Bug Report] <No interrupt annouce on French client>

### ISSUE THREAD

**Issue by Drey242** [tukui-org/ElvUI#59]
### What is the issue you are having?

Interrupt annouce is not showing up on French client for mounth.
An issue was opened (https://git.tukui.org/elvui/elvui/-/issues/2393) but it seems deleted.

### What is the expected behavior?

Interrupt annouce showing up on chat

### What actually happened?

No error, interrupt message is not showing up when you interrupt something

### Suggested Solution/Workaround

Line 175 on Interface\AddOns\ElvUI\Core\Locales\frFR file :

L["Interrupted %s's \124cff71d5ff\124Hspell:%d:0\124h[%s]\124h\124r!"] = "\124cff71d5ff\124Hincantation:%d:0\124h[%s]\124h\124r Interrompu %s !"

Should be something like that : L["Interrupted %s's \124cff71d5ff\124Hspell:%d:0\124h[%s]\124h\124r!"] = "Interrompu %s \124cff71d5ff\124Hspell:%d:0\124h[%s]\124h\124r !"

### Errors

```shell
No error
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by kodewdle** [comment]
Thanks fixed by b524ac59a4964b572d2ed3176dd9fb1a759993a9

**Comment by Drey242** [comment]
Thanks !
