### ISSUE TITLE
[Retail Bug Report] Sort reagent bank does nothing

### ISSUE THREAD

**Issue by Mr-nUUb** [tukui-org/ElvUI#596]
### What is the issue you are having?

Clicking the "Sort Bags" button in reagent bank does nothing. I don't even get an error.

Screenshot of ElvUI Status
![grafik](https://user-images.githubusercontent.com/36689675/202711987-328e39e8-c462-4c5d-85d1-13e2d87c96e7.png)

### What is the expected behavior?

"Sort Bags" button in reagent bank sorts reagents like in previous addons (SL, BfA, etc.)

### What actually happened?

nothing

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by dburnt** [comment]
I get an error (this is with no other addons running)
2x Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua:1793: attempt to call upvalue 'SortReagentBankBags' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua"]:1793: in function <Interface/AddOns/ElvUI/Core/Modules/Bags/Bags.lua:1783>

Locals:
(*temporary) = nil
(*temporary) = "attempt to call upvalue 'SortReagentBankBags' (a nil value)"
f = ElvUI_BankContainerFrame {
 0 = <userdata>
 fullBank = true
 isBank = true
 Bags = <table> {
 }
 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 bottomOffset = 8
 purchaseBagButton = Button {
 }
 template = "Transparent"
 totalSlots = 216
 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294
 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 ContainerHolderByBagID = <table> {
 }
 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 depositButton = ElvUI_BankContainerFrameDepositButton {
 }
 notPurchased = <table> {
 }
 BagIDs = <table> {
 }
 reagentFrame = ElvUIReagentBankFrame {
 }
 reagentToggle = ElvUI_BankContainerFrameReagentButton {
 }
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 bankText = FontString {
 }
 backdropInfo = <table> {
 }
 bagsButton = ElvUI_BankContainerFrameBagsButton {
 }
 PixelSnapDisabled = true
 BottomEdge = Texture {
 }
 DelayedContainers = <table> {
 }
 stackButton = ElvUI_BankContainerFrameStackButton {
 }
 holderFrame = Frame {
 }
 ContainerHolder = ElvUI_BankContainerFrameContainerHolder {
 }
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 TopRightCorner = Texture {
 }
 helpButton = ElvUI_BankContainerFrameHelpButton {
 }
 closeButton = ElvUI_BankContainerFrameCloseButton {
 }
 Center = Texture {
 }
 staleBags = <table> {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 BottomRightCorner = Texture {
 }
 sortButton = ElvUI_BankContainerFrameSortButton {
 }
 TopEdge = Texture {
 }
 mover = ElvUIBankMover {
 }
 NewItemGlow = <table> {
 }
 editBox = ElvUI_BankContainerFrameEditBox {
 }
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422
 events = <table> {
 }
 BottomLeftCorner = Texture {
 }
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399
 LeftEdge = Texture {
 }
 topOffset = 50
}
E = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:379
 mylevel = 60
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 FormatMoney = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:436
 StaticPopup_EscapePressed = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:432
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1403
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:455
 ScheduleTimer = <function> defined @Interface/AddOns/DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 PriestColors = <table> {
 }
 RegisterModule = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1813
 Cooldown_Options = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:129
 OnPauseCooldown = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:237
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface/AddOns/DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 Layout = <table> {
 }
 UnregisterEventForObject = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1718
 Distributor = <table> {
 }
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1234
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 UnregisterAl

**Comment by Mr-nUUb** [comment]
@dburnt Please put stuff like this in a code block either by using the format buttons on top of the input field or by typing 3 backticks (don't forget to close it using 3 backticks again):
` ``` YOUR CODE ``` `

**Comment by Mr-nUUb** [comment]
Seems 13.04 solves this issue. It works for me, so this issue can be closed now.
