### ISSUE TITLE
[Retail Bug Report] 简体中文环境下，“框架宽度” 翻译为"聊天框宽度"；

### ISSUE THREAD

**Issue by l549349545** [tukui-org/ElvUI#597]
### What is the issue you are having?

ElvUI设置 - 背包 - 背包 ，“框架宽度” 翻译为"聊天框宽度",应使用"背包面板宽度"文本；

![QQ图片20221118212738](https://user-images.githubusercontent.com/13399855/202717079-2458667f-41cf-4d2e-b033-e52e878f9950.png)

### What is the expected behavior?

修正背包宽度描述造成的多语言显示错误:
ElvUI - Bags - Bags , “Panel Width” --> "Panel Width (Bags)"
ElvUI设置 - 背包 - 背包 ，"聊天框宽度" --> "背包面板宽度"

或移除多语言文件中的匹配： “Panel Width” ："聊天框宽度"

### What actually happened?

ElvUI设置 - 背包 - 背包 ，“框架宽度” 翻译为"聊天框宽度",应使用"背包面板宽度"文本；

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
is this also acceptable? (frame panel width) f2cdaa06b30
