### ISSUE TITLE
[Retail Bug Report] vending results in nil nil

### ISSUE THREAD

**Issue by dburnt** [tukui-org/ElvUI#598]
### What is the issue you are having?

My chat log fills with lines of "nil nil" whenever I vend anything.  It appears as if it is trying to vend grey items (of which I have none) but that's a guess.

### What is the expected behavior?

No additional chat lines other than the vended item.

### What actually happened?

multiple lines of "nil nil"

### Errors

```shell
none thrown.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by DJScias** [comment]
Hello there,

Is it possible you're using Pawn in any shape or form?

One of its fixes an hour ago in https://github.com/VgerMods/Pawn/commit/54048497093b0be19606fd4db41eb07e4f527cd4 was related to just "nil nil" getting spammed during bags (like selling, opening, etc..), but if you had it disabled for this bug report then of course it's unrelated.

**Comment by dburnt** [comment]
Thank you!  I'd updated Pawn earlier, and while I'd tested the reagent bank sort without any other addons, when I switched characters, Pawn was active.  I've updated Pawn and the error no longer occurred!
