### ISSUE TITLE
[TBC Bug Report] Chat clock shows wrong on the hour

### ISSUE THREAD

**Issue by Mysame** [tukui-org/ElvUI#60]
### What is the issue you are having?

When clock goes to new hour (ex `1:59` -> `2:00`) it will always show `1:00` instead of `2:00`.
This is true for every hour.
![2021-11-10_01-00-11](https://user-images.githubusercontent.com/1966231/141095042-014bc387-0df7-43ba-b857-3e28131c9da8.png)

### What is the expected behavior?

`1:59` should then become `2:00`

### What actually happened?

`1:59` became `1:00`

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by 1Botanica1** [comment]
How is it with no addons, blizzard UI? 

Interface > Social > Chat timestamps

Please test and upload a screenshot

**Comment by 1Botanica1** [comment]
@Mysame are you still having the issue - have you had a chance to test?

**Comment by Mysame** [comment]
The local timestamps work fine.
![2021-11-20_09-00-08](https://user-images.githubusercontent.com/1966231/142719155-7bce9c63-bd42-4919-8c29-221d8fda47ec.png)
