### ISSUE TITLE
[Retail Bug Report] Shadow and Light Currency Data Text Not Working

### ISSUE THREAD

**Issue by dewson8** [tukui-org/ElvUI#600]
### What is the issue you are having?

When hovering over my currency data text on my data bar nothing shows and I am getting an error in my bug sack. I have the most up to date and recent versions of Elvui and Shadow and Light.

### What is the expected behavior?

Currency tooltip to show correctly when hovering over the data text.

### What actually happened?

When hovering over my currency data text on my data bar nothing shows and I am getting an error in my bug sack.

### Errors

```shell
1x ...face/AddOns/ElvUI_SLE/modules/datatexts/currency.lua:210: attempt to perform arithmetic on local 'count' (a nil value)
[string "@Interface/AddOns/ElvUI_SLE/modules/datatexts/currency.lua"]:210: in function <...face/AddOns/ElvUI_SLE/modules/datatexts/currency.lua:198>
[string "@Interface/AddOns/ElvUI_SLE/modules/datatexts/currency.lua"]:314: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:94: in function <...ce/AddOns/ElvUI/Core/Modules/DataTexts/DataTexts.lua:84>

Locals:
total = 0
(for index) = 0
(for limit) = 4
(for step) = 1
i = 0
bagName = "Backpack"
(for index) = 1
(for limit) = 20
(for step) = 1
slotID = 1
link = "|cffa335ee|Hitem:188000::::::::60:1467:::::::::|h[Grovetender's Pack]|h|r"
count = nil
_ = "Deposit Anima"
spellID = 336456
(*temporary) = 250
(*temporary) = 336456
(*temporary) = "attempt to perform arithmetic on local 'count' (a nil value)"
C_Container_GetContainerNumSlots = <function> defined =[C]:-1
C_Container_GetContainerItemLink = <function> defined =[C]:-1
C_Container_GetContainerItemInfo = <function> defined =[C]:-1
C_Item_IsAnimaItemByID = <function> defined =[C]:-1
GetItemSpell = <function> defined =[C]:-1
animaSpellID = <table> {
 345706 = 5
 347555 = 3
 336327 = 35
 336456 = 250
}
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Fixed in the dev build
