### ISSUE TITLE
[Retail Bug Report] LUA error with group finder UI

### ISSUE THREAD

**Issue by AckItsMe** [tukui-org/ElvUI#601]
### What is the issue you are having?

On a fresh UI reload, if I open the Dungeons & Raids panel, then select Premade Groups, select a category, then click Find a Group, the first time I mouse over any group, I receive this LUA error:

Message: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
Time: Fri Nov 18 23:55:44 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/FrameXML/LFGList.lua"]:3521: in function <Interface/FrameXML/LFGList.lua:3510>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2596: in function <Interface/FrameXML/LFGList.lua:2593>
[string "=[C]"]: ?

Locals: <none>

If I clear the error, it does not return unless I reload the UI.   This does seem to be a conflict with Decursive as the problem does not appear to occur when Decursive has been disabled.

### What is the expected behavior?

Not having the UI error...   It's not obvious that this is causing any other issues.

### What actually happened?

See above.

### Suggested Solution/Workaround

Disable the Decursive addon.

### Errors

```shell
Message: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
Time: Fri Nov 18 23:55:44 2022
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@Interface/FrameXML/LFGList.lua"]:3521: in function <Interface/FrameXML/LFGList.lua:3510>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@Interface/FrameXML/LFGList.lua"]:2596: in function <Interface/FrameXML/LFGList.lua:2593>
[string "=[C]"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
Could have to do with https://github.com/tukui-org/ElvUI/issues/261 

Devs will sure look into this.

**Comment by syntrixsystems** [comment]
Just got this same error today opening lfg.

1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML/LFGList.lua"]:3522: in function <FrameXML/LFGList.lua:3511>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2597: in function <FrameXML/LFGList.lua:2594>
[string "=[C]"]: ?

**Comment by RAtwood90** [comment]
It's an known Issue Simpy said no Fix for it at the Moment.

**Comment by 0xbs** [comment]
Known issue since more than a year, I assume it will never get fixed: https://github.com/Stanzilla/WoWUIBugs/issues/195

Me and some other addon authors dealt with the problem by overwriting the function. One has to be careful not to overwrite it for players which do not have a fully secured account. See https://github.com/0xbs/premade-groups-filter/blob/master/FixGetPlaystyleString.lua

**Comment by kodewdle** [comment]
@0xbs thanks, i actually just unskinned the button (https://github.com/tukui-org/ElvUI/commit/da636eed24ea2c9d2873dc3c8ef9324489944d99) and it seems to make the issue go away; at least in one test situation.

*also, we couldn't use any of the code from that URL because it's GPL licensed (not Lesser General Public License (LGPL))*
