### ISSUE TITLE
[Retail Bug Report] RaidDebuffs filter has something that shouldn't be there.

### ISSUE THREAD

**Issue by Mofunkles** [tukui-org/ElvUI#604]
### What is the issue you are having?

The Elemental Shaman debuff Elemental Equilibrium (378277) is showing as part of the RaidDebuffs filter.

### What is the expected behavior?

If a Shaman procs their elemental equilibrium debuff, nobody other than the shaman in question should really have any interest in knowing about it.

### What actually happened?

My unit frames display their debuff.

### Suggested Solution/Workaround

I singled it out to the RaidDebuff filter being what is showing the debuff.  The only solution would be to remove the debuff from this filter.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
RaidDebuff filters do have the shaman spell - Elemental equilibrium under Dathea, Aschnded.

**Comment by Repooc** [comment]
might have been a typo from lucky as i dont see that why that was added personally

**Comment by kodewdle** [comment]
fixed this :)
