### ISSUE TITLE
[Retail Bug Report] Rouge poisons don't open within the action bar

### ISSUE THREAD

**Issue by bartoszhaza** [tukui-org/ElvUI#606]
### What is the issue you are having?

When you add rouge poisons to the action bar you are unable to open the selection, as if the button doesn't work within the action bar, I am only able to apply poisons within the spellbook.

### What is the expected behavior?

When clicking on the poisons icon within the action bar a dropdown should appear of all possible poisons to choose.

### What actually happened?

When clicking on the poisons within the action bar there was no action, before on previous versions, this would throw a lua error.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
you didnt read instructions so closing, and this has been reported and closed already as the flyout button issue is from blizzard (there is a picture of a blue post in one of the tickets you didnt look at about the issue)
![image](https://user-images.githubusercontent.com/1479745/202914612-7f625e25-ab13-47f1-9bc5-a9865677c7d3.png)

**Comment by bartoszhaza** [comment]
@Repooc, thanks for fixing this issue despite the wrong ticket completion ;)
