### ISSUE TITLE
[Retail Bug Report] ElvUI Loot frame issue or Bug

### ISSUE THREAD

**Issue by Daqidragon** [tukui-org/ElvUI#607]
### What is the issue you are having?

Loot Frames/Windows of Items looted/won and the Roll Window Frames.
Everytime you loot a boss in any raid, old or new, The loot windows for the looted items/won items, keeps jumping back and forth between the standard Blizzard UI Loot frame (bottom middle) and the ElvUI Position you set. 
Not sure if it's only me with this issue, but nothing i've tried have helped the problem!
Wasen't there before PrePatch dragonflight, so must be some issue from after Prepatch or something?

### What is the expected behavior?

Not bug out or jump around between Elvui and Blizzard UI position.

### What actually happened?

Everytime you loot a boss in any raid, old or new, The loot windows for the looted items/won items, keeps jumping back and forth between the standard Blizzard UI Loot frame (bottom middle) and the ElvUI Position you set. 
Not sure if it's only me with this issue, but nothing i've tried have helped the problem!
Wasen't there before PrePatch dragonflight, so must be some issue from after Prepatch or something?

### Suggested Solution/Workaround

not sure? not a programmer lol

### Errors

```shell
!
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by UnaffiliatedGamer** [comment]
Same issue here, been bugging me for a while and was hoping there was a report about it. I had to move my elvui loot frames to somewhere similar to the blizz UI default. This only seems to affect the roll frames (the one where you click to roll need or greed, not the roll-results frame which is free moving)
