### ISSUE TITLE
3d portrait not inheriting fader [Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Jerome-Longhurst** [tukui-org/ElvUI#608]
### What is the issue you are having?

3d portrait for the player does not inherit the fader. As soon as I change it to a 2d portrait it behaves correctly and fades.

### What is the expected behavior?

3d portrait will fade along with the rest of the player bars/info
![image](https://user-images.githubusercontent.com/22183168/202900253-7951b672-c080-4305-a263-ff744402c2f7.png)
![Capture](https://user-images.githubusercontent.com/22183168/202900258-abdbe98b-f7e9-4b0e-9a64-5149f60f4129.PNG)

### What actually happened?

3d portrait for the player does not inherit the fader. As soon as I change it to a 2d portrait it behaves correctly and fades.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by tomasrad** [comment]
I second this. Attaching same problem sc. 
![wow](https://user-images.githubusercontent.com/119094411/204073141-f58121f0-75c1-4094-9212-db864f9271aa.JPG)

**Comment by fdreamsu** [comment]
Same here
![a](https://user-images.githubusercontent.com/9639344/204086237-2e9400ca-fcdf-49fa-a73b-2ed2f9a5d196.png)

**Comment by Azilroka** [comment]
This is a blizzard issue.
