### ISSUE TITLE
[Feature Request] Seperate Reagent Bag

### ISSUE THREAD

**Issue by Bowbee** [tukui-org/ElvUI#609]
**Is your feature request related to a problem? Please describe.**
Can we please have a separate bag frame for the new reagent bag?
It would be nice to keep this separate from the combined bag.

**Describe the solution you'd like**
![bags](https://i.imgur.com/ZyWiXnD.png)

**Describe alternatives you've considered**
I have attempted my own mock-up copying the ReagentFrame within Bags.lua - but no luck. Couldnt get anything to display.
The default UI has this behaviour by default as seen in screenshot however I would love all the benefits of having ElvUI control the bags (ilvl overlays, custom padding, elvui sorting etc).

Attempted to modify the module load to allow for Blizz bags to show in addition to ElvUI to hack `ToggleBag_Individual(5)` into `B:OnShow()`.

**Comment by tryallthethings** [comment]
I wanted a visual separation as well. Would this work for you? Did the following just via ElvUI settings:
![image](https://user-images.githubusercontent.com/11146296/203137130-6c374ff0-5a76-4905-9905-3a9de2c119e9.png)

**Comment by Bowbee** [comment]
Yes but I dont want the bag to be at the bottom as my important items are there, reversing bag order just screws with things.
