### ISSUE TITLE
Dungeons healing Floating combat text

### ISSUE THREAD

**Issue by 73mates** [tukui-org/ElvUI#610]
### What is the issue you are having?

Hi, I'm using plugin Elvui floating combat text and when I'm in dungeon, it isn't showing floating combat text for healing my allies. But damage it is showing with no problem.
I have tried this command (/console floatingCombatTextCombatHealing 1) and still nothing.

Do you know what could be the problem?

Thanks!

### What is the expected behavior?

To show floating healing combat text in a dungeon

### What actually happened?

It doesn't working.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
ElvUI does not have anything to do with combat text showing or hiding the text.  You will need to make a ticket on the plugin's github as we do not do support for plugins here on the elvui ticket system.  Use the ticket system for the plugin.
