### ISSUE TITLE
[Retail Bug Report] Debuffs only show if disable and re-enable them on enemy nameplates

### ISSUE THREAD

**Issue by SparkiGB** [tukui-org/ElvUI#611]
### What is the issue you are having?

Casting any debut onto character the debut does not show. Yet is enabled. IF disable it and re-enable it int shows but only for a little while then I have to turn it off and on again. So keeping track of debuffs at moment is impossible. Only started since Dragonflight pre-patch.

### What is the expected behavior?

Tagging a mob with a debuff should show on the nameplates. IT doesn't unless disabled then reenabled 

### What actually happened?

Casting any debut onto character the debut does not show. Yet is enabled. IF disable it and re-enable it int shows but only for a little while then I have to turn it off and on again. So keeping track of debuffs at moment is impossible. Only started since Dragonflight pre-patch.

### Errors

```shell
No errors show. Disabled ALL addons and still doesn't work as it should. Trie don other characters but same issue. Fine in default wow UI.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This could be your filters. 
See filter priority here https://github.com/tukui-org/ElvUI/wiki/filters

AFter going through the filter priority, if you still have the issue - 

Type in chat in game
`/edebug on` 

Do you still have the issue. If so, type in chat in game
`/estatus` and upload a FULL UI screenshot (no cropping) showing both the issue and the status panel. 

Include another screenshot of the relevant nameplate debuff settings.

**Comment by kodewdle** [comment]
closing, no response. reopen if needed. :)
