### ISSUE TITLE
[Retail Bug Report] <Evoker Aura Filter Bugged, Unable to Modify>

### ISSUE THREAD

**Issue by StoneFaceLock** [tukui-org/ElvUI#614]
### What is the issue you are having?

Unable to modify Echo or Time Dilation in "Aura Indicator (Class)" filter.  Cannot change size, location or style. Cannot disable either.  

### What is the expected behavior?

Should be able to modify settings for spell

### What actually happened?

When clicking any button or element to change (Size Offset, Anchor Point, Style), nothing occurs. Unable to change any setting for Echo or Time Dilation, other spells are fine.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Myrl1997** [comment]
Was This fixed i have rthe same issue on my Paladin for Beacon of Light and Beacon of Faith?
