### ISSUE TITLE
[Retail Bug Report] Rogue Poisons Menu

### ISSUE THREAD

**Issue by Maglanus** [tukui-org/ElvUI#616]
### What is the issue you are having?

Poisons menu for rogue putted into any ActionBar give back an error.
It doesnt give an error when used from spellbook.

### What is the expected behavior?

Poisons menu working properly - you can choose what poison apply to your wepons while positioned in action bar.

### What actually happened?

Error

### Errors

```shell
Message: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
Time: Mon Nov 21 11:29:39 2022
Count: 3
Stack: Interface/FrameXML/SpellFlyout.lua:240: attempt to call method 'GetSpellFlyoutDirection' (a nil value)
[string "@Interface/FrameXML/SecureHandlers.lua"]:36: in function <Interface/FrameXML/SecureHandlers.lua:34>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:40: in function <Interface/FrameXML/SecureHandlers.lua:39>
[string "@Interface/FrameXML/SecureHandlers.lua"]:268: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by GhostReapersWorld** [comment]
Just a little input from me, should be the same issue as here:
https://github.com/tukui-org/ElvUI/issues/589

Here is the corresponding blue post to this topic:
https://us.forums.blizzard.com/en/wow/t/lua-error-stopping-me-from-using-summon-demon/1383629/13
