### ISSUE TITLE
[Retail Bug Report] <Unit Frame Class Bar>

### ISSUE THREAD

**Issue by Vvolf1234** [tukui-org/ElvUI#622]
### What is the issue you are having?

When the class bar is enabled it appears on top of everything, even if you open a menu it stays super impossed on top of the menu.
![Screenshot_27](https://user-images.githubusercontent.com/118930725/203626817-7a1f089e-0634-4bb7-9855-350b0af245ef.png)
![Screenshot_28](https://user-images.githubusercontent.com/118930725/203626819-61130af8-59a1-4ff2-997e-e20eb4026406.png)

### What is the expected behavior?

The class bar should not be on top of menus.

### What actually happened?

The class bar is on top off any menu you open

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Toasticon** [comment]
![strata](https://user-images.githubusercontent.com/33032465/203859811-64177bf2-2d5c-45f4-9730-5a280acd547f.png)
You are the bug.

**Comment by Vvolf1234** [comment]
thanks
