### ISSUE TITLE
[Retail Bug Report] Icon quality color in bank not updating

### ISSUE THREAD

**Issue by tryallthethings** [tukui-org/ElvUI#623]
### What is the issue you are having?

The icon quality color in my bank bags is sometimes only updated / shown after moving affected items around. I never noticed it in my regular bags, only in the bank. I haven't found any way to reproduce this issue so far. It happens on different characters and throughout ElvUI versions. Seen this issue for several months already.
Here's a short video showcasing the issue: https://youtu.be/-0Ni4UrEjd4

I checked step 5 and 6 as done, even though I didn't as I can't reproduce the issue on demand. This time I took the video, next time I'll try with `/edebug on` .

### What is the expected behavior?

Bank icon quality color should be shown as soon as I open my bank.

### What actually happened?

Well, they don't 😄 

### Suggested Solution/Workaround

Moving icons around seems to work for some groups (moving an item in certain bags like my engineering bag, all epic quality items). Reloading sometimes works too.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game
`/edebug on` 

Do you still have the issue. If so, type in chat in game
`/estatus` and upload a FULL UI screenshot (no cropping) showing both the issue and the status panel.

**Comment by Azilroka** [comment]
It's because of the item cache issue. It's from scanning the auction house.
