### ISSUE TITLE
[Retail Bug Report] Can't use items in bags with ElvUI bags disabled

### ISSUE THREAD

**Issue by NoNick96** [tukui-org/ElvUI#624]
### What is the issue you are having?

When disabling ElvUI Bag modules, after a while i cannot use items inside the bags. Only items that have a use effect do not work. Moving items around and equipping works fine. /reload fixes it for a while. This doesn't happen at all with ElvUI bags enabled.
ElvUI version: 13.06

### What is the expected behavior?

Being able to use items inside the bags 

### What actually happened?

Not able to use items inside the bag

### Errors

```
5x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Frippez73** [comment]
> ### What is the issue you are having?
> When disabling ElvUI Bag modules, after a while i cannot use items inside the bags. Only items that have a use effect do not work. Moving items around and equipping works fine. /reload fixes it for a while. This doesn't happen at all with ElvUI bags enabled. ElvUI version: 13.06
> 
> ### What is the expected behavior?
> Being able to use items inside the bags
> 
> ### What actually happened?
> Not able to use items inside the bag
> 
> ### Suggested Solution/Workaround
> _No response_
> 
> ### Errors
> ```
> 5x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
> [string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
> [string "=[C]"]: ?
> [string "=[C]"]: in function `UseContainerItem'
> [string "@FrameXML/ContainerFrame.lua"]:1409: in function <FrameXML/ContainerFrame.lua:1318>
> [string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
> [string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
> ```
> 
> ### ElvUI Changelog & Troubleshooting
> * [x]  I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
> * [x]  I have verfied ElvUI is up to date by checking /estatus.
> * [x]  I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
> * [ ]  I have not read step six and I am just clicking all boxes.
> * [x]  I have verfied my issue doesn't exist in the default UI.
> * [x]  I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

I'm having the same problem, been reporting this since ElvUI version 12.97 in ticket #514 and #520. Both closed but error continues unfortunately. Happens every time I port somewhere, in to a dungeon for example or taking a portal like the Stormwind portal from Oribos. Doing /reloadui solves in until next time.
Need investigating please!

18x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>

/Frippez

**Comment by Frippez73** [comment]
> I'm having the same problem, been reporting this since ElvUI version 12.97 in ticket #514 and #520. Both closed but error continues unfortunately. Happens every time I port somewhere, in to a dungeon for example or taking a portal like the Stormwind portal from Oribos. Doing /reloadui solves in until next time. Need investigating please!
> 
> 18x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'. [string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480> [string "=[C]"]: ? [string "=[C]"]: in function `UseContainerItem' [string "@FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick' [string "@FrameXML/ContainerFrame.lua"]:1461: in function <FrameXML/ContainerFrame.lua:1448>
> 
> /Frippez

And still on version 13.08 /Frippez

**Comment by Azilroka** [comment]
function `UseContainerItem` is no longer in the game for Retail UI.

**Comment by Frippez73** [comment]
> function `UseContainerItem` is no longer in the game for Retail UI.

@Azilroka I trust you about it but the issue still persists I'm afraid. I have version 13.10 now.

**Comment by geggiot** [comment]
same issue

**Comment by imoonkin** [comment]
now with version 13.11,  the bug is set to default, which means you don't have to teleport to trigger the bug, you cannot use item by default...

**Comment by Frippez73** [comment]
> now with version 13.11, the bug is set to default, which means you don't have to teleport to trigger the bug, you cannot use item by default...

@imoonkin Is it still possible to use /reloadui as a workaround? Am still on version 13.10, nice to know if I should stay on that version.

**Comment by kodewdle** [comment]
refixed by https://github.com/tukui-org/ElvUI/commit/00f39340e721f3c11fc972fe18c358ee1a0215b6

**Comment by ejrgithub** [comment]
Can't use items in bag after updating to 13.11

get following error

**Comment by Repooc** [comment]
> Can't use items in bag after updating to 13.11 No other mods - Elvui Bags disabled. get following error
> 
> Message: [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'. Time: Fri Dec 16 16:55:04 2022 Count: 1 Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UNKNOWN()'. [string "=[C]"]: in function `UseContainerItem' [string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function <Interface/FrameXML/ContainerFrame.lua:1318> [string "=[C]"]: in function `ContainerFrameItemButton_OnClick' [string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>
> 
> Locals:

ElvUI is on 13.12, try updating and try again

**Comment by Frippez73** [comment]
Worked just fine after updating to version 13.13.
Today I updated to version 13.14 and the issue was back again.
Can't use bag items after porting for example.

**Comment by Frippez73** [comment]
> @Repooc Worked just fine after updating to version 13.13. Today I updated to version 13.14 and the issue was back again. Can't use bag items after porting for example.

Seems to be working now, haven't had the issue for a while. Am still on version 13.14.

**Comment by jwld** [comment]
This is still an issue

**Comment by Azilroka** [comment]
It won't until they fix the taint spread that comes from Edit Mode.

**Comment by jwld** [comment]
@kodewdle Can this issue be reopened please? It's very much still a problem.

**Comment by kodewdle** [comment]
I will reopen it sure, however @Azilroka is correct.  The issue is hard to fix, in order to help fix the issue.  Can you post the steps in  order (least amount possible, ideally) to get the error to happen, for example:

1) disable all but elvui
2) go into instance
3) open bag
4) click item doesn't work

**Comment by kodewdle** [comment]
linked this ticket on our known-issues on discord, maybe others will reply with useful information to help track the cause. thank you :)

**Comment by Etern213** [comment]
> linked this ticket on our known-issues on discord, maybe others will reply with useful information to help track the cause. thank you :)

Seems that there is no reliable way to track this taint. Everytime I met this issue, I reloadui and try to do everything I did before, and the taint issue didn't happen again.
I will continue testing until I find a way to track it.

**Comment by Telokis** [comment]
In case I can help understand things out: I suddenly had this issue yesterday and managed to fix it by simply uninstalling ElvUI Adibags. (I had already removed Adibags but forgot this small addon.)

I can confirm that simply re-adding the addon will prevent me from opening my bags. The exact addon is https://www.curseforge.com/wow/addons/elvui-adibags.

**Comment by dezzuzu** [comment]
in my limited testing, the garrison skin is causing the bug. i disabled the skin and the bug is occurring much less, and i can right click my items from my bags now

**Comment by jwld** [comment]
> in my limited testing, the garrison skin is causing the bug. i disabled the skin and the bug is occurring much less, and i can right click my items from my bags now

I've had all skins disabled for a while and I'm still seeing this unfortunately!

**Comment by jwld** [comment]
@Luckyone961 this is still a problem, I have to reload my UI at least once every hour to use items in my bags. I get that it's hard to fix when it can't be accurately replicated, but don't think this issue should be closed?
