### ISSUE TITLE
[Retail Bug Report] Can't start a group for WQs

### ISSUE THREAD

**Issue by Djodrake** [tukui-org/ElvUI#629]
### What is the issue you are having?

Tried to create a group through clicking on the Find Group button next to a world quest and later start a group but it just gives me the message Interface action failed because of an Addon. I can join groups fine through find a group just not start one.
Edit: What i mean is that the group doesnt start automatically i have to type in the group details manually.

### What is the expected behavior?

To be able to create either a 5 man party for WQs like the Challenges in Bastion or create a raid group for World Bosses.

### What actually happened?

I get the Interface action failed because of an Addon i used /edebug on and got Interface action failed because of an Addon but because i couldnt see the lua error i activated BugGrabber and BugSack 
![WoWScrnShot_112522_094846](https://user-images.githubusercontent.com/115336180/204041399-c0cfac00-90d5-49b1-8cda-0d15a010e6f0.jpg)
When i run with elvui on this happens after i press start a group for World Bosses or Challenges emissary ![WoWScrnShot_112822_0538311](https://user-images.githubusercontent.com/115336180/204195464-00239f1c-8d7b-4d5f-8720-a13731c5aec1.jpg)
With Elvui off it works as intended 
![WoWScrnShot_112822_0537402](https://user-images.githubusercontent.com/115336180/204195610-10cf3536-d0a7-4170-acc0-e9c64e712960.jpg)
### Suggested Solution/Workaround

Found out that it is the LFG skin that causes the issues, it works again when i disable it.

### Errors

```shell
23x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'CreateListing()'.
[string "@Interface\AddOns\!BugGrabber\BugGrabber.lua"]:480: in function <Interface\AddOns\!BugGrabber\BugGrabber.lua:480>
[string "=[C]"]: in function `CreateListing'
[string "@Interface\FrameXML\LFGList.lua"]:1055: in function `LFGListEntryCreation_ListGroupInternal'
[string "@Interface\FrameXML\LFGList.lua"]:1117: in function `LFGListEntryCreation_CheckAutoCreate'
[string "@Interface\FrameXML\LFGList.lua"]:658: in function `LFGListEntryCreation_Show'
[string "@Interface\FrameXML\LFGList.lua"]:2107: in function <Interface\FrameXML\LFGList.lua:2104>
[string "=[C]"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Djodrake u didn't do the Troubleshoot Steps right still other Addons enabled BUT.

Already posted and retested by me with Videos.

https://github.com/tukui-org/ElvUI/issues/261

Check here! Devs will sure take a look into it!

**Comment by Djodrake** [comment]
> @Djodrake u didn't do the Troubleshoot Steps right still other Addons enabled BUT.
I mentioned before the screenshot that i couldnt get my lua errors to show without buggrabber and bugsack thats the only other addons i had active.
