### ISSUE TITLE
[Retail Bug Report] Thick black bar around corners in Keybind interface

### ISSUE THREAD

**Issue by Daenarys** [tukui-org/ElvUI#63]
### What is the issue you are having?

The borders are thicker then in other parts of the UI

### What is the expected behavior?

Should be the same thickness across all interface options

### What actually happened?

Open the Keybind interface and notice the larger borders around the edges

Heres the proof
https://i.imgur.com/P2uh4Xl.png

### Suggested Solution/Workaround

Fix the borders and make them the same as they are in other parts of the UI

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Azilroka** [comment]
Well you are going to be disappointed... Those are shadows.

**Comment by Daenarys** [comment]
Hmm not sure if I get you, but I'm using your ElvUI 12.50 :)
Were the shadows added in 9.1.5? didnt have them before

**Comment by Azilroka** [comment]
Are you using just ElvUI? I mean truly ElvuI and ElvUI OptionsUI... Not ElvUI Shadow and Light, Not AddOnSkins, Not ElvUI Nuts and Bolts, Not ElvUI MerathilisUI, Not ElvUI BenikUI?

**Comment by 1Botanica1** [comment]
Those shadows aren't from ElvUI 

The easiest way to test (and what should be done if you think there is an issue with EvUI) is to disable all addons except ElvUI. 

To quickly disable all other addons, type in chat in game 

/edebug on 

Then check.  If you still have the issue, type in chat in game 

/estatus 

And upload a FULL UI screenshot showing both the issue and the status panel. 

Those are the basic troubleshooting steps.

**Comment by Daenarys** [comment]
Looks like Simpy fixed it in 12.51.

Thanks!
