### ISSUE TITLE
[Retail Bug Report] Currently selected Chat Tab not highlighted

### ISSUE THREAD

**Issue by Daenarys** [tukui-org/ElvUI#630]
### What is the issue you are having?

The currently selected chat tab (General, Combat Log, Whispers etc) isnt highlighed by default and only gets highlighted after you click it. Used to be highlighted all the time.

How it looks when you login
https://i.imgur.com/xiX56qQ.png

How it looks after you click the tab
https://i.imgur.com/dxXRMg0.png

### What is the expected behavior?

The tab you're currently on should be highlighted at all times

### What actually happened?

When you login/change maps the chat tab loses its highlight

### Suggested Solution/Workaround

Make the currently selected chat tab highlighted at all times

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
In the ElvUI menu - click on Install

Click on install cvars

Don't go through the install for the rest, it will reset ElvUI to default. 

If you copy profiles over, you need to go through the install part of ElvUI first, and then copy a profile over.
