### ISSUE TITLE
[Retail Bug Report] Custom actionbutton glow not working

### ISSUE THREAD

**Issue by Lor4de** [tukui-org/ElvUI#634]
### What is the issue you are having?

The custom actionbutton glow doesnt work. Instead the default blizzard style is used. Seems like it happend after the dragonflight prepatch

### What is the expected behavior?

The blizzard actionbutton glow should be replaced by the pixel glow. Worked before dragonflight prepatch

### What actually happened?

The option to configure the action button glow is missing and the old blizzard style is applied

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
If you read the changelog you would have noticed it was removed for the time being due to license issues.
