### ISSUE TITLE
[Retail Bug Report] Totem Tracker Settings Inverted

### ISSUE THREAD

**Issue by xIGBClutchIx** [tukui-org/ElvUI#635]
### What is the issue you are having?

It looks like the sort direction is inverted. Ascending is currently going from top-down, and descending is going from bottom-up.

### What is the expected behavior?

Inverted so that Ascending is going from bottom-up, and descending is going from top-down.

### What actually happened?

Changing the setting and then casting the spell "Consecration" and totem bar appears to be inverted.

### Suggested Solution/Workaround

Inverted the setting

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by xIGBClutchIx** [comment]
Yep here is a few pictures highlighting the issue.
<details>
<summary>Screenshots</summary>

![WoWScrnShot_112822_111543](https://user-images.githubusercontent.com/975065/204327534-9fbb5d67-461f-41eb-82e4-1b90fe178889.jpg)

![WoWScrnShot_112822_111526](https://user-images.githubusercontent.com/975065/204327538-3774c62d-c8cd-4281-b70d-014d1ab56a80.jpg)

![WoWScrnShot_112822_111532](https://user-images.githubusercontent.com/975065/204327544-52722768-5459-4ee7-b4d1-dc23c85839ff.jpg)
</details>

**Comment by Azilroka** [comment]
Ascending order would be
1
2
3
4

Decending order would be
4
3
2
1

However.. due to if it's shown or not.. 1 would be at the top on both until you get more totems.
