### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by neo6633** [tukui-org/ElvUI#637]
### What is the issue you are having?

broke blizzard raid frame 

### What is the expected behavior?

https://i.imgur.com/TvhgZrj.png

check this

### What actually happened?

https://i.imgur.com/TvhgZrj.png

check this

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] 애드온 'ElvUI'|1이;가; 보호된 함수 'CompactRaidGroup1:unusedFunc()' 호출을 시도했습니다.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `unusedFunc'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:151: in function `LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:128: in function `TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:52: in function <...actRaidFrames/Blizzard_CompactRaidFrameContainer.lua:50>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@neo6633 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off
