### ISSUE TITLE
[Retail Bug Report] ProfessionsOrders.lua Lua errors thrown

### ISSUE THREAD

**Issue by wilzifer** [tukui-org/ElvUI#641]
### What is the issue you are having?

ProfessionsOrders.lua Lua errors thrown

### What is the expected behavior?

No Lua errors thrown

### What actually happened?

Message: Interface/AddOns/ElvUI/Mainline/Modules/Skins/Load_Skins.xml:103 Error loading Interface/AddOns/ElvUI/ProfessionsOrders.lua
Time: Mon Nov 28 13:45:15 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI/Mainline/Modules/Skins/Load_Skins.xml:103 Error loading Interface/AddOns/ElvUI/ProfessionsOrders.lua
Time: Mon Nov 28 13:45:15 2022
Count: 1

### Errors

```shell
Message: Interface/AddOns/ElvUI/Mainline/Modules/Skins/Load_Skins.xml:103 Error loading Interface/AddOns/ElvUI/ProfessionsOrders.lua
Time: Mon Nov 28 13:45:15 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI/Mainline/Modules/Skins/Load_Skins.xml:103 Error loading Interface/AddOns/ElvUI/ProfessionsOrders.lua
Time: Mon Nov 28 13:45:15 2022
Count: 1
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/640#issuecomment-1329832929
