### ISSUE TITLE
[Retail Bug Report] Keybinds stop working randomly that are in the action bar until /reload

### ISSUE THREAD

**Issue by badudulance** [tukui-org/ElvUI#643]
### What is the issue you are having?

Hello, i have this problem bugging me since prepatch launch and it still persists. It happens seemingly randomly, at least I wasn't able to discern any pattern besides that it triggers on pressing a keybind at any time.

### What is the expected behavior?

I should press the keybind and the ability should activate.

### What actually happened?

I tried to figure out by process of addon elimination and bugsack to figure out what the cause is but ultimately can't understand a thing. Whenever I'm just damaging enemies, usually the whole of my main action bar stops working. Whenever i press a keybind, there is a clicking noise and does nothing. The ability activates with a left mouse click though, but not with the right click (right click before the bug works for activating abilities). I am lost, tried reinstalling via tukui client, manually, nothing worked.
Here are some bugsack errors that occur once this happens.

![image](https://user-images.githubusercontent.com/109975907/204854171-3d061275-87b9-424f-8b7e-873a90aa5148.png)
![image](https://user-images.githubusercontent.com/109975907/204854187-7ae59128-49d0-491e-a0e7-b9d09e54586e.png)
![image](https://user-images.githubusercontent.com/109975907/204854211-fcc052c4-df0d-4df2-841d-82ecb91c37c9.png)

### Errors

```shell
Error screenshots posted above. Some people point out that these are taints, however I have disabled log taint in ElvUI settings. I searched far and wide, could not find a way to disable taints in bugsack as is said in the FAQ of ELVUI. Please help I am losing my mind over this.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Missing Blizzard Bars with ElvUI right now is causing taints because of an error on Blizzards side

**Comment by badudulance** [comment]
Is there a way to fix it then? I don't fully understand how to not have blizz and elvui bars mixed up. Since not that many people have this problem, I assume there should be a way to fix it even if only temporarily. Thank you!

**Comment by Azilroka** [comment]
Ok so if you use ElvUI's ActionBars you don't lose the keybinds.. If you don't use ours and use the Default UI ActionBars you do. That's what I was saying. There isn't a way to fix it at the moment. This taint breaks the default actionbars because of their editmode tainting the game.
