### ISSUE TITLE
[Retail Bug Report] Herb Tracking isn't staying checked/selected.

### ISSUE THREAD

**Issue by madmann26** [tukui-org/ElvUI#644]
### What is the issue you are having?

Herb tracker checkbox isn't staying selected.

### What is the expected behavior?

When the checkbox is checked, it should stay checked.

### What actually happened?

The first check doesn't stick. Clicking again allows the box to be checked but when you click out and go back, it's unchecked.

### Suggested Solution/Workaround

No errors were displayed when this happens.

### Errors

```shell
/none
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ChristianHernon** [comment]
Came here searching for this bug actually. My experience has been that it's all the map filters, minerals, herbs, transmog. They all revert back to a default state whenever you die. Once on they remain on while logging in and out. But once you die, they're off again and you must re-enable.

**Comment by Azilroka** [comment]
Have you checked to see if this happens with default ui?

**Comment by Azilroka** [comment]
I am not getting that behavior with just ElvUI enabled.

**Comment by Bengesko** [comment]
Having this same issue; checked updates, mods, etc. I haven't died on my toons, either.
