### ISSUE TITLE
[Retail Bug Report] Professions - # of Items to Craft Counter Resets to 1

### ISSUE THREAD

**Issue by Calesta** [tukui-org/ElvUI#645]
### What is the issue you are having?

The counter to craft multiple items in the professions window keeps resetting to 1.

![image](https://user-images.githubusercontent.com/13042214/204903155-c198c47b-eb86-4466-94da-5a88f140e4f3.png)

I'm able to increase/decrease it, but after about 1 second it resets to 1.

### What is the expected behavior?

Obviously, I'd expect the counter to increase/decrease based on user seletcion.

### What actually happened?

The counter increases/decreases but resets to 1 after about a second.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/204935738-31c38aff-8911-4bbf-9ce3-d477777b0e96.mp4

**Comment by Calesta** [comment]
I'm not sure why this was closed as it's still an issue.

I didn't have an opportunity to respond until now given other responsibilities.  Given the above, I also captured a video to show the behavior I'm experiencing.

 https://user-images.githubusercontent.com/13042214/205230804-31d866e0-bbbf-4f59-ab6a-0dcf7a613f4b.mp4

I'm hoping this can be resolved given the likelihood that we'll need to craft multiples for discoveries, skill ups, etc., but I'm not sure what else I can provide in terms of troubleshooting the issue.  Please let me know if you need additional information.
