### ISSUE TITLE
[Retail Bug Report] <Procs dotted line, can't fix>

### ISSUE THREAD

**Issue by johnnyowens01** [tukui-org/ElvUI#647]
### What is the issue you are having?

When a skill procs I get a small rotating lines instead of the regular flashy border from the skill. (After updating today)

### What is the expected behavior?

Should be regular flashy border when a proc happens.

### What actually happened?

Small rotating lines appear around skill instead.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
not an error with elvui, just need to change the option in general -> cosmetics section
