### ISSUE TITLE
[Retail Bug Report] DragonFlight debuff don't show on target UnitFrame (friendly) and party UnitFrames

### ISSUE THREAD

**Issue by Kenppa78** [tukui-org/ElvUI#649]
### What is the issue you are having?

Hi, 

I noticed that several DragonFlight debuffs don't show on the UnitFrames. 
They appear on the Player UnitFrame but don't on the Target UnitFrame (friendly)or on the Party UnitFrame. This has been experienced in open world, but also in several dungeons, such as in Brackenhide Hollow. 
You can see an example here https://imagizer.imageshack.com/img922/8219/Lgepxs.jpg

### What is the expected behavior?

All debuffs should be displayed accordingly to the applied filters. 
I tried to remove all filters, but nothing seems to work

### What actually happened?

I could not find a solution to display these debuffs

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
you must have filter settings incorrect - issues for auras can't be specific to an expansion or specific aura.  if you need help with auras just come over to our discord 🌼
