### ISSUE TITLE
An action was blocked in combat because of taint from ElvUI - OverrideActionBarButton6:Show()

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#654]
### What is the issue you are having?

Taint Log Issues

### What is the expected behavior?

No Taint Log Issues

### What actually happened?

Getting taint log issues.

### Errors

```shell
12/1 23:00:39.470      Interface_Wrath\FrameXML\UIParent.lua:1090
12/1 23:00:39.470      OverrideActionBarButton4:Show()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:357 ActionButton_Update()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:694 ActionButton_OnEvent()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:207
12/1 23:00:39.470  An action was blocked in combat because of taint from ElvUI - OverrideActionBarButton4:Show()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:357 ActionButton_Update()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:694 ActionButton_OnEvent()
12/1 23:00:39.470      Interface\FrameXML\ActionButton.lua:207
12/1 23:00:54.182  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by ElvUI - Interface_Wrath\FrameXML\UIParent.lua:4756 DisplayInterfaceActionBlockedMessage()
12/1 23:00:54.182      Interface_Wrath\FrameXML\UIParent.lua:1090
12/1 23:00:54.182      OverrideActionBarButton4:OverrideActionBarButton4:()
12/1 23:00:54.182      Interface\FrameXML\ActionButton.lua:357 ActionButton_Update()
12/1 23:00:54.182      Interface\FrameXML\ActionButton.lua:694 ActionButton_OnEvent()
12/1 23:00:54.182      Interface\FrameXML\ActionButton.lua:207
12/1 23:00:54.182  Execution tainted by ElvUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface_Wrath\FrameXML\UIParent.lua:4753 DisplayInterfaceActionBlockedMessage()
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
Here's the original taint log file.

[taint.log](https://github.com/tukui-org/ElvUI/files/10142073/taint.log)

**Comment by kodewdle** [comment]
since The War Within is out and this is a taint, reopen if you still have the issue please :)
