### ISSUE TITLE
[Retail Bug Report] MinmapHolder Improperly Scales

### ISSUE THREAD

**Issue by DaveA50** [tukui-org/ElvUI#655]
### What is the issue you are having?

The frame ElvUI_MinimapHolder currently scales twice the scaling amount

### What is the expected behavior?

I would expect the holder frame should scale with the minimap frame

### What actually happened?

When setting the minimap scale to 200%, the holder frame because 2x as large as the scaled minimap. When setting the minimap scale to 50%, the holder frame because half the size of the scaled minimap.

Oversized holder frame at 200%
![minimap holder 200](https://user-images.githubusercontent.com/5604326/205320876-e3ba0856-25d0-413c-a392-d1ae7ada68ad.png)

Undersized holder frame at 50%
![minimap holder 50](https://user-images.githubusercontent.com/5604326/205320922-d2cf3d9f-339a-4262-9604-6b66e30f5b2a.png)

Missing holder frame at 50%
![minimap holder 50 missing](https://user-images.githubusercontent.com/5604326/205320674-f5b9ed94-a878-4b3f-994c-7131dfbdd863.png)

### Suggested Solution/Workaround

ElvUI/Core/Modules/Maps/Minimap.lua:397 add a line `holder:SetScale(1 / mmScale)`

Previous PR was closed, sorry for not providing details before https://github.com/tukui-org/ElvUI/pull/651

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
thanks, i was confused with the PR because you were talking about the hidden holder not the actual mover.. anyways should be good now :) 🌼

**Comment by kodewdle** [comment]
for the record, the MinimapCluslter will also have the "wrong" size; but i choose to not mess with this because well, they use it for the "minimap cluster bar" (optional in elvui) and the size can't dynamically adjust, so if you need to anchor use the hidden holder ;)
