### ISSUE TITLE
[Retail Bug Report] Professions - # of Items to Craft Counter Resets to 1

### ISSUE THREAD

**Issue by Calesta** [tukui-org/ElvUI#657]
### What is the issue you are having?

The counter to craft multiple items in the professions window keeps resetting to 1.

![image](https://user-images.githubusercontent.com/13042214/205377311-043fe1a3-908d-40a0-a798-d57bf1e35853.png)

I'm able to increase/decrease it, but after about 1 second it resets to 1.  Here's a video showing the behavior.

https://user-images.githubusercontent.com/13042214/205377535-e64876b8-5de5-43f4-8df6-4663b995b9ba.mp4

I'm hoping this can be resolved given the likelihood that we'll need to craft multiples for discoveries, skill ups, etc., but I'm not sure what else I can provide in terms of troubleshooting the issue. Please let me know if you need additional information.

### What is the expected behavior?

Obviously, I'd expect the counter to increase/decrease based on user selection.

### What actually happened?

The counter increases/decreases but resets to 1 after about a second.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/205397228-0ebb5af0-6074-4b9b-b73d-78b4c1bf671a.mp4

You are reporting the Default UI behavior.

**Comment by Calesta** [comment]
I'm sure you're very busy and you're closing all these tickets as fast as possible, but I never noticed this as the default behavior. It's not how the base UI works unless it's changed in Dragonflight and was not documented.   I was always able to set the number I wanted to craft, hit 'Create' and it would create that number of items.  The 'Create All' button was there if you wanted to do the maximum number of item crafts.  As I increment the number now, it will simply go back to one at some point which makes crafting a specific number impossible.  I either have to create each individually, create them all or start to create them all and then stop in the middle after the desired number.  If you're simply going to close the issue ticket when I report it, then I guess I'll just deal with it or find an alternative.  Thanks.

**Comment by chriser-** [comment]
I think what he is saying is that the bug is on blizzards side, as it also happens on default UI and there is nothing ElvUI can do.

I have it as well and it is annoying, but blizzards needs to fix it first in the default UI. If it is still broken in ElvUI then, you can open another bug.

**Comment by Azilroka** [comment]
It is reseting in the Default UI. I'm not simply closing the ticket for the fun of it. I showed it with 0 addons.

**Comment by Calesta** [comment]
Thanks Chriser, I misunderstood what was written.  I appreciate the clarification.  I hope that's the case.

Azilroka, my apologies if that came off as condescending or rude; I didn't mean it as such.  I just didn't understand why these tickets were being instantly closed when I knew there was still an issue.  In your video, I didn't see the counter reset at all and the timer you opened went a full five (5) seconds and didn't go back to 1.  If it's truly a Blizzard issue, then I wouldn't have expected that to happen.

In any case, at least Chriser confirmed that I'm not alone in my madness.  I'll wait for it to sort itself out as these things usually do.  :)

**Comment by Azilroka** [comment]
It was cut a little short I guess in the video. It does revert the very last second of the video.

**Comment by voidbeast** [comment]
Yes, this is definitely happening in the default Blizz UI with no addons. There are several noticeable symptoms like the numbers resetting periodically for craft amount as well as for allocation of different quality materials. The tooltip for the item to be crafted also will blink at the same rate as the resetting of the values. Very annoying, but it is not an ElvUI issue....which is kinda disappointing because I know y'all would've fixed it by now if it were. >.<
