### ISSUE TITLE
[Retail Bug Report] Interface/FrameXML/ContainerFrame.lua:907: attempt to index local 'itemButton' (a nil value)

### ISSUE THREAD

**Issue by zmoose** [tukui-org/ElvUI#658]
### What is the issue you are having?

I'm using ElvUI 13.08

I got a new 34 slot bag [Misty Satchel] and after equiping it I got the LUA error and now when I try to open bags it give a LUA error and doesn't open bags.

### What is the expected behavior?

No errors and bag function works

### What actually happened?

Getting LUA error and bags are not opening up.

### Suggested Solution/Workaround

Reloading the UI fixed the issue.

### Errors

```shell
Message: Interface/FrameXML/ContainerFrame.lua:907: attempt to index local 'itemButton' (a nil value)
Time: Fri Dec  2 16:39:05 2022
Count: 1
Stack: Interface/FrameXML/ContainerFrame.lua:907: attempt to index local 'itemButton' (a nil value)
[string "@Interface/FrameXML/ContainerFrame.lua"]:196: in function <Interface/FrameXML/ContainerFrame.lua:194>
[string "@Interface/FrameXML/ContainerFrame.lua"]:220: in function `OpenBag'
[string "@Interface/FrameXML/ContainerFrame.lua"]:285: in function `OpenBackpack'
[string "@Interface/FrameXML/ContainerFrame.lua"]:98: in function `ToggleBackpack_Combined'
[string "@Interface/FrameXML/ContainerFrame.lua"]:117: in function <Interface/FrameXML/ContainerFrame.lua:111>
[string "=[C]"]: in function `ToggleBackpack'
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

Locals: id = 0
force = nil


Message: Interface/FrameXML/ContainerFrame.lua:907: attempt to index local 'itemButton' (a nil value)
Time: Fri Dec  2 16:40:48 2022
Count: 3
Stack: Interface/FrameXML/ContainerFrame.lua:907: attempt to index local 'itemButton' (a nil value)

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Thats a blizzard error.
