### ISSUE TITLE
[TBC Bug Report] Aura Durations incorrect / not updating

### ISSUE THREAD

**Issue by lauenchr** [tukui-org/ElvUI#66]
### What is the issue you are having?

Aura durations are not always up to date. Noticed it on elixirs for the most part during raiding.
Tooltip is correct afaik. Elixirs often stayed at 59 minutes even thirty minutes into usage.

![image](https://user-images.githubusercontent.com/47520341/141373669-79b575fd-47d3-41c0-a99d-d0f7f7717a35.png)
![image](https://user-images.githubusercontent.com/47520341/141384686-54c2cefa-4957-45b9-b935-61b67fefbbb6.png)

Edit: This started happening after the recent updates of ElvUI. I am sure before 2.19 this was working as intended.
I don't know which of the updates broke the feature.

### What is the expected behavior?

Duration should match effective value.

### What actually happened?

I used elixirs in a 25 man raid. Duration stayed at 59 minutes instead of showing actual time.

### Suggested Solution/Workaround

/reload updates the time (once)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by 1Botanica1** [comment]
This is fixed in dev and will be in the next release

**Comment by lauenchr** [comment]
just saw in discord that it should be fixed in dev, closing the issue
