### ISSUE TITLE
[Retail Bug Report] Empowered Spells switch input methods if dismounted in combat (ElvUI 13.10)

### ISSUE THREAD

**Issue by Neonemerld** [tukui-org/ElvUI#665]
### What is the issue you are having?

On my Evoker, I use the Hold and Release input method but if I dismount from a Dragonriding mount while in combat, Empowered spells function as if the "Press and Tap input" method is selected; i.e. releasing the button no longer ends the cast and you have to press a second time to finish the cast instead. This issue can be resolved by remounting a Dragonriding mount and dismounting again out-of-combat, but always reoccurs when dismounting in combat.

I've tested to ensure this is an issue with ElvUI by disabling all other addons except ElvUI and by disabling just the action bar module in ElvUI, where the issue is not present on default action bars even with other addons present. This issue also does not appear when riding ordinary mounts, so I can only assume the issue takes place during the transition from the Dragonriding bar back to the standard bar.

### What is the expected behavior?

Expected behavior is that dismounting from a Dragonriding mount should not change the way Empowered spell inputs work.

### What actually happened?

Empowered spells are changing their input methods when dismounting a Dragonriding mount in combat.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Neonemerld** [comment]
Updated to 13.10, issue still persists.

**Comment by tinyspider** [comment]
Still happening with 13.11. Is it a ELVUI bug or something to do with blizzard’s UI?

**Comment by Neonemerld** [comment]
As far as I can tell, it is a bug with ElvUI because it doesn't persist with default bars. As I mentioned in the first report, it's an issue that only happens while ElvUI's actionbars are enabled. Even leaving everything else enabled and turning off just ElvUI's actionbar module, the default bars don't have this behavior.

**Comment by Neonemerld** [comment]
Update 13.12 seems to have resolved this issue.
