### ISSUE TITLE
[Retail Bug Report] Disabling Raid Control leaves two black squares in it's place instead

### ISSUE THREAD

**Issue by LuniaDev** [tukui-org/ElvUI#666]
### What is the issue you are having?

Disabling Raid Control under General -> BlizzUI Improvements leaves weird black squares where Raid Control used to be

### What is the expected behavior?

Raid Control should disappear and leave no traces behind after being disabled

### What actually happened?

There are two black squares in place of Raid Control after disabling it

See this album: https://imgur.com/a/Tq7AQSz

Seems inconsistent to reproduce, sometimes the black squares don't show up regardless of raid / group status

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed in 13.11
