### ISSUE TITLE
[Retail Bug Report] KeyboardMouseConfirmButton misbehaving

### ISSUE THREAD

**Issue by Mr-nUUb** [tukui-org/ElvUI#667]
### What is the issue you are having?

A frame called `KeyboardMouseConfirmButton` is put on the middle of the screen after a cutscene is played. It makes part of my action bars unclickable. A reload fixes it temporarily.

Here's a screenshot with framestack and ElvUI infos right after eating some Tuskarr soup. This is the most reliable way to trigger this behaviour, as it's available on a regular basis.
![grafik](https://user-images.githubusercontent.com/36689675/205514794-048864fa-722c-4e67-bfa7-f52af875cf65.png)

### What is the expected behavior?

`KeyboardMouseConfirmButton` should not be on top of my action bars, like it was before prepatch.

### What actually happened?

Somehow `KeyboardMouseConfirmButton` ends up on top of my action bars.

### Suggested Solution/Workaround

A reload fixes it until the next cutscene is triggered.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Mr-nUUb** [comment]
Not every cutscene triggers this. The fall of the Lich King in old Dalaran doesn't trigger this.

**Comment by Azilroka** [comment]
We don't make that or alter that frame. It's part of the Tutorial Frames.

**Comment by Mr-nUUb** [comment]
Would it be feasible to add a workaround for this behaviour? If Blizzard isn't able to fix bugs and releases beta-quality software as stable, someone else has to do the dirty work I guess...

**Comment by Scarah22** [comment]
I had same issue.  I solved it by installing MoveIT, created frame KeyboardMouseConfirmButton and moved it..

I can confirm it´s Blizz frame - I disabled ALL addons, except for Addon Control Panel and MoveIT and that frame is still present and movable, so it´s not created by addon, but addon will probably trigger it..

**Comment by Mr-nUUb** [comment]
Please disregard my previous comment. I am able to recreate this issue without any addons (default UI).

Thanks to [Tyreith on the official forums (US)](https://us.forums.blizzard.com/en/wow/en/wow/t/fstack-frame-attribute-showhide-question/1429575/2) I am able to temporarily hide this frame using`/tinspect KeyboardMouseConfirmButton` and disabling `Show` . This change does not survive reloads or logging out and back in, but it keeps the frame from reappearing on subsequent cutscenes.

**Comment by kodewdle** [comment]
im just going to close this as it's not something we mess with.  thanks!
