### ISSUE TITLE
 [Retail Bug Report] Actionbar  Bugs #526 if Elvui bars are disabled

### ISSUE THREAD

**Issue by MeetTh3Greed** [tukui-org/ElvUI#668]
### What is the issue you are having?

Bug still not fix but closed ? Actions Bars doesnt work as usual. Getting still the same error if u disable elvui bars.

### What is the expected behavior?

Bugs get fixed

### What actually happened?

Actionbars arent usable

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
know of this problem and have been working on it, reopen if you still have the trouble after 13.11 but please reopen with `/estatus` screenshot thanks! :)
