### ISSUE TITLE
[Retail Bug Report] Character Summary showing character that isn't mine

### ISSUE THREAD

**Issue by omgshooz** [tukui-org/ElvUI#669]
### What is the issue you are having?

When I hover over the gold amount to bring up my server-wide gold summary, there's a character that appeared at the bottom that doesn't belong to me. 

![image](https://user-images.githubusercontent.com/119820838/205521441-38f357ff-241b-461f-b20b-b018694ededc.png)

### What is the expected behavior?

Expected to not see a character that doesn't belong to me. 

### What actually happened?

Someone else's character is shown in my summary tooltip

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Delete it. Shift + Right Click
