### ISSUE TITLE
[Retail Bug Report] <Artifact Power error>

### ISSUE THREAD

**Issue by Zallanon** [tukui-org/ElvUI#67]
### What is the issue you are having?

When you kill a mob and loot a lua error happens.

### What is the expected behavior?

I think it is expecting a number for your existing artifact power from BfA and when it checks you don't have the heart or gear on so it can't find one.

### What actually happened?

A nil value in artifact power causes an error

### Suggested Solution/Workaround

If the mod can exclude the check outside of BfA maybe, not sure

### Errors

```shell
Message: [string "Error in: UseArtifactPower"]:26: attempt to call method 'SetTexture' (a nil value)
Time: Thu Nov 11 17:51:13 2021
Count: 2
Stack: [string "Error in: UseArtifactPower"]:26: attempt to call method 'SetTexture' (a nil value)

Locals: <none>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org).

**Comment by Luckyone961** [comment]
Thats really interesting, you are posting an error about your broken WeakAura called "UseArtifactPower" in the ElvUI issue tracker

**Comment by Azilroka** [comment]
Well they are using ElvUi.. So it has to be ElvUI's fault.
