### ISSUE TITLE
[Retail Bug Report] <Can't close settings/options in combat>

### ISSUE THREAD

**Issue by martins33** [tukui-org/ElvUI#670]
### What is the issue you are having?

Can't close options (SettingsPanel) in combat. So basically if I'm running a dungeon or something, if I open my settings to lower the audio I can't close it anymore until I'm out of combat, and it blocks my screen.

### What is the expected behavior?

I should be able to close the settings panel in combat.

### What actually happened?

I can't close the settings panel in combat.

### Errors

```shell
Interface action failed because of an Addon.

I found this reddit comment https://www.reddit.com/r/wow/comments/cqq3vx/comment/ewyooma/?utm_source=share&utm_medium=web2x&context=3

which probably has some useful info about this.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed (work around) by https://github.com/tukui-org/ElvUI/commit/efc26a7facaf158bc32d2f680387087bb5b78446
