### ISSUE TITLE
[Retail Bug Report] Can't remove dropdown abilities from the bars

### ISSUE THREAD

**Issue by javiramos94** [tukui-org/ElvUI#671]
### What is the issue you are having?

I can't remove some abilities from my character's bars, specifically those that have different options presented as a dropdown, like mages' portals or warlocks' pets. It's been happening for a few ElvUI patches.

### What is the expected behavior?

I think it should work as it did before, where you could place them in the bars and remove them without issues.

### What actually happened?

I can't remove some abilities from my character's bars, specifically those that have different options presented as a dropdown, like mages' portals or warlocks' pets. It's been happening for a few ElvUI patches.

### Suggested Solution/Workaround

I think it should work as it did before, where you could place them in the bars and remove them without issues.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
this is just how it is, the flyouts right now are custom and don't have drag/drop support.  they are a temporary replacement to just have.. literally anything that works for right now until Blizzard can fix the real flyouts
