### ISSUE TITLE
"Bleed Effects" showing on Partyframes

### ISSUE THREAD

**Issue by MpHollow** [tukui-org/ElvUI#672]
**Is your feature request related to a problem? Please describe.**
Yes, because Evoker have the option to dispell bleeds.

**Describe the solution you'd like**
Toe have premade filters that show bleeds done from all the NPCs that are dispellable (Like Poisons etc.=

**Describe alternatives you've considered**
Alternatives would be to manually build a filter for every bleed that is in the game currently.

**Additional context**
If there is no way that will be implemented in the Addon, please someone tell me how to put all bleeds into on Filter so it shows me the Aura Highlights on my Partyframe if its dispellable :)

**Comment by kodewdle** [comment]
https://github.com/tukui-org/ElvUI/commit/6502d278d512d033c2b5497cb8c00a39c5166519 closes this, however we still need to populate what is a bleed manually until blizzard provides an API to detect it?
