### ISSUE TITLE
[Retail Bug Report] CMD keybinds on Mac not registering

### ISSUE THREAD

**Issue by danielrdotcom** [tukui-org/ElvUI#673]
### What is the issue you are having?

Still cant use Elvui on a Mac as of yet, specifically with regards to using the Command/Meta button. The command button is much easier to reach than CTRL and ALT/OPT. I use alot of CMD+X (as in 1, 2, 3, 4, Q, E, R, etc.) keybinds, this makes it real hard to use my favorite UI (been an ElvUI main for years). I can imagine this is tied to the Blizz UI changes, but I hope there's a workaround/patch for it. Hope this can be solved.

Basically if I try to key bind anything with CMD/Meta it doesn't get used. It works in the base UI but on Elvui the same keybinds seem to be ignored.

### What is the expected behavior?

Keybind with CMD+X (any other button) should work

### What actually happened?

Adding a key bind via ElvUI with the CMD/Meta button does not work, does not register. Even if the keybinds do exist in the default WoW UI it's not showing up or registering on ElvUI.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by danielrdotcom** [comment]
bump

**Comment by syntrixsystems** [comment]
I have this same issue.  Trying to bind shift-left mouse button and it will not bind anywhere. I have shift-rightmouse bound no problem.  Binding other keys works but not shit-leftmouse.

**Comment by Repooc** [comment]
> I have this same issue. Trying to bind shift-left mouse button and it will not bind anywhere. I have shift-rightmouse bound no problem. Binding other keys works but not shit-leftmouse. It tells me it's bound but hovering over the bind it doesn't show or work. I'm on a PC. Disabled all other addons. Still cannot save this bind.
> 
> ![image](https://user-images.githubusercontent.com/47372832/211100682-57394bfc-939d-4d08-b64f-20680b3ebb97.png) ![image](https://user-images.githubusercontent.com/47372832/211100767-d3db9941-80da-4b10-8a6c-88d45c3d9c2d.png)

bc wow doesnt accept binding left and right mouse button natively (i say this bc i have heard bartender does something to work around this which we do not do or intend to do as we let blizzard deal with the handling of what button combinations are allowed vs not)
as for the mac stuff, i cant not comment on how its handled at all in any situation as i do not have a mac to do any tests on so the op will have to wait for someone else to respond that may know off top of their head (as i know none of the dev team run macs)

**Comment by syntrixsystems** [comment]
I see. It did work on bartender before this. I should have just chosen to keep bartender when I did the install.  Don't really want to revert now so I'll work around it.

**Comment by eyalalonn** [comment]
Currently as far as I can tell from the code **ElvUI** doesn't account for `IsMetaKeyDown` whereas **Blizzard**'s code does.

**Comment by wduda** [comment]
I can report that the issue persists, reducing the QoL for Mac users significantly.

**Comment by Nhilrim** [comment]
Yes it is really annoying to disable ElvUI everytime to change/add keybindings cause it works fine with default UI. Dont understand whats the problem with ElvUI since the ticket has been opened last year.

**Comment by kodewdle** [comment]
let me know if this works in dev version please :)

**Comment by kodewdle** [comment]
closing, reopen if this doesn't help in dev: https://github.com/tukui-org/ElvUI/commit/b14765c95d68a46ed9dacc041ba3c786d617c328

**Comment by mikhaben** [comment]
which release will these changes be in?

**Comment by kodewdle** [comment]
13.41 or you can test [development.zip](https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip)
