### ISSUE TITLE
Incompatibility with MobInfo2

### ISSUE THREAD

**Issue by Muehe** [tukui-org/ElvUI#675]
### What is the issue you are having?

Ok, I lied in the checklist below, I didn't disable all other addons, since this is a compatibility issue. When both ElvUI and MobInfo2 addons are active then mob tooltips are broken.

(Note that Questie is also active in all the following screenshots and affected by the bug, but the bug also occurs with just MobInfo2+ElvUI)

### What is the expected behavior?

Tooltips should merge together nicely without removing text. Screenshots for reference.

Tooltip with just ElvUI (and Questie):

![elvui](https://cdn.discordapp.com/attachments/831324000717242439/1049431741091295303/Screenshot_20221205_215913_elvui_questie.png)

Tooltip with just MobInfo2 (and Questie):

![mobinfo2](https://cdn.discordapp.com/attachments/831324000717242439/1049431742035009666/Screenshot_20221205_215712_mobinfo_questie.png)

### What actually happened?

Text is removed below the header and below the first line of Questie's text.

![bug](https://cdn.discordapp.com/attachments/831324000717242439/1049431742433460224/Screenshot_20221205_215552_elvui_mobinfo_questie.png)

### Suggested Solution/Workaround

Disabling the ElvUI tooltip module in the settings is a functioning workaround.

Ideally the addons should integrate nicely, but not sure how that would work. Considering that ElvUI aims for a consistent design it would make sense that MobInfo2 just waives tooltip design when it detects ElvUI tooltip module to be enabled.

I created a report [on the MobInfo2 CurseForge page](https://www.curseforge.com/wow/addons/mobinfo2?comment=2125) since they don't seem to have a GitHub.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Merathilis** [comment]
If the issue is still happening, please report back
