### ISSUE TITLE
[Retail Bug Report] Dungeon Finder Symbol on Minimap is missing

### ISSUE THREAD

**Issue by Nersunea** [tukui-org/ElvUI#676]
### What is the issue you are having?

As the Titel says

### What is the expected behavior?

No response 

### What actually happened?

Since Version 13.08 the Dungeon Finder Symbol on the Minimap is missing. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ImSlipp** [comment]
I had this same issue but figured it out. Have you by chance downloaded the addon minimapbuttonbag? If so the dungeon finder icon would be in there.

**Comment by Nersunea** [comment]
Omg your absolutely right, there it is. Many thanks! So no Bug here!
