### ISSUE TITLE
[Retail Bug Report] x V13.10 /[ADDON_ACTION_BLOCKED] AddOn 'ElvUI' hat versucht die geschützte Funktion 'UIParentRightManagedFrameContainer:SetPoint()' aufzurufen.

### ISSUE THREAD

**Issue by Vilogity** [tukui-org/ElvUI#678]
### What is the issue you are having?

Happens only when in Group.
ELVUI 13.10 

### What is the expected behavior?

idk

### What actually happened?

After joining a Group with my Heal Druid, and Trash fight begins this error happens. 

### Suggested Solution/Workaround

idk

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' hat versucht die geschützte Funktion 'UIParentRightManagedFrameContainer:SetPoint()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML/AnchorUtil.lua"]:34: in function `SetPoint'
[string "@FrameXML/UIParent.lua"]:3095: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2570: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3113: in function <FrameXML/UIParent.lua:3111>
[string "=[C]"]: in function `UIParent_ManageFramePositions'
[string "@FrameXML/TargetFrame.lua"]:1347: in function `UpdateSize'
[string "@FrameXML/TargetFrame.lua"]:1280: in function <FrameXML/TargetFrame.lua:1279>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@FrameXML/TargetFrame.lua"]:123: in function `Update'
[string "@FrameXML/TargetFrame.lua"]:179: in function `OnEvent'
[string "@FrameXML/UnitFrame.lua"]:1041: in function <FrameXML/UnitFrame.lua:1039>

Locals:
Skipped (In Encounter)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
this could be fixed already, closing it for now re-open after posting `/estatus` on 13.11 with the error please~
