### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Lycaner88** [tukui-org/ElvUI#679]
### What is the issue you are having?

I dont know since dragonflight i get always elvui lua errors

### What is the expected behavior?

happens every time the a fight starts

### What actually happened?

it lag´s then a fight starts

### Errors

```shell
19x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' hat versucht die geschützte Funktion 'MainMenuBar:SetPointBase()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPointBase'
[string "@FrameXML/EditModeSystemTemplates.lua"]:62: in function `SetPoint'
[string "@FrameXML/EditModeSystemTemplates.lua"]:177: in function `ApplySystemAnchor'
[string "@FrameXML/EditModeSystemTemplates.lua"]:607: in function `ApplySystemAnchor'
[string "@FrameXML/EditModeSystemTemplates.lua"]:202: in function `UpdateSystem'
[string "@FrameXML/EditModeSystemTemplates.lua"]:587: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1015: in function `UpdateSystem'
[string "@FrameXML/EditModeManager.lua"]:1008: in function `UpdateSystems'
[string "@FrameXML/EditModeManager.lua"]:882: in function `UpdateLayoutInfo'
[string "@FrameXML/EditModeManager.lua"]:239: in function <FrameXML/EditModeManager.lua:231>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
should be fixed in 13.11
