### ISSUE TITLE
[TBC Bug Report] Cannot control guild ranks

### ISSUE THREAD

**Issue by JanezStupar** [tukui-org/ElvUI#68]
### What is the issue you are having?

Guild management operations don't seem to work.

### What is the expected behavior?

Changing the rank should result in guild members rank to change.

### What actually happened?

As an officer in guild when clicking the uprank or downrank button, nothing happens. I hear a click, but nothing happens.

Same holds true for trying to kick people.

### Suggested Solution/Workaround

Workaround is to disable elvui and use built in tools

### Errors

```shell
Message: ADDON_ACTION_FORBIDDEN: ElvUI tried to call the protected function 'GuildDemote()'.
Time: Fri Nov 12 13:49:15 2021
Count: 1
Stack: ADDON_ACTION_FORBIDDEN: ElvUI tried to call the protected function 'GuildDemote()'.
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...UI\Core\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[string "=[C]"]: in function `GuildDemote'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: <none>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by JanezStupar** [comment]
I have confirmed this, with all addons disabled excetp Elvui v2.23

**Comment by Luckyone961** [comment]
This Blizzard taint cannot be fixed at this point

**Comment by JanezStupar** [comment]
Is it at least possible to disable guild controls so that we can directly use the Blizzard UI?

There are issues with raid controls too and having default UI would be preferable for me. That's why I am asking.
