### ISSUE TITLE
[Retail Bug Report] <BAG Currency>

### ISSUE THREAD

**Issue by frankcccccccccc** [tukui-org/ElvUI#680]
### What is the issue you are having?

Bag backdrop overlaps the currency,

### What is the expected behavior?

shouldn't be covered.

### What actually happened?

Bag backdrop overlaps the currency area after the >>Reverse bag slots<< has been selected.
Its able to fix it after clicking on >>Scrap icon<< option with bag open but resets back after reloading and covers the currency bar again. 

### Suggested Solution/Workaround

No permanent solution found.

### Errors

```shell
not that I noticed.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
No screenshot of the issue and of /estatus

**Comment by frankcccccccccc** [comment]
![WoWScrnShot_120622_192945](https://user-images.githubusercontent.com/119971162/206057168-647f5e28-1115-48ba-8d8e-42f313e1724f.jpg)

sry about that.
