### ISSUE TITLE
[Classic Bug Report] No longer heal prediction

### ISSUE THREAD

**Issue by Dichotomia** [tukui-org/ElvUI#681]
### What is the issue you are having?

Hi,

since last version i have no longer heal predictions.

Thanks for the fix.

Best regards

### What is the expected behavior?

Have heal predictions

### What actually happened?

No heal prediction

### Suggested Solution/Workaround

Fix the bug

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
No bug, Read changelog.
