### ISSUE TITLE
More Description ActionBar Names

### ISSUE THREAD

**Issue by Jahfry** [tukui-org/ElvUI#682]
**Is your feature request related to a problem? Please describe.**
Issue attempting to resolve: rationalize bar names between how ElvUI labels action bars in settings versus how they are displayed by BlizzardUI and Bartender

**Describe the solution you'd like**
Make the labels for ActionBars in the ElvUI match to their names/uses similar to how BlizzardUI displays them. This shouldn't require any changes to the functionality of the bars, just a display value edit (that's an assumption). 

Retail is where things get the messiest with Bar names, which makes sense due to recent additions to Dragonflight's number of bars. I assume that the oddities like Blizzard Bar 2 being ElvUI bar 6 (etc) are to keep compatibility with previous Classic profiles while keeping the Retail and Classic ElvUI base the same. 

ALTERNATIVELY: Instead of changing the display label, if it breaks something that keeps compatibility with WoW Classic, maybe just add more description text to the top of each 'Settings > ActionsBars > Player Bars' entry like:

* [ElvUI Bar 2] ... "Bonus Action Bar ... used by the Blizzard UI to page additional actions on Bar 1 as needed"
* [ElvUI Bar 3] ... "Retail BlizzardUI shows this as 'Bar 4', Classic Blizzard UI shows this as 'Right Bar'"
* (etc)

The above would give a way to keep the ElvUI bar #s the same between Retail and Classic while still giving information to the user on how to look at these bars. *For anyone besides a Druid OR a long-time Bartender user who is switching to ElvUI,* ***they probably don't need this much***, but as someone who is both of those things, Bar labels became a big issue for me. 

Bartender for instance displays names that are more obviously similar to the BlizzardUI. To be clear, this isn't a request focused on Bartender compatibility, I'm just including that information as an example. 

I'll show the current mappings for both Retail (Dragonflight) and Classic. Items in () on the Blizzard column indicate that BlizzardUI doesn't show these labels to the players as they are used for Bonus and Class Form shifts automatically. 

**Retail:**
| Blizzard    | ElvUI  | Bartender        | Class                   |
|-------------|--------|------------------|-------------------------|
| (Bar 1)     | Bar 1  | Bar 1            | Druid:None/Travel       |
| (Bonus Bar) | Bar 2  | Bonus Action Bar |                         |
| Bar 2       | Bar 6  | Bar 2            |                         |
| Bar 3       | Bar 5  | Bar 3            |                         |
| Bar 4       | Bar 3  | Bar 4            |                         |
| Bar 5       | Bar 4  | Bar 5            |                         |
| Bar 6       | Bar 13 | Bar 6            |                         |
| Bar 7       | Bar 14 | Bar 7            |                         |
| Bar 8       | Bar 15 | Bar 8            |                         |
| (Class 1)   | Bar 7  | Class 1          | Druid:Cat,Rogue:Stealth |
| (Class 2)   | Bar 8  | Class 2          | Druid:Cat/Prowl         |
| (Class 3)   | Bar 9  | Class 3          | Druid:Bear              |
| (Class 4)   | Bar 10 | Class 4          | Druid:Moonkin           |

**Classic:**
| Blizzard          | ElvUI  | Bartender | Class                   |
|------------------|--------|-----------|-------------------------|
| (Action Bar)     | Bar 1  | Bar 1     | Druid:None/Travel       |
| (Bonus Bar)      | Bar 2  | Bar 2     |                         |
| Right Bar        | Bar 3  | Bar 3     |                         |
| Right Bar 2      | Bar 4  | Bar 4     |                         |
| Bottom Right Bar | Bar 5  | Bar 5     |                         |
| Bottom Left Bar  | Bar 6  | Bar 6     |                         |
| (Class 1)        | Bar 7  | Bar 7     | Druid:Cat,Rogue:Stealth |
| (Class 2)        | Bar 8  | Bar 8     | Druid:Cat/Prowl         |
| (Class 3)        | Bar 9  | Bar 9     | Druid:Bear              |
| (Class 4)        | Bar 10 | Bar 10    | Druid:Moonkin           |

**Describe alternatives you've considered**
Alternative method provided above. 

Otherwise the player simply has to adapt and rationalize each bar on their own. 

**Additional context**

**Comment by Jahfry** [comment]
And note ... I've got things figured out on my end. No worries for me. I'm just trying to make it easier on the next returning Druid player who might be thinking of switching to ElvUI for bar management.

**Comment by Jahfry** [comment]
Ugh. I spaced on the title. Sorry. Should be "Enhance Action Bar labels" or similar.

**Comment by Azilroka** [comment]
The current mappings for ElvUI are exactly the same.. I don't know how you are saying its not for Retail.

**Comment by Azilroka** [comment]
`AB.barDefaults = {
	bar1 = { page = 1, bindButtons = 'ACTIONBUTTON', position = 'BOTTOM,ElvUIParent,BOTTOM,-1,191' },
	bar2 = { page = 2, bindButtons = 'ELVUIBAR2BUTTON', position = 'BOTTOM,ElvUIParent,BOTTOM,0,4' },
	bar3 = { page = 3, bindButtons = 'MULTIACTIONBAR3BUTTON', position = 'BOTTOM,ElvUIParent,BOTTOM,-1,139' },
	bar4 = { page = 4, bindButtons = 'MULTIACTIONBAR4BUTTON', position = 'RIGHT,ElvUIParent,RIGHT,-4,0' },
	bar5 = { page = 5, bindButtons = 'MULTIACTIONBAR2BUTTON', position = 'BOTTOM,ElvUIParent,BOTTOM,-279,4' },
	bar6 = { page = 6, bindButtons = 'MULTIACTIONBAR1BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,264' },
	bar7 = { page = 7, bindButtons = 'ELVUIBAR7BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,298' },
	bar8 = { page = 8, bindButtons = 'ELVUIBAR8BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,332' },
	bar9 = { page = 9, bindButtons = 'ELVUIBAR9BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,366' },
	bar10 = { page = 10, bindButtons = 'ELVUIBAR10BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,400' },
	bar13 = { page = 13, bindButtons = 'MULTIACTIONBAR5BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,400' },
	bar14 = { page = 14, bindButtons = 'MULTIACTIONBAR6BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,400' },
	bar15 = { page = 15, bindButtons = 'MULTIACTIONBAR7BUTTON', position = 'BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-4,400' }
}`

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/206287838-5ba571be-8a4f-4b7e-9f09-3a628a32c49d.png)

**Comment by Jahfry** [comment]
Going to close this and open a fresh one with an actual title.

**Comment by Jahfry** [comment]
> That part was from me using all 3 modes side-by-side (disabling both, enabling ElvUI while Bartender disabled, disabling ElvUI while Bartender disabled) on a Druid with all bars opened. Also with freshly nuked WTF folder.
> 
> It was also very very late at night so I could have goofed that. I'll recheck later.



> The current mappings for ElvUI are exactly the same.. I don't know how you are saying its not for Retail.

Not sure we're talking in the same direction on that. To clarify where I was coming from and how I got there ... 

To recreate why I say the bars don't match between Addons (which is getting down a sidetrack from the original request, but worthy), I'll redo everything step-by-step. I'm doing this as an end user, not looking at config files. 

* WoW Retail BlizzardUI
    * Download/install Bartender and ElvUI
        * but ... before logging in the new character in next screen, disable both addons for now
    * New character (no need to empty WTF to get a fresh slate) with empty UI & no Addons enabled
    * Display Action Bars 2-8 in Blizz > Options > Action Bars
    * Create a macro called "Bar 3" (can be empty)
    * Create a macro called "Bar 4" (can be empty)
    * Drag "Bar 3" macro to Bar 3 on BlizzardUI (verified correct bar by untoggling Bar 3 in Options to see bar with macro disappear, as well as with Edit Mode)
    * Drag "Bar 4" macro to Bar 4 on BlizzardUI (verified correct bar by untoggling Bar 4 in Options to see bar with macro disappear, as well as with Edit Mode)

* Bartender
    * Enable Bartender , ReloadUI
    * enable Bartender Bar 3, verify that the Bar 3 macro is on Bar 3
    
* ElvUI
    * Disable Bartender, Enable ElvUI, ReloadUI
    * Configure ElvUI (initial wizard > Cvars > etc)
    * Toggle Anchors in ElvUI to verify which bar is Bar 3 and which is Bar 4, enable if not already up (don't remember if Bar 4 was displayed by default or not)
    * Mouse over the macro on Bar 3 ... *but it's the macro for Bar 4* (look @ tooltip)
    * Mouse over the macro on Bar 4 ... *it's the macro for Bar 5*
    
Similar process for any other bars shown in my table that don't match the # labels between Blizz/Bartender vs. ElvUI. 

It can all work. It wouldn't be a problem for someone starting from scratch with ElvUI. It's a minor thing if they're moving from BlizzardUI to ElvUI. It's a bigger issue for someone deciding between Bartender and ElvUI, especially if they already have things organized in a way where they remember bar numbers. 

Going back to the top level of the request, the generic "Bar #" labels in ElvUI are simply less informative than the more descriptive labels from BlizzardUI/Bartender. It would seem like it would be a good enhancement to present more descriptive labels. 
    
    
PS. I'm not focusing on WotLK Classic in the above. I've done some configs there, but don't play much except to hang with some old friends. The issue I was trying to bring up is replicated entirely by the above. However I did do a full round of bar# macros and repeated the above steps in Classic WotLK to verify that all bars matched between Blizz/Bartender/ElvUI.

**Comment by Azilroka** [comment]
Well the more descriptive labels can probably be done however.. people go through and change the behavior a lot.

Bartender went through and changed their labels recently to help with new players.

Our bars are setup by actual API returns so our bar 3 is page 3 like its supposed to be even though it's labeled 2 in Blizzard UI because Bar 1 has the back page where you can click.

**Comment by Azilroka** [comment]
Like if you put a spell / macro on bar 2. Then do `/run PickupAction(13)` you will see. 13 is page 2 slot 1

**Comment by Azilroka** [comment]
The other issue is macro conditionials [bar:N]

[bar:2] is 2 in our UI.

I assume that's not the case in Bartender.

**Comment by Jahfry** [comment]
Yeah, I wouldn't want to do anything to change the behavior of existing configs. 

* Simple descriptive text in the UI for each action bar along the lines of "equates to [Bar 2 | Class Bar 1 | Bonus Bar] in the BlizzardUI" might be enough to address the request. 
* Or a toggle in the overall ElvUI Action Bar settings for "[ ] Show BlizzardUI-style Bar Names". And only change the display, not the ElvUI bar numbers under the hood.
