### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by GaetanDoucet** [tukui-org/ElvUI#689]
### What is the issue you are having?

I no longer see disease that I can dispell on my group frame

### What is the expected behavior?

Before some new version, I was able to see with character has a disease or not and that I can dispell it

### What actually happened?

There is nothing showned

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
what class/ spec/ ability gives you disease cure?

**Comment by GaetanDoucet** [comment]
I'm playing holy priest, and I use "Purify" for it. For exemple when there is a magic effect that I can dispel, the frame of the character in the group changes colour slightly and the icon is displayed in the middle (as on the screenshot). However, this no longer applies to disease effects. 
![image](https://user-images.githubusercontent.com/35337536/206691555-5b27a2fe-6a09-4827-a1dc-ecb457501cda.png)

**Comment by Ghostamoose** [comment]
Should be fixed in the next release: 1341020b18de3ff47556148bd1887fbebe1b39be.
