### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by ToxxicApe** [tukui-org/ElvUI#690]
### What is the issue you are having?

Addons Skins - Rare Scanner Close Button is omega small

https://i.imgur.com/7jEaSiA.png

### What is the expected behavior?

first time using addonskins

### What actually happened?

hard to close the window

### Suggested Solution/Workaround

make it bigger

### Errors

```shell
no error
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by ToxxicApe** [comment]
right click fix ;)

**Comment by Azilroka** [comment]
This is not AddOnSkins Tracker.
