### ISSUE TITLE
[Retail Bug Report] Items not showing in bag

### ISSUE THREAD

**Issue by ImSlipp** [tukui-org/ElvUI#691]
### What is the issue you are having?

I have encountered a couple situations where some items don't show in my bag after looting. 

### What is the expected behavior?

Loot to show in bag

### What actually happened?

Loot did not show in bag, bought the Grand Expedition Yak and it did not show the reins in inventory, had to disable ElvUI to claim, also had the same issue with two new dragonflight critters.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by mcfarlin72** [comment]
What I find happening on the PTR is that the items in the bag are sort of frozen. Anything new that goes into bags doesn't show. or if you swap gear it doesn't show, but the actions do happen behind the scene.

**Comment by ImSlipp** [comment]
That's good to know. Just a minor inconvenience having to turn the ElvUI addon off to claim a new mount/pet .

**Comment by Azilroka** [comment]
You more than likely have a bag toggled off. Open the bag bar. If you see an red x then that's the issue.

**Comment by mcfarlin72** [comment]
Still doesn't work for me. All other addons disabled. No red X on bags. When I click on an item in my bags and move it to a different slot the icon shows up in both slots, but the original slot is just grayed out.
![bag issue](https://user-images.githubusercontent.com/24536460/206802363-3a3efe04-a8e2-4537-b358-3298b356e405.JPG)
