### ISSUE TITLE
[Retail Bug Report] <Chat position resetting on load>

### ISSUE THREAD

**Issue by Bromosaurus** [tukui-org/ElvUI#694]
### What is the issue you are having?

Recently swapped to an ultrawide monitor. Enabled Ultrawide support which fixed most issues. However, whenever I load into the game or anytime I have a loading screen, my left chat position and size are reset to default. I am only experiencing this issue in retail. I run the exact same UI in wrath classic with no issues.

I attempted to completely delete elvui and all of its settings from my savedvariables folder and did a fresh install, but the issue still persists.

![qIwT2l7](https://user-images.githubusercontent.com/120209937/206763992-e94ed08f-88e9-47e9-b2c5-d34c8b4e5232.jpeg)

### What is the expected behavior?

When chat is setup during the install, it should remain in that position unless changed.

### What actually happened?

Chat was setup during initial install, but refuses to stay in the designated position upon any loading screen.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by aaronchance** [comment]
Adding more info to this. Doesn't appear to be explicitly tied to ultrawide setting, but moving the chat panel to somewhere other than the original location in the layout installation will cause this bug to occur sporadically

**Comment by rbedsole** [comment]
I'm having an issue that is opposite to this on load/reload the chat box moves higher up and to the right of the default location, what's really odd is that it only happens on one character my dracthyr.
