### ISSUE TITLE
[Retail Bug Report] Expanding a spell flyout triggers an infinite loop of `Spell.IsUnitInRange()`, occasional Lua errors

### ISSUE THREAD

**Issue by Ghostamoose** [tukui-org/ElvUI#696]
### What is the issue you are having?

Opening a spell flyout on your action bars triggers an infinite loop that makes the addon constantly run the action button range check: `Spell.IsUnitInRange()` method. This does not have any affect on functionality or appearance (as far as I know).

I believe this error is related to some Lua errors I've seen mentioned in the ElvUI Retail Support channel on the Discord.

Example error:
```
Message: ...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2461: IsSpellInRange(): Invalid spell slot
Time: Sat Dec 10 19:25:40 2022
Count: 183
Stack: ...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2461: IsSpellInRange(): Invalid spell slot
[string "=[C]"]: ?
[string "=[C]"]: in function `IsSpellInRange'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2461: in function `IsUnitInRange'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2380: in function `IsInRange'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1542: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1540>
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1493: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1476>
```

The above error is (presumably) caused by `FindSpellBookSlotBySpellID()` returning `nil`. I haven't been able to figure out why that function fails. It can return `nil` if given a spell that the player doesn't know, or if it's given a passive spell, though I can't figure out why either of those would apply to the spell flyouts, as they *should* only have known spells in them.

Most of the reports of the above error seem to have something to do with going through a portal, or being otherwise teleported whether it be through the Hearthstone, a summon, etc. I haven't been able to reproduce the error, however it's been mentioned that it happens still with `/edebug` enabled. Since it affects spell flyouts, it's probably mostly limited to classes with default flyout abilities, or people who are evil and put the Dragonflying flyout on their action bar for some reason.

The whole reason I am reporting this error is because, while investigating the above Lua error, this infinite loop is the only way I could find to consistently call `Spell.IsUnitInRange()` to reproduce the error, and it would make sense that it could cause large error counts as seen in the Discord reports. Basically, this infinite loop exposes a bug that would otherwise never be encountered.

### What is the expected behavior?

`Spell.IsUnitInRange()` should not be looping infinitely for flyout buttons that are hidden. In fact, spell flyouts shouldn't even be checked for range, as they (I think) are never home to spells that have a set range.

### What actually happened?

Opening a spell flyout causes the action button range check to loop infinitely.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
should be fixed in 13.11
