### ISSUE TITLE
[Retail Bug Report] Healing Priest (Disease) Aura Highlight not working

### ISSUE THREAD

**Issue by priestdiseasehighlight** [tukui-org/ElvUI#697]
### What is the issue you are having?

Color Highlight for Disease debuffs is not working for Healing Priests, While with the same Settings it does work for Shadow Priest and Mistweaver Monk (so far I know).

Illustrated issue: https://imgur.com/a/Jtk68NW

I've seen already another topic about this (https://github.com/tukui-org/ElvUI/issues/649), but in this case I do think it is an expension issue.

Reasoning: Purify (prior DF, Magic and Disease) got split into two with the DF expension, Purify (magic) and the talented, Improved Purify (Disease).

I don't know if this is anything Elvui can do, or a Blizzard thing, I'm not technical enough for that. Just wanted to point out that it exists. 

### What is the expected behavior?

-

### What actually happened?

-

### Suggested Solution/Workaround

-

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by fdreamsu** [comment]
Same here

**Comment by Ghostamoose** [comment]
Should ideally be fixed in the next release: https://github.com/tukui-org/ElvUI/commit/1341020b18de3ff47556148bd1887fbebe1b39be.

**Comment by kodewdle** [comment]
fixed in 13.11 thanks :)
