### ISSUE TITLE
Textures reset after each reload/relog

### ISSUE THREAD

**Issue by Nononsama** [tukui-org/ElvUI#698]
### What is the issue you are having?

Hello. My textures reset on each relog for some reason. This is how they look when I log into the game https://gyazo.com/b06610ec4f2cbaa33a3b84ac319c0ba6
And this is what smooth supposed to look like:
https://gyazo.com/1bdeeb3649d8e12f3aa88ca8fab26c70

I tried to reinstall wow, elvui, configure everything from scratch, but nothing helps. Every single time I have to choose the texture again, it's very tedious. Is it possible to fix this problem?

### What is the expected behavior?

For smooth texture to be a smooth texture

### What actually happened?

The textures defaults back to Elvui Norm

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Nononsama 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

No cropped Screenshots also u are on 13.06 update to 13.10.

**Comment by Nononsama** [comment]
With edebug on I get this: https://gyazo.com/406cf3530a855baa746b8a1de6d20e34
https://gyazo.com/7ea0256344bda94edb6782ec5aceca4a
There are less texture options to choose from and elvui still default to blizzard textures (I think)
estatus https://gyazo.com/0792dacd99ba18c70ec0b6dc23b98d8f
edebug off https://gyazo.com/d0d5c82749503df2246503786622309b
Issue still remains

**Comment by Nononsama** [comment]
Updated to 13.10, same thing https://gyazo.com/75c319cda0d67c6b0b8be5c3c33ee193

**Comment by RAtwood90** [comment]
> The smooth texture comes in one of this addons https://gyazo.com/7acc5fe789bcd7f01dca6ffea1de2f14 Do you have the texture seperated so I can add it to Elvui as a custom texture?

ElvUI didn't have an Smooth Texture. All ElvUI Textures begins with ElvUI (as i remember correctly)

**Comment by Nononsama** [comment]
Then how can I find where this texture comes from?

**Comment by Azilroka** [comment]
Smooth comes from ElvUI

**Comment by Nononsama** [comment]
Well then how can I find it? Or how can I fix it? There is a file called Smooth located here H:\World of Warcraft\_retail_\Interface\AddOns\ElvUI\Core\Media\Textures
However, deleting it, renaming it or altering it in anyway doesn't seem to have any affect on the matter.

**Comment by Azilroka** [comment]
Then you are not working with the correct directory set in the launcher.

**Comment by Nononsama** [comment]
In the battle net launcher or the tukoi launcher? Because I don't use the later

**Comment by RAtwood90** [comment]
> In the battle net launcher or the tukoi launcher? Because I don't use the later

**World of Warcraft\_retail_\**Interface\AddOns that's the right Folder Structure not **World of Warcraft_retail_\**Interface\AddOns

**Comment by 1Botanica1** [comment]
From memory, this could be something profile related, an issue with that profile. 

Create a new profile and test.  Does the texture change?

**Comment by Nononsama** [comment]
I tried reinstalling wow and making new profile from scratch several times, and on 2 different machines, yet the problem persists.
I'll share my profile later for you to test it yourself.

**Comment by Nononsama** [comment]
> From one other report I have seen with this issue, it was a profile issue.
> 
> Create a new profile and test. Does the texture change?

reply above

**Comment by 1Botanica1** [comment]
Do you still have issues with this?


Type in game `/edebug on`

Test - do you have the issue?

If so, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the error and the status panel.
