### ISSUE TITLE
Quest Bar lost when Elvui is on.

### ISSUE THREAD

**Issue by KL3szcz** [tukui-org/ElvUI#699]
### What is the issue you are having?

Hello. I have a problem with Quest Bars. When there is a Quest where you have to fly on a dragon and press keys, for example, there are no Bars. With disabling Elvui everything works normally.
![2022-12-11 (1)](https://user-images.githubusercontent.com/120339193/206929615-fe5e1e32-5ccf-42f8-9bbb-a5a832eb3a3b.png)
 Now when Elvui is off.
 
![2022-12-11 (2)](https://user-images.githubusercontent.com/120339193/206929699-2eaaa954-46de-4f09-8624-6200f9ada1c5.png)

Some one know where is problem?

### What is the expected behavior?

some one can fix this

### What actually happened?

The bars gone.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@KL3szcz 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

Also i did the same Quest and it's worked for me.

Two Problems can be. Another Addon conflict with ElvUI that's why we got Troubleshooting Steps.

Second ur Bars/Visibility is set wrong.

**Comment by KL3szcz** [comment]
i did /edebug and still have issue.
![2022-12-21 (2)](https://user-images.githubusercontent.com/120339193/208993719-78faf56c-5550-4825-bae9-341c4b585b3a.png)

No bar for nex Quest. I turn off all addons only stay ElvUi and still have issue.

**Comment by Repooc** [comment]
> i did /edebug and still have issue. ![2022-12-21 (2)](https://user-images.githubusercontent.com/120339193/208993719-78faf56c-5550-4825-bae9-341c4b585b3a.png)
> 
> No bar for nex Quest. I turn off all addons only stay ElvUi and still have issue.

this is not with the command `/edebug on` as it would have disabled all addons besides elvui which u have other addons enabled still.  in addition to the status window (you can click and drag it to move it), and post ur actionbar 1 settings (expand the window to try to fit all of it in the picture)

**Comment by Azilroka** [comment]
This is probably the same people who replace their bar1 with another bar number to have it shown all the time while having the main bar hidden..
