### ISSUE TITLE
[TBC Bug Report] Bankslots with items displayed as empty

### ISSUE THREAD

**Issue by insunaa** [tukui-org/ElvUI#70]
### What is the issue you are having?

Bank slots are sometimes displayed as empty on first opening the bank.

### What is the expected behavior?

Bank should always display the correct contents

### What actually happened?

Bank displays some slots as empty when first opening the bank. Immediately after login it's often all slots being displayed as empty.
![image](https://user-images.githubusercontent.com/3718129/141643236-0ba9e96b-5c39-49cb-a37c-e8101c7e6855.png)

### Suggested Solution/Workaround

You can close the bank and re-open the bank and then usually it will mostly display the correct items in the correct slots.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
We know and its fixed in dev.
