### ISSUE TITLE
[Wrath Bug Report] cooldowns.lua error when use some skill (ex: Hunter's Mark )

### ISSUE THREAD

**Issue by coldmeat777** [tukui-org/ElvUI#700]
### What is the issue you are having?

elv ui version : 13.10
wow version : 3.4.0
![image](https://user-images.githubusercontent.com/120456495/207280465-435c19da-fcff-47f4-b726-e00fe1da1d09.png)

*issue*
during level up, 
get error everytime when use Hunter's Mark skill. (spell ID: 14323)
![image](https://user-images.githubusercontent.com/120456495/207279588-d901e64a-22aa-4ce7-8df5-208a34f757af.png)

The error log is as follows

159x Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219>
[string "=[C]"]: in function `SetCooldown'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558>
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1344: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 fontStyle = "OUTLINE"
 font = "Fonts\2002.TTF"
 fontSize = 15.944444
}
(*temporary) = "%d%s:|r%02d"
(*temporary) = 0.083333
(*temporary) = nil
(*temporary) = 5
(*temporary) = "string expected, got nil"

### What is the expected behavior?

No error should occur

### What actually happened?

Only error logs are collected. There is no problem with skill use

### Errors

```shell
159x Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219>
[string "=[C]"]: in function `SetCooldown'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558>
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1344: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 fontStyle = "OUTLINE"
 font = "Fonts\2002.TTF"
 fontSize = 15.944444
}
(*temporary) = "%d%s:|r%02d"
(*temporary) = 0.083333
(*temporary) = nil
(*temporary) = 5
(*temporary) = "string expected, got nil"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by coldmeat777** [comment]
Sorry for not being fluent in English.

**Comment by RAtwood90** [comment]
@coldmeat777 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

**Comment by coldmeat777** [comment]
here is full log when issue happen
Please let me know if you need more information
==================================================================
log1
Message: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
Time: Wed Dec 14 22:03:37 2022
Count: 2
Stack: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219>
[string "=[C]"]: in function `SetCooldown'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558>
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1310: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>

Locals: 
==================================================================
log2
Message: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
Time: Wed Dec 14 22:03:44 2022
Count: 2
Stack: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate'
[string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219>
[string "=[C]"]: in function `SetCooldown'
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558>
[string "@Interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1344: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>

Locals: 

==================================================================

![image](https://user-images.githubusercontent.com/120456495/207603020-12f70e43-d2c4-4547-839b-bb226bf0d7ef.png)

**Comment by RAtwood90** [comment]
> # here is full log when issue happen
> Please let me know if you need more information
> log1 Message: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil) Time: Wed Dec 14 22:03:37 2022 Count: 2 Stack: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil) [string "=[C]"]: ? [string "=[C]"]: in function `SetFormattedText' [string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate' [string "@interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate' [string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219> [string "=[C]"]: in function `SetCooldown' [string "@interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558> [string "@interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1310: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>
> 
> # Locals:
> log2 Message: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil) Time: Wed Dec 14 22:03:44 2022 Count: 2 Stack: Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:72: bad argument #3 to 'SetFormattedText' (string expected, got nil) [string "=[C]"]: ? [string "=[C]"]: in function `SetFormattedText' [string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:72: in function `Cooldown_OnUpdate' [string "@interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:119: in function `Cooldown_TimerUpdate' [string "@Interface\AddOns\ElvUI\Core\General\Cooldowns.lua"]:231: in function <Interface\AddOns\ElvUI\Core\General\Cooldowns.lua:219> [string "=[C]"]: in function `SetCooldown' [string "@interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1572: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1558> [string "@interface\AddOns\ElvUI_Libraries\Core\LibActionButton-1.0\LibActionButton-1.0.lua"]:1344: in function <...ies\Core\LibActionButton-1.0\LibActionButton-1.0.lua:1287>
> 
> Locals:
> 
> ==================================================================
> 
> ![image](https://user-images.githubusercontent.com/120456495/207603020-12f70e43-d2c4-4547-839b-bb226bf0d7ef.png)

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game **/estatus
Upload a full, uncropped screenshot showing the issue and the estatus.**
If you are finished with debugging, you can enable your AddOns back with: /edebug off

Do it again it seems u have deactivated but it's for reproduce Steps.

**Comment by kodewdle** [comment]
corrupt profile, the cd settings are busted in it

**Comment by kodewdle** [comment]
dm me on discord if you want me to fix the profile sometime

**Comment by coldmeat777** [comment]
thanks for the comment
I checked the cd setting of the action bar to disable it and confirmed that the error does not appear anymore.

![image](https://user-images.githubusercontent.com/120456495/208132167-41e76a5b-108d-48c4-968e-646ddda47489.png)

**Comment by coldmeat777** [comment]
Thank you again :) May all the luck and happiness in the world be with you. Merry Christmas and Happy New Year!!
