### ISSUE TITLE
[Retail Bug Report] <Can't open options/settings>

### ISSUE THREAD

**Issue by Swoosh20** [tukui-org/ElvUI#703]
### What is the issue you are having?

When I type /ec the options do not open

i have tried to do this with /luaerros on

I am using elvui version 13.10

### What is the expected behavior?

I expect the settings or options menu to open so i can edit my UI

### What actually happened?

I get this error message

Message: Interface/AddOns/ElvUI_OptionsUI/Core.lua:121: attempt to call method 'Ace3_ColorizeEnable' (a nil value)
Time: Wed Dec 14 10:15:02 2022
Count: 1
Stack: Interface/AddOns/ElvUI_OptionsUI/Core.lua:121: attempt to call method 'Ace3_ColorizeEnable' (a nil value)
[string "=[C]"]: in function `Ace3_ColorizeEnable'
[string "@Interface/AddOns/ElvUI_OptionsUI/Core.lua"]:121: in main chunk
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Config.lua"]:1078: in function `?'
[string "@Interface/AddOns/ElvUI/Libraries/Ace3/AceConsole-3.0/AceConsole-3.0.lua"]:94: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5224: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4924: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals: 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
when you updated, you did not remove the old folders first. you should alway remove the old folders and not overwrite.  we changed the name from ElvUI_OptionsUI to ElvUI_Options... so you should remove the ElvUI_OptionsUI folder assuming u do have the ElvUI_Options folder from when you tried to update previously
