### ISSUE TITLE
[Retail Bug Report] <the dragonheada for aspects menu is gone for hunter>

### ISSUE THREAD

**Issue by Spearhawk** [tukui-org/ElvUI#704]
### What is the issue you are having?

When using Elvui I notice that my hunter is lacking the dragonhead that you click on to get to see what level your in rep in factions in dragonflight. it only occurs when I am using my hunter, it has the tracking button there instead.

### What is the expected behavior?

to have the dragonhead there so I can click to view faction standings etc

### What actually happened?

its gone, there is no dragonhead at all

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by RAtwood90** [comment]
@Spearhawk 

Troubleshooting Steps (ElvUI)
Do these steps in order.

Type in chat in game /edebug on
Test - Do you still have the issue?
If you still have the issue/error - type in chat in game /estatus
Upload a full, uncropped screenshot showing the issue and the estatus.
If you are finished with debugging, you can enable your AddOns back with: /edebug off

**Comment by Spearhawk** [comment]
https://ibb.co/J7Sy1cM
https://ibb.co/v3gXkTG
https://ibb.co/6Wx82sw

check the bottom left part of the minimap where the tracking icon is, there should be the white dragonhead to show the various dragonriding and reputation, its not there.

**Comment by Spearhawk** [comment]
https://ibb.co/Ych20xK
this is my evoker, you see the dragonhead on the bottom left of the minimap, its only the hunter that lacks the dragonhead.

**Comment by RAtwood90** [comment]
Well may it's not an Issue check ur Minimap Settings may it's deactivated for ur Hunter?

**Comment by Spearhawk** [comment]
I have tried to find a setting that would change that but there are so many settings that its like finding a needle in a factory of needles :)

**Comment by Repooc** [comment]
sounds like u have the garrison icon hidden on that character (found in the maps -> minimaps section
