### ISSUE TITLE
[Retail Bug Report] (v13.11) Action bar buttons not working

### ISSUE THREAD

**Issue by JohnL245** [tukui-org/ElvUI#705]
### What is the issue you are having?

Buttons 10 and 11 on action bars 2-5 don't appear to function. I can push the binds or click on them and see it flashing indication it's being pressed, but the things bound to those slots don't work. Moving the icons out of those slots allows them to work again. Disabling the action bars from elvui allows those buttons to work, so this is certainly an elvui issue.

Clicking and dragging an icon into those slots allows you to bind new things to them, but if you click and drag off an action bar then try to **click**  to place an icon in those slots it won't take.

![image_2022-12-16_153937372](https://user-images.githubusercontent.com/120754728/208193376-bcbf8220-eb0e-4331-8001-39c6fed590de.png)

### What is the expected behavior?

The actions bound to the action bar should actually trigger when the button is pressed.

### What actually happened?

Action bar icon flashed like it was being pressed without actually triggering the intended action.

video example: https://youtu.be/iI-4oHqddLU

### Suggested Solution/Workaround

no workaound, these buttons need to work.

### Errors

```shell
no errors visibly trigger.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by enterdoki** [comment]
Can confirm also experiencing the same issue.

**Comment by Joshmvii7** [comment]
Having this issue with button 8 on bars 1 through 4. Gives the indication the button has been pressed but does not fire the action.

**Comment by Mavmins** [comment]
Same issue here, icon blinks but no action taken

**Comment by kodewdle** [comment]
should be fixed in 13.13 :) sorry about that one
