### ISSUE TITLE
[Retail Bug Report] Macro with modifier on ActionBar no longer works after upgrading from 13.11 to 13.13

### ISSUE THREAD

**Issue by dgimb89** [tukui-org/ElvUI#706]
### What is the issue you are having?

Greetings,

I upgraded from 13.11 to 13.13 this morning and multiple of my macros that use modifier conditionals do no longer work.

Example: Macro that is placed on ActionBar with Keybind C
```
#showtooltip
/cast [modifier:shift] Berserking
/cast [modifier:shift] Ancestral Guidance
/cast [nomod:shift,known:114052] Ascendance
/cast [nomod:shift,known:197995] Wellspring
```

As there was a recent change about ActionBarButton activation, I figured that could be related to the recent change. Downgrading back to 13.11 fixes it.

### What is the expected behavior?

When I hold down shift and press C, it should use Berserking as well as Ancestral Guidance,

### What actually happened?

No spell is being casted. Simplifying the macro does not help, any `modifier:shift` conditional will prevent the cast.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [x] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
try on 13.14 please and let us know thank you

**Comment by DarkforceNL** [comment]
I have the same Problem, 13.13 broke the shift macro button for me
also 13.14 didnt work

**Comment by dgimb89** [comment]
@kodewdle Still present in 13.14. Same issue with `/edebug on`. I did another test by installing 13.12 and that's when the issue was introduced.

As a workaround for now, I downgraded to 13.11. If you need some more details how to reproduce this or need me to test any bugfixes, I'm happy to help.

**Comment by DarkforceNL** [comment]
cant seem to downgrade cus i cant find older versions from elvui, but what i did found out is that when you enable lockcast bars and then change the drag button from default (shift) to (none) it seems to work again for me
lmk what you find out

**Comment by dgimb89** [comment]
@DarkforceNL That worked for me too. Disabling "Lock ActionBars" did not do the trick, but enabling and setting it to "None" did.

**Comment by DarkforceNL** [comment]
> @DarkforceNL That worked for me too. Disabling "Lock ActionBars" did not do the trick, but enabling and setting it to "None" did.

Thats why i sad Enable :P and nice that it worked :)

**Comment by Squimbert** [comment]
Same issue. When using a macro like:

#showtooltip
/use [mod:shift]Mighty Caravan Brutosaur;Grand Expedition Yak

and having the ElvUI Pick up Action Key set to shift (the same modifier in the macro), the macro no longer works.

When i change the picup action key to something that is not in my macro (for example alt in the above case), the issue resolves. But i would still ideally like my pickup key to be shift as well as my modifier in my macro to be shift as well.

**Comment by wing5wong** [comment]
following this as experiencing the same.
i use many shift/ctrl mod macros so this is quite high impact. (not sure what the initial fixes that introduced this fixed, maybe more important)
obviously changing the  actionbar drag key (to alt in my case) can limit the effect of this but still, its an awkward workaround at best so ideally there is some other solution.

**Comment by georgi-chinov** [comment]
Same behaviour with selfcast key dropdown (disables the alt mod in macros):
![image](https://user-images.githubusercontent.com/9299216/209413130-6fc64db8-873d-491e-9749-d3fdc5b7931e.png)

**Comment by Azilroka** [comment]
> Any updates on this? I've found I can get them to work if I go into **Options > Action Bars > Lock ActionBars** and change it to **None**. I have to do this each time I start the game as ElvUI seems to reset it back to Shift. When I remove ElvUI my changes remain, that's how I'm determining that it's ElvUI resetting it.

So you are saying it does it every time you login?
