### ISSUE TITLE
[TBC Bug Report] Cooldown of items in bag not properly displayed

### ISSUE THREAD

**Issue by insunaa** [tukui-org/ElvUI#71]
### What is the issue you are having?

If using an item with a cooldown multiple times in a row from the bag (such as bombs used for daily quests) on first use the cooldown will be correctly drawn on the item, on every subsequent use the cooldown will not be visible, unless the bag is closed and re-opened

### What is the expected behavior?

Cooldowns of items should always be drawn, even after using the item multiple times without closing the bag in between

### What actually happened?

Same as issue description. You click an item with a cooldown, the cooldown-number and clock appear as overlay on the item as they should. You click the item again, but this time the overlay is not drawn. Tho the item is actually being used and you can see the cooldown when you hover over the item in the tooltip

Edit: Cooldowns seem a bit broken in general
![image](https://user-images.githubusercontent.com/3718129/141656148-d2035c69-4522-4acb-bbf9-83cc7fc13a7e.png)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by 1Botanica1** [comment]
What version number of ElvUI are you on?

**Comment by insunaa** [comment]
2.24

**Comment by 1Botanica1** [comment]
This was tested & unable to be reproduced. 

Please type in chat in game 
/edebug on

And test.  Do you still have the issue? 

If so, type in chat in game 
/estatus 

And upload a full UI screenshot (I cropped) that shows both the issue and the status panel.

**Comment by insunaa** [comment]
daily quests are on lockout for today, I'll provide the requested info tomorrow! :)

**Comment by Luckyone961** [comment]
can confirm - its fixed in the next release
