### ISSUE TITLE
[Retail Bug Report] ESC doesn't close world map in combat

### ISSUE THREAD

**Issue by mnejing** [tukui-org/ElvUI#710]
### What is the issue you are having?

Please see issue  #686 

I replied, but as I didn't close the issue, I couldn't re-open. This is the reply in full: 

Hi.

So I didn't get a chance to reply back to this because of other commitments. I originally tracked this issue down to another addon that was intermittently causing issues and honestly forgot to come back here to reply. There was some persistent taint that wasn't clearing with /edebug on, which was when I wrote my original post. A complete closing of the client and then doing /edebug on did resolve the issue, and ultimately allowed me to track down the offender.

However, since 13.11 came out, the issue has returned. And instead of it being specific to an addon, it's 100% an issue in ElvUI.

Immediately prior to taking this screenshot, I confirmed that, when in combat, I could not close my map (or any other window, when it was limited to just my map prior to 13.11).

Again, there are no lua errors, just a standard taint (Interface action failed).

![image](https://user-images.githubusercontent.com/31494988/208294046-25e263a1-e17e-497b-b58f-1f40fb8a55a2.png)

### What is the expected behavior?

Windows should close when Escape is pressed while in combat

### What actually happened?

Windows such as the map attempt to adjust the frame, it moves downwards approximately 20 pixels and throws an Interface action blocked error.

### Suggested Solution/Workaround

Something about #686 made things worse.

### Errors

```shell
None.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
We're on 13.14 now
