### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Texxer** [tukui-org/ElvUI#715]
### What is the issue you are having?

Aura Bars are not aligning with the corner of the frame, they are off by a few pixels to the left. It happens to the player and the target frame.

### What is the expected behavior?

Aura Bars should have the same X-axis values as the frames.

### What actually happened?

![Wow_Y43gGLzndi](https://user-images.githubusercontent.com/22458550/208970712-0c34e922-8b9d-4151-8036-a2fe3062343e.png)

### Suggested Solution/Workaround

n/a

### Errors

```shell
n/a
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
> I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using /edebug on? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.
