### ISSUE TITLE
[Retail Bug Report] LFG Tool error

### ISSUE THREAD

**Issue by ravi66** [tukui-org/ElvUI#716]
### What is the issue you are having?

Can not use in game LFG tool

### What is the expected behavior?

Use LFG tool

### What actually happened?

Message: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
Time: Wed Dec 21 19:36:23 2022
Count: 1
Stack: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/LFDFrame.lua"]:641: in function <Interface/FrameXML/LFDFrame.lua:635>
[string "@Interface/FrameXML/LFDFrame.lua"]:657: in function <Interface/FrameXML/LFDFrame.lua:647>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/LFDFrame.lua"]:437: in function `LFDQueueFrame_SetTypeSpecificDungeon'
[string "@Interface/FrameXML/LFDFrame.lua"]:418: in function `LFDQueueFrame_SetType'
[string "@Interface/FrameXML/LFDFrame.lua"]:410: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals: 

Message: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
Time: Wed Dec 21 19:39:17 2022
Count: 1
Stack: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/LFDFrame.lua"]:641: in function <Interface/FrameXML/LFDFrame.lua:635>
[string "@Interface/FrameXML/LFDFrame.lua"]:657: in function <Interface/FrameXML/LFDFrame.lua:647>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2890: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2598: in function <Interface/FrameXML/UIParent.lua:2594>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3196: in function `ShowUIPanel'
[string "@Interface/FrameXML/PVEFrame.lua"]:130: in function `PVEFrame_ShowFrame'
[string "@Interface/FrameXML/PVEFrame.lua"]:88: in function `PVEFrame_ToggleFrame'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:869: in function <Interface/FrameXML/MainMenuBarMicroButtons.lua:867>
[string "=[C]"]: ?

Locals: 

### Errors

```shell
Message: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
Time: Wed Dec 21 19:36:23 2022
Count: 1
Stack: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/LFDFrame.lua"]:641: in function <Interface/FrameXML/LFDFrame.lua:635>
[string "@Interface/FrameXML/LFDFrame.lua"]:657: in function <Interface/FrameXML/LFDFrame.lua:647>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/LFDFrame.lua"]:437: in function `LFDQueueFrame_SetTypeSpecificDungeon'
[string "@Interface/FrameXML/LFDFrame.lua"]:418: in function `LFDQueueFrame_SetType'
[string "@Interface/FrameXML/LFDFrame.lua"]:410: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals: 



Message: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
Time: Wed Dec 21 19:39:17 2022
Count: 1
Stack: Interface/FrameXML/LFDFrame.lua:641: attempt to index global 'LFGLockList' (a nil value)
[string "=[C]"]: ?
[string "@Interface/FrameXML/LFDFrame.lua"]:641: in function <Interface/FrameXML/LFDFrame.lua:635>
[string "@Interface/FrameXML/LFDFrame.lua"]:657: in function <Interface/FrameXML/LFDFrame.lua:647>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/UIParent.lua"]:2890: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2733: in function `ShowUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2598: in function <Interface/FrameXML/UIParent.lua:2594>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3196: in function `ShowUIPanel'
[string "@Interface/FrameXML/PVEFrame.lua"]:130: in function `PVEFrame_ShowFrame'
[string "@Interface/FrameXML/PVEFrame.lua"]:88: in function `PVEFrame_ToggleFrame'
[string "@Interface/FrameXML/MainMenuBarMicroButtons.lua"]:869: in function <Interface/FrameXML/MainMenuBarMicroButtons.lua:867>
[string "=[C]"]: ?

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by PetrPetr** [comment]
Got the same. But i have not ElvUI addon and other ElvUI libs.
