### ISSUE TITLE
[Retail Bug Report] Tooltip sticking to cursor when using modifier (on players only after previous fix)

### ISSUE THREAD

**Issue by KaldoranThydal** [tukui-org/ElvUI#718]
### What is the issue you are having?

Hiya, I've got an issue related to the tooltip sticking on the cursor when using modifier keys.
This was fixed a bit back for mobs etc, however it still does this when hovering over a player, using a modifier and then moving the cursor away. The tooltip remains stick to the cursor.
Hopefully this is able to be fixed like it was for mobs in a previous update?

To confirm, I've disabled all other addons except ElvUI using the debug command and this problem is only with ElvUI.

### What is the expected behavior?

Expected outcome is to hover over a player, use any modifier key and then the tooltip disappear when moving the cursor away from the player

### What actually happened?

Tooltip sticks to the cursor and only gets removed when hovering over another object, player etc to get a new tooltip

### Suggested Solution/Workaround

Whatver the fix was previously for this same issue when hovering over enemies, hopefully that can work on players too?

### Errors

```shell
No bugsack errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Is still an issue? 

Type in chat in game 
`/edebug on`

Test.  If you still have the issue, type in chat in game 
`/estatus` 
And upload a full UI screenshot (no cropping) showing the issue and the status panel. 

Test with no addons, blizzard UI - does it happen with the blizzard UI

**Comment by KaldoranThydal** [comment]
Hi, yes sadly this is still an issue I get with ElvUI only. 
Tested with no addons and the issue goes away, with only elvui enabled the issue returns. 

Since reporting the bug, I'd started using tiptac reborn for my tooltips to stop the issue for now but would love to re-enable ElvUI's tooltips if the issue can be resolved in the future.

**Comment by Luckyone961** [comment]
Can't reproduce
