### ISSUE TITLE
[TBC Bug Report] When u have open bags and u open bank, half of slots in bank are showing empty.

### ISSUE THREAD

**Issue by Mastercry** [tukui-org/ElvUI#72]
### What is the issue you are having?

If you dont have open bags and u open bank or simply reopen evrything looks fine.

### What is the expected behavior?

.

### What actually happened?

.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/issues/70
