### ISSUE TITLE
[Feature Request] allow hooks into toolkit.lua for shadow color and offset to be modified via plugins

### ISSUE THREAD

**Issue by telias82** [tukui-org/ElvUI#720]
**Is your feature request related to a problem? Please describe.**
Not really a problem but the default outline is ugly. 

**Describe the solution you'd like**
Allow plugins to hook into this to allow shadow color and offset to be modified outside of the file. 

**Describe alternatives you've considered**
Manually editing the toolkit lua file

**Comment by Repooc** [comment]
you dont need any hooks to change the color of a shadow for something... if something uses :CreateShadow(), you can just set the backdropcolor and backdropborder color to what you want.. if i recall, if that is called with the 2nd arg being true, u just have to change color of said element by referencing it and use something like :SetBackdropColor() :SetBackdropBorderColor() on that element and if no 2nd arg is passed then that frame should have like a .shadow reference you would do that on instead

**Comment by eltreum0** [comment]
> you dont need any hooks to change the color of a shadow for something... if something uses :CreateShadow(), you can just set the backdropcolor and backdropborder color to what you want.. if i recall, if that is called with the 2nd arg being true, u just have to change color of said element by referencing it and use something like :SetBackdropColor() :SetBackdropBorderColor() on that element and if no 2nd arg is passed then that frame should have like a .shadow reference you would do that on instead
> 
> there may be other ways to accomplish it but this was just going off top of my head as a lot of us have plugins that add/modify shadow colors... some with elvuis function some with our own version of it

its not CreateShadow() its the font shadow

**Comment by telias82** [comment]
I meant text shadow and text shadow color. Not just create shadow
