### ISSUE TITLE
[Retail Bug Report] Custom/Filters not working as intended.

### ISSUE THREAD

**Issue by Toasticon** [tukui-org/ElvUI#721]
### What is the issue you are having?

If I disable all filters and create a custom filter called **Hide** and add for instance **Ghost** with the **Spell ID 8326** to the **blacklist** (or any other spell for that matter) ElvUI overrides my custom filter called Hide with the ones provided by default regardless if they're used or not making custom filters nonfunctional. 

It should also be noted that the default filters, while they do allow you to "remove" spells actually doesn't do so at all. I figured I could just use the Blacklist one and modify it to my needs but that proved fruitless due to the latter problem which made me create my custom one that obviously lead me here. I can however remove spells from my custom filter so at least that is working. I'm guessing this could be solved if the default filters could be deleted, but that is obviously not a feature at the moment.

### What is the expected behavior?

A custom filter should actually work as intended and not be overridden by default ones which aren't even used to begin with.

### What actually happened?

See above.

### Suggested Solution/Workaround

Allows us to delete default filters and/or enable custom filters, or disable the function altogether if no solution can be found.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
https://imgur.com/yrYAmrj
Showing how to make a filter that u described and it working.

No, you can not delete any of the predefined filters from the Filters list.
No, you can not delete any of the spells from those lists but you can disable said spell from being checked. (example below)
https://imgur.com/a/4mKKJHh

While it can be confusing about not able to delete the default spells/list but that does not stop them from being modified to work as someone would want/expect in regards of disabling a spell from being checked as part of that list.
