### ISSUE TITLE
[Retail Bug Report] <Dracthyr HoT replicate by echo doesn't show on unitframe>

### ISSUE THREAD

**Issue by Nyrrod** [tukui-org/ElvUI#722]
### What is the issue you are having?

Dracthyr HoT replicate by the spell echo doesn't show up on the unitframe group/raid. Exemple : when i cast Echo on someone then Dream Breath or Reversion on someone else, the person with the echo buff lost the echo buff aura and should have reversion aura on the unitframe, but this one doesn't appear 

### What is the expected behavior?

When i cast Echo on someone then Dream Breath or Reversion on someone else, the person with the echo buff aura lost the echo buff aura and should have reversion aura on the unitframe

### What actually happened?

When i cast Echo on someone then Dream Breath or Reversion on someone else, the person with the echo buff aura lost the echo buff aura and the HoT doesn't appear on the unitframe, but the player has the HoT.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed in dev ty
