### ISSUE TITLE
[Retail Bug Report] Lua Error : C_timer.After

### ISSUE THREAD

**Issue by Zazou49** [tukui-org/ElvUI#723]
### What is the issue you are having?

Lua error on MM+: 

```
Message: NamePlate10:IsShown(): C_Timer.After requires a non-negative duration
Time: Fri Dec 23 21:50:39 2022
Count: 1
Stack: NamePlate10:IsShown(): C_Timer.After requires a non-negative duration
[string "=[C]"]: ?
[string "=[C]"]: in function `IsShown'
[string "@Interface/AddOns/ElvUI_FCT/core.lua"]:189: in function `Update'
[string "@Interface/AddOns/ElvUI_FCT/core.lua"]:460: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: 
```

### What is the expected behavior?

no error

### What actually happened?

error

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
u failed to read the check boxes, 4th and last as the last one.  that error appears to be from fct which is not elvui

**Comment by Repooc** [comment]
if u can reproduce this error after doing `/edebug on` just open a new ticket with the first page of error(s) u get... that way we can look into it but that error u have looked to be from simpy's addon ElvUI_FCT which he uses github for tickets for his addon
