### ISSUE TITLE
[Retail Bug Report] WOW report 

### ISSUE THREAD

**Issue by Vazziera** [tukui-org/ElvUI#725]
### What is the issue you are having?

I get errors that my interface is experiencing a lot of lua errors so I grabbed bug grabber /bug sack to help report them . 

### What is the expected behavior?

unsure.. game to run without errors?

### What actually happened?

Expected to NOT get that message :D 

### Suggested Solution/Workaround

not sure but i linked one bug report below and anotehr in the error section. 

1x FontString:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI/Core/General/Toolkit.lua"]:106: in function `Point'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/Health.lua"]:63: in function `Configure_HealthBar'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/ClassBars.lua"]:297: in function <...ElvUI/Core/Modules/UnitFrames/Elements/ClassBars.lua:283>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:184: in function `SetEnabled'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:586: in function `Update_AllFrames'
[string "@ElvUI/Core/General/Core.lua"]:1411: in function `UpdateUnitFrames'
[string "@ElvUI/Core/General/Core.lua"]:945: in function `UpdateStart'
[string "@ElvUI/Core/General/Core.lua"]:1611: in function `?'
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceDB-3.0-27/AceDB-3.0.lua"]:462: in function `SetProfile'
[string "@ElvUI_Libraries/Core/LibDualSpec-1.0-22/LibDualSpec-1.0.lua"]:170: in function `CheckDualSpecState'
[string "@ElvUI_Libraries/Core/LibDualSpec-1.0-22/LibDualSpec-1.0.lua"]:447: in function <...I_Libraries/Core/LibDualSpec-1.0/LibDualSpec-1.0.lua:420>

Locals:
(*temporary) = FontString {
 0 = <userdata>
 fontSize = 16
 SetFormattedText = <function> defined =[C]:-1
 parent = ElvUF_Player {
 }
 SetText = <function> defined =[C]:-1
 __HookedAlphaFix = true
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 UpdateTag = <function> defined @ElvUI_Libraries/Core/oUF/elements/tags.lua:688
 fontStyle = "OUTLINE"
}
(*temporary) = nil
(*temporary) = ElvUF_Player_InfoPanel {
 0 = <userdata>
 backdrop = Frame {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil

### Errors

```shell
1x FontString:SetPoint(): Usage: ("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY]
[string "=[C]"]: in function `SetPoint'
[string "@ElvUI/Core/General/Toolkit.lua"]:106: in function `Point'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/Health.lua"]:63: in function `Configure_HealthBar'
[string "@ElvUI/Core/Modules/UnitFrames/Elements/ClassBars.lua"]:297: in function <...ElvUI/Core/Modules/UnitFrames/Elements/ClassBars.lua:283>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@ElvUI_Libraries/Core/oUF/ouf.lua"]:184: in function `SetEnabled'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:586: in function `Update_AllFrames'
[string "@ElvUI/Core/General/Core.lua"]:1411: in function `UpdateUnitFrames'
[string "@ElvUI/Core/General/Core.lua"]:945: in function `UpdateStart'
[string "@ElvUI/Core/General/Core.lua"]:1611: in function `?'
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DBM-Core/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceDB-3.0-27/AceDB-3.0.lua"]:462: in function `SetProfile'
[string "@ElvUI_Libraries/Core/LibDualSpec-1.0-22/LibDualSpec-1.0.lua"]:170: in function `CheckDualSpecState'
[string "@ElvUI_Libraries/Core/LibDualSpec-1.0-22/LibDualSpec-1.0.lua"]:447: in function <...I_Libraries/Core/LibDualSpec-1.0/LibDualSpec-1.0.lua:420>

Locals:
(*temporary) = FontString {
 0 = <userdata>
 fontSize = 16
 SetFormattedText = <function> defined =[C]:-1
 parent = ElvUF_Player {
 }
 SetText = <function> defined =[C]:-1
 __HookedAlphaFix = true
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 UpdateTag = <function> defined @ElvUI_Libraries/Core/oUF/elements/tags.lua:688
 fontStyle = "OUTLINE"
}
(*temporary) = nil
(*temporary) = ElvUF_Player_InfoPanel {
 0 = <userdata>
 backdrop = Frame {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Your profile doesn't have the points.. so it appears you are either corrupted or somehow have values that are incorrect
