### ISSUE TITLE
[Retail Bug Report] Can I Mog It icon not showing on items in bags when bags module enabled in elvui.

### ISSUE THREAD

**Issue by Mooch81** [tukui-org/ElvUI#727]
### What is the issue you are having?

With both Elvui and Can I Mog It addons enabled and the Elvui bags module enabled,  the Can I Mog It icons that show either a check mark or X in the top right corner of an item in the bags is not visible.  No LUA errors or any other issues take place.  When disabling Elvui bag module, icons appear as intended.

### What is the expected behavior?

Can I Mog It checkmark/X's visible in upper right corner of item in bags.

### What actually happened?

No CIMI icons visible.

### Suggested Solution/Workaround

Could be potential strata issue between two addons so overlay not showing correctly.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
this is best reported to them as they add support to our bags and if they need something done specifically by us, they can contact us and let us know.
