### ISSUE TITLE
[Retail Bug Report] <Elvui keeps on deinstalling after relogging>

### ISSUE THREAD

**Issue by Winnion** [tukui-org/ElvUI#729]
### What is the issue you are having?

When i am logging to another character in my wow client. My elvui is gone.
When iam going to the addon folder it dissapeared.

### What is the expected behavior?

Normally the installation stays. 
It started happening after the last update.

### What actually happened?

The installation of elvui just dissapeared and i saw the wow ui.

### Suggested Solution/Workaround

Reinstalling elvui everytime you switch to another character.

### Errors

```shell
12/26 22:10:34.471  Loading Screen Disable (0)
12/26 22:10:34.471  Loading Screen : Loading : Files Read 1055 : Bytes Read 230505739 : Elapsed MS 5377 : MBytes Per Sec 40.883
12/26 22:10:34.471  Loading Screen : XML Loaded 100%
12/26 22:10:34.471  Loading Screen : World Loaded 100%
12/26 22:10:34.471  Loading Screen : Spell Loaded 100%
12/26 22:10:34.471  Spellbook : Make Models Local Begin : 124
12/26 22:10:34.471  Spellbook : Make Models Local End
12/26 22:11:13.441  Client Object Manager Destroyed
12/26 22:11:13.726  Nameplate Shutting Down
12/26 22:11:15.012  Loading Screen Disable (-1)
12/26 22:11:15.669  Loading Screen Disable (-1)
12/26 22:11:15.669  Client Destroy
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This is an issue with the Curseforge Client uninstalling addons that are not synced. There was a complaition that was uploaded with ElvUI in it and Curseforge Client flagged it as that compilation so therefore it will keep uninstalling ElvUI until the API has been resolved on Curseforge's side.
