### ISSUE TITLE
[Wrath Bug Report] Action highlight animation not working

### ISSUE THREAD

**Issue by NerlixCode** [tukui-org/ElvUI#731]
### What is the issue you are having?

After update from 13.14 to 13.15 spell highlight on action bars while hovering the spell in Spellbook doesn't work anymore.

### What is the expected behavior?

When you hover the spell in Spellbook it should be highlighted if your have the same rank of it on your bars (very useful in classic to check what spells you need to update on your bars after learning new ranks). This behavior works perfectly on 13.14 (luckily i had backup of my addons with this version so after downgrading back to it everything works as intended).

### What actually happened?

Not a single spell is highlighted on bars while hovering the same rank in Spellbook. This behavior happens after updating to 13.15 (no other addons being updated at the same time, only ElvUI)

### Suggested Solution/Workaround

According to this change in changelog for 13.15:
- **Updated LibActionButton: action highlight animation not running smoothly. (Thanks Nevcairiel).**

I would assume that this change broke highlight animation in WOTLK (didn't check it in retail).

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed in dev already

**Comment by NerlixCode** [comment]
Hey @kodewdle , i'm kinda confused, you said that this is fixed in development so i was expecting this fix to go live in next releases, and now it's already 13.20 version and it's still not working (didn't work in any version from 13.15 up to 13.17 and now we got 13.20). I understand that right now you guys probably busy with phase 2 update, but just wanna make sure that this bug won't be forgotten :)
