### ISSUE TITLE
[Retail Bug Report] ElvUI_EnhancedCurrency constantly errors

### ISSUE THREAD

**Issue by superthrust** [tukui-org/ElvUI#734]
### What is the issue you are having?

Any time I log in, regardless of any item leaving my bag, inventory, etc. I will CONSTANTLY get an error for EnhancedCurrency. Any time i try to delete that part of the addon, Tukui no longer recognizes ElvUI

### What is the expected behavior?

I expected it to not give me any errors and not be annoying

### What actually happened?

log in
open bags
move/bank/sell/buy item
ERROR ElvUI_EnhancedCurrency

the ONLY resolution is to disable THAT part of the addon, every time i log in.

### Suggested Solution/Workaround

Disabling that part of the addon via addon control panel EVERY time i log in.

### Errors

```shell
4223x ElvUI_EnhancedCurrency/Core.lua:135: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@ElvUI_EnhancedCurrency/Core.lua"]:135: in function <ElvUI_EnhancedCurrency/Core.lua:132>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
this ticket system is for elvui itself, not for plugins.  you need to contact the author(s) of that plugin via whatever means they do support for said plugin.

**Comment by Azilroka** [comment]
ElvUI_EnhancedCurrency is not part of ElvUI itself. That's a 3rd Party Plugin and I do believe it's no longer being maintained for a long time.
