### ISSUE TITLE
[Retail Bug Report] Renown summary minimap button missing

### ISSUE THREAD

**Issue by rawrkats** [tukui-org/ElvUI#738]
### What is the issue you are having?

updated to 13.16 and the renown button disappeared from minimap. Bugsack isn't reporting any errors

### What is the expected behavior?

The Dragonflight Renown status window should be available from the button that was present on the minimap. I have checked the options repeatedly and see no toggle for its visibility.

### What actually happened?

The button does not exist on the minimap anymore. I can't locate the Renown summary window.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by LunarWolf** [comment]
I have been having the same issue. I used to fix it by hiding then unhiding the garrison button for the minimap tab, that no longer works. waiting to see what happens next.

**Comment by EntelligenteEnte** [comment]
> The Dragonflight Renown status window should be available from the button that was present on the minimap. I have checked the options repeatedly and see no toggle for its visibility.

The option is called Garrison Report under Maps -> Minimap -> Minimap Buttons. (Un-)Ticking the "Hide"-button requires a reload to take effect.
