### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by bearfuzzy** [tukui-org/ElvUI#739]
### What is the issue you are having?

after cutscenes some bar buttons are not clickable, only can use the keybinds for it

### What is the expected behavior?

when leaving cutscenes i should be able to click my buttons for the ability to work

### What actually happened?

When going to the final boss of Shadowmoon Burual Ground or any cut scene, after exiting the cutscene a few of the buttons on Bar one of elvui are not clickable. i am still able press the hotkeys for the buttons to make them work. all other bars seem to work fine.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
update your elvui this was fixed recently in 13.16 and further improved by 13.17
