### ISSUE TITLE
[Feature Request] Chat > Option to hide chat channel names

### ISSUE THREAD

**Issue by AdrieAdrie** [tukui-org/ElvUI#74]
**Is your feature request related to a problem? Please describe.**
I would like my chat to look just a little bit cleaner. I mostly just used guild chat, and I can tell it's guild chat by the chat color. The channel name is unnecessary in my opinion. (I don't use global channels and trade etc.)

**Describe the solution you'd like**
Just a toggle to hide the chat channel name. 

**Describe alternatives you've considered**
Currently it is possible to shorten the channel names, but I would personally like it more if I could completely hide it.

**Additional context**
In /s no channel name is shown by default, and I think that looks really nice:
![SyMIGzZH0J](https://user-images.githubusercontent.com/50929790/141701898-aeb0ac81-dedc-46a1-bb6f-4a4d5b228dd1.png)
Fun fact, the short channel names toggle removes the "says:" from the chat message.

**Comment by kodewdle** [comment]
288681351f90c796a8b7cc089223abfd5d8e6e53 done 🧡

**Comment by AdrieAdrie** [comment]
Awesome, thank you so much!
