### ISSUE TITLE
[Feature Request] ElvUI Unitframes Target Castbar Frame Anchor

### ISSUE THREAD

**Issue by Dezpyer** [tukui-org/ElvUI#740]
**Is your feature request related to a problem? Please describe.**
Im resizing my UI (Player, Target Unitframe) based on my WA Icons.

**Describe the solution you'd like**
An option to Attach ja certain Frame in my Case castbar to a other elvui frame in my case Target Health.
WeakAuras already have this option

**Additional context**
Atm there are only these options which dont work for Cast Bar https://i.imgur.com/09XMNAA.png
In WeakAuras you can do stuff like this: https://i.imgur.com/kcTElp5.png

**Comment by Azilroka** [comment]
Detach from Frame.
