### ISSUE TITLE
[Retail Bug Report] Disintegrate ticks

### ISSUE THREAD

**Issue by chokee03** [tukui-org/ElvUI#741]
### What is the issue you are having?

Disintegrate shouldn't show a chaincasted bar when a Disintegrate cast follows a Disintegrate but not chaincasted (like moving a bit before Disintegrating again).

### What is the expected behavior?

Disintegrate should show a normal channeling bar.

### What actually happened?

Elvui shows the channel bar for the second Disintegrate as if it's chaincasted.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
thanks, fixed by https://github.com/tukui-org/ElvUI/commit/6bf55626b70ebd2015fb3a7c1b2149e145219751

**Comment by kodewdle** [comment]
had to move it actually: https://github.com/tukui-org/ElvUI/commit/6e4bd4f38d8de9fb0ffaad959012979edc87dacb
