### ISSUE TITLE
[Retail Bug Report] Parchment Remover removes "Very Rare"-text from Dungeon Journal

### ISSUE THREAD

**Issue by EntelligenteEnte** [tukui-org/ElvUI#742]
### What is the issue you are having?

While Parchment Remover is enabled, the box in the dungeon journal separating rare loot from regular loot no longer displays any text and is just a black box. So far I am only aware of such a box in the loot table for the Vault of the Incarnates raid.

### What is the expected behaviour?

It should display the "Very Rare" text just as it does when Parchment Remover is disabled.

### What actually happened?

With Parchment Remover enabled, a bordered black box is displayed, but it contains no text.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by EntelligenteEnte** [comment]
This is how it looks like with Parchment Remover enabled
![ParchmentRemoverOn](https://user-images.githubusercontent.com/57754389/210459226-9fcbf566-6eea-4406-ba64-2e52669c8ae3.png)

This is how it looks like with Parchment Remover disabled
![ParchmentRemoverOff](https://user-images.githubusercontent.com/57754389/210459230-f1fdcde0-1c5d-43f4-b784-04532446410c.png)

**Comment by Merathilis** [comment]
I just fixed that. Thanks for the Ticket <3
