### ISSUE TITLE
[Retail Bug Report] Wrong cooldown time showing on action bar

### ISSUE THREAD

**Issue by SheWildWolf** [tukui-org/ElvUI#744]
### What is the issue you are having?

Wrong cooldown time showing on action bar

### What is the expected behavior?

Expected the correct cooldown to show on the action bar

### What actually happened?

The cooldown for the ability "Overload Elemental Herb" is showing as 50 days when the actual cooldown is, at present time for me, 3 hours. The ability is on a 12 hour cooldown, however it drops by one hour per herb node harvested. After I used the ability the 12 hour timer showed correctly. After harvesting a few more nodes, the cooldown timer changed to 50 days. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
related: https://github.com/Stanzilla/WoWUIBugs/issues/47

**Comment by kodewdle** [comment]
fixed by: https://github.com/tukui-org/ElvUI/commit/631912d0f1b4c40f3d6944f6ae2db00b7ca25bce was going to see if blizz would fix it but they haven't
