### ISSUE TITLE
[Retail Bug Report] Resto Shaman's Earth Shield is not visible when "added" to Filters

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#745]
### What is the issue you are having?

Hi there,

Resto Shaman's **Earth Shield** (spellID: 974) Buff is not visible in UnitFrames when "added" to Filters.
Every other Shaman Spell like Riptide, Primordial Wave and also ANY Resto Druid, Holy Priest and Monk Buff is Visible!
Why?

### What is the expected behavior?

hmm, let me guess ;)

### What actually happened?

nothing

### Suggested Solution/Workaround

no

### Errors

```shell
no, just not visible
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You are using the spell id not the buff id.

**Comment by fubaWoW** [comment]
> You are using the spell id not the buff id.
Yeah?!

IF this would be the case, ElvUI would return the WRONG Buff ID (but it does not because it is right)!
In most cases SpellID is the BuffID, so also for Earth Shield...

![image](https://user-images.githubusercontent.com/41425685/213595966-42c232a5-a484-4269-b709-4c54d887b8c4.png)

Here also the Aura Info:
```LUA
Dump: value=UnitAura("player", 1) 
[1]="Earth Shield", 		-- name
[2]=136089, 			-- icon
[3]=9, 				-- count
[4]="Magic", 			-- dispelType
[5]=600, 			-- duration
[6]=723383.037, 		-- expirationTime 
[7]="player", 			-- source
[8]=false, 			-- isStealable
[9]=false, 			-- nameplateShowPersonal
[10]=974, 			-- spellID
[11]=true, 			-- canApplyAura
[12]=false, 			-- isBossDebuff
[13]=true, 			-- castByPlayer
[14]=false, 			-- nameplateShowAll
[15]=1, 			-- timeMod
[16]=20, 			-- attribute1
[17]=1215			-- attribute2
```

BTW You (ElvUI) also use the **SAME** ID for the Internal ``Aura Indicator (Class)``, but it works there?! ^^
![image](https://user-images.githubusercontent.com/41425685/213597992-c9e3c218-3cc0-4915-9431-b2801d5d3214.png)

What now, who to blame now?
