### ISSUE TITLE
[Retail Bug Report] Bag not sorting

### ISSUE THREAD

**Issue by xclauwe** [tukui-org/ElvUI#747]
### What is the issue you are having?

When I click on "Sort Bags", ElvUI is trying to sort the bags, but nothing happens. Sometimes, I have the message "ElvUI confused, try again", but most of the time nothing happens.

### What is the expected behavior?

I would have expected my bags to be sorted.

### What actually happened?

Everything in my bags stay where it is and nothing stacks nor goes with the items in the same category in my bag.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by xclauwe** [comment]
***@***.***

De : Azilroka ***@***.***>
Envoyé : 12 janvier 2023 17:38
À : tukui-org/ElvUI ***@***.***>
Cc : xclauwe ***@***.***>; Author ***@***.***>
Objet : Re: [tukui-org/ElvUI] [Retail Bug Report] Bag not sorting (Issue #747)


/estatus

**Comment by Repooc** [comment]
that is an in game command, not something u type in a response to github
