### ISSUE TITLE
[Feature Request] Add tag for party number (useful in Arena)

### ISSUE THREAD

**Issue by trippout** [tukui-org/ElvUI#749]
**Is your feature request related to a problem? Please describe.**
No issue, just wanting to add a feature.  Asked in Tukui discord and seems this isn't implemented in Elvui.

**Describe the solution you'd like**
I'd like a custom text for party IDs to place in UnitFrames (party 1, 2, 3 etc).  This will allow me to know who to target with my @party1, @party2, and so on macros.

**Describe alternatives you've considered**
Tried other addons for frames, but prefer elvui.

**Additional context**
Please refer to tags.lua file in the attached zip.  Lines 885-892 and line 1520 was added.  Not a developer I may be doing this wrong.
[Tags.zip](https://github.com/tukui-org/ElvUI/files/10370055/Tags.zip)

**Comment by Azilroka** [comment]
You can make additional tags using ElvUI TinkerToolbox
