### ISSUE TITLE
[Retail Bug Report] Cooldown Timer Mismatch on Player Buffs and Debuffs

### ISSUE THREAD

**Issue by Cancertron9000** [tukui-org/ElvUI#751]
### What is the issue you are having?

My player buffs and debuffs timer displays mismatch what the time actually is.

### What is the expected behavior?

when the cooldown is at 6 and 7, I would expect it to display 6 and 7 respecitvely 

### What actually happened?

When hitting 6 and 7 seconds, my buffs and debuffs display the incorrect numbers and begin counting in the other direction. The following examples are done exclusively with mongoose fury but it is not exclusive to mongoose fury and happens with all abilities.

![cooldowns](https://user-images.githubusercontent.com/122435271/211751417-14499e41-78a2-4906-a636-f557c3fe4b30.png)

I've tried looking around and couldn't find any reports of the same thing, and I couldn't find the location to change the font of the player buffs/debuffs in case it was an issue with the font pack. version is latest 13.17. 

![Screenshot 2023-01-11 081429](https://user-images.githubusercontent.com/122435271/211753778-6f1cc9bd-02de-49a3-b44f-a673234bb9c9.png)

Image attached indicates other addons are enabled, however I have tested with addons excluding the three elvUI packages and the issue still occurred. I disabled all addons including elvUI, reverting to wow's default UI, and no longer encountered the issue.

![defaultcooldowns](https://user-images.githubusercontent.com/122435271/211754195-1966144c-3d57-41b9-9b10-c98b28a86133.png)

I have also attached a whole UI image, in case this helps you either point me in the right direction, or troubelshoot on your end. 

![UI](https://user-images.githubusercontent.com/122435271/211753732-395a0e1a-8a92-4f40-875b-6c8a1195384f.png)

Thanks!

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
That is 6 on that pixel font. It's too small. You probably have it below 12 I think that one is made font.

**Comment by Cancertron9000** [comment]
> That is 6 on that pixel font. It's too small. You probably have it below 12 I think that one is made font.

I've been pulling my hair out! Thank you so much, didn't realise it was such a simple fix. Life saver :)

**Comment by Repooc** [comment]
i assume its fine then, so closing unless i misunderstood
