### ISSUE TITLE
[Retail Bug Report] Raid Frame Growth Direction not working properly

### ISSUE THREAD

**Issue by Sebastian1989101** [tukui-org/ElvUI#754]
### What is the issue you are having?

I use the option "Left and then Up" on all three Raid Frame settings. However, the Raid 1 and 2 is not going up but instead always growing down. 

### What is the expected behavior?

That the frames grow in the direction from the settings.

### What actually happened?

They always grow down. 

### Suggested Solution/Workaround

Fix it?

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type in chat in game 
`/edebug on` 
And test.  Do you still have the issue? 

If so, type in chat in game 
`/estatus` and upload a full UI screenshot (no cropping) showing both the issue and the status panel (and the settings for that raid frame)

**Comment by Repooc** [comment]
I would suggest to show a few things (in the same picture if possible).  if you hit "o" (default keybind) and show the raid groups in blizzards frame, your raid frames, and the config section for the raid that is showing (raid1, raid2, or raid3).  Prob best to do this in LFR which will have a decent amount of people for a better visual.

I would show this setup after adjusting the "Growth Direction" to different settings.
