### ISSUE TITLE
[Retail Bug Report] Dragon isle summary not showing 

### ISSUE THREAD

**Issue by SoupSammich** [tukui-org/ElvUI#757]
### What is the issue you are having?

Minimap not showing dragon isle summary I do have S&L 

### What is the expected behavior?

to show dragon isle summary 

### What actually happened?

Got on Alt character and installed elvui and set up also set up shadow and light however when I did Darth's Config my mini map is no longer showing the dragon isle summary.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
do `/edebug on` (this disables all addons but elvui)
ensure the Gassiron icon in the Maps -> minimap section in the elvui config isnt set to hide

**Comment by SoupSammich** [comment]
Thank you so much!! fix it!

**Comment by Repooc** [comment]
prob another addon messing with it (most likely not s&l as i am one of the devs for that and we dont touch that item in it)
