### ISSUE TITLE
[Retail Bug Report] 50d for long cooldowns

### ISSUE THREAD

**Issue by dagguh** [tukui-org/ElvUI#759]
### What is the issue you are having?

Put an ability with a long cooldown on an action bar (e.g. `Overload Elemental Deposit` or `Ruby Whelp Shell`). Use it. The cooldown text will improperly show `50d`. Sometimes it doesn't happen for `Overload Elemental Deposit`, but when you trigger its cooldown reduction, it jumps from `11h` to `50d`.

### What is the expected behavior?

It should show the actual cooldown remaining. Like `12h` or `1d`.
![image](https://user-images.githubusercontent.com/1194704/212758952-4e5b8bcf-1ec1-40ab-bc68-2524d94c1b32.png)

### What actually happened?

It shows `50d` cooldown text on the action bar.
![image](https://user-images.githubusercontent.com/1194704/212758892-d1db5cbb-6edc-4bd0-b620-2dfb63015528.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
What happened is you restarted your windows / computer since you used that ability.. This has been a blizzard bug for a long time.

**Comment by dagguh** [comment]
I didn't restart the PC.
Also, in the `What is the expected behavior?`, the default Blizzard UI doesn't have that bug. Does that Blizzard bug affect addons only?

**Comment by Azilroka** [comment]
Yes it only affects addons because they dont put the text on the items.. Once the os restarts.. which I know you said your pc didn't restart but even a windows update that only restarts windows itself will reset that or once your uptime gets over a week.

**Comment by dagguh** [comment]
Wow. Thanks for the explanation!
