### ISSUE TITLE
[TBC Bug Report] Microbar is Broken. This occurs in both TBC and Classic Version.

### ISSUE THREAD

**Issue by Alind777** [tukui-org/ElvUI#76]
### What is the issue you are having?

The Microbar is still broken. There was a ticket about this 11/3 but it appears to have been closed without being resolved. You can reference that ticket for screenshots.

### What is the expected behavior?

The microbar should display in a straight line with all options available.

### What actually happened?

The microbar splits and misaligns. If you disable and re-enable it it goes back into line but as soon as you hit the esc key it breaks again. A more info: If you reset the bar and then change the amount of buttons per row. Then save and exit. Then hit esc it will happen immediately. 

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
What are you settings?
