### ISSUE TITLE
[Wrath Bug Report] green overlay in bags

### ISSUE THREAD

**Issue by gmellado** [tukui-org/ElvUI#764]
### What is the issue you are having?

There is a green overlay in the bags that happens when clicking elements inside the bag or even an empty box.
I've tested:
- all addons ( elvui, dbm, atlas )
- none except elvui
- reset folders and reinstall

Even after a clean install ( no addons, only elvui ) i got this green overlay.

### What is the expected behavior?

Clean bags and no green overlay after clicking on the bag

### What actually happened?

There is a green overlay in the bags that happens when clicking elements inside the bag or even an empty box.
I've tested:
- all addons ( elvui, dbm, atlas )
- none except elvui
- reset folders and reinstall

Even after a clean install ( no addons, only elvui ) i got this green overlay.

### Errors

```shell
Message: ...nterface\AddOns\ElvUI\Wrath\Modules\Skins\Gossip.lua:47: attempt to index local 'GreetingPanel' (a nil value)
Time: Wed Jan 18 02:37:43 2023
Count: 1
Stack: ...nterface\AddOns\ElvUI\Wrath\Modules\Skins\Gossip.lua:47: attempt to index local 'GreetingPanel' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ElvUI\Wrath\Modules\Skins\Gossip.lua"]:47: in function <...nterface\AddOns\ElvUI\Wrath\Modules\Skins\Gossip.lua:39>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\Modules\Skins\Skins.lua"]:1863: in function <Interface\AddOns\ElvUI\Core\Modules\Skins\Skins.lua:1858>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1837: in function `InitializeModules'
[string "@Interface\AddOns\ElvUI\Core\General\Core.lua"]:1946: in function `Initialize'
[string "@Interface\AddOns\ElvUI\Core\init.lua"]:222: in function <Interface\AddOns\ElvUI\Core\init.lua:221>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI_Libraries\Core\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:66: in function <...UI_Libraries\Core\Ace3\AceAddon-3.0\AceAddon-3.0.lua:61>
[string "@Interface\AddOns\ElvUI_Libraries\Core\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface\AddOns\ElvUI_Libraries\Core\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:626: in function <...UI_Libraries\Core\Ace3\AceAddon-3.0\AceAddon-3.0.lua:611>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You on EU and updated for 3.4.1 and you do not have the patch.

**Comment by gmellado** [comment]
Is because of this? If so i guess tomorrow we can close it :)

**Comment by gmellado** [comment]
Closing as it is fixed now
