### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by Davejohnston5** [tukui-org/ElvUI#766]
### What is the issue you are having?

some bags are showing empty in bank when there is stuff in them 

### What is the expected behavior?

there were nobles cards and a deck in the bag . shows them in blizzard ui , but not elvui

### What actually happened?

happened with phase 2 update  updated to .18 and again to .20 , still not showing up 

disbled all addons to test and just elvui loaded

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Pimpi18** [comment]
Hi, i can confirm the bug. With ElvUI Disabled i see the missing bag with items

**Comment by Azilroka** [comment]
It is fixed in the dev version which should get a release sometime today.

**Comment by Davejohnston5** [comment]
Awesome !
