### ISSUE TITLE
[Retail Bug Report] LUA Error after Update to Version 13.20

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#767]
### What is the issue you are having?

LUA Error on Login after Update to 13.20

### What is the expected behavior?

No error on Login ;)

### What actually happened?

Error on Login ^^

### Suggested Solution/Workaround

Add this check:
``if type(func) ~= "function" then return end``
to prevent errors in function ``E:ValueFuncCall()`` in your ***Core.lua***

Looks like this and works:
```LUA
function E:ValueFuncCall()
	local hex, r, g, b = E.media.hexvaluecolor, unpack(E.media.rgbvaluecolor)
	for obj, func in pairs(E.valueColorUpdateFuncs) do
		if type(func) ~= "function" then return end
		func(obj, hex, r, g, b)
	end
end
```

### Errors

```shell
2x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:222: in function <ElvUI/Core/init.lua:221>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:538: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:743: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by fubaWoW** [comment]
ok...
it seems this "fix" will not work
because many of my Datatexts now disappeared...

**Comment by slideroh** [comment]
Same error :| Datatext + BenikUI not working cause of this

**Comment by expresstrainj** [comment]
seems to fix the issue for me

**Comment by bronze** [comment]
```Lua
Message: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Time: Wed Jan 18 10:05:51 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@Interface/AddOns/WagoAnalytics/WagoAnalytics.lua"]:72: in function <Interface/AddOns/WagoAnalytics/WagoAnalytics.lua:70>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:222: in function <Interface/AddOns/ElvUI/Core/init.lua:221>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:538: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:743: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```

**Comment by BelegCufea** [comment]
OK, this one seems to be plauseble workaround for now (thanks [fubaWoW](https://github.com/fubaWoW)) :

line 376 ->
```lua
function E:ValueFuncCall()
	local hex, r, g, b = E.media.hexvaluecolor, unpack(E.media.rgbvaluecolor)
	for obj, func in pairs(E.valueColorUpdateFuncs) do
		if type(func) == "function" then
			func(obj, hex, r, g, b)
		end
	end
end
```

**Comment by fubaWoW** [comment]
> OK, this one seems to be plauseble workaround for now (thanks [fubaWoW](https://github.com/fubaWoW)) :
yeah but it does not work properly, just the error is gone ^^
seems all "Broker" Datatexts are broken anyhow
this seems it is a "bigger" problem

**Comment by Repooc** [comment]
your plugins that provide datatexts needs to update to the changes we made in the backend of elvui

**Comment by fubaWoW** [comment]
> your plugins that provide datatexts needs to update to the changes we made in the backend of elvui

Very Nice...  
Maybe mention it anywhere if you make "Breaking Changes" to a Plugin Features?!  
I know it is very common for the ElvUI Team to just blame anyone else first, before take Responsability ^^  

It seems it is to "hard" to write in the Changelog:
``We made Changes to the Internal DataText System and Plugins maybe need to be Updated``

Or maybe add a Wiki for ElvUI, especially for other Developers, because ElvUI is already VERY Big and got many "external access points" like Skins, DataText Plugins, etc...

Also this would be very Helpful to post the following HERE if there was a Bug reported, instead of **hinding** it in middle of the code inside the ``...\ElvUI\Core\Modules\DataTexts\DataTexts.lua``
```LUA
--[[
	DT:RegisterDatatext(name, category, events, eventFunc, updateFunc, clickFunc, onEnterFunc, onLeaveFunc, localizedName, objectEvent, colorUpdate)

	name - name of the datatext (required) [string]
	category - name of the category the datatext belongs to. [string]
	events - must be a table with string values of event names to register [string or table]
	eventFunc - function that gets fired when an event gets triggered [function]
	updateFunc - onUpdate script target function [function]
	click - function to fire when clicking the datatext [function]
	onEnterFunc - function to fire OnEnter [function]
	onLeaveFunc - function to fire OnLeave, if not provided one will be set for you that hides the tooltip. [function]
	localizedName - localized name of the datetext [string]
	objectEvent - register events on an object, using E.RegisterEventForObject instead of panel.RegisterEvent [function]
	colorUpdate - function that fires when called from the config when you change the dt options. [function]
]]
```

Also that the ``colorUpdate`` function (if present) now **REQUIRES** now a ``self`` value, what was not **needed** before:

Example from you OWN ``Leech.lua`` (ElvUI Version 13.10):
```LUA
local function ValueColorUpdate(hex)
	displayString = strjoin('', '%s: ', hex, '%.2f%%|r')

	if lastPanel then OnEvent(lastPanel) end
end
E.valueColorUpdateFuncs[ValueColorUpdate] = true
```

to the ``Leech.lua`` (ElvUI Version 13.20:
```LUA
local function ValueColorUpdate(self, hex)
	displayString = strjoin('', '%s: ', hex, '%.2f%%|r')

	OnEvent(self)
end
```

seems also the ``E.valueColorUpdateFuncs[ValueColorUpdate] = true`` is no longer needed and THIS cause the error!

But no...
Better every Dev who Touches anything, first need to Reverse the Code to see what changes are made instead of just Record it in a Wiki or at least in the Changelog?! 👍

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/213606002-3f154e53-fd5a-421b-b5a2-48db1f1b1ee1.png)

**Comment by Azilroka** [comment]
> I know it is very common for the ElvUI Team to just blame anyone else first, before take Responsability or just "help" people 

At no point did we blame anyone else for the change. It is a change however that plugin authors need to update. I did 25 custom datatexts in a personal edit in less than 10 minutes. Which was done after the changes in ElvUI.

**Comment by BelegCufea** [comment]
[Azilroka](https://github.com/Azilroka) and [fubaWoW](https://github.com/fubaWoW), thank you both for some insight into the issue.

I am not a addon maker, not even a lua programmer (or native English speaker, so sorry for the plethora or spelling mistakes).

It was a deep rabbit hole to hunt down the issue. Especially when there is no mention in the error message which addon is the culprit.
Relatively easy to fix/update new `colorUpdate` in `RegisterDatatext`. But [ElvUI ChatTweaks](https://github.com/cr4ckp0t/ElvUI_ChatTweaks) had some hardcoded `E.valueColorUpdateFuncs[ValueColorUpdate] = true` outside DataText (that raised the boolean value error in ElvUI). Posted FIX for them so I hope there will be less of these reports (I saw like 3 or 4 in last 2 days) regarding this specific error.

Thanks again.

**Comment by Merathilis** [comment]
> > I know it is very common for the ElvUI Team to just blame anyone else first, before take Responsability or just "help" people
> 
> At no point did we blame anyone else for the change. It is a change however that plugin authors need to update. I did 25 custom datatexts in a personal edit in less than 10 minutes. Which was done after the changes in ElvUI.

Azil also changed it in a few other plugins. E.g. BenikUI, my MerathilisUI ...
