### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by Smuutie** [tukui-org/ElvUI#769]
### What is the issue you are having?

Bank does not show all the available bags.

### What is the expected behavior?

Bank should have all bags inside visible.

### What actually happened?

When bank is opened currently my last bag was not showing at all.
Therefore all items there were not present either.
Once I shuffled the bags the items and the bag appeared but this required me to take out bags and put them back in.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by sebastopol85** [comment]
Same happens to me, adding that i cannot see what items are in my bags, had to disable bag checkbox in ElvUI options menu
