### ISSUE TITLE
[Feature Request] Skin for Time Alert Frame

### ISSUE THREAD

**Issue by hobulian** [tukui-org/ElvUI#77]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Need skin for Time Alert Frame. I am playing wow in korean server. In korean client, play time poped up for every hours with Time Alert Frame. And it's not skinned by Elv yet. And also I cannot move it with Elv frame moving function. 

**Describe alternatives you've considered**
Skin and Frame moving function for Time Alert Frame

**Additional context**
It Shows up like this in SC.
https://imgur.com/a/4bWKhUQ

**Comment by Merathilis** [comment]
There is still a mover left :)
