### ISSUE TITLE
Bank Bags Missing

### ISSUE THREAD

**Issue by Skiiwee29** [tukui-org/ElvUI#771]
### What is the issue you are having?

Bag slot 1 (Not default bag, but first purchased bag slot) is not showing in my ElvUI bank when I open it. 

### What is the expected behavior?

Items in bank bag slot 1 show when I open my bank

### What actually happened?

Items are hidden as if the bag is not there. When disabling ElvUI it shows up fine on stock UP. Move the bag from slot 1 to another slot and those items in Slot 1 show up and the items in the slot moved to Slot 1 disappear. 

### Suggested Solution/Workaround

Not able to find one currently. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by QueenBlade** [comment]
I can confirm the issue.  I noticed that when you disable the bag portion of Elvui, that the first Bank Bag will have a purple outline, whereas the other Bank Bags are all green.  Enabling the bags, when you hover over the first bag from the right on the Bank side, nothing is showing/highlighting.  Its as if there is something in the addon telling it to ignore the first Bank Bag.
1) Purple Outline on Bank Bag 1 - Bag portion of Elvui toggled off
![image](https://user-images.githubusercontent.com/13785217/213350997-063e09df-8507-41da-a573-eb69da202d2e.png)
2) Missing preview/display of Bank Bag 1 - Bag toggled on
![image](https://user-images.githubusercontent.com/13785217/213350799-0e64e30a-f7c3-4aca-8830-29b1c3ed39a8.png)
3) Showing that Bank Bag 1 does have items in it
![image](https://user-images.githubusercontent.com/13785217/213351286-222d1187-6bae-4987-be42-343ce0c81212.png)

**Comment by kodewdle** [comment]
closing this, should be fixed by 13.21 :)  sorry for this one!

**Comment by QueenBlade** [comment]
Confirm fixed, thank you.

**Comment by Skiiwee29** [comment]
confirmed indeed. Appreciate the great work on the UI. Been using it exclusively since Cata.
