### ISSUE TITLE
[Retail Bug Report] "Move to New Window" adds a timestamp to chat messages

### ISSUE THREAD

**Issue by EntelligenteEnte** [tukui-org/ElvUI#773]
### What is the issue you are having?

When you use the "Move to new Window" context-menu option on a channel in the chat frame, all messages that have been posted in the channel so far will get new timestamps left of the original ones as they are moved to the new window. You can repeat this to add even more time-stamps. 

### What is the expected behavior?

The original timestamps are preserved but no new ones are being added when moving the messages to a separate window. (Blizzard UI does exactly that.)

### What actually happened?

Someone posted a message in a chat channel. I right-clicked on the channel name, selected the "Move to New Window"-option and all messages were moved to the newly created window where they got new timestamps left to the original ones. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
thanks for the report, should be fixed by https://github.com/tukui-org/ElvUI/commit/dc8088e2c625c67f80278d124f0884ce54adebdf
