### ISSUE TITLE
[Wrath Bug Report] throwing errors since new patch for uld

### ISSUE THREAD

**Issue by Raven427** [tukui-org/ElvUI#774]
### What is the issue you are having?

4x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:223: in function <ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

### What is the expected behavior?

expect no errors lol

### What actually happened?

i have not felt any difference in game play maybe a little laggy in Highly populated area like wintergrasp

### Errors

```shell
4x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:223: in function <ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@ElvUI_Libraries/Core/Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You wouldn't get it if you did that last step as that is a plugin causing that error.
