### ISSUE TITLE
[Retail Bug Report] Spellbook spells refuse to work until after reloadui

### ISSUE THREAD

**Issue by m4rw3r** [tukui-org/ElvUI#776]
### What is the issue you are having?

After login, opening the Spellbook and clicking any of the spells, or any of the profession skills (like mining, disenchanting, or fishing) does nothing. After a `/reloadui` they start to work, but sometimes moving between zones this breaks again and will require another reload.

### What is the expected behavior?

Spellbook spells as well as the profession skills working without having to call `/reloadui` multiple times per gaming session.

### What actually happened?

After enabling the taint-logging I found some errors which seem to be suggesting that reading/modifying `MultiActionBar_ShowAllGrids` is the cause.

### Suggested Solution/Workaround

By commenting the following two lines from `ElvUI/Core/Modules/ActionBars/ActionBars.lua` (lines 1068-1069) the spellbook starts to work again without the need to use `/reloadui` after every loading screen:

```
_G.MultiActionBar_HideAllGrids = E.noop
_G.MultiActionBar_ShowAllGrids = E.noop
```

### Errors

```shell
1/19 23:38:33.850  Execution tainted by ElvUI while reading MultiActionBar_ShowAllGrids - Interface/FrameXML/SpellBookFrame.lua:195
1/19 23:38:33.850      SpellBookFrame:Show()
1/19 23:38:33.850      Interface/FrameXML/UIParent.lua:2890 Frame:SetUIPanel()
1/19 23:38:33.850      Interface/FrameXML/UIParent.lua:2733 Frame:ShowUIPanel()
1/19 23:38:33.850      Interface/FrameXML/UIParent.lua:2598
1/19 23:38:33.850      Frame:SetAttribute()
1/19 23:38:33.850      Interface/FrameXML/UIParent.lua:3196 ShowUIPanel()
1/19 23:38:33.850      Interface/FrameXML/SpellBookFrame.lua:75 ToggleSpellBook()
1/19 23:38:33.850      TOGGLESPELLBOOK:1
1/19 23:38:34.856  Global variable ON_BAR_HIGHLIGHT_MARKS tainted by ElvUI - Interface/FrameXML/ActionButton.lua:67
1/19 23:38:34.856      ClearOnBarHighlightMarks()
1/19 23:38:34.856      Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:928
1/19 23:38:34.856  Global variable PET_ACTION_HIGHLIGHT_MARKS tainted by ElvUI - Interface/FrameXML/PetActionBar.lua:30 ClearPetActionHighlightMarks()
1/19 23:38:34.856      Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:929
1/19 23:38:35.419  Interface/FrameXML/SpellBookFrame.lua:1228 SpellBook_GetSpellBookSlot()
1/19 23:38:35.419  An action was blocked because of taint from ElvUI - CastSpell()
1/19 23:38:35.419      Interface/FrameXML/SpellBookFrame.lua:713
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by m4rw3r** [comment]
This seems to be solved in either ElvUI 13.23 and/or Retail version 10.0.5. I can't reproduce it in the current retail version.

**Comment by gwenskey** [comment]
I'm having this same issue, using BenikUI with ElvUI if that matters.

6x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'CastSpell()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `CastSpell'
[string "@FrameXML/SpellBookFrame.lua"]:713: in function <FrameXML/SpellBookFrame.lua:660>

I frequently can't manually use the disenchant button from the professions pane, or if I have to drag a spell onto my bars in combat, my spell book breaks and I have to wait till combat ends and reload.

**Comment by kodewdle** [comment]
thanks, i looked into and came to same conclusion. those lines don't appear to be needed anymore (also checked on wrath, seems okay) so fixed by https://github.com/tukui-org/ElvUI/commit/d1f1dede495ca30d46604dce8b958f545f07f45e lets hope it doesn't create a new problem down the road :)
