### ISSUE TITLE
[Classic Bug Report] Bags dont work anymore in Classic (SoM)

### ISSUE THREAD

**Issue by januks** [tukui-org/ElvUI#777]
### What is the issue you are having?

Bags dont work anymore in Classic (SoM)

### What is the expected behavior?

Should open one big bag inventory.

### What actually happened?

Opens only blizzard like bag.

### Errors

```shell
Interface\AddOns\ElvUI\Core\Modules\Bags\Bags.lua:254: attempt to perform arithmetic on local 'bankOffset' (a boolean value)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
should be fixed by https://github.com/tukui-org/ElvUI/commit/77781c785a5914c37f5d5ad922e66b1885b29328
