### ISSUE TITLE
[Wrath Bug Report] <Equip Manager Interface>

### ISSUE THREAD

**Issue by Healingbassist** [tukui-org/ElvUI#778]
### What is the issue you are having?

The equip set manager is not properly skinned.  When to choose a icon, the skin frame is not properly skinned

### What is the expected behavior?

The equip set manager is not properly skinned. 

### What actually happened?

![123](https://user-images.githubusercontent.com/119632062/213783925-16e36ca5-3af4-4213-a384-a09798b2e463.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
fixed by https://github.com/tukui-org/ElvUI/commit/bc0c6f03d6b20dadb422ea94e49988abc242afd0
