### ISSUE TITLE
[Retail Bug Report] Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)

### ISSUE THREAD

**Issue by moxm** [tukui-org/ElvUI#779]
### What is the issue you are having?

Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Count: 2

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### What is the expected behavior?

Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Count: 2

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### What actually happened?

Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Count: 2

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### Suggested Solution/Workaround

Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Count: 2

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

### Errors

```shell
Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Count: 2

Call Stack:
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function <Interface/AddOns/ElvUI/Core/General/Core.lua:1915>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...erface/AddOns/ACU/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Did not follow the checklist correctly (Checkbox's 3 & 6) and have the following duplicate tickets.

Duplicate #774 #772 #770 #767 #763
