### ISSUE TITLE
[Wrath Bug Report] Currency Icons do not fade from mouseover data text bars

### ISSUE THREAD

**Issue by Blumberg1337** [tukui-org/ElvUI#780]
### What is the issue you are having?

I have a custom datatext-"bar" that does display via mouseover when I'm outfight.
That bar also shows information about the amount of gold, silver and copper my character has. When I hover over the datatext, I also see the amount of these currencies for all my characters on the same realm and faction, as well as the sum of it.
This is expected and a standard pick from the default list for datatext options.

However, when acquiring new items or selling/destroying items from bags the error stated in the headline occurs. Also other events trigger the bug, but I didn't figure out which ones or if it happens if people of my group or around me do the same...

It has something to do with the mouseover-"fading", I guess. Infight the currency icons disappear until I get outfight again.

### What is the expected behavior?

The currency icons fade, when the datatext-"bar" fades, too.

### What actually happened?

Example: 

1. I mouseover a datatext-"bar" where the datatext "Gold" is selected as one of the datatexts
2. I remove my cursor from the "bar" stated above and the "bar" and its datatext "Gold" with its currency icons fades
3. I sell stuff at an NPC
4. Only the currency icons for gold, silver and copper from the "bar" become visible, where the datatext "Gold" is selected
5. I mouseover the "bar" again and remove my cursor from the "bar" afterwards
6. The currency icons fade away as the whole "bar" does

Step 4 should not happen and step 5 to 6 not be necessary to manually fix the issue/error.
Step 3 is just triggering step 4.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Duplicate Issue.

It's even on WoWUIBugs... It's something that was changed on Blizzard's C Side.
