### ISSUE TITLE
Datatext Tooltip Backdrop Settings not working.

### ISSUE THREAD

**Issue by RAtwood90** [tukui-org/ElvUI#781]
### What is the issue you are having?

The Databar Tooltip Backdrops aren't Transparent like the Reset i set up for my UI.

Wasn't an Issue before but it happens now with /edebug on.

Results here: https://imgur.com/a/cvowMiz

May it have to do with the DataText changes?

### What is the expected behavior?

Transparent Tooltip Backdrop.

### What actually happened?

None Transparent Tooltip Backdrop.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
It goes by the Tooltip Opacity Level. Tooltips - General
