### ISSUE TITLE
[Wrath Bug Report] Core.lua error upon login

### ISSUE THREAD

**Issue by KalmiaKamui** [tukui-org/ElvUI#783]
### What is the issue you are having?

ElvUI errors out on every log in.

### What is the expected behavior?

No error upon login.

### What actually happened?

This error happen upon every login/UI reload.  I have already disabled DataStore, but that doesn't change anything.

### Errors

```shell
174x ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@ElvUI/Core/General/API.lua"]:456: in function `?'
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You didn't do the last step in the ticket.

**Comment by KalmiaKamui** [comment]
Yes, I did.  DataStore was disabled already _when the above error occurred_.

**Comment by Azilroka** [comment]
That error above if from an ElvUI Plug in.. like ElvUI Enhanced Again.
