### ISSUE TITLE
action bars dissapeared after 10.0.5 launch

### ISSUE THREAD

**Issue by motates** [tukui-org/ElvUI#788]
### What is the issue you are having?

action bars dissapeared after 10.0.5 launch

### What is the expected behavior?

action bars not to dissapear after 10.0.5 launch

### What actually happened?

action bars dissapeared after 10.0.5 launch

### Suggested Solution/Workaround

make action bars work again after 10.0.5 launch

### Errors

```shell
no errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by sgtbaconpants** [comment]
I am experiencing the same issue.

**Comment by rogeriocamorim** [comment]
Same

**Comment by altonslayer** [comment]
there is a closed thread (because 13.21 isn't 13.20 and i guess that means the issue was fixed in 13.21, but i have 13.21 and it still persists) but it has some fixes for the issue

**Comment by gigasgaming** [comment]
i have 13.21 and mines still broke

**Comment by joaoemanuel1981** [comment]
version: 13.21

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 22:46:53 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

**Comment by gigasgaming** [comment]
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 17:53:18 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>

**Comment by joaoemanuel1981** [comment]
If they closed, it will be necessary to wait for the addon update to see the correction applied.

**Comment by Pyxl00** [comment]
I did the fix that was previously mentioned but I'm still seeing the problem of the "toggle anchor" not letting me move the micro bar around. It's not highlighted in a moveable box anymore.
![image_2023-01-24_201356626](https://user-images.githubusercontent.com/116765220/214465330-ce8930d6-5a4e-40c0-a672-9bb00954e7fe.png)
