### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Tdayin** [tukui-org/ElvUI#789]
### What is the issue you are having?

action bars dissapeared after 10.0.5 launch

### What is the expected behavior?

action bars dissapeared after 10.0.5 launch

### What actually happened?

action bars dissapeared after 10.0.5 launch

### Suggested Solution/Workaround

no work around or solutions. disabled elvui for now. please fix this issue!

### Errors

```shell
no errors rcvd.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Lame-One** [comment]
I don't think this how you fill that form out

**Comment by gigasgaming** [comment]
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 17:53:18 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>

**Comment by channswe** [comment]
The correction for the micro bar posted earlier today at:

https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/ActionBars/MicroBar.lua

Seems to resolve this issue. When loading in /edebug on, there was a single .lua error for the microbar which this resolves. After updating this file with the changes here in github, the action bars work correctly.

**Comment by Pyxl00** [comment]
I did the fix that was previously mentioned but I'm still seeing the problem of the "toggle anchor" not letting me move the micro bar around. It's not highlighted in a moveable box anymore.
image_2023-01-24_201356626

**Comment by Pyxl00** [comment]
I did the fix that was previously mentioned but I'm still seeing the problem of the "toggle anchor" not letting me move the micro bar around. It's not highlighted in a moveable box anymore.
![image_2023-01-24_201722457](https://user-images.githubusercontent.com/116765220/214465734-625573a1-e34e-4896-9f38-aa426373d90b.png)

**Comment by channswe** [comment]
@Pyxl00 I would try downloading the 13.22 version of ElvUI now available at https://www.tukui.org/download.php?ui=elvui or through the client. This includes additional updates that will hopefully resolve your issue.

**Comment by Pyxl00** [comment]
@channswe Unfortunately the new  13.23 version did not fix the movability of the micro bar. It only fixed fixed the icon problem where the blizzard skin what showing.

**Comment by channswe** [comment]
@Pyxl00 I would suggest doing /edebug on and see if you get any errors. In either case, if you do or don't, I would open up a new issue if you don't see a similar one in the list for your problem already. Note I'm not affiliated with the ElvUI team, just trying to help out :)
