### ISSUE TITLE
[Classic Bug Report] HelpFrame.lua TitleText

### ISSUE THREAD

**Issue by Londala** [tukui-org/ElvUI#79]
### What is the issue you are having?

A single LUA error pops up constantly, saying Interface\FrameXML\HelpFrame.lua is attempting to index TitleText, a nil value.

### What is the expected behavior?

No Error.

### What actually happened?

Lua error every 5 minutes. Error is in the "Errors" section.

### Errors

```shell
Message: Interface\FrameXML\HelpFrame.lua:225: attempt to index field 'TitleText' (a nil value)
Time: Wed Nov 17 13:37:08 2021
Count: 9
Stack: Interface\FrameXML\HelpFrame.lua:225: attempt to index field 'TitleText' (a nil value)
[string "=[C]"]: ?
[string "@Interface\FrameXML\HelpFrame.lua"]:225: in function <Interface\FrameXML\HelpFrame.lua:216>

Locals:
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by 1Botanica1** [comment]
Please type in chat in game 
/edebug on

Test.  Do you have the issue? 

If so, type in chat in game 
/eststus 

And upload a full UI (uncropped) screenshot showing the error and the status panel.  

Now disable all addons and test with the blizzard UI. Do you get the error?

**Comment by Londala** [comment]
Still have the issue, and still only 1 lua error.

Here's the screenshot with edebug on. Other addons disabled (except warcraft logs uploader, which is an external program):
![Screenshot (139)](https://user-images.githubusercontent.com/25884316/142274264-740827fb-3591-46b0-8bbf-5d6b6fff08e3.png)

Here is my profile, with bags and friendly nameplates disabled:
[elv_error_profile.txt](https://github.com/tukui-org/ElvUI/files/7557703/elv_error_profile.txt)

**Comment by 1Botanica1** [comment]
And now disable all addons and test with the blizzard UI

**Comment by Londala** [comment]
the issue does not occur with blizzard ui

**Comment by Azilroka** [comment]
I'm not seeing that line number exist.. So something is up.

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/142310552-1b99d436-276b-4c9e-80ad-df87bfc9ed18.png)

**Comment by Londala** [comment]
The line exists for me (fresh export)

![Screenshot (154)](https://user-images.githubusercontent.com/25884316/142472542-b4a0b003-0479-41d2-b726-879d3fb0a39b.png)

**Comment by Londala** [comment]
The issue seems to have to do with GM surveys.  I disabled the addon and completed a survey I had received (the notification was not appearing with Elv enabled), and the lua error stopped appearing.  This seems to be confirmed by the line itself.

**Comment by Azilroka** [comment]
Oh you are correct. I looked in the wrong folder. I looked at TBC not Classic.

**Comment by Azilroka** [comment]
However we dont change that OnEvent.

**Comment by kodewdle** [comment]
Checked our code for any possible conflicts, not seeing one. Will keep an eye out tho

**Comment by Luckyone961** [comment]
You just need to fill out the survey in your tickets tab of the help frame, this will fix the error - not ElvUI related. (Happens mostly after using the character unstuck service or closing a ticket)
