### ISSUE TITLE
[Retail Bug Report] Player bags not being updated until /reloadui

### ISSUE THREAD

**Issue by thekdorm** [tukui-org/ElvUI#790]
### What is the issue you are having?

Using v13.21 from GitHub .zip download.

Basically title. Initially discovered when collecting or using items but also found that simply dragging/dropping existing items in inventory to new slot reproduces a similar effect. When dropping an item in a new, empty bag slot the UI will show the item in both the original position as well as the old. This can be repeated as many times as desired. The "old" slots show a grayscale icon of the item and does not produce a tooltip on mouseover. The "true" slot shows the normal colored item icon and will produce a tooltip on mouseover.

### What is the expected behavior?

Inventory slots should be updated immediately when items are added, removed, or moved to new inventory slots.

### What actually happened?

Inventory is never updated until /reloadui.

In the attached image you can see the effect described after moving a single Draconic Vial to multiple different slots - tooltip and other interaction like drag/drop only occurs when mouseover the "true" slot, which has the colored item icon.

![image](https://user-images.githubusercontent.com/53104475/214464800-aebbec04-0518-4ac2-8056-5aeae24b063e.png)

### Suggested Solution/Workaround

/reloadui

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by eltreum0** [comment]
fixed in 13.23

**Comment by thekdorm** [comment]
Confirmed fixed in 13.23.
