### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by taytertot** [tukui-org/ElvUI#791]
### What is the issue you are having?

Action bars not appearing in or out of combat with retail update 10.0.5, there are also no anchors for them
![Screenshot_20230124_091622](https://user-images.githubusercontent.com/35478156/214465787-b5a6a2c7-2dfa-4cb4-8910-dc5c42d8daf9.png)
![Screenshot_20230124_091812](https://user-images.githubusercontent.com/35478156/214465910-6d452400-8204-47c1-a19b-bff548b1f312.png)
![Screenshot_20230124_091829](https://user-images.githubusercontent.com/35478156/214465925-ed6bf225-df73-4b19-b9cc-33644767fcba.png)

### What is the expected behavior?

Expected behaviour is for action bars to load when all are enabled

### What actually happened?

Action bars are all enabled and not loading in or out of combat with retail 10.0.5 and newest Elvui release

### Suggested Solution/Workaround

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 21:19:36 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by eltreum0** [comment]
update to 13.22
