### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Dizzyswiftz** [tukui-org/ElvUI#793]
### What is the issue you are having?

After updating to 13.23 All of my action bars are gone

### What is the expected behavior?

Usually when I update my Elvui using a clean install method, i dont lose access to my action bars. Ive reloaded multiple times and turned them on and off the blizzard UI bars work fine but look awful

### What actually happened?

I installed the new ElvUI after the 10.0.5 patch and have since lost my action bars on every character, They are toggled on but not visible, anchors included

### Suggested Solution/Workaround

I have no clue. Im just a normal user. 

### Errors

```shell
edebug gave me this error

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 21:50:23 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by eltreum0** [comment]
update to 13.23

**Comment by Dizzyswiftz** [comment]
I AM updated to 13.23 as I stated in my ticket.  Sent from Mail for Windows From: EltreumSent: Tuesday, January 24, 2023 9:53 PMTo: tukui-org/ElvUICc: Dizzyswiftz; AuthorSubject: Re: [tukui-org/ElvUI] [Retail Bug Report] <Title here> (Issue #793) update to 13.23—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Dizzyswiftz** [comment]
I AM updated to version 13.23 I said that in my ticket. I even said I started with a new install. THE ACTION BARS ARENT THERE. I gave you a debug as well.  Sent from Mail for Windows From: EltreumSent: Tuesday, January 24, 2023 9:53 PMTo: tukui-org/ElvUICc: Dizzyswiftz; AuthorSubject: Re: [tukui-org/ElvUI] [Retail Bug Report] <Title here> (Issue #793) update to 13.23—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Dizzyswiftz** [comment]
I get this LUA error when logging in as well, on a new install of 13.23 Elvui

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 22:32:31 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
