### ISSUE TITLE
[Retail Bug Report] 13.23 Action Bars Not Showing Up

### ISSUE THREAD

**Issue by Dizzyswiftz** [tukui-org/ElvUI#794]
### What is the issue you are having?

Action bars are not available and visible in Elvui 13.23

### What is the expected behavior?

For the action bars to be visible when activated, and they are. The blizzard UI action bars work fine. 

### What actually happened?

I did a fresh install of elvui for the patch update.

### Suggested Solution/Workaround

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 21:50:23 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>

### Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 21:50:23 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Dizzyswiftz** [comment]
i also get this upon login, with ANOTHER fresh install. on version 10.0.5

Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Tue Jan 24 22:32:31 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1796: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1811: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1837: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1946: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:223: in function <Interface/AddOns/ElvUI/Core/init.lua:222>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>

**Comment by Dizzyswiftz** [comment]
I am updated to the correct version, this has only happened since today's update I was fine yesterday and this morning.

**Comment by Azilroka** [comment]
This is not 13.23..

This line doesn't exist.

`Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target`

https://github.com/tukui-org/ElvUI/blob/v13.23/ElvUI/Core/Modules/ActionBars/MicroBar.lua#L356

**Comment by Dizzyswiftz** [comment]
Thats the only available download for Elvui

**Comment by Azilroka** [comment]
It exists in v13.21.

https://github.com/tukui-org/ElvUI/blob/v13.21/ElvUI/Core/Modules/ActionBars/MicroBar.lua#L356

**Comment by Dizzyswiftz** [comment]
"The current version of ElvUI is 13.23 and was updated on 2023-01-25."

**Comment by Azilroka** [comment]
Yes but you are not using it.. Show your /estatus from in-game.

**Comment by Dizzyswiftz** [comment]
Well it looks like it made it into 13.23 because after downloading and installing, This is what i get.

**Comment by Azilroka** [comment]
Show your /estatus from in-game.
