### ISSUE TITLE
[Feature Request] Add the option to not automatically delete white/gray "Junk" when emptying bags for transmog use.

### ISSUE THREAD

**Issue by Braxusz** [tukui-org/ElvUI#797]
**Is your feature request related to a problem? Please describe.**
With the new feature of white and gray items being moggable, I would like to request that we do not auto delete them for reselling and trading purposes.

**Describe the solution you'd like**
Add an option for the deletion of junk data to allow for keeping all grey and white moggable pieces, or just those that we have yet to learn.

**Describe alternatives you've considered**
Disabling the deletion entirely as to not sell pieces I need to learn.

**Additional context**
I just want to say how much I appreciate what you and your team do for the community. It truly enhances the players experience.

**Comment by Azilroka** [comment]
Disabling would be the best course of action.. Because you would learn them as you pick them up anyway.

**Comment by Azilroka** [comment]
It is by default off

**Comment by Braxusz** [comment]
> 



> Disabling would be the best course of action.. Because you would learn them as you pick them up anyway.

Disabling what, deleting of any junk items?  Sure, we learn them as we pick them up on a character that can learn them, but what about the ones we would want to send to alts to be learned? 

The idea is that I would not want to disable all functionality for the deletion of junk because it is very helpful, but simply be able to leave those things out of that removal. Make sense?

**Comment by Azilroka** [comment]
Yes, Is this a request before it actually deleted any items.. Because according to our code it supposed to be skipped I think

**Comment by Feedy88** [comment]
The thing is, you don't learn grey/white items as you pick them up because they are now BoE. Maybe this could be added to the code, don't delete grey/whites that are BoE

**Comment by Azilroka** [comment]
Yea we don't vendor whites at all. Doing a bund type check would be easy tho.

**Comment by Feedy88** [comment]
My bad, obviously whites don't get auto-sold but you got my point. Thanks for considering the feature.

**Comment by Braxusz** [comment]
> Yea we don't vendor whites at all. Doing a bund type check would be easy tho.

Thank you for reopening this and the reconsideration!

**Comment by Azilroka** [comment]
Well I'm pretty sure our code still does this.. I'll have to confirm

**Comment by Braxusz** [comment]
Your code already skips grey BoE?

**Comment by Azilroka** [comment]
It's supposed to be able to see if it's cosmetic or a transmog item

**Comment by Braxusz** [comment]
Oh ok, interesting.  How long has that been in place?  I had it delete
items just 2 days ago that were moggable.

**Comment by Feedy88** [comment]
If it's in place it seems bugged. Just yesterday sold some grey boots to NPC that were still BoE.

Let me know if I can provide any data or whatsoever.

**Comment by Azilroka** [comment]
I just got a BoE grey so that will help me fix it.

**Comment by Azilroka** [comment]
Fixed in dev..

https://github.com/tukui-org/ElvUI/commit/68c690f82bb502d562055eea9b7cf4a717746a19

**Comment by Azilroka** [comment]
It's been changed to not sell if you don't know it.. You'd have to turn off the auto vendor if you want to actively sell the items on AH
