### ISSUE TITLE
[Feature Request] <Seperate Status Textures for Raid frames/Player frames/Aura Bars >

### ISSUE THREAD

**Issue by rouge171** [tukui-org/ElvUI#8]
Currently switching the Status Bar Texture (ElvUI Settings - Unit Frames - StatusBar Texture) changes all bars to be that texture (auras, raid frames, player frames, etc). It would be a lovely cosmetic change to allow players to change each texture separately.

**Comment by Repooc** [comment]
Shadow & Light allows you to do this.  I been working on a slight rewrite of it but should be functional atm.

**Comment by Azilroka** [comment]
Declined
