### ISSUE TITLE
[Retail Bug Report] "From Me" style filter option doesn't work

### ISSUE THREAD

**Issue by Weberkraut** [tukui-org/ElvUI#80]
### What is the issue you are having?

The "From Me" option in Debuff Triggers for NamePlate Style Filters doesn't work.

### What is the expected behavior?

The style filter should only trigger when your own debuffs are applied.

### What actually happened?

The style filter applies whenever that debuff is applied, even by other players.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by anderspede** [comment]
I'm experiencing the same issue and just submitted a PR (https://github.com/tukui-org/ElvUI/pull/88) to fix it. :)

**Comment by kodewdle** [comment]
Thanks @anderspede I totally overlooked that :)
- Accepted PR <3
