### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Roskanne** [tukui-org/ElvUI#800]
### What is the issue you are having?

Hello. I don't have any actions bars toggled despite it's activated in ELVUI.

The microbar (also activated in ELVUI) is stuck on my interface as nor ELVUI, nor he new edition mode of WoW are working to set this microbar.
I can set this bar again when desactivating the microbar in ELVUI config.

This issues started on the 10.0.5 patch.

I desactivated every addon but Elvui, andnothing changed : still this issues.
I also dowloaed Ace3 to see if it works with, but nothing changes.
I deleted ELVUI and all the files (bak and so on in the folders of each character of retail and classic) and reinstalled it manually, but nothing changed.

I have ELVUI 13.23.

### What is the expected behavior?

ELVUI should have toggled my actions bars and microbar.

### What actually happened?

I don't have action bars when ELVUI is activated.

![wow edition mode no bars](https://user-images.githubusercontent.com/120311830/214726824-85941491-7382-4204-955b-f22a073a319a.jpg)
![elvui anchors missing action bars](https://user-images.githubusercontent.com/120311830/214726828-c42f03d1-9cab-46ca-ae8d-df7d723fcc9a.jpg)
![elvui bars config](https://user-images.githubusercontent.com/120311830/214726830-c827f780-c18c-4441-a64b-d850e397a8b7.jpg)

### Suggested Solution/Workaround

It seems there is a conflict between ELVUI and Blizzard UI.

### Errors

```shell
Message: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Thu Jan 26 01:30:41 2023
Count: 1
Stack: ...ce/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua:356: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...lvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/MicroBar.lua"]:356: in function `SetupMicroBar'
[string "@Interface/AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua"]:1700: in function <.../AddOns/ElvUI/Core/Modules/ActionBars/ActionBars.lua:1646>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1794: in function `CallLoadFunc'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1809: in function `CallLoadedModule'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1835: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1944: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:222: in function <Interface/AddOns/ElvUI/Core/init.lua:221>
[string "=[C]"]: ?
...
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Didn't read steps.. 2.. 4 or 6..

**Comment by Azilroka** [comment]
13.17 is not compatible with 10.0.5.. 13.23 is.. You are 5 versions out of date.

**Comment by Roskanne** [comment]
Tukui client is saying it's up to date.
I tried ti update it anyway, I still have this issue.

I uninstalled completely Elvui and reinstalled manually Elvui by downloading from the website. The website offers 13.23 Elvui, not 13.17 !

I don't know why alll of this happens.

**Comment by Azilroka** [comment]
You need to update the Tukui Client then.. you must be behind on that one also.

**Comment by Roskanne** [comment]
I already reinstalled the client, downloading the file from the website (last phrase of my precedent message, 

I deleted the whole folders of the game, and I reinstalled it this night. It was long, but ELVUI works fine now. Uff!!
I guess an old file of ELVUI was still inside the game, and fuck*d everything up.


Thanks for the help
