### ISSUE TITLE
[Retail Bug Report] New Mail indicator missing from Minimap

### ISSUE THREAD

**Issue by Feedy88** [tukui-org/ElvUI#801]
### What is the issue you are having?

When a character has new Mail (shown in Login Screen), the Icon in the minimap is not visible.

### What is the expected behavior?

When Unopened mail in mailbox, "New Mail" indicator should be visible.

### What actually happened?

"New Mail" indicator is not visible in the minimap. When clicking on `Hide` for Garrison Report, Tracking or Calendar, Mail Icon pops up (even after unhiding again)

### Suggested Solution/Workaround

I assume it could be related to the change, that Pending Work Orders are shown via the Mail Indicator as well.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
should already be addressed in the developer version, just hasnt been released yet
