### ISSUE TITLE
[Retail Bug Report] Briefcase icon 

### ISSUE THREAD

**Issue by Cionax** [tukui-org/ElvUI#803]
### What is the issue you are having?

The Briefcase icon isnt top right side anymore even if its selected in options. 

(this time i deactivated every other addon and the failure still exists)

### What is the expected behavior?

It should be in the top right corner if setted. 

### What actually happened?

The Briefcase icon isnt top right side anymore even if its selected in options.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by achidler** [comment]
I see the same behaviour.
![IMG_3039](https://user-images.githubusercontent.com/63874511/214952356-bc184f0f-1720-485b-a49a-24fd6fe92e68.jpg)

**Comment by jardragon901** [comment]
I also am seeing this happen, can reset it back to where it goes but it will go back to the left later.

**Comment by Nersunea** [comment]
I have the same Problem. If I briefly change the profile and then go back to my current one, the symbol is back on its place. But only until I logout. If I login again, no matter what character (I use the same profile on most of my characters), the symbol is on the wrong place again.

**Comment by kodewdle** [comment]
this is fixed in dev
