### ISSUE TITLE
[Retail Bug Report] ShoppingTooltip1, ShoppingTooltip1.NineSlice.TopLeftCorner, ShoppingTooltip2.NineSlice.Center

### ISSUE THREAD

**Issue by Scarah22** [tukui-org/ElvUI#805]
### What is the issue you are having?

Very occasionally, when i mouse over on usable stuff (like clicking on trinket) during combat, a tooltip appears and sticks on screen, changing some content (gear comparison) while i mouse over some buttons, npc or players and sticks on my cursor. Or it just goes blank, covering my screen on several places.

I can´t reproduce it, it just happens out of the blue sky. When i reload, it does not bother me for few days or weeks and playing w/o addons for several days is impossible for anyone. It started with prepatch, when some older UI addon stopped working and i installed Elvui - which was only new addon i installed. I was trying different sets of addons, waited for outdated addons to update and when it looks promising, it happens. I´m sorry, but i´m really desperate.  After some research how to pinpoint this window i found out it´s:

ShoppingTooltip1
ShoppingTooltip2
ShoppingTooltip1.NineSlice
ShoppingTooltip1.NineSlice.TopLeftCorner
ShoppingTooltip2.NineSlice.Center

Screenshot after boss fight starts and trinket used:
https://drive.google.com/file/d/1f3V9ukaT206I-SQyUd9QEryZYLB8MsEJ/view

With a complexity with your addon and your knowledge in LUA i hope you can help to find a culprit.

I can´t use /edebug because any reload fixes issue for unspecified time.
I can´t confirm: I have verfied my issue doesn't exist in the default UI
I can´t confirm: I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using /edebug on?

### What is the expected behavior?

no stucked window

### What actually happened?

It usually happens in raid/dungeons, sometimes outdoor. On screenshot, it was in raid after boss pull and used trinket, on my alt where i don´t have trinkets to use, but i have food, hp potion, several ports (hs, scroll etc), mounts on my bars and was questing outside, it happened too. So it´s not bound to click, just mouseover. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Evilvonbek** [comment]
@Scarah22 

1: are you using Shadow and Light? if so can you disable the toggle for "always compare" and see if issue goes away
2: if not can you run the command `/run SetCVar('alwaysCompareItems' 0); ReloadUI()` and see if that fixes it?

looks exactly like the issue I reported and then got to be reproducable in base Elvui reliably in another report

**Comment by Scarah22** [comment]
1. i´m not using Shadow and Light
2. i haven´t this issue again from report (for 5 days), but used that cvar now

can you please provide a link for your report? Or steps how you reproduced it? Thank you

**Comment by Evilvonbek** [comment]
@Scarah22 , mine is at https://github.com/tukui-org/ElvUI/issues/826
