### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by 2F4U2** [tukui-org/ElvUI#806]
### What is the issue you are having?

Trying to important a profil on ElvUI, when I loggin I have the error message:

oUF: Error: ElvUI_Libraries is setting its global to an existing name "ElvUF".

Do not know if it has anything to do with the error message, but the button "Import Profile" is missing in the Import text box, meaning I cannot import the profile.

### What is the expected behavior?

No error message and the button to import profile show be visible

### What actually happened?

nothing, can't import 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You installed incorrectly then. You have an older version of ElvUI
