### ISSUE TITLE
[Classic Bug Report] Cast bars for enemies not appearing

### ISSUE THREAD

**Issue by RayShuttlesworth** [tukui-org/ElvUI#81]
### What is the issue you are having?

The cast bars for enemies are not appearing on enemy nameplates or target unit frames while in combat. I am able to see my own casts when I select myself as target. I can see enemy cast bar on nameplates when someone else is attacking the enemy. 

ElvUI 1.53 with WoW 1.14.1 (build 41077)
Attempted with only the two ElvUI addons with no success

### What is the expected behavior?

Cast bar appears on both nameplate and target unit frame when an enemy casts

### What actually happened?

No castbar on both nameplate and target unit frame

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
This has been fixed in dev. There will be an update tomorrow I do believe.

**Comment by RayShuttlesworth** [comment]
Thanks!
