### ISSUE TITLE
Bugsack

### ISSUE THREAD

**Issue by meltymon** [tukui-org/ElvUI#810]
### What is the issue you are having?

I got a Bug Report from "Bugsack" Addon

>`72865x SharedXML/Backdrop.lua:189: attempt to index field 'backdropInfo' (a nil value)
[string "@SharedXML/Backdrop.lua"]:189: in function `GetEdgeSize'
[string "@SharedXML/Backdrop.lua"]:218: in function `SetupTextureCoordinates'
[string "@SharedXML/Backdrop.lua"]:325: in function <SharedXML/Backdrop.lua:294>
[string "=[C]"]: in function `ApplyBackdrop'
[string "@SharedXML/Backdrop.lua"]:341: in function <SharedXML/Backdrop.lua:329>
[string "=[C]"]: in function `SetBackdrop'
[string "@ElvUI/Core/General/Toolkit.lua"]:163: in function `SetTemplate'
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:789: in function <ElvUI/Core/Modules/Tooltip/Tooltip.lua:782>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@FrameXML/GameTooltip.lua"]:385: in function <FrameXML/GameTooltip.lua:382>
[string "=[C]"]: in function `GameTooltip_OnHide'
[string "*GameTooltip.xml:28_OnHide"]:1: in function <[string "*GameTooltip.xml:28_OnHide"]:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "*SharedUIPanelTemplates.xml:418_OnLeave"]:2: in function <[string "*SharedUIPanelTemplates.xml:418_OnLeave"]:1>

Locals:
self = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 template = "Transparent"
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined =[C]:-1
 GetCenterColor = <function> defined @SharedXML/NineSlice.lua:255
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetCenterColor = <function> defined =[C]:-1
 GetFrameLayoutTextureKit = <function> defined @SharedXML/NineSlice.lua:236
 SetVertexColor = <function> defined @SharedXML/NineSlice.lua:285
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 GetBorderColor = <function> defined @SharedXML/NineSlice.lua:273
 TopRightCorner = Texture {
 }
 Center = Texture {
 }
 customBackdropAlpha = 0.800000
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 0 = <userdata>
 OnLoad = <function> defined @SharedXML/NineSlice.lua:241
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopLeftCorner = Texture {
 }
 ClearBackdrop = <function> defined =[C]:-1
 GetFrameLayoutType = <function> defined @SharedXML/NineSlice.lua:232
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetBorderColor = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = "attempt to index field 'backdropInfo' (a nil value)"
defaultEdgeSize = 39
`

### What is the expected behavior?

nothing just submit

### What actually happened?

nothing just submit

### Suggested Solution/Workaround

nothing just submit

### Errors

```shell
72865x SharedXML/Backdrop.lua:189: attempt to index field 'backdropInfo' (a nil value)
[string "@SharedXML/Backdrop.lua"]:189: in function `GetEdgeSize'
[string "@SharedXML/Backdrop.lua"]:218: in function `SetupTextureCoordinates'
[string "@SharedXML/Backdrop.lua"]:325: in function <SharedXML/Backdrop.lua:294>
[string "=[C]"]: in function `ApplyBackdrop'
[string "@SharedXML/Backdrop.lua"]:341: in function <SharedXML/Backdrop.lua:329>
[string "=[C]"]: in function `SetBackdrop'
[string "@ElvUI/Core/General/Toolkit.lua"]:163: in function `SetTemplate'
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:789: in function <ElvUI/Core/Modules/Tooltip/Tooltip.lua:782>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SharedTooltip_SetBackdropStyle'
[string "@FrameXML/GameTooltip.lua"]:385: in function <FrameXML/GameTooltip.lua:382>
[string "=[C]"]: in function `GameTooltip_OnHide'
[string "*GameTooltip.xml:28_OnHide"]:1: in function <[string "*GameTooltip.xml:28_OnHide"]:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "*SharedUIPanelTemplates.xml:418_OnLeave"]:2: in function <[string "*SharedUIPanelTemplates.xml:418_OnLeave"]:1>

Locals:
self = Frame {
 BottomLeftCorner = Texture {
 }
 OnBackdropLoaded = <function> defined @SharedXML/Backdrop.lua:152
 GetBackdropColor = <function> defined @SharedXML/Backdrop.lua:390
 SetBackdropBorderColor = <function> defined =[C]:-1
 RightEdge = Texture {
 }
 template = "Transparent"
 BottomEdge = Texture {
 }
 SetBackdrop = <function> defined =[C]:-1
 GetCenterColor = <function> defined @SharedXML/NineSlice.lua:255
 GetBackdropBorderColor = <function> defined @SharedXML/Backdrop.lua:409
 GetBackdrop = <function> defined @SharedXML/Backdrop.lua:347
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetCenterColor = <function> defined =[C]:-1
 GetFrameLayoutTextureKit = <function> defined @SharedXML/NineSlice.lua:236
 SetVertexColor = <function> defined @SharedXML/NineSlice.lua:285
 SetupTextureCoordinates = <function> defined @SharedXML/Backdrop.lua:214
 GetBorderColor = <function> defined @SharedXML/NineSlice.lua:273
 TopRightCorner = Texture {
 }
 Center = Texture {
 }
 customBackdropAlpha = 0.800000
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 GetEdgeSize = <function> defined @SharedXML/Backdrop.lua:188
 0 = <userdata>
 OnLoad = <function> defined @SharedXML/NineSlice.lua:241
 TopEdge = Texture {
 }
 ApplyBackdrop = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML/Backdrop.lua:278
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 TopLeftCorner = Texture {
 }
 ClearBackdrop = <function> defined =[C]:-1
 GetFrameLayoutType = <function> defined @SharedXML/NineSlice.lua:232
 BottomRightCorner = Texture {
 }
 SetBackdropColor = <function> defined =[C]:-1
 LeftEdge = Texture {
 }
 SetBorderColor = <function> defined =[C]:-1
}
(*temporary) = nil
(*temporary) = "attempt to index field 'backdropInfo' (a nil value)"
defaultEdgeSize = 39
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You didn't read the steps at the end. You clicked them all. This is due to use TipTac and the Tooltip Skin together. You didn't do step 2 and 6. And didn't read step 4.

**Comment by meltymon** [comment]
I dont have The Tiptac addon .i just want to post the issue. thats all
