### ISSUE TITLE
Empowered spells (hold and release) not casting properly after entering instance on dragonriding mount

### ISSUE THREAD

**Issue by Akhorishaan** [tukui-org/ElvUI#811]
### What is the issue you are having?

So, latest version of elvui, edebug on, evoker, everything working great with hold and release casting for empowered spells.  However, if I enter a dungeon while riding a dragonriding mount, hold and release casting for empowered spells no longer functions until I /reloadui, the issue persists through multiple instance zonings until /reloadui is done 

Non-dragonriding mounts don't cause this issue, as well as entering the instance on foot 

Very likely a hotbar swapping issue, as the bug only occurs on empowered spells on the main bar (that switches to the dragonriding bar when you mount), empowered abilities that are not on the main swapped bar are not affected.

### What is the expected behavior?

Empowered spells on the actionbar that is swapped to the dragonriding bar while mounted with hold and release casting should cast at rank 1 empowerment when pressed and released before reaching rank 1, or at the appropriate time when pressed and held until rank 1/2/3/etc.

### What actually happened?

When entering a dungeon while on a dragonriding mount, empowered spells with hold and release casting will continue to charge until they reach the end of the cast bar, then cast, unless you press the button again.

### Suggested Solution/Workaround

The issue persists until /reloadui is done, even if you exit the instance.
You can alternatively drag the affected spell off the bar and put it back on to make it work properly again, you have to do it for both spells though.

Empowered spells that are not on the dragonriding swapped bar are not affected.

### Errors

```shell
None
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by razko** [comment]
I'm experiencing this too and have found a less annoying workaround than reloading ui - if you "pick up" the spell (like when you're reassigning spells on actionbars) and then put it back into the slot, it starts working correctly again. (I think it's because you trigger an "action slot changed" event and whatever scripts are triggered by it fix it.)

**Comment by LazinessEvolved** [comment]
Seconding this bug report. I have the same issues, although I had not connected it to dragonriding. Sometimes hold-release does the expected "tap once and it casts at rank 1 as soon as it hits that first bar" behavior. Other times it requires manual management.

**Comment by mwforrest7** [comment]
Thirding this bug report. I've also been noticing this exact issue and always do a /reload whenever starting M+ just to be safe and make sure my empowered abilities work as expected.

**Comment by jhrncar** [comment]
Same issue, happened exactly like you descriped, and /rl helped.

**Comment by DaleHuntGB** [comment]
I have had this issue quite a lot since playing my Evoker. It fixes after a reload and I have tried creating a WeakAura that will set "empowerTapControls" off, when a key starts and this seemingly has made no difference. Intrigue to know why this is happening.

**Comment by GraemeWilde** [comment]
I am also experiencing this issue. Even if it is not solved yet, I appreciate this issue report that explains to me what causes the issue and how I can work around it.

**Comment by areithropos** [comment]
It is still a thing. I had the issue too, not on every empower spell, but on some: like fire breath is bugged, but dream breath works.

**Comment by UwUway** [comment]
someone from a evoker discord I'm in talked to a dev at blizz and the dev said it was cvar corruption from elvui 
![image](https://github.com/tukui-org/ElvUI/assets/111474428/1736e6f8-65e5-4d70-8232-856c87b74d1a)

**Comment by KDederichs** [comment]
Any news on this? I'd love to use ElvUI but since I mainly play Evoker that bug is a deal breaker for me

**Comment by kodewdle** [comment]
have a fix up in dev, going to close this
