### ISSUE TITLE
Party/range frames fade away as if out of range when actually still in range.

### ISSUE THREAD

**Issue by nautylass** [tukui-org/ElvUI#812]
### What is the issue you are having?

Dead party/raid members show up as "out of range" when further away than 20 yards, despite having abilities that can ress them from up to 40 yards away. 

### What is the expected behavior?

I expect the behaviour of the fader to only fade when I'm actually out of range of said target and can NOT use the ability.

### What actually happened?

I've been running around trying to look for said dead party/raid member in a panic trying to ress them because it says out of range, despite them maybe being 25 yards away and in range of my combat ress.

### Suggested Solution/Workaround

Give the fader a custom slider so you can adjust the sweet spot of the range check.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
> Give the fader a custom slider so you can adjust the sweet spot of the range check.

this isn't possible, they API is blocked and the libraries rely on what spells you have, post your spec/talent load out and maybe the actual issue for your class can be adjusted but a slider is out of the question, it's simply not really possible as they locked down some of the API around that to prevent making fights too easy.
