### ISSUE TITLE
[Retail Bug Report] Mail icon on minimap not obeying positioning

### ISSUE THREAD

**Issue by SiJiL82** [tukui-org/ElvUI#813]
### What is the issue you are having?

Since the latest ElvUI version the mail icon on the minimap is spawning up in the top right of the screen (green circle), rather than in the top right corner of the minimap (yellow circle).
![image](https://user-images.githubusercontent.com/65114782/215273834-67b75905-8205-416f-a596-3ed38cc039b5.png)
If I go into the options and set the X or Y offset to 5, the icon jumps to where it's supposed to be, but then resets back to the top right of the screen when I next log into the character.
![image](https://user-images.githubusercontent.com/65114782/215273892-b1b53dc8-7430-4358-b786-22abbc3f6d86.png)

This is happening on all my characters (shared ElvUI profile).
![image](https://user-images.githubusercontent.com/65114782/215274029-a801a51d-71b4-461c-b8f4-24f6a38be66f.png)

### What is the expected behavior?

Mail icon should be in top right of the minimap where I've positioned it, and should stay there when relogging.

### What actually happened?

Mail icon moves to the top right of the screen.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
I'm just going to leave this open.. It's already been address in several tickets.. It's fixed in development.

**Comment by SiJiL82** [comment]
> I'm just going to leave this open.. It's already been address in several tickets.. It's fixed in development.

Apologies, I searched for issues with "mail" in and only found https://github.com/tukui-org/ElvUI/issues/801 - didn't think it was the same thing as the icon isn't missing, it's moved.
I'll close it.
