### ISSUE TITLE
[Feature Request] <Title here>

### ISSUE THREAD

**Issue by chrisistansell** [tukui-org/ElvUI#814]
Is there a way to add an overlay to the cast bar so you can do some magic and make it show who the caster is targeting?

Visual:
[Name  Castbar Health] < bottom right a box that just says the name of the target being casted on so the cosmetics aren't impacted >.<.   Would work well for the "display target" on player bars too.

Mostly saw a need for this last night in SBG when I got channeled by one of the dominator mobs that I think I could have prevented if  I knew the cast was coming. 

Figured it would help healers help react a little sooner especially if they are targeting mobs and using mouse over heals.

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/215336239-5e257c71-456b-4d33-a9bc-b460d789a7a1.png)
