### ISSUE TITLE
[Wrath Bug Report] <Same issue as #558>

### ISSUE THREAD

**Issue by saphyron** [tukui-org/ElvUI#816]
### What is the issue you are having?

100% same issue as issue #558

### What is the expected behavior?

issue #558

### What actually happened?

issue #558

### Suggested Solution/Workaround

issue #558

### Errors

```shell
issue #558
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This ticket tracker is for the ElvUI addon.. Not the Tukui Windows Client. Same as was said in issue #558
