### ISSUE TITLE
[Retail Bug Report] Mail Icon on Square Minimap Stuck Outside the Frame

### ISSUE THREAD

**Issue by rhinoceroseosei** [tukui-org/ElvUI#817]
### What is the issue you are having?

The icon indicating I have a new mail is stuck just outside the frame of my minimap now. Previously, I had it set to show in the Top Right corner, and now it constantly moves back to the wrong place. It can be put back by selecting the Top Right option again, but reloading the UI undoes this.

### What is the expected behavior?

Mail Icon stays in place

### What actually happened?

Icon is stuck outside the minimap. See images.

estatus: 
![image](https://user-images.githubusercontent.com/117486068/215290845-05fa5ba4-a31e-400c-a757-37e90b51bc70.png)

Minimap: 
![image](https://user-images.githubusercontent.com/117486068/215290850-193fca35-b7d0-4513-8d6a-73d7182a8936.png)

Settings: 
![image](https://user-images.githubusercontent.com/117486068/215290881-763950b7-221d-41b8-97c6-8fb6a6c71585.png)

Mail Icon is in the same place with no addons enabled: 
![image](https://user-images.githubusercontent.com/117486068/215290961-0771121c-b11d-4537-b9f3-2bb16b3b6c9e.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by eltreum0** [comment]
this issue is fixed in the development version of elvui
