### ISSUE TITLE
cooldown timer color 

### ISSUE THREAD

**Issue by Eulenberg** [tukui-org/ElvUI#818]
**Is your feature request related to a problem? Please describe.**
The cooldown timer color of a cd running in modified rate "state" takes priority over the "expiring" cooldown color.

**Describe the solution you'd like**
make it so the coloring of a cooldown, will always be in the "low" threshhold color when its within the "low" threshhold"

**Comment by kodewdle** [comment]
mod rate is going to have an option soon to turn it off entirely, something like this would be useless for mod rate anyways and mod rate does not specify a time in "seconds" anyway so it wouldn't go 3.9 -> 3.1 as you'd expect.
