### ISSUE TITLE
[Retail Bug Report] Ace3(external) Lib issue

### ISSUE THREAD

**Issue by lierox90** [tukui-org/ElvUI#819]
### What is the issue you are having?

ElvUI keeps reporting issue with Ace3 lib. For some reason ElvUI is using external addons libraries instead of prioritizing its own from ElvUI_Libraries, if i disable Ace3 it throws exactly same error but for Ace3 Lib loaded from internals of other addons. for example Masque or Kaliel Tracker.

using /edebug on as it turns off all other addons ofcs solves the issue of error, but thats hardly solution

### What is the expected behavior?

No LUA error

### What actually happened?

ever since ElvUI update intended for patch 10.0.5 was released i started getting this error spammed

### Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Time: Sun Jan 29 05:57:36 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:379: in function `ValueFuncCall'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:331: in function `UpdateMedia'
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:224: in function <Interface/AddOns/ElvUI/Core/init.lua:223>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: <none>
```
```


### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
its an outdated addon breaking this... u stated u did the steps for troubleshooting when u selected the option for
"I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information."

There were backend changes that some plugins use that they need to update their usage of.

**Comment by lierox90** [comment]
outdated addons doesnt answer question on why ElvUI is not using its internal library and isntead uses externals + i never stated any of addons i use are outdated, all of addons throwing this error VIA ElvUI are up-to-date to patch 10.0.5 and are not throwing said error themselves

**Comment by Azilroka** [comment]
This is not how Libraries work. Most libraries will run the most up to date version and upgrade.. We put our libraries into ElvUI_Libraries.. This has nothing to do with how libraries upgrade.. If we don't keep ours up to date and you use WeakAuras and it has a newer version of Ace3.. That version of Ace3 will succeed it. This goes for 90% of the Libraries out there.

**Comment by Azilroka** [comment]
However this error `Message: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)`
is from an outdated Plugin.

**Comment by Azilroka** [comment]
Since you have Ace3 as an External source and it's the same version that we have.. Ours will not succeed it.

**Comment by Azilroka** [comment]
ElvUI PVP Datatext is one of the main ones left that hasn't updated. Which is not part of ElvUI, ElvUI Options or ElvUI Libraries.
