### ISSUE TITLE
[Classic Bug Report] Find Treasure racial

### ISSUE THREAD

**Issue by Morynne** [tukui-org/ElvUI#82]
### What is the issue you are having?

Dwarven racial Find Treasure, when used fills all the minimap with its one big icon.

### What is the expected behavior?

while it should be just in a corner, like all other tracking spells.

### What actually happened?

For more info: the client is ru-ru local, character is dwarf hunter low level.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Morynne** [comment]
It then appeared that it was a bug with all tracking spells, that appeared when I copied WTF folder for a new character.
But I fixed it by hiding and then re-enabling minimap - tracking module.

**Comment by Nickoladze** [comment]
While the workaround above works, the problem comes back every time that I cast Find Herbs after going through a load screen or /reload

Currently using version 1.55 on Classic Era (Season of Mastery)

**Comment by Morynne** [comment]
Yes, it works like that every time. I tried en-gb client, clear Cache, WTF, re-install ElvUI, disabling all other addons: still every login, reload or loading screen, the icon of any tracking on minimap is going crazy. Only touching something in minimap - tracker options of ElvUI makes it normal until some load again.

**Comment by Azilroka** [comment]
This has been fixed in dev.
