### ISSUE TITLE
[Retail Bug Report] <Priest Action bars>

### ISSUE THREAD

**Issue by Aggiecore** [tukui-org/ElvUI#823]
### What is the issue you are having?

When I switch from Holy to Shadow,  my spells on my bars are not saving. Meaning most of my Shadow/Holy  dont transfer. I have to pull them out of my spell book each time. I checked to make sure Spec switching is enabled in profiles. 

### What is the expected behavior?

That once I set things up spell wise. I would have to redo the spells each time i switch

### What actually happened?

See above

### Suggested Solution/Workaround

I dont have one

### Errors

```shell
No errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Blizzard Issue.
