### ISSUE TITLE
[Retail Bug Report] Minimap Icon "Mail" and "Crafting Order" are misplaced on every login!

### ISSUE THREAD

**Issue by fubaWoW** [tukui-org/ElvUI#825]
### What is the issue you are having?

Minimap Icon "Mail" and "Crafting Order" are misplaced on every login!

Crafting Order is a "new" Frame from ``MinimapCluster.IndicatorFrame.CraftingOrderFrame`` and is not moveable by ElvUI.
The Mail Icon is Moveable but is linked to the CraftingOrderFrame or the IndicatorFrame anyhow and this reset the "Mail" Icon on every Login/Reload.

![image](https://user-images.githubusercontent.com/41425685/215541681-b96f7992-8706-4603-bcf1-a01d63014332.png)

### What is the expected behavior?

Minimap Icon "Mail" and "Crafting Order" are NOT misplaced on every login...

### What actually happened?

See Screenshot

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Fixed in dev

**Comment by fubaWoW** [comment]
ok, thanks!
