### ISSUE TITLE
[Retail Bug Report] Tooltips appearing when should be hidden / phantom tooltip

### ISSUE THREAD

**Issue by Evilvonbek** [tukui-org/ElvUI#826]
### What is the issue you are having?

Trinket/Item Tooltip showing during all content and also combat, will either persist even after mouseover has been removed or will stay as phantom boxes when mouseover moved away until either fade timer removes it or another item is moused over like a UF or Boss frame.

This is the phantom tooltip thing myself and several others started getting when 10.0.0 dropped, finally worked out what it was.

Click functionality is still there and not blocked by issue, is purely visual and unexpected behaviour so while annoying is not "is borked, need fixed nowwwww".

Tooltips set for hide/hide for combat/actionbars.

Issue is not present in base ElvUI, but will trigger on **any** other plugin being enabled, even one that is not the source of the toggle found to cause issue.

Can be replicated easily outside S&L active : triggers with Project being enabled even though Toggle that is causing conflict being S&L, same for WT and Eltruism

Issue is caused by enabling "Always Compare" toggle in S&L, Azil thinks it is likely to be connected to a CVar being set that something in Visibility for Tooltip doesn't like

### What is the expected behavior?

no tooltips on actionbars and/or during combat

### What actually happened?

tooltip and compare for Trinkets/items no matter what is going on including combat/boss fights
![weird frames and tips](https://user-images.githubusercontent.com/58301486/215617481-2708a578-a9b2-43b2-8447-bdf3ddd8913a.png)

### Suggested Solution/Workaround

Current workaround is to disable the "Always Toggle" function in S&L, Solution is beyond my knowledge 😺 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
We do not troubleshoot with other addons enable which the last checkbox that u selected states how to test.  Which would rule out S&L and other addons.  S&L only enables and disables a blizzard setting with that option and nothing else so that would rule out S&L... Make sure to do testing steps in the last checkbox.

**Comment by Evilvonbek** [comment]
Tracked down what specific Flag the S&L toggle was setting by checking the ElvUI.lua.bak from when it was happening before I took the toggle off.

				["tooltip"] = {
					["alwaysCompareItems"] = true,
					["showFaction"] = true,

**using a manual set of `/run SetCVar('alwaysCompareItems' 1); ReloadUI()` issue now completely reproducable in Base Elvui.**

As said in initial post Azil thought it was the way that Visibility is interacting with the CVar for it, CVar causing issue for Equipment/Trinkets on Actionbars is **`alwaysCompareItems`**.

**Issue : `alwaysCompareItems`** being set as an active CVar is causing tooltips for equipment ( loom necks for example)/Trinkets to show during combat and on actionbars even when those are set to Hide in visibility

**Expected Behaviour :** no tooltips, same as potions etc do not show

**Actual Behaviour :** when CVar is set to 1 and active, Trinkets/Looms on action bar will show tooltips including in combat

**Workaround :** disable the CVar either via Shadow and Light toggle that most folk are probably setting it by or by reversing the CVar being set manually to 1 using **`/run SetCVar('alwaysCompareItems' 0); ReloadUI()`** ; this however means no more autocompare for other frames and bags etc
![weird frames and tips](https://user-images.githubusercontent.com/58301486/215764649-fbe2a071-76b0-4f79-a13d-06efabbbf152.png)

New Toon, all addons but Elvui turned off for first login then install ran. CVar in question set normally. below are images both in and out of combat
![newcharElvuionlyplusElvuiInstallprocess](https://user-images.githubusercontent.com/58301486/215771395-7e45d93b-43d9-4c12-b3e0-ed0e875f4a23.png)

![image](https://user-images.githubusercontent.com/58301486/215771289-06fd336d-42a6-444b-9aed-4b367f683e3e.png)

**Comment by Azilroka** [comment]
I wonder how we are calling the Hide if it's reproducible in ElvUI

**Comment by Evilvonbek** [comment]
followup with some testing in stock Blizz, seems the issue may be with the compare tooltips overriding whatever is used to hide the normal tooltips

Context : Stock Blizz

image 1 : `alwaysCompareItems` = 0 ( inactive ), trinket on bar
![image](https://user-images.githubusercontent.com/58301486/216319677-0744415c-e621-4f5d-9cb9-dc45a040a619.png)

image 2 : `alwaysCompareItems` = 1 ( active ), same trinket on bar
![image](https://user-images.githubusercontent.com/58301486/216319962-d5cca777-b317-4362-84a1-1f1095aa1343.png)

same behavious with both the loom neck with Use ability and the other passive "on kill" trinket where without CVar set it shows the tooltip and with it set it shows all three, also does the whole phantom thing at times in test with stock blizz plus CVar.

Ignore the look of the tooltips, I'm using Eltriums Glues for the main menu etc
