### ISSUE TITLE
[Retail Bug Report] <Character pannel - Stats squished into eachother>

### ISSUE THREAD

**Issue by weinTv** [tukui-org/ElvUI#829]
### What is the issue you are having?

Character pannel - The Stats part of the character pannel is all squished into itself and therefore its unreadable 

![image](https://user-images.githubusercontent.com/124174439/216079038-ed3f7c8a-16bb-437f-ad84-bd95752d31be.png)

### What is the expected behavior?

Its supposed to be normaly readable

### What actually happened?

Its supposed to be normaly readable

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You didn't disable other addons using /edebug on.

You didn't read step 4 or 6.
