### ISSUE TITLE
[Retail Bug Report] Hiding party frames in arena with @arena1 condition

### ISSUE THREAD

**Issue by tcneuen** [tukui-org/ElvUI#831]
### What is the issue you are having?

I'm attempting to hide the party frames when I'm using GladiusEx in arena. To accomplish this I've set visibility conditional to `[@raid6,exists][nogroup][@arena1,exists] hide;show`., but despite this being set and a test macro working as I would expect, the party frames still show up in arena. 

### What is the expected behavior?

The visibility to respect `[@arena1,exists]` conditional and hide the party frames.

### What actually happened?

Party frames show, no matter the tinkering seems to pretty much ignore the `@arena1` condition. 

### Suggested Solution/Workaround

N/A

### Errors

```shell
N/A
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You are in a group at that point. So it will be shown.

**Comment by tcneuen** [comment]
Aren't the conditionals ORs when separated by brackets?

meaning `[@raid6,exists][nogroup][@arena1,exists]` would equate to, hide when any are true:
- raid 6 member exists
- not in any group
- arena 1 exists

**Comment by Azilroka** [comment]
pretty sure it's executed in order so you are ina group so it will be shown.. arena1 is the opposite team by the way not your group

**Comment by tcneuen** [comment]
I don't think that is correct, I tested with with a this macro to be sure
`/target [@raid6,exists][@arena1,exists][nogroup]Wadsworth;notarget`

- Solo: Targeted Wadsworth
- Group: No Target
- Arena: Targeted Wadsworth 

In normal macros that conditions work as I'd expected

**Comment by Azilroka** [comment]
Well if that's working as expected then the visibility field would work as expected.

**Comment by Azilroka** [comment]
RegisterStateDriver(Header, 'visibility', visibility)

**Comment by Azilroka** [comment]
https://wowpedia.fandom.com/wiki/SecureStateDriver

**Comment by tcneuen** [comment]
That's why it surprised me as well. Any good way for me to test it further?
