### ISSUE TITLE
[Wrath Bug Report] Lua Error when Clicking on Chat to Copy

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#833]
### What is the issue you are having?

16x ElvUI/Core/Modules/Chat/Chat.lua:1493: attempt to call method 'SetChatEditBoxmsg' (a nil value)
[string "@ElvUI/Core/Modules/Chat/Chat.lua"]:1493: in function `fun'
[string "@WIM/Sources/Hooks.lua"]:105: in function <WIM/Sources/Hooks.lua:102>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetHyperlink'
[string "@FrameXML/ItemRef.lua"]:362: in function <FrameXML/ItemRef.lua:1>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface_WrathBlizzard_CombatLog/Blizzard_CombatLog.lua"]:3516: in function <...athBlizzard_CombatLog/Blizzard_CombatLog.lua:3458>
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML/ChatFrame.lua"]:3768: in function <FrameXML/ChatFrame.lua:3767>
[string "=[C]"]: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
data = "cpl:1"
chatID = "1"
chat = ChatFrame1 {
 SetJustifyV = <function> defined =[C]:-1
 RefreshIfNecessary = <function> defined =[C]:-1
 OnPostShow = <function> defined =[C]:-1
 SetScript = <function> defined =[C]:-1
 CalculateLineAlphaValueFromTimestamp = <function> defined =[C]:-1
 isLayoutDirty = false
 tellTimer = 514329.863000
 isDisplayDirty = false
 GetFading = <function> defined =[C]:-1
 IsTextCopyable = <function> defined =[C]:-1
 shouldFadeAfterInactivity = true
 SetIndentedWordWrap = <function> defined =[C]:-1
 GetJustifyV = <function> defined =[C]:-1
 SetFont = <function> defined =[C]:-1
 GetMaxLines = <function> defined =[C]:-1
 font = "Interface\Addons\Details\fonts\Accidental Presidency.ttf"
 GetIndentedWordWrap = <function> defined =[C]:-1
 buttonSide = "left"
 GetFont = <function> defined =[C]:-1
 SetMaxLines = <function> defined =[C]:-1
 CalculateSelectingCharacterIndicesForVisibleLine = <function> defined =[C]:-1
 PageUp = <function> defined =[C]:-1
 RefreshDisplay = <function> defined =[C]:-1
 SetFontObject = <function> defined =[C]:-1
 textIsCopyable = false
 SetOnScrollChangedCallback = <function> defined =[C]:-1
 CalculateNumVisibleLines = <function> defined =[C]:-1
 overrideFadeTimestamp = 0
 MarkDisplayDirty = <function> defined =[C]:-1
 GetMessageInfo = <function> defined =[C]:-1
 GetOnScrollChangedCallback = <function> defined =[C]:-1
 AtTop = <function> defined =[C]:-1
 GetFontObject = <function> defined =[C]:-1
 fontStringPool = <table> {
 }
 CanEffectivelyFade = <function> defined =[C]:-1
 OnPreSizeChanged = <function> defined =[C]:-1
 OnPostMouseUp = <function> defined =[C]:-1
 GetSpacing = <function> defined =[C]:-1
 OnPreLoad = <function> defined =[C]:-1
 SetSpacing = <function> defined =[C]:-1
 name = "General"
 CalculateLineSpacing = <function> defined =[C]:-1
 AddMessage = <function> defined @ElvUI/Core/Modules/Chat/Chat.lua:902
 InitializeFontableFrame = <function> defined =[C]:-1
 GetShadowColor = <function> defined =[C]:-1
 isUninteractable = false
 SetOnTextCopiedCallback = <function> defined =[C]:-1
 fontStyle = "NONE"
 copyButton = ElvUI_CopyChatButton1 {
 }
 AcquireFontString = <function> defined =[C]:-1
 TransformMessages = <function> defined =[C]:-1
 SetShadowColor = <function> defined =[C]:-1
 buttonFrame = ChatFrame1ButtonFrame {
 }
 HasFontObject = <function> defined =[C]:-1
 isDocked = 1
 GetOnTextCopiedCallback = <function> defined =[C]:-1
 SetFading = <function> defined =[C]:-1
 OnPostHide = <function> defined =[C]:-1
 alternativeDefaultLanguage = "Orcish"
 OldAddMessage = <function> defined =[C]:-1
 isInitialized = 1
 ScrollByAmount = <function> defined =[C]:-1
 GetInsertMode = <function> defined =[C]:-1
 SetTimeVisible = <function> defined =[C]:-1
 hasOwnFontObject = true
 scriptsSet = true
 Clear = <function> defined =[C]:-1
 oldAlpha = 0
 channelList = <table> {
 }
 GetTimeVisible = <function> defined =[C]:-1
 MarkLayoutDirty = <function> defined =[C]:-1
 SetTextCopyable = <function> defined =[C]:-1
 BackFillMessage = <function> defined =[C]:-1
 UnpackageEntry = <function> defined =[C]:-1
 FontStringContainer = Frame {
 }
 SetShadowOffset = <function> defined =[C]:-1
 messageTypeList = <table> {
 }
 flashTimer = 0
 timeVisibleSecs = 100
 PackageEntry = <function> defined =[C]:-1
 MakeFontObjectCustom = <function> defined =[C]:-1
 fontObject = table: 0000024E4401BB80 {
 }
 SetInsertMode = <function> defined =[C]:-1
 mouseInTime = 0
 ScrollDown = <function> defined =[C]:-1
 zoneChannelList = <table> {
 }
 SetScrollOffset = <function> defined =[C]:-1
 onDisplayRefreshedCallback = <function> defined =[C]:-1
 insertMode = 2
 ResetSelectingText = <function> defined =[C]:-1
 hasBeenFaded = true
 mouseOutTime = 0
 defaultLanguage = "Orcish"
 styled = true
 GetTextColor = <function> defined =[C]:-1
 fontSize = 14
 ResetAllFadeTimes = <function> defined =[C]:-1
 tab = ChatFrame1Tab {
 }
 GatherSelectedText = <function> defined =[C]:-1
 GetNumVisibleLines = <function> defined =[C]:-1
 ScrollUp = <function> defined =[C]:-1
 0 = <userdata>
 IsSelectingText = 

### What is the expected behavior?

No lua error, and chat line that was clicked on goes into input text box so it can be copied.

### What actually happened?

Lua error. Nothing else.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Fixed in Dev
