### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by OGWalksoft** [tukui-org/ElvUI#834]
### What is the issue you are having?

this one char cant socket gems and gets these errors

### What is the expected behavior?

able to socket gems

### What actually happened?

nothing

### Errors

```shell
Message: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Time: Sun Feb  5 14:19:13 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
[string "@Interface/AddOns/ElvUI/Core/General/Core.lua"]:1949: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:224: in function <Interface/AddOns/ElvUI/Core/init.lua:223>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>

Message: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)
Time: Sun Feb  5 14:19:15 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/General/Core.lua:379: attempt to call local 'func' (a boolean value)

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
not an error with elvui, its from one of your addons/plugins that adds a datatext that they never updated to reflect our changes.
when you posted a ticket, make sure to read and follow the things u checked as it has been reported in the ticket system and doing the last checkbox would have shown no error with just elvui (which the commands would ensure if u had done them)

**Comment by OGWalksoft** [comment]
I did the last part, and the error remained.  thanks for assuming I cant read

**Comment by Repooc** [comment]
do the `/edebug on`, then do `/estatus` and share a picture of that window that pops up with estatus command and the error in the same picture (as i am sure u wont get the error if u do this)

**Comment by Repooc** [comment]
#819 #783 #779 #774 #772 #770 #767 #763
and i didnt assume you cant read, i assume you didnt read considering these were the first few tickets with ur exact error

**Comment by Azilroka** [comment]
> I did the last part, and the error remained. thanks for assuming I cant read
> 
> And rather than be helpful, you chose immature and snarky.
> 
> Well done, my troll, well done

No sir, You disabled all addons that didn't have ElvUI in thier name.. Which is not the same thing as `/edebug on` does.

ElvUI PvP Honor Datatext is not part of ElvUI.
ElvUI Enhanced Again is not part of ElvUI.
ElvUI WindTools is not part of ElvUI.

Those are 3rd party plugins.
