### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by mikemaring** [tukui-org/ElvUI#836]
### What is the issue you are having?

I received a LUA error when clicking a line in my main chat box.

### What is the expected behavior?

It should pop open the line so it can be copy/pasted

### What actually happened?

LUA error occurred

### Errors

```shell
Message: Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1493: attempt to call method 'SetChatEditBoxmsg' (a nil value)
Time: Sun Feb  5 19:56:00 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1493: attempt to call method 'SetChatEditBoxmsg' (a nil value)
[string "=[C]"]: in function `SetChatEditBoxmsg'
[string "@Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua"]:1493: in function `func'
[string "@Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua"]:1532: in function <Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1528>
[string "=[C]"]: in function `SetHyperlink'
[string "@Interface/FrameXML/ItemRef.lua"]:754: in function `ItemRefSetHyperlink'
[string "@Interface/FrameXML/ItemRef.lua"]:392: in function <Interface/FrameXML/ItemRef.lua:7>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_CombatLog/Blizzard_CombatLog.lua"]:3534: in function <...ace/AddOns/Blizzard_CombatLog/Blizzard_CombatLog.lua:3475>
[string "=[C]"]: in function `SetItemRef'
[string "@Interface/FrameXML/ChatFrame.lua"]:4036: in function `ChatFrame_OnHyperlinkShow'
[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1: in function <[string "*ChatFrame.xml:15_OnHyperlinkClick"]:1>
[string "=[C]"]: ?

Locals:
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
been addressed and fixed already in the dev build... will be in next release
