### ISSUE TITLE
[Retail Bug Report] <Onslaught cast intermittently working>

### ISSUE THREAD

**Issue by zabron05** [tukui-org/ElvUI#837]
### What is the issue you are having?

The Fury warrior ability - Onslaught will only work sporadically.  The ability will be off of cd, will be in range and actively attacking boss with other melee abilities, and onslaught will not cast.  Pressing butting 20-30 times will not have it go off.  Swapping to wowui bars, the ability work work without issues.

### What is the expected behavior?

The ability works when pressed.

### What actually happened?

The ability would not cast.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
This is a blizzard issue.
