### ISSUE TITLE
[Classic Bug Report] <Buf text do not editable>

### ISSUE THREAD

**Issue by jack-fdrv** [tukui-org/ElvUI#84]
### What is the issue you are having?

I cant change size of the text on my target bufs, the same for groups bugs etc.

### What is the expected behavior?

I can change the size of text [Here it the video explnation](https://youtu.be/uEcG9KGmRUk)

### What actually happened?

nothing

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
The Buff text that you are trying to change has no bearing on the Cooldown Text you are trying to change that is in Cooldown Text section.
