### ISSUE TITLE
[Feature Request] <addon grouping system>

### ISSUE THREAD

**Issue by fsdraconis** [tukui-org/ElvUI#841]
**Is your feature request related to a problem? Please describe.**
< I am a bit of an altoholic and I use a large amount of addons. It is frequently a problem when it comes to dealing with some of my addons getting updated that they all get enabled on all of my characters. >

**Describe the solution you'd like**
< It would be really neat if there was a way to create addon profile tabs to the left of the addon list (UI interface idea). Each of these tabs could have groupings of specific addons once plugged into it, would turn on or off all of the addons in that grouping with a single click. Instead of manually going through everything. Sure we would have to click all of the relevant sections of each addon to enter them into a profile when creating/editing the profile/grouping button. But after that, you could go from character to character and with a lot less button pressing elegantly change addon selection. For me, I just see this as a way to enable/disable specific addon boxes and not loading a set profile for all addons. This means you could have one button to disable/enable addons while another button changes other options on and or off. >

**Describe alternatives you've considered**
< In my mind I just see this as simple as creating a profile button with a short name that sits to the left of our addon list frame, and then a +/-/~ toggle button next to every addon box. This means you could disable parts of an addon you don't use with the profile button. While also enabling the parts you do want. Then you could create another set for raiding for instance. The ~ mode would ignore that addon setting. >

**Additional context**
< I'm not very good with artwork. But I hope I have communicated enough information to envision something here. >

**Comment by Azilroka** [comment]
ProjectAzilroka - stAddOnManager or Addon Control Panel does this already.

**Comment by fsdraconis** [comment]
stAddOnManager is labeled as abandoned and has not been updated since 2012. Addon Control Panel appears its creator has passed away and has not been updated since November of last year.

**Comment by Azilroka** [comment]
The one in ProjectAzilroka isn't abandoned.. The original project was abandoned by I have persmission to continue it.
