### ISSUE TITLE
[Feature Request] Add a Tag for showing offline time in Party/Raid

### ISSUE THREAD

**Issue by Wilano** [tukui-org/ElvUI#843]
**Is your feature request related to a problem? Please describe.**
No, it's just missing.

**Describe the solution you'd like**
If a party member goes offline (e.g. in a M+ Key), you should have to see the time since he's gone offline.

I'm using my own code snippet to use a tag ('Offlinetimer') for several months. But on every update of the addon I have to reimport the snippet.
Here is the snippet (ElvUI/Core/General/Tags.lua) under Code line 980:
```lua
.....

local unitStatus = {}
ElvUF.Tags.OnUpdateThrottle['offlinetimer'] = 1
ElvUF.Tags.Methods['offlinetimer'] = function(unit)
	if not UnitIsPlayer(unit) then return end

	local guid = UnitGUID(unit)
	local status = unitStatus[guid]
if not UnitIsConnected(unit) then
		if not status or status[1] ~= 'Offline' then
			unitStatus[guid] = {'Offline', GetTime()}
		end
	else
		unitStatus[guid] = nil
	end

	if status ~= unitStatus[guid] then
		status = unitStatus[guid]
	end

	if status then
		local timer = GetTime() - status[2]
		local mins = floor(timer / 60)
		local secs = floor(timer - (mins * 60))
		return format('%s (%01.f:%02.f)', L[status[1]], mins, secs)
	end
end

.....
```

**Describe alternatives you've considered**
Maybe a better code?

**Additional context**
I think everything has been said

**Comment by Repooc** [comment]
if you want to make your own tags that stick, use azilrokas addon ElvUI TinkerToolbox which u can make ur own custom tags.
