### ISSUE TITLE
[Retail Bug Report] Datatexts error on 13.25

### ISSUE THREAD

**Issue by lebagvondouche** [tukui-org/ElvUI#844]
### What is the issue you are having?

Getting an error an no datatexts are working.

### What is the expected behavior?

The datatexts should work as usual.

### What actually happened?

Updated from 13.24 to 13.25 and the datatexts stopped working.

### Errors

```shell
2x ...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:505: bad argument #2 to 'max' (number expected, got nil)
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:505: in function `UpdatePanelInfo'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:620: in function <...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:607>
[string "=[C]"]: in function `LoadDataTexts'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:838: in function `?'
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Masque/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@TomTom/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...aceTomTom/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = 15.999998
(*temporary) = nil
(*temporary) = "number expected, got nil"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by thematrixincendies** [comment]
Same issue

**Comment by Azilroka** [comment]
It's fixed in dev should be a hot fix going out soon.

**Comment by jimmis95** [comment]
Is the ELVUI discontinued or what the heck? This issue has been going on for 2 days now yet still noone's fixing it

**Comment by Azilroka** [comment]
> 

So you assume that ElvUI is discontinued since a fix hasn't been pushed out yet. Yet it HAS been fixed in the development branch.

**Comment by Merathilis** [comment]
> Is the ELVUI discontinued or what the heck? This issue has been going on for 2 days now yet still noone's fixing it

dude, just relax.. and if it would take up to 3 weeks. We all have also other stuff to do and our own projects.

**Comment by thematrixincendies** [comment]
> Is the ELVUI discontinued or what the heck? This issue has been going on for 2 days now yet still noone's fixing it

Just downgrade to 13.24 or clone the development branch.

**Comment by dewson8** [comment]
> > Is the ELVUI discontinued or what the heck? This issue has been going on for 2 days now yet still noone's fixing it
> 
> Just downgrade to 13.24 or clone the development branch.

I'm not seeing the option to download 13.24 anywhere. Where would I be able to get it?

**Comment by Azilroka** [comment]
https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip
