### ISSUE TITLE
[Wrath Bug Report] Names disappear from raid unit frames

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#847]
### What is the issue you are having?

On latest from Tuk updater. 

2x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'PartyMemberFrame1:Hide()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Hide'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1265: in function <ElvUI/Core/Modules/UnitFrames/UnitFrames.lua:1247>
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1354: in function `DisableBlizzard'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:1110: in function `UpdateAllHeaders'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:618: in function `Update_AllFrames'
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:893: in function `?'
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:114: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:24: in function <...ventory/Libs/CallBackHandler/CallbackHandler-1.0.lua:20>
[string "@ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-8.lua"]:59: in function `Fire'
[string "@ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:120: in function <...rkInventory/Externals/Ace3/AceEvent/AceEvent-3.0.lua:119>

### What is the expected behavior?

No issue.

### What actually happened?

Names disappear from raid unit frames.

![image](https://user-images.githubusercontent.com/55365231/217683410-254a2798-529d-4a9e-8cb0-097401440d8f.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
Reload helps, but looks like when you add or remove people from the raid the issue comes back.

**Comment by 1Botanica1** [comment]
You have other addons enabled in that taint 

Type in chat in game 
`/edebug on`

test. Do you still have the issue?  If so, type in chat in game `/estatus` and upload a FULL ui screenshot (no cropping) showing both the issue and the status panel.

**Comment by Gogo1951** [comment]
Agreed, this was a taint issue. Found the issue with another add-on a few weeks ago.
