### ISSUE TITLE
[Classic Bug Report] <Lvl do not show some times on my target>

### ISSUE THREAD

**Issue by jack-fdrv** [tukui-org/ElvUI#85]
### What is the issue you are having?

Details here https://youtu.be/AKXuUWtYTYc

### What is the expected behavior?

I can view lvl

### What actually happened?

Do not show lvl

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
Because you are using [smartlevel] tag. You will need to change that to [level]
