### ISSUE TITLE
[Retail Bug Report] Datatext Lua issue

### ISSUE THREAD

**Issue by rawrkats** [tukui-org/ElvUI#852]
### What is the issue you are having?

my datatexts panels will sometimes not load, and i have to do a reload even after logging in to get them to show properly. Using mMediatag addon, but the bugsack is reporting a core Elvui error with Datatexts

### What is the expected behavior?

The datatexts display without issue/bugs 

### What actually happened?

They disappear.

### Suggested Solution/Workaround

sometimes a reload will work, sometimes it will not. I have tried clearing the ElvUI SV file for a specific character and 'starting fresh' but the issue still happens.

### Errors

```shell
1x ...ceElvUI/Core/Modules/DataTexts/DataTexts.lua:505: bad argument #2 to 'max' (number expected, got nil)
[string "=[C]"]: ?
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:505: in function `UpdatePanelInfo'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:620: in function `LoadDataTexts'
[string "@ElvUI/Core/Modules/DataTexts/DataTexts.lua"]:838: in function `?'
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...dia/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@SharedMedia/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = 16.000164
(*temporary) = nil
(*temporary) = "number expected, got nil"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Update.
