### ISSUE TITLE
[Wrath Bug Report] Missing configuration option for auto self cast

### ISSUE THREAD

**Issue by Ianni** [tukui-org/ElvUI#853]
### What is the issue you are having?

Since the ulduar patch the behavior when casting on targets that are out of range changed. 
Previously this would just cancel the cast with the appropriate message, but now the cast uses the player as the target. 

This can lead to "undesired" behavior e.g. casting bop on a target that is moving out of range at this moment.
The default interface got a new configuration setting for this behavior (see the attached screenshot), but this option is missing from elvui at the moment.
![Screenshot 2023-02-11 012055](https://user-images.githubusercontent.com/471066/218225818-088a0d86-6775-4c84-a047-74c799ffc911.png)

### What is the expected behavior?

Please provide the same configuration option in elvui.

### What actually happened?

see above

### Suggested Solution/Workaround

Disable Elvui, set the options and enable elvui again.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
If you look in that same section you should see an ElvUI button that will take you to the ActionBar config which holds those settings.

**Comment by Ianni** [comment]
Thank you, I have found the option in the acction bar settings. 

But the button you mentioned is missing for me 
![Screenshot 2023-02-11 130403](https://user-images.githubusercontent.com/471066/218256960-40ad562c-f0b2-45a8-84d9-ee8651a0231b.png)

Also, there is no Info Tooltip for the option in elvui, not sure if this is intended.
