### ISSUE TITLE
[Retail Bug Report] Raid Frames can blank out in combat and prevent the use of clicking on them or using mouseover macros

### ISSUE THREAD

**Issue by Aldori15** [tukui-org/ElvUI#854]
### What is the issue you are having?

Raid frames will sometimes disappear in combat when a group party member is added or leaves the group.  This can also happen if you right click your player portrait, then click Edit Mode while in combat.  The raid frames will become inactive and you can no longer click them until you perform a /reload or exit combat.  

This can be cumbersome as a healer during a raid fight.

**Please Note:** I am using the ElvUI addon, but have ElvUI party and raid frames disabled.  I am using Blizzard party and raid frames.  But in the error below, you can see it is being caused due to Elvui trying to call the protected function 'PartyFrame:Raise()'

### What is the expected behavior?

Raid frames should remain active and not disappear or become unclickable during combat.

### What actually happened?

The raid frames became unclickable during combat.

### Suggested Solution/Workaround

Exiting combat or typing /reload

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'PartyFrame:Raise()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `Raise'
[string "@FrameXML/EditModeManager.lua"]:1605: in function `RefreshPartyFrames'
[string "@FrameXML/EditModeManager.lua"]:1518: in function `OnEditModeEnter'
[string "@FrameXML/EditModeManager.lua"]:172: in function `EnterEditMode'
[string "@FrameXML/EditModeManager.lua"]:196: in function <FrameXML/EditModeManager.lua:194>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2915: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2719: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2623: in function <FrameXML/UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3225: in function `ShowUIPanel'
[string "@FrameXML/UnitPopupButtons.lua"]:481: in function `OnClick'
[string "@FrameXML/UnitPopupShared.lua"]:148: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals:
Skipped (In Encounter)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Yes it can because that is taint in Edit Mode Manager. This has been an ongoing issue since beta.

**Comment by Aldori15** [comment]
> Yes it can because that is taint in Edit Mode Manager. This has been an ongoing issue since beta.

This particular instance was opening Edit Mode during combat.  But there are also instances where it can happen randomly - most noticeable if a party member leaves or joins the group.

**Comment by Azilroka** [comment]
Yea it's spread quite badly. They've been working on getting it cleaned up to not spread taints
