### ISSUE TITLE
[Wrath Bug Report] Empty Action Buttons and Pet Auto Cast Action Buttons

### ISSUE THREAD

**Issue by HopelessRomant1c** [tukui-org/ElvUI#855]
### What is the issue you are having?

Enabled action bars with 'Show Empty Buttons' unchecked starts showing and the pet action bar gains double sets of arrows on auto cast spells.

### What is the expected behavior?

Hidden empty action buttons should stay hidden and auto cast pet spells should only have one set of corner arrows.

### What actually happened?

When dragging a pet spell from the spellbook, hidden empty action buttons start showing
In addition auto cast pet abilities get an additional set of arrows

Examle: https://streamable.com/h2wv0b

Video is a month old, but the issue still persists in the newest version 13.26.

### Suggested Solution/Workaround

A relog is required for action buttons to once again become hidden.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by HopelessRomant1c** [comment]
Bug still in the game after the latest update 13.27

**Comment by Azilroka** [comment]
I know for a fact that the double arrows are fixed with ElvUI.. I couldnt reproduce the other error at all.

**Comment by Azilroka** [comment]
https://user-images.githubusercontent.com/1934853/221413065-c018340c-e6d3-410b-8c33-a965bde1840b.mp4

**Comment by HopelessRomant1c** [comment]
You need to drag a spell from your pet's spellbook in order to reproduce.

I see the double arrows have been fixed though, thank you for that.
