### ISSUE TITLE
[Retail Bug Report] Background glow visible when health bar is hidden

### ISSUE THREAD

**Issue by cozawariat** [tukui-org/ElvUI#857]
### What is the issue you are having?

When health bar is disabled then selecting any type of target indicator makes friendly target showing a background glow.
![image](https://user-images.githubusercontent.com/3003260/218338873-3e7ebd54-513c-43ce-a79f-e655b5ea2c2f.png)

### What is the expected behavior?

When health bar is disabled on friendly targets background glow should be optional or hidden.

### What actually happened?

When health bar is disabled then selecting any type of target indicator makes friendly target showing a background glow.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by cozawariat** [comment]
it's working after reloading, but makin any change to the indicator style breaks it again

**Comment by cozawariat** [comment]
in `TargetIndicator.lua` commenting out lines `52` and `53` allows to at least use border glow and arrows on enemy
and doesnt break on friendly target
```diff
- element.Spark:SetVertexColor(color.r, color.g, color.b)
- element.Spark:Show()
+ -- element.Spark:SetVertexColor(color.r, color.g, color.b)
+ -- element.Spark:Show() 
```

**Comment by Azilroka** [comment]
You have Name Only enabled so it only uses that glow. It's not a bug.

**Comment by cozawariat** [comment]
ok name only fixed it, but still the behaviour is not consistent when its off - it doesnt show glow then it does etc.
this could be improved dont you agree?
or you can just pretend everything is fine... anyways thank you for the solution to my problem.
