### ISSUE TITLE
Hide Currency Format

### ISSUE THREAD

**Issue by ghost** [tukui-org/ElvUI#858]
Like with the gold format that can be hidden if need be, it would be nice if you could do the same with currencies. I already use the datatext version for this exact purpose so having it show twice is kinda redundant.
![infobloat](https://user-images.githubusercontent.com/33032465/218339710-80b627cf-c686-468d-83e7-33a012ce4607.jpg)
Additionally remove the empty space if both options are turned off/hidden.

**Comment by kodewdle** [comment]
done 👍
