### ISSUE TITLE
[Wrath Bug Report] Interface / Combat - 3 Cast Key options missing

### ISSUE THREAD

**Issue by prisnagka** [tukui-org/ElvUI#859]
### What is the issue you are having?

Options missing in Interface > Combat when ElvUI enabled.
These options are not visible when ElvUI skinning is enabled:
* Focus Cast Key
* Self Cast Key
* Auto Self Cast

![bild](https://user-images.githubusercontent.com/59577062/218548917-ec0f99aa-4993-4fe9-ad91-8b2e2cfb4f84.png)

Using ElvUI 13.26
![bild](https://user-images.githubusercontent.com/59577062/218550342-5e1b1f13-c7b0-450a-9e7f-10866ac93bb4.png)

### What is the expected behavior?

The 3 mentioned options should be available as shown here when ElvUI is NOT loaded.

![bild](https://user-images.githubusercontent.com/59577062/218548813-46bcf13e-fecc-475c-89e6-3d082b232461.png)

### What actually happened?

Quite easy to see in the first screen shot that the 3 last options are missing.

### Suggested Solution/Workaround

With edebug on (and all other addons thus disabled I guess), the problem persists.
![bild](https://user-images.githubusercontent.com/59577062/218549889-fed5023b-e613-4f0b-be00-7bb753467557.png)

### Errors

```shell
No errors shown, just missing the options...
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Those options are in the ElvUI menu - Actionbar section.
