### ISSUE TITLE
[TBC Bug Report] <Title here>

### ISSUE THREAD

**Issue by Keador** [tukui-org/ElvUI#86]
### What is the issue you are having?

Trying to use party frames for groups < 11. 

### What is the expected behavior?

Party frames should show group 2 if the number of groups setting is set to 2.

### What actually happened?

If the number of groups is set >1, either the second group doesn't show up or shows the same group twice.

### Suggested Solution/Workaround

If this is working as intended, i.e.; Party Frames cannot be used as 10 man raid frames, the setting for the number of groups in the party frames config should probably be removed.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-tbc-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Azilroka** [comment]
Those options was removed before.. Probably got overlooked when we did the all in one version. I'll fix that.
