### ISSUE TITLE
[Wrath Bug Report] Tracked currencies covered by bag items

### ISSUE THREAD

**Issue by brandon-lake** [tukui-org/ElvUI#865]
### What is the issue you are having?

My bags are in this state each time I log in, as well as after reloading my UI.  All bag slots are slightly shifted down such that they cover all of my tracked currencies
![bad_behaviour](https://user-images.githubusercontent.com/46915561/219970915-e11ab1e1-59da-43af-a738-0102ca1789b8.jpg)

### What is the expected behavior?

The expected behaviour would be that all bag slots are about 2-3 millimeters higher.  I can "fix" this issue by simply moving an item within my bags.  This causes all bag slots to reset to their proper position.
![expected_behaviour](https://user-images.githubusercontent.com/46915561/219970992-1596f092-9b0a-47ed-983f-3756c1741e82.jpg)

### What actually happened?

Some additional information - this only occurs while I have the "Reverse Bag Slots" option selected

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat 
/edebug on

Then log out & log back in. Do you still have the issue? 

If so, type in chat in game /estatus

and upload a FULL UI screenshot showing the status panel and the issue 
And another screenshot showing the status panel and how it should look.

**Comment by brandon-lake** [comment]
Typed /edebug on then relogged, issue still there.
![full_UI_bad](https://user-images.githubusercontent.com/46915561/220200063-71d00cd1-caf6-4762-af27-2ef5edad9d0a.jpg)

Now moved an item in bad to reset the bag slots to proper position
![full_UI_good](https://user-images.githubusercontent.com/46915561/220200073-40cbb90e-a2a8-4377-9ca8-07ac6c9ac33a.jpg)

**Comment by xR3cH** [comment]
I have the same issue, but in retail version

**Comment by MrMagoozor** [comment]
> I have the same issue, but in retail version

So do I.
![Screenshot 2023-06-10 224034](https://github.com/tukui-org/ElvUI/assets/17347275/971e122e-cdca-4a38-9397-4479aa044a4e)

**Comment by gizzmo** [comment]
I've been bothered by this bug for a while. I think I found the culprit. 

Normally the bag slots are placed from top to bottom, but with the `Reverse Bag Slot` option enabled they're built bottom up. The issue arises when the code uses the variable `bottomOffset` to anchor that first slot. But later in the same method, it'll recalculate that offset with the current tracked currencies.

See: `Core/Modules/Bags/Bags.lua` [Line 1007](https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/Bags/Bags.lua#L1007C78-L1007C92) & [Line 1069](https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/Bags/Bags.lua#L1069C5-L1069C19)

Hope this helps the devs!

**Comment by kodewdle** [comment]
fixed
