### ISSUE TITLE
[Retail Bug Report] Some code in 'Core/Modules/UnitFrames/UnitFrames.lua'

### ISSUE THREAD

**Issue by Etern213** [tukui-org/ElvUI#869]
### What is the issue you are having?

Here are some code in 'Core/Modules/UnitFrames/UnitFrames.lua'
```
-- For the damn vehicle support:
frame:RegisterEvent('PLAYER_ENTERING_WORLD')
frame:RegisterEvent('UNIT_ENTERING_VEHICLE')
frame:RegisterEvent('UNIT_ENTERED_VEHICLE')
frame:RegisterEvent('UNIT_EXITING_VEHICLE')
frame:RegisterEvent('UNIT_EXITED_VEHICLE')
```
https://github.com/tukui-org/ElvUI/blob/development/ElvUI/Core/Modules/UnitFrames/UnitFrames.lua#L1293

Why we must register these event for vehicle support?
I test many situation about vehicle without it, everything work well and no errors occurred.

### What is the expected behavior?

:)

### What actually happened?

:)

### Suggested Solution/Workaround

Maybe we don't need to register these event for the default PlayerFrame.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Are you a wow dev?

**Comment by Azilroka** [comment]
Or do you just randomly say it's a bug without any basis for your claim?

**Comment by Azilroka** [comment]
https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/PlayerFrame.lua#L54

**Comment by Etern213** [comment]
> Or do you just randomly say it's a bug without any basis for your claim?

Do you see the link I given?
I just ask why we register vehicle event like 'UNIT_EXITING_VEHICLE' for _G.PlayerFrame after calling _G.PlayerFrame:UnregisterAllEvents()
_G.PlayerFrame is not ElvUI playerframe. Its origin PlayerFrame and we already hide it.

And I test many situation about vehicle and found that maybe we don't need to register it.

So do you still think I randomly say it's a bug????

**Comment by Azilroka** [comment]
That code deals with the Player frame and Pet frame. That's what those function calls are for. It's not random and isn't a bug. You can keep the Pet frame with the Player frame disabled.

**Comment by Etern213** [comment]
> That code deals with the Player frame and Pet frame. That's what those function calls are for. It's not random and isn't a bug. You can keep the Pet frame with the Player frame disabled.

Thanks for your reply.
So, According to what you said and my test, if I disable original pet frame and playerframe, and let ElvUI handle both of them, those function are not needed?

**Comment by Azilroka** [comment]
Yes and if we used the original function you w I uldnt have a choice in whether or not you could use Blizzard frames. This function is directly from oUF and overridden by ours to allow it to be customized.

This isn't a bug regardless and has nothing to do with the performance of ElvUI UnitFrames.

**Comment by Etern213** [comment]
Sorry to bother you, I understand it now. Thank you, And I will close this issue.

I raised this issue because I think we can change
```-- For the damn vehicle support:
frame:RegisterEvent('PLAYER_ENTERING_WORLD')
frame:RegisterEvent('UNIT_ENTERING_VEHICLE')
frame:RegisterEvent('UNIT_ENTERED_VEHICLE')
frame:RegisterEvent('UNIT_EXITING_VEHICLE')
frame:RegisterEvent('UNIT_EXITED_VEHICLE')
```
to
```if UF.db.units.pet.enable then
  -- For the damn vehicle support:
  frame:RegisterEvent('PLAYER_ENTERING_WORLD')
  frame:RegisterEvent('UNIT_ENTERING_VEHICLE')
  frame:RegisterEvent('UNIT_ENTERED_VEHICLE')
  frame:RegisterEvent('UNIT_EXITING_VEHICLE')
  frame:RegisterEvent('UNIT_EXITED_VEHICLE')
end
```
to avoid unnecessary event register.
