### ISSUE TITLE
[Classic Bug Report] Issue with Tracking Icon on MiniMap

### ISSUE THREAD

**Issue by Alind777** [tukui-org/ElvUI#87]
### What is the issue you are having?

The tracking icon on the Mini Map gets really big and shifts all the way left. If you hide and unhide the tracking icon it temporarily fixes the issue but it will come back when you log out and log back in. Will attach a SS in the comments.

### What is the expected behavior?

The icon should be small and in the corner of the map.

### What actually happened?

See the issue description.

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/classic-addons.php?id=2&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Alind777** [comment]
![image](https://user-images.githubusercontent.com/94484375/143042023-57b56b3f-430c-4137-b1a8-f88dddb86de1.png)

**Comment by kodewdle** [comment]
Fixed in development branch, will be in next release today.
