### ISSUE TITLE
ADDON_ACTION_FORBIDDEN (JoinBattleField)

### ISSUE THREAD

**Issue by raphaeloliveira** [tukui-org/ElvUI#870]
### What is the issue you are having?

The issue is I'm intermittently unable to queue for battlegrounds or epic battlegrounds. Reloading the UI may temporarily fix the issue but it returns very frequently. 

**ElvUI Log Taints On**
![issue](https://user-images.githubusercontent.com/2700131/221176337-45fdf9fc-8d3c-42f4-9068-734da0f3ac70.jpg)

**Bug Sack On**
![bugsack](https://user-images.githubusercontent.com/2700131/221177106-710da23d-185b-4f72-a764-0a1f4023a0ee.png)

I also recorded a **[video](https://www.youtube.com/watch?v=PcGrcyKyJxc&ab_channel=Raph_)** showing the issue in multiple scenarios:
- all addons enabled except `Narcissus` (because we suspected it could be the culprit)
- `edebug on`
- `edebug off`
- all addons `narci on`

If I disable ElvUI I'm not able to reproduce the issue. You can also see on the **[video](https://www.youtube.com/watch?v=PcGrcyKyJxc&ab_channel=Raph_)** that at some point during `edebug on` it randomly starts working for no apparent reason.

Besides this issue, I'm also experiencing a similar error when using toys or clicking items in the bag (although the later can be workaround by using Elvui's bag module).

### What is the expected behavior?

I should be able to join battleground.

### What actually happened?

The game doesn't allow me to queue to a battleground and an error is displayed if log taint is on or bugsack is on.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
since The War Within is out and this is a taint, reopen if you still have the issue please :)
