### ISSUE TITLE
[Wrath Bug Report] <Vehicle button not showing>

### ISSUE THREAD

**Issue by Healingbassist** [tukui-org/ElvUI#871]
### What is the issue you are having?

it might be a masque issue. the leave vehicle button is not showing the arrow. the skin is masqued.

### What is the expected behavior?

vehicle button should be showing with masque working at the same time?

### What actually happened?

![323](https://user-images.githubusercontent.com/119632062/221331631-650c966c-665b-4580-87df-f2608d8b260b.png)
![323](https://user-images.githubusercontent.com/119632062/221331938-89283644-43ac-43f9-9260-f251eac23f95.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Is this still an issue?
