### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by vixiepixie5** [tukui-org/ElvUI#877]
### What is the issue you are having?

![image](https://user-images.githubusercontent.com/55593130/221461743-d01e8d90-07b3-4614-9921-be8a89b1a025.png)

The image attached is one example, and my hope is it's a "type" thing and not something more intensive. But, some Nameplates are not functioning. They use the default Blizzard ones and not the ElvUI ones. 

### What is the expected behavior?

ElvUI Nameplates show

### What actually happened?

The default Blizzard ones show.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
That's how instances are. We can't alter friendly nameplates in instances.

**Comment by vixiepixie5** [comment]
Sounds good, thanks!
