### ISSUE TITLE
[Wrath Bug Report] Cannot add Ancestral Fortitude Rank 3 (16237) to Filter List

### ISSUE THREAD

**Issue by Lehona** [tukui-org/ElvUI#883]
### What is the issue you are having?

When I'm trying to add Ancestral Fortitude Rank 3 (16237) to the "Aura Indicator (Class)" filter list, the "detail view" (at the bottom) shows rank 1 (16177), but without any options to configure. Neither rank is actually added to the filter list. Adding rank 1 explicitly works as expected. Adding it to e.g. the TurtleDebuffs filter list works as expected as well. 
Turning off all other addons does not help.

### What is the expected behavior?

I should be able to add 16237 just like any other spellID.

### What actually happened?

A broken view of the rank 1 version is shown, but no spell (neither rank 1 nor 3) are added to the filter list.

### Errors

```shell
Message: Interface/AddOns/ElvUI_Options/Core/Filters.lua:334: attempt to index field '?' (a nil value)
Time: Wed Mar  1 22:50:08 2023
Count: 1
Stack: Interface/AddOns/ElvUI_Options/Core/Filters.lua:334: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_Options/Core/Filters.lua"]:334: in function `member'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:215: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:164>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1255: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1153>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1180: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1153>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1754: in function `FeedGroup'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1679: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1663>
[string "=[C]"]: ?
[string "@Interface/AddOns/Attune/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <...terface/AddOns/Attune/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Attune/Libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Attune/Libs/AceGUI-3.0/widgets/AceGUIContainer-TabGroup.lua"]:342: in function `SelectTab'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1790: in function `FeedGroup'
...
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:1850: in function `FeedGroup'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:2034: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:1957>
[string "=[C]"]: in function `?'
[string "@Interface/AddOns/ElvUI/Core/General/Config.lua"]:1116: in function `?'
[string "@Interface/AddOns/Attune/Libs/AceConsole-3.0/AceConsole-3.0.lua"]:90: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:4938: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4601: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4637: in function <Interface/FrameXML/ChatFrame.lua:4633>
[string "=[C]"]: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
It should be showing Multiple Ranks

**Comment by Azilroka** [comment]
![image](https://user-images.githubusercontent.com/1934853/222282112-33488f6d-4ad4-4a56-9633-6e5f1eee3f21.png)

**Comment by Azilroka** [comment]
If it doesn't look like that.. Then you updated wrong.

**Comment by Azilroka** [comment]
Ah OK. It should add it then I'll try when I get home.
