### ISSUE TITLE
[Retail Bug Report] Friendly Unitframes fade out > 10yard

### ISSUE THREAD

**Issue by Yakked** [tukui-org/ElvUI#885]
### What is the issue you are having?

Unitframes for friendly units (target, targettarget, party, raid etc) fade at all range on my rogue, even if i'm next to them, even if i target myself. If the player is from other faction it works as intended.

On the Target Fader for example, i have Enabled checked and only "Range" checked, all the rest blank. Same with all the other Individual or Group Units.

Elvui updated to last version. Version before worked fine i think.

I have several characters and this issue is not happening on others, using the exact same settings.
ONLY HAPPENS ON MY ROGUE. Maybe a talent issue, some info specific to the rogue that ElvUI is not catching?

Doesnt happen if i disable elvui. 

### What is the expected behavior?

Friendly Unitframes should not be faded if close to them, and Target Unitframe should not be faded if i target myself.

### What actually happened?

Friendly Unitframes fade at every range if players are from the same faction, including if i'm next to the player or if i target myself.
The issue is only with Friendly units however, the Range Fader works well with enemy players / units.

### Suggested Solution/Workaround

Guy had same problem last year on WotLK.
Link to the issue: https://github.com/tukui-org/ElvUI/issues/53

### Errors

```shell
no errors
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
What spec are you? And make sure to test with /edebug on because there is addons that have a different version of LibRangeCheck and it's breaking ours.

**Comment by Yakked** [comment]
> What spec are you? And make sure to test with /edebug on because there is addons that have a different version of LibRangeCheck and it's breaking ours.

Outlaw, nothing changed with edebug. Its fine on Sub Spec.

**Comment by 1Botanica1** [comment]
Please type in chat 
`/edebug on` 
And test. 

If you still have the issue, type in chat in game 
`/estatus` and upload an uncropped image showing both the issue (ie. unitframe faded at 10 yards, but abilities still useable) and the status panel

**Comment by Yakked** [comment]
Outlaw (bugged):

<img src="https://s20.directupload.net/images/230306/rjgmwsuy.jpg">

Showing Target Frame out of range. Same Issue with Group Frames (Raid / Party). 

Sub (works fine!):

<img src="https://s20.directupload.net/images/230306/466ygatl.jpg">

**Comment by 1Botanica1** [comment]
That is as shadowstep is used (if available) which has 25? yard range. 
If you don't have shadowstep - then pick pocket is used which only has a 10 yard range.  

Might have to see if there is another spell that could be used for friendlies without shadowstep

**Comment by kodewdle** [comment]
i don't think distract can work as it's a thrown; pistol shot maybe but it would need to be PR to <https://github.com/WeakAuras/LibRangeCheck-2.0> now, not us
