### ISSUE TITLE
Raid Frames Vanishing

### ISSUE THREAD

**Issue by Servarside** [tukui-org/ElvUI#886]
### What is the issue you are having?

This issue has been happening since blizzard released edit mode.

The issue is what appears to be random is during combat (never seen it happen outside of combat) in PvP teamfights or in raids the raid frames "vanish" or just bug out completely forcing me to click nameplates to heal untill I can get out of combat.

Once i'm out of combat I have 2 options.

1.) Press esc > Open Edit mode > disable and enable "raid frames" (can only be done out of combat)

This brings the raid frames back, but sometimes and more often than not 2-3 players frame will show or overlap one another and be untargetable via clicking their raid frame, which forces you into option 2.)

2.) /reload

Obviously in the middle of an intense PvP game or mythic raid I cannot do either of these, it's a wipe if the raid frames bug.

The issue happens normally once a battleground or 1 in every 10 pulls during mythic raid.

Here is some screenshots of the bug: 
![elvui1](https://user-images.githubusercontent.com/126908586/222799693-d6a0b5ff-605f-45eb-b20d-18bd7ea3ac7a.png)
![image (1)](https://user-images.githubusercontent.com/126908586/222799702-c81d8d28-8919-4956-9943-4428eff2ea7b.png)
![image](https://user-images.githubusercontent.com/126908586/222799712-00511897-1942-4c40-8b92-57d9974f219a.png)
https://imgur.com/a/73mClAW

### What is the expected behavior?

N/A

### What actually happened?

N/A

### Suggested Solution/Workaround

I've reinstalled my game and opened several tickets.

Blizzard tell me the usual rename your cache wtf and another folder, they also gave me some console commands to reset server settings for characters.

They also told me some game files can become corrupt over time and this is why I tried the reinstall.

### Errors

```shell
Don't have any errors sorry, more than happy to provide them if you tell me how I do it.

My contact details:

Discord: [REDACTED]

Bnet: [REDACTED]
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Servarside** [comment]
![image](https://user-images.githubusercontent.com/126908586/222925491-367036ec-ca0f-4774-ab6a-235900d05c24.png)

This happens when opening editmode with elvui enabled.

**Comment by 1Botanica1** [comment]
Not sure if you have tried this, can't remember if it was suggested or you said you have.  If not, you can give it a go.   (if it doesn't work, then it is back to waiting).
/ec - Profile 
Create a new profile in ElvUI and run through the install. 
With the new profile, don't make changes except disabling the ElvUI unitframes you don't want & enabling the blizzard frames you want.  and test with only ElvUI enabled. 
`/edebug on` disables all but ElvUI. 
Test to see if you have the issue with the new profile

**Comment by Servarside** [comment]
Hi,

Tested with new profile and all add ons disabled except elvui and the raid frames do still vanish.

**Comment by 1Botanica1** [comment]
Seems same as #743 

this one shows the taint

**Comment by kodewdle** [comment]
dup of https://github.com/tukui-org/ElvUI/issues/743 closing
