### ISSUE TITLE
[Feature Request] Separate growth directions for members in a group and groups within the raid.

### ISSUE THREAD

**Issue by Lohkrim** [tukui-org/ElvUI#887]
I was trying to set up raid frames in a way that the players within each group grow down, but the groups themselves grow right then down. In the current options, there is only a single growth direction option that sets both the players in a group and the groups within the raid at the same time. This makes it impossible to give them different settings. Attached is a crude sketched picture of what I was trying to achieve.
![Capture](https://user-images.githubusercontent.com/127106661/223106702-28a5c9a4-7e6f-44e9-a3a3-dc0f2f3bc075.PNG)

In the current iteration of elvui, this is set to down then right to get the players in each group to go the correct direction. However the groups themselves actually go 123 down the left, 456 down the right. If I set it to right then down, the players in the group become horizontal growing right.

**Comment by Azilroka** [comment]
That's not possible unless we separate all groups with a mover.

**Comment by Lohkrim** [comment]
> That's not possible unless we separate all groups with a mover.

Is that something that could be done as a separate addon to elvui? Like many elvui addons that add, move, etc parts of the ui to the base elvui. Or is that outside the realm of what those others are capable of altering?
