### ISSUE TITLE
[Wrath Bug Report] Error deleting CustomText

### ISSUE THREAD

**Issue by MarcelMertens** [tukui-org/ElvUI#889]
### What is the issue you are having?

Can't remove custom texts - "Delete" button not working

### What is the expected behavior?

Custom Text will delete

### What actually happened?

Nothing, with debug on -> Lua Error

### Suggested Solution/Workaround

Remove the

["customTexts"] = {} 

section un ElvUI.lua manually

If you check the error, i guess the problem is an error in coding:

in Lua File the section name is "customText**s**" the lua error shows that "customText"  (without the "s") is used 

### Errors

```shell
Message: Interface/AddOns/ElvUI_Options/Core/UnitFrames.lua:472: attempt to index field 'customText' (a nil value)
Time: Thu Mar  9 07:47:22 2023
Count: 55
Stack: Interface/AddOns/ElvUI_Options/Core/UnitFrames.lua:472: attempt to index field 'customText' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI_Options/Core/UnitFrames.lua"]:472: in function <Interface/AddOns/ElvUI_Options/Core/UnitFrames.lua:472>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:869: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:691>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:66: in function <.../ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceGUI-3.0/widgets/AceGUIWidget-Button-ElvUI.lua"]:85: in function <...ce3/AceGUI-3.0/widgets/AceGUIWidget-Button-ElvUI.lua:82>
[string "=[C]"]: ?

Locals: <none>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Thanks, this has been already fixed in the dev version and will be in the next release.  

You can download the dev version until next release.

**Comment by kodewdle** [comment]
closing this, already fixed in dev as Botanica mentioned!  thanks for the report 🌼
