### ISSUE TITLE
[Retail Bug Report] MainMenuBar:SetSize - Protected Function

### ISSUE THREAD

**Issue by R41z0r** [tukui-org/ElvUI#89]
### What is the issue you are having?

Becoming the message: Interface failed because of an add-on action - In Bugsack I can see that:
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'MainMenuBar:SetSize()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetSize'
[string "@FrameXML\MainMenuBar.lua"]:338: in function `ChangeMenuBarSizeAndPosition'
[string "@FrameXML\MultiActionBars.lua"]:49: in function `cb'
[string "@FrameXML\MultiActionBars.lua"]:44: in function <FrameXML\MultiActionBars.lua:34>
[string "@FrameXML\MultiActionBars.lua"]:69: in function `MultiActionBar_Update'
[string "@FrameXML\InterfaceOptionsPanels.lua"]:1192: in function `setFunc'
[string "@FrameXML\InterfaceOptionsPanels.lua"]:94: in function <FrameXML\InterfaceOptionsPanels.lua:90>
[string "=[C]"]: in function `pcall'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:215: in function <FrameXML\InterfaceOptionsFrame.lua:214>
[string "=[C]"]: ?
[string "@FrameXML\InterfaceOptionsFrame.lua"]:250: in function <FrameXML\InterfaceOptionsFrame.lua:246>
[string "=[C]"]: in function `Click'
[string "@FrameXML\UIParent.lua"]:4358: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

### What is the expected behavior?

No Error should happen

### What actually happened?

Partly freezes of the screen or little hangs

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'MainMenuBar:SetSize()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetSize'
[string "@FrameXML\MainMenuBar.lua"]:338: in function `ChangeMenuBarSizeAndPosition'
[string "@FrameXML\MultiActionBars.lua"]:49: in function `cb'
[string "@FrameXML\MultiActionBars.lua"]:44: in function <FrameXML\MultiActionBars.lua:34>
[string "@FrameXML\MultiActionBars.lua"]:69: in function `MultiActionBar_Update'
[string "@FrameXML\InterfaceOptionsPanels.lua"]:1192: in function `setFunc'
[string "@FrameXML\InterfaceOptionsPanels.lua"]:94: in function <FrameXML\InterfaceOptionsPanels.lua:90>
[string "=[C]"]: in function `pcall'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:215: in function <FrameXML\InterfaceOptionsFrame.lua:214>
[string "=[C]"]: ?
[string "@FrameXML\InterfaceOptionsFrame.lua"]:250: in function <FrameXML\InterfaceOptionsFrame.lua:246>
[string "=[C]"]: in function `Click'
[string "@FrameXML\UIParent.lua"]:4358: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>
```

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by Luckyone961** [comment]
https://www.tukui.org/forum/viewtopic.php?f=5&t=9344
