### ISSUE TITLE
Elvui minimap tracking resets

### ISSUE THREAD

**Issue by Lordmemnar** [tukui-org/ElvUI#890]
### What is the issue you are having?

As title explains tracking on the minimap has become very odd it has set things that track and I cannot force or track other things and everytime its resetting

### What is the expected behavior?

That updating what id like to track forces it to stay on those

### What actually happened?

Again right click and selecting the boxes and hitting /console reloadui and those boxes uncheck again

### Suggested Solution/Workaround

No idea ive done everything up to and including disabling other addons and living only base ELVUI on and its still happening

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type in chat 
`/edebug on` 
And test. 

If you still have the issue, type in chat in game 
`/estatus` and upload an uncropped image showing both the issue (ie. unitframe faded at 10 yards, but abilities still useable) and the status panel

**Comment by Lordmemnar** [comment]
Closing as I tested something else and I guess my solution is a full UI reset and have to do so from scratch as it was replicated with other mini map tracker addons.

**Comment by vas180** [comment]
Use different profile for settings to be kept and not changed. The issue that track reset after you open again shouldn't  effect the tracking as if you go ahead and move your character after you select the things you wanna show on minimap it will somehow "save" them and wont be reset again. just select and move. It worked for me.
