### ISSUE TITLE
[Feature Request] <Party Frame sort order position>

### ISSUE THREAD

**Issue by clust3rsekt0r** [tukui-org/ElvUI#894]
**Is your feature request related to a problem? Please describe.**
< This problem could be a Blizzard issue, and not related to ELVUI,
1 - How I discover this issue ?
Using Party Macros (Example - /cast [@party1] Renewing Mist); 
- Every time a party is made the order of the party change dynamically is not consistent, I think the index is assign to who enters first instead of class or other order, even if you select in party frame to sort by class or index still not consistent.
- >

**Describe the solution you'd like**
< It is possible to rearrange the party array to a consistent one that lets say if I sort by class Tank shows first and healer after when I run a @party1 macro always goes to the first from top to bottom ?>

**Describe alternatives you've considered**
< A clear and concise description of any alternative solutions or features you've considered. >

**Additional context**
< Add any other context or screenshots about the feature request here. >

**Comment by 1Botanica1** [comment]
When the order of the group is arranged differently to how it would show via blizzards system, then no, the macro for party1 won’t be the tank etc (the first player you have arranged your frames to show).  It will be which character blizzard has assigned for party 1.

**Comment by kodewdle** [comment]
the options are in Sort Method (UnitFrames > Group Units > General > Sort Index) this is what blizzard defines it as.  You can put Name or Index.
