### ISSUE TITLE
[Retail Bug Report] Totem tracker keeps showing up the icons while there's no totem or summon active

### ISSUE THREAD

**Issue by tiagopassarela** [tukui-org/ElvUI#895]
### What is the issue you are having?

I play shaman and warlock and the totem tracker keeps showing the icons of the totems/summons (i.e summon vilefiend) as they were active although they are not.

### What is the expected behavior?

The totem tracker should only show totems and summons while they are active.

### What actually happened?

When I use totems as a druid or summon vilefiend as a warlock for example sometimes the icon of the spell stays in the totem tracker after the totem/summon goes away.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This should be fixed in the dev version.  You can download and test

**Comment by kodewdle** [comment]
reopen if needed, should be fixed by now.
