### ISSUE TITLE
[Feature Request] DataText: Armor penetration

### ISSUE THREAD

**Issue by Darkloke** [tukui-org/ElvUI#897]
**Is your feature request related to a problem? Please describe.**
Right now armor penetration stat as datatext displayed as actually rating but with %. For example in my case it displayed as 515.37% while actual %-value (shown in tooltip) is 34.37%. So my request is to display correct %-value (as in tooltip).

Another issue that in russian client it displays as non-localized string "Armor Penetration".

**Additional context**
![image](https://user-images.githubusercontent.com/4979638/224532071-9bb501ff-f983-4e60-9aae-8b70460bef66.png)

**Comment by Azilroka** [comment]
There is no localization string in Wrath for it.
