### ISSUE TITLE
[Retail Bug Report] Zone Ability during pet battle

### ISSUE THREAD

**Issue by AnimeDrache** [tukui-org/ElvUI#899]
### What is the issue you are having?

During a pet battle the zone ability keeps showing all the time. This is only in ElvUI and not in classic WoW UI. It is not being hidden automatically and you can't enable it.

Proof Screenshot:

https://prnt.sc/C0VgTlvn6BtZ

### What is the expected behavior?

The zone ablilty should be hidden automatically when in a pet battle.

### What actually happened?

The full button still appears in the middle of the screen.

### Suggested Solution/Workaround

This needs to be fixed by the ElvUI team. I can't do anything on that.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game 
`/edebug on` and test 
If it still happens, type in chat in game 
`/eststus` and upload a full UI screenshot showing both the issue and the status panel.

**Comment by AnimeDrache** [comment]
"/eststus" doesn't work to me.

this is what it still looks like in a pet battle after using "/edebug on": https://gyazo.com/3cb238222514fb388c3fae26fa4d3bc5

**Comment by 1Botanica1** [comment]
I had a typo
`/estatus`

**Comment by AnimeDrache** [comment]
Ahhh okay.

Here the screenshot
![Screenshot_52](https://user-images.githubusercontent.com/51856826/225016112-56109b44-675a-4120-bc00-7879801b8ed8.png)

**Comment by AnimeDrache** [comment]
Are you guys investigating? Sorry to bother but didn't got an answer for a week =).

**Comment by kodewdle** [comment]
should be fixed now in dev branch!  thank you for the report 🌼

**Comment by AnimeDrache** [comment]
> should be fixed now in dev branch! thank you for the report 🌼

You are awesome! Thanks! =D
