### ISSUE TITLE
[Retail Bug Report] Bugging Tooltip Background

### ISSUE THREAD

**Issue by AnimeDrache** [tukui-org/ElvUI#900]
### What is the issue you are having?

Sometimes it happens that the tooltip is bugging. It stays where it is. I first thought it was the Plugin "Bagsync" but now I know it must be ElvUI.

You can see the problem here on this gif animation (it happens to the item "Heart of Azeroth"): https://gyazo.com/e83cfa713b7bffc4e74931679732b80b

### What is the expected behavior?

The tooltip background should go away again.

### What actually happened?

See attachment ( https://gyazo.com/e83cfa713b7bffc4e74931679732b80b )

### Suggested Solution/Workaround

You need to fix it, I can't do anything on that =(.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
That's the compare tooltip bug that was introduced by Blizzard this last patch.

**Comment by 1Botanica1** [comment]
You can try using the command `/run SetCVar('alwaysCompareItems', 0); ReloadUI()`

**Comment by AnimeDrache** [comment]
> You can try using the command `/run SetCVar('alwaysCompareItems', 0); ReloadUI()`

Oh what will happen if I use that? I am always scared in messing up my ElvUI hehe.

**Comment by Repooc** [comment]
> > You can try using the command `/run SetCVar('alwaysCompareItems', 0); ReloadUI()`
> 
> Oh what will happen if I use that? I am always scared in messing up my ElvUI hehe.

it will set wows setting that enables auto compare tooltips to be displayed without holding the modifier for it

**Comment by AnimeDrache** [comment]
Sorry for my late answer.

So that command will turn off for me to hold shift/ctrl when I hover on someones tooltip to see his item score (for example)? will it be active for forever then?

**Comment by 1Botanica1** [comment]
Type in chat in game 
`/edebug on` 
Test.  If you still have the issue, type in chat in game `/estatus` and upload a screenshot. 

Then disable ALL addons & test with the blizzard UI - Do you still have the issue?
