### ISSUE TITLE
[Wrath Bug Report] Taint in Wrath

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#901]
### What is the issue you are having?

Snippet of taint log.

3/13 22:49:53.337  Execution tainted by ElvUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface_Wrath/FrameXML/UIParent.lua:4719 DisplayInterfaceActionBlockedMessage()
3/13 22:49:53.337      Interface_Wrath/FrameXML/UIParent.lua:1090
3/13 22:49:53.337      OverrideActionBarButton1:Show()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:368 ActionButton_Update()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:705 ActionButton_OnEvent()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:208
3/13 22:49:53.337  An action was blocked in combat because of taint from ElvUI - OverrideActionBarButton1:Show()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:368 ActionButton_Update()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:705 ActionButton_OnEvent()
3/13 22:49:53.337      Interface/FrameXML/ActionButton.lua:208
3/13 22:49:54.425  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by ElvUI - Interface_Wrath/FrameXML/UIParent.lua:4722 DisplayInterfaceActionBlockedMessage()
3/13 22:49:54.425      Interface_Wrath/FrameXML/UIParent.lua:1090
3/13 22:49:54.425      Search()
3/13 22:49:54.425      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:226 LFGBrowse_DoSearch()
3/13 22:49:54.425      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:179 LFGBrowseFrame:LFGBrowseFrame:()
3/13 22:49:54.425      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
3/13 22:49:54.425      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:69
3/13 22:49:54.425  Execution tainted by ElvUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface_Wrath/FrameXML/UIParent.lua:4719 DisplayInterfaceActionBlockedMessage()
3/13 22:49:54.425      Interface_Wrath/FrameXML/UIParent.lua:1090
3/13 22:49:54.425      OverrideActionBarButton1:Show()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:368 ActionButton_Update()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:705 ActionButton_OnEvent()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:208
3/13 22:49:54.425  An action was blocked in combat because of taint from ElvUI - OverrideActionBarButton1:Show()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:368 ActionButton_Update()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:705 ActionButton_OnEvent()
3/13 22:49:54.425      Interface/FrameXML/ActionButton.lua:208
3/13 22:49:54.703  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by ElvUI - Interface_Wrath/FrameXML/UIParent.lua:4722 DisplayInterfaceActionBlockedMessage()
3/13 22:49:54.703      Interface_Wrath/FrameXML/UIParent.lua:1090
3/13 22:49:54.703      Search()
3/13 22:49:54.703      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:226 LFGBrowse_DoSearch()
3/13 22:49:54.703      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGBrowse.lua:179 LFGBrowseFrame:LFGBrowseFrame:()
3/13 22:49:54.703      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGParentFrame.lua:92 LFGParentFrame_SearchActiveEntry()
3/13 22:49:54.703      Interface/AddOns/Blizzard_LookingForGroupUI/Blizzard_LFGListing.lua:69

### What is the expected behavior?

No taint log entries.

### What actually happened?

Got taint log entries.

### Errors

```shell
Have a look? I know sometimes taint is caused a variety of ways, but the only add-ons showing up for me in taint log are Blizzard Group finder and Elv.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
closing this as it's just a piece of a puzzle, in a box, in a container, lost on a spaceship on the way to another planet with no fuel, and no living navigators. 👾🛰️

**Comment by Gogo1951** [comment]
Go to sleep mate. Go to sleep.
