### ISSUE TITLE
[Retail Bug Report] <Buffs are not displayed on NamePlates>

### ISSUE THREAD

**Issue by Hollicsh** [tukui-org/ElvUI#904]
### What is the issue you are having?

For some reason, buffs are not displayed on NamePlates. But debuffs are displayed. In the settings everything is enabled and configured.
On the NamePlates of mobs and bosses, buffs are also not shown. But debuffs are displayed.

![Screenshot_2](https://user-images.githubusercontent.com/54585769/225740429-56ce9e60-4c64-4224-9d03-4b9d0a76cd8f.png)
![Screenshot_3](https://user-images.githubusercontent.com/54585769/225740433-e273487b-d169-4fda-b5df-ce3eb19d7dcf.png)
![Screenshot_4](https://user-images.githubusercontent.com/54585769/225740437-467f4c54-7f02-4978-a371-1d7a479711f6.png)
![Screenshot_5](https://user-images.githubusercontent.com/54585769/225740441-5aa3f2a9-b3ff-4957-be9f-24832f37ae79.png)
![Screenshot_6](https://user-images.githubusercontent.com/54585769/225740442-e67a6fcd-48b8-4ba8-be06-a0cd57e4a201.png)

### What is the expected behavior?

Buffs should show up, but they don't.

### What actually happened?

Buffs are not displayed on NamePlates. But debuffs are displayed. In the settings everything is enabled and configured.
On the NamePlates of mobs and bosses, buffs are also not shown. But debuffs are displayed.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
You didn't post the settings so I'm going to assume your filters are at fault.

**Comment by Hollicsh** [comment]
This ? I don't know ... It seems to always work by default.

![Screenshot_3](https://user-images.githubusercontent.com/54585769/225767943-6fd31727-f1c1-471a-9afd-32b8a8d507f4.png)
![Screenshot_4](https://user-images.githubusercontent.com/54585769/225767947-b515c483-29c4-466f-a78c-82e2d31a7dbd.png)

**Comment by Hollicsh** [comment]
This ?

![Screenshot_3](https://user-images.githubusercontent.com/54585769/225770807-7a893362-ff12-41fd-83a2-2f01d340419e.png)
![Screenshot_4](https://user-images.githubusercontent.com/54585769/225770808-05bfc396-be5b-4230-9894-d137bca6d6a1.png)
![Screenshot_5](https://user-images.githubusercontent.com/54585769/225770811-5ff6345a-96ba-468b-aba2-f88c92c52217.png)

**Comment by Hollicsh** [comment]
I got it, sorry ....
