### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by Novakowskii** [tukui-org/ElvUI#905]
### What is the issue you are having?

![Bug1](https://user-images.githubusercontent.com/128104626/225779080-efe4a791-bafd-4bb7-8607-60a2e2ad726d.png)
![QYYXjkS](https://user-images.githubusercontent.com/128104626/225779088-47814d84-6027-48e9-954f-59f162350bb9.png)
![vyZGaLN](https://user-images.githubusercontent.com/128104626/225779323-8adfdcc4-4610-4a48-be11-cfe980e59ab4.jpg)

When the pet actionbar is disabled, one of the abilities still shows the timer where it would be if it was disabled in a very small form. 

### What is the expected behavior?

When the pet action bar is disabled, the timers of said pet actionbar should not show

### What actually happened?

The timer for "PetActionButton7Cooldown.,timer.text" showed on my screen despite it being fully disabled. 

### Suggested Solution/Workaround

Work around: Have the pet action bar enabled and adjust it as needed or disable it and put the anchor on the edge of the screen so the bugged timer is hidden

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Reopen the ticket with the below information if you still have issues. 

1. Type in chat in game
`/edebug on`
2. Test
Do you still have the issue?
3. If you still have issues after edebug on, type in chat in game `/estatus`and upload a FULL UI screenshot showing the issue/error and the status panel.
