### ISSUE TITLE
[Retail Bug Report] Evoker Empowered Spells: Tap & Release Default in Instances?

### ISSUE THREAD

**Issue by DaleHuntGB** [tukui-org/ElvUI#906]
### What is the issue you are having?

When entering an instance, the empowered spells from Evoker are seemingly defaulted to Tap & Release rather than Hold & Release. This does not seem to be an issue in the open-world, specifically in instances.

### What is the expected behavior?

The expected behaviour would be for the Empowered Spells to maintain the Hold & Release setting.

### What actually happened?

Until reloading, when entering an instance, the Empowered Spells are defaulted to Tap & Release (although no CVars are changed), therefore, all Empowered Spells require to be tapped again to stop the channel. This is reverted when reloading. This issue is not prevent in the open-world, even when leaving an instance.

### Suggested Solution/Workaround

I have currently got a weakaura that will set the CVar of the Empowered Spells back to Hold & Release, however, this is fired on the `WORLD_STATE_TIMER_START` but this has made no difference. This issue was not present on Bartender or Blizzard Default UI, so I am assuming that this might be an issue with the ElvUI Action Bars (although, this is probably not true either).

### Errors

```shell
No errors to report.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Seems similar (from comments -not all tied to dragon riding) to #811
