### ISSUE TITLE
[Feature Request] Nameplate Pixel Glow

### ISSUE THREAD

**Issue by Trenchfoote** [tukui-org/ElvUI#907]
**Is your feature request related to a problem? Please describe.**

With Blizz affecting textures for nameplates, using a style filter to affect a nameplate with a new texture causes the nameplate to blink or flash. This is very distracting during higher end content. 

**Describe the solution you'd like**

As a solution to textures I believe adding a “pixel glow” option to the actions of a style filter would help draw attention beyond the current suitable options (flashing/border/NP color change). I believe a check box for “pixel glow” with a color selector, thickness, and frequency would satisfy the intent of drawing attention to key events when multiple NPs are on the screen. 

**Describe alternatives you've considered**
Alternatively, I’ve used Plater which has “corrected” the flashing issues but includes some scripting or mods to add pixel glow to unique mobs. Personally, I prefer Elv NPs as the options and features are more intuitive. 

**Additional context**
None

**Comment by kodewdle** [comment]
blinking texture is fixed in development by https://github.com/tukui-org/ElvUI/commit/27abe3371028537cf787998cca3945e0b717f250

**Comment by Trenchfoote** [comment]
I saw, I'll be downloading it this evening. I'd still like to keep this request open as there's some cases where I think it'd be super useful.

Thanks for working the blinking Sympii!!!

**Comment by mBlinkii** [comment]
Hello, I think a Pixel Glow function would be a great alternative to highlight certain NPC or NP again a little better and so I would also be in support of this to include in the Stylefilters.

**Comment by Trenchfoote** [comment]
> 27abe33

Simpy, I'm good for you to close this since you've implemented. Thanks for this!
