### ISSUE TITLE
[Wrath Bug Report] Windows close icon on Currency tab

### ISSUE THREAD

**Issue by QueenBlade** [tukui-org/ElvUI#909]
### What is the issue you are having?

The close icon/button appears on the Currency tab only.  All other windows/tabs the close icon is hidden.  If you click just under the icon/button as it highlights all info on the currency window will disappear but the window/tab will remain open.

![image](https://user-images.githubusercontent.com/13785217/226207994-0663445b-046a-415e-bfe5-26570fa3b4f4.png)

Icon/button highlighted 
![image](https://user-images.githubusercontent.com/13785217/226208021-56a16c83-bad2-43a5-a064-2a170048e06b.png)

After clicking close
![image](https://user-images.githubusercontent.com/13785217/226208036-e66d4514-b334-44f2-a44b-50745b459a31.png)

### What is the expected behavior?

Window closes

### What actually happened?

Window  information disappears and window remains open

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Yes, the close icons are hidden, but you can still interact with them. 

This should be fixed in the dev version, which may also fix the problem you are having above.

**Comment by 1Botanica1** [comment]
Do you still have the issue after updating? 
If so, please type in chat in game `/edebug on` and test. 

If you still have the issues, please type in chat in game `/estatus` and upload a full UI screenshot (no cropping) showing both the issue and status panel.

**Comment by QueenBlade** [comment]
I no longer am having the issue.  Looks like a white x is now present on all tabs/windows.  
Thank you.
