### ISSUE TITLE
[Retail Bug Report] Embedded chat stopped working with 13.28

### ISSUE THREAD

**Issue by nicl-dev** [tukui-org/ElvUI#911]
### What is the issue you are having?

I just updated to 13.28 and it seems that broke my chat windows. Both are now just black squares in the bottom left and right corner of the screen:

![image](https://user-images.githubusercontent.com/75254846/226655071-1baafeaa-c017-452b-b625-627a43660e4c.png)
![image](https://user-images.githubusercontent.com/75254846/226655345-a11dd003-01a0-4f7f-b436-3c4d3e13a355.png)

edebug enabled:

![image](https://user-images.githubusercontent.com/75254846/226656010-24f07f67-e709-4f17-93b7-6799977d2a6e.png)

### What is the expected behavior?

Having a functional embedded chat window.

### What actually happened?

Chat is not embedded, instead there are only black squares.

### Errors
 ```shell
Message: Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:78: attempt to index field 'TitleIconVersion' (a nil value)
Time: Tue Mar 21 16:27:45 2023
Count: 1
Stack: Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:78: attempt to index field 'TitleIconVersion' (a nil value)
[string "@Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua"]:78: in main chunk

Locals: E = <table> {
 GetTimeInfo = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:379
 mylevel = 70
 Bags = <table> {
 }
 Config_SetButtonColor = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:672
 privateVars = <table> {
 }
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 TBC = false
 OnPrivateProfileReset = <function> defined @Interface/AddOns/ElvUI/Core/init.lua:309
 ExitVehicleShowFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:433
 StaticPopup_EscapePressed = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:434
 Config_CreateLeftButtons = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:806
 UpdateUnitFrames = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1429
 GetMoverHolder = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:373
 CopyTable = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:600
 SetMoversPositions = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:450
 EnableMover = <function> defined @Interface/AddOns/ElvUI/Core/General/Movers.lua:399
 QualityColors = <table> {
 }
 DEFAULT_FILTER = <table> {
 }
 PriestColors = <table> {
 }
 UpdateDB = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1398
 SetupTheme = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:191
 media = <table> {
 }
 UnlocalizedClassName = <function> defined @Interface/AddOns/ElvUI/Core/General/API.lua:98
 TagInfo = <table> {
 }
 OnPauseCooldown = <function> defined @Interface/AddOns/ElvUI/Core/General/Cooldowns.lua:237
 SetupChat = <function> defined @Interface/AddOns/ElvUI/Core/General/Install.lua:58
 GeneralMedia_ApplyToAll = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:336
 TagFunctions = <table> {
 }
 wowtoc = 100005
 UIScale = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:55
 StaticPopup_CheckButtonOnClick = <function> defined @Interface/AddOns/ElvUI/Core/General/StaticPopups.lua:1081
 FramesOverlap = <function> defined @Interface/AddOns/ElvUI/Core/General/Math.lua:164
 Config_CreateSeparatorLine = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:662
 AddTag = <function> defined @Interface/AddOns/ElvUI/Core/General/Tags.lua:94
 SetEnabledState = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 Hook = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:273
 Options = <table> {
 }
 GetZoneText = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:148
 UpdateLayout = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1447
 Layout = <table> {
 }
 GetPlayerMapPos = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:103
 Config_UpdateLeftButtons = <function> defined @Interface/AddOns/ElvUI/Core/General/Config.lua:733
 MapInfo_CoordsUpdate = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:77
 PluginInstaller = <table> {
 }
 PixelBestSize = <function> defined @Interface/AddOns/ElvUI/Core/General/PixelPerfect.lua:92
 UnregisterEventForObject = <function> defined @Interface/AddOns/ElvUI/Core/General/Core.lua:1744
 MapInfo_CoordsStop = <function> defined @Interface/AddOns/ElvUI/Core/General/MapInfo.lua:62
 Distributor = <table> {
 }
 StopShake = <function> defined @Interface/AddOns/ElvUI/Core/General/Animation.lua:162
 DBConvertSL = <function> defined @Interface/AddOns/ElvUI/Core/General/C
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Redase1337** [comment]
https://www.tukui.org/downloads/elvui-13.27.zip - for Downgrade - work perfect till fix

**Comment by Zasshem** [comment]
Same issue here! Only downgrade solved the issue!

**Comment by Antrogena** [comment]
würde gerne zurück auf 13.27 da ging noch alles

**Comment by FHeerdink** [comment]
> https://www.tukui.org/downloads/elvui-13.27.zip - for Downgrade - works perfect till fix

This seems to fix it, I updated to 13.28 and my chat and bottom bar wheren't working

**Comment by nicl-dev** [comment]
> I'm still on 10.0.5 though, as the patch hits tomorrow here in the EU. It might just be that.


This is a very good point. I am playing on EU as well. Maybe that's the issue.

**Comment by 1Botanica1** [comment]
**Version 13.28 for Patch 10.0.7**
You can read the changes here: 
https://www.tukui.org/download.php?ui=elvui&changelog

**Version 13.27 for Patch 10.0.5**
For EU/Asia people if you updated too early use this:
https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.27.zip

**Comment by Azilroka** [comment]
> https://www.tukui.org/downloads/elvui-13.27.zip - for Downgrade - works perfect till fix

Works purrfect because you all are on EU. We go through this every single patch on WoW.
