### ISSUE TITLE
[Retail Bug Report] Many errors on 13.28

### ISSUE THREAD

**Issue by BeemerMeUp** [tukui-org/ElvUI#913]
### What is the issue you are having?

After updating to 13.28 and loading the game I received 5 ElvUI LUA errors. Check the attached text files for detailed LUA error info.  Also the Add-on still seems to be out-dated. I've

- Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:78: attempt to index field 'TitleIconVersion' (a nil value)
-  Interface/AddOns/ElvUI/Mainline/Modules/Skins/CombatLog.lua:15: attempt to index field 'db' (a nil value)
- Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:479: doesnt exist!
- Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1 (null)
- Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1 (null)

A reload of the interface did not work neither did disabling all other Add-ons.
I even uninstalled and re-installed the addon. Same result.

Currently the addon is unusable. 

[Elvui Error 1 of 5.txt](https://github.com/tukui-org/ElvUI/files/11033003/Elvui.Error.1.of.5.txt)
[Elvui Error 4 and 5 of 5.txt](https://github.com/tukui-org/ElvUI/files/11033004/Elvui.Error.4.and.5.of.5.txt)
[Elvui Error 3 of 5.txt](https://github.com/tukui-org/ElvUI/files/11033005/Elvui.Error.3.of.5.txt)
[Elvui Error 2 of 5.txt](https://github.com/tukui-org/ElvUI/files/11033006/Elvui.Error.2.of.5.txt)

### What is the expected behavior?

The addon should not show any LUA errors and should load normally and also should not show out-dated.

### What actually happened?

Got LUA Errors and add-on is unusable

### Suggested Solution/Workaround

Disable addon and use native interface.

### Errors

```shell
- Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:78: attempt to index field 'TitleIconVersion' (a nil value)
-  Interface/AddOns/ElvUI/Mainline/Modules/Skins/CombatLog.lua:15: attempt to index field 'db' (a nil value)
- Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua:479: doesnt exist!
- Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1 (null)
- Interface\FrameXML\Bindings.xml:1 Interface/AddOns/ElvUI/Core/Modules/Chat/Chat.lua:1 (null)
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by maplepy** [comment]
![image](https://user-images.githubusercontent.com/28269333/226753501-d80925f3-f28d-4e97-8532-c297c47de539.png)

I'm on EU server and this update is bugged as hell, how can I downgrade please? This is annoying af

**Comment by 1Botanica1** [comment]
> 

The links to downgrade are in the message directly above yours.

**Comment by achidler** [comment]
People on US servers have the same problem now with 10.0.7?

**Comment by 1Botanica1** [comment]
> People on US servers have the same problem now with 10.0.7?

No. If you are having issues, please check to see there isn’t an open ticket with your exact issue. 

If you have issues after going through the troubleshooting, open a new ticket 

If there isn’t, go through the troubleshooting steps 
Type in chat in game `/edebug on` and test. Do you have the issue/error? 
If so, type in chat in game `/eststus` and upload a full UI screenshot (no cropping) showing the issue and the error and the status panel.

**Comment by maplepy** [comment]
> you updated early.

early from what ? that's not very clear

**Comment by maplepy** [comment]
> > 
> 
> The links to downgrade are in the message directly above yours.

Thanks will try to downgrade then :)

**Comment by 1Botanica1** [comment]
> > you updated early.
> 
> early from what ? that's not very clear

For the wow patch in your region.  The wow patches get rolled out to the US first and then to other regions later.   You have updated ElvUI for the 10.0.7 when you are on 10.0.5 still

The comments explain the patches 

I will copy here 

Version 13.28 for Patch 10.0.7
You can read the changes here:
https://www.tukui.org/download.php?ui=elvui&changelog

Version 13.27 for Patch 10.0.5
For EU/Asia people if you updated too early use this:
https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.27.zip

**Comment by BeemerMeUp** [comment]
> Are you in EU/Asia or US server?
> 
> The update was for wow version 10.07
> 
> if you updated too early, you need to downgrade.
> 
> **Version 13.28 for Patch 10.0.7** You can read the changes here: https://www.tukui.org/download.php?ui=elvui&changelog
> 
> **Version 13.27 for Patch 10.0.5** For EU/Asia people if you updated too early use this: https://github.com/tukui-org/ElvUI/archive/refs/tags/v13.27.zip

Perfect thanks. So hopefully today it will work again as intented.. will test it and report back.

**Comment by BeemerMeUp** [comment]
After the update the add-on indeed seems to be working fine again.
