### ISSUE TITLE
[Retail Bug Report] <13.28 >  

### ISSUE THREAD

**Issue by kinndy7871** [tukui-org/ElvUI#914]
### What is the issue you are having?

Getting error report when logging in.

### What is the expected behavior?

I am unsure.

### What actually happened?

When I log into the game I get  the following error.

### Errors

```shell
11x ElvUI/Mainline/Modules/DataTexts/Missions.lua:357: Usage: GetCompleteMissions([missionList,] garrFollowerTypeID)
[string "=[C]"]: ?
[string "@ElvUI/Mainline/Modules/DataTexts/Missions.lua"]:357: in function <ElvUI/Mainline/Modules/DataTexts/Missions.lua:332>

Locals:
(*temporary) = nil
(*temporary) = <table> {
}
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This is fixed in the dev version.  You can download that until next release

**Comment by 1Botanica1** [comment]
https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip

**Comment by kinndy7871** [comment]
It worked!! TYSM! HAGD!

**Comment by 1Botanica1** [comment]
ElvUI has been updated. Just need to update to 13.29
