### ISSUE TITLE
[Retail Bug Report] Bags -> Bag Bar -> Show count not working

### ISSUE THREAD

**Issue by Whyzerman** [tukui-org/ElvUI#917]
### What is the issue you are having?

Show count is not clickable in the options. This worked and was enabled in previous versions of the ElvUI Client, but since the 10.0.0.7 release it is not functional. Bag count is no longer displayed on the bag bar.

### What is the expected behavior?

Show count should be interactable, and should enable bag count to be displayed on the bag bar.

### What actually happened?

Bag count is not displayed, and the option to enable the bag count is not interactable. 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Whyzerman** [comment]
Manually setting the displayFreeBagSlots CVar to 1 or 0 in the default UI also seems to have 0 effect on whether or not the free bag slots are shown for the default UI, nor does it have an effect on whether or not the free bag slots are shown in ElvUI, although the default UI seems to always show the bag count, while ElvUI does not:

ElvUI: https://i.imgur.com/MV9ByLr.jpeg
Default UI: https://i.imgur.com/eh1aSoc.jpeg

**Comment by Azilroka** [comment]
They removed that CVar. That's how we was displaying the information. It has been fixed in development though.

**Comment by kodewdle** [comment]
closing this is fixed in dev builds, will work in next version or you can update to dev! 🌼
