### ISSUE TITLE
[Feature Request] Copy and Paste functionality for notes in Group Finder

### ISSUE THREAD

**Issue by Kromula** [tukui-org/ElvUI#92]
**Is your feature request related to a problem? Please describe.**
I would like to suggest a copy and paste function for notes in Group Finder interfaces. It becomes extremely tedious and taxing having to constantly type out things like Covenant, experience or RIo/Raid progress into notes. I notice that sometimes the text is autopopulated when I sign up to another key or raid, but this is never consistent. 
Not sure if maybe a bug to be reported? 

**Describe the solution you'd like**
Copy and paste function (CTRL+C and CTRL+P) workable in the notes text panel in group finder.
Or consistent population of last note typed. 

**Describe alternatives you've considered**
Feel this may be a blizzard limitation, or potentially a bug, but felt like asking/raising as it's extremely tedious to keep writing out notes, and sometimes the notes persist through signups. 

**Additional context**
Happy to assist with screenshots or videos.

**Comment by Azilroka** [comment]
We don't do anything to that frame besides skin it. We dont have access to call the clipboard to copy or paste anything also.
