### ISSUE TITLE
[Classic Bug Report] <Raid frames not displaying entire raid>

### ISSUE THREAD

**Issue by Raademar** [tukui-org/ElvUI#921]
### What is the issue you are having?

Raid frames not displaying entire raid. Version is 13.29

### What is the expected behavior?

All groups should be displayed.

### What actually happened?

When entering Molten Core with a full raid of 40 members the raid frames removed group 7 and 8 from view, displaying only 1-6. When leaving the instance the missing groups appeared again.
![elvui_groups](https://user-images.githubusercontent.com/24412744/227800908-71a7c361-59bb-4dd1-9380-a604b95fdca1.png)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Azilroka** [comment]
Turn off Max Allowed Groups in UnitFrames - General.
