### ISSUE TITLE
Unskinned Button in LFG "Start Group"

### ISSUE THREAD

**Issue by RAtwood90** [tukui-org/ElvUI#925]
### What is the issue you are having?

Unskinned "Start Group" Button via joining for World Quest.

### What is the expected behavior?

Skinned Button.

### What actually happened?

Unskinned Button.
![WoWScrnShot_032923_171129](https://user-images.githubusercontent.com/73589071/228589314-0b6db35c-ea57-431e-9be3-eae7f94024b6.jpg)
![WoWScrnShot_032923_171134](https://user-images.githubusercontent.com/73589071/228589327-c866395a-663a-436e-94eb-4db65ab32f38.jpg)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
that is intended bc it causes a taint when skinned
