### ISSUE TITLE
[Retail Bug Report] Core.lua:380: attempt to call local 'func' (a boolean value)

### ISSUE THREAD

**Issue by Papa-War** [tukui-org/ElvUI#930]
### What is the issue you are having?

Log in to WoW and get the error. periodically, when looting a new item bags will not open. have to /reload to open bags. 

### What is the expected behavior?

no error

### What actually happened?

logged in and received this error. have received this error as of update 13.29

### Suggested Solution/Workaround

no clue.

### Errors

```shell
83x ElvUI/Core/General/Core.lua:380: attempt to call local 'func' (a boolean value)
[string "@ElvUI/Core/General/Core.lua"]:380: in function `ValueFuncCall'
[string "@ElvUI/Core/General/Core.lua"]:332: in function `UpdateMedia'
[string "@ElvUI/Core/General/Core.lua"]:1968: in function `Initialize'
[string "@ElvUI/Core/init.lua"]:227: in function <ElvUI/Core/init.lua:226>
[string "=[C]"]: ?
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Masque/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...aceMasque/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:542: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:751: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:100: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:93: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:88: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:80: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:76>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
you should do ` I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using /edebug on? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.` part of the things you checked.  That line number doesn't line up, so I am assuming your elvui is out of date.
Before you respond back, make sure to do `/edebug on` and see if you have the issue and then do `/estatus` and provide a picture of that window.
