### ISSUE TITLE
[Retail Bug Report] Can't TAB thru enemies

### ISSUE THREAD

**Issue by Nightfireop** [tukui-org/ElvUI#931]
### What is the issue you are having?

Can't tab enemies as you normally can without the UI, no keybinds is set for TAB so not sure why 

### What is the expected behavior?

Should tab enemies

### What actually happened?

Doesnt do anything

### Suggested Solution/Workaround

N/A

### Errors

```shell
N/A
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game
`/luaerror on` 
test.  Do you still have the issue?

If so, type in chat in game
`/estatus` and upload a full UI screenshot

Also, test with no addons, just the Blizzard UI.  How is it with no addons?

**Comment by Nightfireop** [comment]
![image](https://user-images.githubusercontent.com/129460934/228988108-47a2f2b8-e7c0-42ef-9726-0ea42f80ca33.png)
/luaerror on (nothing happens)

Tab works fine when add ons are on but elvi ui is off

**Comment by 1Botanica1** [comment]
Sorry, old habits from old command. 

Try again, 
`/edebug on`
test
If you have the issue, 
`/estatus` and upload a full UI screenshot

**Comment by Nightfireop** [comment]
![image](https://user-images.githubusercontent.com/129460934/228989843-e03d68b4-1f7b-4a95-92f2-f924bc02d16b.png)

Didn't work =\

**Comment by Repooc** [comment]
not an elvui issue, you prob unbound tab by mistake, which can rebind in the Options section -> keybinds -> targeting in wow settings
