### ISSUE TITLE
[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by mesostealthy** [tukui-org/ElvUI#932]
### What is the issue you are having?

When someone types a heart in the chat like ♥, it shows up as a box instead.

### What is the expected behavior?

It should show up as a heart and game like -> ♥

### What actually happened?

Someone types the heart in the chat and ELVUI display it as an empty box character instead of the heart, ALT + number pad 3 for example for the heart.

### Suggested Solution/Workaround

It shows up as a heart with ElvUI disabled, so maybe just need to display the right character.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That is the font that you have chosen for the chat.  

If the font doesn’t have that character, it shows up as an empty square. 

Change the chat font to something that has that.

**Comment by kodewdle** [comment]
@1Botanica1 is correct here, emojis would normally work (as not an emoji) but mapping it to an emoji would be ok too, so i did that.
