### ISSUE TITLE
Include an option to display seconds in the Time DataText

### ISSUE THREAD

**Issue by Beleynn** [tukui-org/ElvUI#936]
I'd like to request an option to show seconds be added to the Time DataTexts

![time datatext](https://user-images.githubusercontent.com/34138536/229827345-bc3f1e8b-277c-418d-84b0-c23eb2b7d901.png)

**Comment by AphelionZero** [comment]
This would be great!!!

**Comment by Merathilis** [comment]
It's completed. So closing
