### ISSUE TITLE
[Retail Bug Report] ELVNP_Test:SETSCALE

### ISSUE THREAD

**Issue by Trenchfoote** [tukui-org/ElvUI#937]
### What is the issue you are having?

LUA with the ELVUI NP Test frame displayed while in combat.

### What is the expected behavior?

No LUA error.

### What actually happened?

LUA popped. No other issue or detriment to gameplay.

### Errors

```shell
1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_Libraries' tried to call the protected function 'ElvNP_Test:SetScale()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetScale'
[string "@ElvUI/Core/Modules/Nameplates/Nameplates.lua"]:273: in function `ScalePlate'
[string "@ElvUI/Core/Modules/Nameplates/Elements/Threat.lua"]:68: in function <...ns/ElvUI/Core/Modules/Nameplates/Elements/Threat.lua:33>
[string "=[C]"]: in function `PostUpdate'
[string "@ElvUI_Libraries/Core/oUF/elements/threatindicator.lua"]:87: in function <...lvUI_Libraries/Core/oUF/elements/threatindicator.lua:37>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [ ] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That is a taint, not an error - see https://github.com/tukui-org/ElvUI/wiki/errors

Please type in chat in game `/edebug on` and test.  Do you have any issues?  If so, type in chat in game `/estatus` and upload a full UI screenshot (no cropping) showing the issue and the status panel.
