### ISSUE TITLE
[Wrath Bug Report] <Title here>

### ISSUE THREAD

**Issue by czube** [tukui-org/ElvUI#938]
### What is the issue you are having?

<img width="1280" alt="Target cast" src="https://user-images.githubusercontent.com/130065789/230392425-4c76cc79-c785-4ca7-8d72-a7a4e77ac1a0.png">

Hi! 
I'm having issue to move a bar that is circled in a red color above the target frame (green color). I was trying to find a way to move it above the target frame 
in add on settings but unfortunately couldnt do it, i was hoping maybe you guys could help me out with this? 
Thank you! 

### What is the expected behavior?

n/a

### What actually happened?

I'm having issue to move a bar that is circled in a red color above the target frame (green color). I was trying to find a way to move it above the target frame 
in add on settings but unfortunately couldnt do it, i was hoping maybe you guys could help me out with this? 

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
thats called Aura Indicator and is attached to the frame by default and adjustments are done in that section. you can select to detach from the frame and use `/moveui` to move it after u make that selection.  A general question about how to configure elvui is best suited in our discord server as the ticket system is mainly for actual errors/issues. https://discord.gg/xFWcfgE in case you didn't see the chat link on our website on tukui.org
