### ISSUE TITLE
[Classic Bug Report] Raid frame groups disappear on entering instance

### ISSUE THREAD

**Issue by mutantgirl** [tukui-org/ElvUI#940]
### What is the issue you are having?

I use Raid Frame 3 for out 40 man raids. While gathering I can see all groups for buffing and whatnot. On entering the raid instance, groups 7 and 8 disappear and nothing I do gets them back.

Additionally, while outside an instance friendly nameplates works as expected. On entering any dungeon or raid instance, the nameplates revert to native Blizzard nameplates.

Both of these bugs are impairing my ability to heal effectively. Any help would be appreciated.

### What is the expected behavior?

I have 8 rows defined in my settings, and I can see them outside the raid instance. They should remain when entering the raid.
![image](https://user-images.githubusercontent.com/130291911/230773607-9488a6e9-d51e-450d-b810-64d10d336451.png)

Blizzard nameplates for my raidmates should not appear when friendly nameplates are turned on. I wish to see the ElvUI nameplates I defined and as they appear outside raid and dungeon instances.

### What actually happened?

On entering raid instance, groups 7 and 8 simply disappear.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
> Additionally, while outside an instance friendly nameplates works as expected. On entering any dungeon or raid instance, the nameplates revert to native Blizzard nameplates.

> Blizzard nameplates for my raidmates should not appear when friendly nameplates are turned on. I wish to see the ElvUI nameplates I defined and as they appear outside raid and dungeon instances.

Friendly nameplates are restricted and can't be altered/modified by addons in instances.

Regarding the unitframe issue, can u see if u have the option Max Allowed enabled in the unitframes -> general section and disable it and then test.

Future tickets, only 1 issue per ticket

**Comment by mutantgirl** [comment]
Understood. Wasn't sure if they were somehow related.

Yes I do have max allowed enabled:
![image](https://user-images.githubusercontent.com/130291911/230790966-64545042-996e-428d-9cf4-2300086030a9.png)

**Comment by Repooc** [comment]
You never specified if you tested with that option disabled yet.  Sounds like it could be ur issue but need some verification.

**Comment by mutantgirl** [comment]
Raid was cancelled due to Easter, haven't had a chance to test yet. Hopefully Tuesday night I'll have an opportunity.

**Comment by Repooc** [comment]
> Raid was cancelled due to Easter, haven't had a chance to test yet. Hopefully Tuesday night I'll have an opportunity.

boo, tell them that's unacceptable lol

**Comment by mutantgirl** [comment]
Ran MC last night. Worked like a charm. Thanks so much!
