### ISSUE TITLE
[Retail Bug Report] Minimap moved out of anchor on login

### ISSUE THREAD

**Issue by Nokramx** [tukui-org/ElvUI#942]
### What is the issue you are having?

Sometimes, when i login, the minimap gets moved out of its anchor and then always ends up in the exact position from the screenshot.
A /reload always fixes that.

i started noticing this issue after 10.0.7 launched but it happened very rarely. 
A few days ago i created a new alt and now the issue seems so occur much more often (on the new character)

I tried to get help in the elvui discord and it may look like the issue is the blizzard edit mode. 
but from what i see it also may be an elvui bug.

![XSQTftU](https://user-images.githubusercontent.com/51278436/231544603-4f8917db-1fd8-4ef6-9af6-c07221894d65.jpg)

### What is the expected behavior?

Minimap always should be where the anchor is

### What actually happened?

I log into the game, -> minimap (sometimes) is not where the minimap anchor is -> /reload -> minimap is where it is supposed to be

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Luckyone961** [comment]
Should no longer be an issue in 13.40+
