### ISSUE TITLE
[Retail Bug Report] [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UseAction()'.

### ISSUE THREAD

**Issue by Lannakin** [tukui-org/ElvUI#943]
### What is the issue you are having?

v. 13.29

Action bar refuses to accept keypress commands/interactions, but will accept being cursor-clicked on, after changing talents around.  Also sets a LUA error.

Note:  I do not use the ElvUI actionbars, I use the default game ones.  It also seems like there's a time factor involved because I'm having trouble replicating it, although it seems to eventually happen every time I log in.  I was able to get it to be more consistent by:

1. Wait about 3-5 minutes.
2. Change a talent in one loadout, accept, then change it back, accept again.
3. Switch to a different loadout, repeat the above sequence.
4. Try to cast a spell.

### What is the expected behavior?

1. Changed some talents and accepted changes.  
2. Switched to another talent loadout.
3. Try to cast a spell.
4. Action bar accepts keypress and click interactions.

### What actually happened?

1. Changed some talents and accepted changes.  
2. Switched to another talent loadout.
3. Try to cast a spell.
4. Action bar refuses all keypress interactions, but can interact with clicking.  It does make the loud "CLACK" sound that you hear when you try to cast a spell during an existing cast or a GCD.

### Errors

```shell
4x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:89: in function `TryUseActionButton'
[string "@FrameXML/ActionButton.lua"]:124: in function `ActionButtonDown'
[string "ACTIONBUTTON10"]:2: in function <[string "ACTIONBUTTON10"]:1>
```
```


### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Type in chat in game 
`/edebug on` 

Test - try to replicate the issue, go through the steps that causes it. Does it still happen?  

If so, type in chat in game `/eststus` and upload a full UI screenshot (no cropping)

**Comment by Lannakin** [comment]
Ok, I was trying to replicate it too soon after using `/edebug on`

[Imgur](https://imgur.com/h6IWBNz)

I'm so sorry for how long it took me to respond.

**Comment by 1Botanica1** [comment]
See #643 - could be same issue

**Comment by Lannakin** [comment]
> Test with no addons, blizzard UI

I have just retested this issue with my Interface and WTF folders moved out of WoW's directory and even in the default UI with no addon files/settings enabled or even accessible to WoW, but cannot replicate it.

Looking at the issue you've linked in your other message, I would not be surprised if they are linked.  I will comment that if ElvUI had a mouseover function for the actionbars, I'd probably be using the ElvUI actionbars.

**Comment by kodewdle** [comment]
closed, dup of https://github.com/tukui-org/ElvUI/issues/643
