### ISSUE TITLE
Threat data bar doesn't show.[Retail Bug Report] <Title here>

### ISSUE THREAD

**Issue by AphelionZero** [tukui-org/ElvUI#944]
### What is the issue you are having?

I enabled the threat data bar, however the bar never appears, in combat or otherwise.

### What is the expected behavior?

I expected to see the bar while in combat showing my current threat level.

### What actually happened?

I can see, and move the bar when I toggle anchors, however the bar never appears.

### Suggested Solution/Workaround

I have tried disabling all other addons except ElvUI, ElvUI Libraries, and ElvUI Options. Same outcome. 

### Errors

```shell
No lua error is thrown.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by AphelionZero** [comment]
Alright, I tested in a group and it works as intended. Is there any way to allow the threat bar to function outside of a group?

**Comment by Repooc** [comment]
no that is not an option we have in place

**Comment by Azilroka** [comment]
The threat api needs to have units to compare them against. Solo will always return 100% and therefore useless data to show.
