### ISSUE TITLE
[Wrath Bug Report] <Keybind and macro text location>

### ISSUE THREAD

**Issue by pyrodaredevil** [tukui-org/ElvUI#947]
### What is the issue you are having?

This is a constant issue.

### What is the expected behavior?

I should be able to adjust the text location of both the keybind text and macro text on my action bars. In general under submenu "apply to all" or Player Bars keybind text and macro text

### What actually happened?

In General "Apply to All" regardless of the position menu or both the X-Offset and Y-Offset the keybind and macro text does not change. 
In the player bars menu under both keybind text and macro text the postions are grayed out and unable to be changed.

### Errors

```shell
no errors listed
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
Sounds like you are using Masque which the macro and keybind text is handled by the skin/masque and not elvui which is why its greyed out in the individual bar. if you want elvui to handle those, you will need to disable masque
