### ISSUE TITLE
[Classic Bug Report] Lua Error when Pet Dies / Party Members Drop Group in Combat

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#948]
### What is the issue you are having?

OK, so narrowing this one down a bit... 

If my pet dies, or gets too far away and despawns, or someone leaves group in combat... I get a Lua error. 

### What is the expected behavior?

No Lua Error.

### What actually happened?

Lua Error.

### Errors

```shell
Message: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'OverrideActionBarButton3:Show()'.
Time: Sat Apr 22 14:25:57 2023
Count: 1
Stack: ADDON_ACTION_BLOCKED: ElvUI tried to call the protected function 'OverrideActionBarButton3:Show()'.
[string "@Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...tie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Questie/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Questie/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/Questie/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `Show'
[string "@Interface/FrameXML/ActionButton.lua"]:368: in function `ActionButton_Update'
[string "@Interface/FrameXML/ActionButton.lua"]:705: in function `ActionButton_OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:208: in function <Interface/FrameXML/ActionButton.lua:205>

Locals: <none>

```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Gogo1951** [comment]
Also I also got that error when switching between a Hunter and a Warlock (they share a settings profile). It said, "Checking stables, can't find Warlock Pet" when i was on my hunter.

**Comment by 1Botanica1** [comment]
You have other addons enabled when you have reported that taint, not just ElvUI 


That is a taint, not an error - see https://github.com/tukui-org/ElvUI/wiki/errors

Please type in chat in game `/edebug on` 
and test. Do you have any issues? If so, type in chat in game `/estatus` and upload a full UI screenshot (no cropping) showing the issue and the status panel.

**Comment by Azilroka** [comment]
That's a Blizzard error.
