### ISSUE TITLE
[Classic Bug Report] Issue Sharing Settings Profile between Hunter & Lock

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#949]
### What is the issue you are having?

Leveling a New Lock, and I hit some bugs whenever I learned a new pet.

Then, logging off the lock, and back onto the hunter, I hit the bug on the hunter. Only the hunter, not any other class.

### What is the expected behavior?

No Lua Errors.

### What actually happened?

Lua Errors.

### Suggested Solution/Workaround

Doing a reload fixes the issue, but it seems to come back periodically. It was right after I learned a new pet ability on my Warlock that it started.

### Errors

```shell
1st 

2x Interface_Wrath/FrameXML/PetStable.lua:180: bad argument #4 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface_Wrath/FrameXML/PetStable.lua"]:180: in function <Interface_Wrath/FrameXML/PetStable.lua:42>
[string "=[C]"]: in function `PetStable_Update'
[string "@Interface_Wrath/FrameXML/PetStable.lua"]:28: in function <Interface_Wrath/FrameXML/PetStable.lua:13>

Locals:
(*temporary) = "Level %1$d %2$s|n%3$s"
(*temporary) = 19
(*temporary) = "Voidwalker"
(*temporary) = nil
(*temporary) = "string expected, got nil"

2nd - Slightly different

2x Interface_Wrath/FrameXML/PetStable.lua:151: bad argument #5 to 'SetFormattedText' (string expected, got nil)
[string "=[C]"]: in function `SetFormattedText'
[string "@Interface_Wrath/FrameXML/PetStable.lua"]:151: in function <Interface_Wrath/FrameXML/PetStable.lua:42>
[string "=[C]"]: in function `PetStable_Update'
[string "@Interface_Wrath/FrameXML/PetStable.lua"]:28: in function <Interface_Wrath/FrameXML/PetStable.lua:13>

Locals:
(*temporary) = PetStableLevelText {
 0 = <userdata>
}
(*temporary) = "%1$s Level %2$d %3$s|n%4$s"
(*temporary) = "Sarnagma"
(*temporary) = 19
(*temporary) = "Voidwalker"
(*temporary) = nil
(*temporary) = "string expected, got nil"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That error isn’t mentioning ElvUI 

Please type in chat in game /edebug on and test. Do you have any issues? If so, type in chat in game /estatus and upload a full UI screenshot (no cropping) showing the issue and the status panel.

**Comment by Azilroka** [comment]
That's a Blizzard error
