### ISSUE TITLE
[Retail Bug Report] War Mode Text Bug (Space Missing)

### ISSUE THREAD

**Issue by AnimeDrache** [tukui-org/ElvUI#950]
### What is the issue you are having?

Just a small issue that needs to be fixed by you. When enabling "War Mode", there is a space missing between the left Icon and the text in the info bar (see attachment).
![Unbenannt](https://user-images.githubusercontent.com/51856826/233832166-3204018f-411a-42e7-b65a-e833d3c08406.png)

### What is the expected behavior?

1 more space between the left icon and the text

### What actually happened?

The left Icon is too close to the text.

### Suggested Solution/Workaround

You just add a space ♥

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
done 🌼

**Comment by AnimeDrache** [comment]
> done 🌼

Awesome! Can't wait for the update! =D
