### ISSUE TITLE
[Wrath Bug Report] Title Selection Checkboxes Work But Don't Look Right

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#952]
### What is the issue you are having?

![image](https://user-images.githubusercontent.com/55365231/234199146-bba681b2-db93-4375-a56c-fda74e426aad.png)

It shows a few of them as being checked. Odd.

### What is the expected behavior?

Do we need checkboxes there? May be find with just the dropdown.

### What actually happened?

See picture. This has been a bug for a long time, but it's super trivial.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
How does it show with no addon, blizzard UI? Does it have the checkboxes? 

The character frame is a blizzard frame, ElvUI skins it.

**Comment by Gogo1951** [comment]
JFC Blizzard needs to fix their shit! (=
