### ISSUE TITLE
[Wrath Bug Report] Picking out a Macro during Combat Gives Lua Error / Taint Error

### ISSUE THREAD

**Issue by Gogo1951** [tukui-org/ElvUI#955]
### What is the issue you are having?

In combat, I accidentally dragged a button off my bar. I went to get the macro back, and got an error in-game when trying to interact with the macro and put it on my bar while I was in combat. Also saw an error in taint log.

I didn't disable other add-ons, but the errors seem pretty specific to ElvUI.

### What is the expected behavior?

No Error.

### What actually happened?

Got Error.

### Errors

```shell
### Lua Error

5x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'PickupMacro()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `PickupMacro'
[string "@Blizzard_MacroUI/Blizzard_MacroUI.lua"]:42: in function <Blizzard_MacroUI/Blizzard_MacroUI.lua:40>

### Taint Log 

4/29 21:42:54.250  An action was blocked in combat because of taint from ElvUI - PickupMacro()
4/29 21:42:54.250      Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:42
4/29 21:42:56.352  Global variable INTERFACE_ACTION_BLOCKED_SHOWN tainted by ElvUI - Interface_Wrath/FrameXML/UIParent.lua:4722 DisplayInterfaceActionBlockedMessage()
4/29 21:42:56.352      Interface_Wrath/FrameXML/UIParent.lua:1090
4/29 21:42:56.352      PickupMacro()
4/29 21:42:56.352      Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:42
4/29 21:42:56.352  Execution tainted by ElvUI while reading INTERFACE_ACTION_BLOCKED_SHOWN - Interface_Wrath/FrameXML/UIParent.lua:4719 DisplayInterfaceActionBlockedMessage()
4/29 21:42:56.352      Interface_Wrath/FrameXML/UIParent.lua:1090
4/29 21:42:56.352      PickupMacro()
4/29 21:42:56.352      Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:42
4/29 21:42:56.352  An action was blocked in combat because of taint from ElvUI - PickupMacro()
4/29 21:42:56.352      Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:42
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Is it causing the macro not being able to be moved or just showing the taint? 

Please also always test with just ElvUI 

Type in chat in game 
`/edebug on`

Test - do you have the issue?  

If so, type in chat in game `/estatus` and upload a full ui screenshot (no cropping) showing both the issue and the status panel. 

More about taints here https://github.com/tukui-org/ElvUI/wiki/errors

**Comment by Gogo1951** [comment]
As soon as you pick up the macro from your macro UI, it gives the error. You can't drop it on your bar, the moment you pick it up it tosses and error and you de-select the macro you were "holding."

This was the only entry in the taint log.

**Comment by 1Botanica1** [comment]
Please follow the instructions above, test and provide the requested screenshot

**Comment by Gogo1951** [comment]
I can't tell if I have the error because that turns off bug sack.

![image](https://user-images.githubusercontent.com/55365231/236107591-0ed2c087-fa50-4b8a-b027-343e73681dac.png)

**Comment by 1Botanica1** [comment]
You said that you can’t drop the macro on the bar and it deselects the macro you were holding. 

Do you still have the issue when going through all of the troubleshooting steps?

**Comment by 1Botanica1** [comment]
So apart from the taint, it isn’t causing any issues to game play?

**Comment by Luckyone961** [comment]
AddOns are not allowed to modify UI panels in combat, moving a icon skinned by ElvUI around counts as modifying and will always error. Don't do that kind of things in combat or disable the ElvUI skin for it if you to it regulary.
