### ISSUE TITLE
[Retail Bug Report] <LibElvUIPlugin-1.0.lua:110: bad argument #1 to 'GetAddOnMetadata'>

### ISSUE THREAD

**Issue by Hollicsh** [tukui-org/ElvUI#957]
### What is the issue you are having?

Error pops up when entering the game

### What is the expected behavior?

Probably shouldn't have this error

### What actually happened?

Error pops up when entering the game

### Errors

```shell
1x ...aries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua:110: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name LibElv-UIButtons-1.0. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: in function `GetAddOnMetadata'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua"]:110: in function `RegisterPlugin'
[string "@ElvUI_SLE/libs/LibElv-UIButtons-1.0/LibElv-UIButtons-1.0.lua"]:565: in main chunk

Locals:
(*temporary) = "LibElv-UIButtons-1.0"
(*temporary) = "Title"
(*temporary) = "Invalid AddOn name LibElv-UIButtons-1.0. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"

---
---
---

1x ...aries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua:110: bad argument #1 to 'GetAddOnMetadata' (Invalid AddOn name LibElv-GameMenu-1.0. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable))
[string "=[C]"]: in function `GetAddOnMetadata'
[string "@ElvUI_Libraries/Core/LibElvUIPlugin-1.0-41/LibElvUIPlugin-1.0.lua"]:110: in function `RegisterPlugin'
[string "@ElvUI_SLE/libs/LibElv-GameMenu-1.0/LibElv-GameMenu-1.0.lua"]:120: in main chunk

Locals:
(*temporary) = "LibElv-GameMenu-1.0"
(*temporary) = "Title"
(*temporary) = "Invalid AddOn name LibElv-GameMenu-1.0. - Usage: local value = C_AddOns.GetAddOnMetadata(name, variable)"
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That isn’t from ElvUI 

You have checked you tested with `/edebug on` but it seems you haven’t. That command disables all addons except ElvUI 

That is from S&L which needs to be updated.  Please report any issues with S&L directly to the authors.

**Comment by Hollicsh** [comment]
Shit ...
Confused, rushed, sorry ..
