### ISSUE TITLE
Nameplates not showing

### ISSUE THREAD

**Issue by nebnar** [tukui-org/ElvUI#958]
### What is the issue you are having?

13.30 caused an issue where the nameplates are not showing unless you are targeting a player.  The screenshot below shows me targeting an enemy player in the background, but the foreground enemy nameplate is not active.

![WoWScrnShot_050323_165539](https://user-images.githubusercontent.com/132510563/236047681-c6ab82c7-17d5-40d7-b119-f21b599cc65c.jpg)

### What is the expected behavior?

Would like it where nameplates always show unless i turn them off

### What actually happened?

downloaded 13.30 and logged on.  Updated all Curseforge addons

### Suggested Solution/Workaround

no change except chat disappeared

### Errors

```shell
none seen
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That is a blizzard thing, happens with no addons as well. 

**Blizzard issue.**
Run this command (type in chat in game) to workaround it:
`/run SetCVar("nameplatePlayerMaxDistance", 60)`

**Comment by kodewdle** [comment]
yep^
