### ISSUE TITLE
[Retail Bug Report] ElvUI does not give the right actionbar for WQ 'Rolie Polie Molie'

### ISSUE THREAD

**Issue by jeremy-hill** [tukui-org/ElvUI#960]
### What is the issue you are having?

(Checked closed and open comments and couldn't find a writeup for this, but I suspect you might know about it). Anyway, as per other comments on https://www.wowhead.com/ptr/quest=73698/rolie-polie-molie: 

> I'm not entirely sure why but ElvUI for me is making it so the correct abilities aren't showing for this WQ. I tried checking the visibility state of all the bars and they're all empty or my other bars. Turning off ElvUI gives the correct abilities to complete this WQ. Am I the only one with this problem?

ElvUI makes the action bar for the quest as such:
![image](https://user-images.githubusercontent.com/66854273/236065982-168d567f-3663-4557-bb3c-0fc172205649.png)

With ElvUI disabled: 

![image](https://user-images.githubusercontent.com/66854273/236066054-55712472-fd28-4a49-bd24-fa76bc71f448.png)

### What is the expected behavior?

Correct action bar buttons for the quest.

### What actually happened?

Wrong buttons.

### Suggested Solution/Workaround

Disable ElvUI.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This is already fixed in dev and will be in next release

**Comment by 1Botanica1** [comment]
https://github.com/tukui-org/ElvUI/archive/refs/heads/development.zip
Link to the dev version - see the ElvUI discord if help is needed installing
