### ISSUE TITLE
[Feature Request] Add further customization to Aura Bars

### ISSUE THREAD

**Issue by Toasticon** [tukui-org/ElvUI#962]
**Is your feature request related to a problem? Please describe.**
What's being done to Aura Bars is great, but I wish there was a way to limit the amount you can view as well as being able to further customize the layout instead of relying on my DIY weakaura. Tracking important buffs for tanks, procs and RtB buffs (or trinkets) is pretty much the only thing I use it for but it clashes with everything else.

**Describe the solution you'd like**
A way to hide aura name(s) and only show the icon and duration if possible. Think buffs, but limited to only 2-4 auras that are much bigger and important. I don't mind creating my own filter or having a predefined one (can help with that).

**Describe alternatives you've considered**
WA/EBB. Shadowed Unit Frames had an option to enlarge your own auras but you can imagine how weird that looks.

**Additional context**

**Comment by Repooc** [comment]
Just to do some clarification of the request.  Sounds like your request is really just the ability to hide the aura name on aura bars.
For limiting the amount you can view:  There is an option, Max Bars, which will set a hard limit of amount of auras that will be shown.
What auras are able to be shown is of course controlled by the filter priority you have set.  Technically this could be a way to limit the amount of auras shown if u have your own filters with the only auras u want to track but the real way to control how many can be seen at a given time is handled by the Max Bars option.

**Comment by Toasticon** [comment]
While that may be true, my idea is more inline with something shown with the first 2 examples here:
![preview](https://user-images.githubusercontent.com/33032465/236481504-164ee42f-64dd-4761-8c89-582f99393c81.png)
https://legacy.curseforge.com/wow/addons/auratracker
And it seems someone had the exact the same issue and thought up something similar. So we can close this, but I appreciate the help nonetheless. Just clarify; I don't want the bars to show up either just, a huge Aura like with the regular UI de/buffs (or actionbars) with a fancy timer.

**Comment by Azilroka** [comment]
The bars on the left is basically aurabars just inverted with the icon on the right.

**Comment by Repooc** [comment]
> While that may be true, my idea is more inline with something shown with the first 2 examples here: ![preview](https://user-images.githubusercontent.com/33032465/236481504-164ee42f-64dd-4761-8c89-582f99393c81.png) https://legacy.curseforge.com/wow/addons/auratracker And it seems someone had the exact the same issue and thought up something similar. So we can close this, but I appreciate the help nonetheless. Just clarify; I don't want the bars to show up either, just a huge Aura like with the regular UI de/buffs (or actionbars) with a fancy timer.

If u just want an aura then that is what the buffs (or debuffs) section for that unitframe is for which is just an icon and cd text. So no we wouldn't remove the bar from aurabars.
