### ISSUE TITLE
UI taint when attempting to bonus roll after reload

### ISSUE THREAD

**Issue by Taizunz** [tukui-org/ElvUI#964]
### What is the issue you are having?

If you /reload after a bonus roll frame has appeared and then try to perform the bonus roll after the reload by clicking the Dice button, it fails and the button becomes irresponsive.

### What is the expected behavior?

For the bonus roll button to work regardless of whether you try to click it before or after a /reload

### What actually happened?

1. Defeated a boss that prompted a bonus roll frame to appear, i.e. Sha of Anger in MoP.
2. Don't click anything in the bonus roll frame yet.
3. Do a /reload
4. Now try to click the bonus roll dice.
5. Lua error is thrown and the button taints/becomes irresponsive to any further clicks.
6. Additional /reload's don't fix this. A full ElvUI disable is required if the user wishes to perform the bonus roll at this point.

### Errors

```shell
[ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'AcceptSpellConfirmationPrompt()'.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Taizunz** [comment]
![image](https://user-images.githubusercontent.com/15648000/236466927-80af1909-b4ed-4731-bf1c-27b4a2de1a2e.png)

**Comment by 1Botanica1** [comment]
I don’t see the issue in that screenshot. 

the bonus roll

**Comment by Taizunz** [comment]
The issue + estatus:
https://user-images.githubusercontent.com/15648000/236474396-c08944d0-3907-41ca-9fef-b578d962fb7c.mp4

Vanilla/no addons where I perform the exact same steps:
https://user-images.githubusercontent.com/15648000/236475833-bd566c89-6aec-49a6-b650-7cbcc2b769a9.mp4

**Comment by Ankhsalot** [comment]
Hi, I have been having the same issue, screenshots attached. Seems to happen on last boss only in raid ie not all the time.
![WoWScrnShot_110323_104557](https://github.com/tukui-org/ElvUI/assets/149287140/61837df3-2c8c-4918-b2ac-4b30a3e7802c)
![WoWScrnShot_110323_104442](https://github.com/tukui-org/ElvUI/assets/149287140/35784182-e478-42b7-bb7f-be5b1c881d0d)


Message: ADDON_ACTION_FORBIDDEN: ElvUI tried to call the protected function 'AcceptSpellConfirmationPrompt()'.
Time: Fri Nov  3 10:44:23 2023
Count: 1
Stack: ADDON_ACTION_FORBIDDEN: ElvUI tried to call the protected function 'AcceptSpellConfirmationPrompt()'.
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `AcceptSpellConfirmationPrompt'
[string "*GroupLootFrame.xml:228_OnClick"]:1: in function <[string "*GroupLootFrame.xml:228_OnClick"]:1>

Locals: handlers = <table> {
  = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109
}
index = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 NewModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 EnableModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 SecureHook = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:335
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 RawHookScript = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:394
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 name = "ElvUI_DebugTools"
 Initialize = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:114
 IsEnabled = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 baseName = "ElvUI"
 DisableModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 StaticPopup_Show = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:108
 TaintError = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:103
 PLAYER_REGEN_DISABLED = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:99
 PLAYER_REGEN_ENABLED = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:94
 RegisterMessage = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 ScriptErrorsFrame_OnError = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:87
 ScriptErrorsFrame_UpdateButtons = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:74
 IsHooked = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceHook-3.0/AceHook-3.0.lua:492
 ModifyErrorFrame = <function> defined @Interface/AddOns/ElvUI/Core/Modules/Misc/DebugTools.lua:39
 HideFrame = Frame {
 }
 IsModule = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 SendMessage = <function> defined @Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/Callba

**Comment by kodewdle** [comment]
since The War Within is out and this is a taint, reopen if you still have the issue please :)
