### ISSUE TITLE
BonusRollFrame mover/anchor no longer available

### ISSUE THREAD

**Issue by Taizunz** [tukui-org/ElvUI#965]
### What is the issue you are having?

I can't reposition the BonusRollFrame with ElvUI as the mover/anchor for it isn't available.

Video showing the lack of a mover + edebug on + estatus:
https://user-images.githubusercontent.com/15648000/236480019-8762fa9b-9291-4ca2-a3ac-ee77f93c99fa.mp4

### What is the expected behavior?

For the BonusRollFrame mover/anchor to be available.

### What actually happened?

Since Dragonflight 10.1 released the BonusRollFrame has moved into a less suitable position for me, so I wanted to reposition it in ElvUI via /moveui (or ElvUI -> Toggle Anchors) but immediately noticed that there is no mover/anchor for it at all.

I don't know if the mover disappeared with DF 10.1 or ElvUI 13.31 or earlier, as I haven't had to reposition this frame in months, if not years.
A quick look at ElvUI changelogs makes it clear that a mover for this frame was added in ElvUI 10.73 in 2018, but I don't see any other mentions of it potentially being removed or broken since then.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by kodewdle** [comment]
it was broken for some time of Edit Mode, thanks for the report :) fixed it in development
