### ISSUE TITLE
[TBC Bug Report] Chat window not snapping into place in right position

### ISSUE THREAD

**Issue by DrSterni** [tukui-org/ElvUI#97]
### What is the issue you are having?

Everytime after logout the chat window which I put into the right positioned chat-frame loses it's position inside the frame.

After going into the chat-options for this particular chat-window and there resetting the window, I am able to drag&drop it into the right position and there it sticks exactly where it should be.

Until the next login, after that it's sort of "broken" again.

### What is the expected behavior?

Chat-window should stay in place.

### What actually happened?

see above.

### Suggested Solution/Workaround

see above (resetting the frame all the time).

### ElvUI Changelog/Troubleshooting

- [x] #100

**Comment by 1Botanica1** [comment]
TROUBLESHOOTING STEPS
1)Type in chat in game /edebug on
2) Test - Do you still have the issue?
3) If you still have the issue/error, type in chat in game `/estatus` and upload a FULL UI screenshot (no cropping) showing both the issue/error and the estatus panel.

**Comment by DrSterni** [comment]
It seems to work fine after activating the debug-mode (and even disabling it afterwards). Thank you! I will re-open this ticket if the problem occurs again later.

**Comment by DrSterni** [comment]
No, problem is not solved (as I thought).

You can see the right chat window ("Plündern / Handeln") is not really fitting the chat frame.

As I said: resetting the window would put it into the left chat frame, perfectly matching the borders. Dragging it from there to the right window would make it work again for one session.

![WoWScrnShot_120721_005553](https://user-images.githubusercontent.com/48457416/144941389-6d35c876-c972-473c-a2c7-70eb538dc111.jpg)

**Comment by 1Botanica1** [comment]
You have other addons enabled. 

Try to recreate the issue with only ElvUI

/edebug on

Then log out & back in -

**Comment by Repooc** [comment]
in addition to that, still looks like u may not have panel snapping enabled, and if u do, that window isnt even locked which u can tell its not locked (right click the chat tab and select lock) by the little corner piece on the bottom right of the chat window.

Before doing anything I say below, make sure to do what Botanica suggests first.
The image is showing u where the panel snapping option is at, the video is showing me moving the chat window (left click and drag away and let go of left mouse button) then dragging it back and letting it "snap" into place, then locking the window.

![image](https://user-images.githubusercontent.com/1479745/144950710-94c74b12-8cf3-4ab5-abd6-6166cc882253.png)

https://user-images.githubusercontent.com/1479745/144950755-94fd6ea0-b726-4864-9fab-e276adc0d6e5.mp4

**Comment by DrSterni** [comment]
Thanks for the advice!

Yes, panel snapping is (and was) always on. The "drag & drop"-feature is crystal-clear, but thanks for the explanation anyways.

Here's another screenshot of just ELVUI running and still that bug.

Even if panel snapping is on, the chat window will NOT fall into place. Strange, isn't it?

![WoWScrnShot_120721_233522](https://user-images.githubusercontent.com/48457416/145119715-b8a91f3b-4f34-4122-b0df-f40b112de423.jpg)

**Comment by Ernest314** [comment]
Chat panels cannot snap to the right side, all these other people don't know what they're talking about.

The snapping behavior is Blizzard's, Elvui just skins over it. Blizzard only has chat frames on the left, so snapping only works on the left. The right side panels are manually positioned and locked.

**Comment by kodewdle** [comment]
@DrSterni  if this happens, try to rerun **Setup Chat** part of installer and verify your **chat-cache.txt** is not read-only (or being replaced); optionally you can also try:  **/run SetCVar('synchronizeChatFrames', 0)**
basically - the problem will reappear if the game syncs the **chat-cache.txt** from the server (like if you play on two different computers).

@Ernest314  this is true for what we refer to as **docking**;  snapping however was designed and written by me.  you can move the main chat to the right panel by pulling both chats out of their panel and swapping them into the opposite panel.  however you will still be limited to only one dock, as you said.

**Comment by Ernest314** [comment]
Oh! I see what you mean now, my bad. That does make more sense.

**Comment by memostar91** [comment]
I had this problem on retail as well. I copy my main Elvui profile to my other characters; after copying the profile, the snapping gets broken. I followed things mentioned here, unfortunately none of these solved the issue. I used "reset chat positions" button in the default chat settings UI for the chat tab I was trying to snap to the right panel, then the snapping worked just fine.

**Comment by Repooc** [comment]
`/run ElvUI[1].Chat:ClearSnapping();ReloadUI()`
Should do it for ya

**Comment by Psykosa** [comment]
> `/run ElvUI[1].Chat:ClearSnapping();ReloadUI()` Should do it for ya

A few years late, but just wanted to say thank you. This worked perfectly for me 😄
