### ISSUE TITLE
[Retail Bug Report] Datatext export/import format: table - missing data for datatext

### ISSUE THREAD

**Issue by helmuth99** [tukui-org/ElvUI#970]
### What is the issue you are having?

When exporting a profile with the format table, the datatext wont work for some reason when being imported directly to ElvDB["profiles"][private.Profilename], because there is missing data in ElvDB["global"]["datatext"][datatext-name]. In the end the Panel is registerd but shows a black entry. [https://gyazo.com/719a091888f38db9ab6684d01674cba2] Maybe it is intended that way. 

### What is the expected behavior?

When importing the profile directly to the DB, that the Datatext is working.

### What actually happened?

The panel didnt work and had only a blank entry.

### Suggested Solution/Workaround

When exporting the profile with the format: plugin you can search for the lines (2) that do the same thing as in the Savevariable (1) and it sometimes will fix it and sometimes it wont.

(1) Data in profile SavedVariables (https://gyazo.com/bbe684f8a4366683abe4cefd5c63a417)
(2) Lines of code from format plugin (https://gyazo.com/01c18845495b1f0e9ca37ba3b6f6a879)

### Errors

```shell
No error
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by helmuth99** [comment]
https://gyazo.com/4d4738223d1f5f4d81e38964ed6b8e5e
I added the missing part from global like above and added it to ElvDB["global"]["datatext"][datatext-name] and it works now.

**Comment by Azilroka** [comment]
The custom panel is setup globally and is not part of the profile export. You would need to export the global table for that.

**Comment by Repooc** [comment]
sounds more like an issue with the user not exporting the global db, so closing.  reopen if u find exporting global doesnt yield the desire db entries
