### ISSUE TITLE
[Feature Request] Minimap north marker

### ISSUE THREAD

**Issue by italankin** [tukui-org/ElvUI#972]
**Is your feature request related to a problem? Please describe.**
With rotating minimap I find it easier to navigate with a north marker - saves time because you dont need to open big map.

For example, in Azure Vault after first boss people often miss the right door, because two doors are the same. With an additional guide you can quickly get your bearings and find the right exit.

**Describe the solution you'd like**
A north marker on minimap.

**Describe alternatives you've considered**
Disabling rotating minimap, but it makes navigation harder.

**Additional context**
I assume that north marker was a part of minimap itself in Shadowlands, but in Dragonflight it has moved to a separate blizzard frame, which is disabled in ElvUI.

**Comment by Repooc** [comment]
duplication of #750
