### ISSUE TITLE
[Feature Request] Debuffs Missing from Filters

### ISSUE THREAD

**Issue by 26209** [tukui-org/ElvUI#975]
**Is your feature request related to a problem? Please describe.**
There are some missing debuffs that I feel should be added. Some dungeon ones such as whirling dagger from freehold and many raid debuffs are not being shown. I do not have a complete list right now, another is oblivion debuff on sarkareth.

Edit: found some more
Brackenhide 
Gutshot: Crippling Bite
Trash: Necrotic Breath 382805

Echo of Neltharion
Volcanic Heart

**Describe the solution you'd like**
More testing being done with raid/dungeon spell ids.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tsumeno** [comment]
- Whirling Dagger from Harlan (https://www.warcraftlogs.com/reports/KBJj4gP8TaqcM72C/#fight=29&type=damage-taken&by=ability&pull=20)
- Firey Demise from Chargath (https://www.warcraftlogs.com/reports/KBJj4gP8TaqcM72C/#fight=22&type=damage-taken&by=ability&pull=9)
- Grapeshot dot from Eudora (https://www.warcraftlogs.com/reports/KBJj4gP8TaqcM72C/#fight=29&type=damage-taken&by=ability&phase=2) 

Just from the top of my head. I am sure there are more debuffs missing that should be visible by default, but those 3 were very noticeable missing.
