### ISSUE TITLE
[Retail Bug Report] Loot rolling with Master Loot in Raids broken

### ISSUE THREAD

**Issue by Mandibull82** [tukui-org/ElvUI#976]
### What is the issue you are having?

I was in Aberrus, we killed the first boss and I was unable to see the loot rolls frame, I was able to see the loot rolls window showing what others would be rolling, but not the actual loot roll interface. I was unable to roll for loot.

### What is the expected behavior?

Whn the boss dies we should see the loot rolls window showing what everyone else rolled, and the window for the loot allowing us to roll.

All I saw was the loot rolls window showing what everone else was rolling and some timer bars at the top for each item showing how much time was left to roll. I couldnt see any way to actually roll.

### What actually happened?

The boss died and the loot roll interface did not appear. No LUA errors came up, so it was a silent failure where we had the Blizzard original frame hidden by ElvUI but the replacement for it didnt seem to appear (unless I was blind).

I could see in the top-ish left of the UI the roll window showing what loot there was and what everone else was rolling for that loot. I could loot the boss and see the loot window. But the Roll frame with the need/greed/pass buttons was not visible.

I was in Aberrus at the time in normal difficulty, but I assume it would also happen in LFR. This was not an issue prior to 10.1, in 10.0.7 i ran a raid and I got to see the standard blizzard loot roll frames. That said I dont think they had the new frame back then for showing what others had rolled either (or at least I dont remember seeing it).

### Suggested Solution/Workaround

I dont really know, I just disabled the loot frame and the skin and then followed some instructuons that someone posted on the ElvUI classic forums to edit the below.

World of Warcraft\_retail_\Interface\AddOns\ElvUI\Core\Defaults\Private.lua

In the V.general section, change the below from true to false.
```
loot = true,
lootRoll = true,
```

In V.skins.blizzard section. Ensure loot = true.

This returned the blizzard loot roll frame and I was able to roll normally from then on in.

### Errors

```shell
There were no LUA errors triggered. So possibly an event not being handled or something??
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Revert any changes to the ElvUI code and test. 

Type in chat in game 
`/edebug on` 

Test - do you see the loot roll frame? 

If not, type in chat in game `/estatus` and upload a full ui screenshot (no cropping) showing both the issue and the status panel.

**Comment by mikeSGman** [comment]
I have the same issue, and had to /reloadui every boss we downed... it sucks.

**Comment by Mandibull82** [comment]
Hi, it seems like it works now for me on 13.33, not sure why it didnt work before. Although it is in a completely different location and smaller to the generic wow UI so maybe before I was just blind and not seeing it at the top of the screen as small thin bars with small icons previously.
