### ISSUE TITLE
[Retail Bug Report] <Range Fader>

### ISSUE THREAD

**Issue by Aldrahin** [tukui-org/ElvUI#978]
### What is the issue you are having?

Hello,
right now iam having an issue with the Range Fader from my Shaman/Evoker from the Unitframes.

Example: Iam using Riptide (40yards) on the Unitframe and it gets casted succesfully even tho the Unitframe is faded out like it would be when iam out of range. This issue is only occuring after i logged onto my Evoker heal where the Heals are only having 25-30yards Range. I´ve made numerous new Profiles and deleted the old ones to make sure its not a bugged Profile thing. But the issue remains the same.

![Elvui](https://github.com/tukui-org/ElvUI/assets/134162259/2d070db6-a714-4173-8708-b0d5c288a9b7)
https://streamable.com/3la51f -- Video Clip of it

### What is the expected behavior?

The Range Fader aint bugging out after logging onto the Evoker.

### What actually happened?

Explained Above

### Suggested Solution/Workaround

I´ve made sure to reinstall the Addon and turning off all the other Addons which were active, but the issue remains the same.
Closing the Game and restart it fixes the Issue but as you might guess is rlly annoying.

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/437

**Comment by 1Botanica1** [comment]
https://www.wowhead.com/news/patch-10-1-5-hotfixes-for-july-12th-class-bugfixes-delete-character-fix-334011?webhook
