### ISSUE TITLE
[Retail Bug Report] <Azerite is throwing error>

### ISSUE THREAD

**Issue by Naxterra** [tukui-org/ElvUI#979]
### What is the issue you are having?

Azerite Forge is throwing errors and I cannot select any powers

### What is the expected behavior?

Not generate any errors

### What actually happened?

On Heart of Azeroth screen it is generating errors.
![grafik](https://github.com/tukui-org/ElvUI/assets/41871948/0fa77e7b-39d4-41c1-9c28-45923664928c)

### Errors

```shell
Message: ...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun May 21 12:58:10 2023
Count: 1
Stack: ...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua"]:27: in function <...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:8>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1851: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1792: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:147: in function `loadFunc'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:179: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:172>
[string "=(tail call)"]: ?
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals: (*temporary) = <function> defined =[C]:-1



Message: ...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:840: attempt to index field 'buttons' (a nil value)
Time: Sun May 21 12:58:15 2023
Count: 1
Stack: ...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:840: attempt to index field 'buttons' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:840: in function `Refresh'
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:665: in function `Update'
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:169: in function <...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:163>

Locals: (*temporary) = <function> defined =[C]:-1

Message: ...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:840: attempt to index field 'buttons' (a nil value)
Time: Sun May 21 13:00:28 2023
Count: 1
Stack: ...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:840: attempt to index field 'buttons' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:840: in function `Refresh'
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:656: in function <...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:652>
[string "=[C]"]: in function `SetPendingActivationEssence'
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:671: in function `SetPendingEssence'
[string "@Interface/AddOns/Blizzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua"]:614: in function <...zzard_AzeriteEssenceUI/Blizzard_AzeriteEssenceUI.lua:610>

Locals: (*temporary) = <function> defined =[C]:-1
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
Please type in chat in game 
`/edebug on`
Test.  Do you still get the error? 

If so type in chat in game 
`/edebug on` 
And upload a screenshot showing both the error (click on first to show 1/x) and the status panel.  
Also, copy error here 

What are the steps to reproduce the error?

**Comment by Naxterra** [comment]
edebug on, issue occurs
![grafik](https://github.com/tukui-org/ElvUI/assets/41871948/4bdd6cf8-1c36-487a-849b-385ab01fce8b)

Message: ...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
Time: Sun May 21 14:03:45 2023
Count: 1
Stack: ...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua"]:27: in function <...dOns/ElvUI/Mainline/Modules/Skins/AzeriteEssence.lua:8>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1851: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI/Core/Modules/Skins/Skins.lua"]:1792: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/ElvUI_Libraries/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:545: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:147: in function `loadFunc'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:179: in function `ShowFrame'
[string "@Interface/FrameXML/PlayerInteractionFrameManager.lua"]:215: in function <Interface/FrameXML/PlayerInteractionFrameManager.lua:212>

Locals: (*temporary) = <function> defined =[C]:-1


Steps
Go to Silithus > Heart of Azeroth
Click on Heart Forge
error comes up

**Comment by kodewdle** [comment]
fix up in dev branch, closing
