### ISSUE TITLE
[Retail Bug Report] "Show Pet in Journal" option is missing

### ISSUE THREAD

**Issue by lucastws** [tukui-org/ElvUI#98]
### What is the issue you are having?

I love pet battles and I always prepare my comp before the battle by looking at the pet info in Collectables after selecting it, right clicking the pet frame and choosing the option "Show Pet in Journal". For some reason, **this option is missing when using ElvUI**.

I'm currently using version 12.57 and I already tried Googling this problem and I actually found [a topic on Tukui Forum about it](https://www.tukui.org/forum/viewtopic.php?f=5&t=13975) but there is no answer at all. I also found [a guy asking about it on Discord too](https://discord.com/channels/209244641537556480/222356141785612288/799262808696422411) and, once again, there is no answer - with a solution - for him too (except for an another guy telling him to come here and open an issue about it - which is literally what i'm doing right now).

I attached two images: one showing what option I'm talking about on Blizzard's default layout and another one with ElvUI activated excluding this option. My game's language is set to brazilian portuguese but I believe that's understandable enough to get my point.

If there is already a solution out there, I want to apologize for opening this issue and I'd really appreciate if somebody show me how to fix it/a workaround.

Thanks in advance.

### What is the expected behavior?

After selecting a battle pet and right clicking on its frame, it was supposed to have an option saying "Show Pet in Journal" (which is "Exibir Mascote no diário" in portuguese).

![1](https://user-images.githubusercontent.com/49876399/144079381-55d46212-f7e6-45be-b0a1-f55ed99cb6ec.jpg)

### What actually happened?

After selecting a battle pet and right clicking on its frame, it shows all designed options except "Show Pet in Journal" (which is "Exibir Mascote no diário" in portuguese).

![2](https://user-images.githubusercontent.com/49876399/144079405-5c84792f-b0ae-4444-a654-94e420177ce6.jpg)

### ElvUI Changelog/Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog) and done the [Troubelshooting Steps](https://www.tukui.org/forum/viewtopic.php?p=28#p28).

**Comment by kodewdle** [comment]
![Wow_2021-12-01_09-47-14](https://user-images.githubusercontent.com/2266754/144256086-9ea69dca-8103-47cc-a821-559711a79da8.png)

for me this is working.  i checked in the code and the "Show Pet in Journal" only appears for other players battle pets (not your own)

**Comment by lucastws** [comment]
> ![Wow_2021-12-01_09-47-14](https://user-images.githubusercontent.com/2266754/144256086-9ea69dca-8103-47cc-a821-559711a79da8.png)
> 
> for me this is working. i checked in the code and the "Show Pet in Journal" only appears for other players battle pets (not your own)

You're right, I tested with other player's pet and the option really is there.

![image](https://user-images.githubusercontent.com/49876399/144320473-fc0cbcdb-07b1-4375-a435-62d1a1d6a7a6.png)

But the problem remains: **the option is still missing on wild and dungeon pets (bosses and normals)**. I don't know if it was intended to be this way but that option is way more useful - to me - in this scenary than for just looking at other people's pet. For example, testing it after your comment was the first time I ever clicked in other player's pet.

![image](https://user-images.githubusercontent.com/49876399/144322457-50383f6d-9ad1-49d0-a6dd-ca56101c08de.png)

![image](https://user-images.githubusercontent.com/49876399/144322489-aac4a93a-72b9-400a-b0c4-72a8a1d3b546.png)
