### ISSUE TITLE
Action bars and visibility state while using [advflyable]

### ISSUE THREAD

**Issue by AphelionZero** [tukui-org/ElvUI#984]
### What is the issue you are having?

The action bar visibility state condition [advflyable] causes action bars to remain invisible even when Global fade logic would dictate otherwise. Example: pressing F1 to target self should show action bars, yet with [advflyable] in the visibility state box it doesn't work. 

### What is the expected behavior?

The action bars to remain invisible while on a Dragonflight mount yet retain the global fade rules.

### What actually happened?

Having the [advflyable] seems to interrupt the global fade rules and the bars remain invisible.

### Suggested Solution/Workaround

I wouldn't know where to start.

### Errors

```shell
No errors are thrown.
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://www.tukui.org/download.php?ui=elvui&changelog).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
There is a bug in general with Inherit Global Fade while on the dragonriding mount, which is prob part of your issue.

Another issue seems your understanding (at least it appears to me that way but could be mistaken) of how the visibility box + inherit global fade works.  While they both technically work together, the way they work together may come off as confusing.

The Inherit Global Fade "triggers" that determine if the bar should/can be shown takes priority over the visibility option for the bar.  First it checks if one of the inherit global fade triggers are true and allows the bar to be visible and is typically shown if nothing is set in the visibility box which it then looks at the visibility option and that would determine if the bar is visible or not.  

Using the macro conditional `[group:raid] show;hide` as an example, which it will check if you are in a raid group and if true, it will show the bar, if not true, it will hide the bar.
So having both options set, visibility set to the example conditional above and having the Inherit Global Fade option enabled on the bar, one of the triggers for Inherit Global Fade has to be true, like targeting something, casting something, you are in combat, just to name a few then it will check the visibility option for the bar and determine if it should show or not based on its contents which in the example, if you are in a raid group or not.


https://github.com/tukui-org/ElvUI/assets/1479745/b4378af4-7da0-4aaf-a97e-39dc0df52e85

Example of the current known bug that I was referring to which is probably part of your issue.

**Comment by AphelionZero** [comment]
Perhaps I needed to be clearer as I feel I have a good understanding of Global Fade
I add [advflyable] to the visibility state box to hide a bar while on a dragonriding mount, however, once I dismount, and target something (for example) the bar remains hidden. This is what I meant when I say [advflyable] stops the triggers from working.

**Comment by Repooc** [comment]
I think I understood you but regardless of the outcome as there is a bug, it appears that you didn't understand what I was saying about the macro conditional from my message.  Using `[advflyable]` does not check if you are on a dragonriding mount, it checks if you are able to mount on a dragonriding mount in the area you are in, not if you are on one or not is what I am saying. The condition you would want to use to see if you are on a mount or not would be `[bonusbar:5]`.  I'll show the difference between the 2 without Inherit Global Fade as I know there is bug with it atm when it comes to dragonriding in general.

Example `[advflyable] hide; show` hides when condition (if the area is mountable on a dragonriding mount) is true else hide
https://github.com/tukui-org/ElvUI/assets/1479745/63fa0bf2-2bf7-4276-b58c-3de7395f2016


Example `[bonusbar:5] hide; show` hides when condition (if you are on a dragonriding mount) is true else hide
https://github.com/tukui-org/ElvUI/assets/1479745/5cb20f56-90a5-43f9-8ad1-26daeb7c62c7

With Inherit Global Fade which keeps the bar hidden until you are dismounted from the dragonriding mount and have fullfilled a condition of Inherit Global Fade to show the bar, which sounds like what you want.
https://github.com/tukui-org/ElvUI/assets/1479745/d44b1530-71de-4153-9799-c234be97c788

**Comment by Repooc** [comment]
Hopefully that clears up what I was trying to explain about the conditional you were trying to use vs what should be used to determine if you are ON the dragonriding mount or not vs if you CAN be on the dragonriding mount or not

**Comment by AphelionZero** [comment]
Ohhhhh okay, I think I understand now. Thank you very much for taking the time to explain this. I really appreciate the videos you made as it was instrumental in clearing up the confusion.
