### ISSUE TITLE
[Retail Bug Report] "ADDON_ACTION_FORBIDDEN" - 'ElvUI' tried to call the protected function 'OnOpen()'

### ISSUE THREAD

**Issue by RealHawkBat** [tukui-org/ElvUI#989]
### What is the issue you are having?

When I access the Dungeon Journal for Aberrus raid, and I check the loot tab for the Raid, the BugSack addon detects the bug:

[ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.

### What is the expected behavior?

This bug should not occur and should not trigger BugSack.

Other that the error appearing in BugSack, there doesn't appear to be any other observable unexpected behavior.

### What actually happened?

The BugSack addon detects the bug:

[ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.

Other that the error appearing in BugSack, there doesn't appear to be any other observable unexpected behavior.

I tried again by disabling every addon I had EXCEPT ElvUI and BugSack/BugGrabber, and the error occurred.

I then disabled ElvUI so the ONLY addons I had active were BugSack/BugGrabber, and the error DID NOT occur.

### Suggested Solution/Workaround

I have tried using the "/edebug on" command. However, as the bug is only picked up by the BugSack addon and there isn't any  other observable unexpected behavior, I cannot tell if the issue pesists when using the "/edebug on" command.

### Errors

```shell
25x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:587: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:576>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2943: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2786: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2651: in function <FrameXML/UIParent.lua:2647>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3253: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3214: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1150: in function `ToggleEncounterJournal'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1162: in function <FrameXML/MainMenuBarMicroButtons.lua:1160>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
This is a taint, you can read more about taints here https://github.com/tukui-org/ElvUI/wiki/errors

**Comment by Ghostamoose** [comment]
> This is a taint, you can read more about taints here https://github.com/tukui-org/ElvUI/wiki/errors

This taint issue is related to https://github.com/Stanzilla/WoWUIBugs/issues/434

**Comment by hawkbat8** [comment]
Just an update:

- I tried again by disabling every addon I had EXCEPT ElvUI and BugSack/BugGrabber, and the error occurred.
- I then disabled ElvUI so the ONLY addons I had active were BugSack/BugGrabber, and the DID NOT error occur.

**Comment by Luckyone961** [comment]
Should be fixed in 13.40+, if this is still an issue feel free to re-open the ticket

**Comment by RealHawkBat** [comment]
Hello, this issue is still occurring. I'm using ElvUI v13.40. The error is as follows:

25x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:587: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:576>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2943: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2786: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2651: in function <FrameXML/UIParent.lua:2647>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3253: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:3214: in function `ToggleFrame'
[string "@FrameXML/UIParent.lua"]:1150: in function `ToggleEncounterJournal'
[string "@FrameXML/MainMenuBarMicroButtons.lua"]:1162: in function <FrameXML/MainMenuBarMicroButtons.lua:1160>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by Typowow** [comment]
Similar error but different protected function on LFG

1x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML/LFGList.lua"]:3543: in function <FrameXML/LFGList.lua:3532>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML/LFGList.lua"]:2603: in function <FrameXML/LFGList.lua:2600>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}
