### ISSUE TITLE
[Feature Request] Need a more detailed documentation

### ISSUE THREAD

**Issue by ZhengYuan-Public** [tukui-org/ElvUI#991]
**Is your feature request related to a problem? Please describe.**
I want to customize the font size of a particular element. The wiki [custom-texts](https://github.com/tukui-org/ElvUI/wiki/custom-texts) showed a general way of how, but I can't find any documentation about all supported tags.

**Describe the solution you'd like**
I just need a full list of detailed supported tags.

**Comment by 1Botanica1** [comment]
In game 
ElvUI - Available Tags 

Has the list of tags and their descriptions

**Comment by Repooc** [comment]
Updated the page to say this as well.
