### ISSUE TITLE
No anchor on ElvUI to move chat window, covering up cast bars

### ISSUE THREAD

**Issue by Chickenshet** [tukui-org/ElvUI#994]
### What is the issue you are having?

There used to be an anchor to move the chat bar when NPCs talk but now there is none and it's covering parts of my spell bars and it's really annoying 

### What is the expected behavior?

Fixed 

### What actually happened?

Chat covering bars

### Errors

```shell
-
```

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [X] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by 1Botanica1** [comment]
That is controlled/moved by blizzard edit/ move
