### ISSUE TITLE
[Retail Bug Report] Crafting order window is missing the "arrow" to go back to the previous window

### ISSUE THREAD

**Issue by Danycm1** [tukui-org/ElvUI#995]
### What is the issue you are having?

Crafting order window is missing the "arrow" to go back to the previous window, we instead get an empty square that is misaligned

### What is the expected behavior?

They should be an arrow "<" that shows you can go back

### What actually happened?

Currently we only have a empty square, under the white circle you can see the square where the "back arrow" should be(clicking the empty square does work, you go back to the previous window)

![image](https://github.com/tukui-org/ElvUI/assets/86419755/d9cec7cd-304f-47a6-b962-474323a57643)

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
i am not sure what arrow you are talking about but i would do `/edebug on` and test

https://github.com/tukui-org/ElvUI/assets/1479745/30810481-194d-434c-9e45-742a2b89253a

video of no skins from elvui on the frame as an example of not seeing what you are referring to at the moment (which what i show in the video works the same with elvui skin enabled)

**Comment by Danycm1** [comment]
Hello, here's a video of what i'm talking about(I had to stay under 10MB to upload to github bear this in mind)
I show the square with /edebug on and then with default UI

https://github.com/tukui-org/ElvUI/assets/86419755/bba379c5-6643-4375-972e-85f3873b0407

**Comment by Repooc** [comment]
ahhh ok. ill take another look then. thanks for the video

**Comment by Repooc** [comment]
can you show `/estatus` window... idk if my engineering and enchanting doesnt have that button or what but i cant seem to reproduce what you have in your video as i dont have a tailor atm

**Comment by Danycm1** [comment]
I have leatherworking & tailoring
![image](https://github.com/tukui-org/ElvUI/assets/86419755/b71ef5de-b36b-4211-86be-8740e07124af)

**Comment by Repooc** [comment]
ok maybe ill get one of the other devs to look if they have the profession to double check

**Comment by Danycm1** [comment]
Hi, here you go
![image](https://github.com/tukui-org/ElvUI/assets/86419755/e4ad85a6-6ca4-4af3-9c14-3ee818df72b1)

**Comment by Repooc** [comment]
99f18f1fb10d61bb42054c540d0d71aab79bc2c3 should fix your issue when its released (or if you try the development branch)

**Comment by Merathilis** [comment]
> [99f18f1](https://github.com/tukui-org/ElvUI/commit/99f18f1fb10d61bb42054c540d0d71aab79bc2c3) should fix your issue when its released (or if you try the development branch)

You need coffee? I have one :>

**Comment by Repooc** [comment]
yes 📦

**Comment by Danycm1** [comment]
I added your patch manually but it seems like it's not working(unless there's a prior commit I need?)
![image](https://github.com/tukui-org/ElvUI/assets/86419755/7fe98c8c-d2d8-4f7d-aa71-21be69e0fb27)

**Comment by kodewdle** [comment]
you keep posting with other stuff enabled.  sorry but closing this, please read the steps.

**Comment by Danycm1** [comment]
> you keep posting with other stuff enabled. sorry but closing this, please read the steps.

It was tested with and without stuff enabled, I posted screenshot with other enabled as I was redoing my UI, sorry for that. Here is another screen with 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' + /edebug on activated.

![image](https://github.com/tukui-org/ElvUI/assets/86419755/c58f02f1-8f82-4058-918c-68219d292f94)
with /fstack
![image](https://github.com/tukui-org/ElvUI/assets/86419755/28c3d595-b277-4d66-84e7-9c1d05e7ef46)

**Comment by kodewdle** [comment]
thanks - it helps a lot to do those steps; so we can have a better idea of where to look, it gets messy and confusing otherwise!

anyways, it should be fixed by: f37e14fdb0e365bd5f3a68205432d36196e68781
