### ISSUE TITLE
[Feature Request] Difficultycolor Tag

### ISSUE THREAD

**Issue by lgrano** [tukui-org/ElvUI#996]
**Is your feature request related to a problem? Please describe.**
The difficultycolor tag uses dark gray as its default color for low level, bosses and unknown or undefined enemies. If you are using a dark color on your unitframes it becomes difficult to see it. Since i have poor vision my UI is usually black/white for high contrast.  There used to be custom colors defined by Elvui but it was changed in version 11.42 ( July 8th 2020 ) as indicates this line on the changelog:
>Swapped **\[difficultycolor\]** to use Blizzard's **Creature Difficulty Color** instead of our custom coloring.

**Describe the solution you'd like**
Its a Accessibility issue that could  be resolved by letting  users change the difficultycolors tag either to custom colors or make the current color a lighter shade of gray. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Repooc** [comment]
we dont really give tags options... your best bet is to use the addon TinkerToolbox to create your own version of the tag and name it something like lgranodifficultycolor and you can use our code for the tag as a reference to help you make it and make adjustments as needed.

![image](https://github.com/tukui-org/ElvUI/assets/1479745/0b752464-2e7c-46a0-94e2-02262b61d578)

https://github.com/Gethe/wow-ui-source/blob/e8693cc8bc1f4ca2391216badfcf63290328aefd/Interface/FrameXML/UIParent.lua#L4646
is good reference to blizzards code on the returns and such... might be a bit over your head, idk what your coding experience is like.
