### ISSUE TITLE
13.34 "Global Fade now works properly while Dragonriding, various Hide issues are now resolved" - Actionbars still shown

### ISSUE THREAD

**Issue by XBlueBobX** [tukui-org/ElvUI#997]
### What is the issue you are having?

Using inherit global fade on actionbars is not hiding them whilst dragonriding. When using any other mount they do indeed inherit global fade and hide. All addons disabled bar Elvui.
![ELVUI](https://github.com/tukui-org/ElvUI/assets/41550031/70deac8f-573f-4725-879e-d3fb177d612a)

### What is the expected behavior?

Select ActionBars>Player Bars>Inherit Global Fade

Action bars will be hidden when dragonriding

### What actually happened?

Select ActionBars>Player Bars>Inherit Global Fade

Action bars are still displayed when dragonriding

### ElvUI Changelog & Troubleshooting

- [X] I have confirmed that I have read the [Changelog](https://github.com/tukui-org/ElvUI/blob/development/CHANGELOG.md).
- [X] I have verfied ElvUI is up to date by checking /estatus.
- [X] I have verfied my issue doesn't exist in the ElvUI Issue Tracker.
- [ ] I have not read step six and I am just clicking all boxes.
- [X] I have verfied my issue doesn't exist in the default UI.
- [X] I have disabled all addons except the three called 'ElvUI', 'ElvUI Libraries', and 'ElvUI Options' by using `/edebug on`? This is important in order to rule out that any of your other addons are causing the issue. If you manage to pinpoint a conflict between ElvUI and another addon, make sure you include that information.

**Comment by Repooc** [comment]
This is working as intended actually, we are treating it like any other vehicle that has a bar with abilities on it.  I am the author of actionbar buddy, maybe I will add an option to ignore dragon riding to get the outcome you are wanting with my plugin installed.  Note: Don't install it now thinking I have added that as an option as I have not done so yet, just an idea I thought of while responding to you.

**Comment by XBlueBobX** [comment]
Hi, It seems to be a little more complicated than that. It does inherit global fade on login (see attached). I am on a dragonriging mount and when I fly it remains hidden and shows with target/mouseover. As soon as I land then remount it always shows. 
![Hoden](https://github.com/tukui-org/ElvUI/assets/41550031/23b54611-4454-4b9c-860f-1ec2e833b4a9)
![Target](https://github.com/tukui-org/ElvUI/assets/41550031/43c159cf-7fd9-4d6e-9f1e-96ef66019e39)

So the functionality does seem to be there and was working previously afaik. Is this not a bug or a feature request?

**Comment by XBlueBobX** [comment]
Actually going back to 13.31 fixes the issue. I can now mount dragonriding and it inherits global fade all the time - but you dso need to click player frame then exit for it to work.  Can you please reopen this bug? At least I can stick with 13.31 as its been annoying me since I updated :)

**Comment by Repooc** [comment]
i have not been able to reproduce the on login picture yet, if the bars option is to have inherit global fade enabled, the bars are NOT to hide when on the dragon riding mount, so tech the first picture is not working as intended. The second picture is tech intended.

**Comment by Repooc** [comment]
reproduce the issue upon initial login while on the mount. will investigate it and get it fixed by one of us

**Comment by Repooc** [comment]
7eee2e378cd42d219ec10a48178117064d859c53 makes sure it follows dragonriding upon initial login now

**Comment by XBlueBobX** [comment]
!E1!fN16UjUss4xL9bGSY3bYkTsabsYUjal2ZiD2rJhAmn4(eJBV2nzcZp4zFRQBBJXCZz15OvJ0eC7QQUU811L2(6(E(UljcYcsAg(B6hj0ugnoGIpXXFkicgp239RdN598GEV47gszRdf(J17O57(t2sri8BnFb8gEmp9)jotPjBZPhvJyYIiQF)ACCbPEKGi)cmaX1u)CHV4kQdiN10yAkjcLtMGf82UrPKn0mKnYwbVxqanr8C874E1xT2mAcHL67o9LE)2WzWAlxYJhW3KqsfBanbL1kukUIuWN772V3G)5JZM8LXpi18iXu(pPP9jsxyHYzc62kESWL9lQ)yJ8NMSveXIP(UJNmEiY9csWBlt5jRilPb8ivyyH)yT)QMTfyoL)kT4xatVtI2EGAjn26M581rVlstW2mbFZJr8FQ8f7aFNBVa0RUFE)Tcb(x5RbI)pBPBbZJi2kHtzbeGAqww21m9NE(XNYx6f670i)Xwwkh)g(7ufy0JNmaCB00bGbtaRn9v8DWlMmT1xEEkjfEBl8b9w3zcQTxykLia)xoD9N45n51dKM)SrhJwMMT9Dhg9(xg9JPrKDWEqYelQZjsqnMVZOTwltB9cUhXbhKhjDnvCq7MbwN3rQOAL7m6y26oRoD9DF81dK)YWrEhTxfRz54aKdQZ2vRYQl(AmuSd6wkwiRZUUBW0YSLbex6ZZYuXXZ5z1aXP32W39foxipd0a92wVlWLjOg)BEmT3cwetS7ms30aJCOsKhkkDIkDukSA6D(gabHowhhcBySZPtbBhf2UmB14AgHTmPA0(e3qff1Qv7dinKtZtnWlYQHg4zaFsV(xglBB3YWP9rOXgGdTmrCyxn8qMGUP(rMl737Q1s30(yhytp6i9Jwk)yV()OtbT10YQlENLr3wgwGE(kliLxFxo9GqnM70YcnrEKGL0ChVDxKTVsdzbruxiLsdG8o6YJDktZ5AUbniObemSSu7z9(xs3mK6wEoRqolG6XxVgZjxOjNOAgqq7oZ2TpoQDgW)TCN25h66PQXwxVVf7qsbDK9xGeoyk9uEuLe61CQGB6oDmnRhpDDiGWo2yVWXH7mAz1gCUUHSvvo2Cr8SJMdKesR6bu9MDsapDwcL1Vr8UJtbLgn1zPeFFkuy9vwmBdj5mvbVwHath4iUHLr(rCVuObH65ipX9zAz0s3bkp5rIEJfV(jkzztt6BLNYxzO2x3LyQdUKEh645wabZc5AEdxTbi3zLnt(PHOTRCY)fk5DArLXgXVTgKTcRUdumEAZllzchQnWdwPc2ksWjTWCl12Wgv7jl(Dk0x270ArSRHsKGeDevoEOxZybRzBycU5Vo55bdh8upVRJl62P1DDlJFwn1MuP9FcNO4tLGufc7bRtq0BtpUyHnIOxEGwRrfNWsAhYQg)wt7jWb7wf776ZQHM5B3Zq7DFkeslB7cBRDJmnDOVcJYUCbse7AEmasEHXGiA6zBz8eiIQFrmVZd0fFYED1Tldb9YYyznUXm726Y5B4Xa9IPK1W0DqfJGqICsTTz0bYrF8yBOdKZibZ(LqIPrdA48vG03gZeYPCKd)voghEIdFLCohbGCQm1lSllzz4pFLdkbAnYXR6JYtiRAx9)LJWFr6Xzp3DDswH9mEDsish71PjfQDAGKeVDZJP8Tjz(J7uk)d66Hz7VGSkNehdSLtbdqXavFMOqQqI0nNCv)W540mNZfWPWB4cBONwMShP50DZqtD3eBtj5VOmwJoimhWXUMnS4ErjHealjJ6YbBDvZElN43nblCkrp0pe)yfpDdaBD)MCz5e9F)B7NVF(FxUW9bBtXdaFhf2nC7OU6gNJypw44Q5Yg)59BOlzB3899Z)2s2QvSGTrID5VpBda8IWj7XxNfYtfbrimcitwz(7k3pIA0pb14IjbEoEjsl)e)LuqNXpw6sQU41bSxh3u782noJGvCU9reZMSFinHuseepGF9XeiJiS447GQg7kFqVZvWuNbXOUihpiIkb8Zafg)lbSUGqCzpUVRmDDvK4XiGAXqeHDP)9nLkKJhupCpmYtGehw1o0vzgHPA82p3LeNTF(ysAk4sC)DqNzR29KV7GHJ9Wlv70l)QQ)bGUzfjyf))bSlrOhYauKadRLEu2aHk345TBPGLHjm(c9)G3ae(OSIJEE9g98Qn6f7zLctJSSH(6C06Ozy2UB72D9xDh2dWA)rDSHx0XX02YQJwBqzG3yIIAKTLzxhyonnyIft9UTX3iVOWdGXlQaIlCXK41llkaDYYNk4h6wga1AFaE)uCzy1X48Eq5wWhbt8dXl8AtHeW0LykXLlrWCTLJORe5mb)9f4PtekyBU7YGzGaTvgmkEmpiqKxMzE8c(J8ikloehYfWllirJGm0iQzHCyGSP00zquswfpjLVIcNj4X)RTe51C5v5Epnr5NZvXnud7GZHJRlr5ETntYwd2gLKbA9QWQz(YDQTHLe0il4QavE0s(pL3ApE(kLTmpd0M8lS587CHl0q2O1ZbOYizd6uqDLixkia0SU858IK6sJ0O2wLWzOsx0VydTu0j63iIBsyJSgMIg58HHVoz8tFrLedz(DwgR4Ir)guhAbKioIcjqcbx4FB)COM5p3)pY1iBPgvApyhSFAastH0QDSDfCu5lB02CqTYf1uvbTAcZ(IHxGfRggboZbYIpeIeojuz3HEZeuzANqibqKmjWIkDGpA2Zdh)Wl)2pY)0nEhkkCM6nvAJ3gJkzm1NyQOevzPnvfAmq6XefFYPIePLF8jtvLNBVzMfjS86n7XHEidY6X177PVIQsJA80bfw0K4ODOA8hH1ziZMjl71erjQA8nZGTlm4HJh(APDSunIOemu(nXk1Q2i9NP(B(Nze6atDXNh1D5hh1mIsQ4vzDW6vzqajqbGOmFvnh(FGU0ZGrA)5CznmQyOv19Ea7Foa1FU2N9FE2NBY7jSZmkr)IaTJvovh3C755jhqEO)S6TD1XgAQsRl0GvBl4VoQwOW2LKnlnQTMJLf8F2oMDS1mCuTLPeAel4nVqykO1sVZk8ZdSeoWk9)y11isYtGGW(UYF8RGvcPcDxXIe5F20X89ZXG1(5hs7jGgFwN)(JZs88Mey2mI6RtFzYgb(MWvP8mX(5dHUDdZcjj5dGErM(smuBF5(5JyzH7NJ311fOppvThjEnejxVFE)i(MBQqOj6gYdEdAhHd61KyO77RY0WpsIa0570Rt20u2gs0NWqvPue0lzFf4gXXnmPg2Rh0HFUhW)(7XIESi693)qkznpELSy1F5vYh)3)

**Comment by XBlueBobX** [comment]
This is my set up. If its not being fixed i can just stay on older version. Thanks for checking

**Comment by Repooc** [comment]
> This is my set up. If its not being fixed i can just stay on older version. Thanks for checking

what not being fixed? you mean, you want the bars to hide when on the mount? if that is what you want, it is not broken.  we wont support outdated versions of elvui.  i did however update my plugin ElvUI ActionBarBuddy so you can pick and choose what "events" inherit global fade trigger on.  you can use that to remove the dragonriding option to it will hide the bars while you are on your dragonriding mount.

**Comment by XBlueBobX** [comment]
Sorry if any offense taken there, figured it was a regression from previous version. Ill get that plugin, cheers again

**Comment by Repooc** [comment]
> gin, cheers a

no offense taken, think just a miscommunication is all.  yeah my plugin will make it so you can uncheck the triggers you dont want to effect the bars.  so in your case, if you were to uncheck dragonriding then the bars wont show when you mount ur dragonriding mount which is what it sounds like.  if you have questions/issues with the plugin, just make sure to post on the github for that project.  I dont have a specific discord for that plugin, which you could reach out on the Shadow & Light discord if you rather have more of "live" chat if help is needed

**Comment by XBlueBobX** [comment]
I got it and its working perfectly. Very handy and many thanks again!
